Repository gitpod-io/gitpod, pull requests merged in 2021-08, with the labels that each got.

#5001 [dashboard] add regular workspaces to list only
  components/dashboard/src/workspaces/workspace-model.ts
Labels: approved, component: dashboard, lgtm, size/XS

#5032 [gpctl] Support batch-building workspace images
  dev/gpctl/cmd/imagebuilds-build-batch.go
  dev/gpctl/cmd/imagebuilds-build.go
Labels: approved, lgtm, size/L

#5039 Fix bug in github-app.ts
  components/server/ee/src/prebuilds/github-app.ts
Labels: approved, lgtm, size/S

#5044 Update Getting Started links
  README.md
Labels: approved, lgtm, size/XS

#4966 [dashboard] Allow Projects for Individuals
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/service/service-mock.ts
  components/dashboard/src/teams/JoinTeam.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/migration/1627287775965-UserProjects.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/ee/src/prebuilds/github-app.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, component: dashboard, lgtm, size/XL, 🧑‍🚀 crew: teams and projects

#5056 [prow] Add new team member
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#5051 [supervisor] Reword upload message
  components/supervisor/pkg/supervisor/tasks.go
Labels: approved, lgtm, size/XS

#5058 [server] Allow workspace restarts with base image from private repo
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/XS

#4985 [dashboard] Don't show "xh left" hints for installations with payment disabled (e.g., Self-Hosted)
  components/dashboard/src/settings/Plans.tsx
Labels: approved, lgtm, size/XS

#5049 Update authorization step layout in onboarding flow
  components/dashboard/src/icons/NoAccess.svg
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, component: dashboard, lgtm, size/S, user experience, 🧑‍🚀 crew: teams and projects

#5074 Update right menu style
  components/dashboard/src/components/PillMenuItem.tsx
Labels: user experience, component: dashboard, type: improvement, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5054 [Projects] Fix prebuild association
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/ee/src/prebuilds/github-app.ts
Labels: type: bug, component: dashboard, feature: prebuilds, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/M

#4868 [dashboard] Add invite members button on projects page
  components/dashboard/src/projects/Projects.tsx
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5081 [content-service] Fix error check expression
  components/content-service/pkg/service/workspace-service.go
Labels: approved, lgtm, size/XS

#5082 [ws-daemon] Add more details when is not possible to update CPU limits
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/XS

#5085 Support combining SSDs into a raid
  chart/templates/ws-daemon-daemonset.yaml
  chart/values.yaml
Labels: approved, lgtm, size/M

#5077 [dashboard] Fix Teams & Projects top-level menu UX
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/ContextMenu.tsx
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/S

#5055 fix(workspace): force-stop workspaces stuck in a bad state
  chart/templates/ws-manager-bridge-configmap.yaml
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/main.ts
  components/ws-manager-bridge/src/meta-instance-controller.ts
Labels: approved, size/L, lgtm

#5093 Align invite members button on the team page
  components/dashboard/src/projects/Projects.tsx
Labels: type: bug, user experience, component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5094 [ws-manager-bridge] Set stopping/stopped time
  components/ws-manager-bridge/src/meta-instance-controller.ts
Labels: approved, lgtm, size/S

#5096 [ws-daemon] Don't include first SSD in the raid
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS

#5100 [supervisor] Correctly reap child processes
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/M

#5108 [supervisor] fix #5104: don't truncate env values after `=` char
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
Labels: approved, size/L, lgtm

#5097 [agent-smith] Support CPU limit penalties
  chart/templates/agent-smith-configmap.yaml
  chart/templates/agent-smith-role.yaml
  components/common-go/kubernetes/kubernetes.go
  components/ee/agent-smith/go.mod
  components/ee/agent-smith/go.sum
  components/ee/agent-smith/pkg/agent/actions.go
  components/ee/agent-smith/pkg/agent/agent.go
  components/ee/agent-smith/pkg/agent/config.go
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
Labels: approved, size/L, lgtm

#5111 [dashboard] Don't list deleted user projects
  components/gitpod-db/src/typeorm/project-db-impl.ts
Labels: approved, lgtm, size/XS

#5101 [gitpod-db] Fix invalid table name in query
  components/gitpod-db/src/periodic-deleter.ts
Labels: approved, lgtm, size/XS

#5131 [dashboard] Disallow team names that might conflict with dashboard URLs
  components/dashboard/src/teams/NewTeam.tsx
  components/gitpod-db/package.json
  components/gitpod-db/src/the-big-username-blocklist.d.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  yarn.lock
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/M

#5136 revert 7826291
  chart/templates/server-deployment.yaml
  chart/values.yaml
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/S

#5112 Update projects empty state
  components/dashboard/src/FromReferrer.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/Setup.tsx
  components/dashboard/src/index.css
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/settings/EnvironmentVariables.tsx
  components/dashboard/src/settings/Integrations.tsx
  components/dashboard/src/settings/Teams.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/M

#5127 [server] Add support for typescript map
  components/server/src/main.ts
Labels: approved, lgtm, size/XS

#5140 [workspacekit] Remove debug log to avoid confusing message
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/XS

#5143 [ws-daemon] Improve path concatenation
  components/ws-daemon/pkg/content/tar.go
Labels: approved, lgtm, size/XS

#5152 [content-service] Don't filter blobs during clone
  components/content-service/pkg/git/git.go
Labels: approved, lgtm, size/XS

#5153 [ws-daemon] Remove Containerd4214 workaround
  components/ws-daemon/pkg/daemon/containerd4214.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: approved, size/L, lgtm

#5117 [ws-daemon] Collect logs from runc command
  components/common-go/log/log.go
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/iws/iws.go
Labels: approved, lgtm, size/M

#5167 disable userfaultfd for all unprivileged users
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, do-not-merge/hold, size/XS

#5169 fix(chart/templates): missing AND
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS

#5166 [gpctl] Throttle image builds
  dev/gpctl/cmd/imagebuilds-build-batch.go
Labels: approved, lgtm, size/XS

#5170 [server] Free private repos
  components/dashboard/src/settings/Plans.tsx
  components/server/ee/src/user/eligibility-service.ts
Labels: approved, lgtm, size/M

#5161 Do not upload ghost workspace logs and skip backups
  components/ws-daemon/pkg/content/service.go
  components/ws-manager/pkg/manager/monitor.go
Labels: approved, lgtm, size/S

#5184 [workspace]: add force-stop check on stopping workspaces
  chart/templates/ws-manager-bridge-configmap.yaml
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/meta-instance-controller.ts
Labels: approved, lgtm, size/S

#5162 [agent-smith] Do not log errors for processes not running
  components/ee/agent-smith/pkg/agent/agent.go
Labels: approved, lgtm, size/XS

#5189 [payment] don't rely on VERSION env var
  components/gitpod-protocol/src/env.ts
  components/server/src/env.ts
Labels: groundwork: scheduled, approved, lgtm, size/XS

#5208 moved deployment to new cluster
  .werft/build.ts
  .werft/certs/cert/versions.tf
  .werft/certs/versions.tf
  .werft/util/certs.ts
Labels: approved, lgtm, size/S

#5221 [ws-daemon] Refactor containerd error handling
  chart/templates/ws-daemon-daemonset.yaml
  components/ws-daemon/pkg/container/container.go
  components/ws-daemon/pkg/container/containerd.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: approved, lgtm, size/M

#5200 Remove repeated command shortname from gpctl
  dev/gpctl/cmd/imagebuilds-build-batch.go
Labels: approved, lgtm, size/XS

#5234 [ws-man-bridge] don't update stopped workspaces
  components/ws-manager-bridge/src/bridge.ts
Labels: approved, lgtm, size/S

#5229 [ws-daemon] Check for workspace state
  components/ws-daemon/pkg/dispatch/dispatch.go
Labels: approved, lgtm, size/S

#5147 Revert the revert of "[ide] added VS Code "Insiders" IDE variant"
  chart/templates/server-deployment.yaml
  chart/values.yaml
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/M

#5220 [analytics] group rendered events by session
  components/dashboard/package.json
  components/dashboard/src/start/StartWorkspace.tsx
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/loading-frame.ts
  yarn.lock
Labels: approved, lgtm, size/M

#5242 [supervisor] Fix segfault in supervisor.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS

#5241 [blobserve] Catch panic in HTTP requests
  components/blobserve/pkg/blobserve/blobserve.go
Labels: approved, lgtm, size/S

#5230 [werft] Update sweeper to use new cluster credentials
  .werft/wipe-devstaging.yaml
Labels: approved, lgtm, size/XS

#5248 feat: add wrapping for contextUrl
  components/dashboard/src/start/CreateWorkspace.tsx
Labels: community-contribution, component: dashboard, approved, lgtm, size/XS

#5255 [ws-daemon] Try stay alive long enough (<= 100s) until containerd is back online
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS

#5259 [dev] Push RAM requests in preview envs
  .werft/values.dev.yaml
Labels: approved, lgtm, size/M

#5218 open task terminal in correct workspace location
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/terminal/service.go
  components/supervisor/pkg/terminal/terminal_test.go
Labels: approved, size/L, lgtm

#5113 [projects] allow only github.com and gitlab.com
  components/dashboard/src/projects/NewProject.tsx
Labels: 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5270 Update error messages
  components/image-builder/pkg/builder/builder.go
Labels: community-contribution, approved, lgtm, size/XS

#5289 [server] don't always throw exception in deleteUser
  components/server/ee/src/user/user-deletion-service.ts
Labels: approved, lgtm, size/XS

#5293 [supervisor] Remove misleading error message
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS

#5120 Import GitLab projects
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/server/ee/src/container-module.ts
  components/server/ee/src/github/github-app-support.ts
  components/server/ee/src/gitlab/gitlab-app-support.ts
  components/server/ee/src/prebuilds/github-app.ts
  components/server/ee/src/prebuilds/gitlab-app.ts
  components/server/ee/src/prebuilds/gitlab-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/gitlab/api.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/server/src/projects/projects-service.ts
  yarn.lock
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XXL

#5239 removed fntlnz from code owners
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#5295 [supervisor] Close docker unix socket on termination
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS

#5298 [supervisor] Refactor supervisor exit to allow defer execution
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/S

#5302 Extra `and` in subtitle
  components/dashboard/src/settings/Teams.tsx
Labels: approved, lgtm, size/XS

#5291 Update long description in messagebus
  components/service-waiter/cmd/messagebus.go
Labels: approved, lgtm, size/XS

#5294 [ws-manager] Ensure status before setting phase tag
  components/ws-manager/pkg/manager/manager.go
Labels: approved, lgtm, size/XS

#5296 [workspacekit] Close lift unix socket on termination
  components/workspacekit/cmd/rings.go
  components/workspacekit/pkg/lift/lift.go
Labels: approved, lgtm, size/S

#5257 [workspace]: update logs
  chart/templates/ws-manager-bridge-configmap.yaml
  components/ws-manager-bridge/src/meta-instance-controller.ts
Labels: approved, lgtm, size/S

#5325 [ws-daemon] remove failed backups
  components/ws-daemon/pkg/content/archive.go
  components/ws-daemon/pkg/content/archive_test.go
Labels: approved, lgtm, size/S

#4655 [dashboard] Update tailwindcss and enable jit (now stable)
  components/dashboard/package.json
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: component: dashboard, approved, size/L, lgtm

#5316 [readme]: update links
  install/docker/README.md
Labels: approved, lgtm, size/XS

#5322 [ws-manager-bridge] Sync node grpc options with go counterpart
  components/ws-manager-bridge/src/bridge-controller.ts
Labels: approved, lgtm, size/XS

#5300 [ws-proxy] Configure grpc keepalive DialOption options
  components/ws-proxy/pkg/proxy/infoprovider.go
Labels: approved, lgtm, size/S

#5339 [ws-daemon] log reduced severity
  components/ws-daemon/pkg/dispatch/dispatch.go
Labels: approved, lgtm, size/XS

#5080 [proxy] Simplify conditional log expression
  components/proxy/conf/Caddyfile
  components/proxy/plugins/logif/lang/lang.go
Labels: approved, lgtm, size/S

#5340 [ws-daemon] Don't try to re-set same quota
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/S

#5319 [projects] limit number of prebuilts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/projects/projects-service.ts
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5318 [projects] add missing search filter
  components/dashboard/src/projects/Projects.tsx
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/M

#5346 [projects] remove prebuild number
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/service/service-mock.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/projects/projects-service.ts
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5358 [ws-daemon] Pass error by value instead of reference
  components/ws-daemon/pkg/content/archive.go
Labels: approved, lgtm, size/S

#5355 [dashboard] Propose to add Git integration
  components/dashboard/src/start/CreateWorkspace.tsx
Labels: approved, lgtm, size/XS

#5323 [dashboard] Add tooltip to project names
  components/dashboard/src/components/Tooltip.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: user experience, component: dashboard, approved, lgtm, size/XS

#5359 [dashboard] Fix typo on Select Account page
  components/dashboard/src/settings/SelectAccountModal.tsx
Labels: component: dashboard, approved, lgtm, size/XS

#5266 [db] fix creationTime in baseline migration
  components/gitpod-db/src/typeorm/migration/1629706076011-FixCreationTimeColumns.ts
Labels: 🧑‍🚀 crew: teams and projects, approved, lgtm, size/S

#5347 [content-service] Remove error log if the bucket does not exists
  components/content-service/pkg/storage/gcloud.go
Labels: approved, lgtm, size/S

#5352 [agent-smith] Show blacklisted command arguments
  components/ee/agent-smith/pkg/agent/agent.go
Labels: approved, lgtm, size/XS

#5213 [registry-facade] Fix error gosimple S1017
  components/ee/agent-smith/pkg/agent/agent.go
Labels: approved, lgtm

#5222 [werft] Fail werft if cert copy fails
  .werft/util/certs.ts
Labels: approved, lgtm, size/XS

#5375 [projects] fix search input on /new
  components/dashboard/src/projects/NewProject.tsx
Labels: component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5240 [ws-daemon] Refactor unmount
  components/workspacekit/cmd/rings.go
  components/ws-daemon/pkg/content/service.go
  components/ws-manager/pkg/manager/monitor.go
Labels: approved, lgtm, size/M

#5299 [workspacekit] Refactor ws-daemon grpc client connection
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/M

#4145 Corrects minio helm repo command
  chart/README.md
Labels: community-contribution, approved, lgtm

#5431 Fix typo in github workflow
  .github/workflows/check-gitpodyaml.yml
Labels: approved, lgtm, size/XS

#5428 Missed semicolon
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: approved, lgtm, size/XS

#5423 Add 'type' label to workspace stop metric
  components/ws-manager/pkg/manager/metrics.go
Labels: approved, lgtm, size/XS

#5415 [agent-smith] Improve report of infringements with long commands
  components/ee/agent-smith/cmd/run.go
  components/ee/agent-smith/pkg/agent/agent.go
Labels: approved, lgtm, size/M

#5417 [code] apply installation options for extensions from vsix
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS

#5436 Handle reconnecting websocket cancel
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/reconnecting-ws.go
  components/local-app/pkg/bastion/bastion.go
Labels: approved, lgtm, size/S

#5420 [license] adjust users of self-hosted license
  components/licensor/ee/pkg/licensor/licensor.go
  components/licensor/ee/pkg/licensor/licensor_test.go
Labels: approved, lgtm, size/S

#5432 changed nodeAffinity for preview environments
  .werft/build.ts
  .werft/jaeger.yaml
  .werft/values.dev.yaml
  .werft/values.k3sWsCluster.yaml
  .werft/values.nodeAffinities_0.yaml
  .werft/values.nodeAffinities_1.yaml
Labels: approved, size/L, lgtm

#5286 [helm] Add liveness probe to ws-proxy deployment
  chart/templates/ws-proxy-deployment.yaml
Labels: approved, lgtm, size/XS

#5369 [local-app] gracefully handle invalid token
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/go/reconnecting-ws.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/local-app/go.mod
  components/local-app/go.sum
  components/local-app/main.go
  components/local-app/pkg/auth/auth.go
  components/local-app/pkg/auth/auth_test.go
  components/local-app/pkg/bastion/bastion.go
  components/server/src/auth/bearer-authenticator.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/oauth-server/db.ts
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/XL

#5454 [ws-manager] Restart pod on config change
  chart/values.yaml
Labels: approved, lgtm, size/XS

#5444 [ws-daemon] Remove gitpod_ws_daemon_workspace_cpu_limit_sec metric
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/S

#5422 Fix drift in alpine container version
  chart/values.yaml
  components/image-builder-mk3/leeway.Dockerfile
Labels: approved, lgtm, size/XS

#5457 [ws-manager-bridge] Remove unused grpc dependency
  components/ws-manager-bridge/package.json
  yarn.lock
Labels: groundwork: scheduled, approved, size/L, lgtm, team: workspace

#5459 [owners] Introduce the IDE team
  OWNERS_ALIASES
  components/ide/OWNERS
  components/supervisor/OWNERS
Labels: approved, lgtm, size/S

#5438 [server] Bump gitpod-yml-inferrer
  components/server/package.json
  yarn.lock
Labels: approved, lgtm, size/S
