Repository gitpod-io/gitpod, pull requests merged in 2021-09, with the labels that each got.

#5477 Enable Teams & Projects on joining of a team
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/teams/JoinTeam.tsx
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, lgtm, size/M, feature: teams and projects

#5479 fix #5478: readd GITPOD_WORKSPACE_CONTEXT_URL
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/XS

#5144 chore(install): retire broken gcp-terraform
  install/gcp-terraform/environment/full/.gitignore
  install/gcp-terraform/environment/full/README.md
  install/gcp-terraform/environment/full/main.tf
  install/gcp-terraform/environment/full/providers.tf
  install/gcp-terraform/environment/full/values.yaml
  install/gcp-terraform/environment/full/variables.tf
  install/gcp-terraform/environment/full/versions.tf
  install/gcp-terraform/environment/installer/.gitignore
  install/gcp-terraform/environment/installer/BUILD.yaml
  install/gcp-terraform/environment/installer/main.auto.tfvars
  install/gcp-terraform/environment/installer/main.tf
  install/gcp-terraform/environment/installer/modules
  install/gcp-terraform/environment/installer/outputs.tf
  install/gcp-terraform/environment/installer/providers.tf
  install/gcp-terraform/environment/installer/templates/values.tpl
  install/gcp-terraform/environment/installer/variables.tf
  install/gcp-terraform/modules/BUILD.yaml
  install/gcp-terraform/modules/certmanager/main.tf
  install/gcp-terraform/modules/certmanager/outputs.tf
  install/gcp-terraform/modules/certmanager/templates/certificate.tpl
  install/gcp-terraform/modules/certmanager/templates/clusterissuer.tpl
  install/gcp-terraform/modules/certmanager/templates/values.tpl
  install/gcp-terraform/modules/certmanager/variables.tf
  install/gcp-terraform/modules/certmanager/versions.tf
  install/gcp-terraform/modules/database/README.md
  install/gcp-terraform/modules/database/main.tf
  install/gcp-terraform/modules/database/outputs.tf
  install/gcp-terraform/modules/database/templates/values.tpl
  install/gcp-terraform/modules/database/variables.tf
  install/gcp-terraform/modules/dns/README.md
  install/gcp-terraform/modules/dns/locals.tf
  install/gcp-terraform/modules/dns/main.tf
  install/gcp-terraform/modules/dns/outputs.tf
  install/gcp-terraform/modules/dns/templates/values.tpl
  install/gcp-terraform/modules/dns/variables.tf
  install/gcp-terraform/modules/dns/versions.tf
  install/gcp-terraform/modules/gitpod/main.tf
  install/gcp-terraform/modules/gitpod/templates/values.node-layout.tpl
  install/gcp-terraform/modules/gitpod/templates/values.tpl
  install/gcp-terraform/modules/gitpod/variables.tf
  install/gcp-terraform/modules/kubeconfig/main.tf
  install/gcp-terraform/modules/kubeconfig/outputs.tf
  install/gcp-terraform/modules/kubeconfig/templates/kubeconfig.tpl
  install/gcp-terraform/modules/kubeconfig/terraform.tf
  install/gcp-terraform/modules/kubeconfig/variables.tf
  install/gcp-terraform/modules/kubernetes/README.md
  install/gcp-terraform/modules/kubernetes/main.tf
  install/gcp-terraform/modules/kubernetes/outputs.tf
  install/gcp-terraform/modules/kubernetes/variables.tf
  install/gcp-terraform/modules/registry/README.md
  install/gcp-terraform/modules/registry/main.tf
  install/gcp-terraform/modules/registry/outputs.tf
  install/gcp-terraform/modules/registry/templates/registry-auth.tpl
  install/gcp-terraform/modules/registry/templates/values.tpl
  install/gcp-terraform/modules/registry/variables.tf
  install/gcp-terraform/modules/storage/README.md
  install/gcp-terraform/modules/storage/main.tf
  install/gcp-terraform/modules/storage/outputs.tf
  install/gcp-terraform/modules/storage/templates/values.tpl
  install/gcp-terraform/modules/storage/variables.tf
Labels: component: install, approved, lgtm, size/XXL

#5481 Fix dark theme colors and overflowing rounded corners
  components/dashboard/src/projects/NewProject.tsx
Labels: user experience, component: dashboard, approved, lgtm, size/S, feature: teams and projects

#5469 [ws-daemon] Refactor mark unmount
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/M

#5482 [server, paymentendpoint] Fix config (parsing)
  chart/templates/payment-endpoint-deployment.yaml
  chart/values.yaml
Labels: approved, lgtm, size/XS

#5483 [server] Add/propagate missing defaults
  chart/templates/payment-endpoint-deployment.yaml
  chart/templates/server-configmap.yaml
  chart/values.yaml
  components/server/src/config.ts
Labels: approved, lgtm, size/S

#5485 [server] Fix temporary config validation
  chart/templates/server-configmap.yaml
  components/server/src/config.ts
Labels: approved, lgtm, size/S

#5456 vscode desktop on windows
  components/local-app/main.go
  components/local-app/pkg/bastion/bastion.go
Labels: approved, lgtm, size/XS

#5486 [blobserve] Add error handling in MarkDone
  components/blobserve/pkg/blobserve/refstore.go
  components/blobserve/pkg/blobserve/refstore_test.go
Labels: approved, lgtm, size/M

#5449 Configure grpc client ChannelOptions
  components/ee/db-sync/leeway.Dockerfile
  components/gitpod-protocol/src/util/grpc.ts
  components/server/leeway.Dockerfile
  components/server/src/container-module.ts
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-bridge/src/bridge-controller.ts
Labels: approved, lgtm, size/M

#5495 [db-migration] fix timestamp of AddPrebuildInfo
  components/gitpod-db/src/typeorm/migration/1630566926740-AddPrebuildInfo.ts
Labels: approved, lgtm, size/XS

#5442 [db] Subscribe existing users to DevXMail
  components/gitpod-db/src/typeorm/migration/1630335270192-UpdateDevxAndOnboardingMail.ts
Labels: approved, lgtm, size/S

#5502 [db-migration] update timestamp of UpdateDevxAndOnboardingMail
  components/gitpod-db/src/typeorm/migration/1630586785018-UpdateDevxAndOnboardingMail.ts
Labels: approved, lgtm, size/XS

#5506 [db-sync] add d_b_prebuild_info
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/deleted-entry-gc.ts
Labels: approved, lgtm, size/XS

#5487 [ws-manager] Refactor activity map to sync.Map
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/status_test.go
Labels: approved, lgtm, size/S

#5505 [supervisor] Remove unnecessary log about port already exposed
  components/supervisor/pkg/ports/served-ports.go
Labels: approved, lgtm, size/XS

#5499 [ws-manger] Add dependency on dependsOn key for ws-manager
  chart/templates/ws-manager-deployment.yaml
Labels: approved, lgtm, size/XS

#5514 [prow] Give IDE team more ownership
  OWNERS
  components/local-app/OWNERS
Labels: approved, lgtm, size/XS

#5511 Remove Theia settings and point to Code image
  chart/templates/server-configmap.yaml
  chart/templates/server-deployment.yaml
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/M

#5192 [dashboard] Add George as a dashboard OWNER
  components/dashboard/OWNERS
Labels: approved, lgtm, size/XS

#5531 Immediately redirect to www.gitpod.io for any website slugs.
  components/dashboard/src/App.tsx
Labels: approved, lgtm, size/S

#5510 [ws-manager-api] Remove hardcoded grpc call deadline
  components/ws-manager-api/typescript/src/promisified-client.ts
Labels: approved, lgtm, size/XS

#5541 [server] Fix admin stop workspace
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
  test/pkg/integration/user.go
  test/tests/admin/blockuser_test.go
Labels: approved, size/L, lgtm

#5228 [chart] Reduce verbosity of the logs
  chart/values.yaml
Labels: approved, lgtm, size/XS

#5480 Introduce '/headless-log-download' endpoint for transparent log downloads
  components/proxy/Dockerfile
  components/proxy/conf/Caddyfile
  components/proxy/plugins/headlesslogdownload/go.mod
  components/proxy/plugins/headlesslogdownload/go.sum
  components/proxy/plugins/headlesslogdownload/headless_log_download.go
  components/server/src/server.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/headless-log-service.ts
Labels: approved, lgtm, size/XXL

#5180 [docker-up] Update docker-compose and slirp4netns
  components/docker-up/dependencies.sh
Labels: approved, lgtm, size/XS

#5545 Change provider dropdown icon size
  components/dashboard/src/icons/Plus.svg
  components/dashboard/src/icons/Switch.svg
Labels: user experience, component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS

#5546 [changelog] added PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/S

#5540 [projects] fix projectId for incremental prebuilds
  components/server/ee/src/workspace/workspace-factory.ts
Labels: approved, lgtm, size/S

#5529 [server / inferrer] prefetch configuration files
  components/server/src/projects/projects-service.ts
Labels: approved, lgtm, size/S

#5362 [gitlab] Accept '#' sign in branches / context URLs
  components/server/src/gitlab/gitlab-context-parser.spec.ts
  components/server/src/gitlab/gitlab-context-parser.ts
Labels: approved, lgtm, size/M

#5548 [supervisor] remove prebuild task progress logging
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/tasks.go
Labels: approved, lgtm, size/M, release-note-none

#5530 [image-builder-bob] Update to latest buildkit
  components/image-builder-bob/leeway.Dockerfile
Labels: approved, lgtm, size/XS

#5550 [ws-manager] Log event trace log as INFO
  components/ws-manager/pkg/manager/monitor.go
Labels: approved, lgtm, size/XS, release-note-none

#5496 [server] Remove legacy configuration
  chart/templates/server-deployment.yaml
  components/server/ee/src/container-module.ts
  components/server/ee/src/env.ts
  components/server/ee/src/server.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/config.ts
  components/server/src/container-module.ts
  components/server/src/env.ts
  components/server/src/server.ts
Labels: approved, lgtm, size/XL

#5559 [ws-proxy] Improve log message and reduce verbosity
  components/ws-proxy/pkg/proxy/auth.go
  components/ws-proxy/pkg/proxy/routes.go
Labels: approved, lgtm, size/XS, release-note-none

#5547 Revert "[chart] Reduce verbosity of the logs"
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#5544 [dashboard] give team URLs a dedicated slug
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/teams/JoinTeam.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/teams-context.tsx
Labels: 🧑‍🚀 crew: teams and projects, approved, lgtm, size/M

#5556 Change default branch label colors for dark theme
  components/dashboard/src/projects/Project.tsx
Labels: user experience, component: dashboard, 🧑‍🚀 crew: teams and projects, approved, lgtm, size/XS, release-note

#5542 [content-service] DeleteObject: improve it.Next err handling
  components/content-service/pkg/storage/gcloud.go
Labels: approved, lgtm, size/S, release-note-none

#5600 [analytics] Propagate allows onboarding to Segment
  components/server/src/user/user-controller.ts
Labels: approved, lgtm, size/XS, release-note-none

#5604 [server] Trigger restart on deployment if config changed
  chart/templates/server-deployment.yaml
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#5605 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XL, release-note-none

#5568 [server] Redirect without hitting sorry endpoint.
  components/server/src/auth/generic-auth-provider.ts
Labels: approved, lgtm, size/XS

#5607 Cleaned up CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5606 [changelog] some cleanup
  .github/pull_request_template.md
  .werft/changelog.yaml
Labels: approved, lgtm, size/XS, release-note-none

#5614 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5567 [supervisor] reduce noise when terminating child processes
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS, release-note-none

#5615 [proxy] Upgrade Caddy
  components/proxy/Dockerfile
  components/proxy/plugins/corsorigin/go.mod
  components/proxy/plugins/corsorigin/go.sum
  components/proxy/plugins/headlesslogdownload/go.mod
  components/proxy/plugins/headlesslogdownload/go.sum
  components/proxy/plugins/jsonselect/go.mod
  components/proxy/plugins/jsonselect/go.sum
  components/proxy/plugins/logif/go.mod
  components/proxy/plugins/logif/go.sum
  components/proxy/plugins/secwebsocketkey/go.mod
  components/proxy/plugins/secwebsocketkey/go.sum
  components/proxy/plugins/workspacedownload/go.mod
  components/proxy/plugins/workspacedownload/go.sum
Labels: approved, lgtm, size/XXL, release-note-none

#5629 [server] Fix SharedWorkspaceAccessGuard
  components/server/src/auth/resource-access.ts
Labels: approved, lgtm, size/XS, release-note-none

#5630 [bob] Add debug instructions
  components/image-builder-bob/.vscode/launch.json
  components/image-builder-bob/README.md
Labels: approved, lgtm, size/M, release-note-none

#5190 [ws-daemon] Update runc to v1.0.1
  components/ws-daemon/leeway.Dockerfile
Labels: approved, lgtm, size/XS

#5610 [ws-manager] Wait additional time to deletionGracePeriod before finalize workspace
  components/ws-manager/pkg/manager/monitor.go
Labels: approved, lgtm, size/S, release-note-none

#5613 [supervisor] Increase sendHeartBeat to 30s plus a random additional wait
  components/supervisor/frontend/src/ide/heart-beat.ts
Labels: approved, lgtm, size/XS, release-note-none

#5283 [chart] Redirect bash debug to stdout
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS

#5650 [ws-manager-api] Partially revert the use of a deadline per grpc call
  components/ws-manager-api/typescript/src/promisified-client.ts
Labels: approved, lgtm, size/XS, release-note-none

#5651 [server] Add workspace ID in trace span WorkspaceStarter.startWorkspace
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/XS, release-note-none

#5626 feat(slug): add /code-of-conduct to redirect
  components/dashboard/src/App.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5668 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5671 [changelog] manually fixed sorting
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5634 Improve leeway task to update go modules
  components/BUILD.yaml
  components/common-go/go-get-kubernetes.sh
  components/content-service-api/typescript/util/go.mod
  components/content-service-api/typescript/util/go.sum
  components/content-service/pkg/storage/generate-mock.sh
  components/gitpod-protocol/go/generate-mock.sh
  components/gitpod-protocol/hack/generate-config.sh
  components/local-app/go.mod
  components/local-app/go.sum
  components/proxy/plugins/corsorigin/go.sum
  components/proxy/plugins/headlesslogdownload/go.sum
  components/proxy/plugins/jsonselect/go.sum
  components/proxy/plugins/logif/go.sum
  components/proxy/plugins/secwebsocketkey/go.sum
  components/proxy/plugins/workspacedownload/go.sum
  components/workspacekit/go.mod
  components/workspacekit/go.sum
  components/ws-daemon-api/generate.sh
  components/ws-daemon-api/go/go.mod
  components/ws-daemon-api/go/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-manager/go.mod
  components/ws-manager/go.sum
  dev/changelog/go.sum
  scripts/protoc-generator.sh
Labels: approved, size/L, lgtm, release-note-none

#5635 [ws-manager] Remove error message if pod no longer exists
  components/ws-manager/pkg/manager/annotations.go
Labels: approved, lgtm, size/XS, release-note-none

#5637 [ws-daemon] Refactoring to reduce log verbosity
  components/common-go/log/log.go
  components/workspacekit/pkg/seccomp/notify.go
  components/ws-daemon/nsinsider/pkg/nsenter/nsexec.c
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-daemon/pkg/iws/uidmap.go
Labels: approved, size/L, lgtm, release-note-none

#5656 [ws-proxy] Change log level if no owner cookie is present
  components/ws-proxy/pkg/proxy/auth.go
Labels: approved, lgtm, size/XS, release-note-none

#5674 [projects] fix filter for prebuilds updates
  components/dashboard/src/projects/Prebuilds.tsx
Labels: component: dashboard, feature: prebuilds, approved, lgtm, size/XS, feature: teams and projects, release-note-none

#5658 [ws-manager] Change log level for starting new workspaces
  components/ws-manager/pkg/manager/manager.go
Labels: approved, lgtm, size/XS, release-note-none

#5400 [ws-proxy] Remove proxy of ws-manager
  chart/templates/ws-proxy-configmap.yaml
  chart/templates/ws-proxy-networkpolicy.yaml
  chart/values.yaml
  components/ws-proxy/cmd/root.go
  components/ws-proxy/cmd/run.go
  components/ws-proxy/pkg/ratelimit/rate-limited-listener.go
Labels: approved, size/L, lgtm

#5652 independent deployment of code images
  chart/templates/server-configmap.yaml
  chart/templates/server-deployment.yaml
  chart/templates/server-ide-configmap.yaml
  components/server/ee/src/workspace/workspace-starter.ts
  components/server/package.json
  components/server/src/config.ts
  components/server/src/container-module.ts
  components/server/src/ide-config.ts
  components/server/src/workspace/workspace-starter.ts
  yarn.lock
Labels: approved, size/L, lgtm, release-note-none

#5664 Enable GRPC logging
  components/common-go/grpc/grpc.go
  components/content-service/cmd/run.go
  components/image-builder-mk3/cmd/run.go
  components/supervisor/cmd/run.go
  components/workspacekit/cmd/rings.go
  components/ws-daemon/cmd/run.go
  components/ws-manager/cmd/run.go
  components/ws-proxy/cmd/run.go
  dev/gpctl/cmd/root.go
Labels: approved, lgtm, size/M, release-note-none

#5682 [server] allow unsubscribe from onboarding emails
  components/server/src/user/newsletter-subscription-controller.ts
Labels: component: server, approved, lgtm, size/XS, release-note

#5685 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M, release-note-none

#5679 [server] remove prebuilt time limit
  components/gitpod-db/src/typeorm/migration/1592203031938-Baseline.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-db/src/workspace-db.ts
  components/licensor/ee/pkg/licensor/licensor.go
  components/licensor/ee/pkg/licensor/licensor_test.go
  components/licensor/typescript/ee/main.go
  components/licensor/typescript/ee/src/index.ts
  components/licensor/typescript/ee/src/module.cc
  components/licensor/typescript/ee/src/nativemodule.d.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/ee/src/workspace/workspace-health-monitoring.ts
Labels: approved, size/L, lgtm, release-note-none

#5421 [projects] add check for createProject
  components/dashboard/src/projects/NewProject.tsx
  components/server/src/projects/projects-service.ts
Labels: approved, lgtm, size/S

#5691 [helm] Introduce optional deploy of ide config map
  chart/templates/server-ide-configmap.yaml
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#5700 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5696 [common-go] Do not log EOF errors decoding JSON
  components/common-go/log/log.go
  components/common-go/log/log_test.go
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/iws/iws.go
Labels: approved, size/L, lgtm, release-note-none

#5711 [supervisor] Check for canceled context and reword message
  components/supervisor/pkg/supervisor/services.go
Labels: approved, lgtm, size/S, release-note-none

#5709 [gpctl] Add missing go dependencies
  dev/gpctl/go.mod
  dev/gpctl/go.sum
Labels: approved, lgtm, size/M, release-note

#5714 [ws-daemon] Remove not useful log
  components/ws-daemon/pkg/iws/iws.go
Labels: approved, lgtm, size/XS, release-note-none

#5695 [dashboard] Allow workspace renaming
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: approved, lgtm, size/M, release-note

#5719 fix parisng of tasks env vars in go
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/tasks.go
  components/supervisor/pkg/supervisor/tasks_test.go
Labels: approved, lgtm, size/M, release-note

#5728 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5736 [code] show open in desktop notificaiton
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#5730 [dashboard] Remove duplicate status header in Prebuild page
  components/dashboard/src/projects/Prebuild.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5557 Add Gitpod version and score info metrics
  components/server/src/prometheus-metrics.ts
  components/server/src/server.ts
Labels: approved, lgtm, size/S, release-note-none

#5727 Update node prometheus library to 13.2.0
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/messaging/client-call-metrics.ts
  components/server/ee/src/monitoring-endpoint-ee.ts
  components/server/ee/src/prebuilds/prebuild-queue-maintainer.ts
  components/server/package.json
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/client-data-prometheus-adapter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/ws-manager-bridge/package.json
  components/ws-manager-bridge/src/main.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
  yarn.lock
Labels: approved, lgtm, size/M, release-note

#5739 [proxy] Enable Caddy metrics
  components/proxy/conf/Caddyfile
Labels: approved, lgtm, size/XS, release-note-none

#5748 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5749 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5757 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5760 [workspacekit] Check if process is already finished during termination
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/XS, release-note-none

#5750 [code] Enable terminal localEcho by default
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#5581 chore(dei): he -> [they|their]
  components/server/ee/src/user/eligibility-service.ts
Labels: approved, lgtm, size/XS, release-note

#5744 [server] Don't re-set owner cookie
  components/server/src/user/user-controller.ts
Labels: approved, lgtm, size/S, release-note-none

#5755 [ws-manager-bridge] Add status update metric
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: approved, lgtm, size/S, release-note

#5766 try reconnect 15 times to ws on bad handshake with 3xx or 4xx status code
  components/gitpod-protocol/go/reconnecting-ws.go
Labels: approved, lgtm, size/S, release-note-none

#5710 [analytics] improve status_rendered events
  components/dashboard/src/start/StartWorkspace.tsx
  components/supervisor/frontend/src/index.ts
Labels: approved, lgtm, size/M, release-note-none

#5439 [db] Fix string booleans to be booleans
  components/gitpod-db/src/typeorm/migration/1630333424897-ReplaceStringBooleansWithBooleans.ts
Labels: approved, lgtm, size/S

#5756 [ws-manager] Add validation of grpc connections in the pool
  components/ws-manager/pkg/manager/integration_test.go
  components/ws-manager/pkg/manager/internal/grpcpool/pool.go
  components/ws-manager/pkg/manager/internal/grpcpool/pool_test.go
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/manager_test.go
Labels: approved, size/L, lgtm, release-note-none

#5677 [chart] Reduce verbosity of the logs
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#5768 [dropbear] patch to allow g+w and o+w to the user's homedir, ~/.ssh, and ~/.ssh/authorized_keys
  components/supervisor/BUILD.yaml
Labels: approved, lgtm, size/XS, release-note-none

#5725 docs(coc): use .github/CODE_OF_CONDUCT.md instead
  CODE_OF_CONDUCT.md
Labels: approved, size/L, lgtm, release-note-none

#5775 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5792 [dashboard] Unify animated spinner for both light and dark themes
  components/dashboard/src/icons/Spinner.svg
  components/dashboard/src/icons/SpinnerDark.svg
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
Labels: approved, lgtm, size/S, release-note-none

#5797 [ws-daemon] Use unique container names for init
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/M, release-note

#5788 [code] upgrade to VS Code 1.60.2
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#5799 [ws-manager] Fix invalid logic to remove old endpoint
  components/ws-manager/pkg/manager/internal/grpcpool/pool.go
  components/ws-manager/pkg/manager/manager.go
Labels: approved, lgtm, size/S, release-note-none

#5794 [workspacekit] Update libseccomp and fuse-overlayfs
  .gitpod.yml
  .werft/build.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  components/workspacekit/BUILD.yaml
  dev/image/Dockerfile
Labels: approved, lgtm, size/S, release-note

#5803 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5168 [analytics] Track Projects & Teams
  components/dashboard/package.json
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/PillMenuItem.tsx
  components/dashboard/src/components/TabMenuItem.tsx
  components/dashboard/src/index.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/teams/Members.tsx
  components/gitpod-protocol/src/analytics.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/util/analytics.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/user/enforcement-endpoint.ts
  components/server/src/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, lgtm, size/XL, feature: teams and projects, release-note-none

#5789 [ws-daemon] Reduce messages log level
  components/content-service/pkg/initializer/git.go
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/dispatch/dispatch.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-daemon/pkg/resources/dispatch.go
Labels: approved, lgtm, size/S, release-note-none

#5812 [server] fix loglevel filter: apply to all calls, not just console.
  components/gitpod-protocol/src/util/logging.ts
Labels: approved, lgtm, size/M, release-note-none

#5811 [ws-scheduler] Adjust log levels
  components/ee/ws-scheduler/pkg/scaler/driver.go
Labels: approved, lgtm, size/XS, release-note-none

#5776 [server] Update node to 12.22.6 and add additional binaries
  components/server/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note

#5819 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5820 [supervisor] Do not emit a warning creating symlinks
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS, release-note-none

#5813 [ws-daemon] Remove use of intemediate buffer during tar creation
  components/ws-daemon/pkg/content/archive.go
Labels: approved, lgtm, size/XS, release-note-none

#5829 [chart] Upgrade kube-rbac-proxy to v0.11.0
  chart/templates/_helpers.tpl
Labels: approved, lgtm, size/XS, release-note

#5837 [owners] Update to reflect latest team changes
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none

#5835 [server] Delete unused PrebuildQueueMaintainer and PrebuildRateLimiter
  components/server/ee/src/container-module.ts
  components/server/ee/src/prebuilds/prebuild-queue-maintainer.ts
  components/server/ee/src/prebuilds/prebuild-rate-limiter.ts
Labels: approved, size/L, lgtm, release-note-none

#5842 [proxy] Do not log supervisor proxy errors
  components/ws-proxy/pkg/proxy/pass.go
Labels: approved, lgtm, size/XS, release-note-none

#5745 [preview-env] Deploy monitoring-satellite alongside preview environments
  .werft/build.ts
  .werft/build.yaml
  .werft/util/observability.ts
Labels: approved, size/L, lgtm, release-note-none

#5860 Add node affinity to monitoring-satellite
  .werft/util/observability.ts
Labels: approved, lgtm, size/XS, release-note-none

#5026 Ask for a Gitpod workspace snapshot
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: approved, lgtm, size/XS

#5857 [content-service] Do not log prebuild initialized logs in info level
  components/content-service/pkg/initializer/prebuild.go
Labels: approved, lgtm, size/XS, release-note-none

#5868 [build] Don't deploy monitoring-satelite by default
  .werft/build.ts
Labels: approved, lgtm, size/M, release-note-none

#5874 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#5839 [ws-daemon] Reduce log level of CPU limit messages
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/XS, release-note-none

#5555 [t&p] add workspaces to teams
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/index.css
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/workspace-model.ts
  components/gitpod-db/package.json
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/gitpod-service.ts
Labels: approved, lgtm, size/XXL, release-note-none

#5885 [ws-manager-bridge] Also copy status.conditions.headlessTaskFailed into WorkspaceInstanceConditions
  components/gitpod-protocol/src/workspace-instance.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: approved, lgtm, size/XS, release-note-none

#5880 [ws-manager-bridge] Properly provide cluster metrics
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
  components/ws-manager-bridge/tsconfig.json
Labels: approved, lgtm, size/S, release-note-none

#5855 [analytics] Fix location prop in analytics track call
  components/server/src/auth/login-completion-handler.ts
Labels: approved, lgtm, size/XS, release-note-none

#5893 [gitpod-db] added more tests
  components/gitpod-db/src/workspace-db.spec.db.ts
Labels: approved, lgtm, size/M, release-note-none

#5894 [projects] clear team selection
  components/dashboard/src/Menu.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5882 [dev] build job: move from name-based to label-based node selector
  .werft/build.yaml
  .werft/changelog.yaml
Labels: approved, lgtm, size/S, release-note-none

#5898 Close stale PRs more agressively
  .github/stale.yml
Labels: approved, lgtm, size/XS, release-note-none

#5848 [code] Fixes exthost deadlock
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#5907 [projects] Enable New Workspace button when config is Git-based
  components/dashboard/src/projects/ConfigureProject.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5920 [db] Create index ind_buildWorkspaceId on d_b_prebuild_workspace_info
  components/gitpod-db/src/typeorm/migration/1632903852031-IndexBuildWorkspaceId.ts
Labels: approved, lgtm, size/S, release-note

#5916 [dashboard] don't show 'new project' button
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: component: dashboard, approved, lgtm, size/XS, feature: teams and projects, team: meta, release-note-none

#5587 [dashboard] improve branches page
  components/dashboard/src/projects/Project.tsx
Labels: component: dashboard, approved, lgtm, size/XS, feature: teams and projects, release-note-none

#5918 [server] Handle terminals for tasks that have already been closed
  components/server/src/workspace/headless-log-service.ts
Labels: approved, lgtm, size/S, release-note

#5897 [ws-daemon] Properly handle mark unmount
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-daemon/pkg/daemon/markunmount.go
  components/ws-manager/pkg/manager/monitor.go
Labels: approved, lgtm, size/XL, release-note

#5912 Clean-up Readme
  README.md
Labels: approved, lgtm, size/S

#5938 Add 5 second interval automatic page reload to default 404 page for unserved ports.
  components/ws-proxy/public/port-not-found.html
Labels: approved, lgtm, size/XS, release-note

#5948 [werft] replaced ws-nodepools and enabled raid0 on ws-nodepools
  .werft/build.ts
  .werft/values.dev.yaml
  .werft/values.nodeAffinities_2.yaml
  .werft/values.nodeAffinities_3.yaml
Labels: approved, lgtm, size/S, release-note

#5939 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S, release-note-none

#5957 [t&p] enable teams and projects ui
  components/dashboard/src/Menu.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/service/service-mock.ts
  components/dashboard/src/teams/JoinTeam.tsx
  components/gitpod-protocol/src/permission.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: component: dashboard, approved, lgtm, size/M, feature: teams and projects, release-note

#5962 Fix location of integration tests binaries
  test/entrypoint.sh
Labels: approved, lgtm, size/XS, release-note-none
