Repository gitpod-io/gitpod, pull requests merged in 2021-10, with the labels that each got.

#5969 [test] Ensure agent binaries are available in PATH
  test/entrypoint.sh
  test/leeway-build.sh
Labels: approved, lgtm, size/XS, release-note-none

#5900 [teams] use owner's GitLab account by default
  components/dashboard/src/projects/NewProject.tsx
  components/server/ee/src/gitlab/gitlab-app-support.ts
Labels: component: dashboard, approved, lgtm, size/S, feature: teams and projects, team: meta, release-note-none

#5967 [db] Sync and GC d_b_team_membership_invite
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/deleted-entry-gc.ts
Labels: approved, lgtm, size/XS, release-note

#5917 [supervisor] Add carret return to prebuild terminal message
  components/supervisor/pkg/supervisor/tasks.go
Labels: approved, lgtm, size/XS, release-note-none

#5973 [projects] fix for empty projects page
  components/dashboard/src/projects/Project.tsx
Labels: approved, lgtm, size/S, release-note-none

#5961 [projects] Fix rendering of startedAt attribute
  components/dashboard/src/projects/Projects.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5960 [teams] don't show error if already in team
  components/dashboard/src/teams/JoinTeam.tsx
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: component: dashboard, approved, lgtm, size/S, feature: teams and projects, team: meta, release-note-none

#5983 Reword team creation header to meet current features
  components/dashboard/src/teams/NewTeam.tsx
Labels: component: dashboard, approved, lgtm, size/XS, feature: teams and projects, team: meta, release-note-none

#6011 Rename teams to team plans
  components/dashboard/src/settings/Teams.tsx
  components/dashboard/src/settings/settings-menu.ts
Labels: component: dashboard, approved, lgtm, size/S, team: meta, release-note-none

#6013 Fix typos for team plans
  components/dashboard/src/settings/Teams.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5966 Laushinka/allow users to delete 5066
  components/dashboard/README.md
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/entity/db-team.ts
  components/gitpod-db/src/typeorm/migration/1632908105486-AddSoftDeletedToTeam.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, size/L, lgtm, release-note

#6015 [supervisor] fix firing unload event
  components/supervisor/frontend/src/ide/gitpod-service-client.ts
  components/supervisor/frontend/src/index.ts
Labels: approved, lgtm, size/XS, release-note-none

#6005 [db] Add index 'ind_dbsync' on d_b_code_sync_resource
  components/gitpod-db/src/typeorm/migration/1633334251143-IndexCodeSyncCreated.ts
Labels: approved, lgtm, size/S, release-note

#6012 [ws-manager] Do not nest /workspace as relative path
  components/ws-manager/pkg/manager/create.go
Labels: approved, lgtm, size/XS, release-note-none

#5999 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S, release-note-none

#5972 Rename latest to insiders
  components/dashboard/src/settings/Preferences.tsx
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#6034 [teams] Fix typo in 'Delete Team' button text
  components/dashboard/src/teams/TeamSettings.tsx
Labels: approved, lgtm, size/XS, release-note-none

#6025 [agent-smith] Allow commands to skip infringements
  components/ee/agent-smith/pkg/agent/agent.go
  components/ee/agent-smith/pkg/agent/config.go
Labels: approved, lgtm, size/M, release-note-none

#6027 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6020 [installer]: apply type fixes to the installer components
  installer/pkg/common/common.go
  installer/pkg/common/constants.go
  installer/pkg/components/agent-smith/configmap.go
  installer/pkg/components/agent-smith/role.go
  installer/pkg/components/blobserve/configmap.go
  installer/pkg/components/blobserve/constants.go
  installer/pkg/components/gitpod/configmap.go
  installer/pkg/components/image-builder-mk3/configmap.go
  installer/pkg/components/registry-facade/configmap.go
  installer/pkg/components/server/configmap.go
  installer/pkg/components/server/ide-configmap.go
  installer/pkg/components/server/role.go
  installer/pkg/components/ws-manager-bridge/configmap.go
  installer/pkg/components/ws-manager/configmap.go
  installer/pkg/components/ws-proxy/configmap.go
  installer/pkg/components/ws-scheduler/configmap.go
Labels: approved, lgtm, size/M, release-note

#6050 [changelog] next try to enable automatic merge
  .werft/changelog.yaml
  dev/changelog/pullrequest.go
Labels: approved, lgtm, size/XS, release-note-none

#6029 [code] Update code to 1.61
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#6058 [dashboard] Improve deletion modal
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: approved, lgtm, size/XS, release-note-none

#6030 chore(docker) Align Alpine versions
  components/ee/kedge/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#6066 [prebuild-logs] ignore other instances
  components/dashboard/src/components/PrebuildLogs.tsx
Labels: approved, lgtm, size/XS, release-note-none

#5982 Support per-workspace filesystem quota on `/workspace`
  chart/templates/ws-daemon-daemonset.yaml
  components/content-service/pkg/initializer/initializer.go
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/pkg/content/hooks.go
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/quota/xfs.go
  components/ws-daemon/pkg/quota/xfs_test.go
Labels: approved, lgtm, size/XXL, release-note

#6059 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6086 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6087 [changelog] fixes for the changelog
  .werft/changelog.yaml
  dev/changelog/pullrequest.go
  dev/changelog/update.go
Labels: approved, lgtm, size/S, release-note-none

#6463 [code] switch nightly job to release/1.62
  .werft/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6467 [workspacekit] Make resolv.conf writeable
  components/workspacekit/cmd/rings.go
  components/workspacekit/cmd/rings_test.go
Labels: approved, lgtm, size/M, team: workspace, release-note
