Repository gitpod-io/gitpod, pull requests merged in 2021-12, with the labels that each got.

#6986 added github action for changelog
  .github/workflows/changelog.yml
  .werft/changelog.yaml
Labels: approved, lgtm, size/M, release-note-none

#6920 [installer]: change default containerd runtime dir
  installer/pkg/config/v1/config.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#6952 Cleanup no child processes running errors
  components/common-go/process/process.go
  components/content-service/pkg/initializer/git.go
  components/supervisor/pkg/supervisor/ssh.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/terminal/terminal.go
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note-none

#6902 Update alpine to 3.15
  chart/templates/proxy-deployment.yaml
  chart/values.yaml
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ee/kedge/leeway.Dockerfile
  components/ee/ws-scheduler/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/image-builder/example-config.json
  components/image-builder/leeway.Dockerfile
  components/image-builder/pkg/resolve/resolve_test.go
  components/image-builder/workspace-image-layer/tests/positive/alpine-withuser.dockerfile
  components/image-builder/workspace-image-layer/tests/positive/alpine.dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/supervisor/leeway.Dockerfile
  components/supervisor/openssh/leeway.Dockerfile
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager/debug.Dockerfile
  components/ws-manager/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  dev/poolkeeper/leeway.Dockerfile
  dev/sweeper/leeway.Dockerfile
  installer/leeway.Dockerfile
  installer/pkg/components/proxy/constants.go
  test/leeway.Dockerfile
Labels: approved, lgtm, size/M, team: meta, team: workspace, team: IDE, release-note

#6988 Adapt workspace download config
  components/proxy/plugins/workspacedownload/workspace_download.go
Labels: approved, lgtm, size/M, team: meta, release-note

#6970 .werft/build: Deploy monitoring-satellite before Gitpod
  .werft/build.ts
Labels: approved, lgtm, size/M, release-note-none

#6964 [installer]: remove jaeger operator external
  installer/pkg/config/v1/config.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#6991 [server] When adding a project to a team, install the prebuild webhook as the adding user, not as a (random) team owner
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, lgtm, size/S, team: meta, release-note

#6997 Enable manual trigger to nighlty job
  .github/workflows/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6998 [ops] Small dashboard/graph fixes
  operations/observability/mixins/meta/dashboards/components/meta-overview.json
  operations/observability/mixins/meta/dashboards/components/server.json
Labels: operations: observability, approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#6994 [server] re-enable telepresence
  components/server/BUILD.yaml
Labels: component: server, priority: high (dev loop impact), approved, lgtm, groundwork: in review, team: meta, release-note-none

#7018 changed shell for changelog
  .github/workflows/changelog.yml
Labels: approved, lgtm, size/XS, release-note-none

#7004 [jetbrains] Add PyCharm IDE
  chart/templates/server-ide-configmap.yaml
  chart/values.yaml
  components/BUILD.yaml
  components/ide/jetbrains/image/BUILD.yaml
  components/ide/jetbrains/image/supervisor-ide-config_pycharm.json
  installer/pkg/components/server/ide-configmap.go
  installer/pkg/components/workspace/constants.go
  installer/pkg/config/versions/versions.go
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note

#7021 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S, release-note-none

#7024 changed time schedule for changelog
  .github/workflows/changelog.yml
Labels: approved, lgtm, size/XS, release-note-none

#7029 [jetbrains] Update GitHub action
  .github/workflows/jetbrains-updates-template.yml
  .github/workflows/jetbrains-updates.yml
  chart/templates/server-ide-configmap.yaml
  installer/pkg/components/server/ide-configmap.go
Labels: approved, size/L, lgtm, team: workspace, team: IDE, release-note-none

#7044 [chart] Change first disk for raid0
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7045 [image-builder] Accept "familiar" base image refs
  components/image-builder-bob/cmd/proxy.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7047 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7040 [installer]: set component owners
  installer/pkg/components/agent-smith/OWNERS
  installer/pkg/components/blobserve/OWNERS
  installer/pkg/components/content-service/OWNERS
  installer/pkg/components/dashboard/OWNERS
  installer/pkg/components/image-builder-mk3/OWNERS
  installer/pkg/components/openvsx-proxy/OWNERS
  installer/pkg/components/proxy/OWNERS
  installer/pkg/components/registry-facade/OWNERS
  installer/pkg/components/server/OWNERS
  installer/pkg/components/ws-daemon/OWNERS
  installer/pkg/components/ws-manager-bridge/OWNERS
  installer/pkg/components/ws-manager/OWNERS
  installer/pkg/components/ws-proxy/OWNERS
  installer/pkg/components/ws-scheduler/OWNERS
Labels: approved, size/L, lgtm, team: workspace, release-note

#7052 [image-builder] Pull digested base refs correctly
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7062 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7059 [jetbrains] Add PhpStorm IDE
  .github/workflows/jetbrains-updates.yml
  chart/templates/server-ide-configmap.yaml
  chart/values.yaml
  components/BUILD.yaml
  components/ide/jetbrains/image/BUILD.yaml
  components/ide/jetbrains/image/supervisor-ide-config_phpstorm.json
  installer/pkg/components/server/ide-configmap.go
  installer/pkg/components/workspace/constants.go
  installer/pkg/config/versions/versions.go
Labels: approved, lgtm, size/M, team: meta, team: workspace, team: IDE, release-note

#7020 Made tracing optional for preview environments
  .werft/build.ts
  .werft/values.dev.yaml
  .werft/values.tracing.yaml
Labels: approved, lgtm, size/S, release-note

#7065 separator fix
  components/dashboard/src/components/Separator.tsx
Labels: community-contribution, component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#7084 [ide] Prepare for vscode release 1.63
  .github/workflows/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7079 [ws-manager] Retry controlPort on conflict
  components/ws-manager/pkg/manager/manager.go
Labels: approved, size/L, lgtm, team: workspace, release-note

#7030 [dashboard] Improve team selection UX in new Project flow
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, size/L, lgtm, team: meta, release-note

#7089 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7083 [supervisor] Add log for exposed port instance update
  components/supervisor/pkg/ports/exposed-ports.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6767 [installer]: create readme
  installer/README.md
Labels: approved, lgtm, size/XL, team: workspace, release-note

#7103 [dashboard] Fix UI experiments
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/experiments.ts
Labels: approved, lgtm, size/M, team: meta, release-note-none

#7104 [chart] Restore registry pullsecret
  chart/templates/image-builder-registry-auth-secret.yaml
Labels: approved, lgtm, size/XS, groundwork: in review, team: workspace, release-note-none

#7063 Enable experimentalNetwork by default
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/workspace-starter.ts
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/M, team: meta, team: workspace, release-note

#7000 Jk/api-telemetry
  components/server/ee/src/monitoring-endpoint-ee.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7131 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7127 [dashboard] Fix possible race condition when creating a new project
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7041 [installer]: bump rabbitmq chart to remove deprecated kube api
  installer/third_party/charts/rabbitmq/Chart.yaml
  installer/third_party/charts/rabbitmq/values.yaml
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7155 [chart] Fix values yaml after ephemeral storage change
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7133 [code] update stable to 1.63
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#7162 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7165 [workspacekit] Make independent of supervisor
  .werft/util/kubectl.ts
  chart/templates/registry-facade-configmap.yaml
  chart/values.yaml
  components/BUILD.yaml
  components/supervisor/leeway.Dockerfile
  components/workspacekit/BUILD.yaml
  components/workspacekit/leeway.Dockerfile
  installer/pkg/components/registry-facade/configmap.go
  installer/pkg/components/registry-facade/constants.go
  installer/pkg/components/workspace/constants.go
  installer/pkg/config/versions/versions.go
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note-none

#7169 [ws-scheduler] Pace GetWorkspace calls
  components/ee/ws-scheduler/pkg/scaler/driver.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7175 Pin insiders version temporarily
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7173 [workspacekit] Don't shadow /.supervisor
  components/supervisor/BUILD.yaml
  components/workspacekit/leeway.Dockerfile
Labels: approved, lgtm, size/XS, team: workspace, team: IDE, release-note-none

#7176 Point code nightly workflow back to main
  .github/workflows/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7107 [installer]: update docker-registry to allow for pod security policy application
  installer/pkg/components/docker-registry/helm.go
  installer/pkg/components/docker-registry/objects.go
  installer/pkg/components/docker-registry/rolebinding.go
  installer/third_party/charts/docker-registry/Chart.yaml
Labels: approved, lgtm, size/M, team: workspace, release-note

#7190 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7198 [server] Pin oci-tool to 0.1.1
  components/server/leeway.Dockerfile
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#7209 Revert "Pin insiders version temporarily"
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6827 [Werft] - Update build to support Installer
  .werft/build.ts
  .werft/post-process.sh
  .werft/util/kubectl.ts
  .werft/util/uninstall-gitpod.sh
  .werft/wipe-devstaging.ts
  installer/pkg/components/cluster/certmanager.go
  installer/pkg/components/image-builder-mk3/clusterrole.go
  installer/pkg/components/registry-facade/clusterrole.go
  installer/pkg/components/registry-facade/podsecuritypolicy.go
  installer/pkg/components/server/configmap.go
  installer/pkg/components/ws-daemon/clusterrole.go
  installer/pkg/components/ws-scheduler/clusterrole.go
  installer/pkg/components/ws-scheduler/clusterrolebinding.go
Labels: approved, lgtm, size/XXL, team: meta, team: workspace, release-note

#7219 [werft] Conditional path to uninstall-gitpod.sh
  .werft/util/kubectl.ts
Labels: approved, lgtm, size/S, release-note-none

#7223 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7206 [installer]: correct the starts_with validation on the config
  installer/pkg/config/validation.go
Labels: component: install, approved, lgtm, size/XS, team: workspace, release-note, team: self-hosted

#7172 [db] Allow to update PaymentSourceInfos
  components/gitpod-db/src/accounting-db.spec.db.ts
  components/gitpod-db/src/typeorm/accounting-db-impl.ts
Labels: approved, lgtm, size/M, groundwork: in review, team: meta, release-note-none

#7154 werft/observability: Pin default observability branch to v0.0.1
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#7199 [installer]: change ownership
  OWNERS_ALIASES
  installer/OWNERS
Labels: approved, lgtm, size/XS, team: workspace, release-note-none, team: self-hosted

#7233 Add domain to previewEnvironment config
  .werft/observability/monitoring-satellite.ts
Labels: approved, lgtm, size/XS, release-note-none, team: platform

#7235 [prow]: add self-hosted team as owners
  OWNERS
Labels: approved, lgtm, size/XS, release-note-none

#7239 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7247 [server] tracing: fix creation of "FOLLOWS_FROM" reference
  components/gitpod-protocol/src/util/tracing.ts
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#7163 Improve start page when GitHub App not installed
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, size/L, lgtm, team: meta, release-note

#7244 [installer]: document installing to a namespace
  installer/README.md
Labels: approved, lgtm, size/S, release-note-none, team: self-hosted

#7262 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7228 Add cluster autoscaler dashboard
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-cluster-autoscaler-k3s.json
Labels: approved, lgtm, size/XXL, release-note-none, team: platform

#7259 [dashboard] Fix PageWithSubMenu selection state by URL-encoding all links
  components/dashboard/src/components/PageWithSubMenu.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7251 [bitbucket] enable projects
  components/dashboard/src/projects/NewProject.tsx
  components/server/ee/src/bitbucket/bitbucket-app-support.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/prebuilds/bitbucket-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/package.json
  components/server/src/bitbucket/bitbucket-context-parser.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  yarn.lock
Labels: approved, size/L, lgtm, team: meta, release-note

#7276 [code] upgrade to vscode 1.63.2
  WORKSPACE.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7283 [vscode] Remove image-builder folder
  gitpod-ws.code-workspace
Labels: approved, lgtm, size/XS, release-note-none

#7291 [code] update stable to 1.63.2
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7298 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7292 [server] Debug output for dangling ws connections
  components/server/src/express-util.ts
Labels: approved, lgtm, size/S, groundwork: in review, team: meta, release-note-none

#5128 Mention username who added project in a team
  components/dashboard/src/projects/NewProject.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/projects/projects-service.ts
Labels: component: dashboard, meta: never-stale, approved, lgtm, size/M, feature: teams and projects, team: meta

#7296 Update vscode stable image in installer
  installer/pkg/components/workspace/constants.go
Labels: approved, lgtm, size/XS, release-note-none, team: self-hosted

#7309 [installer]: refactor the workspace component with ide ownership
  installer/pkg/components/blobserve/configmap.go
  installer/pkg/components/server/ide/configmap.go
  installer/pkg/components/workspace/OWNERS
  installer/pkg/components/workspace/constants.go
  installer/pkg/components/workspace/ide/OWNERS
  installer/pkg/components/workspace/ide/constants.go
  installer/pkg/components/ws-scheduler/configmap.go
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note-none, team: self-hosted

#7287 [db, payment] Remove DBPaymentSource
  components/ee/payment-endpoint/src/chargebee/payment-source-handler.ts
  components/ee/payment-endpoint/src/container-module.ts
  components/gitpod-db/src/accounting-db.spec.db.ts
  components/gitpod-db/src/accounting-db.ts
  components/gitpod-db/src/typeorm/accounting-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-subscription.ts
Labels: approved, size/L, lgtm, team: meta, release-note-none

#7012 [supervisor] Provide port Name and Description along with the port status
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/supervisor-api/go/status.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Status.java
  components/supervisor-api/status.proto
  components/supervisor/pkg/ports/ports.go
  components/supervisor/pkg/ports/ports_test.go
Labels: community-contribution, approved, lgtm, size/XXL, team: meta, team: IDE, release-note, cla: pending :hourglass_flowing_sand:

#7270 Use gp-code-server-test script
  test/tests/ide/python_ws_test.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7322 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7312 Link to user profile
  components/dashboard/src/projects/NewProject.tsx
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: approved, lgtm, size/S, team: meta, release-note

#7342 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7319 Setup IdentitiesOnly as yes in ssh config
  components/local-app/pkg/bastion/bastion.go
Labels: community-contribution, approved, lgtm, size/XS, team: IDE, release-note-none, cla: accepted :heavy_check_mark:

#7355 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7068 Improve colors used for labels and headings on dashboard integrations…
  components/dashboard/src/settings/Integrations.tsx
Labels: community-contribution, approved, lgtm, size/S, team: meta, release-note-none, cla: accepted :heavy_check_mark:

#7378 Fix Gitpod casing in proc tests
  components/ee/agent-smith/pkg/detector/proc.go
  components/ee/agent-smith/pkg/detector/proc_test.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none

#7372 [local-app] timeout the local app after special time of inactivity
  components/local-app/main.go
  components/local-app/pkg/bastion/bastion.go
Labels: community-contribution, approved, lgtm, size/M, team: IDE, release-note-none, cla: accepted :heavy_check_mark:

#7401 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none
