Repository gitpod-io/gitpod, pull requests merged in 2021-11, with the labels that each got.

#6425 Update canceled prebuild status icon
  components/dashboard/src/icons/StatusCanceled.svg
Labels: user experience, component: dashboard, feature: prebuilds, approved, lgtm, size/XS, team: meta, release-note-none

#6480 [gpctl] Add debug command
  dev/gpctl/cmd/debug-log.go
  dev/gpctl/cmd/debug.go
Labels: approved, size/L, lgtm, team: workspace, release-note

#6470 [ws-deployment] Add install gitpod partial step
  operations/workspace/deployment/README.md
  operations/workspace/deployment/example-config.yaml
  operations/workspace/deployment/pkg/common/cluster.go
  operations/workspace/deployment/pkg/common/context.go
  operations/workspace/deployment/pkg/config/v1/config.go
  operations/workspace/deployment/pkg/step/installgitpod.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none, component: workspace deployment

#6481 [ws-deployment] Refactor deployment methods so that steps(cluster create and gitpod installation) can be run for each cluster in parallel.
  operations/workspace/deployment/go.mod
  operations/workspace/deployment/go.sum
  operations/workspace/deployment/pkg/orchestrate/deploy.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none

#6498 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S, release-note-none

#6500 fix debug command for code-nightly
  .werft/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6376 Introduce project slug
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/migration/1634894637934-AddSlugToProject.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/ee/src/gitlab/gitlab-app-support.ts
  components/server/src/projects/projects-service.ts
Labels: approved, lgtm, size/M, team: meta, release-note

#6477 [teams] inactivate Leave Team action for last team owner
  components/dashboard/src/teams/Members.tsx
Labels: approved, lgtm, size/S, team: meta, release-note-none

#6424 [dashboard] add additional prebuild state to UI
  components/dashboard/src/projects/Prebuilds.tsx
Labels: component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#6484 [dashboard] Improve email address already in use
  components/dashboard/src/Login.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/provider-utils.tsx
  components/server/src/auth/errors.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/user/user-service.ts
Labels: approved, lgtm, size/M, team: meta, release-note-none

#6039 chore: capitalize proper noun Git in dashboard components
  components/dashboard/src/FromReferrer.tsx
  components/dashboard/src/Setup.tsx
  components/dashboard/src/prebuilds/InstallGitHubApp.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/settings/Account.tsx
  components/dashboard/src/settings/Integrations.tsx
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: community-contribution, approved, lgtm, size/M, team: meta, release-note

#6510 fix code nightly job
  .werft/code-nightly.yaml
Labels: approved, lgtm, release-note-none

#6511 Change MyApplicationActivationListener visibility
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/listeners/MyApplicationActivationListener.kt
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6497 [ws-deployment] Introduce context wrapper and overrides
  operations/workspace/deployment/cmd/deploy.go
  operations/workspace/deployment/cmd/root.go
  operations/workspace/deployment/pkg/common/cluster.go
  operations/workspace/deployment/pkg/common/context.go
  operations/workspace/deployment/pkg/orchestrate/deploy.go
  operations/workspace/deployment/pkg/step/createcluster.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none, component: workspace deployment

#6521 [changelog] support all case variations of "nOnE"
  .werft/changelog.yaml
  CHANGELOG.md
  dev/changelog/update.go
Labels: approved, lgtm, size/S, release-note-none

#6526 [installer] Build for every version
  components/BUILD.yaml
  installer/BUILD.yaml
  installer/cmd/render.go
  installer/cmd/root.go
  installer/cmd/version.go
  installer/cmd/versions.yaml
  installer/leeway.Dockerfile
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6495 [registry-facade] Add docs to registry-facade
  components/registry-facade/README.md
Labels: groundwork: scheduled, approved, lgtm, size/S, team: workspace, release-note

#6529 [build] Bump leeway to v0.2.8
  .gitpod.yml
  .werft/build.yaml
  .werft/code-nightly.yaml
  .werft/debug.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
Labels: approved, lgtm, size/S, release-note-none

#6539 [db] Fix updateUserPartial
  components/gitpod-db/src/typeorm/user-db-impl.ts
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#6537 Add tracing to Werft jobs
  .werft/build.ts
  .werft/build.yaml
  .werft/observability/monitoring-satellite.ts
  .werft/observability/tracing.ts
  .werft/package.json
  .werft/tsconfig.json
  .werft/util/gcloud.ts
  .werft/util/kubectl.ts
  .werft/util/shell.ts
  .werft/util/werft.ts
  .werft/wipe-devstaging.ts
  .werft/wipe-devstaging.yaml
  .werft/yarn.lock
Labels: approved, lgtm, size/XXL, release-note-none, team: platform

#6426 [jetbrains-image] Improve logging
  components/ide/jetbrains/image/startup.sh
  components/ide/jetbrains/image/status/main.go
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#6541 [db] Automatically migrate the 'migrations' table
  components/gitpod-db/BUILD.yaml
  components/gitpod-db/leeway.Dockerfile
  components/gitpod-db/migrate-migrations/0_2_0_down_procedure.sql
  components/gitpod-db/migrate-migrations/0_2_0_up_procedure.sql
  components/gitpod-db/migrate.sh
  components/gitpod-db/migrate_gcp.sh
Labels: approved, lgtm, size/M, groundwork: in review, team: meta, release-note-none

#6544 [db-sync] Upgrade argparse
  components/ee/db-sync/package.json
  yarn.lock
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#6538 [supervisor] Fix IDE shutdown
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#6527 Add jetbrains-backend-plugin resources as build srcs
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: approved, lgtm, size/XS, team: IDE, release-note-none, editor: jetbrains

#6540 [installer] Simplify config surface
  installer/pkg/common/objects.go
  installer/pkg/components/proxy/objects.go
  installer/pkg/components/ws-daemon/objects.go
  installer/pkg/config/v1/config.go
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6551 [jetbrains] Fix Heartbeat plugin connection error
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusProvider.kt
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6542 [gpctl] Support multiple container for debug logs
  dev/gpctl/cmd/debug-log.go
  dev/gpctl/pkg/util/kubernetes.go
Labels: approved, lgtm, size/M, team: workspace, release-note

#6560 [build] Add commit to version manifest
  components/BUILD.yaml
  components/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#6546 Include GitLab subgroups
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/server/src/projects/projects-service.ts
  components/server/src/repohost/repo-url.spec.ts
  components/server/src/repohost/repo-url.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, size/L, lgtm, team: meta, release-note

#6574 [installer]: add persistent volume claim to in cluster container registry
  installer/third_party/charts/docker-registry/values.yaml
Labels: component: install, approved, lgtm, size/XS, release-note

#6577 Preserve team scope in dashboard
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: user experience, component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#6582 [code] update stable to 1.62.0
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#6584 [installer]: allow img-builder ingress from server
  installer/pkg/components/image-builder-mk3/networkpolicy.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#6583 [installer] Embed helm dependencies
  installer/BUILD.yaml
  installer/pkg/helm/helm.go
  installer/third_party/charts/charts.go
  installer/third_party/charts/dockerRegistry.go
  installer/third_party/charts/jaegerOperator.go
  installer/third_party/charts/minio.go
  installer/third_party/charts/mysql.go
  installer/third_party/charts/rabbitmq.go
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6586 [code] switch nightly job to main again
  .werft/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6507 [dashboard] Add small UI changes for desktop IDEs
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/ide/jetbrains/image/supervisor-ide-config_goland.json
  components/ide/jetbrains/image/supervisor-ide-config_intellij.json
Labels: approved, lgtm, size/XS, team: meta, team: IDE, release-note-none

#5940 Add a guiding template for feature requests
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, lgtm, size/S, release-note-none

#6505 [dashboard] Remove feature flag for desktop IDEs
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/M, team: meta, release-note

#6599 [test] Add manual testing instructions for integration tests
  test/README.md
Labels: approved, lgtm, size/S, release-note-none

#5985 [test] Use configured username
  components/image-builder-bob/cmd/build.go
  components/image-builder-bob/pkg/builder/builder.go
  components/supervisor/pkg/supervisor/tasks.go
  components/supervisor/pkg/terminal/terminal.go
  test/entrypoint.sh
  test/leeway.Dockerfile
  test/pkg/integration/setup.go
  test/tests/components/content-service/content-service_test.go
  test/tests/components/server/server_test.go
  test/tests/workspace/contexts_test.go
Labels: approved, lgtm, size/M, team: meta, team: workspace, team: IDE, release-note-none

#6605 [db] Move migrations from *.sql to TS
  components/gitpod-db/BUILD.yaml
  components/gitpod-db/leeway.Dockerfile
  components/gitpod-db/migrate-migrations/0_2_0_down_procedure.sql
  components/gitpod-db/migrate-migrations/0_2_0_up_procedure.sql
  components/gitpod-db/migrate.sh
  components/gitpod-db/migrate_gcp.sh
  components/gitpod-db/package.json
  components/gitpod-db/src/migrate-migrations.ts
  components/gitpod-db/src/typeorm/migrate-migrations-0_2_0.ts
  components/gitpod-db/src/typeorm/typeorm.ts
Labels: approved, size/L, lgtm, groundwork: in review, team: meta, release-note-none

#6591 [installer]: create a configmap with a simplified installation manifest
  installer/cmd/render.go
  installer/pkg/common/display.go
  installer/pkg/common/sorter.go
Labels: approved, lgtm, size/XL, team: workspace, release-note

#6612 [db] Fix migrations config
  components/gitpod-db/src/config.ts
Labels: approved, lgtm, size/S, groundwork: in review, team: meta, release-note-none

#6607 [Analytics] Strip quotes of anonymous_id for identify call
  components/server/src/analytics.ts
Labels: approved, lgtm, size/S, team: meta, release-note-none

#6622 [db] Fix 'migrations' migration for GCP case
  chart/templates/db-migrations-job.yaml
  components/gitpod-db/migrate.sh
  components/gitpod-db/migrate_gcp.sh
  components/gitpod-db/typeorm.sh
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6609 [docker-up] Sligh wrap netns cleanup
  components/docker-up/docker-up/main.go
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none

#6503 [werft] Cleanup build.ts around KUBECONFIG
  .werft/build.ts
  .werft/util/certs.ts
  .werft/util/gpctl.ts
  .werft/util/kubectl.ts
  .werft/util/util.ts
  .werft/wipe-devstaging.ts
  .werft/yarn.lock
Labels: approved, lgtm, size/XL, groundwork: in review, team: meta, release-note-none

#6628 [registry-facade] Add supervisor ref to ImageSpec
  components/registry-facade-api/go/imagespec.pb.go
  components/registry-facade-api/imagespec.proto
  components/registry-facade/pkg/registry/registry.go
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6619 [ws-deployment] Add gitpod installation step
  operations/workspace/deployment/pkg/orchestrate/deploy.go
  operations/workspace/deployment/pkg/step/installgitpod.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none, component: workspace deployment

#6640 Fix select button
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, lgtm, size/S, team: meta, release-note-none

#6646 [werft] Fix version drift to make sure yarn.lock stays clean
  .werft/package.json
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#6647 Update .werft/yarn.lock after fresh yarn install
  .werft/yarn.lock
Labels: approved, lgtm, size/M, release-note-none

#6637 [ws-manager] Add supervisor ref to IDEImage
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_admission.json
Labels: approved, lgtm, size/XXL, team: workspace, release-note-none

#6621 [installer]: allow use of external container registry
  installer/pkg/components/blobserve/configmap.go
  installer/pkg/components/blobserve/deployment.go
  installer/pkg/components/image-builder-mk3/configmap.go
  installer/pkg/components/image-builder-mk3/deployment.go
  installer/pkg/components/proxy/configmap.go
  installer/pkg/components/registry-facade/configmap.go
  installer/pkg/components/registry-facade/daemonset.go
  installer/pkg/components/ws-manager/configmap_test.go
Labels: approved, lgtm, size/XL, team: workspace, release-note

#6624 Set version in Go components during build time
  WORKSPACE.yaml
  components/blobserve/BUILD.yaml
  components/content-service/BUILD.yaml
  components/ee/agent-smith/BUILD.yaml
  components/ee/kedge/BUILD.yaml
  components/ee/ws-scheduler/BUILD.yaml
  components/image-builder-mk3/BUILD.yaml
  components/image-builder/BUILD.yaml
  components/registry-facade/BUILD.yaml
  components/service-waiter/BUILD.yaml
  components/supervisor/BUILD.yaml
  components/workspacekit/BUILD.yaml
  components/ws-daemon/BUILD.yaml
  components/ws-manager/BUILD.yaml
  components/ws-proxy/BUILD.yaml
  dev/poolkeeper/BUILD.yaml
  operations/workspace/deployment/BUILD.yaml
Labels: approved, lgtm, size/S, team: meta, team: workspace, team: IDE, release-note-none

#6644 [ws-deployment] Add retry support within steps
  operations/workspace/deployment/cmd/deploy.go
  operations/workspace/deployment/pkg/common/cluster.go
  operations/workspace/deployment/pkg/orchestrate/deploy.go
  operations/workspace/deployment/pkg/step/createcluster.go
  operations/workspace/deployment/pkg/step/installgitpod.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none, component: workspace deployment

#6676 [helm-chart] Fix ws-daemon raid deployment
  chart/templates/ws-daemon-daemonset.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6659 [test] Build DBConfig from env var secrets
  test/pkg/integration/apis.go
Labels: approved, lgtm, size/M, release-note-none

#6677 [code] upgrade to vscode 1.62.2
  WORKSPACE.yaml
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6648 [supervisor] Remove old gp bin before symlink
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6697 [ws-proxy] Get supervisor image from pod annotation instead from ws-proxy config
  components/ws-proxy/BUILD.yaml
  components/ws-proxy/pkg/proxy/config.go
  components/ws-proxy/pkg/proxy/infoprovider.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6661 added an extra nodepool
  .werft/build.ts
  .werft/values.nodeAffinities_1.yaml
Labels: approved, lgtm, size/M, release-note-none

#6703 [jetbrains] Update to version 213.5744
  components/ide/jetbrains/image/BUILD.yaml
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6690 [code] update stable to 1.62.2
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#6714 [image-builder-mk3] Fix docker.io interaction
  components/image-builder-bob/pkg/proxy/proxy.go
Labels: approved, lgtm, size/XS, release-note-none

#6711 [dashboard] Show loading indicator when switching git providers to add a new project
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, lgtm, size/S, team: meta, release-note

#6718 [ws-scheduler] Set supervisor ref for ghosts
  chart/templates/ws-scheduler-configmap.yaml
  components/ee/ws-scheduler/pkg/scaler/driver.go
  installer/pkg/components/ws-scheduler/configmap.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#6722 [jetbrains] Wait for content before backend start
  components/ide/jetbrains/image/startup.sh
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6723 [dashboard] Prefer project.slug over project.name in Projects page links
  components/dashboard/src/projects/Projects.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6747 [dashboard] Change default color theme from Light → System
  components/dashboard/src/App.tsx
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note

#6753 [installer]: validate the AuthProvider config value
  installer/pkg/config/v1/config.go
Labels: approved, lgtm, size/S, team: workspace, release-note

#6754 Add JetBrains Update GitHub action
  .github/workflows/jetbrains-updates.yml
Labels: approved, size/L, lgtm, team: IDE, release-note-none

#6768 [dashboard] Make color theme preference backwards compatible
  components/dashboard/src/App.tsx
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6669 [server] Add and use supervisor image config
  chart/templates/server-ide-configmap.yaml
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/ide-config.ts
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/S, team: meta, release-note-none

#6671 [ide] Add VS Code desktop IDE options
  chart/templates/server-ide-configmap.yaml
  chart/values.yaml
  components/BUILD.yaml
  components/dashboard/src/components/CheckBox.tsx
  components/dashboard/src/images/vscodeInsiders.svg
  components/dashboard/src/settings/Preferences.tsx
  components/ide/code-desktop/BUILD.yaml
  components/ide/code-desktop/leeway.Dockerfile
  components/ide/code-desktop/startup.sh
  components/ide/code-desktop/status/BUILD.yaml
  components/ide/code-desktop/status/go.mod
  components/ide/code-desktop/status/go.sum
  components/ide/code-desktop/status/main.go
  components/ide/code-desktop/supervisor-ide-config_insiders.json
  components/ide/code-desktop/supervisor-ide-config_stable.json
Labels: approved, lgtm, size/XXL, team: meta, team: IDE, release-note

#6765 [image-builder-bob] Update buildkit
  components/image-builder-bob/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#6682 [ws-manager-bridge] Support forced cluster dereg
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.js
  components/ws-manager-bridge/src/cluster-service-server.ts
  dev/gpctl/cmd/clusters-deregister.go
Labels: approved, size/L, lgtm, team: meta, team: workspace, release-note

#6737 Change environment variable scope placeholder
  components/dashboard/src/settings/EnvironmentVariables.tsx
Labels: component: dashboard, approved, lgtm, size/XS, team: meta, release-note-none

#6774 [openvsx-proxy] Disable debug logging
  chart/templates/openvsx-proxy-configmap.yaml
  components/openvsx-proxy/pkg/handler.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#6781 [installer] Disable debug logging for openvsx-proxy
  installer/pkg/components/openvsx-proxy/configmap.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#6721 Remove team when sole owner and remove projects
  components/gitpod-db/src/team-db.spec.db.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/src/user/user-deletion-service.ts
Labels: approved, size/L, lgtm, team: meta, release-note

#6786 [ws-manager] Add test for affinity template merge
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.json
Labels: approved, lgtm, size/XL, team: workspace, release-note-none

#6639 [observability] Add ws team success criteria dashboard
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6780 replaced nodepool 3 with 0 for prev-envs
  .werft/build.ts
  .werft/values.nodeAffinities_0.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6783 [ws-manager-api] Log ws-manager call error
  components/ws-manager-api/typescript/src/promisified-client.ts
Labels: approved, lgtm, size/XS, release-note-none

#6652 [dashboard] show error message on new project for Bitbucket-only users
  components/dashboard/src/projects/NewProject.tsx
Labels: approved, lgtm, size/M, team: meta, release-note

#6742 [installer] Update IDE config
  installer/pkg/components/blobserve/configmap.go
  installer/pkg/components/server/ide-configmap.go
  installer/pkg/components/server/types.go
  installer/pkg/components/workspace/constants.go
  installer/pkg/components/ws-scheduler/configmap.go
  installer/pkg/config/versions/versions.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none

#6733 [ws-daemon] Umount dangling mask mounts
  components/ws-daemon/pkg/iws/iws.go
Labels: approved, lgtm, size/M, team: workspace, release-note

#6809 [code] upgrade to vscode 1.62.3
  WORKSPACE.yaml
Labels: approved, lgtm, size/XS, release-note-none

#6812 [code] update stable to 1.62.3
  chart/values.yaml
Labels: approved, lgtm, size/XS, release-note

#6822 Add installer folder to vscode settings
  gitpod-ws.code-workspace
Labels: approved, lgtm, size/XS, release-note-none

#6824 [installer] Remove Jobs after a minute of completion
  installer/pkg/components/database/init/job.go
  installer/pkg/components/migrations/job.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#6825 [installer] Update kube-rbac-proxy container and reduce log level
  installer/pkg/common/common.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#6813 [payment] added more resilience to GitHub payment endpoint
  components/ee/payment-endpoint/src/github/subscription-reconciler.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6784 [Analytics] Fix domain and Expiration date in Dashboard's Segment Cookie
  components/dashboard/src/Analytics.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6836 [image-builder-mk3]: set x-forwarded-for header value to 127.0.0.1
  components/image-builder-bob/pkg/proxy/proxy.go
Labels: approved, lgtm, size/S, release-note

#6838 [jetbrains] Remove werft secret
  .werft/build.ts
  .werft/build.yaml
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/image/BUILD.yaml
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#6845 [ops] Add dashboard "Meta Services"
  operations/observability/mixins/meta/dashboards/components/meta-services.json
Labels: approved, lgtm, size/XL, team: meta, release-note-none

#6854 .werft/observability: Simplify deployment logic
  .werft/observability/monitoring-satellite.ts
Labels: approved, lgtm, size/M, release-note-none, team: platform

#6856 .werft/observability: Align rendering cmd with latest changes
  .werft/observability/monitoring-satellite.ts
Labels: approved, lgtm, size/XS, release-note-none, team: platform

#6837 Fix JetBrains update GitHub action
  .github/workflows/jetbrains-updates.yml
Labels: approved, lgtm, size/XS, team: IDE, release-note-none, editor: jetbrains

#6775 [db] Make hand-written transformers more robust against odd DB values
  components/gitpod-db/src/typeorm/entity/db-prebuild-info-entry.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
Labels: approved, lgtm, size/M, groundwork: in review, team: meta, release-note

#6866 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M, release-note-none

#6031 add GIT_AUTHOR_EMAIL
  components/dashboard/src/settings/Account.tsx
Labels: meta: never-stale, approved, lgtm, size/XS, team: meta, release-note

#6862 [installer]: set affinities for pods and jobs
  installer/pkg/components/blobserve/deployment.go
  installer/pkg/components/content-service/deployment.go
  installer/pkg/components/dashboard/deployment.go
  installer/pkg/components/database/incluster/helm.go
  installer/pkg/components/database/init/job.go
  installer/pkg/components/image-builder-mk3/deployment.go
  installer/pkg/components/migrations/job.go
  installer/pkg/components/minio/incluster/minio.go
  installer/pkg/components/openvsx-proxy/statefulset.go
  installer/pkg/components/proxy/deployment.go
  installer/pkg/components/rabbitmq/helm.go
  installer/pkg/components/registry-facade/daemonset.go
  installer/pkg/components/server/deployment.go
  installer/pkg/components/ws-manager-bridge/deployment.go
  installer/pkg/components/ws-manager/deployment.go
  installer/pkg/components/ws-proxy/deployment.go
  installer/pkg/components/ws-scheduler/deployment.go
  installer/pkg/helm/helm.go
Labels: approved, size/L, lgtm, team: workspace, release-note

#6873 [changelog] fixed changelog
  .werft/changelog.yaml
  CHANGELOG.md
  dev/changelog/update.go
Labels: approved, size/L, lgtm, release-note-none

#6880 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6881 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6882 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6884 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6885 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6890 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6891 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6889 Revert "[db] Make hand-written transformers more robust against odd D…
  components/gitpod-db/src/typeorm/entity/db-prebuild-info-entry.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
Labels: approved, lgtm, size/M, team: meta, release-note-none

#6892 Use forked Minio charts
  chart/Chart.yaml
  chart/dependencies/minio/.helmignore
  chart/dependencies/minio/Chart.yaml
  chart/dependencies/minio/README.md
  chart/dependencies/minio/ci/distributed-values.yaml
  chart/dependencies/minio/templates/NOTES.txt
  chart/dependencies/minio/templates/_helper_create_bucket.txt
  chart/dependencies/minio/templates/_helpers.tpl
  chart/dependencies/minio/templates/clusterroles.yaml
  chart/dependencies/minio/templates/configmap.yaml
  chart/dependencies/minio/templates/deployment.yaml
  chart/dependencies/minio/templates/ingress.yaml
  chart/dependencies/minio/templates/networkpolicy.yaml
  chart/dependencies/minio/templates/poddisruptionbudget.yaml
  chart/dependencies/minio/templates/post-install-create-bucket-job.yaml
  chart/dependencies/minio/templates/post-install-prometheus-metrics-job.yaml
  chart/dependencies/minio/templates/post-install-prometheus-metrics-role.yaml
  chart/dependencies/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  chart/dependencies/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
  chart/dependencies/minio/templates/pvc.yaml
  chart/dependencies/minio/templates/rolebindings.yaml
  chart/dependencies/minio/templates/secrets.yaml
  chart/dependencies/minio/templates/securitycontextconstraints.yaml
  chart/dependencies/minio/templates/service.yaml
  chart/dependencies/minio/templates/serviceaccount.yaml
  chart/dependencies/minio/templates/servicemonitor.yaml
  chart/dependencies/minio/templates/statefulset.yaml
  chart/dependencies/minio/values.yaml
Labels: approved, lgtm, size/XXL, release-note

#6857 Unshallow repo after workspace is ready
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/M, team: IDE, release-note-none

#6911 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6913 updated Chart.lock
  chart/Chart.lock
Labels: approved, lgtm, size/XS

#6914 [changelog] updated changelog
  chart/Chart.lock
Labels: approved, lgtm, size/XS, release-note-none

#6915 [changelog] updated changelog
  chart/Chart.lock
Labels: approved, lgtm, size/XS, release-note-none

#6893 [installer]: set all internal certs to 90 days duration
  installer/pkg/common/constants.go
  installer/pkg/components/cluster/certmanager.go
  installer/pkg/components/docker-registry/certificate.go
  installer/pkg/components/registry-facade/certificate.go
  installer/pkg/components/ws-daemon/tlssecret.go
  installer/pkg/components/ws-manager/tlssecret.go
Labels: approved, lgtm, size/M, team: workspace, release-note

#6834 [monitoring] Update overview dashboard
  operations/observability/mixins/meta/dashboards/components/meta-overview.json
Labels: approved, lgtm, size/XXL, team: meta, release-note-none

#6878 feat(dashboard): redirect /memes to the website
  components/dashboard/src/App.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6883 [dashboard][server] Make all project slugs unique within a team or user account by adding a unique suffix
  components/dashboard/src/projects/NewProject.tsx
  components/server/src/projects/projects-service.ts
Labels: approved, lgtm, size/S, team: meta, release-note

#6917 [Analytics] Fix path prop of dashboard_clicked event
  components/dashboard/src/App.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6925 [gitpod-protocol] Remove HTTP headers from logs
  components/gitpod-protocol/go/reconnecting-ws.go
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6946 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6947 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6948 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6949 [server] Prevent blocked users from starting new prebuilds
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6951 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6953 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6790 [dashboard] Extract IDE preferences data
  components/dashboard/src/components/CheckBox.tsx
  components/dashboard/src/components/SelectableCard.tsx
  components/dashboard/src/images/ideLogos.ts
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/XL, team: meta, team: IDE, release-note-none

#6958 [changelog] don't duplicate last entry
  .werft/changelog.yaml
  CHANGELOG.md
  dev/changelog/update.go
Labels: approved, lgtm, size/S, team: meta, release-note-none

#6603 Clean up Jetbrains Backend plugin
  .gitignore
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/listeners/MyApplicationActivationListener.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/ControllerStatusService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/HeartbeatService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/ide/jetbrains/backend/services/SupervisorInfoService.kt
Labels: approved, size/L, lgtm, team: IDE, release-note-none

#6926 [installer]: validate that cluster meets minimum kubernetes version
  installer/pkg/cluster/checks.go
  installer/pkg/cluster/validation.go
Labels: approved, size/L, lgtm, team: workspace, release-note

#6933 chart/template: Fix tracing endpoint variable
  .werft/values.dev.yaml
  chart/templates/_helpers.tpl
Labels: approved, lgtm, size/XS, release-note

#6961 moved job to build code-nightly from werft to github-actions
  .github/workflows/code-nightly.yaml
  .werft/code-nightly.yaml
Labels: approved, lgtm, size/M

#6968 [image-builder] Workaround buildkit#2484
  components/image-builder-bob/BUILD.yaml
  components/image-builder-bob/cmd/runc-facade/main.go
  components/image-builder-bob/leeway.Dockerfile
Labels: approved, size/L, lgtm, team: workspace, release-note-none

#6975 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#6978 [db] Fix indexExists
  components/gitpod-db/src/typeorm/migration/helper/helper.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#6962 Add download button
  components/dashboard/src/admin/WorkspaceDetail.tsx
Labels: component: dashboard, approved, lgtm, size/S, team: meta, release-note-none

#6966 [dashboard] When creating a new Project in your personal account, don't ask under which team to create it
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note

#6971 Adjust success criteria dashboard grouping period
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: approved, lgtm, size/XS, team: workspace, release-note

#6985 [installer]: set max ghost workspaces to 0
  installer/pkg/components/ws-scheduler/configmap.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none
