Repository gitpod-io/gitpod, pull requests merged in 2021-07, with the labels that each got.

#4705 [server] Update more GitLab integration settings URLs
  chart/values.yaml
  components/dashboard/src/service/service-mock.ts
  components/server/src/gitlab/gitlab-urls.ts
  dev/manual-tests/testsuite.yaml
  install/docker/examples/gitpod-gitlab/values/auth-providers.yaml
Labels: component: dashboard, component: server

#4698 feat(db): update examples in the dashboard
  components/gitpod-db/src/typeorm/migration/1625458087438-UpdateExamples.ts
Labels: aspect: examples, component: db

#4738 [code] serve each webview from own origin
  chart/templates/ws-manager-configmap.yaml
  components/ide/code/leeway.Dockerfile
  components/proxy/conf/Caddyfile
  components/supervisor-api/go/info.pb.go
  components/supervisor-api/info.proto
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/services.go
  components/ws-manager/pkg/manager/config.go
  components/ws-manager/pkg/manager/create.go
  components/ws-proxy/pkg/proxy/pass.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
  components/ws-proxy/pkg/proxy/workspacerouter.go
  components/ws-proxy/pkg/proxy/workspacerouter_test.go
Labels: approved, size/XL

#4837 [ws-manager] Pull images if not present
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
  components/ws-manager/pkg/manager/testdata/cdwp_ghost.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_probe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
  components/ws-manager/pkg/manager/testdata/cdwp_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
  components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
  components/ws-manager/pkg/manager/testdata/getWorkspaces_podOnly.json
  components/ws-manager/pkg/manager/testdata/status_brokenScheduler_UNKNOWN00.json
  components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED02.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED03.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.json
  components/ws-manager/pkg/manager/testdata/status_errimgpull.json
  components/ws-manager/pkg/manager/testdata/status_errimgpull_CREATING01.json
  components/ws-manager/pkg/manager/testdata/status_failedBeforeStopping_explicitFail.json
  components/ws-manager/pkg/manager/testdata/status_failedLogs_UNKNOWN00.json
  components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN01.json
  components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN02.json
  components/ws-manager/pkg/manager/testdata/status_failedTheiaMount_PENDING00.json
  components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.json
  components/ws-manager/pkg/manager/testdata/status_firstUserActivity_RUNNING.json
  components/ws-manager/pkg/manager/testdata/status_imagespec_RUNNING00.json
  components/ws-manager/pkg/manager/testdata/status_interrupted.json
  components/ws-manager/pkg/manager/testdata/status_interrupted_CREATING00.json
  components/ws-manager/pkg/manager/testdata/status_interrupted_networkNotReady_1_event_only.json
  components/ws-manager/pkg/manager/testdata/status_interrupted_networkNotReady_2_event_and_exitcode.json
  components/ws-manager/pkg/manager/testdata/status_interrupted_networkNotReady_3_recovered_CONSTRUCTED.json
  components/ws-manager/pkg/manager/testdata/status_ownerToken.json
  components/ws-manager/pkg/manager/testdata/status_prebuildFail_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_prebuildFail_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_stuckInCreating_CREATING00.json
  components/ws-manager/pkg/manager/testdata/stopping_basic.json
  components/ws-manager/pkg/manager/testdata/timeout_interrupted_noActivity.json
  components/ws-manager/pkg/manager/testdata/timeout_interrupted_withActivity.json
Labels: approved, lgtm, size/L

#4813 [server] Handle `releases/tag/<tag>` in GitHub context parser
  components/server/src/github/github-context-parser.spec.ts
  components/server/src/github/github-context-parser.ts
Labels: approved, lgtm

#4847 [content-service] Improve CPU utilization for initial git clone command
  components/content-service/pkg/git/git.go
Labels: approved, lgtm, size/XS

#4867 Fix node-root path for new nodepool of core-dev
  .werft/values.dev.yaml
Labels: approved, lgtm, size/XS

#4865 [server] Fix GitLab testEmptyProject test
  components/server/src/gitlab/gitlab-context-parser.spec.ts
Labels: approved, lgtm, size/XS

#4866 [server] Remove misleading log in AdditionalContentPrefixContextParser
  components/server/src/workspace/additional-content-prefix-context-parser.ts
Labels: approved, lgtm, size/XS

#4836 Update Gitpod k3s Docker image for release 0.10.0
  install/docker/README.md
  install/docker/examples/gitpod-3-nodes/README.md
  install/docker/examples/gitpod-3-nodes/docker-compose.yaml
  install/docker/examples/gitpod-gitlab/gitlab/Dockerfile
  install/docker/examples/gitpod/docker-compose.yaml
  install/docker/gitpod-image/Dockerfile
  install/docker/gitpod-image/entrypoint.sh
  install/docker/gitpod-image/values.yaml
Labels: approved, lgtm, size/L

#4878 Adding myself to meta owners :-)
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#4870 [dashboard] Fix email notifications checkbox
  components/dashboard/src/settings/Notifications.tsx
Labels: approved, lgtm, size/M

#4873 docs(readme): add link to our discord server
  README.md
Labels: approved, documentation, lgtm, size/XS

#4880 Fix db-migration order prior to deploying to production
  components/gitpod-db/src/typeorm/migration/1626784647462-WorkspaceInstanceStoppingTime.ts
Labels: approved, lgtm, size/XS

#4883 [ws-manmager] Remove span logs from WorkspaceReadyProbe
  components/ws-manager/pkg/manager/probe.go
Labels: approved, lgtm, size/XS

#4683 [ws-daemon] Remove Containerd4214 workaround
  components/ws-daemon/pkg/daemon/containerd4214.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: approved, lgtm, size/L

#4888 [server] Don't count ToS rejection to login metric
  components/server/src/auth/generic-auth-provider.ts
Labels: approved, lgtm, size/XS

#4887 Fix proxy deployment manifest duplicated keys
  chart/templates/proxy-deployment.yaml
Labels: approved, lgtm, size/XS

#4895 [werft] Remove left-over installer build
  .werft/build.ts
Labels: approved, lgtm, size/XS

#4905 [content-service] Start snapshots from-other
  components/content-service/pkg/initializer/snapshot.go
Labels: approved, lgtm, size/XS

#4910 [gitpod-db] Don't count stopping instances as running
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: approved, lgtm, size/XS

#4631 Implement project configurator
  components/dashboard/package.json
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/MonacoEditor.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/start/WorkspaceLogs.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/migration/1626853418369-ProjectConfiguration.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/additional-content-prefix-context-parser.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  yarn.lock
Labels: approved, component: dashboard, lgtm, roadmap item: teams & projects, size/XXL

#4891 [analytics] fixed anonymous ID trait in identify()
  components/server/package.json
  components/server/src/auth/login-completion-handler.ts
  components/server/src/server.ts
  components/server/src/user/user-controller.ts
  yarn.lock
Labels: approved, lgtm, size/M

#4912 [workspacekit] Discover bind mount paths
  components/workspacekit/cmd/rings.go
  components/workspacekit/cmd/rings_test.go
  components/workspacekit/go.mod
Labels: approved, lgtm, size/L

#4916 Fix lodgen benchmark cloneTargets
  dev/loadgen/prod-benchmark.yaml
Labels: approved, lgtm, size/S

#4903 [supervisor] Add unit tests for task composition
  components/content-service/go.mod
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/supervisor/tasks.go
  components/supervisor/pkg/supervisor/tasks_test.go
Labels: approved, lgtm, size/L

#4807 Upgrade to VS Code 1.58.2
  components/ide/code/leeway.Dockerfile
Labels: approved, lgtm, size/XS

#4930 Revert "[ws-daemon] Remove Containerd4214 workaround"
  components/ws-daemon/pkg/daemon/containerd4214.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: approved, lgtm, size/L

#4941 [ws-daemon] Always remove temp backup file
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/XS

#4944 [server/analytics] fix filter for unconfirmed user
  components/server/src/auth/generic-auth-provider.ts
Labels: approved, lgtm, size/S

#4953 [content-service] Log error if is not related to ErrBucketNotExist
  components/content-service/pkg/storage/gcloud.go
Labels: approved, lgtm, size/XS

#4952 [ws-daemon] Filter tasks log if the file does not exists
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/XS

#4954 [ws-proxy] Skip DNS errors when workspace is not available
  components/ws-proxy/pkg/proxy/pass.go
Labels: approved, lgtm, size/XS

#4917 [dashboard] Minor Teams & Projects UI fixes
  components/dashboard/src/components/MonacoEditor.tsx
  components/dashboard/src/projects/ConfigureProject.tsx
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: approved, component: dashboard, lgtm, size/S

#4957 Revert "DO NOT MERGE THIS"
  components/dashboard/src/service/service.tsx
  components/licensor/typescript/ee/src/index.ts
Labels: approved, lgtm, size/M

#4960 [prow] Add csweichel to meta owner list
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#4956 [agent-smith] Disable by default
  chart/values.yaml
Labels: approved, lgtm, size/XS

#4969 [ws-daemon] Currectly use limit writer
  components/content-service/pkg/storage/gcloud.go
  components/content-service/pkg/storage/minio.go
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/S

#4980 fix(.github): security policy item gets automatically created when SECURITY.md exists
  .github/ISSUE_TEMPLATE/config.yml
Labels: approved, lgtm, size/XS

#4915 Remove old headless log infrastructure
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/headless-workspace-log.ts
  components/server/ee/src/prebuilds/prebuild-queue-maintainer.ts
  components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/messagebus-integration.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-bridge/ee/src/bridge.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/messagebus-integration.ts
  components/ws-manager-bridge/src/wsman-subscriber.ts
  components/ws-manager/pkg/manager/manager.go
  components/ws-proxy/pkg/proxy/infoprovider_test.go
Labels: approved, lgtm, size/XXL

#4987 [chart] Remove deprecated field 'maxBackupSize' from _helpers.tpl
  chart/templates/_helpers.tpl
Labels: approved, lgtm, size/XS

#4990 [chart] Set workspace size limit
  chart/values.yaml
Labels: approved, lgtm, size/XS

#4994 [ws-daemon] Remove old sandboxing behaviour
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/quota/mounts.go
  components/ws-daemon/pkg/quota/mounts_test.go
  components/ws-daemon/pkg/quota/sandbox_linux.go
Labels: approved, lgtm, size/XL

#4996 [ws-daemon] Filter tasks log if the file does not exists
  components/ws-daemon/pkg/resources/controller.go
Labels: approved, lgtm, size/XS

#4995 [ws-daemon] Don't remove the backup tar before uploading it
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/S

#4986 [dashboard] Fix alignment of pending changes widget in workspaces list
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: approved, component: dashboard, lgtm, size/XS

#5013 [ws-manager] Don't nil-deref on timeout computation
  components/ws-manager/pkg/manager/status.go
Labels: approved, lgtm, size/XS

#5010 [image-builder] Support whitelisted registries in GP layer build
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Labels: approved, lgtm, size/S

#5015 [gpctl] Improve image builds
  dev/gpctl/cmd/imagebuilds-build.go
  dev/gpctl/cmd/imagebuilds.go
Labels: approved, lgtm, size/S
