Repository gitpod-io/gitpod, pull requests merged in 2022-02, with the labels that each got.

#7935 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7926 [ws-manager] Refactor connectToWorkspaceDaemon helper
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/manager_test.go
Labels: approved, size/L, lgtm, team: workspace, release-note

#7839 [installer]: put component ownership under webapp/workspace teams
  installer/cmd/render.go
  installer/pkg/components/components-webapp/OWNERS
  installer/pkg/components/components-webapp/components.go
  installer/pkg/components/components-workspace/OWNERS
  installer/pkg/components/components-workspace/components.go
  installer/pkg/components/components.go
Labels: approved, size/L, lgtm, team: workspace, release-note, team: self-hosted

#7915 [installer]: add yq and kubectl to docker image
  installer/leeway.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none, team: self-hosted

#7933 [installer]: add the Installer config to a configmap for debugging
  installer/pkg/components/gitpod/configmap.go
Labels: approved, lgtm, size/S, release-note-none, team: self-hosted

#7913 [ReadMe] - update Integrated Code reviews link
  README.md
Labels: community-contribution, approved, lgtm, size/XS, release-note-none, cla: accepted :heavy_check_mark:

#7967 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7960 Fix project details layout
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/admin/Property.tsx
Labels: component: dashboard, approved, lgtm, size/XS, team: webapp, release-note-none

#7961 Write unique error message if ready file create fails
  components/content-service/pkg/initializer/initializer.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7954 .werft/observability: Add stackdriver support
  .werft/build.ts
  .werft/build.yaml
  .werft/observability/monitoring-satellite.ts
Labels: approved, lgtm, size/S, release-note-none, team: platform

#7893 Added a script to download k3s kubeconfig for preview-environments
  dev/preview/install-k3s-kubeconfig.sh
  dev/preview/ssh-vm.sh
Labels: approved, lgtm, size/M, release-note-none

#7970 add felladrin to IDE team
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none

#7727 [installer]: add jaeger sampling options to the tracing object
  installer/pkg/common/common.go
  installer/pkg/components/agent-smith/daemonset.go
  installer/pkg/components/blobserve/deployment.go
  installer/pkg/components/content-service/deployment.go
  installer/pkg/components/image-builder-mk3/deployment.go
  installer/pkg/components/registry-facade/daemonset.go
  installer/pkg/components/server/deployment.go
  installer/pkg/components/ws-daemon/daemonset.go
  installer/pkg/components/ws-manager-bridge/deployment.go
  installer/pkg/components/ws-manager/deployment.go
  installer/pkg/components/ws-proxy/deployment.go
  installer/pkg/config/v1/experimental/experimental.go
  installer/pkg/config/v1/experimental/validation.go
  installer/pkg/config/v1/validation.go
Labels: approved, size/L, lgtm, team: webapp, team: workspace, release-note, team: self-hosted, installer: needs interface change

#7972 observability/mixins: Add Makefile step that generates dashboards
  operations/observability/mixins/.gitignore
  operations/observability/mixins/Makefile
  operations/observability/mixins/dashboards.jsonnet
Labels: approved, lgtm, size/S, release-note-none, team: platform

#7952 use fragment instead of query in jetbrains gateway links
  components/ide/jetbrains/image/status/main.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7974 Added KUBCONFIG to /etc/bash.bashrc
  .werft/vm/manifests.ts
  .werft/vm/vm.ts
Labels: approved, lgtm, size/XS, release-note-none

#7987 [werft] Disable telemetry job for preview environments
  .werft/post-process.sh
Labels: approved, lgtm, size/XS, release-note-none

#7976 gpctl: Introduce client metadata headers
  dev/gpctl/cmd/clusters.go
  dev/gpctl/cmd/imagebuilds.go
  dev/gpctl/cmd/workspaces.go
  dev/gpctl/pkg/util/grpc.go
Labels: approved, lgtm, size/M, team: webapp, team: workspace, release-note-none

#7990 Add blobserve rules for new vscode insiders
  chart/templates/blobserve-configmap.yaml
  components/blobserve/pkg/blobserve/blobspace.go
  installer/pkg/components/blobserve/configmap.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7993 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7977 Introduce GitHub Action to apply team labels based on reviewers
  .github/workflows/team-labeler.yml
Labels: approved, lgtm, size/S, release-note-none, team: platform

#7984 werft: Close slice spans
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#7985 [jb-gateway] fix awt deadlocks
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#7998 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: approved, lgtm, size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#8000 Fix typo in CODEOWNERS file
  .github/CODEOWNERS
Labels: approved, lgtm, size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#8001 [db] Add index for all queries on DBPrebuildWorkspaceUpdatable
  components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace-updatable.ts
  components/gitpod-db/src/typeorm/migration/1643879235654-PWSUIndexes.ts
Labels: approved, lgtm, size/M, team: webapp, release-note-none

#7999 fix team owner style
  components/dashboard/src/admin/ProjectDetail.tsx
Labels: approved, lgtm, size/XS, team: webapp, release-note-none

#7978 [gitlab] support nested repos in envvar patterns
  components/gitpod-protocol/src/protocol.ts
Labels: approved, lgtm, size/XS, team: webapp, release-note

#7940 [server] Change PeriodicDeleter interval: 2s->30s
  components/gitpod-db/src/periodic-deleter.ts
Labels: approved, lgtm, size/M, team: webapp, release-note

#7968 [ws-manager-bridge] update prebuild state properly
  components/ws-manager-bridge/ee/src/bridge.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: approved, lgtm, size/S, team: webapp, release-note

#8008 [ws-manager-api] Fix cluster selection
  components/ws-manager-api/typescript/src/client-provider.spec.ts
  components/ws-manager-api/typescript/src/client-provider.ts
Labels: approved, lgtm, size/S, release-note-none

#7948 Chaged docker port from 2475 to back to 2375
  .werft/build.yaml
  .werft/clean-up-werft-build-nodes.yaml
  .werft/debug.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7989 fix nil pointer deref when trying to log an error in docker-up
  components/docker-up/docker-up/main.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#8016 fix typo in assignment
  components/docker-up/docker-up/main.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7930 Update to vscode 1.64
  WORKSPACE.yaml
  components/ide/code/supervisor-ide-config.json
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#8019 [code] update stable to 1.64
  chart/values.yaml
  installer/pkg/components/workspace/ide/constants.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#8011 Added support to send logs from preview-environment to GCP
  .werft/build.ts
  .werft/build.yaml
  .werft/vm/charts/fluentbit/values.yaml
  .werft/vm/vm.ts
Labels: approved, lgtm, size/M, release-note-none, team: platform

#8004 Switch to our own libseccomp bindings
  components/workspacekit/go.mod
  components/workspacekit/go.sum
  components/ws-daemon/nsinsider/go.mod
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7982 ws-manager-bridge: Print audit logs when client header is set
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: approved, lgtm, size/S, team: webapp, team: workspace, release-note-none

#8023 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#8033 Update dev-environment image for gpctl changes
  .gitpod.yml
  .werft/build.yaml
  .werft/clean-up-werft-build-nodes.yaml
  .werft/debug.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#8038 Temporarily pin insiders to stable branch
  .github/workflows/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#8039 Fix code-nightly workflow typo and upgrade leeway
  .github/workflows/code-nightly.yaml
Labels: approved, lgtm, size/XS, release-note-none

#7966 add coredns dashboard
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/coredns.json
Labels: approved, lgtm, size/XXL, team: workspace, release-note-none, team: platform

#8047 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7912 add ssh load test
  dev/ssh-load-test/README.md
  dev/ssh-load-test/cmd/lotconn.go
  dev/ssh-load-test/cmd/reopen.go
  dev/ssh-load-test/cmd/root.go
  dev/ssh-load-test/go.mod
  dev/ssh-load-test/go.sum
  dev/ssh-load-test/step4-ws-proxy-mem.png
Labels: approved, lgtm, size/XXL, release-note-none

#8057 Fixed payment binding
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#8062 [ci] Fix JB Nightly GitHub Action
  .github/workflows/jetbrains-auto-update-template.yml
Labels: size/S, team: IDE, release-note-none

#8069 remove not exist components gateway-plugin:plugin
  .gitpod.yml
Labels: size/XS, release-note-none

#8071 [server] Replace nextTick with setImmediate
  components/server/src/workspace/headless-log-controller.ts
Labels: size/XS, team: webapp, release-note-none

#8073 [server, dashboard] Do basic rate limiting on startWorkspace
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/messaging/connection-error-handler.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/L, team: webapp, release-note

#8078 Point code nightly job back to main
  .github/workflows/code-nightly.yaml
Labels: size/XS, team: IDE, release-note-none

#8079 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#8080 [observability] add cross-teams codeowners
  .github/CODEOWNERS
Labels: size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#7931 add alert for conntrack table getting full
  operations/observability/mixins/cross-teams/rules/components/nodes/alerts.libsonnet
Labels: approved, lgtm, size/M, team: workspace, release-note-none, team: platform

#8072 Werft: Force default annotations for main build
  .werft/build.ts
Labels: size/S, release-note-none, team: platform

#8040 .werft: Add honeycomb trace as job result
  .werft/util/werft.ts
Labels: size/XS, release-note-none, team: platform

#8068 [jetbrains] label release update PRs with IDE label
  .github/workflows/jetbrains-updates-template.yml
Labels: size/XS, team: IDE, release-note-none

#8083 [jb][gw] allow to install without restart
  components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/XS, team: IDE, release-note-none

#8085 Werft: Don't fail main jobs for failed deployments
  .werft/build.ts
Labels: size/L, release-note-none, team: platform

#8061 [workspacekit] make /etc/hosts modifiable
  components/workspacekit/cmd/rings.go
  components/workspacekit/cmd/rings_test.go
Labels: size/M, team: workspace, release-note-none

#8093 [server] fix for wrong token selected if multiple
  components/gitpod-db/src/typeorm/user-db-impl.ts
Labels: size/XS, team: webapp, release-note

#8095 Fix credential helper regression
  components/gitpod-cli/cmd/credential-helper.go
Labels: size/S, team: IDE, release-note-none

#8116 Relax CODEOWNERS review requirements
  .github/CODEOWNERS
Labels: size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#8100 [protocol] Make ContextURL.parseToURL support the newly-accepted 'git@{host}:{user}/{repo}.git' format
  components/gitpod-protocol/src/context-url.spec.ts
  components/gitpod-protocol/src/context-url.ts
Labels: size/M, team: webapp, release-note

#8094 Create an index for contextURL column
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/migration/1644327547997-IndexWorkspaceContextUrl.ts
Labels: size/S, team: webapp, release-note-none

#8119 [ws-daemon] Support git lfs
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note

#8090 Update GitpodWorkspaceTooManyRegularNotActive severity level
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#8110 Update code dockerfile
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/S, team: IDE, release-note-none

#8121 Fix overflow on port not found page
  components/ws-proxy/public/port-not-found.html
Labels: community-contribution, size/XS, release-note-none

#8126 Truncate workspace name on workspace start page
  components/dashboard/src/start/StartWorkspace.tsx
Labels: user experience, component: dashboard, size/XS, team: webapp, release-note-none

#8123 Werft: Add attribute that identifies runs with VMs pre-made
  .werft/build.ts
  .werft/util/werft.ts
Labels: size/XS, release-note-none, team: platform

#8087 werft/config: Delete core-dev namespace on branch delete
  .github/CODEOWNERS
  .werft/config.yaml
  .werft/delete-preview-environments/delete-preview-environment.ts
  .werft/delete-preview-environments/delete-preview-environment.yaml
Labels: size/L, release-note-none, team: platform

#8134 workspacekit: Enable scmpid check.
  components/workspacekit/pkg/seccomp/notify.go
Labels: size/S, team: workspace, release-note

#8136 Log cfs quota and period
  components/ws-daemon/pkg/cpulimit/cfs.go
Labels: size/XS, team: workspace, release-note-none

#8141 Update code to 1.64.2
  WORKSPACE.yaml
Labels: size/XS, team: IDE, release-note-none

#8109 Use procfs library for reading proc files
  components/gitpod-cli/cmd/credential-helper.go
  components/gitpod-cli/cmd/credential-helper_test.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
Labels: size/L, team: IDE, release-note-none

#8143 Update code stable to v1.64.2
  chart/values.yaml
  installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#8152 [server] Disable inference of extensions
  components/server/src/config/config-inferrer.spec.ts
  components/server/src/config/config-inferrer.ts
  components/server/src/config/configuration-service.ts
Labels: size/XS, team: webapp, release-note-none

#8163 remove contact support message
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden
Labels: size/XS, team: workspace, release-note-none

#8168 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8160 [supervisor] Improve init shutdown behaviour
  components/supervisor/cmd/init.go
Labels: size/L, team: IDE, release-note-none

#8170 fix panic if ssh server failed to start
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#8176 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8164 increase downloadOTS attempts to 20
  components/content-service/pkg/initializer/initializer.go
Labels: size/XS, team: workspace, release-note-none

#8182 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8181 Ensure docker in workspace works with fuse
  components/workspacekit/cmd/rings.go
Labels: size/S, team: workspace, release-note

#8125 [dashboard, supervisor, ws-proxy] Break redirect loop on failing workspaces starts
  components/dashboard/package.json
  components/dashboard/src/App.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/supervisor/frontend/src/index.ts
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
  yarn.lock
Labels: size/L, release-note

#8185 Add alerts for excessive GC of ws-daemon
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Labels: size/M, team: workspace, release-note

#8204 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8214 [server] Order suggested repository URLs case-insensitively
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#8216 jb-gw: consolidate welcome and recent screens
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/Workspace.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceInstance.java
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthCallbackHandler.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectorView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodRecentConnections.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/XXL, team: IDE, release-note-none

#8218 jb-gw: wrap start hint comment if it does not fit
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
Labels: size/XS, release-note-none

#8219 [protocol] Fix toPermissionSet
  components/gitpod-protocol/src/permission.ts
Labels: size/XS, team: webapp, release-note-none

#8166 Bump Node version for building the VS Code image
  WORKSPACE.yaml
  components/ide/code/BUILD.yaml
  components/ide/code/bin/code
  components/ide/code/bin/gp-code
  components/ide/code/bin/open
  components/ide/code/leeway.Dockerfile
Labels: size/M, team: IDE, release-note-none

#8227 [server] disable perMessageDeflate on websockets
  components/server/src/express/ws-handler.ts
Labels: size/XS, team: webapp, release-note

#8249 [jb] clarify to install release not EAP gateway
  components/ide/jetbrains/gateway-plugin/doc/installing.md
Labels: size/XS, team: IDE, release-note-none

#8233 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8250 [dashboard] Ensure we fetch IDEOptions onload + onNewInstance
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/S, team: webapp, release-note-none

#8239 jb: enable debug flow for backend plugin
  components/ide/jetbrains/backend-plugin/README.md
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthService.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/image/status/main.go
Labels: size/L, team: IDE, release-note-none

#8086 Basic Bitbucket Server support (login and workspace start)
  components/server/ee/src/auth/host-container-mapping.ts
  components/server/package.json
  components/server/src/auth/host-container-mapping.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-container-module.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-language-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-token-handler.ts
  yarn.lock
Labels: size/XXL, team: webapp, release-note

#8270 [installer] Add MINIO_SKIP_CLIENT=yes to minio
  components/installer/third_party/charts/minio/values.yaml
Labels: size/XS, release-note, team: self-hosted

#8067 telemetry: add more fields to data
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/installation-admin-protocol.ts
  components/installation-telemetry/cmd/send.go
  components/installation-telemetry/pkg/server/installationAdmin.go
  components/server/src/installation-admin/installation-admin-controller.ts
Labels: size/M, team: webapp, release-note, team: self-hosted

#8273 [bridge] Fix PreparingUpdateEmulator initialization
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/preparing-update-emulator.ts
Labels: size/S, team: webapp, release-note-none

#8277 Reduce CPU requests from 1 core to 100m
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, team: workspace, release-note-none, team: platform

#8278 Use latest workspace-vm-image for preview envs
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8275 nsinsider: Match the usage of nsinsider to the current codebase.
  components/ws-daemon/nsinsider/main.go
Labels: team: workspace, release-note

#8283 [supervisor] Fix dotfile installation
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#8293 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8297 Prune everything (remove filter)
  .werft/clean-up-werft-build-nodes.yaml
Labels: size/XS, release-note-none, team: platform

#8210 [Analytics] Include anonymous ID in login and signup track calls
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/App.tsx
  components/dashboard/src/settings/Notifications.tsx
  components/gitpod-protocol/src/analytics.ts
  components/server/src/analytics.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#8288 [installer] Remove default workspace template
  components/installer/pkg/components/ws-manager/configmap.go
  components/installer/pkg/components/ws-manager/configmap_test.go
Labels: size/M, team: workspace, release-note

#8289 [ws-manager] Wait for workspace pod to be ready
  components/ws-manager/pkg/manager/manager.go
Labels: size/L, team: workspace, release-note

#8302 [installer] Add missing nil check for experimental ws-daemon config
  components/installer/pkg/components/ws-daemon/configmap.go
Labels: size/S, team: workspace, release-note-none

#8332 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8306 [server] Restrict snapshot access based on repository access
  components/dashboard/src/start/CreateWorkspace.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/auth/host-container-mapping.ts
  components/server/ee/src/github/container-module.ts
  components/server/ee/src/prebuilds/github-service.ts
  components/server/ee/src/prebuilds/gitlab-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/repohost/repository-provider.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
Labels: size/L, team: webapp, release-note

#8272 telemetry: show collected data under the toggle
  components/dashboard/src/admin/Settings.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/installation-admin-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/container-module.ts
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/installation-admin/telemetry-data-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note

#8339 [jb] track client project sessions
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServer.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/RemoteTrackMessage.java
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/HeartbeatService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/SupervisorInfoService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/XL, team: IDE, release-note-none

#8346 [installer] Use fuse as default ShiftFS method
  components/installer/pkg/config/v1/config.go
Labels: size/XS, release-note, team: self-hosted

#8348 [server] make ping pong async
  components/server/src/express/ws-connection-handler.ts
Labels: size/S, team: webapp, release-note-none

#8357 Update VM image ID
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8362 Fix VM image ID
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8358 werft/jobs/build: Add observability support to installer
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/observability/monitoring-satellite.ts
Labels: size/M, release-note-none, team: platform

#8374 [server] Track snapshot access requests, and whether they are granted or denied
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#8317 [jb] fix #8296: validate host key fingerprint
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/XL, team: IDE, release-note-none

#8371 [jb]: customize remote indicator
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodBranding.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/icons/GitpodIcons.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/HeartbeatService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/SupervisorInfoService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/icons/logo.svg
Labels: size/L, team: IDE, release-note-none

#8307 Add maximum lifetime constraint for a workspace
  chart/templates/ws-manager-configmap.yaml
  components/installer/pkg/components/ws-manager/configmap.go
  components/ws-manager-api/go/config/config.go
  components/ws-manager/config-schema.json
  components/ws-manager/example-config.json
  components/ws-manager/pkg/manager/integration_test.go
  components/ws-manager/pkg/manager/monitor.go
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/status_test.go
  components/ws-manager/pkg/manager/testdata/timeout_regular_maxLifetime.golden
  components/ws-manager/pkg/manager/testdata/timeout_regular_maxLifetime.json
  components/ws-manager/pkg/manager/testing_test.go
Labels: size/XL, team: workspace, release-note

#8266 installer: make OpenVSX URL configurable in the openvsx proxy
  install/installer/pkg/components/openvsx-proxy/configmap.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/load.go
Labels: size/S, team: IDE, release-note, team: self-hosted

#8389 [installer] Ensure ws-proxy is scheduled in different nodes
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/S, team: workspace, release-note

#8390 Log parent quota
  components/ws-daemon/pkg/cpulimit/cfs.go
Labels: size/S, team: workspace, release-note-none

#8393 Update helm cpu limit
  chart/templates/ws-manager-configmap.yaml
  chart/values.yaml
Labels: size/XS, team: workspace, release-note-none

#8386 [admin] (temp) disable telemetry for gitpod.io
  components/dashboard/src/admin/Settings.tsx
Labels: size/XS, team: webapp, release-note-none

#8366 [ws-daemon] Improve cache error handling
  components/ws-daemon/pkg/daemon/cache_reclaim.go
  components/ws-daemon/pkg/daemon/cache_reclaim_test.go
Labels: size/S, team: workspace, release-note-none

#8406 jb: configure SDK workaround
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodProjectManager.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/M, team: IDE, release-note-none

#8372 [ws-manager] Add missing check to fix OOM error
  components/ws-manager/pkg/manager/manager.go
Labels: size/M, team: workspace, release-note-none

#8407 Use old small Workspace Image for VMs for now
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8415 jb: auto preconfigure module SDK as well
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodProjectManager.kt
Labels: size/M, team: IDE, release-note-none

#8424 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#8422 Identify Call Improvements
  components/server/src/analytics.ts
Labels: size/XS, team: webapp, release-note-none

#8430 [jb] update link to GW docs
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/XS, team: IDE, release-note-none

#8431 Revert "Revert "[server, db] AuthProviderEntry: Introduce oauthRevision to av…"
  components/dashboard/src/service/service-mock.ts
  components/gitpod-db/BUILD.yaml
  components/gitpod-db/src/auth-provider-entry-db.ts
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-auth-provider-entry.ts
  components/gitpod-db/src/typeorm/migration/1643986994402-OAuthRevision.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/host-context-provider-impl.ts
Labels: team: webapp, release-note-none

#8432 jb: fix update gateway instructions
  chart/templates/server-ide-configmap.yaml
  components/ide/jetbrains/gateway-plugin/doc/installing.md
  install/installer/pkg/components/server/ide/configmap.go
Labels: size/S, team: IDE, release-note-none

#8376 [installer]: remove jaeger operator
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/jaeger-operator/helm.go
  install/installer/third_party/charts/jaeger-operator/Chart.yaml
  install/installer/third_party/charts/jaeger-operator/crd.yaml
  install/installer/third_party/charts/jaeger-operator/values.yaml
  install/installer/third_party/charts/jaegerOperator.go
Labels: size/L, team: webapp, release-note, team: self-hosted

#8373 dashboard: set correct default setting for telemetry
  components/dashboard/src/admin/Settings.tsx
Labels: size/XS, team: webapp, release-note, team: self-hosted

#8436 [installer] Tidy up `omitempty` in config
  install/installer/example-config.yaml
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, release-note-none, team: self-hosted

#8444 Update stable with vscode_session telemetry fix
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#8440 add dekstop-ide-ready phase to status_rendered analytics event
  components/ide/code-desktop/status/main.go
  components/ide/jetbrains/image/status/main.go
  components/ide/jetbrains/image/supervisor-ide-config_goland.json
  components/ide/jetbrains/image/supervisor-ide-config_intellij.json
  components/ide/jetbrains/image/supervisor-ide-config_phpstorm.json
  components/ide/jetbrains/image/supervisor-ide-config_pycharm.json
  components/supervisor-api/go/status.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Status.java
  components/supervisor-api/status.proto
  components/supervisor/frontend/src/index.ts
  components/supervisor/pkg/supervisor/services.go
Labels: size/XXL, team: IDE, release-note-none

#8316 forcing the werft job to fail if the branch name is too long to suppo…
  .werft/build.ts
Labels: size/S, release-note-none

#8460 [installer]: remove jaeger operator from the config
  install/installer/README.md
  install/installer/example-config.yaml
  install/installer/pkg/config/v1/config.go
Labels: size/XS, release-note, team: self-hosted

#8461 Log workspace starts and stop
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none
