Repository gitpod-io/gitpod, pull requests merged in 2022-04, with the labels that each got.

#9055 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9024 Add new VS Code domain to config maps
  chart/templates/blobserve-configmap.yaml
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/S, team: workspace, release-note-none

#9045 [dashboard] Remove prebuild status errors from prebuild logs
  components/dashboard/src/components/PrebuildLogs.tsx
Labels: size/M, team: webapp, release-note

#9060 [kots]: add distribution check to the KOTS preflights
  install/kots/manifests/kots-preflight.yaml
Labels: size/XS, release-note, team: self-hosted

#9061 Switch KOTS publish to use envvars
  .werft/jobs/build/publish-kots.ts
Labels: size/XS, release-note-none

#9066 fix #9065: Blobserve does not launch in preview envs due to syntax er…
  chart/templates/blobserve-configmap.yaml
Labels: size/XS, release-note-none

#9063 [registry-facade] Support blob caching in Redis
  components/blobserve/pkg/blobserve/refstore.go
  components/registry-facade/.vscode/launch.json
  components/registry-facade/example-spec.json
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/registry-facade/pkg/registry/blob.go
  components/registry-facade/pkg/registry/cache.go
  components/registry-facade/pkg/registry/cache_test.go
  components/registry-facade/pkg/registry/imagecfg.go
  components/registry-facade/pkg/registry/ipfs.go
  components/registry-facade/pkg/registry/layersource.go
  components/registry-facade/pkg/registry/layersource_test.go
  components/registry-facade/pkg/registry/manifest.go
  components/registry-facade/pkg/registry/registry.go
  components/registry-facade/pkg/registry/resolver.go
Labels: size/XXL, team: workspace, release-note, deployed: workspace, deployed

#9047 Properly declare analytics variable
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none, team: platform

#9086 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9087 Fix dead link for the source of docs
  docs/README.md
Labels: size/XS, release-note-none

#9092 Change reviewers for some workspace components
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#8896 [bitbucket-server] support for projects and prebuilds
  components/dashboard/src/projects/NewProject.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/auth/host-container-mapping.ts
  components/server/ee/src/bitbucket-server/container-module.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/prebuilds/bitbucket-server-app.ts
  components/server/ee/src/prebuilds/bitbucket-server-service.spec.ts
  components/server/ee/src/prebuilds/bitbucket-server-service.ts
  components/server/ee/src/prebuilds/bitbucket-service.ts
  components/server/ee/src/server.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/package.json
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/projects/projects-service.ts
  components/server/src/repohost/repo-url.ts
  yarn.lock
Labels: size/XXL, team: webapp, release-note

#9109 Fix prebuild base selection
  components/server/ee/src/workspace/workspace-factory.ts
Labels: size/M, team: webapp, release-note

#8824 [server] For GitLab projects without an owner avatar, fall back to the namespace avatar, or generate the default GitLab avatar
  components/dashboard/src/projects/NewProject.tsx
  components/server/ee/src/gitlab/gitlab-app-support.ts
Labels: size/M, team: webapp, release-note

#9099 [bitbucket-server] reuse icon from bitbucket
  components/dashboard/src/provider-utils.tsx
Labels: size/XS, team: webapp, release-note-none, team: product-design

#9105 [dashboard] Update variable refresh option
  operations/observability/mixins/workspace/dashboards/components/agent-smith.json
  operations/observability/mixins/workspace/dashboards/components/blobserve.json
  operations/observability/mixins/workspace/dashboards/components/content-service.json
  operations/observability/mixins/workspace/dashboards/components/registry-facade.json
  operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
  operations/observability/mixins/workspace/dashboards/components/ws-manager.json
  operations/observability/mixins/workspace/dashboards/components/ws-proxy.json
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/M, team: workspace, release-note-none

#9119 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9120 [ws-manager-bridge] Add spans for prebuild state and error
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#9083 [kots]: add a kernel version check to the preflights
  install/kots/manifests/kots-preflight.yaml
Labels: size/S, release-note, team: self-hosted

#9110 [dev] Add yq v4.23.1 as `yq4` binary in dev image
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-clean-up-werft-build-nodes.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  components/supervisor/pkg/config/gitpod-config_test.go
  dev/image/Dockerfile
Labels: size/S, team: IDE, release-note-none, team: platform

#9123 Add ws-manager-bridge to pre-commit prettier checks
  .pre-commit-config.yaml
Labels: size/XS, team: webapp, release-note-none

#9124 werft/observability: Address FIXME
  .werft/observability/monitoring-satellite.ts
Labels: size/S, release-note-none, team: platform

#9125 Added requirements to KOTS installation
  install/README.md
Labels: size/S, release-note, team: self-hosted

#9121 [gitpod-db] Don't consider garbage-collected prebuilds as potential bases for incremental prebuilds
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/server/ee/src/workspace/workspace-factory.ts
Labels: size/XS, team: webapp, release-note

#9129 [ws-manager-bridge] Fix counting of stale prebuild events
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#8831 [dashboard] Remove Prebuild logs and button from Project Settings
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/Prebuilds.tsx
Labels: size/XL, team: webapp, release-note

#9134 Install pre-commit hooks during prebuild
  .gitpod.yml
Labels: size/XS, release-note-none

#9118 add PVC feature flag
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/config-provider.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/go/core_grpc.pb.go
  components/ws-manager-api/go/mock/mock.go
  components/ws-manager-api/typescript/src/core_grpc_pb.d.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.js
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
Labels: size/L, team: webapp, release-note-none

#9116 [ws-manager-bridge] Skip stale prebuild events
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/M, team: webapp, release-note

#9144 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8956 [local-app] Cleanup run command, apply recommended go style
  components/local-app/main.go
  components/local-app/pkg/auth/auth.go
Labels: size/L, team: IDE, release-note-none

#8576 [installer] Allow to set default workspace timeout
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/user/eligibility-service.ts
  components/server/ee/src/user/user-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/config.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/workspace-starter.ts
  install/installer/example-config.yaml
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/types.go
  install/installer/pkg/components/ws-manager/configmap.go
  install/installer/pkg/config/v1/config.go
Labels: meta: never-stale, size/L, team: webapp, team: workspace, team: IDE, release-note, team: self-hosted

#9113 Properly update response in openvsx proxy
  components/openvsx-proxy/pkg/modifyresponse.go
  components/openvsx-proxy/pkg/openvsxproxy_test.go
Labels: size/M, team: IDE, release-note-none

#9151 [ws-manager-bridge] Log handling of prebuild update events
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#9153 Revert '[ws-manager-bridge] Skip stale prebuild events'
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#9154 [supervisor] remove supervisor_readiness for headless workspaces
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#9158 Point Insiders back to `gp-code/main`
  .github/workflows/code-nightly.yaml
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9004 Redirect web page when instance changed
  components/dashboard/src/start/StartWorkspace.tsx
  components/supervisor/frontend/src/index.ts
Labels: size/M, team: webapp, team: IDE, release-note

#9166 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9051 [dashboard] Implement a PaymentContext and use it to hide payment features when payment is disabled
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/index.tsx
  components/dashboard/src/payment-context.tsx
  components/dashboard/src/settings/Account.tsx
  components/dashboard/src/settings/EnvironmentVariables.tsx
  components/dashboard/src/settings/Integrations.tsx
  components/dashboard/src/settings/Notifications.tsx
  components/dashboard/src/settings/Plans.tsx
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/settings/Teams.tsx
  components/dashboard/src/settings/settings-menu.ts
Labels: size/XL, team: webapp, release-note

#9184 [code] Build stable image for 1.66.1
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9185 [code] Update stable to 1.66.1
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#9186 [image-builder-bob] Update buildkit to v0.10.1
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XXL, team: workspace, release-note, team: self-hosted

#9187 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8841 [dashboard]: Use prebuild record when determining prebuild actions
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/projects/Prebuild.tsx
Labels: size/M, team: webapp, release-note

#8925 [webapp] move admin redirects to `App.tsx`
  components/dashboard/src/App.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
Labels: size/M, team: webapp, release-note-none

#8970 [dashboard] replace dev configuration with env vars
  components/dashboard/README.md
  components/dashboard/craco.config.js
Labels: size/L, team: webapp, release-note

#9193 enable indexing with GoLand in prebuilds
  .gitpod.yml
  scripts/goland-indexing.sh
Labels: size/S, release-note-none

#9108 Bitbucket Server: add token validator
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-container-module.ts
  components/server/src/bitbucket-server/bitbucket-server-token-validator.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-token-validator.ts
  components/server/src/bitbucket/bitbucket-token-validator.ts
  components/server/src/github/github-token-validator.ts
  components/server/src/gitlab/gitlab-token-validator.ts
  components/server/src/repohost/repo-url.spec.ts
  components/server/src/repohost/repo-url.ts
  components/server/src/workspace/git-token-scope-guesser.ts
  components/server/src/workspace/git-token-validator.ts
Labels: size/XL, team: webapp, release-note

#9211 werft: fix typo.
  .werft/jobs/build/job-config.ts
Labels: size/XS, release-note-none

#9191 [ws-manager-bridge] Skip stale prebuild events
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note

#9199 [analytics] Fix default notification settings in analytics call
  components/server/src/analytics.ts
Labels: size/XS, team: webapp, release-note-none

#9202 Move publish Kots method under buildAndPublish
  .werft/build.ts
  .werft/jobs/build/build-and-publish.ts
  .werft/jobs/build/publish-kots.ts
Labels: size/M, release-note-none, team: platform

#9228 Setup component (and dir) for public API server
  .github/CODEOWNERS
  components/public-api-server/RAEDME.md
Labels: size/XS, team: webapp, release-note-none

#9082 [installer] Add custom CA secret support
  install/installer/pkg/common/ca.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/validation.go
Labels: size/L, team: webapp, team: workspace, release-note, team: self-hosted

#9233 [ws-manager-bridge] Fix statusVersion comparison
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/S, team: webapp, release-note

#9071 [kots]: change the CPU and memory checks to be min not sum
  install/kots/manifests/kots-preflight.yaml
Labels: size/S, release-note, team: self-hosted

#6272 [server] add vscode(-insiders) ouath2 clients
  components/gitpod-db/package.json
  components/gitpod-db/src/typeorm/auth-code-repository-db.ts
  components/gitpod-db/src/typeorm/entity/db-oauth-auth-code.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/proxy/conf/Caddyfile
  components/proxy/plugins/corsorigin/cors_origin.go
  components/server/package.json
  components/server/src/oauth-server/db.ts
  components/server/src/oauth-server/oauth-controller.ts
  yarn.lock
Labels: approved, size/L, team: webapp, team: IDE, release-note-none

#9222 Update Readme Header's elements alignment
  README.md
Labels: size/S, release-note-none

#9197 [jb-gw]: disable new workspace button when url is blank
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
Labels: community-contribution, size/S, team: IDE, release-note, cla: accepted :heavy_check_mark:

#9227 Add `maximumBackupCount` and `blobQuota` configuration surface to the installer
  install/installer/pkg/common/storage.go
  install/installer/pkg/config/v1/config.go
Labels: size/S, team: workspace, release-note, team: self-hosted

#9215 [installer] open-vsx: configure redis
  install/installer/pkg/components/openvsx-proxy/configmap.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: size/M, team: IDE, release-note

#9251 [public-api-server] Serve a hello world over http
  components/public-api-server/main.go
Labels: size/XS, team: webapp, release-note-none

#9254 [installer] Allow composed render funcs to output no object
  install/installer/pkg/common/render.go
  install/installer/pkg/common/render_test.go
Labels: size/M, release-note-none, team: self-hosted

#9135 [bitbucket-server] add to Git Integrations UI
  components/dashboard/src/settings/Integrations.tsx
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/authenticator.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
  components/server/src/bitbucket-server/bitbucket-server-urls.ts
Labels: size/M, team: webapp, release-note

#9266 [ws-daemon] Enable workspace IP forwarding
  components/ws-daemon/nsinsider/main.go
  components/ws-daemon/pkg/iws/iws.go
Labels: size/S, team: workspace, release-note-none

#9270 [ws-daemon] Enable workspace IP forwarding
  components/ws-daemon/pkg/iws/iws.go
Labels: size/S, team: workspace, release-note-none

#9271 [ws-daemon] Introduce IO limiting
  components/ws-daemon/pkg/cgroup/cgroup.go
  components/ws-daemon/pkg/cgroup/plugin_cachereclaim.go
  components/ws-daemon/pkg/cgroup/plugin_cachereclaim_test.go
  components/ws-daemon/pkg/cgroup/plugin_fuse.go
  components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
  components/ws-daemon/pkg/daemon/cgroup_customizer.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XXL, team: workspace, release-note, team: self-hosted

#9237 [devenv] Bump werft CLI
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-clean-up-werft-build-nodes.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
Labels: size/S, team: IDE, release-note-none, team: platform

#9272 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#9094 [installer] Disable `definitely-gp` by default
  chart/values.yaml
  install/installer/docs/air-gap.md
  install/installer/example-config.yaml
  install/installer/pkg/config/v1/config.go
Labels: size/XS, team: webapp, release-note, team: self-hosted

#9252 [public-api-server] Setup component in installer with experimental conf
  .github/CODEOWNERS
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/versions/versions.go
Labels: size/M, team: webapp, team: IDE, release-note-none, team: self-hosted

#9290 [public-api-server] Simple gRPC server
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/main.go
Labels: size/L, team: webapp, release-note-none

#9294 [nsinsider] Make veth0 match container MTU
  components/ws-daemon/nsinsider/main.go
Labels: size/XS, team: workspace, release-note

#9268 Use dynamic links for downloading the latest version of JetBrains Tools
  components/ide/jetbrains/image/BUILD.yaml
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#9295 [ws-daemon] Apply IO limits continuosly
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
Labels: size/M, team: workspace, release-note-none

#9258 [public-api-server] Add k8s deployment into installer
  install/installer/pkg/components/public-api-server/constants.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/components/public-api-server/rolebinding.go
Labels: size/L, team: webapp, release-note-none

#9297 Add experimental config values for the Server component
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, release-note

#9260 [public-api-server] Enable in preview environments
  .werft/jobs/build/installer/installer.ts
Labels: size/XS, team: webapp, release-note-none

#9304 [installer]: use fully qualified image name for redis image
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: size/XS, team: IDE, release-note-none

#9312 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9305 Make server githubApp.certSecretName configurable
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/types.go
Labels: size/XS, team: webapp

#9327 [ws-daemon] Improve cgroup plugin activation count
  components/ws-daemon/pkg/cgroup/cgroup.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
Labels: size/M, team: workspace, release-note-none

#9330 [installer] Add missing ports to server, ws-manager-bridge
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/S, team: webapp, release-note-none

#9334 Add additional logging for io limiting
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
Labels: size/XS, release-note-none

#9320 Add WebApp to /components/common-go codeowners
  .github/CODEOWNERS
Labels: size/XS, team: webapp, team: workspace, release-note-none

#9338 [registry-facade] Do not log warning from local store already exist error
  components/registry-facade/pkg/registry/manifest.go
Labels: size/XS, team: workspace, release-note

#9344 Revert "[registry-facade] remove supervisor from static layer"
  install/installer/pkg/components/registry-facade/configmap.go
Labels: size/XS, team: workspace, release-note-none

#9331 [supervisor] prevent slow clients to stale tasks in headless workspaces
  components/supervisor/pkg/supervisor/tasks.go
  components/supervisor/pkg/terminal/terminal.go
Labels: size/M, team: IDE, release-note-none

#9360 [docker-up] Add docker-compose binary
  components/docker-up/BUILD.yaml
  components/docker-up/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note

#9367 Update OpenSSH to v9.0
  components/supervisor/openssh/leeway.Dockerfile
Labels: size/XS, team: IDE, release-note

#9220 [observability] Add alert rule for high ws failure
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#9379 [installer] fix redis pvc name incorrect
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: size/XS, team: IDE, release-note-none

#9378 [code] Build stable image for 1.66.2
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9381 [code] Update stable to 1.66.2
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#9382 Revert "[ws-daemon] Fix CPU limit annotation"
  components/ws-daemon/pkg/cpulimit/cpulimit.go
  components/ws-daemon/pkg/cpulimit/dispatch.go
Labels: size/M, team: workspace, release-note

#9355 [ws-manager] add metrics to track initialize and finalize of workspaces
  components/ws-manager/pkg/manager/metrics.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/M, team: workspace, release-note

#9358 [ws-proxy] fix ACME challenge handler
  components/ws-proxy/pkg/proxy/workspacerouter.go
Labels: size/XS, team: workspace, release-note

#9388 Fix the shell error
  scripts/setup-google-adc.sh
Labels: size/XS, team: workspace, release-note-none

#9336 Add some missing `component:` labels to various helm chart templates
  chart/templates/agent-smith-daemonset.yaml
  chart/templates/auth-providers-configmap.yaml
  chart/templates/blobserve-networkpolicy.yaml
  chart/templates/content-service-configmap.yaml
  chart/templates/db-sync-configmap.yaml
  chart/templates/image-builder-mk3-authkey-secret.yaml
  chart/templates/openvsx-proxy-configmap.yaml
  chart/templates/proxy-configmap.yaml
  chart/templates/registry-facade-configmap.yaml
  chart/templates/server-configmap.yaml
  chart/templates/server-ide-configmap.yaml
  chart/templates/workspace-template.yaml
  chart/templates/ws-manager-bridge-configmap.yaml
  chart/templates/ws-manager-configmap.yaml
  chart/templates/ws-proxy-configmap.yaml
Labels: size/M, release-note-none

#9300 [public-api-server] Group http and grpc servers into a baseserver package
  .github/CODEOWNERS
  components/common-go/baseserver/options.go
  components/common-go/baseserver/options_test.go
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
  components/common-go/baseserver/testing.go
  components/common-go/go.mod
  components/common-go/log/log.go
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/main.go
  components/public-api/go/go.mod
Labels: size/XXL, team: webapp, team: workspace, release-note-none

#9368 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9293 [dashboard] add notice for stable back and change latest desc
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/S, team: webapp, release-note-none, team: product-design

#9313 [baseserver] Add prometheus metrics
  components/common-go/baseserver/options.go
  components/common-go/baseserver/options_test.go
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
  components/public-api-server/go.mod
  components/public-api-server/go.sum
Labels: size/XL, team: webapp, release-note-none

#9372 [server] disallow deauthorization if account is blocked
  components/server/src/auth/authenticator.ts
  components/server/src/user/user-controller.ts
Labels: size/S, team: webapp, release-note-none

#9278 Fix default vscode settings sync value
  components/server/src/code-sync/code-sync-service.ts
Labels: size/XS, team: webapp, release-note-none

#9404 Ensure IO limits are written after first workspace is stopped
  components/ws-daemon/pkg/cgroup/cgroup.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/M, release-note

#9402 [protocol] fix generate id for bad repo names
  components/gitpod-protocol/src/util/generate-workspace-id.spec.ts
  components/gitpod-protocol/src/util/generate-workspace-id.ts
Labels: size/S, team: webapp, release-note-none

#9400 [installer] Rename `common.Affinity` to `NodeAffinity`
  install/installer/pkg/common/common.go
  install/installer/pkg/components/agent-smith/daemonset.go
  install/installer/pkg/components/blobserve/deployment.go
  install/installer/pkg/components/content-service/deployment.go
  install/installer/pkg/components/dashboard/deployment.go
  install/installer/pkg/components/database/init/job.go
  install/installer/pkg/components/ide-proxy/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/migrations/job.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
  install/installer/pkg/helm/helm.go
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: self-hosted

#9390 ws-daemon: align to decide if cgroup v2.
  components/ws-daemon/pkg/iws/iws.go
Labels: size/M, team: workspace, release-note

#9415 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#9317 [server] Add priorization to repo URLs
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#9324 [public-api] Ensure no objects are rendered by installer without experimental config
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/components/public-api-server/objects_test.go
Labels: size/L, team: webapp, release-note-none

#9397 [public-api] Add unimplemented workspace service
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
  components/public-api-server/BUILD.yaml
  components/public-api-server/go.mod
  components/public-api-server/integration_test.go
  components/public-api-server/main.go
  components/public-api/go/v1/examples_test.go
Labels: size/L, team: webapp, release-note-none

#9362 [public-api] Extend k8s definitions with a service
  install/installer/pkg/components/public-api-server/constants.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/components/public-api-server/service.go
Labels: size/M, team: webapp, release-note-none

#9361 [werft] Improve findFreeHostPorts speed
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/util/kubectl.ts
Labels: size/M, release-note, team: platform

#9424 [ws-man-bridge] Document when unknown workspace instance occurs
  components/ws-manager-bridge/src/bridge.ts
Labels: size/L, team: webapp, release-note-none

#9429 Revert "Fix the shell error"
  scripts/setup-google-adc.sh
Labels: size/XS, release-note-none

#9427 Allow workspace timeouts to be extended when a user has workspaces in multiple regions
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note

#9363 [public-api] Route api.<domain> to public api service & deployment
  components/proxy/conf/Caddyfile
  components/public-api-server/main.go
Labels: size/XS, team: webapp, release-note-none

#9440 [ws-daemon] Support config reload for IO limits
  components/ws-daemon/cmd/root.go
  components/ws-daemon/cmd/run.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go
  components/ws-daemon/pkg/config/config.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/L, team: workspace, release-note-none

#9441 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9443 [ide] Initialize a shared terminal on JetBrains IDEs when a workspace starts
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: IDE, release-note, editor: jetbrains

#9398 [public-api] Register unimplemented Prebuild service
  components/public-api-server/integration_test.go
  components/public-api-server/main.go
Labels: size/M, team: webapp, release-note-none

#9436 [baseserver] Helper for starting server in tests
  components/common-go/baseserver/server_test.go
  components/common-go/baseserver/testing.go
  components/public-api-server/integration_test.go
Labels: size/M, team: webapp, release-note-none

#9446 [server, dashboard] Refactor User.getPrimaryEmail to return "string | undefined" instead of throwing an error
  components/dashboard/src/Menu.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/settings/Account.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/analytics.ts
Labels: size/M, team: webapp, release-note

#9448 [public-api] Fix semantic merge
  components/public-api-server/integration_test.go
Labels: size/XS, team: webapp, release-note-none

#9449 [installer] reduce openvsx-proxy request memory
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: size/XS, team: IDE, release-note-none

#9447 [wsman-bridge] Lint typescript files
  components/ws-manager-bridge/ee/src/container-module.ts
  components/ws-manager-bridge/ee/src/index.ts
  components/ws-manager-bridge/src/bridge-controller.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/index.ts
  components/ws-manager-bridge/src/main.ts
  components/ws-manager-bridge/src/messagebus-integration.ts
  components/ws-manager-bridge/src/meta-instance-controller.ts
  components/ws-manager-bridge/src/preparing-update-emulator.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
  components/ws-manager-bridge/src/wsman-subscriber.ts
Labels: size/XXL, team: webapp, release-note-none

#9224 [supervisor-api] New API endpoint to set active client
  components/supervisor-api/go/control.pb.go
  components/supervisor-api/go/info.pb.go
  components/supervisor-api/go/notification.pb.go
  components/supervisor-api/go/notification.pb.gw.go
  components/supervisor-api/go/notification_grpc.pb.go
  components/supervisor-api/go/port.pb.go
  components/supervisor-api/go/status.pb.go
  components/supervisor-api/go/terminal.pb.go
  components/supervisor-api/go/token.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Notification.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/NotificationServiceGrpc.java
  components/supervisor-api/notification.proto
Labels: size/XXL, team: IDE, release-note-none

#9445 [jb] allow to specify plugins per a product
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/ide/jetbrains/image/status/go.mod
  components/ide/jetbrains/image/status/go.sum
  components/ide/jetbrains/image/status/main.go
  components/ide/jetbrains/image/status/main_test.go
Labels: size/L, team: webapp, team: IDE, release-note

#9462 [server] Optimization: Map GitHub API repositories during pagination, not after
  components/server/ee/src/prebuilds/github-service.ts
Labels: size/S, team: webapp, release-note

#9438 [ws-manager] fix workspace status flipping pending to deleted
  components/ws-manager/pkg/manager/annotations.go
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
  components/ws-manager/pkg/manager/testdata/cdwp_customcerts.golden
  components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
  components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_probe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
  components/ws-manager/pkg/manager/testdata/cdwp_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
  components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
  components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
Labels: size/M, team: workspace, release-note

#9464 [code] Build stable image for 1.66.2 with proxy fix
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9319 [baseserver] Add /ready and /live endpoints, with config
  components/common-go/baseserver/options.go
  components/common-go/baseserver/options_test.go
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
  components/common-go/go.mod
  components/common-go/go.sum
  components/public-api-server/go.mod
  components/public-api-server/go.sum
Labels: size/M, team: webapp, team: workspace, release-note-none

#9477 [server] enhance log message for image build
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#9480 [Observability] Add node resource consumption dashboards
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-node-resource-metrics.json
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none, team: platform

#9478 [public-api] Use /ready and /live for probes
  install/installer/pkg/components/public-api-server/deployment.go
Labels: size/S, team: webapp, release-note-none

#9455 [kots]: add an installation status pod
  .werft/jobs/build/build-and-publish.ts
  install/installer/leeway.Dockerfile
  install/kots/manifests/gitpod-installation-status.yaml
  install/kots/manifests/gitpod-installer-job.yaml
  install/kots/manifests/kots-app.yaml
Labels: size/M, release-note, team: self-hosted

#9422 [ws-man-bridge] Add started and completed metrics to track health
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/M, team: webapp, release-note-none

#9488 [dashboard] Make sure we have the auth cookie set before redirecting to the workspace URL
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/XS, team: webapp, release-note

#9470 [code] Update stable to 1.66.2 with proxy fix
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#9493 [ws-daemon] Check blkio throttle exists
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go
Labels: size/S, team: workspace, release-note

#9450 [jetbrains] experimental support of warm up in prebuilds
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/container-module.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp, release-note

#9512 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#9281 mess with tracing
  components/gitpod-messagebus/src/messagebus.ts
  components/gitpod-protocol/src/util/tracing.ts
  components/server/src/workspace/messagebus-integration.ts
Labels: size/L, team: webapp, release-note

#9516 [ws-manager-bridge] Fix workspace instance update started total metric incrementing
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/XS, team: webapp, release-note-none

#9517 [ws-man-bridge] Fix Workspace Instance status update dashboard to work across web-app clusters
  operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
Labels: size/XS, team: webapp, release-note-none

#9476 [baseserver] Serve pprof on /debug/pprof
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
Labels: size/S, team: webapp, release-note-none

#9485 [kots]: allow configuration of Open VSX URL
  install/kots/manifests/gitpod-installer-job.yaml
  install/kots/manifests/kots-config.yaml
Labels: size/S, release-note, team: self-hosted
