Repository gitpod-io/gitpod, pull requests merged in 2022-09, with the labels that each got.

#12564 [usage] Report upload/download metrics for usage report
  components/usage/pkg/contentservice/client.go
  components/usage/pkg/contentservice/metrics.go
  components/usage/pkg/server/server.go
Labels: size/M, release-note-none

#12559 Fix for Webhook Event GC
  components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
Labels: size/S, team: webapp, release-note

#12563 [usage] Drop raw sessions from usage report to cut size in half
  components/usage/pkg/apiv1/report-generator.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/contentservice/usage_report.go
  components/usage/pkg/contentservice/usage_report_test.go
Labels: size/S, team: webapp, release-note-none

#12574 [server] Don't raise alerts on unspecific startWorkspace errors
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, release-note-none

#12557 [observability] add cluster selector for browser overview dashboard
  operations/observability/mixins/IDE/dashboards.libsonnet
  operations/observability/mixins/IDE/dashboards/components/browser-overview.json
Labels: size/M, team: IDE, release-note-none

#12379 [installer-tests] Fix GCP database config
  install/infra/modules/gke/main.tf
  install/infra/modules/k3s/main.tf
  install/infra/modules/k3s/output.tf
  install/tests/Makefile
  install/tests/manifests/kots-config-gcp-db.yaml
  install/tests/output.tf
Labels: size/M, release-note-none, team: self-hosted

#12252 [installer-tests] Adding test support for s3 registry backend
  .werft/installer-tests.ts
  install/tests/Makefile
  install/tests/main.tf
  install/tests/manifests/kots-config-aws-s3-backend.yaml
  install/tests/output.tf
Labels: size/M, release-note-none, team: self-hosted

#12380 [installer-tests] Add annotations to Cron job files
  .werft/aks-installer-tests.yaml
  .werft/cleanup-installer-tests.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/installer-tests.ts
  .werft/jobs/build/self-hosted-upgrade-tests.ts
  .werft/k3s-installer-tests.yaml
  .werft/self-hosted-installer-tests.yaml
  install/tests/Makefile
  install/tests/main.tf
  install/tests/manifests/kots-config.yaml
Labels: size/XL, release-note-none, team: self-hosted

#12385 [terraform] Add random variables to terrraform resource names
  install/infra/modules/aks/kubernetes.tf
  install/infra/modules/aks/local.tf
  install/infra/modules/aks/main.tf
  install/infra/modules/aks/monitoring.tf
  install/infra/modules/aks/networks.tf
  install/infra/modules/eks/kubernetes.tf
  install/infra/modules/gke/main.tf
  install/infra/modules/k3s/main.tf
  install/tests/Makefile
Labels: size/M, release-note-none, team: self-hosted

#12575 [UBP] Show "running" for instances with no end time in the usage view
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/XS, team: webapp, release-note-none

#12305 [server] Implement EntitlementServiceUBP.hasPaidSubscription
  components/server/ee/src/billing/entitlement-service-ubp.ts
Labels: size/M, team: webapp, release-note-none

#12573 fix: Round of the `elapsedMinutes` of prebuilds
  components/supervisor/pkg/supervisor/tasks.go
Labels: team: IDE, release-note-none

#12576 [db] fix d_b_workspace_instance_usage.startedAt and add ind_dbsync
  components/gitpod-db/src/typeorm/migration/1662027342962-WorkspaceInstanceUsageUpdate.ts
Labels: size/S, team: webapp, release-note-none

#12586 Align GCP Single Cluster TF Database Output with Installation UI
  install/infra/single-cluster/gcp/Makefile
Labels: size/XS, release-note-none, team: self-hosted

#12603 [code] build code stable release 1.71
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#12604 [code] upgrade stable code to 1.71 release
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: IDE, release-note

#12606 [code] point nightly job back to gp-code/main
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#12607 [code] update code stable to align all proposal apis
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: IDE, release-note-none

#12608 [terraform] Turn off node auto-provisioning in GKE
  install/infra/modules/gke/main.tf
Labels: size/S, release-note-none, team: self-hosted

#12577 [single-cluster/eks] Add `cluster-autoscaler`
  install/infra/modules/eks/output.tf
  install/infra/modules/tools/aws-cluster-autoscaler/main.tf
  install/infra/single-cluster/aws/Makefile
  install/infra/single-cluster/aws/tools.tf
Labels: size/L, release-note, team: self-hosted

#12590 Add alerts for kubernetes nodes
  operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml
  operations/observability/mixins/platform/rules/kubernetes/nodes.yaml
Labels: size/M, release-note-none, team: platform

#12593 Add kube-state-metrics alerts
  operations/observability/mixins/platform/rules/observability-stack/kube-state-metrics.yaml
Labels: size/M, release-note-none, team: platform

#12594 Add Prometheus alerts
  operations/observability/mixins/platform/rules/observability-stack/prometheus.yaml
Labels: size/M, release-note-none, team: platform

#12588 [ops] WebApp: Fix team-specific alerts
  operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
Labels: size/S, team: webapp, release-note-none

#12584 Added Usage table
  components/gitpod-db/src/typeorm/migration/1662040283793-AddUsageTable.ts
  components/usage/pkg/db/dbtest/usage.go
  components/usage/pkg/db/usage.go
  components/usage/pkg/db/usage_test.go
Labels: size/L, team: webapp, release-note-none

#12617 [usage] Setup ledger reconciler tick
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/server/server.go
Labels: size/S, team: webapp, release-note-none

#12605 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12624 [UBP] Add a stale data warning to the Usage view
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/XS, team: webapp, release-note-none

#12232 fix(jetbrains): avoid connection loops
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/M, team: IDE, release-note, editor: jetbrains

#12632 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12642 [usage] constrain workspaceInstanceId to be unique
  components/gitpod-db/src/typeorm/migration/1662359515252-UsageUniqueInstanceId.ts
Labels: team: webapp, release-note-none

#12568 feat(jetbrains): show workspace class in backend control center
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodMetricProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: IDE, release-note, editor: jetbrains

#12618 [usage] Usage ledger API protos
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
Labels: size/XXL, team: webapp, release-note-none

#12644 [usage] Invoke ReconcileUsageWithLedger from controller
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#12539 [code-browser] extensions observabiilty
  WORKSPACE.yaml
  components/ide-metrics-api/idemetrics.proto
  components/ide-metrics-api/typescript-grpcweb/.gitignore
  components/ide-metrics-api/typescript-grpcweb/BUILD.yaml
  components/ide-metrics-api/typescript-grpcweb/build.sh
  components/ide-metrics-api/typescript-grpcweb/package.json
  components/ide-metrics-api/typescript-grpcweb/src/index.ts
  components/ide-metrics-api/typescript-grpcweb/tsconfig.json
  components/ide-metrics-api/typescript-grpcweb/webpack.config.js
  components/supervisor/frontend/src/index.ts
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
  operations/observability/mixins/IDE/dashboards.libsonnet
  operations/observability/mixins/IDE/dashboards/components/code-browser.json
  yarn.lock
Labels: size/XXL, team: IDE, release-note-none

#12645 [usage] Find running and stopped instances in ledger reconciler
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/usage.go
  components/usage/pkg/db/usage.go
Labels: size/M, team: webapp, release-note-none

#12648 [gitpod-protocol] move generation of go types to prebuilds and werft
  .gitpod.yml
  .pre-commit-config.yaml
  components/gitpod-protocol/go/BUILD.yaml
  components/gitpod-protocol/go/scripts/generate-config.sh
  components/gitpod-protocol/hack/generate-config.sh
Labels: size/M, team: webapp, release-note

#12446 Add `/oauth/inspect` endpoint
  components/server/src/oauth-server/oauth-controller.ts
Labels: aspect: security, size/S, team: webapp, release-note-none, aspect: authorization

#12662 [usage] Implement ledger control loop
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/usage.go
  components/usage/pkg/db/usage_test.go
  components/usage/pkg/server/server.go
Labels: size/XL, team: webapp, release-note-none

#12386 [server] 'abort' prebuilds
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: size/M, team: webapp, release-note-none

#12664 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12657 [local-preview] set low memory & cpu requirements
  install/preview/entrypoint.sh
Labels: size/XS, release-note, team: self-hosted

#12665 [installer-tests] fix azure authentication
  install/tests/Makefile
Labels: size/XS, release-note-none, team: self-hosted

#12652 [server] Guard against bogus RPC method names
  components/server/src/auth/rate-limiter.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/XL, team: webapp, release-note-none

#12646 Added API call to fetch usage data
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/db/usage.go
  components/usage/pkg/db/usage_test.go
  gitpod-ws.code-workspace
Labels: size/XXL, team: webapp, release-note-none

#12653 Server-side apply of ceph CRDs + wait until ready
  .werft/vm/vm.ts
Labels: size/XS, release-note-none, team: platform

#12673 [db-sync] sync d_b_usage
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note-none

#12656 [usage] Wiring ListUsage through server
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage/pkg/db/usage.go
Labels: size/L, team: webapp, release-note-none

#12669 Reword "Spending Limit" to "Usage Limit"
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/billing/billing-service.ts
  components/server/ee/src/billing/entitlement-service-ubp.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note

#12671 [usage] Save inserted and updated records in the DB
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/usage.go
  components/usage/pkg/db/usage.go
Labels: size/M, team: webapp, release-note-none

#12681 [usage] Cleanup usage records after test
  components/usage/pkg/apiv1/usage_test.go
Labels: size/XS, team: webapp, release-note-none

#12654 [integration] Test multi-repo support
  test/tests/components/ws-manager/multi_repo_test.go
Labels: size/L, team: workspace, release-note-none

#12691 [usage] Drop big log message
  components/usage/pkg/apiv1/usage.go
Labels: size/XS, team: webapp, release-note-none

#12696 [usage] Filter out not started workspace instances
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/S, team: webapp, release-note-none

#12692 [usage] Serialize metadata into usage records
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/usage.go
Labels: size/L, team: webapp, release-note-none

#12703 Update dev/ssh-load-test and dev/changelog go mod versions
  dev/changelog/go.mod
  dev/ssh-load-test/go.mod
Labels: size/S, release-note-none, team: platform

#12716 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12710 [usage] Add listing of credit balance
  components/usage/pkg/db/usage.go
  components/usage/pkg/db/usage_test.go
Labels: size/M, team: webapp, release-note-none

#12229 [installer-preview] add werft flags for triggering self-hosted preview
  .github/workflows/delete-kots-channel.yml
  .werft/build.ts
  .werft/installer-tests.ts
  .werft/jobs/build/job-config.ts
  .werft/jobs/build/self-hosted-upgrade-tests.ts
  install/tests/Makefile
  install/tests/cleanup.sh
Labels: size/L, release-note-none, team: self-hosted

#12719 Change preview pvc to ReadWriteOnce
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none

#12680 [supervisor] track cpu/memory usage analytics
  components/supervisor/README.md
  components/supervisor/hot-deploy.sh
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: IDE, release-note-none

#12707 [usage] Exclude workspace instances without a startedTime
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/workspace_instance.go
Labels: size/S, team: webapp, release-note-none

#12711 [billing] Add ReconcileInvoices RPC to BillingService protos
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/billing_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_pb.js
  components/usage-api/usage/v1/billing.proto
Labels: size/XXL, team: webapp, release-note-none

#12496 [local-preview] Remove unused dead code
  install/preview/entrypoint.sh
Labels: size/S, release-note, team: self-hosted

#12724 [grpc] log stack on panic
  components/common-go/grpc/grpc.go
Labels: size/S, team: webapp, team: workspace, release-note-none

#12720 [billing] Implement FinalizeInvoice with usage ledger
  components/usage/pkg/apiv1/billing.go
Labels: size/M, team: webapp, release-note-none

#12729 [billing] Trigger ReconcileInvoices in ledger reconciler
  components/usage/pkg/apiv1/billing_noop.go
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#12732 [UBP] Extract common UBP configuration components
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Labels: size/XL, team: webapp, release-note-none

#12712 [billing] Implement ReconcileInvoices
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/M, team: webapp, release-note-none

#12736 [usage] store more data for in usage entry
  components/gitpod-protocol/src/usage.ts
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/user.go
  components/usage/pkg/db/dbtest/workspace_instance.go
  components/usage/pkg/db/usage.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/XL, team: webapp, release-note-none

#12677 [dashboard] Use new usage API for team-usage
  components/dashboard/src/teams/TeamUsage.tsx
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/usage.go
  components/usage/pkg/db/usage_test.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/XL, team: webapp, release-note-none

#12742 [supervisor] add 7,8 bucket for cpu perf analytics
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#12751 [supervisor] bucket per each Gb for memory analytics
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#12731 [usage] Remove no longer used ListBilledUsage API
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
Labels: size/XXL, team: webapp, release-note-none

#12749 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12752 [stripe] Create customers with attributionId
  components/server/ee/src/user/stripe-service.ts
Labels: size/XS, team: webapp, release-note-none

#12688 [usage] Remove old controller & report generator
  components/usage/pkg/apiv1/report-generator.go
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/db/dbtest/workspace_instance.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
  components/usage/pkg/server/server.go
Labels: size/XXL, team: webapp, release-note-none

#12754 [server] Don't count "Professional Open Source" as personal subscription
  components/server/ee/src/billing/billing-mode.ts
Labels: size/XS, team: webapp, release-note-none

#12762 [stripe] Use AttributionID metadata when querying for customers
  components/server/ee/src/user/stripe-service.ts
Labels: size/S, team: webapp, release-note-none

#12764 [usage] make tests robust
  components/usage/pkg/db/usage_test.go
Labels: size/M, team: webapp, release-note-none

#12763 [usage-api] remove superceded API
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
Labels: size/XXL, team: webapp, release-note-none

#12766 [usage] Ignore running instances before August 2022
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/S, team: webapp, release-note-none

#12651 Replace webapp alerts from jsonnet to YAML
  .werft/observability/monitoring-satellite.ts
  operations/observability/mixins/meta/mixin.libsonnet
  operations/observability/mixins/meta/rules.libsonnet
  operations/observability/mixins/meta/rules/SLO/SLOs.libsonnet
  operations/observability/mixins/meta/rules/SLO/login/alerts.libsonnet
  operations/observability/mixins/meta/rules/SLO/login/rules.libsonnet
  operations/observability/mixins/meta/rules/components/components.libsonnet
  operations/observability/mixins/meta/rules/components/messagebus/alerts.libsonnet
  operations/observability/mixins/meta/rules/components/nodes/alerts.libsonnet
  operations/observability/mixins/meta/rules/components/nodes/rules.libsonnet
  operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
  operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
  operations/observability/mixins/meta/rules/login-slo.yaml
  operations/observability/mixins/meta/rules/messagebus.yaml
  operations/observability/mixins/meta/rules/meta-nodes.yaml
  operations/observability/mixins/meta/rules/server.yaml
  operations/observability/mixins/meta/rules/usage.yaml
Labels: size/XXL, team: webapp, release-note-none, team: platform

#12659 Replace workspace alerts from Jsonnet to YAML
  .werft/observability/monitoring-satellite.ts
  operations/observability/mixins/workspace/mixin.libsonnet
  operations/observability/mixins/workspace/rules.libsonnet
  operations/observability/mixins/workspace/rules/SLO/SLOs.libsonnet
  operations/observability/mixins/workspace/rules/SLO/workspacefailure/rules.libsonnet
  operations/observability/mixins/workspace/rules/components/components.libsonnet
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
  operations/observability/mixins/workspace/rules/components/nodes/rules.libsonnet
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
  operations/observability/mixins/workspace/rules/components/workspaces/rules.libsonnet
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
  operations/observability/mixins/workspace/rules/components/ws-manager/alerts.libsonnet
  operations/observability/mixins/workspace/rules/nodes.yaml
  operations/observability/mixins/workspace/rules/workspacefailure-SLO.yaml
  operations/observability/mixins/workspace/rules/workspaces.yaml
  operations/observability/mixins/workspace/rules/ws-daemon.yaml
  operations/observability/mixins/workspace/rules/ws-manager.yaml
Labels: size/XXL, team: workspace, release-note-none, team: platform

#12773 [usage] Fix negative credits
  components/usage/pkg/apiv1/pricer.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/M, team: webapp, release-note-none

#12769 [biling] Remove UpdateInvoices - old reconciler
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/server/server.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/L, team: webapp, release-note-none

#12445 code-sync: store editSessions
  WORKSPACE.yaml
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-resource.ts
  components/server/src/code-sync/code-sync-service.ts
Labels: size/L, release-note

#12630 docs(jb-gateway-plugin): update README.md
  components/ide/jetbrains/gateway-plugin/README.md
  components/ide/jetbrains/gateway-plugin/screenshot.png
Labels: size/M, team: IDE, release-note-none, editor: jetbrains, docs-enhancement

#12621 Add Gitpod-related actions to JetBrains IDEs
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServer.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/Error.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/SetWorkspaceTimeoutResult.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/TakeSnapshotOptions.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceTimeoutDuration.java
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/AccessControlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/CommunityChatAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ContextAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/DashboardAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/DocumentationAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ExtendWorkspaceTimeoutAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/FollowUsOnTwitterAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ReportIssueAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/SettingsAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ShareWorkspaceSnapshotAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/StopWorkspaceAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/UpgradeSubscriptionAction.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
Labels: size/XXL, team: IDE, release-note, editor: jetbrains

#12780 Fix PrometheusRule name
  operations/observability/mixins/workspace/rules/workspacefailure-SLO.yaml
Labels: size/XS, team: workspace, release-note-none

#12734 [server] Ensure PVC workspace class does not change on restart
  components/server/src/workspace/workspace-classes.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, team: workspace, release-note-none

#12755 [stripe] Use attributionId in stripe queries in usage
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
  components/usage/pkg/stripe/stripe_test.go
Labels: size/L, team: webapp, release-note-none

#12775 [usage] Remove unused RPCs from proto
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/billing_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/billing.proto
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/billing_noop.go
Labels: size/XXL, team: webapp, release-note-none

#12785 [usage] Remove default controller schedule of 1h
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/XS, team: webapp, release-note-none

#12788 Add dashboard URL for KubeCPUOvercommit and KubeMemoryOvercommit
  operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml
Labels: size/XS, release-note-none, team: platform

#12781 Send traces from previews to Honeycomb
  .werft/jobs/build/helm/values.tracing.yaml
  .werft/observability/monitoring-satellite.ts
Labels: size/XS, release-note-none, team: platform

#12796 [ws-manager-bridge] Don't report workspace instance update failures as both a failure and a success
  components/ws-manager-bridge/src/bridge.ts
Labels: size/S, team: webapp, release-note-none

#12787 [stripe] Finalized invoce debits, do not set credits to negative when updating
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/S, team: webapp, release-note-none

#12797 Remove bradlc.vscode-tailwindcss from list of extensions
  .gitpod.yml
Labels: size/XS, team: webapp, release-note-none

#12798 [ws-manager-bridge] Use more reasonable duration buckets for workspace instance updates
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/XS, team: webapp, release-note-none

#12806 [usage] Include drafts when listing usage summary
  components/usage/pkg/apiv1/usage.go
Labels: size/XS, team: webapp, release-note-none

#12776 [cost center] put all costcenter access behind API
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/cost-center-db.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/typeorm/cost-center-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-cost-center.ts
  components/gitpod-db/src/typeorm/migration/1662639748206-CostCenterPaymentStrategy.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/billing/billing-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/user/user-service.ts
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/cost_center.go
Labels: size/XXL, team: webapp, release-note-none

#12801 test: Workspace testing does not guarantee branch name creation
  test/tests/workspace/contexts_test.go
Labels: size/S, team: workspace, release-note-none

#12799 test: More robust port-forward of ComponentAPI
  test/pkg/integration/apis.go
Labels: size/M, team: workspace, release-note-none

#12810 [usage] added a test for ListUsage
  components/usage/pkg/apiv1/usage_test.go
Labels: size/M, team: webapp, release-note-none

#12701 Install monitoring-satellite with obs-installer
  .werft/observability/install-satellite.sh
  .werft/observability/manifests/monitoring-satellite.yaml
  .werft/observability/monitoring-satellite.ts
Labels: size/L, release-note-none, team: platform

#12811 Import network limiting dashboard
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/network-limiting.json
Labels: size/XS, team: workspace, release-note-none

#12809 [dashboard] (pagination) make sure next page is selectable
  components/dashboard/src/Pagination/getPagination.spec.ts
  components/dashboard/src/Pagination/getPagination.ts
Labels: size/M, team: webapp, release-note-none

#12837 [server][telepresence] continue with downloadVolume on errors and log
  dev/telepresence-hack/copy-mounts/main.go
Labels: size/XS, release-note-none

#12839 [dashboard] reenable attribution to personal account
  components/dashboard/src/components/BillingAccountSelector.tsx
Labels: team: webapp, release-note-none

#12842 Minor improvements to Werft slices
  .werft/build.yaml
  .werft/jobs/build/job-config.ts
Labels: size/M, release-note-none, team: platform

#12808 workspace integration test: add missing PVC feature flag
  test/tests/components/ws-manager/tasks_test.go
Labels: size/XS, team: workspace, release-note-none

#12793 Improve the script of integration test
  .werft/workspace-run-integration-tests.sh
Labels: size/L, team: workspace, team: IDE, release-note-none

#12854 [dashboards] Add gRPC / Server dashboard
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none, team: platform

#12852 Add link to support on phone verification
  components/dashboard/src/start/VerifyModal.tsx
Labels: size/XS, team: webapp, release-note

#12843 [UBP] Fix usage gRPC `sugar.ts` file
  components/usage-api/typescript/src/usage/v1/sugar.ts
Labels: team: webapp, release-note-none

#12833 Improve fetching repositories loading state
  components/dashboard/src/projects/NewProject.tsx
Labels: size/XS, team: webapp, release-note

#12818 [usage] Remove unused config and functions
  components/usage/cmd/run.go
  components/usage/pkg/contentservice/client.go
  components/usage/pkg/contentservice/metrics.go
  components/usage/pkg/contentservice/noop.go
  components/usage/pkg/contentservice/usage_report.go
  components/usage/pkg/contentservice/usage_report_test.go
  components/usage/pkg/server/server.go
  components/usage/pkg/stripe/stripe.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/XL, team: webapp, release-note-none

#12855 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12860 Revert "Improve layer caching by moving apk commands up"
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, team: self-hosted

#12556 [agent-smith] Add more details to the infringement
  components/ee/agent-smith/pkg/agent/agent.go
Labels: size/XS, team: workspace, release-note-none

#12890 [ide]: pin latest JB plugin version
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/server/ide/configmap.go
Labels: size/M, team: IDE, release-note-none

#12746 [pvc] fix prebuilds when using pvc
  components/content-service/pkg/layer/provider.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: workspace, team: IDE, release-note-none

#12844 Adds vscode auth callback route
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
  components/proxy/conf/Caddyfile
  components/ws-proxy/pkg/proxy/pass.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/workspacerouter.go
  components/ws-proxy/pkg/proxy/workspacerouter_test.go
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none

#12885 [gpctl] Show when workspace has user activity
  dev/gpctl/cmd/workspaces-list.go
Labels: size/XS, team: workspace, release-note-none

#12878 [ws-daemon] Ensure add handler is called before update
  components/ws-daemon/pkg/dispatch/dispatch.go
Labels: size/S, team: workspace, release-note-none

#12856 workspace integration test: enhance TestRegularWorkspaceTasks test speed
  test/tests/components/ws-manager/tasks_test.go
Labels: size/M, team: workspace, release-note-none

#12859 workspace integration test: add PVC FF to TestPrebuildWorkspaceTaskSuccess
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/M, team: workspace, release-note-none

#12895 [ws-manager] add policy key to tracing in StopWorkspace call
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none

#12861 workspace integration test: refactor TestBackup
  test/go.mod
  test/go.sum
  test/pkg/integration/integration.go
  test/pkg/integration/workspace.go
  test/tests/components/ws-manager/content_test.go
  test/tests/components/ws-manager/multi_repo_test.go
  test/tests/components/ws-manager/prebuild_test.go
  test/tests/components/ws-manager/tasks_test.go
  test/tests/workspace/cgroup_v2_test.go
  test/tests/workspace/docker_test.go
  test/tests/workspace/example_test.go
  test/tests/workspace/k3s_test.go
  test/tests/workspace/mount_proc_test.go
Labels: size/L, team: workspace, release-note-none

#12896 [content-service] chown after prebuild git ops when using pvc
  components/content-service/pkg/initializer/prebuild.go
Labels: size/S, team: workspace, release-note-none

#12873 Remove deprecated Project DB `config` feature
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/migration/1662983610386-DropProjectConfig.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/usage/pkg/db/project_test.go
Labels: size/XXL, team: webapp, release-note-none

#12887 [UBP] Add `subscribeToStripe` server method
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, release-note-none

#12872 [dashboard] Show error messages in the UI when upgrading with Stripe fails
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Labels: size/S, team: webapp, release-note-none

#12761 [local-preview] Reduce storage requirements
  install/preview/entrypoint.sh
Labels: size/S, release-note, team: self-hosted

#12807 Preview-env don't wait for WS pods
  .werft/util/kubectl.ts
Labels: size/XS, release-note-none

#12858 [usage] smaller UI improvements
  components/dashboard/src/components/UsageView.tsx
Labels: size/M, team: webapp, release-note-none

#12907 Revert "Revert "Improve layer caching by moving apk commands up""
  install/installer/leeway.Dockerfile
Labels: size/XS, team: webapp, release-note-none, team: self-hosted

#12903 [usage-api] Use better typescript generator
  components/server/ee/src/billing/billing-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/container-module.ts
  components/server/src/workspace/workspace-starter.ts
  components/usage-api/generate.sh
  components/usage-api/typescript/package.json
  components/usage-api/typescript/src/google/protobuf/timestamp.pb.ts
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/billing_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_pb.js
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  scripts/protoc-generator.sh
  yarn.lock
Labels: size/XXL, team: webapp, release-note-none

#12917 [usage] Rename ReconcileUsageWithLedger to ReconcileUsage
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/scheduler/job.go
  components/usage/pkg/scheduler/job_test.go
Labels: size/XL, team: webapp, release-note-none

#12733 [UBP] Add placeholder billing configuration UI to the user settings page
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/settings/Billing.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Labels: size/M, team: webapp, release-note-none

#12898 test: fix broken slack notification
  .werft/workspace-run-integration-tests.sh
Labels: size/XS, team: workspace, release-note-none

#12921 [stripe] Use AttributionID metadata when querying for customers
  components/server/ee/src/user/stripe-service.ts
Labels: size/S, team: webapp, release-note-none

#12918 Remove deprecated sendFeedback server method
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#12875 [JetBrains Backend Plugin] Allow specifying the test-repository when running launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#12920 [installer]: make the installer config file consistent
  install/installer/cmd/config.go
  install/installer/cmd/render.go
  install/installer/cmd/validate_cluster.go
  install/installer/cmd/validate_config.go
Labels: size/S, release-note, team: self-hosted

#12926 [code] build stable image for 1.71.1 release
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#12929 [code] update stable browser code to 1.71.1
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: IDE, release-note

#12928 previews: Trigger artificial traffic every 2 hours
  .werft/platform-trigger-artificial-job.yaml
Labels: size/XS, release-note-none, team: platform

#12931 [usage] Remove unused WorkspaceInstanceUsage model
  components/usage/pkg/db/dbtest/workspace_instance_usage.go
  components/usage/pkg/db/order.go
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
Labels: size/XL, team: webapp, release-note-none
