Repository gitpod-io/gitpod, pull requests merged in 2022-08, with the labels that each got.

#11674 [dashboard] Hide PVC feature section when feat flag not set
  components/dashboard/src/projects/ProjectSettings.tsx
Labels: size/M, team: webapp, release-note-none

#11643 [server] add http endpoint workspacePageClose for beacon
  components/server/src/user/user-controller.ts
Labels: size/M, team: webapp, release-note-none

#11570 Fix find authorized user for GHE prebuilds
  components/server/ee/src/prebuilds/github-enterprise-app.ts
Labels: size/L, team: webapp, release-note

#11762 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11694 [usage] Extend method call with order arg
  components/dashboard/src/teams/TeamUsage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/typescript/src/usage/v1/sugar.ts
Labels: size/M, team: webapp, release-note-none

#11765 [server] Tie protected_secrets to ConfigCag
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#11772 Remove check for absence
  operations/observability/mixins/IDE/rules/components/openvsx-proxy/alerts.libsonnet
Labels: size/XS, team: IDE, release-note-none

#11773 [usage] Fix arguments to the listBilledUsage call
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/S, team: webapp, release-note-none

#11747 [usage] Delay gRPC self connection
  components/usage/pkg/server/dialer.go
  components/usage/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#11774 [usage] Enable sorting in the UI
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/S, release-note-none

#11779 [ws-daemon] Increase resources more real values
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: size/XS, team: workspace, release-note-none

#11781 [ws-manager] fix not handling workspaces that are completed
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_workspaceCompleted_01.golden
  components/ws-manager/pkg/manager/testdata/status_workspaceCompleted_01.golden
  components/ws-manager/pkg/manager/testdata/status_workspaceCompleted_01.json
Labels: size/XL, team: workspace, release-note-none

#11568 [installer-tests] Support tests against multiple version of k8s and ubuntu images
  .werft/installer-tests.ts
  .werft/jobs/build/self-hosted-upgrade-tests.ts
  install/infra/terraform/aks/kubernetes.tf
  install/infra/terraform/aks/variables.tf
  install/infra/terraform/eks/kubernetes.tf
  install/infra/terraform/eks/variables.tf
  install/infra/terraform/gke/main.tf
  install/infra/terraform/gke/variables.tf
  install/infra/terraform/k3s/main.tf
  install/infra/terraform/k3s/variables.tf
  install/tests/Makefile
  install/tests/main.tf
Labels: size/XL, release-note-none, team: self-hosted

#11244 Update feedback issue template
  .github/ISSUE_TEMPLATE/feedback_issue.yml
Labels: size/XS, release-note-none

#11782 Add kube-rbac-proxy to content-service
  install/installer/pkg/components/content-service/deployment.go
Labels: size/XS, team: workspace, release-note-none

#11793 Revert "TEST COMMIT"
  components/server/ee/src/user/user-service.ts
Labels: size/XS, team: webapp, release-note-none

#11799 Ensure workspace is only deleted once
  components/ws-daemon/pkg/internal/session/store.go
Labels: size/XS, team: workspace, release-note-none

#11434 [dashboard] Next steps nudge for local-preview
  components/dashboard/src/App.tsx
  components/dashboard/src/utils.ts
  install/preview/entrypoint.sh
  install/preview/manifests/coredns.yaml
Labels: size/M, team: webapp, release-note, team: product-design

#11681 [usage] Implement CollectUsage
  components/usage/pkg/apiv1/pricer.go
  components/usage/pkg/apiv1/pricer_test.go
  components/usage/pkg/apiv1/usage-report.go
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/server/server.go
Labels: size/XXL, team: webapp, release-note-none

#11805 Add observability debug on failure
  .werft/observability/monitoring-satellite.ts
Labels: size/M, release-note-none, team: platform

#11810 Fix the sleep in the cmd
  .werft/observability/monitoring-satellite.ts
Labels: size/XS, release-note-none, team: platform

#11808 Provide better error message for HTTP 524
  components/content-service/pkg/initializer/git.go
  components/content-service/pkg/initializer/prebuild.go
Labels: size/S, team: workspace, release-note-none

#11797 [usage] Add metrics for number of usage records
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reporter.go
Labels: size/S, team: webapp, release-note-none

#11802 Detach dangling base mounts
  components/ws-daemon/pkg/iws/iws.go
Labels: size/XS, team: workspace, release-note-none

#11826 Add annotation gitpod.io/startedDisposal ealier
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#11817 [server] better handle workspacePageClose endpoint response status and log ctx
  components/server/src/user/user-controller.ts
Labels: size/M, team: webapp, release-note-none

#11829 Get the Installer dependencies for every workspace
  .gitpod.yml
Labels: size/XS, release-note-none

#11798 [dashboard] Fix rendering of the redirect URI on Git Integrations page
  components/dashboard/src/settings/Integrations.tsx
Labels: size/XS, team: webapp, release-note

#11827 [dashboard] Fix displaying of logs for finished Prebuilds
  components/dashboard/src/components/PrebuildLogs.tsx
Labels: size/XS, team: webapp, release-note-none

#11840 Don't compile previewctl on workspace-startup
  .gitpod.yml
Labels: size/XS, release-note-none

#11800 [usage] Improve pagination behavior
  components/dashboard/src/Pagination/Pagination.tsx
  components/dashboard/src/Pagination/getPagination.spec.ts
  components/dashboard/src/Pagination/getPagination.ts
  components/dashboard/src/components/Pagination.tsx
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/L, team: webapp, release-note-none

#11824 add log when starting workspace with pvc
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, release-note-none

#11815 Replace with sorting icon
  components/dashboard/src/images/sort-arrow.svg
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/S, team: webapp, release-note-none

#11850 [ws-manager] Disable PVC feature
  components/ws-manager/pkg/manager/create.go
Labels: size/XS, team: workspace, release-note-none

#11819 Update README.md
  test/README.md
Labels: size/XS, release-note-none

#11853 Add support for HTTP_PROXY, HTTPS_PROXY and NO_PROXY in probes
  components/common-go/kubernetes/probes.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#11859 Revert add annotation gitpod.io/startedDisposal earlier
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#11851 [code] Point to 1.70 release branch
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#11832 [installer] Support configuration of the public API HTTP port
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/constants.go
  install/installer/pkg/components/public-api-server/service.go
Labels: size/S, team: webapp, release-note-none, team: self-hosted

#11841 [usage] Self-connection allows up to 30MB in message response
  components/usage/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#11863 [dashboard] Optimization: Don't wait before fetching a team's spending limit
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Labels: size/XS, team: webapp, release-note-none

#11864 [usage] Add alert on failed reconciliations
  operations/observability/mixins/meta/rules/components/components.libsonnet
  operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Labels: size/M, team: webapp, release-note-none

#11869 [installer] Add missing output.golden changes of #11807
  install/installer/cmd/testdata/render/minimal/output.golden
Labels: size/S, release-note-none, team: self-hosted

#11871 [installer] Fix writing golden files
  install/installer/cmd/render_test.go
Labels: size/XS, release-note-none, team: self-hosted

#11872 [installer] Fix writing golden files
  install/installer/cmd/render_test.go
Labels: size/XS, release-note-none, team: self-hosted

#11830 Log warning instead of tracing error span
  components/ws-daemon/pkg/content/service.go
Labels: size/M, team: workspace, release-note-none

#11855 previews: Add preview owner reference to certificates
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/prepare.ts
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11838 Remove fixed resources
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/user/eligibility-service.ts
  components/server/ee/src/workspace/workspace-starter.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.json
  install/installer/pkg/components/server/types.go
Labels: size/XXL, team: webapp, team: workspace, release-note-none

#11876 [installer] Small render test improvements
  install/installer/cmd/render_test.go
Labels: size/S, release-note-none, team: self-hosted

#11870 [gpctl] Add workspace type to workspaces list
  dev/gpctl/cmd/workspaces-list.go
Labels: size/M, team: workspace, release-note-none

#11831 [server] Introduce EntitlementServiceChargbee and move relevant parts of EligibilityService into it
  components/server/ee/src/billing/entitlement-service-chargebee.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/user/eligibility-service.spec.db.ts
  components/server/ee/src/user/eligibility-service.ts
  components/server/ee/src/user/user-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/ee/src/workspace/workspace-starter.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/container-module.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp, release-note-none

#11877 [code] update stable code image to fix changelog related url not works
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note, team: self-hosted

#11868 [db][usage] Add d_b_billed_session table migration and Go definitions
  components/gitpod-db/src/typeorm/migration/1659601647550-BilledSession.ts
  components/usage/pkg/db/billed_session.go
  components/usage/pkg/db/billed_session_test.go
Labels: size/M, team: webapp, release-note-none

#11548 Fixed some spelling errors in README.md
  README.md
Labels: community-contribution, size/S, release-note-none, cla: accepted :heavy_check_mark:

#11842 [billing] Report metrics on updated subscriptions
  components/usage/pkg/server/server.go
  components/usage/pkg/stripe/reporter.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: webapp, release-note-none

#11893 [content-service] handle git access denied error
  components/content-service/pkg/initializer/git.go
Labels: size/S, team: workspace, release-note-none

#11898 gpctl: support all workspace types.
  dev/gpctl/cmd/workspaces-list.go
Labels: size/XS, team: workspace, release-note

#11895 [content-init] do not hide error during git checkout
  components/content-service/pkg/initializer/git.go
Labels: size/XS, team: workspace, release-note-none

#11896 [blobserve] Fix lint issues
  components/blobserve/pkg/blobserve/blobserve.go
  components/blobserve/pkg/blobserve/blobspace.go
  components/blobserve/pkg/blobserve/blobspace_test.go
  components/blobserve/pkg/blobserve/refstore_test.go
Labels: component: blobserve, size/M, team: IDE, release-note-none

#11899 [code] build stable code image for 1.70
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#11647 [supervisor-frontend] use beacon to send heartbeat to avoid data loss
  components/supervisor/frontend/src/ide/gitpod-server-compatibility.ts
  components/supervisor/frontend/src/ide/heart-beat.ts
Labels: size/M, team: webapp, team: IDE, release-note-none

#11890 [usage] Fix UsageReconciliationFailures alert
  operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Labels: size/XS, team: webapp, release-note-none

#11900 [code] update stable code image to 1.70
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note, team: self-hosted

#11881 [codeowners] Allow all teams to approve installer testdata changes
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#10199 Replace AlertBox with Alert component
  components/dashboard/src/components/AlertBox.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/settings/Integrations.tsx
  components/dashboard/src/settings/Plans.tsx
  components/dashboard/src/settings/Teams.tsx
Labels: community-contribution, component: dashboard, type: improvement, size/M, team: webapp, release-note, cla: accepted :heavy_check_mark:

#11809 [ws-daemon] Enable workspace content housekeeping
  components/ws-daemon/pkg/internal/session/store.go
  components/ws-daemon/pkg/internal/session/store_test.go
Labels: size/L, team: workspace, release-note-none

#11879 [installer] Ensure stable ordering of rendered K8s objects
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/pkg/common/display.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none, team: self-hosted

#11907 [server] Add missing @injectable()
  components/server/src/billing/entitlement-service.ts
Labels: size/XS, team: webapp, release-note-none

#11908 [usage] Fix max call send message size
  components/usage/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#11905 [code] point nightly job back to gp-code/main
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#11878 [kots]: only add to base image allow list in airgapped mode
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note, team: self-hosted

#11777 When starting a workspace but usage attribution is unclear, prompt for explicit user choice
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/settings/Billing.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/user/user-service.ts
Labels: size/XL, team: webapp, release-note-none

#11920 [ws-daemon] Log update of resource limits
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
  components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go
Labels: size/XS, team: workspace, release-note-none

#11813 BillingMode: add Json RPC API methods (2/4)
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#11922 [usage] Add runbook link for GitpodUsageScheduledReconciliationFailures
  operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Labels: size/XS, team: webapp, release-note-none

#11882 [usage] Add `billInstancesAfter` config setting
  components/usage/cmd/run.go
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/server/server.go
Labels: size/L, team: webapp, release-note-none

#11923 [dashboard] fix arbitrary useEffect
  components/dashboard/src/App.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/settings/selectClass.tsx
Labels: size/XS, team: webapp, release-note-none

#11925 [usage] Add grpc client metrics, up max call sizes
  components/usage/pkg/server/server.go
Labels: size/S, team: webapp, release-note-none

#11921 [UBP] Add tests and functionality to the Stripe webhook handler
  components/public-api-server/pkg/webhooks/stripe.go
  components/public-api-server/pkg/webhooks/stripe_test.go
Labels: size/L, team: webapp, release-note-none

#11576 Stop sign on "out of credits"
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note

#11909 [usage] Proto changes for markBilledSession RPC
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/billing_pb.d.ts
  components/usage-api/typescript/src/usage/v1/billing_pb.js
  components/usage-api/usage/v1/billing.proto
Labels: size/XXL, team: webapp, release-note-none

#11873 Retry doFinalize if gRPC status code is Unavailable
  components/ws-manager/pkg/manager/monitor.go
Labels: size/M, team: workspace, release-note-none

#11931 Enable workspace classes feature for teams
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#11420 [alerts] change load avg alert to critical
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#11939 Return error to the client and only ignore tracing error
  components/ws-daemon/pkg/content/service.go
Labels: size/S, team: workspace, release-note-none

#11938 Ignore git error message `does not have any commits yet`
  components/content-service/pkg/git/git.go
  components/content-service/pkg/git/git_test.go
  components/content-service/pkg/initializer/git.go
  components/content-service/pkg/initializer/prebuild.go
Labels: size/M, team: workspace, release-note-none

#11933 fix log to output all info properly
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, release-note-none

#11948 registry-facade: Remove unnecessary varilable declaration.
  components/registry-facade/pkg/registry/blob.go
Labels: size/XS, team: workspace, release-note-none

#11913 Change installer testdata CODEOWNERS to anyone
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#11946 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#11943 [kots]: collect the user config in support bundles
  install/kots/manifests/kots-redactor.yaml
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/M, release-note, team: self-hosted

#11965 [kots]: fix typo which meant wasn't using the appSlug in config collect
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/XS, release-note, team: self-hosted

#11974 [common-go] Remove unused WorkspaceSupervisorEndpoint helper
  components/common-go/kubernetes/kubernetes.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#11983 ws-daemon: enhance log
  components/ws-daemon/pkg/internal/session/workspace.go
Labels: size/XS, team: workspace, release-note

#11980 Update the alert description unit
  operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
Labels: size/XS, team: webapp, release-note

#11957 Ensure workspace class is persisted
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, release-note-none

#11954 [installer]: remove the custom labels from the selector labels
  install/installer/cmd/testdata/render/customization/config.yaml
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/pkg/components/agent-smith/daemonset.go
  install/installer/pkg/components/blobserve/deployment.go
  install/installer/pkg/components/content-service/deployment.go
  install/installer/pkg/components/dashboard/deployment.go
  install/installer/pkg/components/database/cloudsql/deployment.go
  install/installer/pkg/components/ide-metrics/deployment.go
  install/installer/pkg/components/ide-proxy/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note, team: self-hosted

#11766 Set KOTS/Replicated dependencies to latest
  .gitpod.yml
  .werft/aks-installer-tests.yaml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/ide-integration-tests-startup.yaml
  .werft/k3s-installer-tests.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  .werft/run-integration-tests.yaml
  .werft/self-hosted-installer-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/image/Dockerfile
Labels: size/M, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#11978 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11653 [supervisor]: gitpod config changed analytics
  .pre-commit-config.yaml
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/installer/post-process.sh
  components/common-go/analytics/analytics.go
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/hack/generate-config.sh
  components/ide/jetbrains/image/status/main.go
  components/ide/jetbrains/image/status/main_test.go
  components/supervisor/cmd/run.go
  components/supervisor/pkg/config/gitpod-config-analytics.go
  components/supervisor/pkg/config/gitpod-config.go
  components/supervisor/pkg/config/gitpod-config_analytics_test.go
  components/supervisor/pkg/config/gitpod-config_test.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none

#12007 [ws-daemon] Include workspace id in error
  components/ws-daemon/pkg/content/service.go
Labels: size/XS, team: workspace, release-note-none

#11999 Add billing setup in sugar
  components/usage-api/typescript/src/usage/v1/sugar.ts
Labels: size/M, team: webapp, release-note-none

#12009 Update jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#11081 Auto-forward all workspace open ports when using Latest JetBrains IDEs
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodPortsService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/backend-plugin/src/test/kotlin/io/gitpod/jetbrains/remote/GitpodPortsServiceTest.kt
Labels: size/XL, team: IDE, release-note, editor: jetbrains

#12022 ws-daemon: add span when NewWorkspace
  components/ws-daemon/pkg/internal/session/store.go
Labels: size/XS, team: workspace, release-note-none

#11825 observability: Add a alert for the network connections.
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#11991 Upgrade Gradle for compatibility with Java 17
  components/gitpod-protocol/java/gradle/wrapper/gradle-wrapper.properties
  components/gitpod-protocol/java/gradlew
  components/ide-metrics-api/java/.classpath
  components/ide-metrics-api/java/.project
  components/ide-metrics-api/java/gradle/wrapper/gradle-wrapper.properties
  components/ide-metrics-api/java/gradlew
  components/ide/jetbrains/backend-plugin/gradle/wrapper/gradle-wrapper.jar
  components/ide/jetbrains/backend-plugin/gradle/wrapper/gradle-wrapper.properties
  components/ide/jetbrains/backend-plugin/gradlew
  components/ide/jetbrains/backend-plugin/gradlew.bat
  components/ide/jetbrains/gateway-plugin/gradle/wrapper/gradle-wrapper.jar
  components/ide/jetbrains/gateway-plugin/gradle/wrapper/gradle-wrapper.properties
  components/ide/jetbrains/gateway-plugin/gradlew
  components/ide/jetbrains/gateway-plugin/gradlew.bat
  components/supervisor-api/java/gradle/wrapper/gradle-wrapper.properties
  components/supervisor-api/java/gradlew
Labels: size/XXL, team: IDE, release-note-none

#12025 Fix redirect on team usage page
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/S, team: webapp, release-note-none

#11977 [IDE jobs] only post interesting notifications to Slack
  .github/workflows/code-nightly.yaml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates-template.yml
Labels: size/S, team: IDE, release-note-none

#11856 previews: Implement certificate garbage collection
  .werft/platform-delete-preview-environments-cron.ts
Labels: size/M, release-note-none, team: platform

#12031 [installer]: use typemeta declaration in the helm customisations
  install/installer/cmd/testdata/render/statefulset-customization/config.yaml
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/pkg/helm/helm.go
Labels: size/XXL, release-note, team: self-hosted

#12034 Increase threshold for unavailable targets
  operations/observability/mixins/platform/rules/scrape.libsonnet
Labels: size/XS, release-note-none, team: platform

#11949 [UBP] Add placeholder implementation of `FinalizeInvoice`
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
Labels: size/S, team: webapp, release-note-none

#12016 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11749 [installer-tests] Add slack webhook for test failures
  .werft/aks-installer-tests.yaml
  .werft/cleanup-installer-setups.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/installer-tests.ts
  .werft/k3s-installer-tests.yaml
  .werft/self-hosted-installer-tests.yaml
  install/tests/Makefile
  install/tests/manifests/kots-config.yaml
Labels: size/XL, release-note-none, team: self-hosted

#12037 [installer]: escape inline yaml keys for labels/annotations in Helm
  install/installer/cmd/testdata/render/customization/config.yaml
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/pkg/helm/helm.go
Labels: size/XL, release-note, team: self-hosted

#11976 Add clone3 to seccomp profile syscalls
  components/docker-up/dependencies.sh
  components/docker-up/docker-up/main.go
  components/docker-up/go.mod
  components/docker-up/go.sum
  components/ws-daemon/seccomp-profile-installer/main.go
Labels: size/S, team: workspace, release-note-none

#12046 [installer] Fix lint issue
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XS, team: workspace, release-note-none

#12047 Restrict codeowners of 'supervisor-api' only to '.proto' files
  .github/CODEOWNERS
Labels: size/XS, team: IDE, release-note-none

#12044 content-service: check remote branch exists before git checkout
  components/content-service/pkg/initializer/git.go
Labels: size/S, team: workspace, release-note-none

#12054 [code] build stable code image for 1.70.1
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#11888 [usage] Implement markWorkspaceInstanceSessionAsBilled
  components/server/ee/src/billing/billing-mode.ts
  components/server/src/container-module.ts
  components/server/src/workspace/workspace-starter.ts
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/apiv1/size_test.go
  components/usage/pkg/db/billed_session.go
  components/usage/pkg/server/server.go
Labels: size/L, team: webapp, release-note-none

#12055 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#12039 Add support for the new observability installer in preview environments
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/job-config.ts
  .werft/observability/monitoring-satellite.ts
Labels: size/L, release-note-none, team: platform

#12059 observability: add #workspace > 20 in alert GitpodWorkspaceTooManyRegularNotActive
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#12070 Fix order of installer testdata ownership
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#12069 Workspace integration tests: Poll for job phase instead of tailing logs
  .werft/workspace-run-integration-tests.sh
  .werft/workspace-run-integration-tests.yaml
Labels: size/L, team: workspace, release-note-none

#12032 Fix IntelliJ IDEA detection of Gradle projects from Gitpod repository
  .idea/.gitignore
  .idea/gradle.xml
  .idea/misc.xml
  components/gitpod-protocol/java/.classpath
  components/ide/jetbrains/backend-plugin/.classpath
  components/supervisor-api/java/.classpath
Labels: size/M, team: IDE, release-note-none, editor: jetbrains

#12074 Avoid displaying prebuild-related workspaces in the workspaces list from JetBrains Gateway
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/Workspace.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceType.java
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#12080 [server] maintain workspace instance state
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: size/S, team: webapp, release-note-none

#12053 [JetBrains] Show Workspace CPU/Memory resources in control center
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
Labels: component: ide, size/L, team: IDE, release-note, editor: jetbrains

#12052 [Gitpod CLI] Highlight current task in `gp tasks list`
  components/gitpod-cli/cmd/tasks-list.go
Labels: component: gp cli, size/S, team: IDE, release-note

#12081 Workspace integration tests: Improve message when preview env build job fails
  .werft/workspace-run-integration-tests.sh
Labels: size/M, team: workspace, release-note-none

#12085 [bug][usage] Fixes return of SetBilledSession
  components/usage/pkg/apiv1/billing.go
Labels: size/XS, team: webapp, release-note-none

#12087 [Gitpod CLI] Align `gp top` thresholds with JetBrains
  components/gitpod-cli/cmd/top.go
Labels: component: gp cli, size/XS, team: IDE, release-note-none

#12006 Update Platform Version from stable JetBrains Backend Plugin
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#12071 Fix X-Forwarded-* headers in openvsx-proxy
  components/openvsx-proxy/pkg/handler.go
  components/openvsx-proxy/pkg/modifyresponse.go
  components/openvsx-proxy/pkg/openvsxproxy_test.go
  components/openvsx-proxy/pkg/run.go
Labels: size/L, team: IDE, release-note-none

#12101 [registry-facade] Improve IPFS logging
  components/registry-facade/pkg/registry/blob.go
  components/registry-facade/pkg/registry/http_client.go
Labels: size/M, team: workspace, release-note-none

#12106 [registry-facade] Remove unnecessary check
  components/registry-facade/pkg/registry/blob.go
Labels: size/XS, team: workspace, release-note-none

#12110 Fix workspace integration test
  test/pkg/integration/integration.go
Labels: size/XS, team: workspace, release-note-none

#12127 loadgen: Slight README improvement.
  dev/loadgen/README.md
Labels: size/XS, team: workspace, release-note-none

#12111 [server] Don't redirect to sorry on unrecognized login errors
  components/server/src/auth/generic-auth-provider.ts
Labels: size/XS, team: webapp, release-note-none

#12040 [dashboard] Show workspace class in admin view
  components/dashboard/src/admin/WorkspaceDetail.tsx
Labels: size/XS, team: webapp, release-note-none

#12123 [usage] Use actual date for start time
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/S, team: webapp, release-note-none

#12102 [dashboard] allow to open desktop links on app domain
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/M, team: webapp, release-note-none

#12082 redirect to desktop IDE on app domain
  components/supervisor/frontend/src/ide/heart-beat.ts
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/M, team: IDE, release-note

#12018 ws-daemon: ignore error when workspace persistent state location not exist
  components/ws-daemon/pkg/internal/session/workspace.go
Labels: size/XS, team: workspace, release-note-none

#12122 [usage] Increase results per page to 50
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/XS, team: webapp, release-note-none

#12105 [server] fix using snapshotBucketId when it is undefined or empty
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#12146 removed vscode java pack
  .gitpod.yml
Labels: size/XS, release-note-none
