Repository gitpod-io/gitpod, pull requests merged in 2022-07, with the labels that each got.

#11060 [alerts] fix pod/container/namespace not rendering
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#11059 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11031 Update project settings preference copy
  components/dashboard/src/projects/ProjectSettings.tsx
Labels: size/XS, team: webapp, release-note-none

#10925 [telemetry] Add new `telemetry.data` config option for telemetry
  components/installation-telemetry/cmd/send.go
  gitpod-ws.code-workspace
  install/installer/pkg/components/gitpod/cronjob.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/kots/manifests/gitpod-installer-job.yaml
  install/preview/entrypoint.sh
Labels: size/M, release-note, team: self-hosted

#11075 [kots] update image to be the latest config change build
  install/kots/manifests/gitpod-installation-status.yaml
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note-none, team: self-hosted

#11074 [server] Workaround for lagging prebuild permissions
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note

#11086 Update prebuild status description alignment
  components/dashboard/src/projects/Prebuilds.tsx
Labels: size/XS, team: webapp, release-note-none

#11100 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11102 [licensor] Align dirty repo state
  components/licensor/typescript/ee/src/api.ts
Labels: size/XS, team: webapp, release-note-none

#11110 [ws-proxy] Add X-Forwarded-Port header
  components/ws-proxy/pkg/proxy/routes.go
Labels: size/XS, team: workspace, release-note

#11117 Temporarily use a fixed version of JetBrains Gateway SDK
  components/ide/jetbrains/gateway-plugin/gradle.properties
Labels: size/XS, team: IDE, release-note-none

#11028 [usage] Use a config file to configure usage component
  components/usage/BUILD.yaml
  components/usage/cmd/run.go
  components/usage/config.json
  components/usage/go.mod
  components/usage/pkg/server/server.go
  install/installer/BUILD.yaml
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
  install/installer/pkg/components/usage/constants.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/usage/deployment_test.go
  install/installer/pkg/components/usage/objects_test.go
  install/installer/pkg/components/usage/stripe.go
Labels: size/XL, team: webapp, release-note-none, team: self-hosted

#11095 Point Code Nightly to gp-code/release/1.69
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#11122 remove certificate kubectl wait assert
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11130 [ws-proxy] Refactor SSH heartbeat GRPC connection
  components/ws-proxy/cmd/run.go
Labels: size/XS, team: workspace, release-note-none

#11129 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11126 [supervisor] Remove signal terminated log
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#11077 [preview] run the telemetry job right after gitpod is ready
  install/preview/entrypoint.sh
Labels: size/S, release-note, team: self-hosted

#11119 [prebuild] Fix view when coming from prefix
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/M, team: webapp, release-note-none

#11138 Align access level of Workspaces of type "prebuild" with Prebuilds
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
Labels: size/L, team: webapp, release-note

#11141 Fix certificate alert to add more debug and use ask handle
  .werft/util/certs.ts
  .werft/util/slack.ts
Labels: size/S, release-note-none, team: platform

#11096 [installer]: set a stable password for messagebus
  install/installer/pkg/common/render.go
  install/installer/pkg/components/rabbitmq/secret.go
Labels: size/S, release-note, team: self-hosted

#11111 [kots]: add firewall check for the pull registry
  install/kots/manifests/kots-preflight.yaml
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/M, release-note, team: self-hosted

#11157 [ws-daemon] Increase process priority
  components/ws-daemon/cmd/run.go
Labels: size/S, team: workspace, release-note-none

#11133 obserbility: Add a alert for AutoscaleFailure.
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#11161 [installer] fix workspace template generation
  install/installer/pkg/components/ws-manager/configmap.go
  install/installer/pkg/components/ws-manager/configmap_test.go
Labels: size/M, team: workspace, release-note-none

#11158 ws-manager: Replace backup/restore success with total metric
  components/ws-manager/pkg/manager/metrics.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/M, team: workspace, release-note-none

#11151 Update containerd and docker dependencies
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/workspacekit/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  dev/preview/previewctl/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/L, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#11040 Fix the upgrade tests and use annotations from JSON
  .werft/aks-installer-tests.yaml
  .werft/eks-installer-tests.yaml
  .werft/installer-tests.ts
  .werft/jobs/build/job-config.ts
  .werft/jobs/build/self-hosted-upgrade-tests.ts
  .werft/k3s-installer-tests.yaml
  .werft/run-sh-upgrade-tests-gke.yaml
  .werft/self-hosted-installer-tests.yaml
  install/tests/Makefile
  install/tests/main.tf
Labels: size/XXL, release-note-none, team: self-hosted

#11175 Fix incompatible column type in DBBlockedRepository
  components/gitpod-db/src/typeorm/entity/db-blocked-repository.ts
  components/gitpod-db/src/typeorm/migration/1657105883801-BlockedRepositoryFix.ts
Labels: size/M, team: webapp, release-note-none

#11184 [ws-daemon] Fix extraction of process arguments
  components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
Labels: size/XS, team: workspace, release-note-none

#11186 [ws-daemon] Add additional process type priorities
  components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/M, team: workspace, release-note-none

#11187 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#11080 [server] Add server API to list blocked repositories
  components/gitpod-db/src/blocked-repository-db.spec.db.ts
  components/gitpod-db/src/blocked-repository-db.ts
  components/gitpod-db/src/typeorm/blocked-repository-db-impl.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#11191 [server] Log hasReadAccess errors
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
Labels: size/XS, team: webapp, release-note-none

#11196 [db-sync] Escape column names
  components/ee/db-sync/src/export.ts
Labels: size/XS, team: webapp, release-note-none

#11210 [ws-daemon] Remove WorkspaceInfo noisy log
  components/ws-daemon/pkg/iws/iws.go
Labels: size/XS, team: workspace, release-note-none

#11218 [code] Generate stable images for 1.69
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#11220 [code] Update stable to 1.69
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#11192 [prebuild] Make prebuild logs view more responsive
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/XS, team: webapp, release-note

#11197 Escape column names in INSERT statement
  components/ee/db-sync/src/export.ts
Labels: size/XS, team: webapp, release-note-none

#11221 [usage] Add initial gRPC API
  components/public-api-server/pkg/server/server.go
  components/usage-api/buf.yaml
  components/usage-api/generate.sh
  components/usage-api/go.mod
  components/usage-api/go.sum
  components/usage-api/go/BUILD.yaml
  components/usage-api/go/go.mod
  components/usage-api/go/go.sum
  components/usage-api/go/v1/pagination.pb.go
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/tools.go
  components/usage-api/usage/v1/pagination.proto
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/server/server.go
  install/installer/BUILD.yaml
  install/installer/go.mod
  install/installer/go.sum
Labels: size/XXL, team: webapp, release-note-none, team: self-hosted

#11234 [dashboard] Show assigned node for workspace
  components/dashboard/src/admin/WorkspaceDetail.tsx
Labels: size/XS, team: webapp, release-note-none

#11235 [configcat] Add code scanning for feature flags
  .github/workflows/configcat.yml
Labels: size/S, release-note-none

#11239 [feature flags] Nudge passing in full User shapes and derive email from it
  components/dashboard/src/Menu.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/settings/Preferences.tsx
  components/gitpod-protocol/src/experiments/configcat.ts
  components/gitpod-protocol/src/experiments/types.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#11236 [usage] Add network policy to allow ingress from server
  install/installer/pkg/components/usage/networkpolicy.go
  install/installer/pkg/components/usage/objects.go
  install/installer/pkg/components/usage/objects_test.go
Labels: size/M, team: webapp, release-note-none

#11194 [ws-manager-bridge] Use WS update status version
  components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/XXL, team: webapp, release-note-none

#11216 [ws-manager] log errors as warnings during exponential backoff
  components/ws-manager/pkg/manager/manager.go
Labels: size/S, team: workspace, release-note-none

#11230 [gpctl] add command to get last heartbeat time of workspace
  dev/gpctl/cmd/workspaces-last-heartbeat.go
Labels: size/M, team: workspace, release-note-none

#11245 [code] point code nightly to gp-code/main branch
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#11253 [ws-proxy] Remove the port number from "X-Forwarded-Host" header as it's already defined in "X-Forwarded-Port"
  components/ws-proxy/pkg/proxy/routes.go
Labels: size/XS, team: workspace, release-note

#11247 Improve "GitpodWorkspaceTooManyRegularNotActive" alert
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#11254 [Analytics] move "project_created" call to projects-service.ts and add project ID
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#11258 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11208 Implement skateboard Usage view with dummy data
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/TeamUsage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp, release-note

#11260 [local-preview] Differentiate btw Gitpod `starting` and `running`
  install/preview/prettylog/main.go
Labels: size/XS, release-note, team: self-hosted

#11246 Add `function:getSSHPublicKeys` scope to vscode client
  components/server/src/oauth-server/db.ts
Labels: size/XS, team: webapp, release-note-none

#11282 [server] Reduce gitpod_server_api_calls_duration_seconds precision, add 2 buckets
  components/server/src/prometheus-metrics.ts
Labels: size/XS, team: webapp, release-note-none

#11268 [installer]: add test for customization of proxy service
  install/installer/pkg/common/customize_test.go
Labels: size/S, release-note, team: self-hosted

#11286 [db-sync] Escape column name in UPDATE statement
  components/ee/db-sync/src/export.ts
Labels: size/XS, team: webapp, release-note-none

#11292 [code] build stable image for 1.69.0 with ports onOpen fix
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#11293 [code] upgrade stable code with ports onOpen fix
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#11242 [local-preview] Support `127-0-0-1.nip.io` for `DOMAIN`
  install/preview/entrypoint.sh
  install/preview/manifests/coredns.yaml
Labels: size/L, release-note, team: self-hosted

#11295 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11283 Basic usage API for TypeScript (1/3)
  .github/CODEOWNERS
  components/usage-api/generate.sh
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/BUILD.yaml
  components/usage-api/typescript/mocha.opts
  components/usage-api/typescript/package.json
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/typescript/tsconfig.json
  components/usage-api/usage/v1/pagination.proto
  components/usage-api/usage/v1/usage.proto
  gitpod-ws.code-workspace
Labels: size/XXL, team: webapp, release-note-none

#11262 [usage] Set reconcile duration buckets to 30s, up to 300s
  components/usage/pkg/controller/reporter.go
Labels: size/XS, team: webapp, release-note-none

#11264 [usage] Billing controller returns an error
  components/usage/pkg/controller/billing.go
  components/usage/pkg/controller/reconciler.go
Labels: size/S, team: webapp, release-note-none

#11252 [installer-tests] Fix the k3s installer tests YAML
  .werft/k3s-installer-tests.yaml
Labels: size/M, release-note-none

#11304 Add feature flag for blocked repositories UI
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/admin/BlockedRepositorySettings.tsx
  components/dashboard/src/admin/License.tsx
  components/dashboard/src/admin/PageWithAdminSubMenu.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/admin/admin-menu.ts
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/index.tsx
Labels: size/L, team: webapp, release-note-none

#11306 Specify the KUBECONFIG var in the cmctl command
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11209 Update 'gateway-plugin' to work with JetBrains Gateway v222.3345.1+
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/M, team: IDE, release-note, editor: jetbrains

#11320 [server, protocol] GuardedCostCenter and AttributionId.parse/render (3/5)
  components/gitpod-protocol/src/attribution.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
  components/server/src/user/user-service.ts
Labels: size/XL, team: webapp, release-note-none

#11325 [code] Generate stable image for 1.69.1
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#11326 [code] Update stable to 1.69.1
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#11330 [ws-daemon] improve DisposeWorkspace logging
  components/ws-daemon/pkg/content/service.go
Labels: size/S, team: workspace, release-note-none

#11329 fix unhelpful log messages
  components/supervisor/pkg/ports/served-ports.go
  components/workspacekit/cmd/rings.go
Labels: size/XS, team: workspace, team: IDE, release-note-none

#11332 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11219 [installer] improve ws-proxy configmap
  install/installer/pkg/components/ws-proxy/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: workspace, release-note-none, team: self-hosted

#11185 [installer] improve ws-manager config
  install/installer/pkg/components/ws-manager/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: workspace, release-note-none, team: self-hosted

#11109 [usage] Workspace Pricer uses config
  .werft/jobs/build/installer/installer.ts
  components/usage/config.json
  components/usage/pkg/server/server.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp, release-note-none, team: self-hosted

#11099 [kots]: add monitoring graphs
  install/kots/manifests/kots-app.yaml
Labels: size/S, release-note, team: self-hosted

#11237 [kots]: add node CPU/memory check tests to workspace node only
  install/kots/manifests/kots-preflight.yaml
Labels: size/M, release-note, team: self-hosted

#11307 Clean code from GitpodServerLauncher and update JetBrains backend-plugin to work when user has proxies
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServerLauncher.java
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/testclient/TestClient.java
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
Labels: size/M, team: IDE, release-note

#11021 Add `function:sendHeartBeat` scope
  components/server/src/oauth-server/db.ts
Labels: size/XS, team: webapp, release-note-none

#11341 [local-preview] show `DOMAIN` in the output
  install/preview/entrypoint.sh
  install/preview/prettylog/main.go
Labels: size/S, release-note, team: self-hosted

#11333 Enhance workspace integration test
  .werft/workspace-run-integration-tests.yaml
Labels: size/XS, team: workspace, release-note-none

#11331 [ws-daemon] do not fail workspace if git status failed during dispose
  components/ws-daemon/pkg/content/service.go
Labels: size/XS, team: workspace, release-note-none

#11359 Implement hasReadAccess for Bitbucket
  components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
Labels: size/M, team: webapp, release-note-none

#11376 Fix cert loop
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11377 Fix the check cert function
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11390 [content-service] Do not stash untracked files
  components/content-service/pkg/initializer/prebuild.go
Labels: size/XS, team: workspace, release-note-none

#11392 [ws-manager] Remove temporal workaround for kubelet issue
  components/ws-manager/pkg/manager/manager.go
Labels: size/L, release-note-none

#11393 [ws-daemon] Increase number of concurrent backup uploads
  components/ws-daemon/pkg/content/service.go
Labels: size/XS, team: workspace, release-note-none

#11394 [content-service] Fix TestGitStatusFromFiles test
  components/content-service/pkg/git/git_test.go
Labels: size/S, team: workspace, release-note-none

#11382 [supervisor] Refactor content-init error handling
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/S, team: IDE, release-note-none

#11396 [ws-manager] Wait for pod running before removing annotations
  components/ws-manager/pkg/manager/manager.go
Labels: size/M, team: workspace, release-note-none

#11356 Record webhook events
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/typeorm/entity/db-webhook-event.ts
  components/gitpod-db/src/typeorm/migration/1657702361007-AddWebhookEvent.ts
  components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
  components/gitpod-db/src/webhook-event-db.ts
  components/gitpod-protocol/src/index.ts
  components/gitpod-protocol/src/webhook-event.ts
  components/server/ee/src/prebuilds/bitbucket-app.ts
  components/server/ee/src/prebuilds/bitbucket-server-app.ts
  components/server/ee/src/prebuilds/github-app.ts
  components/server/ee/src/prebuilds/github-enterprise-app.ts
  components/server/ee/src/prebuilds/gitlab-app.ts
Labels: size/XL, team: webapp, release-note-none

#11405 Simple UI for Prebuild Events (sneak preview)
  components/dashboard/src/App.tsx
  components/dashboard/src/projects/Events.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp, release-note-none

#11407 Add missing permission to watch node object
  install/installer/pkg/components/ws-manager/role.go
Labels: size/XS, team: workspace, release-note-none

#11419 [ws-manager] do not overwrite failed state
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.golden
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.golden
Labels: size/S, team: workspace, release-note-none

#11421 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11409 Test if auth host is reachable
  components/server/package.json
  components/server/src/auth/auth-provider-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  yarn.lock
Labels: aspect: security, size/M, team: webapp, release-note

#11432 [server] Fix tracing and logging when aborting prebuilds on newer push
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: size/M, team: webapp, release-note-none

#11438 Fix cert exec commands to correctly return debug
  .werft/util/certs.ts
Labels: size/XS, release-note-none, team: platform

#11387 [usage] Implement `GetBilledUsage` RPC
  components/dashboard/src/teams/TeamUsage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/sugar.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_grpc_pb.js
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
  components/usage/pkg/server/server.go
Labels: size/XXL, team: webapp, release-note-none

#11439 [usage] Store user, project, workspace, type & class + migration
  1658144661198-WorkspaceInstanceUsageAddExtraFields.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-instance-usage.ts
Labels: size/M, team: webapp, release-note-none

#11443 [usage] Use floating point values to hold instance credit usage
  components/usage/pkg/controller/billing.go
  components/usage/pkg/controller/billing_test.go
  components/usage/pkg/controller/reconciler.go
Labels: size/M, team: webapp, release-note-none

#11445 Update Preview env's dashboard with new metrics
  operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Labels: size/S, release-note-none, team: platform

#11448 [ws-daemon] Add support for limiting number of processes in workspaces
  components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: workspace, release-note, team: self-hosted

#11457 Add mising db-sync config for d_b_webhook_event
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note-none

#11323 [kots]: delete channel on branch delete
  .github/workflows/delete-kots-channel.yml
Labels: size/M, release-note-none, team: self-hosted

#11444 [usage] Add user, workspace, project, type, class to WorkspaceInstanceUsage in go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
Labels: size/M, team: webapp, release-note-none

#11446 [dashboard] BlockedRepo UI
  components/dashboard/src/App.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/BlockedRepositorySettings.tsx
Labels: size/XL, team: webapp, release-note-none, team: product-design

#11461 [code] Generate stable image for 1.69.2
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#11460 [usage] Store workspace, project, type & class
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/dbtest/workspace.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
  components/usage/pkg/db/workspace_instance_usage.go
Labels: size/L, team: webapp, release-note-none

#11465 [common-go] Add experiments client & ConfigCat implementation
  components/common-go/experiments/configcat.go
  components/common-go/experiments/flags.go
  components/common-go/experiments/noop.go
  components/common-go/experiments/types.go
  components/common-go/experiments/types_test.go
  components/common-go/go.mod
  components/common-go/go.sum
Labels: size/L, team: webapp, team: workspace, release-note-none

#11464 [code] Update stable to 1.69.2
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#11471 [configcat] Upgrade JS SDKs
  components/dashboard/package.json
  components/gitpod-protocol/package.json
  components/server/package.json
  yarn.lock
Labels: size/XXL, team: webapp, release-note-none

#11417 Simplify configuration of git setting safe.directory
  components/content-service/pkg/git/git.go
  components/content-service/pkg/initializer/git.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/ws-daemon/BUILD.yaml
  components/ws-daemon/default.gitconfig
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/internal/session/workspace.go
  test/pkg/integration/common/git-client.go
  test/tests/workspace/contexts_test.go
  test/tests/workspace/git_test.go
Labels: size/M, team: workspace, team: IDE, release-note-none

#11487 Add dashboard for swap utilization per cluster and node
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/node-swap.json
Labels: size/L, team: workspace, release-note-none

#11490 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10788 [db][protocol] Implement a CostCenter entity to attribute workspace usage to
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/cost-center-db.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/cost-center-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-cost-center.ts
  components/gitpod-db/src/typeorm/migration/1658241900000-CostCenter.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp, release-note-none

#11484 [usage] Make endTime non-mandatory for billed session
  components/dashboard/src/teams/TeamUsage.tsx
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#11497 [usage] Tiny fix to use variable rather than literal value in test
  components/usage/pkg/controller/reconciler_test.go
Labels: size/XS, team: webapp, release-note-none

#11348 [kots]: add preflight checks for IDE/meta nodes
  install/kots/manifests/kots-preflight.yaml
Labels: size/M, release-note, team: self-hosted

#11500 [usage] Remove dummy data from server
  components/gitpod-protocol/src/usage.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#11501 [usage] Round credit & hours values in UI
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/XS, team: webapp, release-note-none

#11505 [usage] Ensure billed usage results are ordered
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
Labels: size/M, team: webapp, release-note-none

#11506 Add Summary row to Gitpod overview dashboard
  operations/observability/mixins/Makefile
  operations/observability/mixins/components/bar_gauge_panel.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.libsonnet
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none, team: platform

#11516 [ws-manager] fix not handling err in initializeWorkspaceContent
  components/ws-manager/pkg/manager/monitor.go
Labels: size/XS, team: workspace, release-note-none

#11520 Change blobserve CODEOWNERS to team IDE
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#11412 [local-preview] Remove `cert-manager` dependency
  install/preview/entrypoint.sh
  install/preview/leeway.Dockerfile
Labels: size/L, release-note, team: self-hosted

#11389 Support VSCodium for Settings Sync
  components/server/src/oauth-server/db.ts
Labels: size/XS, team: webapp, team: IDE, release-note-none

#11515 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#11481 [UBP] Pagination and UI fixes
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/Arrow.tsx
  components/dashboard/src/components/DropDown.tsx
  components/dashboard/src/components/Pagination.tsx
  components/dashboard/src/images/credits.svg
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/TeamUsage.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-protocol/src/usage.ts
Labels: size/XL, team: webapp, release-note-none

#11522 Move usageAttributionId
  components/dashboard/src/settings/Billing.tsx
  components/gitpod-db/src/typeorm/migration/1658394096656-UsageAttributionId.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#11508 Add Spending Limit to Billing page
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note

#11529 Fix team reviews in Jetbrains auto updates
  .github/workflows/jetbrains-updates-template.yml
Labels: size/XS, release-note-none

#11546 [installer] Disable integration tests during upgrade tests
  .werft/jobs/build/self-hosted-upgrade-tests.ts
Labels: size/XS, release-note-none

#11518 Refactor ws-daemon and registry-facade postStart hook
  components/registry-facade/BUILD.yaml
  components/registry-facade/leeway.Dockerfile
  components/ws-daemon/BUILD.yaml
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/leeway.Dockerfile
  dev/ready-probe-labeler/BUILD.yaml
  dev/ready-probe-labeler/go.mod
  dev/ready-probe-labeler/go.sum
  dev/ready-probe-labeler/main.go
  gitpod-ws.code-workspace
  install/installer/pkg/components/registry-facade/clusterrole.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: size/XXL, team: workspace, release-note-none

#11550 Remove the duplicated error message
  components/ws-manager/cmd/run.go
Labels: size/S, team: workspace, release-note-none

#11523 Adjust the Workspace Start URL the in JetBrains Gateway workspaces list
  components/ide/jetbrains/gateway-plugin/README.md
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/M, team: IDE, release-note, editor: jetbrains

#11543 [server] GH: Send 401 with message on failed webhook
  components/server/ee/src/prebuilds/github-enterprise-app.ts
Labels: size/XS, team: webapp, release-note

#11507 [usage] ListUsage filters by time range
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/dbtest/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
Labels: size/XL, team: webapp, release-note-none

#11554 [UBP] View without data or access
  components/dashboard/src/teams/TeamUsage.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/L, team: webapp, release-note-none

#11562 [usage] ListBilledUsage allows to specify ordering
  components/usage-api/buf.yaml
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/typescript/src/usage/v1/usage_pb.d.ts
  components/usage-api/typescript/src/usage/v1/usage_pb.js
  components/usage-api/usage/v1/usage.proto
Labels: size/L, team: webapp, release-note-none

#11547 Refactor Manager StartWorkspace
  components/ws-manager-api/typescript/src/promisified-client.ts
  components/ws-manager/pkg/manager/manager.go
Labels: size/M, team: workspace, release-note-none

#11577 [usage] By default sort results descending
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/workspace_instance_usage.go
  components/usage/pkg/db/workspace_instance_usage_test.go
Labels: size/M, team: webapp, release-note-none

#11569 Add a delete rety and fail into the certificate issue function
  .werft/util/certs.ts
Labels: size/S, release-note-none, team: platform

#11560 Remove config for cpu bucket limiting in preview environments
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/helm/values.variant.cpuLimits.yaml
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
Labels: size/S, release-note-none
