Repository gitpod-io/gitpod, pull requests merged in 2022-05, with the labels that each got.

#9669 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9672 Preivew Envs: Change with-vm from opt-in to opt-out
  .werft/jobs/build/job-config.ts
Labels: size/XS, release-note-none, team: platform

#9671 K3s in preview envs: authenticate with docker hub to avoid rate limit
  .werft/build.yaml
  .werft/vm/manifests.ts
Labels: size/M, release-note-none, team: platform

#9679 Give more resources to build
  .werft/build.yaml
Labels: size/XS, release-note-none, team: platform

#9681 Ensure deleteVM is idempotent
  .werft/vm/vm.ts
Labels: size/XS, release-note-none, team: platform

#9617 Laushinka/server logs incoming 9556
  components/public-api-server/main.go
  components/public-api-server/middleware/logging.go
  components/public-api-server/middleware/logging_test.go
Labels: size/M, team: webapp, release-note-none

#9675 [observability] Add alerts for pending phase
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/M, team: workspace, release-note-none

#9683 [helm] Fix ws-manager configmap
  chart/templates/ws-manager-configmap.yaml
Labels: size/M, release-note-none

#9692 Do not swallow config errors
  components/ws-daemon/pkg/config/config.go
Labels: size/XS, team: workspace, release-note-none

#9699 [docker-up] Update docker compose to 2.5.0
  components/docker-up/BUILD.yaml
Labels: size/XS, team: workspace, release-note

#9668 [code] point code nightly to gp-code/release/1.67 branch
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#9694 GetPrebuild mock implementation
  components/public-api-server/pkg/apiv1/prebuild.go
  components/public-api-server/pkg/apiv1/prebuild_test.go
Labels: size/M, team: webapp, release-note-none

#9708 [image-builder-bob] Update buildkit to v0.10.2
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-bob/leeway.Dockerfile
Labels: team: workspace, release-note

#9606 [public-api] Remove google.Status from proto responses
  components/public-api-server/pkg/apiv1/prebuild.go
  components/public-api-server/pkg/apiv1/prebuild_test.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api/BUILD.yaml
  components/public-api/generate.sh
  components/public-api/gitpod/v1/prebuilds.proto
  components/public-api/gitpod/v1/workspaces.proto
  components/public-api/go/v1/prebuilds.pb.go
  components/public-api/go/v1/workspaces.pb.go
  components/public-api/hack/protoc-gen-gplint/BUILD.yaml
  components/public-api/hack/protoc-gen-gplint/go.mod
  components/public-api/hack/protoc-gen-gplint/go.sum
  components/public-api/hack/protoc-gen-gplint/main.go
  components/public-api/typescript/src/gitpod/v1/prebuilds_grpc_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/prebuilds_grpc_pb.js
  components/public-api/typescript/src/gitpod/v1/prebuilds_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/prebuilds_pb.js
  components/public-api/typescript/src/gitpod/v1/workspaces_grpc_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/workspaces_grpc_pb.js
  components/public-api/typescript/src/gitpod/v1/workspaces_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/workspaces_pb.js
Labels: size/XXL, team: webapp, release-note-none

#9711 [ws-daemon] Remove workspaceSizeLimit
  chart/templates/ws-daemon-configmap.yaml
Labels: size/XS, release-note-none

#9703 [public-api] Extract BearerToken from request
  components/public-api-server/integration_test.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/M, team: webapp, release-note-none

#9706 [supervisor] Improve IDE readiness probe
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: IDE, release-note

#9715 [public-api] Restructure packages to better align with other components
  components/public-api-server/main.go
  components/public-api-server/pkg/server/integration_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/L, release-note-none

#9691 Extend cron job to handle VM-based preview envs
  .werft/platform-delete-preview-environments-cron.ts
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/util/werft.ts
Labels: size/XL, release-note-none, team: platform

#9734 [installer] Fix shortname usage
  install/installer/pkg/common/common.go
Labels: size/XS, release-note-none, team: self-hosted

#9707 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9746 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9717 [installer]: Add server chargebee configuration to the installer
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp, release-note, team: self-hosted

#9701 kots: Support s3 backend with incluster registry
  install/kots/manifests/gitpod-installer-job.yaml
  install/kots/manifests/gitpod-registry-s3-backend.yaml
  install/kots/manifests/kots-config.yaml
Labels: size/M, release-note, team: self-hosted

#9748 Add workspace integration tests for Git LFS support
  test/tests/workspace/git_test.go
Labels: size/M, team: workspace, release-note-none

#9677 Remove sweeper
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/wipe-devstaging.ts
  chart/templates/db-deny-all-allow-explicit-networkpolicy.yaml
  codecov.yml
  dev/BUILD.yaml
  dev/charts/sweeper/.helmignore
  dev/charts/sweeper/Chart.yaml
  dev/charts/sweeper/templates/_helpers.tpl
  dev/charts/sweeper/templates/deployment.yaml
  dev/charts/sweeper/values.yaml
  dev/sweeper/BUILD.yaml
  dev/sweeper/go.mod
  dev/sweeper/go.sum
  dev/sweeper/leeway.Dockerfile
  dev/sweeper/main.go
  gitpod-ws.code-workspace
Labels: size/XXL, release-note-none, team: platform

#9754 Improve process handling and show stdout/stderr in portforward-monitoring-satellite-harvester.sh
  dev/preview/util/portforward-monitoring-satellite-harvester.sh
Labels: size/S, release-note-none, team: platform

#9721 [licensor] force preinstall to build `liblicensor.a`
  components/licensor/typescript/BUILD.yaml
  components/licensor/typescript/ee/src/api.ts
Labels: size/S, team: webapp, release-note-none, team: self-hosted

#9741 [kots]: improve installer job failure recovery
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/S, release-note, team: self-hosted

#9756 [installer] Make runDbDeleter configurable for the server component
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/configmap_test.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, release-note, team: self-hosted

#9704 [public-api] Proxy GetWorkspace to server
  components/public-api-server/BUILD.yaml
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/proxy/conn.go
  components/public-api-server/pkg/server/integration_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/XL, team: webapp, release-note-none

#9740 [public-api] Set config in installer
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
  install/installer/pkg/components/public-api-server/objects_test.go
Labels: size/M, team: webapp, release-note-none

#9753 [dev] Add werft credential helper
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup-jetbrains.yaml
  .werft/ide-integration-tests-startup-vscode.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-clean-up-werft-build-nodes.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-integration-tests-startup-cron.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/image/Dockerfile
  dev/preview/werft-credential-helper.sh
Labels: size/S, team: workspace, team: IDE, release-note-none, team: platform

#9727 [registry-facade] Split off port for readiness probe
  components/blobserve/cmd/run.go
  components/common-go/kubernetes/probes.go
  components/registry-facade/cmd/run.go
Labels: size/S, team: webapp, team: workspace, release-note

#9761 [code]: Generate stable images for 1.67
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9777 [code] Update stable to 1.67
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#9768 [ws-manager] Reduce readiness probe initialDelaySeconds
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class.golden
  components/ws-manager/pkg/manager/testdata/cdwp_customcerts.golden
  components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
  components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_probe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
  components/ws-manager/pkg/manager/testdata/cdwp_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
  components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
  components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
Labels: size/M, team: workspace, release-note

#9762 [server] blocklist repositories
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/config.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, release-note

#9781 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#9783 [integration-test] Fix image build test
  test/tests/components/image-builder/builder_test.go
Labels: size/XS, release-note-none

#9738 Use link component class for the editor selection modal
  components/dashboard/src/settings/SelectIDEModal.tsx
Labels: size/XS, team: webapp, release-note

#9779 [installer] Minor alignments + fixes
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/database/cloudsql/deployment.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/objects.go
Labels: size/M, team: webapp, release-note-none, team: self-hosted

#9780 [installer-diff] Filter out unwanted objects, and reduce noise
  dev/installer-diff/cmd/filter.go
Labels: size/M, release-note-none

#9769 [dashboard] Minor refactor of Card and SolidCard components
  components/dashboard/src/admin/License.tsx
  components/dashboard/src/components/Card.tsx
  components/dashboard/src/components/SolidCard.tsx
Labels: size/M, team: webapp, release-note-none

#9805 [ws-manager] add cluster role needed for volume snapshots content access
  install/installer/pkg/components/ws-manager/role.go
  install/installer/pkg/components/ws-manager/rolebinding.go
Labels: size/M, team: workspace, release-note-none

#9809 [content-service] Add logs for Redis pipeline errors
  components/registry-facade/pkg/registry/cache.go
Labels: size/S, team: workspace, release-note

#9813 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9654 [server] Make account deletion for fault tolerant
  components/server/src/user/user-deletion-service.ts
Labels: size/M, team: webapp, release-note

#9799 [installer] Fix server GitHub app cert mount
  install/installer/pkg/components/server/deployment.go
Labels: size/XS, team: webapp, release-note-none

#9803 [ws-manager] fix calling dispose multiple times
  components/ws-manager/pkg/manager/annotations.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note

#9771 [dashboard] handle unlimited users condition in license page
  components/dashboard/src/admin/License.tsx
Labels: size/XS, team: webapp, release-note-none

#8248 Add env var name/value length validation
  components/gitpod-protocol/src/protocol.ts
Labels: community-contribution, meta: never-stale, size/XS, team: webapp, release-note, cla: accepted :heavy_check_mark:

#9840 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9850 Fix typo
  dev/preview/util/download-and-merge-harvester-kubeconfig.sh
Labels: size/XS, release-note-none, team: platform

#9853 Fix typo
  dev/preview/install-k3s-kubeconfig.sh
Labels: size/XS, release-note-none, team: platform

#9859 Update GitLab logo
  components/dashboard/src/images/gitlab.svg
Labels: size/S, team: webapp, release-note

#9860 [Analytics] Add team properties to team_joined call
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#9663 [dashboard] increase IDE awareness for onboarding users when starting workspace
  components/dashboard/src/App.tsx
  components/dashboard/src/settings/SelectIDEModal.tsx
Labels: size/S, team: webapp, release-note

#9818 Update bug label in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size/XS, release-note-none

#9655 [db][protocol] Implement TeamSubscription2 DB shapes and migration
  components/dashboard/src/settings/Plans.tsx
  components/ee/payment-endpoint/src/accounting/subscription-model.ts
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/team-subscription-2-db.ts
  components/gitpod-db/src/typeorm/deleted-entry-gc.ts
  components/gitpod-db/src/typeorm/entity/db-subscription.ts
  components/gitpod-db/src/typeorm/entity/db-team-membership.ts
  components/gitpod-db/src/typeorm/entity/db-team-subscription-2.ts
  components/gitpod-db/src/typeorm/migration/1650526577994-TeamSubscrition2.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/team-subscription-2-db-impl.ts
  components/gitpod-protocol/src/accounting-protocol.ts
  components/gitpod-protocol/src/team-subscription-protocol.ts
Labels: size/XL, team: webapp, release-note-none

#9214 workspacekit: Remove slirp4netns codes where it affects the supervisor.
  components/workspacekit/cmd/rings.go
Labels: size/XS, team: workspace, release-note

#9877 [code] point code nightly back to gp-code/main branch
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#9881 Update buildkit to v0.10.3
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note

#9869 [pre-commit] Ensure a file is either empty, or ends with one newline
  .pre-commit-config.yaml
Labels: size/XS, team: webapp, release-note-none

#9871 [werft] Configure payment with installer
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/installer/post-process.sh
  .werft/jobs/build/payment/chargebee-config-secret.yaml
  .werft/jobs/build/payment/payment-endpoint-deployment.yaml
  .werft/jobs/build/payment/payment-endpoint-networkpolicy.yaml
  .werft/jobs/build/payment/payment-endpoint-rolebinding.yaml
  .werft/jobs/build/payment/payment-endpoint-service-account.yaml
  .werft/jobs/build/payment/payment-endpoint-service.yaml
  .werft/jobs/build/payment/render.ts
Labels: size/XL, release-note-none, team: platform

#9880 [licensor] cleanup duplicate license types
  components/licensor/ee/pkg/licensor/gitpod.go
  components/licensor/ee/pkg/licensor/licensor.go
  components/licensor/ee/pkg/licensor/licensor_test.go
  components/licensor/ee/pkg/licensor/replicated.go
  components/licensor/typescript/ee/src/api.ts
Labels: size/M, team: webapp, release-note-none

#9870 [pre-commit] Add go fmt, go mod tidy & bump versions
  .pre-commit-config.yaml
Labels: size/S, team: webapp, release-note-none

#9863 Laushinka/add metrics for server 9824
  components/public-api-server/pkg/proxy/conn.go
  components/public-api-server/pkg/proxy/prometheusmetrics.go
  components/public-api-server/pkg/proxy/prometheusmetrics_test.go
  components/public-api-server/pkg/server/integration_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#9879 [baseserver] Expose gRPC prometheus metrics
  components/common-go/baseserver/options.go
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
Labels: size/M, team: webapp, release-note-none

#9714 [ws-manager] Explicitly proxy image-builder
  components/ws-manager/BUILD.yaml
  components/ws-manager/cmd/run.go
  components/ws-manager/go.mod
  components/ws-manager/go.sum
  components/ws-manager/pkg/proxy/imagebuilder.go
Labels: size/L, team: workspace, release-note-none

#9907 [ws-manager] Fix CDWP test
  components/ws-manager/pkg/manager/testdata/cdwp_class_notfound.golden
Labels: size/XS, team: workspace, release-note-none

#9913 Enable build cache for gradle tasks and run them in parallel when possible, to reduce their duration
  .gitpod.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#9882 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9917 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9914 [public-api] Add network policy to allow connections from proxy
  install/installer/pkg/components/public-api-server/networkpolicy.go
  install/installer/pkg/components/public-api-server/networkpolicy_test.go
  install/installer/pkg/components/public-api-server/objects.go
Labels: size/L, team: webapp, release-note-none

#9905 Run cleanup job on each Werft build node
  .werft/platform-clean-up-werft-build-node.yaml
  .werft/platform-trigger-werft-cleanup.yaml
Labels: size/M, release-note-none, team: platform

#9825 Ensure workspace can be deleted even if context timed out
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note

#9916 [bridge] Fix logging
  components/ws-manager-bridge/src/bridge-controller.ts
Labels: size/XS, team: webapp, release-note-none

#9941 [dashboard] fixing backoff for getHeadlessLog calls
  components/dashboard/src/components/PrebuildLogs.tsx
Labels: size/S, team: webapp, release-note

#9912 fix grpc proto generation
  scripts/protoc-generator.sh
Labels: size/XS, release-note-none

#9924 [bridge] Fix wrong mapping of WorkspaceStatus to prebuild when "snapshot" is missing
  components/ws-manager-bridge/BUILD.yaml
  components/ws-manager-bridge/ee/src/bridge.ts
  components/ws-manager-bridge/mocha.opts
  components/ws-manager-bridge/package.json
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.spec.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.ts
Labels: size/XL, team: webapp, release-note

#9936 [prebuilds] no prebuilds for inactive repos
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: size/M, team: webapp, release-note-none

#9954 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#9951 [workspacekit] improve logging when not able to connect to daemon
  components/workspacekit/cmd/rings.go
Labels: size/S, team: workspace, release-note-none

#9943 [ws-daemon] fix restore from snapshot not working
  components/content-service/pkg/storage/gcloud.go
  components/content-service/pkg/storage/minio.go
  components/ws-daemon/pkg/content/initializer.go
Labels: size/S, team: workspace, release-note

#9947 [installer] Small render improvements
  install/installer/cmd/render.go
Labels: size/M, release-note, team: self-hosted

#9886 Change imagePullPolicy to IfNotPresent
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup-jetbrains.yaml
  .werft/ide-integration-tests-startup-vscode.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/jobs/build/helm/values.dev.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-run-integration-tests.yaml
Labels: size/S, team: workspace, team: IDE, release-note-none, team: platform

#9957 [gitpod-db] fix tables.ts
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note

#9889 [Analytics] Fix Dotfile Tracking
  components/dashboard/src/settings/Preferences.tsx
Labels: size/S, team: webapp, release-note-none

#9959 Revert "[prebuilds] no prebuilds for inactive repos"
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: team: webapp, release-note

#9960 [integration-test] Partially fix TestRegularWorkspaceTasks
  test/pkg/integration/integration.go
  test/tests/components/ws-manager/tasks_test.go
Labels: size/M, release-note-none

#9958 [baseserver] gRPC Health service
  components/common-go/baseserver/options.go
  components/common-go/baseserver/options_test.go
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
Labels: size/M, team: webapp, release-note-none

#9963 Remove `dev/installer-diff` program
  dev/installer-diff/.gitignore
  dev/installer-diff/BUILD.yaml
  dev/installer-diff/README.md
  dev/installer-diff/cmd/filter.go
  dev/installer-diff/cmd/root.go
  dev/installer-diff/go.mod
  dev/installer-diff/go.sum
  dev/installer-diff/main.go
Labels: size/XXL, release-note-none

#9964 remove with-helm and associated functions
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/job-config.ts
Labels: size/L, release-note-none

#9968 [integration-test] Add supervisor task status test
  test/tests/components/ws-manager/tasks_test.go
Labels: size/M, team: workspace, release-note-none

#9987 [content-service] fix gcloud test
  components/content-service/pkg/storage/gcloud_test.go
Labels: size/XS, team: workspace, release-note-none

#9985 [pre-commit] Add license header check
  .pre-commit-config.yaml
Labels: size/XS, release-note-none

#9979 [dashboard] fix workspace start stuck in checking during ide onboarding
  components/dashboard/src/App.tsx
Labels: size/S, team: webapp, release-note-none

#9829 [public-api] Convert server errors to appropriate RPC errors
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/proxy/errors.go
  components/public-api-server/pkg/proxy/errors_test.go
Labels: size/L, team: webapp, release-note-none

#9992 ws-daemon: improve start up time of iws for workspacekit
  components/ws-daemon/pkg/content/hooks.go
Labels: size/XS, team: workspace, release-note-none

#9961 [supervisor] inflate all git repos
  components/content-service/pkg/initializer/initializer.go
  components/content-service/pkg/initializer/initializer_test.go
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/ws-daemon/pkg/content/service.go
  components/ws-manager/README.md
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class_notfound.golden
  components/ws-manager/pkg/manager/testdata/cdwp_customcerts.golden
  components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
  components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_probe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
  components/ws-manager/pkg/manager/testdata/cdwp_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
  components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
  components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
  components/ws-manager/pkg/manager/testdata/getWorkspaces_podOnly.json
  components/ws-manager/pkg/manager/testdata/status_brokenScheduler_UNKNOWN00.json
  components/ws-manager/pkg/manager/testdata/status_cannotPull_004_CREATING00.json
  components/ws-manager/pkg/manager/testdata/status_cannotPull_005_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_contentInitFailed_005_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_degenerate_noWorkspaceID.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED02.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED03.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.json
  components/ws-manager/pkg/manager/testdata/status_errimgpull.json
  components/ws-manager/pkg/manager/testdata/status_errimgpull_CREATING01.json
  components/ws-manager/pkg/manager/testdata/status_failedBeforeStopping_explicitFail.json
  components/ws-manager/pkg/manager/testdata/status_failedLogs_RUNNING00.json
  components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.json
  components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json
Labels: size/XL, team: workspace, team: IDE, release-note

#9903 Validate scopes per client
  components/server/src/oauth-server/db.ts
  components/server/src/oauth-server/repository.ts
Labels: size/S, team: webapp, release-note-none

#9949 Expose a new environment variable `JETBRAINS_GITPOD_WORKSPACE_HOST` to be displayed on JB IDE Hostname widget
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodGatewayClientCustomizationProvider.kt
  components/ide/jetbrains/image/status/main.go
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#9922 [public-api] Add role binding for kube-rbac-proxy to auth metric scrapes
  install/installer/pkg/components/public-api-server/rolebinding.go
Labels: size/M, team: webapp, release-note-none

#9938 Only end the span if it exists
  .werft/util/werft.ts
Labels: size/XS, release-note-none, team: platform

#9995 [ws-daemon] Remove stray "cannot write limit" errors
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go
Labels: size/XS, team: workspace, release-note

#9983 [public api] Add `gpctl api workspace ownertoken` command
  dev/gpctl/cmd/api/root.go
  dev/gpctl/cmd/api/workspaces-get.go
  dev/gpctl/cmd/api/workspaces-ownertoken.go
  dev/gpctl/cmd/api/workspaces.go
  scripts/protoc-generator.sh
Labels: size/L, team: workspace, release-note-none

#10003 Improve automated PR description for JetBrains auto-update
  .github/workflows/jetbrains-updates-template.yml
  .github/workflows/jetbrains-updates.yml
Labels: size/S, team: IDE, release-note-none

#10000 [integration-test] Enable tests to run from local
  test/README.md
  test/pkg/integration/apis.go
  test/pkg/integration/common/port_forward.go
  test/pkg/integration/integration.go
  test/tests/components/content-service/content-service_test.go
Labels: size/L, team: workspace, release-note-none

#9996 workspacekit: Record the errors of connecting to ws-daemon
  components/workspacekit/cmd/rings.go
Labels: size/XS, team: workspace, release-note-none

#10026 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#10029 Add meta ID and owner to find workspace image-build Pod
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none

#10006 Revert "[bridge] Fix wrong mapping of WorkspaceStatus to prebuild when "snapshot" is missing"
  components/ws-manager-bridge/BUILD.yaml
  components/ws-manager-bridge/ee/src/bridge.ts
  components/ws-manager-bridge/mocha.opts
  components/ws-manager-bridge/package.json
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.spec.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.ts
Labels: size/XL, team: webapp

#10034 [ws-man-bridge] Add cluster role binding to scrape metrics
  install/installer/pkg/components/ws-manager-bridge/rolebinding.go
Labels: size/S, team: webapp, release-note

#10047 Temporary skip the TestMissingBackup pvc test to make the integration test pass
  test/tests/components/ws-manager/content_test.go
Labels: size/XS, team: workspace, release-note-none

#9819 Pass quality to code build process
  .github/workflows/code-nightly.yaml
  WORKSPACE.yaml
  components/ide/code/BUILD.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/S, team: IDE, release-note-none

#10050 [baseserver] Initialize go metrics automatically
  components/common-go/baseserver/server.go
Labels: size/M, team: webapp, team: workspace, release-note-none

#10055 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10015 [jb-backend] add jb_active_language tracking
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
Labels: size/M, team: IDE, release-note-none

#9755 Edit kots advanced mode wording
  install/kots/manifests/kots-config.yaml
Labels: size/S, release-note-none, team: self-hosted

#10053 [ws-manager] make sure to fail prebuild if we cannot store snapshot from it
  components/ws-manager/pkg/manager/monitor.go
Labels: size/XS, team: workspace, release-note

#10058 [code] update stable image 1.67.0 with active language tracking and i…
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#10052 [public-api] Publish to NPM
  components/BUILD.yaml
  components/public-api/typescript/BUILD.yaml
  components/public-api/typescript/package.json
  components/public-api/typescript/src/gitpod/v1/pagination_grpc_pb.js
  components/public-api/typescript/src/gitpod/v1/pagination_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/pagination_pb.js
  components/public-api/typescript/src/gitpod/v1/prebuilds_grpc_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/prebuilds_grpc_pb.js
  components/public-api/typescript/src/gitpod/v1/prebuilds_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/prebuilds_pb.js
  components/public-api/typescript/src/gitpod/v1/workspaces_grpc_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/workspaces_grpc_pb.js
  components/public-api/typescript/src/gitpod/v1/workspaces_pb.d.ts
  components/public-api/typescript/src/gitpod/v1/workspaces_pb.js
Labels: size/L, team: webapp, release-note

#10060 [public api] Enable gRPC reflection
  components/common-go/baseserver/server.go
Labels: size/XS, team: webapp, team: workspace, release-note

#10082 [ws-daemon] log when ready probe fails
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/S, team: workspace, release-note

#10079 Install gitpod.gitpod-theme as builtin extension
  WORKSPACE.yaml
  components/ide/code/codehelper/main.go
Labels: size/XS, team: IDE, release-note-none

#10069 [licensor] allow invalid domain in professional license
  components/licensor/ee/pkg/licensor/licensor.go
  components/licensor/ee/pkg/licensor/licensor_test.go
  components/licensor/ee/pkg/licensor/replicated.go
  components/licensor/typescript/ee/main.go
Labels: size/S, team: webapp, release-note-none

#10066 Update bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: size/XS, release-note-none

#10096 [baseserver] Failed certificate setup errors, instead of exiting
  components/common-go/baseserver/server.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10097 [public-api] Default local server run to port 9001, same as installer config
  components/public-api-server/main.go
Labels: size/XS, team: webapp, release-note-none

#10031 [image-builder] Fix error when secret is a json
  components/image-builder-bob/pkg/proxy/auth.go
  components/image-builder-mk3/pkg/auth/auth.go
Labels: size/XS, team: workspace, release-note

#10099 [public-api] Do not use localhost as address, not reachable in containers/k8s
  components/common-go/baseserver/server.go
  components/public-api-server/pkg/server/server.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10102 [db] enable overriding of expiryDate on tokens
  components/gitpod-db/src/typeorm/user-db-impl.ts
Labels: size/S, team: webapp, release-note

#10104 [payment] Set excludeFromMoreResources to true by default for new legacy Team Plans
  components/ee/payment-endpoint/src/chargebee/team-subscription-handler.ts
Labels: size/XS, team: webapp, release-note-none

#10109 [baseserver] Change default metrics port to 9502 to not clash with kube-rbac-proxy
  components/common-go/baseserver/server.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10113 [ws-daemon] ensure readyiness probe will not block indefinetely
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/XS, team: workspace, release-note-none

#10114 seccomp notify: correction of system call name in the log.
  components/workspacekit/pkg/seccomp/notify.go
Labels: size/XS, team: workspace, release-note

#10112 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#10016 [alerts] add alert when autoscaler adds nodes rapidly
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#10119 Move % to after the number
  .werft/platform-trigger-werft-cleanup.sh
Labels: size/XS, release-note-none, team: platform

#10117 [public-api] Align command structure with other servers
  components/public-api-server/cmd/root.go
  components/public-api-server/cmd/run.go
  components/public-api-server/main.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
Labels: size/L, team: webapp, release-note-none

#10121 Bump workflows dependencies' version
  .github/workflows/code-nightly.yaml
  .github/workflows/jetbrains-auto-update-template.yml
Labels: size/S, release-note-none

#10110 Replace UA logo
  components/dashboard/src/icons/gitpod-ua.svg
  components/dashboard/src/icons/gitpod.svg
  components/dashboard/src/start/StartPage.tsx
Labels: size/S, team: webapp, release-note-none

#10130 Use the builds nodepool. Workload is going away
  .werft/wipe-devstaging.yaml
Labels: size/XS, release-note-none, team: platform

#10135 Update spacing between theme options
  components/dashboard/src/settings/Preferences.tsx
Labels: size/XS, team: webapp, release-note

#10094 [image-builder-bob] Use separate auth for target and base
  components/image-builder-bob/cmd/proxy.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Labels: size/M, team: workspace, release-note

#10061 [dashboard] implement feedback modal 9928
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/PillMenuItem.tsx
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
  components/dashboard/src/feedback-form/FeedbackModal.tsx
  components/dashboard/src/images/feedback/crying-emoji.svg
  components/dashboard/src/images/feedback/happy-emoji.svg
  components/dashboard/src/images/feedback/meh-emoji.svg
  components/dashboard/src/images/feedback/starry-emoji.svg
  components/dashboard/src/index.css
Labels: size/L, team: webapp, release-note

#9492 Remove stargz from builder bob
  components/image-builder-bob/pkg/builder/builder.go
Labels: size/XS, team: workspace, release-note

#10136 Update dotfiles layout in user preferences
  components/dashboard/src/settings/Preferences.tsx
Labels: size/S, team: webapp, release-note

#10151 [server] log less errors
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
  components/server/src/bitbucket/bitbucket-file-provider.ts
  components/server/src/github/file-provider.ts
  components/server/src/gitlab/file-provider.ts
Labels: team: webapp, release-note
