Repository gitpod-io/gitpod, pull requests merged in 2022-11, with the labels that each got.

#14307 [code] build stable image to fix in-product changelog
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#14308 [code] update stable code to fix in-product changelog
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#14068 ws-manager: remove PVC once the workspace pod is unschedulable
  components/ws-manager/pkg/manager/manager.go
Labels: size/S, team: workspace, release-note-none

#14300 [gitpod-protocol] Add support for getTeams to golang client
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
Labels: size/S, team: webapp, release-note-none

#14314 [public-api] Add member_since to TeamMember definition
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Labels: size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14134 [db] Change the primary key of the `d_b_workspace_cluster` table
  components/gitpod-db/src/typeorm/migration/1666611052662-ChangeWorkspaceClusterTablePK.ts
Labels: size/S, team: webapp, release-note-none

#14317 [JetBrains] Fix the IDE version to download in GitHub Action
  .github/workflows/jetbrains-auto-update-template.yml
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#14318 [JetBrains] Run the GitHub Action only when `backend-plugin/gradle-latest.properties` changes
  .github/workflows/jetbrains-auto-update.yml
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#14319 [JetBrains] Set the GitHub Action to run also on schedule
  .github/workflows/jetbrains-auto-update.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14296 [server] Add metric for completed image builds
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, release-note-none

#14152 [public-api] Implement experimental TeamsService.CreateTeam
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api-server/pkg/proxy/errors.go
  components/public-api-server/pkg/proxy/errors_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/XL, team: webapp, release-note-none

#14232 [dashboard] Use public-api to CreateTeams
  components/dashboard/BUILD.yaml
  components/dashboard/package.json
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/L, team: webapp, release-note-none

#14326 [public-api] Implement member_since on TeamMember
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/M, team: webapp, release-note-none

#14044 [usage] Implement CreateStripeSubscription
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/server/server.go
  components/usage/pkg/stripe/stripe.go
  components/usage/pkg/stripe/stripe_test.go
  install/installer/pkg/components/usage/configmap.go
Labels: size/L, team: webapp, release-note-none

#14323 [db] Add extra assertions to workspace cluster db tests
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
Labels: size/L, team: webapp, release-note-none

#14327 [usage] Use workspaceClass displayName in Usage view
  components/dashboard/src/components/UsageView.tsx
Labels: size/S, team: webapp, release-note-none

#14333 [ws-daemon] Force build of container image
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note-none

#14324 [loadgen] Allow parallel runs
  dev/loadgen/.gitignore
  dev/loadgen/README.md
  dev/loadgen/cmd/benchmark.go
  dev/loadgen/cmd/run.go
  dev/loadgen/pkg/loadgen/executor.go
Labels: size/L, team: workspace, release-note-none

#13882 [image-builder-bob] Enable wait if error in debug mode
  components/image-builder-bob/cmd/root.go
Labels: size/XS, team: workspace, release-note-none

#14096 [pvc] add init container to workspace to chown pvc mount folder
  components/ws-manager/pkg/manager/create.go
Labels: size/S, team: workspace, release-note-none

#14337 [public-api] Define experimental GetTeam RPC
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/go/experimental/v1/teams_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/teams.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14338 [public-api] Add alerts for no metrics and failing RPCs
  operations/observability/mixins/meta/rules/public-api.yaml
Labels: size/M, team: webapp, release-note-none

#14249 [usage]Actually reset usage during ResetUsage RPC
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/db/cost_center.go
  components/usage/pkg/db/cost_center_test.go
  components/usage/pkg/db/dbtest/cost_center.go
Labels: size/L, team: webapp, release-note-none

#14339 [public-api] Add avatar_url and full_name to TeamMember
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Labels: size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14341 [ws-manager-bridge] Take the applicationCluster from config
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: size/S, team: webapp, release-note-none

#14301 [public-api] Implement experimental ListTeams
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/L, team: webapp, release-note-none

#14346 kubecdl: use label filter to find the exact cluster
  dev/kubecdl/main.go
Labels: size/XS, release-note-none

#14330 [server] Do not fail joining a team you're already a member of
  components/dashboard/src/teams/JoinTeam.tsx
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#14299 Add links to explore cardinality metrics
  operations/observability/mixins/self-hosted/dashboards/observability/cardinality-management-overview.json
Labels: size/S, release-note-none, team: delivery-operations-experience

#14313 [dashboard] ListTeams using PublicAPI
  components/dashboard/src/App.tsx
Labels: size/S, team: webapp, release-note-none

#14347 [dashboard] Fix public api feature flag name
  components/dashboard/src/contexts/FeatureFlagContext.tsx
Labels: size/XS, team: webapp, release-note-none

#14332 [usage] Use createStripeSubscription behind feature flag
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#14355 kubecdl: filter the instance-type = control-plane
  dev/kubecdl/main.go
Labels: size/XS, release-note-none

#14357 [openvsx-mirror] stable dashboard variables
  operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Labels: size/XS, team: IDE, release-note-none

#14136 [db-sync] Add the `d_b_workspace_cluster` table to sync config
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note-none

#14285 [image-builder-mk3] Commit sequence diagram
  components/image-builder-mk3/README.md
  docs/workspace/image-builder-mk3/README.md
  docs/workspace/image-builder-mk3/sequencediagram.svg
  docs/workspace/image-builder-mk3/sequencediagram.txt
Labels: size/M, team: workspace, release-note-none

#14354 [blobserve] remove not exists file replacement
  components/blobserve/pkg/blobserve/blobspace.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/S, team: IDE, release-note-none

#14356 [JetBrains EAP] Add actions `Copy URL` and `Copy Web URL` to the terminal's ports context menu
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodCopyUrlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodCopyWebUrlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortsActionCopyUrl.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
Labels: size/L, team: IDE, release-note, editor: jetbrains

#14262 [JetBrains Gateway Plugin] Publish automatically to stable channel
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14371 Update stable to `1.73`
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#14370 [grafana] Fix Connect / server error requests labels
  operations/observability/mixins/cross-teams/dashboards/gitpod-connect-server.json
Labels: size/XS, team: webapp, team: workspace, team: IDE, release-note-none, team: devx, team: delivery-operations-experience

#14366 refactor dispose workspace when using pvc
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/L, team: workspace, release-note-none

#14344 [bitbucket-server] improve logging of webhook installation
  components/server/ee/src/prebuilds/bitbucket-server-service.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
Labels: size/S, team: webapp, release-note-none

#14368 Revert "Default to letsencrypt cert issuer"
  .werft/jobs/build/job-config.ts
Labels: size/XS, release-note-none, team: devx

#14343 [public-api] Implement experimental GetTeam
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/M, team: webapp, release-note-none

#14373 [public-api] Add primary_email to TeamMember
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14328 [public-api] Implement experimental JoinTeam
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/M, team: webapp, release-note-none

#14385 [gitpod-protocol] Add ResetGenericInvite to golang client
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
Labels: size/S, team: webapp, release-note-none

#14377 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14389 [usage] Make reset usage task configurable through installer
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, release-note-none, team: delivery-operations-experience

#14369 [Jetbrains] Use single copy to clipboard approach
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ShareWorkspaceSnapshotAction.kt
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14383 Skip the cannot mount workspace event because it might be an intermediate state
  components/ws-manager/pkg/manager/metrics.go
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_failedWorkspaceMount_PENDING00.golden
  components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.golden
Labels: size/M, team: workspace, release-note-none

#14391 [local-preview] Update status messages to depend on echo's
  install/preview/entrypoint.sh
  install/preview/prettylog/main.go
Labels: size/XS, release-note, team: delivery-operations-experience

#14241 Refactor `previewctl install-context`
  dev/preview/previewctl/cmd/credentials.go
  dev/preview/previewctl/cmd/install_context.go
  dev/preview/previewctl/cmd/list_previews.go
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/go.mod
  dev/preview/previewctl/go.sum
  dev/preview/previewctl/main.go
  dev/preview/previewctl/pkg/gcloud/config.go
  dev/preview/previewctl/pkg/k8s/config.go
  dev/preview/previewctl/pkg/k8s/context.go
  dev/preview/previewctl/pkg/k8s/context/gke/dev.go
  dev/preview/previewctl/pkg/k8s/context/gke/dev_test.go
  dev/preview/previewctl/pkg/k8s/context/harvester/harvester.go
  dev/preview/previewctl/pkg/k8s/context/harvester/harvester_test.go
  dev/preview/previewctl/pkg/k8s/context/k3s/k3s.go
  dev/preview/previewctl/pkg/k8s/context/k3s/k3s_test.go
  dev/preview/previewctl/pkg/k8s/context/loader.go
  dev/preview/previewctl/pkg/k8s/harvester.go
  dev/preview/previewctl/pkg/k8s/pforward.go
  dev/preview/previewctl/pkg/k8s/service.go
  dev/preview/previewctl/pkg/k8s/service_test.go
  dev/preview/previewctl/pkg/k8s/vm.go
  dev/preview/previewctl/pkg/k8s/vm_test.go
  dev/preview/previewctl/pkg/preview/preview.go
  dev/preview/previewctl/pkg/ssh/mock.go
  dev/preview/previewctl/pkg/ssh/ssh.go
Labels: size/XXL, release-note-none, team: devx

#14329 [dashboard] Use public-api to JoinTeam
  components/dashboard/src/App.tsx
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/teams/JoinTeam.tsx
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/M, release-note-none

#14395 [public-api] Cleanup Workspace Service tests
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#14396 [previewctl] fix branch flag and rename structs
  dev/preview/previewctl/cmd/get_name.go
  dev/preview/previewctl/cmd/install_context.go
  dev/preview/previewctl/cmd/list_previews.go
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/cmd/ssh_vm.go
  dev/preview/previewctl/pkg/preview/preview.go
Labels: size/L, release-note-none, team: devx

#14242 Test dotfile support
  test/tests/components/ws-manager/dotfiles_test.go
Labels: size/L, team: workspace, release-note-none

#14397 Use proper variable interpolation in Leeway script
  components/BUILD.yaml
Labels: size/XS, release-note-none, team: devx

#14372 [dashboard] Fetch team members using public API
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/teams/Members.tsx
Labels: size/M, team: webapp, release-note-none

#14400 Add Website Slug for CDE
  components/dashboard/src/App.tsx
Labels: size/XS, team: webapp, release-note-none

#14402 [public-api] Fix request started metric reporting
  components/public-api-server/pkg/server/metrics.go
Labels: size/XS, team: webapp, release-note-none

#14404 [code] Point back to main
  .github/workflows/code-nightly.yml
Labels: size/XS, release-note-none

#14405 [observability] add max value for mem and cpu
  operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Labels: size/XS, team: IDE, release-note-none

#14407 [registry-facade] Add additional GetBlob error logs
  components/registry-facade/pkg/registry/blob.go
  components/registry-facade/pkg/registry/metrics.go
Labels: size/XS, team: workspace, release-note-none

#14414 Fix registry facade blobSource dashboard and add link
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/registry-facade-blobsource.json
Labels: size/S, team: workspace, release-note-none

#14417 obs: fix new workspace does not shown workspace success rate
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/XS, team: workspace, release-note-none

#14415 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14390 [GitHub Action] Use Large VM for Preview Environments related to JetBrains IDEs
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14398 [public-api] Proxy Cookies to downstream for auth
  components/public-api-server/pkg/auth/context.go
  components/public-api-server/pkg/auth/context_test.go
  components/public-api-server/pkg/auth/middleware.go
  components/public-api-server/pkg/auth/middleware_test.go
  components/public-api-server/pkg/proxy/conn.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
Labels: size/L, team: webapp, release-note-none

#14403 [dashboard] Authenticate with Public API using Cookies instead of Tokens
  components/dashboard/src/service/public-api.ts
Labels: size/M, team: webapp, release-note-none

#14411 [public-api] Implement UpdateTeamMember and DeleteTeamMember
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
Labels: size/L, team: webapp, release-note-none

#14422 [public-api] Parametrize connection URL based on token
  components/public-api-server/pkg/proxy/conn.go
  components/public-api-server/pkg/proxy/conn_test.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
Labels: size/M, team: webapp, release-note-none

#14388 [preview] Add support for new `with-slow-database` annotation
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, release-note-none

#14412 [dashboard] Use Public API to UpdateTeamMember and DeleteTeamMember
  components/dashboard/src/teams/Members.tsx
Labels: size/S, team: webapp, release-note-none

#14428 [code] update startup.sh to replace temporary variables
  components/ide/code/startup.sh
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/XS, team: IDE, release-note-none

#14432 [kots] merge custom docker config correctly
  install/installer/scripts/kots-install.sh
Labels: size/XS, release-note, team: delivery-operations-experience

#14423 [installer] Add a toxiproxy deployment behind the experimental `slowDatabase` flag.
  install/installer/pkg/components/toxiproxy/constants.go
  install/installer/pkg/components/toxiproxy/deployment.go
  install/installer/pkg/components/toxiproxy/objects.go
  install/installer/pkg/components/toxiproxy/objects_test.go
Labels: size/L, team: webapp, release-note-none, team: devx

#14435 [JetBrains] Update Gradle to the same version used in other components (v7.3.1)
  dev/jetbrains-test/gradle/wrapper/gradle-wrapper.properties
Labels: team: IDE, release-note-none

#14430 [installer] Add a toxiproxy service behind the experimental `slowDatabase` flag
  install/installer/pkg/components/toxiproxy/constants.go
  install/installer/pkg/components/toxiproxy/deployment.go
  install/installer/pkg/components/toxiproxy/objects.go
  install/installer/pkg/components/toxiproxy/objects_test.go
  install/installer/pkg/components/toxiproxy/service.go
Labels: size/M, team: webapp, release-note-none

#13590 Pagination design fixes
  components/dashboard/src/Pagination/Pagination.tsx
  components/dashboard/src/Pagination/PaginationNavigationButton.tsx
Labels: community-contribution, size/M, release-note, cla: accepted :heavy_check_mark:

#14442 [workspace] Don't run tests when using debug.sh
  scripts/ws-deploy.sh
Labels: size/XS, team: workspace, release-note-none

#14445 [loadgen] Move workspace stress repository
  dev/loadgen/configs/prod-benchmark-pvc.yaml
  dev/loadgen/configs/prod-benchmark.yaml
  dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml
  dev/loadgen/configs/workspace-preview-benchmark.yaml
Labels: size/XS, team: workspace, release-note-none

#14302 [registry-facade] Remove redis sentinel and add TLS support
  components/registry-facade-api/go/config/config.go
  components/registry-facade/pkg/registry/registry.go
  install/installer/pkg/components/registry-facade/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: workspace, release-note-none, team: delivery-operations-experience

#14420 test: check the /workspace UID:GID is gitpod:gitpod
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/M, team: workspace, release-note-none

#14460 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14421 [gitlab/webhook] return code 200 on Unauthorized
  components/server/ee/src/prebuilds/gitlab-app.ts
Labels: size/S, team: webapp, release-note

#14394 [JetBrains] Improve code readability
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#14470 [openvsx-mirror] add incoming requests monitoring
  operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Labels: size/XXL, team: IDE, release-note-none

#14466 [public-api] Handle blocked user error
  components/public-api-server/pkg/proxy/errors.go
  components/public-api-server/pkg/proxy/errors_test.go
Labels: size/XS, team: webapp, release-note-none

#14490 [public-api] Properly extract errors from Websocket RPC
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/proxy/errors.go
  components/public-api-server/pkg/proxy/errors_test.go
Labels: size/L, team: webapp, release-note-none

#14492 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14452 [JetBrains] Upgrade Gradle Wrapper to v7.5.1 in all components
  components/gitpod-protocol/java/gradle/wrapper/gradle-wrapper.jar
  components/gitpod-protocol/java/gradle/wrapper/gradle-wrapper.properties
  components/gitpod-protocol/java/gradlew
  components/gitpod-protocol/java/gradlew.bat
  components/ide-metrics-api/java/gradle/wrapper/gradle-wrapper.jar
  components/ide-metrics-api/java/gradle/wrapper/gradle-wrapper.properties
  components/ide-metrics-api/java/gradlew
  components/ide-metrics-api/java/gradlew.bat
  components/ide/jetbrains/backend-plugin/gradle/wrapper/gradle-wrapper.jar
  components/ide/jetbrains/backend-plugin/gradle/wrapper/gradle-wrapper.properties
  components/ide/jetbrains/backend-plugin/gradlew
  components/ide/jetbrains/backend-plugin/gradlew.bat
  components/ide/jetbrains/gateway-plugin/gradle/wrapper/gradle-wrapper.jar
  components/ide/jetbrains/gateway-plugin/gradle/wrapper/gradle-wrapper.properties
  components/ide/jetbrains/gateway-plugin/gradlew
  components/ide/jetbrains/gateway-plugin/gradlew.bat
  components/supervisor-api/java/gradle/wrapper/gradle-wrapper.jar
  components/supervisor-api/java/gradle/wrapper/gradle-wrapper.properties
  components/supervisor-api/java/gradlew
  components/supervisor-api/java/gradlew.bat
  dev/jetbrains-test/gradle/wrapper/gradle-wrapper.jar
  dev/jetbrains-test/gradle/wrapper/gradle-wrapper.properties
  dev/jetbrains-test/gradlew
  dev/jetbrains-test/gradlew.bat
Labels: size/L, team: IDE, release-note-none, editor: jetbrains

#14514 fix admin search
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
Labels: size/M, team: webapp, release-note-none

#14511 [werft] Update previews to use analytics token from secret
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, release-note-none, team: devx

#14517 Remove legacy branch-namespace script
  .gitpod.yml
  scripts/branch-namespace.sh
Labels: size/S, release-note-none, team: devx

#14519 [ci] Fix werft job definition
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none

#14393 Remove download workspace button from admin
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: size/M, team: webapp, release-note

#14540 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14534 [Integration Tests] Allow running specific IDE suite
  .github/pull_request_template.md
  .werft/ide-integration-tests-startup.sh
  .werft/jobs/build/job-config.ts
  test/run.sh
Labels: size/M, team: IDE, release-note-none

#14537 [dashboard] Handle create team errors from Public API better
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/S, team: webapp, release-note-none

#14522 [server] Remove download workspace APIs
  components/server/src/container-module.ts
  components/server/src/server.ts
  components/server/src/storage/content-service-client.ts
  components/server/src/storage/storage-client.ts
  components/server/src/workspace/workspace-download-service.ts
Labels: size/L, team: webapp, release-note-none

#14527 [JetBrains EAP] Auto-approve PRs created for updating Backend Plugin's SDK
  .github/CODEOWNERS
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: IDE, release-note-none

#14539 [installer-tests] Fail cleanup job when any environment cleanup fails
  install/tests/cleanup.sh
Labels: size/XS, release-note-none, team: delivery-operations-experience

#14399 Introduce a single Leeway entrypoint script
  dev/BUILD.yaml
  dev/preview/BUILD.yaml
Labels: size/XS, release-note-none, team: devx

#14544 [JetBrains] Run jetbrains integration tests when creating automated PR for JB updates
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14548 Move previewctl install-context to `leeway run dev:preview`
  dev/BUILD.yaml
  dev/preview/BUILD.yaml
Labels: size/XS, release-note-none, team: devx

#14525 [observability] add threads and latency charts
  operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Labels: size/XL, team: IDE, release-note-none

#14546 [server] Break dependency of content-service on gitpod-protocol, and usage-api on gitpod-protocol
  components/content-service-api/typescript/BUILD.yaml
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/BUILD.yaml
  components/server/src/code-sync/code-sync-service.ts
  components/server/src/container-module.ts
  components/server/src/storage/content-service-client.ts
  components/server/src/util/content-service-sugar.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-service.ts
  components/usage-api/typescript/BUILD.yaml
Labels: size/M, team: webapp, team: workspace, release-note-none

#14521 [proxy] Remove workspace download plugin
  components/proxy/Dockerfile
  components/proxy/conf/Caddyfile
  components/proxy/plugins/workspacedownload/go.mod
  components/proxy/plugins/workspacedownload/go.sum
  components/proxy/plugins/workspacedownload/workspace_download.go
Labels: size/XL, team: webapp, release-note-none

#14526 [content-service] Remove GetWorkspaceDownloadURL
  components/content-service-api/go/workspace.pb.go
  components/content-service-api/go/workspace_grpc.pb.go
  components/content-service-api/typescript/src/workspace_grpc_pb.d.ts
  components/content-service-api/typescript/src/workspace_grpc_pb.js
  components/content-service-api/typescript/src/workspace_pb.d.ts
  components/content-service-api/workspace.proto
  components/content-service/pkg/service/workspace-service.go
  components/gitpod-protocol/src/wsready.ts
Labels: size/M, team: webapp, team: workspace, release-note-none

#14555 [public-api] Parse TeamID as UUID for extra validation
  components/public-api-server/pkg/apiv1/team.go
Labels: size/S, team: webapp, release-note-none

#14401 [supervisor] disable analyze in headless workspace
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/S, team: IDE, release-note-none

#14553 [openvsx-proxy] switch to debug instead of info
  components/openvsx-proxy/pkg/errorhandler.go
  components/openvsx-proxy/pkg/handler.go
  components/openvsx-proxy/pkg/modifyresponse.go
  components/openvsx-proxy/pkg/prometheus.go
Labels: size/S, team: IDE, release-note-none

#14538 [installer] Deploy Public API without experimental config
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
  install/installer/pkg/components/public-api-server/networkpolicy_test.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/components/public-api-server/objects_test.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp, release-note, team: devx, team: delivery-operations-experience

#14559 [server] Remove userId from deleteTeam() rpc
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#14564 Fix syntax errors
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: workspace, release-note-none

#14503 [server] snapshots for PVC workspaces
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/ee/src/workspace/snapshot-service.ts
  components/ws-manager-api/go/mock/mock.go
  components/ws-manager-api/typescript/src/core_grpc_pb.d.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.js
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-api/typescript/src/promisified-client.ts
Labels: size/L, do-not-merge/hold, team: webapp, release-note-none

#14550 [JetBrains] Add GitHub tokens for automatically creating, asking for reviews, and approving PRs
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-update-plugin-platform.yml
Labels: size/S, team: IDE, release-note-none

#14565 [image-builder] Increment metric on build completions
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Labels: size/XS, team: workspace, release-note-none

#14071 [ssh-proxy] only send heartbeat for pty sessions
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager/pkg/manager/manager.go
  components/ws-proxy/pkg/sshproxy/forward.go
  components/ws-proxy/pkg/sshproxy/heartbeat.go
  components/ws-proxy/pkg/sshproxy/server.go
Labels: size/S, team: workspace, release-note

#14570 [pvc] set FSGroupChangePolicy
  components/ws-manager/pkg/manager/create.go
Labels: size/XS, team: workspace, release-note-none

#14575 Update code insiders to 1.73.1
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, release-note-none

#14512 Fix workspace alerts path
  .werft/observability/manifests/monitoring-satellite.yaml
Labels: size/XS, release-note-none, team: delivery-operations-experience

#14572 [public-api] Cleanup connection retrieval to reduce duplication
  components/public-api-server/pkg/apiv1/team.go
Labels: size/M, team: webapp, release-note-none

#14578 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14571 [server] Remove deprecatedDoWatchWorkspaceImageBuildLogs() - unused
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#14535 [server] Allow setting ws-class on project level
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/settings/selectClass.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/ee/src/workspace/workspace-starter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-classes.ts
  components/server/src/workspace/workspace-starter.spec.ts
  components/server/src/workspace/workspace-starter.ts
Labels: needs visual design, size/L, team: webapp, release-note

#14558 [public-api] Define TeamsService.DeleteTeam RPC
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/go/experimental/v1/teams_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/teams.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#13620 [code] sync profiles/collections
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-collection.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-resource.ts
  components/gitpod-db/src/typeorm/migration/1664913169612-CodeSyncCollectionDB.ts
  components/server/src/code-sync/code-sync-service.ts
Labels: editor: code (browser), meta: never-stale, size/XXL, release-note-none

#14523 [public api] Proto definitions for tokens
  .gitattributes
  components/public-api/gitpod/experimental/v1/tokens.proto
  components/public-api/go/experimental/v1/tokens.pb.go
  components/public-api/go/experimental/v1/tokens_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/tokens.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_pb.ts
Labels: size/XL, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14574 [dashboard] Use PublicAPI to DeleteTeam
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/XS, team: webapp, release-note-none

#14586 Fix conflicting PrometheusRules
  operations/observability/mixins/meta/rules/public-api.yaml
Labels: size/XS, team: webapp, release-note-none

#14577 Update stable to `1.73.1`
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#14584 [JetBrains] Auto-approve also EAP Gateway Plugin updates
  .github/CODEOWNERS
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14589 [JetBrains] Add a step to check and approve the PR created for Gateway Plugin
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#14582 [JetBrains] Update Platform Version from JetBrains Gateway Plugin
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14515 [dashboard] usage view allows for flexible time range
  components/dashboard/package.json
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/components/react-datepicker.css
  yarn.lock
Labels: needs visual design, size/L, team: webapp, release-note

#14321 ws-manager: Monitor a event about deleting a pod
  components/ws-manager/cmd/run.go
  components/ws-manager/pkg/manager/pod_controller.go
Labels: size/S, team: webapp, team: workspace, release-note-none

#14593 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#14408 [JetBrains EAP] Port Forwarding improvements
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodPortForwardingService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodPortsService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodCopyUrlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodCopyWebUrlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodGlobalPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodGlobalPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/utils/LocalHostUri.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/backend-plugin/src/test/kotlin/io/gitpod/jetbrains/remote/util/LocalHostUriTest.kt
Labels: size/XXL, team: IDE, release-note-none, editor: jetbrains

#14599 [server] Don't count user errors in failed image builds metrics
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#14597 fix incremental workspaces
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#14587 [usage] Decrease Usage record create batch size
  components/usage/pkg/db/usage.go
Labels: size/XS, team: webapp, release-note-none

#14601 Building locally will produce a unique version every time
  dev/preview/workflow/preview/build.sh
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, release-note-none, team: devx

#14604 [public-api] Define ProjectsService
  components/public-api/gitpod/experimental/v1/pagination.proto
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/pagination.pb.go
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/go/experimental/v1/projects_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/projects.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/pagination_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
Labels: size/XL, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#14623 [JetBrains] Fix JDWP error triggered when running `launch-dev-server.sh`
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14627 [public api] Wire up UnimplementedTokensService
  components/public-api-server/pkg/apiv1/tokens.go
  components/public-api-server/pkg/server/server.go
Labels: size/S, release-note-none

#14608 [observability] add vscode install extension failure alert rule
  operations/observability/mixins/IDE/rules/vscode.yaml
Labels: size/S, team: IDE, release-note-none

#14628 [JetBains] Fix to continuously observe ports while Gitpod Port Forwarding Service is active
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
Labels: size/M, team: IDE, release-note-none, editor: jetbrains
