Repository gitpod-io/gitpod, pull requests merged in 2022-01, with the labels that each got.

#7394 Remove workspace deployment
  operations/workspace/deployment/.gitignore
  operations/workspace/deployment/BUILD.yaml
  operations/workspace/deployment/OWNERS
  operations/workspace/deployment/README.md
  operations/workspace/deployment/cmd/deploy.go
  operations/workspace/deployment/cmd/root.go
  operations/workspace/deployment/example-config.yaml
  operations/workspace/deployment/go.mod
  operations/workspace/deployment/go.sum
  operations/workspace/deployment/main.go
  operations/workspace/deployment/pkg/common/cluster.go
  operations/workspace/deployment/pkg/common/context.go
  operations/workspace/deployment/pkg/config/v1/config.go
  operations/workspace/deployment/pkg/orchestrate/deploy.go
  operations/workspace/deployment/pkg/runner/shellcommand.go
  operations/workspace/deployment/pkg/step/createcluster.go
  operations/workspace/deployment/pkg/step/installgitpod.go
Labels: approved, lgtm, size/XXL, team: workspace, release-note-none

#7414 [werft] Consider migrations delete successful
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#7395 Remove theia IDE
  .gitignore
  chart/templates/blobserve-configmap.yaml
  chart/templates/server-ide-configmap.yaml
  chart/values.yaml
  components/BUILD.yaml
  components/ide/theia/BUILD.yaml
  components/ide/theia/bin/code
  components/ide/theia/bin/open
  components/ide/theia/leeway.Dockerfile
  components/ide/theia/package-libs.sh
  components/ide/theia/startup.sh
  components/ide/theia/supervisor-config.json
  components/ide/theia/supervisor-ide-config.json
  dev/manual-tests/testsuite.yaml
  installer/pkg/components/server/ide/configmap.go
Labels: approved, size/L, lgtm, team: IDE, release-note

#7371 [server] set default branch for BitBucket provider
  components/server/src/bitbucket/bitbucket-repository-provider.ts
Labels: community-contribution, approved, lgtm, size/XS, team: meta, release-note, cla: accepted :heavy_check_mark:

#7420 [local-app] fix timeout chan no consumer
  components/local-app/pkg/bastion/bastion.go
Labels: community-contribution, approved, lgtm, size/XS, team: IDE, release-note-none, cla: accepted :heavy_check_mark:

#7364 [installer]: add example for post-processing the YAML
  installer/README.md
Labels: approved, lgtm, size/S, release-note, team: self-hosted

#7421 [server] dispose pingpong timer when ws is closing/closed
  components/server/src/express-util.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7429 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S, release-note-none

#7272 Install Gitpod in Harvester-based k3s cluster for preview environments (opt-in)
  .werft/build.ts
  .werft/build.yaml
  .werft/vm/manifests.ts
  .werft/vm/vm.ts
Labels: approved, size/L, lgtm, release-note-none

#7427 Update VM image
  .werft/vm/manifests.ts
Labels: approved, lgtm, size/XS, release-note-none

#7434 [db] DROPT TABLE d_b_payment_source_info
  components/gitpod-db/src/typeorm/migration/1641287965022-DropDBPaymentSourceInfo.ts
Labels: approved, lgtm, size/S, groundwork: in review, team: meta, release-note-none

#7392 [server] infer extensions and add a comment
  components/server/src/config/config-inferrer.spec.ts
  components/server/src/config/config-inferrer.ts
  components/server/src/config/configuration-service.ts
Labels: approved, size/L, lgtm, team: meta, release-note

#7275 Auto focus on cancel on confirmation modal
  components/dashboard/src/components/ConfirmationModal.tsx
Labels: user experience, component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#7437 Rename editor preference section heading
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/whatsnew/WhatsNew-2021-04.tsx
  components/server/src/ide-config.ts
  installer/pkg/components/server/ide/configmap.go
Labels: approved, lgtm, size/S, team: meta, team: IDE, release-note

#7449 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7320 Remove FORBIDDEN_SLUGS
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: community-contribution, meta: never-stale, approved, lgtm, size/M, team: meta, release-note-none, cla: accepted :heavy_check_mark:

#7444 Launch k3s on VM on Harvester
  .werft/vm/manifests.ts
  .werft/vm/vm.ts
Labels: approved, size/L, lgtm, release-note-none

#7388 Restore page bottom margin
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: user experience, component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#7451 Move .vscode-remote location to /workspace folder
  components/ide/code/startup.sh
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7314 [dashboard] enable UI experiments only for Gitpod SaaS
  components/dashboard/src/App.tsx
Labels: approved, lgtm, size/XS, groundwork: in review, team: meta, release-note-none

#7339 Make analytic event casing consistent
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: meta: never-stale, approved, lgtm, size/XS, team: meta, release-note-none

#7457 [ide] Update code stable image
  chart/values.yaml
  installer/pkg/components/workspace/ide/constants.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7464 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7337 Add dotfile repo support
  components/dashboard/src/settings/Preferences.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, size/L, lgtm, team: meta, team: IDE, release-note

#7465 [db] Remove dropped table d_b_payment_source_info from db-sync
  components/gitpod-db/src/tables.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7456 Add Harvester to workspace kubeconfig
  .gitpod.yml
  dev/preview/download-and-merge-harvester-kubeconfig.sh
Labels: approved, lgtm, size/M, release-note-none

#7494 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7493 Update dotfiles input help text design
  components/dashboard/src/settings/Preferences.tsx
Labels: user experience, component: dashboard, type: improvement, approved, lgtm, size/XS, team: meta, release-note-none

#7391 [server] use owner and repo name for workspace id
  components/gitpod-protocol/src/util/generate-workspace-id.spec.ts
  components/gitpod-protocol/src/util/generate-workspace-id.ts
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/gitpod-protocol/src/util/parse-workspace-id.ts
  components/local-app/main.go
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-factory.ts
  components/ws-proxy/pkg/proxy/workspacerouter.go
Labels: approved, lgtm, size/M, team: meta, team: workspace, team: IDE, release-note

#7480 Make certs for Gitpod installation on harvester available
  .werft/build.ts
Labels: approved, lgtm, size/S, release-note-none

#7463 Add git command analytics
  components/gitpod-cli/BUILD.yaml
  components/gitpod-cli/cmd/credential-helper.go
  components/gitpod-cli/cmd/git-track-command.go
  components/gitpod-cli/cmd/version.go
  components/gitpod-cli/pkg/gitpod/server.go
  components/gitpod-cli/pkg/gitpod/version.txt
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
Labels: approved, size/L, lgtm, team: meta, team: IDE, release-note

#7417 [supervisor] fix addgroup adduser command not pair
  components/supervisor/pkg/supervisor/user.go
Labels: community-contribution, approved, size/L, lgtm, team: IDE, release-note-none, cla: accepted :heavy_check_mark:

#7495 Truncate projects with long path
  components/dashboard/src/projects/Projects.tsx
Labels: user experience, component: dashboard, type: improvement, approved, lgtm, size/XS, team: meta, release-note-none

#7506 Add a deprecation notice to the Helm charts.
  chart/README.md
Labels: approved, lgtm, size/S, release-note-none

#7509 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7508 [installer]: use a pointer deref if the ssh gateway secret does not exist
  installer/pkg/components/ws-proxy/deployment.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7513 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7511 [installer] Adjust mysql helm chart probes configuration
  installer/pkg/components/database/incluster/helm.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7520 Fix telepresence for server
  components/server/src/config.ts
  installer/pkg/components/server/configmap.go
  installer/pkg/components/server/deployment.go
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7533 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7504 [server] remove GraphQL API
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/graphql/graphql-codegen.yml
  components/server/ee/src/graphql/graphql-controller.ts
  components/server/ee/src/graphql/graphql-gen.ts
  components/server/ee/src/graphql/graphql.schema.json
  components/server/ee/src/graphql/resolvers.ts
  components/server/ee/src/graphql/schema.graphql
  components/server/ee/src/server.ts
  components/server/package.json
  yarn.lock
Labels: approved, lgtm, size/XXL, team: meta, release-note

#7510 [installer] Adjust default MySQL value
  installer/pkg/components/database/incluster/configmap.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7502 [server] removed unused branding from config
  chart/templates/server-configmap.yaml
  chart/values.yaml
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/branding-parser.ts
  components/server/src/config.ts
  components/server/src/user/user-controller.ts
  components/server/src/workspace/gitpod-server-impl.ts
  installer/pkg/components/server/configmap.go
  installer/pkg/components/server/types.go
Labels: approved, lgtm, size/XL, team: meta, release-note-none

#7241 community: route users to Discord for support
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: meta: never-stale, approved, lgtm, size/XS, team: meta, release-note

#7528 werft/VM: Use different auth-provider secret for previews on Harvester VMs
  .werft/build.ts
  .werft/build.yaml
Labels: approved, lgtm, size/S, release-note-none

#7557 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7558 [code] Address insiders changes
  WORKSPACE.yaml
  components/ide/code/bin/code
  components/ide/code/bin/gp-code
  components/ide/code/bin/open
  components/ide/code/leeway.Dockerfile
  components/ide/code/startup.sh
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#7535 [server] allow prevent merge on failed prebuilds
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/prebuilds/github-app.ts
  components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
Labels: approved, lgtm, size/S, team: meta, release-note

#7560 Remove Integration button text changed
  components/dashboard/src/settings/Integrations.tsx
Labels: community-contribution, approved, lgtm, size/XS, team: meta, release-note-none, cla: pending :hourglass_flowing_sand:

#7580 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7577 removed proxy to access new preview-environment
  .werft/build.ts
  .werft/vm/vm.ts
Labels: approved, lgtm, size/S, release-note-none

#7578 Add bottom padding for projects, branches, and prebuilds
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
Labels: user experience, component: dashboard, approved, lgtm, size/XS, team: meta, release-note

#7148 Updated license summary for npm packages
  License.third-party.npm.txt
Labels: approved, lgtm, size/XXL, team: IDE, release-note-none

#7589 [prebuild-init] Prune while fetching
  components/content-service/pkg/git/git.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7588 Update Go Dependency List
  License.third-party.go.txt
  scripts/go-licenses.sh
Labels: approved, lgtm, size/XL, release-note-none

#7541 [observability] Create histogram for API method calls duration
  components/server/src/prometheus-metrics.ts
  components/server/src/websocket/websocket-connection-manager.ts
  operations/observability/mixins/meta/dashboards/components/server.json
Labels: approved, lgtm, size/XXL, team: meta, release-note-none

#7599 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7507 Remove Theia references from the CLI component
  components/gitpod-cli/cmd/credential-helper.go
  components/gitpod-cli/cmd/env.go
  components/gitpod-cli/cmd/preview.go
Labels: approved, size/L, lgtm, team: IDE, release-note-none

#7596 [installer] Adjust rabbitmq helm chart probes configuration
  installer/pkg/components/rabbitmq/helm.go
Labels: approved, lgtm, size/S, release-note, team: self-hosted

#7559 [code] Port telemetry to stable
  chart/values.yaml
  installer/pkg/components/workspace/ide/constants.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7606 [dashboard] single workspaces list
  components/dashboard/src/App.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/workspace-model.ts
Labels: approved, size/L, lgtm, team: meta, release-note

#7609 [protocol] use owner and repo in lower case in ws IDs
  components/gitpod-protocol/src/util/generate-workspace-id.spec.ts
  components/gitpod-protocol/src/util/generate-workspace-id.ts
Labels: approved, lgtm, size/XS, team: meta, release-note

#7616 Explicitly launch code server on 0.0.0.0
  WORKSPACE.yaml
  components/ide/code/startup.sh
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7618 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7621 fix #7054: fix disposing of listeners
  components/server/src/messaging/local-message-broker.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7622 Revert "[supervisor] Add log for exposed port instance update"
  components/supervisor/pkg/ports/exposed-ports.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7619 [supervisor] nicely handle OOM killed IDE processes
  components/ide/jetbrains/image/startup.sh
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7534 Don't try to connect to opened ports
  components/supervisor/pkg/ports/ports.go
  components/supervisor/pkg/ports/ports_test.go
  components/supervisor/pkg/ports/served-ports.go
  components/supervisor/pkg/ports/served-ports_test.go
Labels: approved, lgtm, size/XL, team: IDE, release-note-none

#7631 Fix exposed ports edge case
  components/supervisor/pkg/ports/ports.go
Labels: approved, lgtm, size/XS, team: IDE, release-note-none

#7594 werft/post-process: Configure different registry facade DNS for Harvester previews
  .werft/post-process.sh
Labels: approved, lgtm, size/XS, release-note-none

#7624 [dashboard] Fix broken client.dispose()
  components/gitpod-protocol/src/gitpod-service.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7633 Download instead of view account statement
  components/dashboard/src/admin/UserDetail.tsx
Labels: approved, lgtm, size/M, team: meta, release-note

#7637 [dashboard] Prevent adding 'gmail.com' as a verified student email domain
  components/dashboard/src/admin/UserDetail.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7652 Fix DB migration order
  components/gitpod-db/src/typeorm/migration/1642493449937-ProjectEnvVars.ts
Labels: approved, lgtm, do-not-merge/hold, size/XS, team: meta, release-note-none

#7651 Increase timeout of failing testIssue4045Minimal test
  components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7625 [installer] Fix mysql image pull policy
  installer/pkg/components/database/incluster/helm.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7614 added support for cleanSlateDeployment
  .werft/build.ts
  .werft/vm/vm.ts
Labels: approved, lgtm, size/M, release-note-none

#7659 [dashboard] Don't offer to add common email domains as a verified student domains in Admin
  components/dashboard/src/admin/UserDetail.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note

#7623 [installer] Fix ws-daemon image pull policy
  installer/pkg/components/ws-daemon/daemonset.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7661 [server] fix commit check
  components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
Labels: approved, lgtm, size/XS, team: meta, release-note

#7656 [installer] Fix lifecycle PostStart label update
  installer/pkg/components/registry-facade/daemonset.go
  installer/pkg/components/ws-daemon/daemonset.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7670 [installer] Fix registry-facade ClusterRoleBinding name
  installer/pkg/components/registry-facade/rolebinding.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7674 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7665 Web responsiveness
  components/dashboard/src/projects/ConfigureProject.tsx
  components/dashboard/src/projects/Projects.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7660 [installer] Switch default log level to info
  installer/cmd/mirror_list.go
  installer/cmd/validate-cluster.go
  installer/cmd/version.go
  installer/pkg/common/common.go
  installer/pkg/components/agent-smith/configmap.go
  installer/pkg/components/blobserve/configmap.go
  installer/pkg/components/content-service/configmap.go
  installer/pkg/components/database/incluster/secret.go
  installer/pkg/components/gitpod/configmap.go
  installer/pkg/components/image-builder-mk3/configmap.go
  installer/pkg/components/openvsx-proxy/configmap.go
  installer/pkg/components/registry-facade/configmap.go
  installer/pkg/components/server/configmap.go
  installer/pkg/components/server/deployment.go
  installer/pkg/components/server/ide/configmap.go
  installer/pkg/components/ws-daemon/configmap.go
  installer/pkg/components/ws-manager-bridge/configmap.go
  installer/pkg/components/ws-manager/configmap.go
  installer/pkg/components/ws-proxy/configmap.go
  installer/pkg/components/ws-scheduler/configmap.go
Labels: approved, lgtm, size/M, team: meta, team: workspace, team: IDE, release-note, team: self-hosted

#7687 [installer] Telemetry should not run in workspace clusters
  installer/pkg/components/gitpod/cronjob.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7667 Fixing a broken link / typo in installer's readme
  installer/README.md
Labels: community-contribution, approved, lgtm, size/XS, release-note-none, team: self-hosted

#7693 Update Team Workspace aliases
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none

#7701 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7682 Update workspace success criteria
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7697 did not receive seccomp fd from ring2
  components/workspacekit/cmd/rings.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7705 docker-up: drop the `kernel.domainname` as rootless container currently fail
  components/docker-up/runc-facade/main.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7703 Use new code server arg --server-data-dir
  WORKSPACE.yaml
  components/ide/code/startup.sh
  components/ide/code/supervisor-ide-config.json
  components/supervisor/pkg/supervisor/supervisor.go
Labels: approved, lgtm, size/S, team: IDE, release-note-none

#7725 Ignore broken config validation
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#7739 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7740 Use space character instead of u+00a0
  CHANGELOG.md
  License.third-party.npm.txt
  components/dashboard/src/components/ConfirmationModal.tsx
  components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts
  components/ee/payment-endpoint/src/accounting/subscription-service.spec.db.ts
  components/gitpod-protocol/src/ide-frontend-service.ts
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/server/ee/src/user/user-deletion-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/git-token-scope-guesser.ts
  components/server/src/workspace/workspace-starter.ts
Labels: approved, lgtm, size/M, team: meta, release-note-none

#7738 Fix incorrect type in GithubAppPrebuildConfig
  components/gitpod-protocol/go/gitpod-service.go
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7653 [dashboard] update preferences page for desktop IDE's
  components/dashboard/src/icons/IDENone.svg
  components/dashboard/src/icons/IDENoneDark.svg
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, size/L, lgtm, team: meta, release-note-none

#7730 [installation-telemetry]: log data sent to Segment
  components/installation-telemetry/cmd/send.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7735 credential-helper: validate parsed git command data
  components/gitpod-cli/cmd/credential-helper.go
Labels: approved, lgtm, size/M, team: IDE, release-note-none

#7749 [content-init] Ensure .gitpod path is available
  components/content-service/pkg/git/git.go
  components/content-service/pkg/initializer/initializer.go
  components/ws-daemon/pkg/content/initializer.go
Labels: approved, lgtm, size/M, team: workspace, release-note-none

#7753 [content-init] Propagate sensible error messages
  components/content-service/pkg/initializer/initializer.go
  components/ws-daemon/cmd/content-initializer/main.go
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/content/service.go
Labels: approved, lgtm, size/M, team: workspace, release-note

#7710 Trigger node high load warnings sooner
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7763 Trigger node high load warnings sooner
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7765 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7775 Restore beta label for the desktop editor settings
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/XS, team: meta, release-note-none

#7777 credentialHelper minor refactor
  components/gitpod-cli/cmd/credential-helper.go
Labels: approved, size/L, lgtm, team: IDE, release-note-none

#7755 added 3 new workspace nodepools for preview-environments
  .werft/build.ts
  .werft/values.nodeAffinities_3.yaml
  .werft/values.nodeAffinities_4.yaml
  .werft/values.nodeAffinities_5.yaml
Labels: approved, size/L, lgtm, release-note-none

#7302 [dashboard] show repo name when workspace creation fails
  components/dashboard/src/start/CreateWorkspace.tsx
Labels: community-contribution, approved, lgtm, size/M, team: meta, release-note, cla: accepted :heavy_check_mark:

#7752 [installer] Fix invalid tag name for image build template
  installer/pkg/config/v1/config.go
Labels: approved, lgtm, size/XS, release-note, team: self-hosted

#7790 ws-daemon: Name the magic exit code to make it common
  components/ws-daemon/cmd/content-initializer/main.go
  components/ws-daemon/pkg/content/exit-code.go
  components/ws-daemon/pkg/content/initializer.go
Labels: approved, lgtm, size/S, team: workspace, release-note-none

#7788 [owners] Update to reflect latest team changes
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none

#7581 Include in the README where to access the development environment when developing dashboards using gitpod
  components/dashboard/README.md
Labels: approved, lgtm, size/XS, team: webapp, release-note

#7582 Fix the `gitpod.yml` checker Action
  .github/workflows/check-gitpodyaml.yml
Labels: approved, lgtm, size/S, release-note-none

#7791 Switch to prometheus collectors package
  components/blobserve/cmd/run.go
  components/content-service/cmd/run.go
  components/openvsx-proxy/pkg/prometheus.go
  components/ws-daemon/cmd/run.go
Labels: approved, lgtm, size/S, team: workspace, team: IDE, release-note-none

#7767 add dockerfile for testing image builder
  test/tests/components/image-builder/test.Dockerfile
Labels: approved, lgtm, size/XS, release-note-none

#7804 [prebuilds] no update status for pending prebuild
  components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
Labels: approved, lgtm, size/XS, team: webapp, release-note-none

#7802 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7808 [server] Fix case where we might close ws connections too frequently
  components/server/src/express/ws-connection-handler.ts
Labels: approved, lgtm, size/M, release-note-none

#7810 Ignore missing data-mysql-0 pvc during uninstall
  .werft/util/uninstall-gitpod.sh
Labels: approved, lgtm, size/XS, release-note-none

#7811 [team-sub] fix wording on add members
  components/dashboard/src/settings/Teams.tsx
Labels: approved, lgtm, size/XS, release-note-none

#7813 [helm] registry-facade, ws-daemon: Add postStart and preStop lifecycl…
  chart/templates/registry-facade-clusterrole.yaml
  chart/templates/registry-facade-daemonset.yaml
  chart/templates/registry-facade-rolebinding.yaml
  chart/templates/ws-daemon-daemonset.yaml
  chart/templates/ws-daemon-rolebinding.yaml
Labels: approved, lgtm, size/M, release-note-none

#7769 [installer] Add missing kube-rbac-proxy container in ws-manager deployment
  installer/pkg/components/ws-manager/deployment.go
Labels: approved, lgtm, size/XS, team: workspace, release-note

#7828 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7817 [owners] rename team meta to webapp
  OWNERS
  OWNERS_ALIASES
  components/content-service-api/OWNERS
  components/dashboard/OWNERS
  components/ee/db-sync/OWNERS
  components/ee/kedge/OWNERS
  components/ee/payment-endpoint/OWNERS
  components/gitpod-db/OWNERS
  components/gitpod-messagebus/OWNERS
  components/gitpod-protocol/OWNERS
  components/image-builder-api/OWNERS
  components/licensor/OWNERS
  components/local-app-api/OWNERS
  components/proxy/OWNERS
  components/registry-facade-api/OWNERS
  components/server/OWNERS
  components/service-waiter/OWNERS
  components/supervisor-api/OWNERS
  components/ws-daemon-api/OWNERS
  components/ws-manager-api/OWNERS
  components/ws-manager-bridge-api/OWNERS
  components/ws-manager-bridge/OWNERS
  installer/pkg/components/dashboard/OWNERS
  installer/pkg/components/proxy/OWNERS
  installer/pkg/components/server/OWNERS
  installer/pkg/components/ws-manager-bridge/OWNERS
  installer/pkg/config/versions/OWNERS
  operations/observability/mixins/meta/OWNERS
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note-none, team: self-hosted

#7834 Update WebApp team label in component owners
  components/dashboard/OWNERS
  components/ee/db-sync/OWNERS
  components/ee/kedge/OWNERS
  components/ee/payment-endpoint/OWNERS
  components/gitpod-db/OWNERS
  components/gitpod-protocol/OWNERS
  components/licensor/OWNERS
  components/proxy/OWNERS
  components/server/OWNERS
  components/service-waiter/OWNERS
  components/ws-manager-bridge/OWNERS
  installer/pkg/components/dashboard/OWNERS
  installer/pkg/components/proxy/OWNERS
  installer/pkg/components/server/OWNERS
  installer/pkg/components/ws-manager-bridge/OWNERS
  installer/pkg/config/versions/OWNERS
  operations/observability/mixins/meta/OWNERS
Labels: approved, lgtm, size/M, team: workspace, team: IDE, release-note-none, team: self-hosted

#7837 [server] allow having +1 active tokens
  components/gitpod-db/src/typeorm/user-db-impl.ts
Labels: approved, lgtm, size/XS, team: webapp, release-note

#7732 [Dashboard]: add send telemetry to admin settings
  components/dashboard/src/App.tsx
  components/dashboard/src/admin-context.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/admin-menu.ts
  components/dashboard/src/index.tsx
  components/gitpod-db/src/installation-admin-db.ts
  components/gitpod-db/src/typeorm/installation-admin-db-impl.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/installation-admin-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: approved, size/L, lgtm, team: webapp, release-note, team: self-hosted

#7840 Update leeway user commands to get DB credentials
  components/BUILD.yaml
Labels: approved, lgtm, size/S, release-note-none

#7818 Don't deploy Jaeger with preview environments
  .werft/build.ts
  .werft/jaeger.yaml
  .werft/util/kubectl.ts
Labels: approved, lgtm, size/M, release-note-none

#7841 Log correct fs
  components/ws-daemon/pkg/iws/iws.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7857 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7842 Limit desktop editor options width on large viewports
  components/dashboard/src/settings/Preferences.tsx
Labels: approved, lgtm, size/XS, team: webapp, release-note-none

#7851 [installer] add an experimental config section
  installer/cmd/render.go
  installer/pkg/common/render.go
  installer/pkg/common/storage.go
  installer/pkg/config/v1/config.go
  installer/pkg/config/v1/experimental/experimental.go
Labels: approved, lgtm, size/M, release-note-none, team: self-hosted

#7870 [content-initializer] Force local tags when fetching
  components/content-service/pkg/git/git.go
Labels: approved, lgtm, size/XS, team: workspace, release-note-none

#7867 Update base image for dev env and dev-env tag
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
Labels: approved, lgtm, size/S, release-note-none

#7887 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7896 [ci] notify ide-jobs slack channel
  .github/workflows/code-nightly.yaml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-auto-update.yml
  .github/workflows/jetbrains-updates-template.yml
  .github/workflows/jetbrains-updates.yml
Labels: approved, lgtm, size/M, release-note-none

#7907 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XS, release-note-none

#7869 Move local companions behind ide proxy
  components/dashboard/BUILD.yaml
  components/dashboard/conf/Caddyfile
  components/dashboard/leeway.Dockerfile
  components/ide-proxy/BUILD.yaml
  components/ide-proxy/Dockerfile
  components/ide-proxy/conf/Caddyfile
  components/proxy/conf/Caddyfile
Labels: approved, lgtm, size/M, team: webapp, team: IDE, release-note-none

#7905 add metric to track failed manifest requests from registry-facade
  components/registry-facade/pkg/registry/metrics.go
  operations/observability/mixins/workspace/dashboards/components/registry-facade.json
Labels: approved, lgtm, size/XXL, team: workspace, release-note

#7758 Update dev installation root URL
  .werft/build.ts
Labels: approved, lgtm, size/XS, release-note-none

#7805 [server] Ensure incremental prebuilds always use the latest config
  components/server/ee/src/workspace/workspace-factory.ts
Labels: approved, lgtm, size/XS, release-note

#7924 Fix server dashboard default time range
  operations/observability/mixins/meta/dashboards/components/server.json
Labels: approved, lgtm, size/S, team: webapp, release-note-none

#7921 [docker-up] Remove slirp4netns
  components/docker-up/BUILD.yaml
  components/docker-up/dependencies.sh
  components/docker-up/docker-up/main.go
  components/docker-up/slirp-docker-proxy/main.go
Labels: approved, lgtm, size/XL, team: workspace, release-note-none

#7928 add sagor999 to workspace team
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, release-note-none
