Repository gitpod-io/gitpod, pull requests merged in 2022-12, with the labels that each got.

#15085 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15089 fix path to prettier config
  gitpod-ws.code-workspace
Labels: size/XS, release-note-none

#15042 [server] Validate PAT signature
  components/server/src/auth/bearer-authenticator.ts
  components/server/src/config.ts
Labels: size/M, team: webapp, release-note-none, team: devx

#15087 ws-daemon: Enhause the traces for DisposeWorkspace
  components/ws-daemon/pkg/content/service.go
Labels: size/XS, team: workspace, release-note-none

#15093 [pat] Apply on-update property to _lastModified column, remove from expirationTime
  components/gitpod-db/src/typeorm/migration/1669888999897-PersonalAccessTokenFixLastModifiedAutoUpdate.ts
Labels: size/S, team: webapp, release-note-none

#15004 [IAM] add component skeleton
  components/BUILD.yaml
  components/iam/BUILD.yaml
  components/iam/README.md
  components/iam/cmd/root.go
  components/iam/cmd/run.go
  components/iam/config.json
  components/iam/go.mod
  components/iam/go.sum
  components/iam/leeway.Dockerfile
  components/iam/main.go
  components/iam/pkg/config/config.go
  components/iam/pkg/server/server.go
  gitpod-ws.code-workspace
  install/installer/BUILD.yaml
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/versions.yaml
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/iam/configmap.go
  install/installer/pkg/components/iam/constants.go
  install/installer/pkg/components/iam/deployment.go
  install/installer/pkg/components/iam/objects.go
  install/installer/pkg/components/iam/rolebinding.go
  install/installer/pkg/components/iam/service.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/versions/versions.go
Labels: size/XXL, team: webapp, team: IDE, release-note-none, team: delivery-operations-experience

#15090 [server] remove pvc related code
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-volume-snapshot.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/garbage-collector.ts
  components/server/src/workspace/workspace-deletion-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: size/XL, team: webapp, release-note-none

#15015 [pat] Token UI polish
  components/dashboard/src/components/Loader.tsx
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/settings/PersonalAccessTokens.tsx
  components/dashboard/src/settings/TokenEntry.tsx
Labels: size/XXL, team: webapp, release-note-none

#15097 [pat] Fix expiration time auto-udpate
  components/gitpod-db/src/typeorm/migration/1669892320740-PersonalAccessTokenFixExpirationTimeAutoUpdate.ts
Labels: size/S, team: webapp, release-note-none

#15107 Update spacing in token regeneration modal
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/XS, team: webapp, release-note

#15078 [proxy] Pre-flight server authentication related endpoints to add additional latency
  components/proxy/conf/Caddyfile
Labels: size/S, team: webapp, release-note-none

#15079 [proxy] Extract common request matchers to a snippet
  components/proxy/conf/Caddyfile
Labels: size/M, team: webapp, release-note-none

#15109 [go] clean up gen of go types
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/go/scripts/generate-config.sh
Labels: size/XXL, team: webapp, team: IDE, release-note-none

#15108 [pat] API allows update which does not change any data
  components/gitpod-db/go/personal_access_token.go
  components/gitpod-db/go/personal_access_token_test.go
  components/public-api-server/pkg/apiv1/tokens_test.go
Labels: size/M, team: webapp, release-note-none

#15091 [server] simplify workspace classes
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/service/service-mock.ts
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/settings/selectClass.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/gitpod-protocol/src/workspace-class.ts
  components/server/src/config.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-classes.spec.ts
  components/server/src/workspace/workspace-classes.ts
  components/server/src/workspace/workspace-starter.spec.ts
  components/server/src/workspace/workspace-starter.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/slowserver/configmap.go
Labels: size/XXL, team: webapp, release-note-none, team: devx

#15096 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#14869 Drop unused ArgoCD Metrics
  operations/observability/mixins/self-hosted/rules/argocd/servicemonitor.yaml
Labels: size/S, release-note-none, team: delivery-operations-experience

#15117 [usage] remove dependency on workspace class name
  components/usage/pkg/apiv1/pricer.go
  components/usage/pkg/apiv1/pricer_test.go
Labels: size/S, team: webapp, release-note-none

#15115 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15119 [pat] Change title from Personal Access Tokens to Access Tokens
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/M, team: webapp, release-note-none

#15122 Update access token scope name
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/XS, team: webapp, release-note-none

#15031 [JetBrains] Fail build on error
  components/ide/jetbrains/backend-plugin/build.sh
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15094 singleton SupervisorServiceClient
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
  components/supervisor/frontend/src/index.ts
Labels: size/L, team: IDE, release-note-none

#14883 [JetBrains] Refresh files before updating Maven projects
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/optional/GitpodForceUpdateMavenProjectsActivity.kt
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#15124 [dashboard] remove admin alter OSS plan
  components/dashboard/src/admin/UserDetail.tsx
Labels: size/S, team: webapp, release-note-none

#15082 Label JetBrains IDE images with their versions
  .github/workflows/jetbrains-auto-update-template.yml
  WORKSPACE.yaml
  components/ide/jetbrains/image/BUILD.js
  components/ide/jetbrains/image/leeway.Dockerfile
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#15081 Add IDE versions to ide service
  components/ide-service-api/go/config/ideconfig.go
  components/ide-service/go.mod
  components/ide-service/pkg/ocitool/resolve.go
  components/ide-service/pkg/ocitool/resolve_test.go
  components/ide-service/pkg/server/ideconfig.go
Labels: size/L, team: IDE, release-note-none

#15133 Update VS Code's icon
  components/ide-proxy/static/image/ide-logo/vscode.svg
Labels: type: bug, size/M, team: IDE, release-note-none

#15136 [installer] Don't mount ws-manager-client-tls in meta/webapp deployments
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/slowserver/deployment.go
  install/installer/pkg/components/ws-manager-bridge/configmap.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager-bridge/objects.go
  install/installer/pkg/components/ws-manager-bridge/objects_test.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XL, team: webapp, team: workspace, release-note-none

#15141 Fix grammar in PersonalAccessTokens.tsx
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/XS, team: webapp, release-note-none

#14918 [installer] manually set `allowPrivilegeEscalation` to false
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/common.go
  install/installer/pkg/components/dashboard/deployment.go
  install/installer/pkg/components/database/cloudsql/deployment.go
  install/installer/pkg/components/database/init/job.go
  install/installer/pkg/components/gitpod/cronjob.go
  install/installer/pkg/components/ide-metrics/deployment.go
  install/installer/pkg/components/ide-proxy/deployment.go
  install/installer/pkg/components/ide-service/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/migrations/job.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/slowserver/deployment.go
  install/installer/pkg/components/toxiproxy/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note, team: delivery-operations-experience

#15145 [usage] support multiple entries on invoices
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
Labels: size/XL, team: webapp, release-note-none

#15149 [iam] Add proto definitions for OIDC provider config
  components/public-api/gitpod/experimental/v1/oidc.proto
  components/public-api/go/experimental/v1/oidc.pb.go
  components/public-api/go/experimental/v1/oidc_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/oidc.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
Labels: size/XL, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#15163 [iam] clean up oidc.proto
  components/public-api/gitpod/experimental/v1/oidc.proto
  components/public-api/go/experimental/v1/oidc.pb.go
  components/public-api/go/experimental/v1/oidc_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/oidc.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#15168 [server] remove ssh functions scopes for workspace
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#15170 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15172 [usage] increment cycle on finalize invoice
  components/gitpod-db/go/cost_center.go
  components/usage/pkg/apiv1/billing.go
Labels: size/M, team: webapp, release-note-none

#15174 [dashboard] update description
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/XS, team: webapp, release-note-none

#15159 [ubp] allow usage of team without stripe sub
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/server/src/user/user-service.ts
Labels: size/S, team: webapp, release-note-none

#15177 [server] IAM: Report missing session info as client error
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/prometheus-metrics.ts
Labels: size/S, team: webapp, release-note-none

#15178 [ide-service] Move to ide-service jetbrains warmup logic
  components/ide-service/BUILD.yaml
  components/ide-service/pkg/server/server.go
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_multiple_ide.golden
Labels: size/S, team: IDE, release-note-none

#15179 dev/preview:configure-workspace fix
  .gitpod.yml
  dev/preview/workflow/preview/configure-workspace.sh
Labels: size/S, release-note-none, team: devx

#15185 [observability] Add IDE Service Dashboard
  operations/observability/mixins/IDE/dashboards.libsonnet
  operations/observability/mixins/IDE/dashboards/components/ide-service.json
Labels: size/XXL, team: IDE, release-note-none

#15180 [pat] Paginate list tokens view
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/S, team: webapp, release-note-none

#15164 Point code nightly worklow to the release branch
  .github/workflows/code-nightly.yml
Labels: size/XS, release-note-none

#15192 [server] Move admin endpoints on GitpodServer to AdminServer
  components/gitpod-protocol/src/admin-protocol.ts
  components/gitpod-protocol/src/gitpod-service.ts
Labels: size/S, release-note-none

#15167 Increase scrape interval to decrease datapoints per minute
  operations/observability/mixins/self-hosted/rules/argocd/servicemonitor.yaml
  operations/observability/mixins/self-hosted/rules/pyrra/servicemonitor.yaml
Labels: size/XS, release-note-none, team: delivery-operations-experience

#15191 [usage] handle no stopping but stopped time
  components/gitpod-db/go/workspace_instance.go
  components/usage/pkg/apiv1/pricer_test.go
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
Labels: size/M, release-note-none

#15129 [previewctl] move code around and simplify install context
  .werft/ide-integration-tests-startup.sh
  .werft/workspace-run-integration-tests.sh
  dev/preview/previewctl/cmd/access.go
  dev/preview/previewctl/cmd/credentials.go
  dev/preview/previewctl/cmd/get.go
  dev/preview/previewctl/cmd/install_context.go
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/pkg/k8s/context/k3s/k3s.go
  dev/preview/previewctl/pkg/k8s/service.go
  dev/preview/previewctl/pkg/k8s/service_test.go
  dev/preview/previewctl/pkg/preview/context.go
  dev/preview/previewctl/pkg/preview/preview.go
  dev/preview/previewctl/pkg/preview/util.go
  dev/preview/previewctl/pkg/preview/util_test.go
  dev/preview/previewctl/pkg/util/git.go
  dev/preview/workflow/lib/ensure-gcloud-auth.sh
  dev/preview/workflow/preview/build.sh
  dev/preview/workflow/preview/configure-workspace.sh
  dev/preview/workflow/preview/preview.sh
Labels: size/XXL, team: workspace, team: IDE, release-note-none, team: devx

#15128 `previewctl list stale`
  dev/preview/previewctl/BUILD.yaml
  dev/preview/previewctl/cmd/access.go
  dev/preview/previewctl/cmd/get.go
  dev/preview/previewctl/cmd/get_name.go
  dev/preview/previewctl/cmd/list_previews.go
  dev/preview/previewctl/cmd/stale.go
  dev/preview/previewctl/cmd/workspaces.go
  dev/preview/previewctl/go.mod
  dev/preview/previewctl/go.sum
  dev/preview/previewctl/pkg/k8s/context/k3s/k3s.go
  dev/preview/previewctl/pkg/k8s/pforward.go
  dev/preview/previewctl/pkg/preview/context.go
  dev/preview/previewctl/pkg/preview/preview.go
  dev/preview/previewctl/pkg/preview/status.go
  dev/preview/previewctl/pkg/preview/util.go
Labels: size/XXL, release-note-none, team: devx

#15198 [oidc] Add stub RPCs
  components/common-go/experiments/flags.go
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/XL, team: webapp, team: workspace, release-note-none

#15205 [usage] make increment billing cycle more robust
  components/gitpod-db/go/cost_center.go
  components/usage/pkg/apiv1/billing.go
Labels: size/XS, team: webapp, release-note-none

#15166 preview delete cron use previewctl list stale
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/prepare.ts
  .werft/platform-delete-preview-environment.ts
  .werft/platform-delete-preview-environments-cron.ts
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/util/preview.ts
  .werft/vm/vm.ts
  dev/preview/previewctl/BUILD.yaml
  dev/preview/previewctl/cmd/stale.go
  dev/preview/previewctl/cmd/workspaces.go
  dev/preview/previewctl/pkg/preview/status.go
  dev/preview/workflow/preview/configure-workspace.sh
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none, team: devx, team: delivery-operations-experience

#15062 [Server] Extract IDE config resolution logic to ide-service
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/ide-service.spec.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/workspace-starter.spec.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: webapp, team: IDE, release-note-none

#14938 [dashboard] List projects using Public API
  components/dashboard/src/Menu.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/go/gitpod-service.go
Labels: size/L, team: webapp, release-note-none

#15208 Clean up bash scripts in favour of `previewctl`
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/prepare.ts
  .werft/observability/monitoring-satellite.ts
  .werft/platform-delete-preview-environment.ts
  .werft/platform-delete-preview-environments-cron.ts
  .werft/util/preview.ts
  .werft/vm/vm.ts
  dev/preview/BUILD.yaml
  dev/preview/install-k3s-kubeconfig.sh
  dev/preview/previewctl/pkg/preview/status.go
  dev/preview/ssh-vm.sh
  dev/preview/util/portforward-monitoring-satellite-core-dev.sh
  dev/preview/util/portforward-monitoring-satellite-harvester.sh
  dev/preview/util/preview-name-from-branch.sh
  dev/preview/workflow/preview/build.sh
  dev/preview/workflow/preview/deploy-gitpod.sh
  dev/preview/workflow/preview/deploy-monitoring-satellite.sh
Labels: size/L, release-note-none, team: devx, team: delivery-operations-experience

#15212 [server] don't fail on currency change
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#15201 flag: add BETA Label to `/tokens` page
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/XS, team: webapp, release-note-none

#15165 Update Code to `1.74.0`
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#15216 [content-service] Prevent permission denied during content init
  components/content-service/pkg/archive/tar.go
Labels: size/XS, team: workspace, release-note

#15225 [alerts] improve autoscale alert to provide actual reason for failure in alert message
  operations/observability/mixins/workspace/rules/central/nodes.yaml
Labels: size/XS, team: workspace, release-note-none

#15224 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15226 [werft] Remove helm publish job
  .werft/jobs/build/build-and-publish.ts
Labels: size/S, release-note-none

#15220 [installer]: improve the comparison method for the golden files
  install/installer/cmd/render_test.go
Labels: size/XS, release-note-none, team: delivery-operations-experience

#15230 [dashboard] consistent pay wall
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartPage.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/L, team: webapp, release-note-none

#15242 Remove unused scripts
  dev/preview/install-k3s-kubeconfig.sh
  dev/preview/portforward-monitoring-satellite.sh
  dev/preview/util/portforward-monitoring-satellite-core-dev.sh
  dev/preview/util/portforward-monitoring-satellite-harvester.sh
  dev/preview/util/setup-access.sh
Labels: size/L, release-note-none, team: devx

#15030 Parallelise dev:preview and deploy monitoring satellite automatically
  dev/preview/workflow/preview/preview.sh
Labels: size/XS, release-note-none, team: devx

#15244 Wait for certificate and log error when it fails
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, release-note-none, team: devx

#15222 [public-api] implement public api methods for supervisor
  components/public-api-server/pkg/apiv1/user.go
  components/public-api-server/pkg/apiv1/user_test.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#15247 Remove beta and early access labels for Teams, Projects, and Billing
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/M, team: webapp, release-note

#15255 Append "excluding VAT" to prices on billing pages
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/XS, team: webapp, release-note

#15257 Remove Kubescape from preview environments
  dev/preview/workflow/config/monitoring-satellite.yaml
Labels: size/XS, release-note-none, team: devx

#15112 Use public api in supervisor
  components/common-go/experiments/configcat.go
  components/common-go/experiments/flags.go
  components/common-go/experiments/types.go
  components/supervisor/BUILD.yaml
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/metrics/reporter.go
  components/supervisor/pkg/ports/exposed-ports.go
  components/supervisor/pkg/ports/ports-config.go
  components/supervisor/pkg/ports/ports-config_test.go
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/git.go
  components/supervisor/pkg/supervisor/supervisor.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/XXL, team: IDE, release-note-none

#15261 [code] code-nightly point back to main
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE, release-note-none

#15264 [ide-service]: update grafana dashboard
  operations/observability/mixins/IDE/dashboards/components/ide-service.json
Labels: size/L, team: IDE, release-note-none

#15263 [installer]: make the kots install overwrite the config if exists
  install/installer/scripts/kots-install.sh
Labels: size/XS, release-note, team: delivery-operations-experience

#15271 Revert "Use public api in supervisor"
  components/common-go/experiments/configcat.go
  components/common-go/experiments/flags.go
  components/common-go/experiments/types.go
  components/supervisor/BUILD.yaml
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/metrics/reporter.go
  components/supervisor/pkg/ports/exposed-ports.go
  components/supervisor/pkg/ports/ports-config.go
  components/supervisor/pkg/ports/ports-config_test.go
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/git.go
  components/supervisor/pkg/supervisor/supervisor.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none

#15221 Update beta label on access tokens
  components/dashboard/src/settings/PersonalAccessTokens.tsx
Labels: size/XS, team: webapp, release-note-none

#15268 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15269 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15278 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15289 [wsmanager] improve error tracing in finalize workspace content
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#15288 [dashboard] allow setting ws class for prebuilds
  components/dashboard/src/projects/ProjectSettings.tsx
  components/gitpod-protocol/src/protocol.ts
Labels: size/M, team: webapp, release-note

#14978 [Analytics] adopt cookieless ID on dashboard and server
  components/dashboard/src/Analytics.tsx
  components/server/src/analytics.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#15300 Default to letsencrypt cert isuser
  .werft/jobs/build/job-config.ts
  dev/preview/BUILD.yaml
Labels: size/S, release-note-none, team: devx

#15120 Remove build artefacts from Leeway package srcs listings
  components/dashboard/BUILD.yaml
  components/ee/db-sync/BUILD.yaml
  components/ee/payment-endpoint/BUILD.yaml
  components/gitpod-db/BUILD.yaml
  components/licensor/typescript/BUILD.yaml
  components/server/BUILD.yaml
  components/ws-manager-bridge/BUILD.yaml
  dev/preview/workflow/preview/build.sh
  install/installer/BUILD.yaml
Labels: size/M, team: webapp, release-note-none, team: devx, team: delivery-operations-experience

#15303 Fix var assignment in deploy-harvester
  dev/preview/workflow/preview/deploy-harvester.sh
Labels: size/XS, release-note-none, team: devx

#15302 [codeowners] Add IAM component to WebApp codeowners
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#15301 [iam] Setup chi mux for routing
  components/iam/go.mod
  components/iam/go.sum
  components/iam/pkg/oidc/router.go
  components/iam/pkg/server/server.go
Labels: size/M, release-note-none

#15309 Add "Rider" and "CLion" IDEs to backend-plugin/hot-deploy.sh
  components/ide/jetbrains/backend-plugin/hot-deploy.sh
Labels: size/XS, release-note-none

#15299 fix #15266: decouple deployment of supervisor for image builds
  components/image-builder-api/go/imgbuilder.pb.go
  components/image-builder-api/imgbuilder.proto
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.js
  components/image-builder-api/typescript/src/imgbuilder_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_pb.js
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, team: workspace, release-note-none

#15284 [code-sync] Update `/v1/collection` endpoint response
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.ts
Labels: size/S, team: webapp, team: IDE, release-note-none

#15317 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15319 [test] fix dotfile test failed
  test/tests/components/ws-manager/dotfiles_test.go
Labels: do-not-merge/hold, size/XS, release-note-none

#15324 [server] increate request timeout to ide-service to 5 sec
  components/server/src/ide-service.ts
Labels: size/S, team: webapp, release-note-none

#15305 [oidc] Setup db
  components/gitpod-db/go/dbtest/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config_test.go
  components/gitpod-db/src/typeorm/migration/1670850042413-CreateOIDCClientConfigTable.ts
Labels: size/L, team: webapp, release-note-none

#15327 [configcat] Stop logging info messages
  components/common-go/experiments/configcat.go
  components/common-go/experiments/types.go
Labels: team: webapp, team: workspace

#15330 [observability] add job variable for grpc client
  operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-client.json
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: devx, team: delivery-operations-experience

#15323 [iam] Mount database secret as a file
  components/iam/pkg/config/config.go
  components/iam/pkg/server/server.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/common.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/iam/configmap.go
  install/installer/pkg/components/iam/deployment.go
Labels: size/M, team: webapp, release-note-none, team: delivery-operations-experience

#15326 Add gitpod-monitor by default
  .gitpod.yml
Labels: size/XS, release-note-none, team: devx

#15340 Revert "[configcat] Stop logging info messages"
  components/common-go/experiments/configcat.go
  components/common-go/experiments/types.go
Labels: size/S, team: webapp, team: workspace, release-note-none

#15341 Add PoC to build in GitHub actions
  .github/workflows/poc-build.yml
Labels: size/L, release-note-none

#15342 [jb-launcher] no panic on resolving user env vars
  components/ide/jetbrains/launcher/main.go
Labels: size/S, team: IDE, release-note-none

#15233 [IDE Service] Move warmup logic to JetBrains Launcher
  components/ide-service/BUILD.yaml
  components/ide-service/pkg/server/testdata/ideconfig_happypath.golden
  components/ide-service/pkg/server/testdata/ideconfig_happypath_resolve.golden
  components/ide-service/pkg/server/testdata/ideconfig_idetype_not_correct.golden
  components/ide-service/pkg/server/testdata/ideconfig_idetype_unknown.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_invalid.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code.golden
  components/ide/jetbrains/launcher/main.go
Labels: size/M, team: IDE, release-note-none, editor: jetbrains

#15343 [image-builder] Change affinity in ws clusters
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/pkg/components/image-builder-mk3/deployment.go
Labels: size/XS, team: workspace, release-note-none

#15350 Show team usage tab only for team owners
  components/dashboard/src/Menu.tsx
Labels: size/XS, team: webapp, release-note

#15352 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15355 [db] handle race in `gorm.Save`
  components/gitpod-db/go/cost_center.go
  components/gitpod-db/go/cost_center_test.go
Labels: size/S, team: webapp, release-note-none

#15366 🧹 fix typo and copy-paste-error
  components/iam/pkg/server/server.go
  components/public-api-server/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#15359 Skip stale branch check for artificial jobs
  dev/preview/previewctl/cmd/stale.go
Labels: size/XS, release-note-none, team: devx

#15356 [server] Fix clientIp extraction for analytics
  components/server/src/analytics.ts
  components/server/src/express-util.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/S, team: webapp, release-note-none

#15367 Replace prebuild message emoji
  components/supervisor/pkg/supervisor/tasks.go
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/S, team: IDE, release-note

#15364 Replace prebuild duration message emoji
  components/supervisor/pkg/supervisor/tasks.go
Labels: size/XS, team: IDE, release-note

#15320 [installer, gitpod-db] Introduce database.ssl.ca
  components/gitpod-db/go/conn.go
  components/gitpod-db/src/config.ts
  components/gitpod-db/src/wait-for-db.ts
  components/public-api-server/pkg/server/server.go
  components/service-waiter/cmd/database.go
  components/usage/pkg/server/server.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/database/init/constants.go
  install/installer/pkg/components/database/init/job.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/validation.go
Labels: size/L, team: webapp, release-note, team: delivery-operations-experience

#15376 Update code to `1.74.1`
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#15378 Wait for the workspace secret before creating the workspace pod
  components/ws-manager/pkg/manager/manager.go
Labels: size/S, team: workspace, release-note-none

#15371 Update beta notice for the JetBrains integration
  components/dashboard/src/settings/SelectIDE.tsx
Labels: size/S, team: webapp, release-note

#15382 [dashboard] link to website's cost estimator
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/S, team: webapp, release-note-none

#15379 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15363 [JetBrains] remove custom JDK detection
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodProjectManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/optional/GitpodForceUpdateMavenProjectsActivity.kt
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/launcher/hot-deploy.sh
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
Labels: size/L, team: IDE, release-note-none, editor: jetbrains

#15388 [server] Allow options on ws start (1/2)
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, team: IDE, release-note-none

#15267 Add basic OIDC client
  components/iam/.vscode/launch.json
  components/iam/go.mod
  components/iam/go.sum
  components/iam/pkg/config/config.go
  components/iam/pkg/oidc/demo.go
  components/iam/pkg/oidc/oauth2.go
  components/iam/pkg/oidc/router.go
  components/iam/pkg/oidc/service.go
  components/iam/pkg/oidc/service_test.go
  components/iam/pkg/server/server.go
Labels: size/XXL, team: webapp, release-note-none, team: devx, team: delivery-operations-experience

#15390 [launcher] hot-deploy loops through all ides
  components/ide/jetbrains/launcher/hot-deploy.sh
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#15357 Update link to Awesome Gitpod repository
  README.md
Labels: size/XS, release-note-none, team: dcs

#15408 Set refresh-credential code owner to the workspace team
  .github/CODEOWNERS
Labels: size/XS, team: workspace, release-note-none

#15407 Update go.mod
  components/iam/go.mod
  components/ide-service/go.mod
  components/refresh-credential/go.mod
Labels: size/XS, team: IDE, release-note-none

#15412 [CODEOWNERS] Make WebApp code owners of `iam` and `iam-api`
  .github/CODEOWNERS
Labels: size/XS, team: webapp, release-note-none

#15405 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15413 [ide-service] provide user id for configcat feature flags
  components/ide-service-api/go/ide.pb.go
  components/ide-service-api/ide.proto
  components/ide-service-api/typescript/src/ide.pb.ts
  components/server/src/ide-service.ts
Labels: size/M, team: IDE, release-note-none

#15416 [iam] Do not log at Trace level
  components/iam/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#15417 [oidc] Cleanup registration of route handlers
  components/iam/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#15421 [public-api] Make StopWorkspace a unary RPC
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/v1connect/workspaces.connect.go
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/go/experimental/v1/workspaces_grpc.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/ide_client_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/ide_client_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/pagination_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/S, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#15428 test: Add the script to create QA report
  test/report.sh
Labels: size/M, release-note-none

#15429 ws-manager: A bit improve the code not to use the magic number
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none

#15418 [iam] Drop OIDC prefix from service, remove unused handler
  components/iam/pkg/oidc/oauth2.go
  components/iam/pkg/oidc/router.go
  components/iam/pkg/oidc/service.go
  components/iam/pkg/oidc/service_test.go
  components/iam/pkg/server/server.go
Labels: size/L, team: webapp, release-note-none

#15381 [db] Support encrypted JSON in Go
  components/gitpod-db/go/dbtest/encryption.go
  components/gitpod-db/go/dbtest/oidc_client_config.go
  components/gitpod-db/go/encryption.go
  components/gitpod-db/go/encryption_test.go
  components/gitpod-db/go/json.go
  components/gitpod-db/go/json_test.go
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/time.go
  components/gitpod-db/go/time_test.go
Labels: size/L, team: webapp, release-note-none

#15143 Set default cols and rows when creating pty
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/terminal/terminal.go
Labels: size/L, team: IDE, release-note-none

#15432 [installer] Update third_party charts to use full index
  install/installer/third_party/charts/minio/Chart.yaml
  install/installer/third_party/charts/mysql/Chart.yaml
  install/installer/third_party/charts/rabbitmq/Chart.yaml
Labels: size/XS, release-note, team: delivery-operations-experience

#15434 reduce ownership of common-go to staff engineers
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#15415 [run-gp] experiment with adding run-gp layer to subset of users
  components/common-go/experiments/types.go
  components/ide-service-api/go/config/ideconfig.go
  components/ide-service-api/go/ide.pb.go
  components/ide-service-api/ide.proto
  components/ide-service-api/typescript/src/ide.pb.ts
  components/ide-service/.gitignore
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/ide-service/pkg/server/ideconfig.go
  components/ide-service/pkg/server/server.go
  components/ide-service/pkg/server/testdata/ideconfig_happypath.golden
  components/ide-service/pkg/server/testdata/ideconfig_happypath_resolve.golden
  components/ide-service/pkg/server/testdata/ideconfig_idetype_not_correct.golden
  components/ide-service/pkg/server/testdata/ideconfig_idetype_unknown.golden
  components/server/src/ide-service.ts
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/M, team: IDE, release-note-none, team: staff-engineers

#15414 [db] Support cipher-set in go
  components/gitpod-db/go/dbtest/encryption.go
  components/gitpod-db/go/encryption.go
  components/gitpod-db/go/encryption_test.go
Labels: size/L, team: webapp, release-note-none

#15397 Introduce new version designs
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/settings/SelectIDE.tsx
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: component: dashboard, size/M, team: webapp, team: IDE, release-note-none

#15431 ws-manager: Prevent duplication of stop metrics
  components/ws-manager/pkg/manager/metrics.go
Labels: size/XS, team: workspace, release-note-none

#15423 [public-api] Validate Workspace IDs
  components/common-go/namegen/workspaceid.go
  components/common-go/namegen/workspaceid_test.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp, team: workspace, release-note-none, team: staff-engineers

#15436 [JetBrains] Upgrade Gateway Plugin stable version to v223.7571.203
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectorView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/.gitkeep
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectorView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/.gitkeep
  components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: IDE, release-note-none, editor: jetbrains

#15448 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15458 [dashboard] Add feature flag to use Public API Workspaces Service
  components/dashboard/src/contexts/FeatureFlagContext.tsx
Labels: size/XS, team: webapp, release-note-none

#15464 [gitpod-cli] clean up
  components/gitpod-cli/cmd/info.go
  components/gitpod-cli/cmd/open.go
  components/gitpod-cli/cmd/ports-list.go
  components/gitpod-cli/cmd/preview.go
  components/gitpod-cli/cmd/tasks-attach.go
  components/gitpod-cli/cmd/tasks-list.go
  components/gitpod-cli/cmd/tasks-stop.go
  components/gitpod-cli/cmd/top.go
  components/gitpod-cli/pkg/supervisor-helper/info.go
  components/gitpod-cli/pkg/supervisor-helper/status.go
  components/gitpod-cli/pkg/supervisor-helper/supervisor.go
  components/gitpod-cli/pkg/supervisor/client.go
  components/gitpod-cli/pkg/supervisor/ports.go
  components/gitpod-cli/pkg/supervisor/status-tasks.go
  components/gitpod-cli/pkg/supervisor/terminal-attach.go
  components/gitpod-cli/pkg/utils/logError.go
Labels: size/XL, team: IDE, release-note-none

#15460 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15461 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains
