Repository gitpod-io/gitpod, pull requests merged in 2022-03, with the labels that each got.

#8469 change alert period for ws stuck on starting or stopping to 20m
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#8495 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8077 Update VS Code References (settings sync schema, leeway)
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-resource.ts
  components/ide/code/leeway.Dockerfile
  components/server/src/code-sync/code-sync-service.ts
Labels: size/M, team: webapp, team: IDE, release-note-none

#8483 Update runbook url for GitpodWsDaemonExcessiveGC
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#8514 [code] point code nightly to gp-code main release 1.65
  .github/workflows/code-nightly.yaml
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/XS, team: IDE, release-note-none

#8515 Update code nightly action
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#8519 try harder when attempting to add or remove annotation from workspaces
  components/ws-manager/pkg/manager/annotations.go
Labels: size/S, team: workspace, release-note

#8521 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8526 Fix codehelper nil point
  components/ide/code/codehelper/main.go
Labels: size/XS, team: IDE, release-note-none

#8477 installer: clarify experimental config flag
  install/installer/cmd/render.go
Labels: size/XS, release-note, team: self-hosted

#8503 Remove free text search on contextURL
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note

#8530 Set the timeout for the server deployment to 10min
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none, team: platform

#8544 Fix launch-dev-server script to work also from VS Code
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/ControllerStatusService.kt
Labels: size/XS, team: IDE, release-note-none

#8552 [code] codehelper exec replace process
  components/ide/code/codehelper/main.go
Labels: team: IDE, release-note-none

#8556 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8549 Pass auth cookie as env variable
  test/pkg/agent/workspace/api/api.go
  test/pkg/agent/workspace/main.go
  test/tests/ide/vscode/python_ws_test.go
Labels: size/S, release-note-none

#8543 Updated the VM manifest to use the newly exported image for VM based preview-environments
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8546 Link to privacy policy from login page
  components/dashboard/src/Login.tsx
Labels: size/XS, team: webapp, release-note, team: product-design

#8565 [dashboard] Further disambiguate 'Team Plans' vs 'Teams' based on user feedback (title, button, invite modal)
  components/dashboard/src/settings/Teams.tsx
Labels: size/XS, team: webapp, release-note-none

#8562 Fix workspace search under user detail
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-protocol/src/admin-protocol.ts
Labels: size/XS, team: webapp, release-note

#8570 Update UA logo
  components/dashboard/src/icons/gitpod-ua.svg
Labels: size/XS, team: webapp, release-note-none

#8571 Update UA logo
  components/dashboard/src/icons/gitpod-ua.svg
Labels: size/XS, team: webapp, release-note-none

#8587 add warning when all attempts to download OTS have failed
  components/content-service/pkg/initializer/initializer.go
Labels: size/XS, team: workspace, release-note-none

#8591 chore(server): add github app install script for dev iteration against staging github app
  components/server/install-gh-app.sh
Labels: size/M, team: webapp, release-note-none

#8538 Add Replicated/KOTS dependencies to image
  .gitpod.yml
  .werft/build.yaml
  .werft/clean-up-werft-build-nodes.yaml
  .werft/debug.yaml
  .werft/delete-preview-environments/delete-preview-environments-cron.yaml
  .werft/delete-preview-environments/delete-preview-environments.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
Labels: size/S, release-note-none, team: platform

#8535 werft/deploy/post-process: Use intention-revealing variable name
  .werft/jobs/build/installer/post-process.sh
Labels: size/M, release-note-none, team: platform

#8598 werft/vm: Update image
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none

#8577 Improve werft job build speed and make honeycomb more accurate
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none

#8609 Update to vscode 1.65
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#8599 Revert "werft/vm: Update image"
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none

#8606 Update debug script
  components/ws-daemon/debug.sh
Labels: size/S, team: workspace, release-note-none

#8611 [code] update stable to 1.65
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#8624 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#8590 A little follow-up on cgroup v2 support
  components/ws-daemon/pkg/iws/iws.go
  docs/workspace/architecture.drawio.svg
  docs/workspace/namespaces.drawio.svg
Labels: size/L, team: workspace, release-note

#8622 [installer] Add network policy for registry-facade access to coredns
  install/installer/pkg/common/networkpolicies.go
Labels: size/S, release-note, team: self-hosted

#8632 Only allow exact-matching of workspace search
  components/dashboard/src/admin/WorkspacesSearch.tsx
Labels: size/S, team: webapp, release-note

#8547 [installer]: add annotation to make DB resources restart if changes
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/M, team: webapp, release-note

#8602 [prebuilds] Introduce 'failed' state for prebuilds
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/gitpod-protocol/src/headless-workspace-log.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
  components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/M, team: webapp, release-note-none

#8640 [code] revert code nightly to gp-code main
  .github/workflows/code-nightly.yaml
Labels: size/XS, release-note-none

#8608 Introduce TeamSubscription.noMoreResources to be able to exclude TeamSubscriptions from bigger clusters
  components/ee/payment-endpoint/src/chargebee/team-subscription-handler.ts
  components/gitpod-db/src/team-subscription-db.ts
  components/gitpod-db/src/typeorm/entity/db-team-subscription.ts
  components/gitpod-db/src/typeorm/migration/1646410374581-TSNoMoreResources.ts
  components/gitpod-db/src/typeorm/team-subscription-db-impl.ts
  components/gitpod-protocol/src/team-subscription-protocol.ts
  components/server/ee/src/typings/swot-js/index.d.ts
  components/server/ee/src/user/eligibility-service.spec.db.ts
  components/server/ee/src/user/eligibility-service.ts
  components/server/tsconfig.json
Labels: size/L, team: webapp, release-note-none

#8617 [server] Temp. disable expensive telemetry queries
  components/server/src/installation-admin/telemetry-data-provider.ts
Labels: size/XS, team: webapp, release-note-none

#8649 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8639 werft/vm/manifest: Disable google cloud agent
  .werft/vm/manifests.ts
Labels: size/S, release-note-none, team: platform

#8643 werft/build/prepare: Cleanup code
  .werft/jobs/build/prepare.ts
Labels: size/M, release-note-none, team: platform

#8636 .werft/build: Cleaning code
  .werft/build.ts
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/validate-changes.ts
Labels: size/M, release-note-none

#8629 Disable cache reclaim when cgroup v2.
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/S, team: workspace, release-note

#8657 [kots]: add workaround for #8529
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/S, release-note-none, team: self-hosted

#8633 [kots]: make the self-hosted cert more explicitly selectable
  install/kots/manifests/gitpod-certificate.yaml
  install/kots/manifests/kots-config.yaml
Labels: size/M, release-note, team: self-hosted

#8661 werft/deploy: Trigger VM creation before container builds
  .werft/build.ts
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/prepare.ts
  .werft/vm/vm.ts
Labels: size/M, release-note-none, team: platform

#8667 .werft/vm/manifest: Faster boots by requiring less readiness probes
  .werft/vm/manifests.ts
Labels: size/S, release-note-none, team: platform

#8670 [prebuilds] stopping prebuilds are not failed
  components/ws-manager-bridge/ee/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#8550 Support private registries
  components/image-builder-api/go/imgbuilder.pb.go
  components/image-builder-api/imgbuilder.proto
  components/image-builder-api/typescript/src/imgbuilder_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_pb.js
  components/image-builder-bob/cmd/proxy.go
  components/image-builder-bob/pkg/proxy/auth.go
  components/image-builder-mk3/debug.sh
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/image-source-provider.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: webapp, team: workspace, release-note

#8675 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8673 Send slack notification when IDE integration tests fails
  .werft/integration-tests-startup.yaml
  .werft/run-integration-tests-ide.yaml
  test/leeway.Dockerfile
Labels: size/S, release-note-none

#8674 .werft/build/prepare: Clarify why we compare workapce and job image
  .werft/jobs/build/prepare.ts
Labels: size/XS, release-note-none, team: platform

#8678 ./werft/deploy: Log secret creation to the correct slice
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none, team: platform

#8666 Enable changing default editor in integration tests
  components/gitpod-protocol/go/gitpod-service.go
  test/tests/ide/vscode/python_ws_test.go
Labels: size/S, team: webapp, release-note-none

#8682 Wait until k3s apiserver is ready
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/S, release-note-none, team: platform

#8687 werft/deploy: Wait for certmanager readiness on Harvester deployments
  .werft/jobs/build/deploy-to-preview-environment.ts
Labels: size/XS, release-note-none, team: platform

#8689 [kots]: create dev channels in KOTS and formalise the release process
  install/kots/Makefile
  install/kots/README.md
Labels: size/M, release-note, team: self-hosted

#8694 [installer] Add air-gap instructions
  install/installer/docs/air-gap.md
Labels: size/M, release-note-none, team: self-hosted

#8711 [server] fix compile error
  components/gitpod-db/src/typeorm/migration/1646803519382-PrebuildUpdatableSHA.ts
  components/server/ee/src/prebuilds/github-enterprise-app.ts
Labels: size/S, team: webapp

#8712 Be more robust in case kubectl fails
  .werft/util/kubectl.ts
Labels: size/S, release-note-none, team: platform

#8655 Add prettier to pre-commit, install pre-commit in prebuild
  .gitpod.yml
  .pre-commit-config.yaml
  .prettierrc.json
  .werft/jobs/build/validate-changes.ts
Labels: size/M, team: webapp, release-note-none

#8721 [ws-manager-bridge] Document ClusterService rpcs and messages
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/go/cluster-service_grpc.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_grpc_pb.js
Labels: size/M, team: webapp, release-note

#8726 Fix error handling
  .werft/util/kubectl.ts
Labels: size/XS, release-note-none, team: platform

#8722 [server][hotfix] Disable webhooks for github.com and GitHub Enterprise
  components/server/src/projects/projects-service.ts
Labels: size/XS, team: webapp, release-note-none

#8708 [kots]: add standard labels to KOTS manifests
  install/kots/manifests/gitpod-certificate-secret.yaml
  install/kots/manifests/gitpod-certificate.yaml
  install/kots/manifests/gitpod-cloudsql-secret.yaml
  install/kots/manifests/gitpod-config-patch.yaml
  install/kots/manifests/gitpod-database-secret.yaml
  install/kots/manifests/gitpod-dns-gcp-secret.yaml
  install/kots/manifests/gitpod-installation.yaml
  install/kots/manifests/gitpod-issuer-azure.yaml
  install/kots/manifests/gitpod-issuer-gcp.yaml
  install/kots/manifests/gitpod-license.yaml
  install/kots/manifests/gitpod-registry-s3-backend.yaml
  install/kots/manifests/gitpod-storage-azure-secret.yaml
  install/kots/manifests/gitpod-storage-gcp-secret.yaml
  install/kots/manifests/gitpod-storage-s3-secret.yaml
Labels: size/M, release-note, team: self-hosted

#8737 Update to vscode 1.65.2
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#8741 [code] update stable to 1.65.2
  chart/values.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#8736 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8699 align dashboard plans page wording on website
  components/dashboard/src/settings/Plans.tsx
Labels: size/XS, team: webapp, release-note

#8743 Werft tracing improvements
  .werft/build.ts
Labels: size/S, release-note-none, team: platform

#8754 Use placeholder text for Provider Host input
  components/dashboard/src/settings/Integrations.tsx
Labels: team: webapp, release-note-none

#8763 [installer] explain `InstallerKind` in README
  install/installer/README.md
Labels: size/XS, release-note-none, team: self-hosted

#8732 [Analytics] Track when users save a change to the dotfile repo
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/settings/Preferences.tsx
Labels: size/XXL, team: webapp, release-note-none

#8768 [server] Lint/fix prebuild-manager.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: size/L, team: webapp, release-note-none

#8685 Remove Theia extension related code
  components/gitpod-protocol/BUILD.yaml
  components/gitpod-protocol/data/builtin-theia-plugins.json
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/theia-plugins.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/code-sync/code-sync-service.ts
  components/server/src/container-module.ts
  components/server/src/theia-plugin/theia-plugin-service.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: webapp, team: IDE, release-note-none

#8770 [kubecdl] Fix server name pattern
  dev/kubecdl/main.go
Labels: size/XS, release-note

#8644 [server] remove setting sync record with limit
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.ts
  components/server/src/code-sync/code-sync-service.ts
Labels: size/L, team: webapp, release-note

#8774 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8750 Only flush traces once
  .werft/observability/tracing.ts
Labels: size/S, release-note-none, team: platform

#8739 fix #8738: Interpreting https://self as a hostname, not a keyword. If…
  components/proxy/conf/Caddyfile
Labels: size/XS, release-note-none

#8748 Fixing the clean-slate-deployment of new VM base preview-environments
  .werft/jobs/build/prepare.ts
Labels: size/S, release-note-none, team: platform

#8793 Fix caching of GitHub queries
  components/server/src/github/api.ts
Labels: size/XXL, team: webapp, release-note

#8787 .werft/build: Remove code-coverage
  .werft/build.ts
  .werft/jobs/build/coverage.ts
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#8808 [loadgen] Update benchmark yaml
  dev/loadgen/prod-benchmark.yaml
Labels: size/M, team: workspace, release-note

#8709 Adds new foreign route for vscode webview/webworker resources
  WORKSPACE.yaml
  components/proxy/conf/Caddyfile
  components/ws-proxy/pkg/proxy/workspacerouter.go
  components/ws-proxy/pkg/proxy/workspacerouter_test.go
Labels: size/L, team: webapp, team: workspace, release-note-none

#8821 [db] Add missing Workspace index (id, deleted)
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/migration/1647333804782-IndexWorkspaceIdDeleted.ts
Labels: size/S, team: webapp, release-note

#8806 Use timingSafeEqual for signature comparision
  components/server/ee/src/prebuilds/github-enterprise-app.ts
Labels: size/XS, team: webapp, release-note-none

#8828 Update python-test-workspace repo in ide test
  test/tests/ide/vscode/python_ws_test.go
Labels: size/XS, release-note-none

#8827 Fix docker run --privileged
  components/docker-up/docker-up/main.go
Labels: size/XS, team: workspace, release-note

#8785 [kots] remove cert-manager from Gitpod package
  install/kots/Makefile
  install/kots/README.md
  install/kots/charts/cert-manager/Chart.yaml
  install/kots/manifests/crd-cert-manager.yaml
  install/kots/manifests/gitpod-certificate.yaml
  install/kots/manifests/gitpod-installer-job.yaml
  install/kots/manifests/gitpod-issuer-azure.yaml
  install/kots/manifests/gitpod-issuer-gcp.yaml
  install/kots/manifests/helm-cert-manager.yaml
  install/kots/manifests/kots-config.yaml
Labels: size/XXL, release-note, team: self-hosted

#8839 Discard log output from slirp4netns
  components/workspacekit/cmd/rings.go
Labels: size/XS, team: workspace, release-note-none

#8837 [installer]: allow for minified config YAML
  install/installer/pkg/config/loader.go
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note, team: self-hosted

#8849 [agent-smith] lock workspaces map before read
  components/ee/agent-smith/pkg/agent/agent.go
Labels: size/S, team: workspace, release-note-none

#8847 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8781 [dev] Update Dockerfile
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/platform-clean-up-werft-build-nodes.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
Labels: size/M, release-note-none, team: platform

#8854 [server] Fix checkoutLocation for imagebuilds
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note

#8819 .werft/observabilityAdd configuration to deploy kubescape
  .werft/observability/monitoring-satellite.ts
Labels: release-note-none, team: platform

#8858 [gitpod-db] add index on `workspaceDB.Type` Column
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/migration/1647290507971-IndexWorkspaceType.ts
Labels: size/S, team: webapp, release-note

#8852 [observability] Add agent-smith egress violations graph
  operations/observability/mixins/workspace/dashboards/components/agent-smith.json
Labels: size/L, team: workspace, release-note-none

#8870 [kots]: remove GCP DNS resolver
  install/kots/manifests/gitpod-dns-gcp-secret.yaml
Labels: size/S, release-note, team: self-hosted

#8876 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8878 [db] Fix findPrebuildsWithWorkpace
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/XS, team: webapp, release-note

#8797 Add job attributes to all spans
  .werft/jobs/build/job-config.ts
  .werft/util/werft.ts
Labels: size/M, release-note-none, team: platform

#8881 [installer]: handle different line endings on apiVersion extraction
  install/installer/pkg/config/loader.go
Labels: size/XS, release-note-none, team: self-hosted

#8875 Remove truncation and overflow team invitation URL
  components/dashboard/src/teams/Members.tsx
Labels: component: dashboard, team: webapp, release-note

#8885 Update VM image to gitpod-k3s-202203171353.qcow2
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8835 Remove re-run from /prebuilds, redirect to logs when rerunning
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
Labels: size/L, release-note

#8889 Revert "Update VM image to gitpod-k3s-202203171353.qcow2"
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8907 [kubecdl] Fix instance filter
  dev/kubecdl/main.go
Labels: size/XS, release-note-none

#8844 [kots] Add a pre-flight check for `cert-manager`
  install/kots/manifests/kots-preflight.yaml
Labels: size/XS, release-note, team: self-hosted

#8899 Remove console statements introduced in #7715
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: size/XS, team: webapp, release-note-none

#8853 [server] Finish spans
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp, release-note-none

#8909 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8887 Update VM image and handling
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#8898 Add script to preload images onto nodes
  dev/preview/distribute-images.sh
Labels: size/M, release-note-none, team: platform

#8892 [kots]: escape golang template variables for Helm resources
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note, team: self-hosted

#8923 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8857 [KOTS]: add recommended preflights
  install/kots/manifests/kots-preflight.yaml
Labels: size/M, release-note, team: self-hosted

#8918 [ws-proxy] Configure kube-rbac
  install/installer/pkg/components/ws-proxy/configmap.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XS, team: workspace, release-note

#8931 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8914 [supervisor] add sudo permission to custom images
  components/supervisor/pkg/supervisor/user.go
Labels: size/M, team: IDE, release-note

#8932 [observability] Update agent smith graph
  operations/observability/mixins/workspace/dashboards/components/agent-smith.json
Labels: size/XS, team: workspace, release-note-none

#8951 allow to specify vm name when connecting to harvester VM
  dev/preview/ssh-proxy-command.sh
  dev/preview/ssh-vm.sh
Labels: size/XS, release-note-none, team: platform

#8968 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8960 Fix kubecdl to work with workspace-clusters
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/platform-clean-up-werft-build-nodes.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  dev/image/Dockerfile
  dev/kubecdl/.vscode/launch.json
Labels: size/M, release-note-none, team: platform

#8794 [Analytics] Enrich 'workspace_started' call with projectId and type
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp, release-note-none

#8949 [Analytics] Include Invite ID with Team created Call
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#8772 Update team deletion confirmation modal
  components/dashboard/src/teams/TeamSettings.tsx
Labels: meta: never-stale, size/XS, team: webapp, release-note

#8873 Avoid using process.exit as we need to flush telemetry
  .werft/build.ts
  .werft/util/slack.ts
Labels: size/M, release-note-none, team: platform

#8813 ui: enlarge search box on dashboard
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: community-contribution, size/XS, release-note-none, cla: pending :hourglass_flowing_sand:

#8969 Revert "ui: enlarge search box on dashboard"
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XS, team: webapp, release-note-none

#8759 [installer] set the ServiceType as LB for ws-proxy
  install/installer/README.md
  install/installer/pkg/components/ws-proxy/objects.go
Labels: size/M, team: workspace, release-note-none, team: self-hosted

#8915 telemetry: Enable data fields that were disabled
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/installation-admin/telemetry-data-provider.ts
Labels: size/M, team: webapp, release-note, team: self-hosted

#8993 Ignore VNC related ports on boot
  .gitpod.yml
Labels: size/S, release-note-none

#9002 Improve sidebar menu colors
  components/dashboard/src/components/PageWithSubMenu.tsx
Labels: size/XS, team: webapp, release-note

#8891 Iterate through pages
  components/server/ee/src/bitbucket/bitbucket-app-support.ts
Labels: size/M, team: webapp, release-note

#9008 [idea] ignore compiled files in gitpod repo
  .idea/gitpod.iml
Labels: size/S, release-note-none

#9009 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#8884 .werft/build: Refactor installer steps into dedicated class
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
Labels: size/XL, release-note-none, team: platform

#8761 [installer] Add docs for workspace SSH access
  install/installer/docs/workspace-ssh-access.md
Labels: size/S, release-note-none, team: self-hosted

#7556 Add epic issue template
  .github/ISSUE_TEMPLATE/epic.yml
Labels: size/L, release-note-none

#9015 [idea] Ignore .idea/misc.xml which contains opened editor config
  .gitignore
  .idea/misc.xml
Labels: size/XS, release-note-none

#8917 Extend compatibility of JetBrains Gateway plugin to the EAP version
  components/ide/jetbrains/gateway-plugin/gradle.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnector.kt
Labels: size/S, team: IDE, release-note

#8996 [install]: document installing via kots
  install/README.md
  install/licenses/Community (Beta).yaml
  install/licenses/Community (Unstable).yaml
  install/licenses/Community.yaml
Labels: size/L, release-note, team: self-hosted

#9027 [code] point code nightly to gp-code main release 1.66
  .github/workflows/code-nightly.yaml
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#9029 Bump node version
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/XS, team: IDE, release-note-none

#9032 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm
