Repository gitpod-io/gitpod, pull requests merged in 2022-10, with the labels that each got.

#13467 [werft] Use awscliv2 from dev-environment and skip install in cleanup preview job
  .werft/cleanup-installer-tests.yaml
Labels: size/XS, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#13475 test: restart control plane components after the volume snapshot is finished
  test/pkg/integration/apis.go
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/L, team: workspace, release-note-none

#13471 [certificates]: validate that certs are valid for a Gitpod install
  .github/CODEOWNERS
  components/BUILD.yaml
  components/kots-config-check/certificate/BUILD.yaml
  components/kots-config-check/certificate/entrypoint.sh
  components/kots-config-check/certificate/leeway.Dockerfile
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/L, release-note, team: self-hosted

#13516 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#13363 [image-builder-mk3] Use baseserver
  components/image-builder-api/go/config/config.go
  components/image-builder-api/go/go.mod
  components/image-builder-api/go/go.sum
  components/image-builder-mk3/cmd/root.go
  components/image-builder-mk3/cmd/run.go
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/go.sum
  install/installer/pkg/components/image-builder-mk3/configmap.go
Labels: size/L, team: workspace, release-note-none, team: self-hosted

#13454 JetBrains: Update `launch-dev-script.sh` and contributing docs
  components/ide/jetbrains/backend-plugin/.run/backend-plugin.run.xml
  components/ide/jetbrains/backend-plugin/README.md
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
Labels: size/L, team: IDE, release-note-none

#13477 [migrations] Delete Probe workspaces from DB
  components/gitpod-db/src/typeorm/migration/1664524890935-DeleteProbeWorkspacesAndInstances.ts
Labels: size/S, team: webapp, release-note-none

#13522 [public-api] Reuse metrics registry from baseserver
  components/public-api-server/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#13524 [db] Add `uid` column to `d_b_oauth_auth_code_entry` table
  components/gitpod-db/src/typeorm/migration/1664781308555-ChangeOauthCodePrimaryKey.ts
Labels: size/S, team: webapp, release-note-none

#13247 Add awesome-gitpod link in the docs section
  README.md
Labels: size/XS

#13545 [installer] Support enabling protected secrets
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/types.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, release-note-none, team: self-hosted

#13509 [code] point nightly job to gp-code/release/1.72
  .github/workflows/code-nightly.yaml
Labels: size/XS, team: IDE, release-note-none

#13472 Minor cleanup for blobserver response headers
  components/ide-proxy/conf/Caddyfile
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: size/S, team: workspace, team: IDE, release-note-none

#13539 [obs] Dashboard for psi metrics
  operations/observability/mixins/workspace/dashboards.libsonnet
  operations/observability/mixins/workspace/dashboards/psi.json
Labels: size/XXL, team: workspace, release-note-none

#13429 ws-manager: remove PVC object if the workspace pod fails to up
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note

#13518 test: restart control plane components during the volume snapshot is in progress
  test/go.mod
  test/go.sum
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/M, team: workspace, release-note-none

#13554 [ws-manager] fix tests
  components/ws-manager/pkg/manager/annotations_test.go
  components/ws-manager/pkg/manager/manager_test.go
Labels: size/S, team: workspace, release-note-none

#13538 Update free plan name
  components/dashboard/src/settings/Plans.tsx
  components/gitpod-protocol/src/plans.ts
Labels: size/XS, team: webapp, release-note

#13519 [db] Remove usages of the `d_b_layout_data` table
  components/gitpod-db/src/typeorm/entity/db-layout-data.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/TakeSnapshotOptions.java
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/snapshot-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
  dev/loadgen/cmd/run.go
  dev/loadgen/configs/prod-benchmark-pvc.yaml
  dev/loadgen/configs/prod-benchmark.yaml
  dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml
  dev/loadgen/configs/workspace-preview-benchmark.yaml
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none

#13563 [usage] Fix alerting for GitpodUsageTooLongSinceLastSuccessfulLedgerReconciliation
  operations/observability/mixins/meta/rules/usage.yaml
Labels: size/XS, team: webapp, release-note-none

#13565 [usage] Handle Stripe customers with zero subscriptions
  components/usage/pkg/stripe/stripe.go
Labels: size/M, team: webapp, release-note-none

#13566 [usage] Make function output stable to fix flaky test
  components/usage/pkg/stripe/stripe.go
Labels: size/XS, team: webapp, release-note-none

#13568 [dashboard] Fix off-by-one error on usage range end date
  components/dashboard/src/components/UsageView.tsx
Labels: size/XS, team: webapp, release-note-none

#13572 Revert "[migrations] Delete Probe workspaces from DB"
  components/gitpod-db/src/typeorm/migration/1664524890935-DeleteProbeWorkspacesAndInstances.ts
Labels: size/S, team: webapp, release-note-none

#13548 [server] Removes momentjs and replaces it with dayjs
  components/dashboard/package.json
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/index.tsx
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/settings/SSHKeys.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/ee/db-sync/package.json
  yarn.lock
Labels: size/L, team: webapp, release-note-none

#13571 [usage] Simplify dashboard by showing gauge and history in the same graph
  operations/observability/mixins/meta/dashboards/components/usage.json
Labels: size/L, team: webapp, release-note-none

#13569 [admin] don't run an empty search on load
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
Labels: size/S, team: webapp, release-note-none

#13557 Two rows of 4 option on onboarding IDE selector
  components/dashboard/src/settings/SelectIDEModal.tsx
Labels: community-contribution, size/XS, release-note-none, cla: pending :hourglass_flowing_sand:

#13540 [terraform] cleaning up k3s module to use for tests
  .werft/installer-tests.ts
  install/infra/modules/gke/output.tf
  install/infra/modules/k3s/dns.tf
  install/infra/modules/k3s/local.tf
  install/infra/modules/k3s/main.tf
  install/infra/modules/k3s/output.tf
  install/infra/modules/k3s/variables.tf
  install/infra/modules/tools/cloud-dns-ns/main.tf
  install/infra/single-cluster/k3s/cluster.tf
  install/infra/single-cluster/k3s/local.tf
  install/infra/single-cluster/k3s/output.tf
  install/infra/single-cluster/k3s/tools.tf
  install/infra/single-cluster/k3s/variables.tf
  install/tests/Makefile
  install/tests/main.tf
  install/tests/output.tf
Labels: size/XL, release-note-none, team: self-hosted

#13573 [db-sync] Optionally read DB credentials from env vars
  components/ee/db-sync/src/commands.ts
  components/ee/db-sync/src/config.ts
Labels: size/L, team: webapp, release-note-none

#13515 [ws-daemon] Improve download speed of snapshots
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/pkg/content/initializer.go
Labels: size/S, team: workspace, release-note-none

#13341 allow to enable PVC feature flag for user via ConfigCat
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/config-provider.ts
Labels: size/M, team: webapp, release-note-none

#13560 loadgen: make the start workspace timeout same as the ws-manager start workspace timeout
  dev/loadgen/pkg/loadgen/executor.go
Labels: size/XS, team: workspace, release-note-none

#13594 [pvc] potential workaround for mount volume failure
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none

#13586 [test] Reduce loop wait time
  components/image-builder-mk3/pkg/orchestrator/monitor.go
  components/ws-daemon/cmd/content-initializer/main.go
  components/ws-daemon/cmd/root.go
  components/ws-daemon/pkg/content/initializer.go
  test/pkg/integration/workspace.go
Labels: size/L, team: workspace, release-note-none

#13588 [dashboard] Fix integrations wording
  components/dashboard/src/Setup.tsx
Labels: size/XS, team: webapp, release-note-none

#13582 [proxy] Handle both gRPC and HTTP requests against public-api
  components/proxy/conf/Caddyfile
  components/public-api-server/pkg/server/server.go
Labels: size/S, team: webapp, release-note-none

#13414 [dashboard] Deprecate the creation of projects under individual accounts
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/PillMenuItem.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/teams/teams-context.tsx
Labels: size/XL, team: webapp, release-note

#13584 [db] Add a `_lastModified` column to the `d_b_oauth_auth_code_entry` table
  components/gitpod-db/src/typeorm/migration/1664894040785-AddLastModifiedToAuthCodeTable.ts
Labels: size/S, team: webapp, release-note-none

#13537 feat(gitpod-cli): Create `gp info` command
  components/gitpod-cli/cmd/info.go
Labels: size/L, team: IDE, release-note

#13386 [ws-daemon] fix WaitForInit not found error in tracing
  components/ws-daemon-api/daemon.proto
  components/ws-daemon-api/go/daemon.pb.go
  components/ws-daemon-api/go/daemon_grpc.pb.go
  components/ws-daemon-api/go/mock/mock.go
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_pb.js
  components/ws-daemon/pkg/content/service.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/L, team: workspace, release-note-none

#13585 [usage] Only show notification to team owners
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#13600 Infer with-preview if with-integration-tests is set
  .werft/jobs/build/job-config.ts
Labels: size/S, release-note-none, team: platform

#13611 [stripe] Fix inverted comparison
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/XS, team: webapp, release-note-none

#13579 [public-api] Switch go codegen to buf
  components/public-api/buf.gen.yaml
  components/public-api/generate.sh
  components/public-api/go/v1/pagination.pb.go
  components/public-api/go/v1/prebuilds.pb.go
  components/public-api/go/v1/prebuilds_grpc.pb.go
  components/public-api/go/v1/workspaces.pb.go
  components/public-api/go/v1/workspaces_grpc.pb.go
  components/public-api/google/rpc/LICENSE
  components/public-api/google/rpc/README.md
  components/public-api/google/rpc/code.proto
  components/public-api/google/rpc/error_details.proto
  components/public-api/google/rpc/status.proto
  scripts/protoc-generator.sh
Labels: size/XXL, team: webapp, release-note-none

#13604 [stripe] Report metrics from client calls in Go
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/stripe/reporter.go
  components/usage/pkg/stripe/stripe.go
Labels: size/M, team: webapp, release-note-none

#13605 [ws-daemon] Stop logging cpu limit error
  components/ws-daemon/pkg/cpulimit/cfs.go
  components/ws-daemon/pkg/cpulimit/dispatch.go
Labels: size/XS, team: workspace, release-note-none

#13613 [server] Fix network connections not limited
  components/server/ee/src/billing/entitlement-service-chargebee.ts
Labels: size/XS, team: webapp, team: workspace, release-note-none

#13607 chore(gitpod-cli): Update top table output format
  components/gitpod-cli/cmd/top.go
Labels: size/M, team: IDE, release-note

#13614 [stripe] Add tests for ReconcileInvoices
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/db/dbtest/cost_center.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: webapp, release-note-none

#13533 [installer-tests] Cleanup secret creation on Gitpod install
  install/tests/Makefile
Labels: size/M, release-note-none, team: self-hosted

#13625 [ws-daemon] Adjust SignedURL expiration
  components/content-service/pkg/storage/gcloud.go
Labels: size/XS, team: workspace, release-note-none

#13624 [ws-daemon] Improve download options
  components/ws-daemon/pkg/content/initializer.go
Labels: size/XS, team: workspace, release-note-none

#13552 [pvc] fix when opening repo with no .gitpod.yml
  components/content-service/pkg/layer/provider.go
Labels: size/M, team: workspace, release-note-none

#13593 [pvc] add a test for non gitpodified repo
  test/tests/components/ws-manager/content_test.go
Labels: size/XS, release-note-none

#13619 Update tf version in docker image
  .gitpod.yml
  .werft/aks-installer-tests.yaml
  .werft/build.yaml
  .werft/cleanup-installer-tests.yaml
  .werft/debug.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/ide-integration-tests-startup.yaml
  .werft/k3s-installer-tests.yaml
  .werft/platform-delete-preview-environment.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/image/Dockerfile
Labels: size/S, team: workspace, team: IDE, release-note-none, team: platform, team: self-hosted

#13630 [installer-tests] disable npm version update notice
  .werft/aks-installer-tests.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/k3s-installer-tests.yaml
Labels: size/XS, release-note-none, team: self-hosted

#13629 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#13602 [usage] Switch codegen of Go proto/grpc to buf
  components/usage-api/buf.gen.yaml
  components/usage-api/generate.sh
  components/usage-api/go.mod
  components/usage-api/go.sum
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/tools.go
Labels: size/M, team: webapp, release-note-none

#13640 [dashboard] Don't double-encapsulate Alert contents in <span/> or <p/>
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/ErrorMessage.tsx
  components/dashboard/src/projects/Projects.tsx
Labels: size/S, team: webapp, release-note-none

#13643 [db] Stop writing to the `uid` field of the `d_b_oauth_auth_code_entry` table
  components/gitpod-db/src/typeorm/auth-code-repository-db.ts
Labels: size/XS, team: webapp, release-note-none

#13534 [server] Throw specific errors when interacting with teams
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: size/M, team: webapp, release-note-none

#13646 [usage] Use buf for ts_proto plugin codegen
  components/usage-api/buf.gen.yaml
  components/usage-api/generate.sh
Labels: size/S, team: webapp, release-note-none

#13649 [db] Reset primary keys in `d_b_oauth_auth_code_entry`
  components/gitpod-db/src/typeorm/migration/1665062302891-ResetAuthCodePrimaryKeys.ts
Labels: size/S, team: webapp, release-note-none

#13647 [metric] Add Prometheus metric for instances marked as stopped
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/S, team: webapp, release-note-none

#13645 [server] Report Stripe client metrics
  components/server/ee/src/user/stripe-service.ts
  components/server/src/prometheus-metrics.ts
Labels: size/L, team: webapp, release-note-none

#13655 Revert "ws-manager: remove PVC object if the workspace pod fails to up"
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#13652 Check if preview cert is ready before trying to create/destroy it
  .werft/util/certs.ts
Labels: size/S, release-note-none, team: platform

#13664 [installer] enable protected_secrets by default
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, release-note, team: self-hosted

#13657 Update gradle plugins from JetBrains Backend-Plugin
  components/ide/jetbrains/backend-plugin/build.gradle.kts
Labels: size/XS, team: IDE, release-note-none

#13599 [db-sync] Add `d_b_oauth_auth_code_entry` to db-sync
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note-none

#13612 Add missing Gitpod configurations for RubyMine and WebStorm
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/src/protocol.ts
  components/ide/jetbrains/backend-plugin/hot-deploy.sh
  components/server/src/ide-service.ts
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/M, team: webapp, team: IDE, release-note-none

#13644 [db] Drop `uid` column on `d_b_oauth_auth_code_entry`
  components/gitpod-db/src/typeorm/migration/1665054816691-RemoveUidFieldFromAuthCodeTable.ts
Labels: do-not-merge/hold, size/S, team: webapp, release-note-none

#13659 [usage] Add GetStripeCustomer to BillingService
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/usage/v1/billing.proto
Labels: size/L, team: webapp, release-note-none

#13495 [supervisor] shutdown processes gracefully
  components/common-go/process/process.go
  components/common-go/process/process_test.go
  components/supervisor/cmd/init.go
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/terminal/service.go
  components/supervisor/pkg/terminal/terminal.go
  components/supervisor/pkg/terminal/terminal_test.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note

#13667 [stripe] Implement BillingService.GetStripeCustomer
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/M, team: webapp, release-note-none

#13681 [db] Remove `uid` field from entity
  components/gitpod-db/src/typeorm/entity/db-oauth-auth-code.ts
Labels: size/XS, team: webapp, release-note-none

#13669 [server] Use BillingService.GetStripeCustomer to fetch customer
  components/server/ee/src/user/stripe-service.ts
Labels: size/S, team: webapp, release-note-none

#13660 chore: add jetbrains label to automated PRs
  .github/workflows/jetbrains-updates-template.yml
Labels: size/XS, team: IDE, editor: jetbrains

#13617 Build stable image for VS Code Browser 1.72
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, release-note

#13687 Update stable to `1.72.0`
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#13690 [server] don't rely on stripe for billingmode
  components/server/ee/src/billing/billing-mode.ts
Labels: size/S, team: webapp, release-note-none

#13699 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#13694 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#13670 Fix indentation so nodeAffinity is used
  .werft/aks-installer-tests.yaml
  .werft/cleanup-installer-tests.yaml
  .werft/eks-installer-tests.yaml
  .werft/k3s-installer-tests.yaml
Labels: size/M, release-note-none, team: delivery, team: self-hosted

#13671 [grafana] Add Grafana panel for instances_marked_stopped
  operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
Labels: size/XXL, team: webapp, release-note-none

#13705 [server] Remove fallback to search for stripe customers
  components/server/ee/src/user/stripe-service.ts
Labels: size/S, team: webapp, release-note-none

#13709 Delete cordoned node once it's empty during werft cleanup
  .werft/platform-trigger-werft-cleanup.sh
Labels: size/S, release-note-none, team: platform

#13717 [server] openPort maps ResourceExhausted from ws-man to TooManyRequests
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#13713 [server] Garbage collect probe workspaces
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/workspace/garbage-collector.ts
Labels: size/M, team: webapp, release-note-none

#13693 [public-api] Authentication interceptors for connect API
  components/public-api-server/go.sum
  components/public-api-server/pkg/auth/auth.go
  components/public-api-server/pkg/auth/auth_test.go
  components/public-api-server/pkg/auth/context.go
  components/public-api-server/pkg/auth/context_test.go
  components/public-api-server/pkg/auth/middleware.go
  components/public-api-server/pkg/auth/middleware_test.go
  components/public-api-server/pkg/server/integration_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/XL, team: webapp, release-note-none

#13725 Update `code-nightly.yml` to pull from `gp-code/main` again
  .github/workflows/code-nightly.yaml
Labels: editor: code (browser), size/XS, release-note-none

#13738 [content-service] Remove usage.proto - unused
  components/content-service-api/go/usage.pb.go
  components/content-service-api/go/usage_grpc.pb.go
  components/content-service-api/typescript/src/usage_grpc_pb.d.ts
  components/content-service-api/typescript/src/usage_grpc_pb.js
  components/content-service-api/typescript/src/usage_pb.d.ts
  components/content-service-api/typescript/src/usage_pb.js
  components/content-service-api/usage.proto
Labels: size/M, team: workspace, release-note-none

#13711 [obs] Remove NetworkConnectionsTooHigh alert
  operations/observability/mixins/workspace/rules/nodes.yaml
Labels: size/S, team: workspace, release-note-none

#13702 [gp-cli] remove unused code
  components/gitpod-cli/cmd/open.go
  components/gitpod-cli/cmd/preview.go
  components/gitpod-cli/pkg/supervisor-helper/supervisor.go
  components/gitpod-cli/pkg/theialib/mock.go
  components/gitpod-cli/pkg/theialib/protocol.go
  components/gitpod-cli/pkg/theialib/service.go
Labels: size/XXL, team: IDE, release-note-none

#13744 [server] Disallow removing all Owners from a team
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: size/S, team: webapp, release-note

#13724 Add a lock timeout for plan/apply and general timeout on apply
  dev/preview/workflow/lib/terraform.sh
Labels: size/S, release-note-none, team: platform

#13755 [server] Fix typo in probe workspaces search
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/XS, team: webapp, release-note-none

#13701 [usage] Report Stripe metrics without full request path
  components/usage/pkg/stripe/reporter.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: webapp, release-note-none

#13728 Add option to add authentication to Jaeger and custom tags
  install/installer/pkg/common/common.go
  install/installer/pkg/components/agent-smith/daemonset.go
  install/installer/pkg/components/blobserve/deployment.go
  install/installer/pkg/components/content-service/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
  install/installer/pkg/config/v1/config.go
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note, team: self-hosted

#13704 [server] Use CostCenter to determine if user has paid subscription
  components/server/ee/src/billing/entitlement-service-ubp.ts
Labels: size/S, team: webapp, release-note-none

#13762 Rename Self-Hosted Team in CODEOWNERS
  .github/CODEOWNERS
Labels: size/S, release-note-none, team: delivery-operations-experience

#13763 add servicemonitors for argocd
  operations/observability/mixins/platform/rules/argocd/servicemonitor.yaml
Labels: size/M, release-note-none, team: platform

#13718 Add leeway dev/preview:build and dev/preview:deploy-gitpod
  dev/preview/BUILD.yaml
  dev/preview/workflow/lib/ensure-gcloud-auth.sh
  dev/preview/workflow/preview/build.sh
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, release-note-none, team: platform

#13449 [supervisor] local exposed
  components/supervisor/pkg/ports/exposed-ports.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: IDE, release-note-none

#13781 [installer/tests] upload diagnostics when installation fails
  install/tests/Makefile
Labels: size/S, release-note-none, team: delivery-operations-experience

#13780 [installer-tests] fixup werft major phase naming, messaging
  .werft/installer-tests.ts
Labels: size/S, release-note-none, team: delivery-operations-experience

#13783 Build images for 1.72.1
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#13760 Skip "MountVolume.MountDevice failed for volume"
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/status.go
Labels: size/S, team: workspace, release-note-none

#13784 Update stable to `1.72.1`
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), team: IDE, release-note-none

#13756 [Future Preview Environments] Terraform Certificates
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/prepare.ts
  .werft/util/certs.ts
  .werft/vm/vm.ts
  dev/preview/infrastructure/harvester/cert.tf
  dev/preview/infrastructure/harvester/provider.tf
Labels: size/L, release-note-none, team: platform

#13665 [self-hosted-preview] Support version specification in preview
  .werft/jobs/build/job-config.ts
  .werft/jobs/build/self-hosted-upgrade-tests.ts
  install/tests/Makefile
Labels: size/M, release-note-none, team: delivery, team: self-hosted

#13775 [Future Preview Environments] Use TF to create DNS records
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/prepare.ts
  .werft/platform-delete-preview-environment.ts
  .werft/util/certs.ts
  .werft/util/gcloud.ts
  .werft/util/preview.ts
  .werft/vm/vm.ts
  dev/preview/infrastructure/harvester/dns.tf
  dev/preview/infrastructure/harvester/provider.tf
  dev/preview/infrastructure/harvester/svc.tf
  dev/preview/infrastructure/harvester/variables.tf
Labels: size/XL, release-note-none, team: platform

#13791 [usage] Return CostCenter from UsageService.SetCostCenter protos
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
  components/usage-api/usage/v1/usage.proto
Labels: size/S, team: webapp, release-note-none

#13795 [Preview env] Fix cert recreation
  .werft/util/certs.ts
  dev/preview/infrastructure/harvester/variables.tf
Labels: size/M, release-note-none, team: platform

#13748 Fix preview name prefix
  .werft/util/preview.ts
Labels: size/XS, release-note-none, team: platform

#13736 [public-api] Refactor to use connect handlers, route to HTTP server
  components/proxy/conf/Caddyfile
  components/public-api-server/pkg/apiv1/prebuild.go
  components/public-api-server/pkg/apiv1/prebuild_test.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/proxy/errors.go
  components/public-api-server/pkg/proxy/errors_test.go
  components/public-api-server/pkg/server/integration_test.go
  components/public-api-server/pkg/server/server.go
  dev/gpctl/cmd/public-api.go
Labels: size/XL, team: webapp, team: workspace, release-note-none

#13796 loadgen: support custom workspace timeout
  dev/loadgen/README.md
  dev/loadgen/cmd/benchmark.go
  dev/loadgen/configs/prod-benchmark-pvc.yaml
  dev/loadgen/configs/prod-benchmark.yaml
  dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml
  dev/loadgen/configs/workspace-preview-benchmark.yaml
Labels: size/S, team: workspace, release-note-none

#13803 [preview] Include with-payment in default configuration
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
Labels: size/M, team: webapp, release-note-none

#13799 [codeowners] Make WebApp codeowners of ws-manager-bridge-api
  .github/CODEOWNERS
Labels: size/XS, team: webapp, release-note-none

#13561 [terraform] prepare terraform modules to use for tests
  install/infra/modules/aks/local.tf
  install/infra/modules/aks/output.tf
  install/infra/modules/eks/local.tf
  install/infra/modules/eks/output.tf
  install/infra/modules/eks/providers.tf
  install/infra/modules/eks/variables.tf
  install/infra/modules/tools/cloud-dns-ns/main.tf
  install/infra/single-cluster/aws/output.tf
  install/infra/single-cluster/azure/cluster.tf
  install/infra/single-cluster/azure/output.tf
  install/infra/single-cluster/gcp/cluster.tf
  install/infra/single-cluster/gcp/output.tf
  install/infra/single-cluster/gcp/terraform.tfvars
  install/infra/single-cluster/gcp/tools.tf
  install/tests/main.tf
Labels: size/L, release-note-none, team: delivery

#13808 Re-add default value for storage class
  dev/preview/infrastructure/harvester/variables.tf
Labels: size/XS, release-note-none, team: platform

#13739 [content-service] Use buf to generate protos
  components/content-service-api/buf.gen.yaml
  components/content-service-api/buf.yaml
  components/content-service-api/generate.sh
  components/content-service-api/go/blobs.pb.go
  components/content-service-api/go/blobs_grpc.pb.go
  components/content-service-api/go/content.pb.go
  components/content-service-api/go/content_grpc.pb.go
  components/content-service-api/go/headless-log.pb.go
  components/content-service-api/go/headless-log_grpc.pb.go
  components/content-service-api/go/ideplugin.pb.go
  components/content-service-api/go/ideplugin_grpc.pb.go
  components/content-service-api/go/initializer.pb.go
  components/content-service-api/go/workspace.pb.go
  components/content-service-api/go/workspace_grpc.pb.go
  components/gitpod-protocol/src/wsready.ts
Labels: size/M, team: webapp, team: workspace, release-note-none

#13743 [proxy] Enable CORS for api.<domain> from https://<domain> origin
  components/proxy/conf/Caddyfile
  components/proxy/plugins/corsorigin/cors_origin.go
Labels: size/M, team: webapp, release-note-none

#13651 [installer-tests] Splitting the integration tests
  .werft/installer-tests.ts
  install/tests/tests.sh
Labels: size/M, release-note-none, team: platform, team: delivery, team: self-hosted, team: delivery-operations-experience

#13816 [installer-tests] dump config at start of test
  .werft/installer-tests.ts
Labels: size/S, release-note-none, team: delivery-operations-experience

#13746 [Usage-based] Adjust Stripe usage limits to spec
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#13813 feat(gateway-plugin): allow spearate builds for stable and latest
  .github/workflows/jetbrains-update-plugin-platform.yml
  .gitpod.yml
  components/BUILD.yaml
  components/ide/jetbrains/gateway-plugin/.gitignore
  components/ide/jetbrains/gateway-plugin/BUILD.yaml
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  components/ide/jetbrains/gateway-plugin/gradle.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectorView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnector.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnectorView.kt
  components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: IDE, release-note-none, editor: jetbrains

#13798 [usage] Validate spending limits in UpdateCostCenter
  .werft/jobs/build/installer/installer.ts
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/db/cost_center.go
  components/usage/pkg/db/cost_center_test.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/XL, team: webapp, release-note-none

#13839 Adjust IDE alerts to work with centralized alerting
  operations/observability/mixins/IDE/rules/opensvx.yaml
Labels: team: IDE

#13823 Drain, delete, and uncordon node on cleanup
  .werft/platform-trigger-werft-cleanup.sh
Labels: size/XS, release-note-none, team: platform

#13838 [code] build stable code image to bring responsive PortsView
  WORKSPACE.yaml
Labels: size/XS, release-note

#13747 Fix the auto-port-forwarding on JetBrains EAP IDEs
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
Labels: size/L, team: IDE, release-note, editor: jetbrains

#13844 [code] fix portsView address open twice #13778
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#13627 [werft] Implement log streaming for subprocesses
  .werft/installer-tests.ts
  .werft/util/shell.ts
Labels: aspect: testing, size/L, release-note-none, team: delivery

#13752 feat(gitpod-cli): report errors to ide-metrics-api
  components/gitpod-cli/BUILD.yaml
  components/gitpod-cli/cmd/info.go
  components/gitpod-cli/cmd/ports-list.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/gitpod-cli/pkg/supervisor-helper/info.go
  components/gitpod-cli/pkg/utils/logError.go
  components/ide-metrics-api/go/idemetrics.pb.go
  components/ide-metrics-api/go/idemetrics.pb.gw.go
  components/ide-metrics-api/java/src/main/java/io/gitpod/idemetrics/api/MetricsServiceGrpc.java
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/L, team: IDE, release-note-none

#13848 Increase vscode test timeout
  test/tests/ide/vscode/python_ws_test.go
Labels: size/XS, team: IDE, release-note-none

#13820 obs: fix new workspace does not shown workspace success rate
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/XS, team: workspace, release-note-none

#13821 ws-manager: `NODE_EXTRA_CA_CERTS` is the value of the gitpod internals
  components/ws-manager/pkg/manager/create.go
Labels: size/XS, team: workspace, release-note

#13855 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#13841 [server] Deprecate AdditionalContentPrefixContextParser
  components/server/src/container-module.ts
  components/server/src/workspace/additional-content-prefix-context-parser.ts
Labels: size/M, team: webapp, release-note

#13857 Replace ¢ -> $ and Balance -> Balance Used
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/S, team: webapp, release-note-none

#13853 Build stable images for `1.72.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#13860 Update stable to `1.72.2`
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#13859 [configcat] Do not supply lists to configcat evaluations
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/gitpod-protocol/src/experiments/configcat.ts
  components/gitpod-protocol/src/experiments/types.ts
  components/server/ee/src/billing/billing-mode.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, release-note-none

#13768 [prebuild] Support opening a specfic prebuild
  components/dashboard/src/projects/Prebuild.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/container-module.ts
  components/server/src/workspace/open-prebuild-prefix-context-parser.ts
Labels: size/M, team: webapp, release-note

#13876 Add a Prometheus alert rule for SSH Gateway
  operations/observability/mixins/IDE/rules/ssh-gateway.yaml
Labels: operations: observability, size/S, team: IDE, release-note-none

#13883 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#13542 [installer-tests] Use reference architecture to run integration tests
  .werft/installer-tests.ts
  install/infra/modules/k3s/main.tf
  install/infra/modules/k3s/output.tf
  install/tests/Makefile
  install/tests/manifests/aws-terraform.tfvars
  install/tests/manifests/azure-terraform.tfvars
  install/tests/manifests/gcp-terraform.tfvars
  install/tests/manifests/k3s-terraform.tfvars
  install/tests/manifests/managed-dns.tf
  install/tests/manifests/tf-backend.tf
Labels: size/XXL, release-note-none, team: delivery

#13888 [usage] Check UBP even without any teams
  components/server/ee/src/billing/billing-mode.ts
Labels: size/M, team: webapp, release-note-none
