Repository gitpod-io/gitpod, pull requests merged in 2022-06, with the labels that each got.

#10229 [content-service] enable public read on gitpod repo root folder
  components/content-service/pkg/initializer/git.go
Labels: size/XS, team: workspace, team: IDE, release-note

#10394 dashboard: connect via ssh devx improvement
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
Labels: size/XS, team: webapp, release-note

#10400 [workspace-instance] Deprecate deployedTime field
  components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: size/XS, team: webapp, release-note

#10372 content-service: ignore the error of `user.overlay.(impure|origin)` attributes
  components/content-service/pkg/archive/tar.go
Labels: size/S, team: workspace, release-note

#10249 [usage] Setup controller and reconciler
  components/usage/cmd/run.go
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/controller/controller.go
  components/usage/pkg/controller/controller_test.go
  components/usage/pkg/controller/reconciler.go
Labels: size/L, team: webapp, release-note-none

#10388 [gitpod-cli] Add command 'gp ports list'
  components/gitpod-cli/cmd/ports.go
  components/gitpod-cli/cmd/ports/ports-list.go
  components/gitpod-cli/pkg/supervisor/ports.go
Labels: component: gp cli, size/L, team: IDE, release-note

#10371 [usage] Add database-waiter
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/usage/objects_test.go
Labels: size/XS, team: webapp, release-note-none

#10370 [db][payment][server] Implement TeamSubscription2.excludeFromMoreResources
  components/ee/payment-endpoint/src/chargebee/team-subscription-handler.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/entity/db-team-subscription-2.ts
  components/gitpod-db/src/typeorm/migration/1653983151212-TS2MoreResources.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/team-subscription-protocol.ts
  components/server/ee/src/user/eligibility-service.ts
Labels: size/M, team: webapp, release-note-none

#10382 [observability] Add SLI numbers to the Workspace Success Criteria Dashboard
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/L, team: workspace, release-note-none

#9759 [kots]: add database to preflight checks
  components/BUILD.yaml
  components/kots-config-check/database/BUILD.yaml
  components/kots-config-check/database/entrypoint.sh
  components/kots-config-check/database/leeway.Dockerfile
  install/kots/manifests/kots-preflight.yaml
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/L, release-note, team: self-hosted

#10407 Fix 'gateway-plugin' not being detected as a project
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  .idea/modules.xml
Labels: size/M, team: IDE, release-note-none, editor: jetbrains

#10266 [image-builder-bob] Introduce URL processing for non docker api urls
  components/image-builder-bob/pkg/proxy/proxy.go
  components/image-builder-bob/pkg/proxy/proxy_test.go
Labels: size/L, team: workspace, release-note

#10401 [gpctl] Fix parsing error when running `gpctl workspaces describe <instanceID>`
  dev/gpctl/cmd/workspaces-describe.go
Labels: size/XS, team: workspace, release-note

#10413 [supervisor] improve error message around user group and uid
  components/supervisor/pkg/supervisor/user.go
  components/supervisor/pkg/supervisor/user_test.go
Labels: size/XS, team: IDE, release-note

#10416 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#10424 [server] Make Stripe settings optional even when payment is enabled
  components/server/src/config.ts
Labels: size/XS, team: webapp, release-note-none

#10421 [bridge] Cleanup dead "probe" code (1/3)
  components/ws-manager-bridge/ee/src/bridge.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: size/M, team: webapp, release-note-none

#10429 [baseserver] Stop logging healthcheck RPCs Redux
  components/common-go/baseserver/server.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10425 [bridge] Extracting updating of prebuilds into PrebuildUpdater (2/3)
  components/ws-manager-bridge/ee/src/container-module.ts
  components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
Labels: size/M, team: webapp, release-note-none

#10390 [usage] Harden parsing of time from VarChar field
  components/usage/pkg/db/types.go
  components/usage/pkg/db/types_test.go
Labels: size/L, release-note-none

#10367 [usage] Add db.WorkspaceInstance model in golang
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
  components/usage/pkg/db/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#10412 Add previewctl/gpctl autocompletion to workspace image
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup-jetbrains.yaml
  .werft/ide-integration-tests-startup-vscode.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/BUILD.yaml
  dev/image/BUILD.yaml
  dev/image/Dockerfile
  dev/leeway.Dockerfile
Labels: size/M, team: workspace, team: IDE, release-note-none, team: platform

#10438 Remove X-Server from Dev-Image
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/ide-integration-tests-startup-jetbrains.yaml
  .werft/ide-integration-tests-startup-vscode.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/image/Dockerfile
Labels: size/S, team: workspace, team: IDE, release-note-none, team: platform

#10443 Simplify configuration of KubeRBACProxyContainerWithConfig and remove collision
  components/common-go/baseserver/server.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-manager/deployment.go
Labels: size/M, team: webapp, team: workspace, release-note, team: self-hosted

#10458 [docker-up] Update docker compose to v2.6.0
  components/docker-up/BUILD.yaml
Labels: size/XS, team: workspace, release-note

#10445 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10423 Fix runbook URL
  operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Labels: size/XS, team: workspace, release-note-none

#10469 [docker-up] Check docker-compose download
  components/docker-up/BUILD.yaml
Labels: size/XS, team: workspace, release-note

#10478 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10436 [previewctl] Improve logging
  dev/preview/previewctl/cmd/get_name.go
  dev/preview/previewctl/cmd/install_context.go
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/go.mod
  dev/preview/previewctl/go.sum
  dev/preview/previewctl/main.go
  dev/preview/previewctl/pkg/preview/preview.go
Labels: size/M, release-note-none, team: platform

#10342 Add metrics to record backup/restore success/failure count
  components/ws-manager/pkg/manager/metrics.go
  components/ws-manager/pkg/manager/monitor.go
Labels: size/M, team: workspace, release-note

#10489 [code] point code nightly to gp-code/release/1.68 branch
  .github/workflows/code-nightly.yaml
Labels: editor: code (browser), team: IDE, release-note-none

#10471 [installer] Update kube-rbac-proxy to v0.12.0
  install/installer/pkg/common/constants.go
Labels: release-note, team: self-hosted

#10441 [kots] Add --use-experimental-config to installer render call
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note-none, team: self-hosted

#10309 Update dashboard navigation
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/PillMenuItem.tsx
  components/dashboard/src/icons/CaretUpDown.svg
Labels: size/L, team: webapp, release-note

#10475 Update sigs.k8s.io/e2e-framework to v0.0.7
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/supervisor-api/go.mod
  components/supervisor-api/go.sum
  components/supervisor/go.sum
  components/usage/go.mod
  components/usage/go.sum
  components/ws-manager-api/go.mod
  components/ws-manager-api/go.sum
  components/ws-proxy/go.mod
  components/ws-proxy/go.sum
  test/go.mod
  test/go.sum
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note

#10466 Update to new stable alpine version v3.16
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/supervisor/openssh/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager/debug.Dockerfile
  components/ws-manager/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  dev/poolkeeper/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note, team: self-hosted

#10457 [usage] Log db with standard logger
  components/usage/pkg/db/conn.go
Labels: size/S, team: webapp, release-note-none

#10490 [usage] Handle empty value varchar time, use ISO8601
  components/usage/pkg/db/types.go
  components/usage/pkg/db/types_test.go
Labels: size/L, team: webapp, release-note-none

#10480 [usage] Automatically cleanup records between test DB connections
  components/usage/pkg/db/conn.go
  components/usage/pkg/db/project_test.go
  components/usage/pkg/db/workspace_instance_test.go
  components/usage/pkg/db/workspace_test.go
Labels: size/M, team: webapp, release-note-none

#10456 [usage] List workspace instances
  components/usage/cmd/run.go
  components/usage/go.mod
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/db/conn_test.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/L, team: webapp, release-note-none

#10492 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10504 Update docs link in user menu
  components/dashboard/src/Menu.tsx
Labels: size/XS, team: webapp, release-note-none

#10505 Fix JetBrains Gateway Plugin to work on v222.2889.2
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/XS, team: IDE, release-note, editor: jetbrains

#10517 Revert "Always keep preview envs on db activity"
  .werft/platform-delete-preview-environments-cron.ts
Labels: size/XS, team: platform

#10511 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10483 [usage] Validate workspace instances in reconciler
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/L, release-note-none

#10528 [usage] Add db model for TeamMembership
  components/usage/pkg/db/conn.go
  components/usage/pkg/db/team_membership.go
  components/usage/pkg/db/team_membership_test.go
Labels: size/M, team: webapp, release-note-none

#10518 Configure grpc_server histogram metrics with proper buckets
  components/common-go/baseserver/server.go
  components/ws-manager/cmd/run.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10519 ws-daemon: Soft limit of the xfs at first to ensure that the contents can be restored
  components/ws-daemon/pkg/content/hooks.go
  components/ws-daemon/pkg/quota/xfs.go
  components/ws-daemon/pkg/quota/xfs_test.go
Labels: size/M, team: workspace, release-note

#10148 [gitlab] get rid of UnhandledPromiseRejectionWarning
  components/server/ee/src/prebuilds/gitlab-app.ts
Labels: size/M, team: webapp, release-note

#9939 [kots]: add storage to preflight checks
  components/BUILD.yaml
  components/kots-config-check/storage/BUILD.yaml
  components/kots-config-check/storage/entrypoint.sh
  components/kots-config-check/storage/leeway.Dockerfile
  install/kots/manifests/kots-preflight.yaml
  install/kots/manifests/kots-support-bundle.yaml
Labels: size/L, release-note, team: self-hosted

#10491 [content-service] show error if failed to download backup file
  components/content-service/pkg/initializer/initializer.go
Labels: size/XS, team: workspace, release-note

#10495 [usage] List workspaces for each workspace instance in usage period
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/dbtest/workspace.go
  components/usage/pkg/db/workspace.go
  components/usage/pkg/db/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#10435 [prebuilds] add metrics for prebuilds 10383
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/prometheus-metrics.ts
  components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/M, team: webapp, release-note-none

#10546 [usage] Simplify Workspace record creation for tests
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/dbtest/workspace.go
  components/usage/pkg/db/workspace.go
  components/usage/pkg/db/workspace_test.go
Labels: size/M, team: webapp, release-note-none

#10547 [usage] Add listing of memberships by UserID
  components/usage/pkg/db/team_membership.go
  components/usage/pkg/db/team_membership_test.go
Labels: size/M, team: webapp, release-note-none

#10540 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10535 Update preview environment dashboard
  operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Labels: size/M, release-note-none, team: platform

#10520 [server] Introduce and use a ErrorCodes.INTERNAL_SERVER_ERROR
  components/gitpod-protocol/src/messaging/error.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/S, team: webapp, release-note-none

#10450 [dashboard] Move inactive workspaces out of sight
  components/dashboard/src/components/Arrow.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/workspace-model.ts
  components/gitpod-protocol/src/util/timeutil.ts
Labels: size/L, team: webapp, release-note

#10556 Fix registry facade not being able to start up in preview environment
  .werft/util/certs.ts
Labels: size/XS, team: workspace, release-note-none

#10554 Minor Stripe API clean-up
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#10562 Add workspace class to workspace environment variables
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/testdata/cdwp_class.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class_notfound.golden
Labels: size/XS, team: workspace, release-note

#10567 [code]: Generate stable images for 1.68
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#10555 Implement Stripe portal to allow usage-based customers to manage their billing details
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/user/stripe-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#10568 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10551 [usage] Generate usage report
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/workspace_instance.go
Labels: size/L, team: webapp, release-note-none

#10589 [code] Generate stable images for 1.68
  WORKSPACE.yaml
Labels: size/XS, release-note-none

#10571 [code] Update stable to 1.68
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#10585 [loadgen] Wait before workspace termination
  dev/loadgen/README.md
  dev/loadgen/cmd/benchmark.go
Labels: size/S, team: workspace, release-note-none

#10601 [code] revert stable image to 1.67
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#10602 [ws-manager] change log from debug to error
  components/ws-manager/pkg/manager/status.go
Labels: size/XS, team: workspace, release-note-none

#10596 Refactor 'normalizedContextURL' property from Java class 'WorkspaceContext' as Optional
  components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceContext.java
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#10594 Use `xterm-256color` when creating terminal
  components/supervisor/pkg/terminal/service.go
Labels: size/XS, team: IDE, release-note-none

#10604 Revert "[werft]: disable publish to kots on main build"
  .werft/jobs/build/job-config.ts
Labels: size/XS, release-note, team: self-hosted

#10582 [kots]: move the openssh installation to the container image
  install/installer/leeway.Dockerfile
  install/kots/manifests/gitpod-installation-status.yaml
  install/kots/manifests/gitpod-installer-job.yaml
Labels: size/XS, release-note, team: self-hosted

#10618 loadgen: fix the error handling when failed to get the ws infomation.
  dev/loadgen/pkg/loadgen/executor.go
Labels: size/S, team: workspace, release-note-none

#10619 [gp-cli] add command to extend workspace timeout
  components/gitpod-cli/cmd/timeout-extend.go
  components/gitpod-cli/cmd/timeout.go
  components/gitpod-protocol/go/error.go
Labels: size/L, team: IDE, release-note

#10591 [usage] Round workspace runtime
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/workspace_instance.go
Labels: size/S, team: webapp, release-note-none

#10640 [ws-manager] Make sure volume restore time is accurate
  components/ws-manager/pkg/manager/manager.go
Labels: team: workspace, release-note-none

#10634 Add probe metrics to preview environment
  .werft/observability/monitoring-satellite.ts
Labels: size/XS, release-note-none, team: platform

#10636 werft/build: Rename created_vm span attribute
  .werft/jobs/build/prepare.ts
Labels: size/XS, release-note-none, team: platform

#10597 [ws-manager] change workspace state tracing
  components/common-go/kubernetes/kubernetes.go
  components/ws-manager/pkg/manager/create.go
  components/ws-manager/pkg/manager/imagespec.go
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/monitor.go
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_firstUserActivity_RUNNING.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_imagespec_RUNNING00.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_interrupted_networkNotReady_1_event_only.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_interrupted_networkNotReady_3_recovered_CONSTRUCTED.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_metadata.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_ownerToken.golden
  components/ws-manager/pkg/manager/testdata/actOnPodEvent_stoppedByRequest_000_RUNNING00.golden
  components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
  components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class.golden
  components/ws-manager/pkg/manager/testdata/cdwp_class_notfound.golden
  components/ws-manager/pkg/manager/testdata/cdwp_customcerts.golden
  components/ws-manager/pkg/manager/testdata/cdwp_debug_workspace_pod.golden
  components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
  components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fixedresources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
  components/ws-manager/pkg/manager/testdata/cdwp_probe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
  components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
  components/ws-manager/pkg/manager/testdata/cdwp_template.golden
  components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
  components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
  components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden
  components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
Labels: size/L, team: webapp, team: workspace, release-note-none

#10641 [ws-manager] Increase restore counter only if it's restoring from the Backup/VolumeSnapshot
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#10631 Mount Stripe API keys into the usage component
  install/installer/pkg/components/usage/constants.go
  install/installer/pkg/components/usage/deployment.go
Labels: size/M, team: webapp, release-note-none

#10539 Add persistent volume claim to prebuild settings
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
Labels: size/M, team: webapp, release-note-none

#10654 [Analytics] Remove PII from deleted Users
  components/server/src/user/user-deletion-service.ts
Labels: size/S, team: webapp, release-note-none

#10670 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/S, release-note-none, lgtm

#10673 Remove deprecated function
  components/gitpod-cli/cmd/credential-helper.go
  components/gitpod-cli/cmd/env.go
  components/gitpod-cli/cmd/git-token-validator.go
  components/gitpod-cli/pkg/gitpod/server.go
  components/ide/code-desktop/status/main.go
  components/ide/code/codehelper/main.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/local-app/pkg/bastion/bastion.go
  components/registry-facade/pkg/registry/registry.go
  components/supervisor/cmd/terminal.go
  components/supervisor/pkg/supervisor/notification.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/terminal/service.go
  components/workspacekit/cmd/rings.go
  components/ws-daemon/cmd/client.go
  components/ws-manager/cmd/run.go
  components/ws-manager/pkg/manager/integration_test.go
  components/ws-manager/pkg/manager/manager.go
  components/ws-proxy/cmd/run.go
  components/ws-proxy/pkg/sshproxy/server.go
  dev/gpctl/cmd/clusters.go
  dev/gpctl/cmd/imagebuilds.go
  dev/gpctl/cmd/workspaces.go
  dev/loadgen/cmd/benchmark.go
  dev/loadgen/cmd/run.go
  test/pkg/integration/apis.go
Labels: size/L, team: workspace, team: IDE, release-note-none

#10661 [prebuilds] make sure prebuild and branch commits are the same
  components/dashboard/src/projects/Project.tsx
Labels: size/S, team: webapp, release-note-none

#10537 [installer] support service type `ClusterIP` for proxy
  install/installer/pkg/components/proxy/service.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/v1/experimental/validation.go
Labels: size/M, team: webapp, release-note-none, team: self-hosted

#10668 Preview environments: Add extra external_labels to Prometheus
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/observability/monitoring-satellite.ts
Labels: size/XS, release-note-none, team: platform

#10646 Listen on instance updates of a running prebuild
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note

#10532 [self-hosted] Gitpod local preview install method
  components/BUILD.yaml
  install/preview/BUILD.yaml
  install/preview/README.md
  install/preview/entrypoint.sh
  install/preview/leeway.Dockerfile
  install/preview/manifests/messagebus.yaml
Labels: size/L, release-note, team: self-hosted

#10638 [GP CLI] Allow explicity and automated disabling of output colorization
  components/gitpod-cli/cmd/ports-list.go
  components/gitpod-cli/cmd/root.go
  components/gitpod-cli/cmd/tasks-list.go
  components/gitpod-cli/cmd/top.go
Labels: component: gp cli, size/S, team: IDE, release-note-none

#10690 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10558 [jb]: monitor low memory notifications
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  operations/observability/mixins/IDE/dashboards.libsonnet
  operations/observability/mixins/IDE/dashboards/components/jb.json
Labels: size/XL, team: IDE, release-note-none

#10678 Add `--schedule` flag to `usage run` command
  components/usage/cmd/run.go
Labels: size/XS, team: webapp, release-note-none

#10699 Remove critical alert GitpodWsDaemonExcessiveGC > 60s (but keep the non-critical warning for now)
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#10691 [code]: Generate stable images for 1.68.1
  WORKSPACE.yaml
Labels: size/XS, team: IDE, release-note-none

#10707 [code] Update stable to 1.68.1
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#10708 [code] point code nightly to gp-code/main branch
  .github/workflows/code-nightly.yaml
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#10711 [ws-manager] fix crash when restoring from volume snapshot
  components/ws-manager/pkg/manager/manager.go
Labels: size/XS, team: workspace, release-note-none

#10710 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10712 [jb] fix dashboard
  operations/observability/mixins/IDE/dashboards/components/jb.json
Labels: size/S, team: IDE, release-note-none

#10714 [jb] actually fix dashboard
  operations/observability/mixins/IDE/dashboards/components/jb.json
Labels: size/S, team: IDE, release-note-none

#10713 [billing] Create Stripe invoices for teams based on their usage
  components/usage/pkg/controller/reconciler.go
  components/usage/pkg/stripe/stripe.go
  components/usage/pkg/stripe/stripe_test.go
Labels: size/L, team: webapp, release-note-none

#10592 Update platform version from 'gateway-plugin' to target JetBrains Gateway v2022.2-Nightly
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle.properties
Labels: size/S, team: IDE, release-note-none, editor: jetbrains

#10723 [gp-cli] update timeout description
  components/gitpod-cli/cmd/timeout.go
Labels: size/XS, team: IDE, release-note

#10721 Change disk bus from scsi to virtio to gain performance
  .werft/vm/manifests.ts
Labels: size/XS, release-note-none, team: platform

#10746 Update gitpod-protocol deps
  components/gitpod-protocol/package.json
  yarn.lock
Labels: size/L, team: webapp, release-note-none

#10744 [ws-daemon] Fix quota size regex's false positives
  components/ws-daemon/pkg/quota/size.go
  components/ws-daemon/pkg/quota/size_test.go
Labels: size/XS, release-note

#10761 [werft] Delete unused file .werft/jobs/build/helm/values.payment.yaml
  .werft/jobs/build/helm/values.payment.yaml
Labels: size/S, release-note-none

#10755 Add text panel with link to Preview Start SLO
  operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Labels: size/M, release-note-none, team: platform

#10681 Opt-in preview environments
  .github/pull_request_template.md
  .werft/build.ts
  .werft/jobs/build/job-config.ts
  .werft/jobs/build/validate-changes.ts
  dev/changelog/pullrequest.go
Labels: size/M, release-note-none, team: platform

#10733 [content-service-api] add bool to snapshot intializer struct
  components/content-service-api/go/blobs.pb.go
  components/content-service-api/go/blobs_grpc.pb.go
  components/content-service-api/go/content.pb.go
  components/content-service-api/go/content_grpc.pb.go
  components/content-service-api/go/headless-log.pb.go
  components/content-service-api/go/headless-log_grpc.pb.go
  components/content-service-api/go/ideplugin.pb.go
  components/content-service-api/go/ideplugin_grpc.pb.go
  components/content-service-api/go/initializer.pb.go
  components/content-service-api/go/workspace.pb.go
  components/content-service-api/go/workspace_grpc.pb.go
  components/content-service-api/initializer.proto
  components/content-service-api/typescript/src/initializer_pb.d.ts
  components/content-service-api/typescript/src/initializer_pb.js
Labels: size/L, release-note-none

#10771 previewctl: Wrap shell script that list VMs
  dev/preview/list-vms.sh
  dev/preview/previewctl/cmd/list_previews.go
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/go.mod
  dev/preview/previewctl/go.sum
  dev/preview/previewctl/pkg/preview/preview.go
  dev/preview/previewctl/pkg/preview/preview_test.go
Labels: size/XXL, release-note-none, team: platform

#10776 call prestophook.sh from ring1 directly
  components/workspacekit/cmd/rings.go
  components/ws-manager/pkg/manager/create.go
Labels: size/S, team: workspace, release-note-none

#10758 [usage] Batch lookup Workspaces to fix too many placeholders error
  components/usage/go.mod
  components/usage/pkg/db/dbtest/workspace.go
  components/usage/pkg/db/workspace.go
  components/usage/pkg/db/workspace_test.go
Labels: size/M, team: webapp, release-note-none

#10778 [usage] Fix querying workspace instances to use startedTime existence to filter
  components/usage/pkg/controller/reconciler_test.go
  components/usage/pkg/db/dbtest/workspace_instance.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/L, team: webapp, release-note-none

#10730 update env to use werft grpc
  .gitpod.yml
  .werft/build.yaml
  .werft/debug.yaml
  .werft/gke-installer-tests.yaml
  .werft/ide-integration-tests-startup-jetbrains.yaml
  .werft/ide-integration-tests-startup-vscode.yaml
  .werft/ide-run-integration-tests.yaml
  .werft/platform-delete-preview-environments-cron.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  .werft/run-integration-tests.yaml
  .werft/wipe-devstaging.yaml
  .werft/workspace-run-integration-tests.yaml
  dev/image/Dockerfile
Labels: size/M, team: workspace, team: IDE, release-note-none, team: platform

#10685 [kots]: allow multiple docker pull secrets
  install/kots/manifests/gitpod-installer-job.yaml
  install/kots/manifests/gitpod-registry-secret.yaml
  install/kots/manifests/kots-config.yaml
Labels: size/M, release-note, team: self-hosted

#10789 [usage] Batch list workspace instances in range
  components/usage/pkg/db/dbtest/workspace_instance.go
  components/usage/pkg/db/workspace_instance.go
  components/usage/pkg/db/workspace_instance_test.go
Labels: size/M, team: webapp, release-note-none

#10774 previewctl: Add SSH command
  dev/preview/previewctl/cmd/root.go
  dev/preview/previewctl/cmd/ssh_vm.go
  dev/preview/previewctl/pkg/preview/preview.go
  dev/preview/ssh-vm.sh
Labels: size/M, release-note-none, team: platform

#10780 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10796 [supervisor] Make compatible with run-gp
  components/supervisor/cmd/run.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: IDE, release-note-none

#10800 Add SLIs to preview-environment dashboard
  operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Labels: size/XXL, release-note-none, team: platform

#10810 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10815 [usage] Do not run tests with SQL debug mode
  components/usage/pkg/db/conn.go
Labels: size/XS, team: webapp, release-note-none

#10737 previews: Remote-write metrics to core-dev
  .werft/build.yaml
  .werft/observability/monitoring-satellite.ts
Labels: size/S, release-note-none, team: platform

#10818 [usage] Fix flaky test for ListWorkspacesByID
  components/usage/pkg/db/workspace_test.go
Labels: size/S, team: webapp, release-note-none

#10821 [usage] Temporarily remove flaky test
  components/usage/pkg/db/workspace_test.go
Labels: size/S, team: webapp, release-note-none

#10775 Add tests for external dependencies in GCP
  .werft/installer-tests.ts
  install/infra/terraform/gke/main.tf
  install/infra/terraform/k3s/main.tf
  install/tests/Makefile
  install/tests/manifests/kots-config-gcp-db.yaml
  install/tests/manifests/kots-config-gcp-registry.yaml
  install/tests/manifests/kots-config-gcp-storage.yaml
Labels: size/L, release-note-none, team: self-hosted

#10688 [installation-telemetry] Add licenseType to sent telemetry
  components/gitpod-protocol/src/installation-admin-protocol.ts
  components/installation-telemetry/cmd/send.go
  components/installation-telemetry/pkg/server/installationAdmin.go
  components/server/src/installation-admin/telemetry-data-provider.ts
Labels: size/XS, team: webapp, release-note, team: self-hosted

#10830 Allow PRs for JetBrains IDEs updates to be created with a Preview Environment
  .github/workflows/jetbrains-updates-template.yml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#10837 [code] build stable image for 1.68.2 with port tunnel broken fix
  WORKSPACE.yaml
Labels: size/XS, release-note

#10838 [code] make 1.68.2 stable
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#10812 observability: Add GitpodWorkspaceTooLongTerminating alert.
  operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#10834 [server] Increase startWorkspace rate limit 1 → 3 starts per user per 10 seconds
  components/server/src/auth/rate-limiter.ts
Labels: size/XS, team: webapp, release-note-none

#10814 [dashboard] Fix checkboxes on project settings page
  components/dashboard/src/projects/ProjectSettings.tsx
Labels: size/S, team: webapp, release-note

#10865 [Self-Hosted] Changed preflight memory check error amount and reworded
  install/kots/manifests/kots-preflight.yaml
Labels: size/XS, release-note-none, team: self-hosted

#10855 observability: Ring the phone only when a data loss occurs with GitpodWsDaemonCrashLooping
  operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Labels: size/S, team: workspace, release-note-none

#10846 Trigger to bootstrap a preview environment in workspace integration test job
  .werft/workspace-run-integration-tests.yaml
Labels: size/XS, team: workspace, release-note-none

#10877 Assume that preview envs without `mysql-0` are not active.
  .werft/platform-delete-preview-environments-cron.ts
Labels: size/XS, release-note-none, team: platform

#10879 [supervisor] enabled SSH debug log by default
  components/supervisor/pkg/supervisor/ssh.go
Labels: size/XS, team: IDE, release-note-none

#10850 [installer] add `customCACert` volume to `ws-proxy`
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/L, team: workspace, release-note

#10888 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#10829 [installer] Move blobserve out workspace clusters
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/components-workspace/components.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#10794 Fix concurrent token renewal issues
  components/server/src/user/token-service.ts
Labels: size/S, team: webapp, release-note
