Repository gitpod-io/gitpod, pull requests merged in 2023-02, with the labels that each got.

#16140 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16142 [dashboard] unify usage
  components/dashboard/src/Menu.tsx
  components/dashboard/src/Usage.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/teams/TeamUsage.tsx
Labels: size/M, team: webapp, release-note-none

#16111 Update usage credits element
  components/dashboard/src/components/UsageView.tsx
Labels: size/XS, team: webapp, release-note-none

#16126 [spicedb] Add role & rolebinding to watch endpoints
  install/installer/pkg/components/spicedb/objects.go
  install/installer/pkg/components/spicedb/role.go
  install/installer/pkg/components/spicedb/rolebinding.go
Labels: size/M, team: webapp, release-note-none

#15976 [installer]: deprecate experimental IDE config
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/ide-config/config.yaml
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/pkg/components/ide-metrics/deployment.go
  install/installer/pkg/components/ide-proxy/service.go
  install/installer/pkg/components/ide-proxy/service_test.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/openvsx-proxy/service.go
  install/installer/pkg/components/openvsx-proxy/service_test.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/deprecations.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: IDE, release-note, team: delivery-operations-experience

#15889 [fix] : workspace options model closes on space
  components/dashboard/src/components/DropDown2.tsx
Labels: community-contribution, size/XS, team: webapp, release-note

#16134 Don't cancel previewctl builds on main
  .github/workflows/build.yml
Labels: size/XS, release-note-none

#16145 [spicedb] Basic organizations model
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/M, team: webapp, release-note-none

#16147 [proxy] Fix meta workspace-handler
  components/proxy/conf/workspace-handler.meta
Labels: size/XS, team: webapp, release-note-none

#16148 Introduce empty preview environment garbage collection job
  .github/workflows/preview-env-gc.yml
Labels: size/S, release-note-none

#16124 Run regression check after each successful main build
  .github/workflows/preview-env-check-regressions.yml
Labels: size/M, release-note-none

#16159 [jb] create cache directories to fix integration tests
  .github/workflows/jetbrains-integration-test.yml
Labels: size/XS, release-note-none

#16073 Decouple gitpod web extension
  .github/workflows/code-nightly.yml
  WORKSPACE.yaml
  components/BUILD.yaml
  components/ide-service/pkg/server/server.go
  components/ide/code/BUILD.yaml
  components/ide/code/codehelper/BUILD.yaml
  components/ide/code/codehelper/leeway.Dockerfile
  components/ide/code/codehelper/supervisor-ide-config.json
  components/ide/code/leeway.Dockerfile
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/versions.yaml
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
  install/installer/pkg/config/versions/versions.go
Labels: size/L, team: IDE, release-note-none

#16155 [jb] clarify how to test platform updates
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: IDE, release-note-none

#16160 [server] Guard getTeam
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#16144 Make sure generated workspace id align to regexp
  components/common-go/namegen/workspaceid.go
  components/common-go/namegen/workspaceid_test.go
Labels: size/S, release-note-none, team: staff-engineers

#16141 [prebuilds] respect gitpod.yml in GHE
  components/server/ee/src/prebuilds/github-enterprise-app.ts
Labels: size/XS, team: webapp, release-note-none

#16171 [spicedb] Use a secret in preview envs
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, release-note-none, team: delivery-operations-experience

#16173 [installer] Replace flag withoutWorkspaceComponents with 'Kind != "Full"'
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/pkg/common/common.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/slowserver/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager-bridge/objects.go
  install/installer/pkg/components/ws-manager-bridge/objects_test.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp, release-note-none, team: delivery-operations-experience

#16172 [spicedb] Require secretRef config
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/spicedb/objects.go
  install/installer/pkg/components/spicedb/secret.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp, release-note-none, team: delivery-operations-experience

#16156 [server, installer] Make admin-login-secret configurable (new default: not set)
  components/server/src/config.ts
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/user/user-controller.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/render.go
  install/installer/pkg/components/server/admin_secret.go
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/objects.go
  install/installer/pkg/components/slowserver/configmap.go
  install/installer/pkg/components/slowserver/objects.go
  install/installer/pkg/components/slowserver/render_test.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/validation.go
Labels: size/L, team: webapp, release-note-none, team: delivery-operations-experience

#16152 GHA Publish to NPM
  .github/pull_request_template.md
  .github/workflows/build.yml
  components/gitpod-protocol/scripts/publish.js
Labels: size/S, team: webapp, release-note-none

#16166 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16150 Delete platform-delete-preview-* jobs
  .werft/platform-delete-preview-environment.ts
  .werft/platform-delete-preview-environment.yaml
  .werft/platform-delete-preview-environments-cron.ts
  .werft/platform-delete-preview-environments-cron.yaml
Labels: size/XL, release-note-none, team: delivery-operations-experience

#16175 Remove platform-trigger-artificial-job
  .werft/platform-trigger-artificial-job.sh
  .werft/platform-trigger-artificial-job.yaml
Labels: size/L, release-note-none, team: delivery-operations-experience

#16176 [slowserver] Fix slowserver
  install/installer/pkg/components/slowserver/deployment.go
Labels: size/S, team: webapp, release-note-none

#16024 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#16025 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#16182 [code] New vscode release 1.75
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16191 :seedling: reflect docs breaking changes
  components/dashboard/src/workspaces/WorkspacesNew.tsx
Labels: size/XS, team: webapp, release-note-none

#16193 [gh-app] unsubscribe from pull_request.synchronize
  components/server/ee/src/prebuilds/github-app.ts
Labels: size/XS, team: webapp, release-note-none

#16151 [FIX] Improved UX for Workspace Entry Component
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/ItemsList.tsx
  components/dashboard/src/workspaces/WorkspaceEntryNew.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
Labels: community-contribution, size/M, release-note, cla: accepted :heavy_check_mark:

#16186 [server] Cleanup Organization RPCs authorization checks
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#16194 [server] Extend guardTeamResource with fine-grained ops
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/authorization/perms.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#16198 Don't publish npm packages from gha action on main
  .github/workflows/build.yml
Labels: size/XS, release-note-none

#16188 [ide-service] Always send IdeImageLayers
  components/ide-service/pkg/server/server.go
Labels: size/XS, team: IDE, release-note-none

#16153 Update workspace class descriptions
  components/dashboard/src/service/service-mock.ts
Labels: size/XS, team: webapp, release-note-none

#16202 Revert "[gh-app] unsubscribe from pull_request.synchronize"
  components/server/ee/src/prebuilds/github-app.ts
Labels: size/XS, team: webapp, release-note-none

#16042 [ws-manager-mk2] Configure leader election
  components/ws-manager-mk2/main.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  install/installer/pkg/components/ws-manager-mk2/role.go
Labels: size/M, team: workspace, release-note-none

#16199 [spicedb] Add job TTL to migrations
  install/installer/pkg/components/spicedb/migrations.go
Labels: size/XS, team: webapp, release-note-none

#16203 Add scaffolding for IDE integration tests
  .github/CODEOWNERS
  .github/workflows/ide-integration-tests.yml
Labels: size/M, release-note-none

#15622 Switch from alpine to wolfi
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/supervisor/openssh/leeway.Dockerfile
  components/toxic-config/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager/debug.Dockerfile
  components/ws-manager/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
  test/tests/components/image-builder/test.Dockerfile
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#16216 Remove cgroup v1 plugins
  components/ws-daemon/pkg/cgroup/plugin_fuse.go
  components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
  components/ws-daemon/pkg/daemon/daemon.go
Labels: size/XL, team: workspace, release-note-none

#16218 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16205 Use dev image as the container image for the job
  .github/workflows/ide-integration-tests.yml
Labels: size/XS, team: IDE, release-note-none

#16164 [dashboard] move org menu left
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/Menu.tsx
  components/dashboard/src/Setup.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/data/workspaces/list-workspaces-query.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/project-context.tsx
  components/dashboard/src/projects/projects.routes.ts
  components/dashboard/src/settings/settings.routes.ts
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/teams-context.tsx
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/Billing.tsx
  components/dashboard/src/user-settings/ChargebeeTeams.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/Integrations.test.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/Notifications.tsx
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/Plans.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/user-settings/ProfileInformation.tsx
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/user-settings/SelectAccountModal.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  components/dashboard/src/user-settings/SelectIDEModal.tsx
  components/dashboard/src/user-settings/ShowTokenModal.tsx
  components/dashboard/src/user-settings/TokenEntry.tsx
  components/dashboard/src/user-settings/selectClass.tsx
  components/dashboard/src/user-settings/settings-menu.ts
  components/dashboard/src/user-settings/settings.routes.ts
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/dashboard/src/workspaces/WorkspacesNew.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp, release-note

#16197 [server] Add spicedb client
  components/server/package.json
  components/server/src/authorization/spicedb.ts
  components/server/src/container-module.ts
  yarn.lock
Labels: size/M, team: webapp, release-note-none

#16204 [dashboard] Make sure we actually have the ownerToken set before we r…
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/M, team: webapp, release-note-none

#16207 [server] Perform authorization checks for Orgs against spicedb
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/authorization/checks.ts
  components/server/src/authorization/perms.ts
  components/server/src/container-module.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp, release-note-none

#16227 [spicedb] Enable ingress policy for dispatch endpoint, from sibling
  install/installer/pkg/components/spicedb/networkpolicy.go
Labels: size/S, team: webapp, release-note-none

#16224 [dashboard] state must evict when org changes
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/L, team: webapp, release-note-none

#16229 [spicedb] Actually enable running dispatch server
  install/installer/pkg/components/spicedb/deployment.go
Labels: size/XS, team: webapp, release-note-none

#16233 [gitpod-db] Add region for cluster selection
  components/gitpod-db/src/typeorm/migration/1675694207999-WorkspaceClusterRegion.ts
Labels: size/S, team: webapp, release-note-none

#16242 [codehelper] fix CSP replacement when serving from sources
  components/ide/code/codehelper/main.go
Labels: size/S, team: IDE, release-note-none

#16245 [spicedb] Log level info
  install/installer/pkg/components/spicedb/deployment.go
Labels: size/XS, team: webapp, release-note-none

#16230 [spicedb] Adjust readiness probe frequency
  install/installer/pkg/components/spicedb/deployment.go
Labels: size/S, team: webapp, release-note-none

#16210 [supervisor] Add missing stream api metrics
  components/supervisor/pkg/serverapi/publicapi.go
Labels: size/XS, team: IDE, release-note-none

#16212 fixing lint errors
  components/dashboard/package.json
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/user-settings/ChargebeeTeams.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/Plans.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  components/dashboard/src/user-settings/selectClass.tsx
Labels: size/L, team: webapp, release-note-none

#16252 Update settings section header semantics
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/XS, team: webapp, release-note-none

#16163 [teams] Remove slug usage
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service-mock.ts
  components/gitpod-db/src/team-db.spec.db.ts
  components/gitpod-db/src/typeorm/entity/db-team.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/transformer.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/project.go
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
  components/server/src/auth/resource-access.spec.ts
Labels: size/M, team: webapp, release-note-none

#16254 [obs] Temporarily avoid imageBuildFailure reason for InstanceStartFailures alert
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/XS, team: webapp, release-note-none

#16201 Reuse the same workspace patterns
  components/common-go/namegen/workspaceid.go
  components/ws-proxy/pkg/proxy/workspacerouter.go
Labels: size/S, team: workspace, release-note-none, team: staff-engineers

#16259 [dashboard] fix logo
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/M, team: webapp, release-note-none

#16181 [ws-manager-mk2] Implement MarkActive
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/pkg/activity/activity.go
  components/ws-manager-mk2/service/manager.go
  components/ws-manager-mk2/ws-manager-mk2.code-workspace
Labels: size/L, team: workspace, release-note-none

#16226 [ws-manager-mk2] Extract ctrl utils to common-go
  components/common-go/kubernetes/kubernetes.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/service/manager.go
Labels: size/L, team: workspace, release-note-none, team: staff-engineers

#16037 git auth under team settings
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/components/forms/InputField.tsx
  components/dashboard/src/components/forms/SelectInputField.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/data/auth-providers/delete-org-auth-provider-mutation.ts
  components/dashboard/src/data/auth-providers/org-auth-providers-query.ts
  components/dashboard/src/data/auth-providers/upsert-org-auth-provider-mutation.ts
  components/dashboard/src/data/billing-mode/org-billing-mode-query.ts
  components/dashboard/src/data/organizations/org-members-query.ts
  components/dashboard/src/hooks/use-onblur-error.ts
  components/dashboard/src/hooks/useId.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/teams/GitIntegrationsPage.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
  components/dashboard/src/teams/teams-context.tsx
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/gitpod-protocol/src/gitpod-service.ts
Labels: size/XXL, team: webapp, release-note-none

#16263 [dashboard] Add George as CodeOwner
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#16262 Simplify preview environment staleness check
  dev/preview/previewctl/cmd/stale.go
  dev/preview/previewctl/cmd/workspaces.go
  dev/preview/previewctl/pkg/preview/status.go
  dev/preview/previewctl/pkg/preview/util.go
Labels: size/L, release-note-none

#16096 Add workspacecontexturl to gpcli
  components/gitpod-cli/cmd/info.go
Labels: component: gp cli, community-contribution, size/S, release-note, cla: accepted :heavy_check_mark:

#15946 [fix] :Preselect editor and class on the new workspace modal on first load
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
Labels: community-contribution, size/XS, release-note, cla: accepted :heavy_check_mark:

#16248 [spicedb] Add kube-rbac-proxy to expose metrics endpoint
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/spicedb/rolebinding.go
Labels: size/S, team: webapp, release-note-none

#16275 [dashboard] small fixes
  components/dashboard/src/menu/Menu.tsx
Labels: size/XS, team: webapp, release-note-none

#16249 Add missing options to gha build
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/actions/deploy-gitpod/metadata.yml
  .github/pull_request_template.md
  .github/workflows/build.yml
Labels: size/M, release-note-none

#16276 [code] Cherry pick firefox webview workaround
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16280 Re-render app on org change
  components/dashboard/src/App.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/S, team: webapp, release-note-none

#16284 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16270 [server] Ignore old FREE/FREE_50 when evaluating BillingMode
  components/server/ee/src/billing/billing-mode.spec.db.ts
  components/server/ee/src/billing/billing-mode.ts
Labels: size/S, team: webapp, release-note

#16213 [code] Point code nightly worklow back to main branch
  .github/workflows/code-nightly.yml
Labels: size/XS, release-note-none

#16281 small improvements for gp rebuild
  components/gitpod-cli/cmd/rebuild.go
  components/ide/code/codehelper/.gitignore
  components/ide/code/codehelper/main.go
Labels: size/L, team: IDE, release-note-none

#16136 [ws-manager-api] Add region for cluster selection
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/workspace-cluster.ts
  components/image-builder-api/typescript/src/sugar.ts
  components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/go/core_grpc.pb.go
  components/ws-manager-api/go/mock/mock.go
  components/ws-manager-api/typescript/.vscode/launch.json
  components/ws-manager-api/typescript/src/client-provider-source.ts
  components/ws-manager-api/typescript/src/client-provider.spec.ts
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-api/typescript/src/constraints.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.d.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.js
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/go/cluster-service_grpc.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_grpc_pb.d.ts
  components/ws-manager-bridge-api/typescript/src/cluster-service_grpc_pb.js
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
  dev/gpctl/cmd/clusters-register.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ws-manager-bridge/types.go
Labels: size/XL, release-note-none

#16291 [image-builder-api] Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#16292 Reverse order of Feedback emojis
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
Labels: size/XS, team: webapp

#16295 Enable build workflow dispatc
  .github/workflows/build.yml
Labels: size/XS, release-note-none

#16288 [gorm] Ignore NotFound errors when logging
  components/gitpod-db/go/conn.go
Labels: size/XS, team: webapp, release-note-none

#16289 [usage] Reduce log level for Fetching usage data log
  components/usage/pkg/apiv1/usage.go
Labels: size/XS, team: webapp, release-note-none

#16294 Change ws-manager-api code owners
  .github/CODEOWNERS
Labels: size/XS, team: workspace, release-note-none

#16273 [server] Make sure to only ever finish this span once
  components/gitpod-protocol/src/util/tracing.ts
  components/image-builder-api/typescript/src/sugar.ts
Labels: size/S, team: webapp, release-note-none

#15997 [gitpod-cli] add command analytics
  components/gitpod-cli/cmd/completion.go
  components/gitpod-cli/cmd/credential-helper.go
  components/gitpod-cli/cmd/docs.go
  components/gitpod-cli/cmd/env.go
  components/gitpod-cli/cmd/git-token-validator.go
  components/gitpod-cli/cmd/git-track-command.go
  components/gitpod-cli/cmd/gitpodRun.go
  components/gitpod-cli/cmd/info.go
  components/gitpod-cli/cmd/init.go
  components/gitpod-cli/cmd/open.go
  components/gitpod-cli/cmd/ports-await.go
  components/gitpod-cli/cmd/ports-expose.go
  components/gitpod-cli/cmd/ports-list.go
  components/gitpod-cli/cmd/ports-visibility.go
  components/gitpod-cli/cmd/ports.go
  components/gitpod-cli/cmd/preview.go
  components/gitpod-cli/cmd/rebuild.go
  components/gitpod-cli/cmd/root.go
  components/gitpod-cli/cmd/root_test.go
  components/gitpod-cli/cmd/snapshot.go
  components/gitpod-cli/cmd/stop-workspace.go
  components/gitpod-cli/cmd/sync-await.go
  components/gitpod-cli/cmd/sync-done.go
  components/gitpod-cli/cmd/tasks-attach.go
  components/gitpod-cli/cmd/tasks-list.go
  components/gitpod-cli/cmd/tasks-stop.go
  components/gitpod-cli/cmd/tasks.go
  components/gitpod-cli/cmd/timeout-extend.go
  components/gitpod-cli/cmd/timeout-set.go
  components/gitpod-cli/cmd/timeout-show.go
  components/gitpod-cli/cmd/top.go
  components/gitpod-cli/cmd/url.go
  components/gitpod-cli/cmd/version.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/gitpod-cli/pkg/gitpod/server.go
  components/gitpod-cli/pkg/supervisor/terminal-attach.go
  components/gitpod-cli/pkg/utils/global.go
  components/gitpod-cli/pkg/utils/logError.go
  components/gitpod-cli/pkg/utils/trackEvent.go
  components/supervisor/cmd/error-report.go
  components/supervisor/cmd/send-analytics.go
Labels: size/XXL, team: IDE, release-note-none

#16304 gp rebuild: disable desktop IDEs
  components/gitpod-cli/cmd/rebuild.go
Labels: size/XS, team: IDE, release-note-none

#16314 [entitlement] Limit network connections for all users
  components/server/ee/src/billing/entitlement-service-ubp.ts
Labels: size/XS, team: webapp, release-note-none

#16192 [db] d_b_workspace get organizationId
  components/gitpod-db/src/typeorm/migration/1675744891502-WorkspaceOrganizationId.ts
Labels: size/S, team: webapp, release-note-none

#16303 [server] Guess workspace region
  components/server/package.json
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/region-service.ts
  components/server/src/workspace/workspace-starter.ts
  yarn.lock
Labels: size/L, team: webapp, release-note-none

#16260 Add open desktop ide entrypoint for browser code
  components/gitpod-protocol/src/typings/globals.ts
  components/supervisor/frontend/src/index.ts
Labels: editor: code (browser), size/XS, team: webapp, team: IDE, release-note-none

#16319 [server] Guess region for both workspaceCreate and workspaceStart
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#16261 [server] set organizationid on workspace creation
  components/gitpod-db/.vscode/launch.json
  components/gitpod-db/go/workspace.go
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/transformer.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp, release-note-none

#16321 Update gitpod-web extension to improve open desktop ide prompt
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note

#16322 [image-builder-api] Update codeowners to ws team
  .github/CODEOWNERS
Labels: size/XS, team: workspace, release-note-none

#16323 Fix ide tests
  test/pkg/integration/apis.go
  test/tests/ide/vscode/python_ws_test.go
Labels: size/S, release-note-none

#16312 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16310 Update openssh to v9.2
  components/supervisor/openssh/leeway.Dockerfile
Labels: size/XS, team: IDE, release-note-none

#16287 [supervisor] improve config watch logging
  components/supervisor/pkg/config/gitpod-config.go
Labels: size/S, team: IDE, release-note-none

#16305 [gpctl] Ensure region is all lowercase, provide cmd help
  dev/gpctl/cmd/clusters-register.go
Labels: size/XS, team: workspace, release-note-none

#16331 [OIDC] Check issuer URL for reachability
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/L, team: webapp, release-note-none

#16269 [db] long running migration for filling the organizationid in workspaces
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/long-running-migration/long-running-migration.spec.db.ts
  components/gitpod-db/src/long-running-migration/long-running-migration.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.spec.db.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
  components/gitpod-db/src/typeorm/entity/db-long-running-migration.ts
  components/gitpod-db/src/typeorm/migration/1675863598550-LongRunningMigration.ts
  components/server/src/server.ts
Labels: size/XL, team: webapp, release-note-none

#16333 [gp-cli] fix sync-await cannot interrupt
  components/gitpod-cli/cmd/sync-await.go
Labels: size/XS, team: IDE, release-note-none

#16336 [gitpod-db] reduce migration batch size
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
Labels: size/S, team: webapp, release-note-none

#16209 [ws-manager-mk2] Workspace timeouts
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
Labels: size/XL, team: workspace, release-note-none

#16340 [db] optimize workspace update
  components/gitpod-db/.vscode/launch.json
  components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
Labels: size/S, team: webapp, release-note-none

#16132 update vscode workspace folders
  gitpod-ws.code-workspace
  scripts/update-gitpod-ws.code-workspace.js
Labels: size/XL, release-note-none

#16339 [usage] update stripe usage on finalization
  components/usage/pkg/apiv1/billing.go
Labels: size/S, team: webapp, release-note-none

#16342 Revert "update vscode workspace folders"
  gitpod-ws.code-workspace
  scripts/update-gitpod-ws.code-workspace.js
Labels: size/XL, release-note-none

#16308 Always show all navigation menu items
  components/dashboard/src/menu/Menu.tsx
Labels: size/S, team: webapp, release-note

#16337 [gitpod-web-extension] fix supervisor notify request not await
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16334 [server] Typed workspace region
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/workspace-cluster.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/region-service.ts
  components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/typescript/src/client-provider.spec.ts
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: size/L, team: webapp, team: workspace, release-note-none

#16343 [ws-man-bridge] Expose region in ClusterStatus
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: size/XS, team: webapp, release-note-none

#16327 [redis] Deploy component
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/redis/constants.go
  install/installer/pkg/components/redis/deployment.go
  install/installer/pkg/components/redis/objects.go
  install/installer/pkg/components/redis/service.go
Labels: size/L, team: webapp, release-note-none, team: security-infrastructure-and-delivery

#16345 [gpctl] Expose region in cluster list
  dev/gpctl/cmd/clusters-list.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#16297 [dashboard] fixing redirects
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/projects/project-context.tsx
Labels: size/L, team: webapp, release-note-none

#16329 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16359 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16360 [gp-cli] fix gp open cmd open another file
  components/gitpod-cli/cmd/open.go
Labels: size/XS, team: IDE, release-note-none

#16361 [ws-manager-bridge] fix incorrect module import
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/cluster-sync-service.ts
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/XS, team: webapp, release-note-none

#16367 [gp-cli] fix empty human readable timeout
  components/gitpod-cli/cmd/timeout-set.go
  components/gitpod-cli/cmd/timeout-show.go
Labels: size/S, team: IDE, release-note-none

#16373 Fix preview gha build
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/workflows/build.yml
Labels: size/S, release-note-none, team: security-infrastructure-and-delivery

#16374 [server] disable long migrations via config
  components/server/ee/src/server.ts
  components/server/src/config.ts
  components/server/src/server.ts
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/server/types.go
Labels: size/S, team: webapp, release-note-none

#16377 [installer] args to disable jobs
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, release-note-none, team: security-infrastructure-and-delivery

#16375 [test] update JetBrains RubyMine test repo
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/XS, release-note-none

#16318 [ws-manager-mk2] Controller env tests
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/service/manager.go
  components/ws-manager-mk2/ws-manager-mk2.code-workspace
Labels: size/XL, team: workspace, release-note-none

#16381 [migrations] added logs and air
  components/gitpod-db/src/long-running-migration/long-running-migration.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.spec.db.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
Labels: size/L, team: webapp, release-note-none

#16384 [ws-man-bridge-api] Fix codegen
  components/ws-manager-bridge-api/buf.gen.yaml
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.js
Labels: size/XS, team: webapp, release-note-none

#16387 [codeowners] Update registry-facade-api owner
  .github/CODEOWNERS
Labels: size/XS, team: workspace, release-note-none

#16341 [ws-manager-mk2] Cleanup EverReady condition
  components/common-go/kubernetes/kubernetes.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
Labels: size/M, team: workspace, release-note-none, team: staff-engineers

#16388 Update buildkit container image
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note-none

#16348 [ws-manager-mk2] Aborted condition, grace period
  components/ws-daemon/pkg/controller/controller.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/service/manager.go
Labels: size/L, team: workspace, release-note-none

#16364 [server] pass organizationId to create ws
  components/gitpod-protocol/src/attribution.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/ee/src/billing/entitlement-service-chargebee.ts
  components/server/ee/src/billing/entitlement-service-license.ts
  components/server/ee/src/billing/entitlement-service-ubp.ts
  components/server/ee/src/billing/entitlement-service.ts
  components/server/ee/src/prebuilds/prebuild-manager.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp, release-note-none

#16258 feat: Improved UX for Environment Variable Item List ( Settings )
  components/dashboard/src/user-settings/EnvironmentVariableEntry.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
Labels: size/M, release-note

#16158 [dashboard] Fix Dashboard lint errors for Login.tsx
  components/dashboard/src/Login.tsx
Labels: community-contribution, size/M, cla: accepted :heavy_check_mark:

#16393 [dashboard] don't create more than one workspace
  components/dashboard/src/start/CreateWorkspace.tsx
Labels: size/S, team: webapp, release-note-none

#16372 [ws-manager-mk2] Support class|network limiting and PSI
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace, release-note-none, feature: ws-manager-mk2

#16398 [ws-manager-mk2] Support system environment variables
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/service/manager.go
Labels: size/XL, team: workspace, release-note-none, feature: ws-manager-mk2

#16382 Add credentials token for browser IDE
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/frontend-dashboard-service.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#16403 [ws-manager-mk2] Fix stuck on init/dispose failure
  components/ws-daemon/pkg/controller/controller.go
Labels: size/S, team: workspace, release-note-none

#16407 [ws-manager-mk2] Fix workspace URL not set in env
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/main.go
Labels: size/S, team: workspace, release-note-none

#16400 [ws-manager-mk2] Add finalizer on workspace, handle ws deletion
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/service/manager.go
Labels: size/L, team: workspace, release-note-none

#16411 [gitpod-db] Fix AuthProviderEntryDBImpl.findByUserId
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
Labels: size/S, team: webapp, release-note-none

#16002 Replaced loading svg icon with Loader component
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/Loader.tsx
  components/dashboard/src/icons/Spinner.svg
Labels: community-contribution, size/L, release-note

#16353 Add nav items and icons to org selector
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/org-icon/OrgIcon.tsx
  components/dashboard/src/components/org-icon/consistent-classname.test.ts
  components/dashboard/src/components/org-icon/consistent-classname.ts
  components/dashboard/src/components/org-icon/styles.css
  components/dashboard/src/data/billing-mode/user-billing-mode-query.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/tailwind.config.js
Labels: size/XXL, team: webapp, release-note

#16317 [oidc] encode and validate state params
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/oidc/oauth2.go
  components/public-api-server/pkg/oidc/router_test.go
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
  components/public-api-server/pkg/oidc/state_jwt.go
  components/public-api-server/pkg/oidc/state_jwt_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/L, team: webapp, release-note-none

#16428 [dashboard] k8s applications
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-applications.json
Labels: size/XL, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery

#16422 Small adjustments to org selector menu
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/org-icon/OrgIcon.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/S, team: webapp, release-note-none
