Repository gitpod-io/gitpod, pull requests merged in 2023-05, with the labels that each got.

#17434 [wsman-mk2] Log reconciliations
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/XS, team: workspace, feature: ws-manager-mk2

#17393 [ws-manager-mk2] Run integration tests against mk2 by default in GHA (+ preview fixes)
  .github/workflows/workspace-integration-tests.yml
  dev/preview/workflow/preview/deploy-gitpod.sh
  test/pkg/integration/apis.go
  test/pkg/integration/integration.go
  test/pkg/integration/setup.go
Labels: size/M, team: workspace

#17441 Adds org naming step in dedicated setup flow
  components/dashboard/src/data/organizations/create-org-mutation.ts
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/GettingStartedStep.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/dedicated-setup/SetupLayout.tsx
Labels: size/XL, team: webapp

#17432 Streamline dedicated login/signup
  components/dashboard/src/Login.tsx
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/provider-utils.tsx
  components/gitpod-db/go/team.go
  components/gitpod-db/go/team_test.go
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp

#17444 [dashboard] handle organization-owned users
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/onboarding/use-show-user-onboarding.ts
  components/gitpod-protocol/src/protocol.ts
Labels: size/M, team: webapp

#17422 Repersist IDP public key when lost
  components/public-api-server/pkg/identityprovider/cache.go
  components/public-api-server/pkg/identityprovider/cache_test.go
Labels: size/M, team: webapp

#17443 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#17451 [ws-manager-mk2] Fix abort prebuild failure
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/M, team: workspace

#17462 [ws-manager-mk2] Return exposed ports in workspace status
  components/ws-manager-mk2/service/manager.go
Labels: size/S, team: workspace

#17461 [server] fix login regression
  components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
  components/server/src/user/user-service.ts
Labels: size/M, team: webapp

#17454 [obs] right align image builds in the Running Workspaces pane
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview-mk2.json
Labels: size/M, team: workspace

#17458 [server] Fix parsing of go duration WEB-280
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/util/timeutil.spec.ts
  components/gitpod-protocol/src/util/timeutil.ts
  components/server/src/workspace/gitpod-server-impl.ts
  yarn.lock
Labels: size/L, team: webapp

#17463 [SSO] Use ClientConfigID & Subject as composite key for identities WEB-279
  components/public-api-server/pkg/oidc/router.go
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
  components/server/src/iam/iam-oidc-create-session-payload.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/L, team: webapp

#17453 [obs] mk2 dashboard, change startup time heatmap's rate to `rate interval`
  operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json
Labels: size/M, team: workspace

#17464 [public-api] Implement UpdateOIDCClientConfig WEB-278
  components/gitpod-db/go/dbtest/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config_test.go
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/XL, team: webapp

#17465 [ws-manager-mk2] Fix prebuild start failure false positives
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/S, team: workspace

#17449 [ws-manager-mk2] Fix slow p25 workspace startup time
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
Labels: size/S, team: workspace, feature: ws-manager-mk2

#17467 Dedicated Setup - SSO Setup
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/data/oidc-clients/upsert-oidc-client-mutation.ts
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/dedicated-setup/SetupLayout.tsx
  components/dashboard/src/images/check.svg
  components/dashboard/src/provider-utils.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/SSOConfigForm.tsx
Labels: size/XXL, team: webapp

#17433 [server] Unify periodic jobs
  components/server/src/container-module.ts
  components/server/src/jobs/database-gc.ts
  components/server/src/jobs/ots-gc.ts
  components/server/src/jobs/runner.ts
  components/server/src/jobs/token-gc.ts
  components/server/src/jobs/webhook-gc.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/one-time-secret-server.ts
  components/server/src/projects/webhook-event-garbage-collector.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/server.ts
  components/server/src/user/token-garbage-collector.ts
  components/server/src/user/token-service.ts
Labels: size/XXL, team: webapp

#17437 [dashboard] Remove cypress
  components/dashboard/README.md
  components/dashboard/cypress.json
  components/dashboard/cypress/fixtures/example.json
  components/dashboard/cypress/fixtures/profile.json
  components/dashboard/cypress/fixtures/users.json
  components/dashboard/cypress/integration/app.spec.ts
  components/dashboard/cypress/plugins/index.js
  components/dashboard/cypress/support/commands.js
  components/dashboard/cypress/support/index.js
  components/dashboard/cypress/tsconfig.json
  components/dashboard/package.json
  yarn.lock
Labels: size/XXL, team: webapp

#17459 [baseserver] Test port is 0
  components/common-go/baseserver/server.go
  components/common-go/baseserver/server_test.go
  components/common-go/baseserver/testing.go
Labels: size/M, team: staff-engineers

#17470 [oidc] Restrict actions to team owners WEB-284
  components/gitpod-db/go/dbtest/team_membership.go
  components/gitpod-db/go/dbtest/user.go
  components/gitpod-db/go/team_membership.go
  components/gitpod-db/go/team_membership_test.go
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/XXL, team: webapp

#17466 Compute onboarding state – WEB-287
  components/gitpod-db/src/team-db.spec.db.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17167 [usage] Mutex jobs redis WEB-266
  .gitignore
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/scheduler/job.go
  components/usage/pkg/scheduler/job_test.go
  components/usage/pkg/scheduler/ledger_job.go
  components/usage/pkg/scheduler/mutex.go
  components/usage/pkg/scheduler/mutex_test.go
  components/usage/pkg/scheduler/reset_usage_job.go
  components/usage/pkg/server/server.go
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/redis/networkpolicy.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/XL, team: webapp, release-note-none

#17347 [dashboard] remove start-with-options feature flag
  components/dashboard/src/App.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/MonacoEditor.tsx
  components/dashboard/src/index.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
  components/dashboard/src/workspaces/start-workspace-modal-context.tsx
Labels: size/XXL, team: webapp

#17476 [dashboard] fix button rendering
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/S, team: webapp

#17468 [obs] Include p01, p25 and p75 in success criteria
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/L, team: workspace

#17297 [dashboard] Always use these options for repository
  components/dashboard/src/start/start-workspace-options.ts
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/protocol.ts
Labels: size/L, team: webapp

#17479 [usage] Fix constructor binding
  components/usage/pkg/scheduler/ledger_job.go
Labels: size/XS, team: webapp

#17481 [wsman-mk2] Schedule on non experimental nodes
  components/ws-manager-mk2/controllers/create.go
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, team: workspace, feature: ws-manager-mk2

#17485 [server] migrate ws without usageattribution
  components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17486 [wsman-mk2] Log workspace startup time
  components/ws-manager-mk2/controllers/metrics.go
Labels: size/XS, team: workspace, feature: ws-manager-mk2

#17475 [preview] force gce when providing infrastructure, avoid harvester
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/gce/vm.tf
  dev/preview/infrastructure/variables.tf
  dev/preview/workflow/preview/deploy-harvester.sh
  dev/preview/workflow/preview/determine-env.sh
Labels: size/M

#17489 Add missing await on promise.
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp

#17222 [test] Fix workspace integration tests
  .github/CODEOWNERS
  .github/workflows/workspace-integration-tests.yml
  .werft/vm/manifests/rook-ceph/common.yaml
  components/gitpod-protocol/go/gitpod-service.go
  dev/preview/BUILD.yaml
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/gce/vm.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/scripts/install-trustmanager.sh
  dev/preview/infrastructure/variables.tf
  dev/preview/workflow/preview/deploy-gitpod.sh
  dev/preview/workflow/preview/deploy-monitoring-satellite.sh
  test/README.md
  test/pkg/integration/apis.go
  test/pkg/integration/git-client.go
  test/pkg/integration/workspace.go
  test/tests/workspace/contexts_test.go
  test/tests/workspace/git_test.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none

#17483 [server] Report duration of jobs
  components/server/src/jobs/runner.ts
  components/server/src/prometheus-metrics.ts
Labels: size/S, team: webapp

#17487 [server] Delete webhook events directly
  components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
Labels: size/S, team: webapp

#17493 [server] mark admin as migrated
  components/gitpod-db/src/typeorm/migration/1683183008878-AdminUserMigrated.ts
Labels: size/S, team: webapp

#17488 Use getOnboardingState api for dedicated setup flow
  components/dashboard/src/App.tsx
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
  components/dashboard/src/user-context.tsx
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17496 [ws-manager-mk2] Make mk2 dashboard the default
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview-mk2.json
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/XXL, team: workspace, feature: ws-manager-mk2

#17300 [installer] First user is no longer admin WEB-127
  install/installer/pkg/components/server/configmap.go
Labels: size/XS, team: webapp

#17500 Revert "[server] Delete webhook events directly"
  components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
Labels: size/S, team: webapp

#17498 Fix "too many renders" errors – WEB-302
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
Labels: size/XS, team: webapp

#17301 [server] Remove grant first user admin WEB-127
  components/server/src/config.ts
  components/server/src/user/user-service.ts
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/types.go
Labels: size/XS, team: webapp

#17505 Update honeycomb illustration
  components/dashboard/src/icons/honeycomb-bg.svg
Labels: size/S, team: webapp

#17506 removing user from top right for dedicated setup
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/dedicated-setup/SetupLayout.tsx
  components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/sso/SSOConfigForm.tsx
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/XL, team: webapp

#17510 [server] remove admin-user from org on first user sign-in – WEB-303
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/M, team: webapp

#17478 [dashboard] invite link for SSO orgs
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/teams/Members.tsx
  components/gitpod-db/src/team-db.spec.db.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/public-api-server/debug.sh
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17480 [ws-manager-mk2] Enable by default in preview envs
  .github/pull_request_template.md
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/XS, team: workspace

#17517 [ws-manager-mk2] Ensure stop reason is logged
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/XS, team: workspace, feature: ws-manager-mk2

#17503 VS Code Browser release 1.78
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#17524 [loadgen] update docs to support ws-manager-mk2
  dev/loadgen/README.md
Labels: size/XS, team: workspace

#17516 [dashboard] git auth on create workspace
  components/dashboard/src/components/AuthorizeGit.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: webapp

#17528 [server] Do not allow to remove Org accounts – WEB-319
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17474 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#17532 Remove upgrade plan check icon
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/XS, team: webapp

#17534 Show usage
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
  components/server/src/iam/iam-session-app.spec.ts
Labels: size/S, team: webapp

#17355 Enable dashboard linter for pre-commit hooks
  .pre-commit-config.yaml
  components/dashboard/BUILD.yaml
  components/dashboard/package.json
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/dashboard/src/start/StartPage.tsx
Labels: size/S, team: webapp

#17533 [ws-manager-mk2] Custom retry backoff params for modifyWorkspace
  components/ws-manager-mk2/service/manager.go
Labels: size/S, team: workspace

#17539 removing setup intent related code
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/user/stripe-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/usage/v1/billing.proto
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: webapp

#17554 [preview] update VM image to match gen97
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: workspace

#17502 [ws-manager-mk2] Test automation for ws-daemon
  components/ws-daemon/BUILD.yaml
  components/ws-daemon/crd/workspace.gitpod.io_workspaces.yaml
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/pkg/controller/mocks.go
  components/ws-daemon/pkg/controller/suite_test.go
  components/ws-daemon/pkg/controller/workspace_controller_test.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  install/installer/go.mod
Labels: size/XXL, team: workspace, feature: ws-manager-mk2

#17529 [server] Ensure admin user is owner of any Org – WEB-303
  components/server/src/user/user-controller.ts
Labels: size/S, team: webapp

#17538 org-owned owners cannot delete the owning org
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service-mock.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/team.go
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
  components/server/src/api/teams.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
Labels: size/L, team: webapp

#17560 [iam] Validate OIDC Create Session Payload - WEB-338
  components/server/src/iam/iam-oidc-create-session-payload.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/L, team: webapp

#17559 allow to redirect only for whitelisted trusted protocols
  components/dashboard/src/service/service.tsx
Labels: size/XS, team: webapp

#17522 Display active state on org sso configs
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/EmptyMessage.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
Labels: size/L, team: webapp

#17565 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE

#17568 Refresh user after activating git integration
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
Labels: size/S, team: webapp

#17548 [ws-manager-mk2] Refactor lastActivity
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/timeout_controller_test.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/pkg/activity/activity.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace

#17572 [server] adding git authprovider is an org update
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp

#17507 [image-builder-bob] update buildkit
  components/common-go/go-update-wc-deps.sh
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-bob/leeway.Dockerfile
Labels: size/S, team: workspace, team: staff-engineers

#17577 Don't wait for onboarding state to render
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/app/AppLoading.tsx
  components/dashboard/src/app/AppRoutes.tsx
Labels: size/S, team: webapp

#17582 ensure dedicated setup doesn't show on prod saas
  components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
Labels: size/XS, team: webapp

#17593 [analytics plugin] allow to configure segment endpoint
  components/proxy/plugins/analytics/analytics.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp

#17594 [dashboard] no editing email for org users
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/ProfileInformation.tsx
  components/gitpod-protocol/src/protocol.ts
Labels: size/L, team: webapp

#17581 Update Platform Version of JetBrains Gateway Plugin (Stable) to 231.8…
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE

#17584 Update Platform Version of JetBrains Gateway Plugin (EAP) to 231.9011…
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS

#17585 Update Platform Version of JetBrains Backend Plugin (EAP) to 231.9011…
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS

#17590 Update VS Code Browser to `1.78.2`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE

#17586 Increase workspace TerminationGracePeriodSeconds to avoid removal of nodes
  components/ws-manager-mk2/controllers/create.go
Labels: size/XS, team: workspace

#17447 Directly tunnel websocket connection to ssh server
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/S, team: IDE

#17592 [server] Move update user implementation to UserService
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17549 [usage] Scheduler with mutex by default
  components/usage/pkg/scheduler/job.go
  components/usage/pkg/scheduler/ledger_job.go
  components/usage/pkg/scheduler/reset_usage_job.go
  components/usage/pkg/scheduler/scheduler.go
  components/usage/pkg/scheduler/scheduler_test.go
  components/usage/pkg/server/server.go
Labels: size/L, team: webapp

#17570 [sso] Improve SSO dance logs & user facing error messages WEB-300
  components/public-api-server/pkg/oidc/router.go
Labels: size/S, team: webapp

#17603 [dashboard] update document title on setup
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/hooks/use-document-title.ts
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/teams/JoinTeam.tsx
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/M, team: webapp

#17575 [dashboard] fix reload
  components/dashboard/src/data/workspaces/create-workspace-mutation.ts
  components/dashboard/src/start/start-workspace-options.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/L, team: webapp

#17613 [server] remove unused code in user-service.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/server/src/user/user-service.ts
Labels: size/M, team: webapp

#17574 Update stripe customers during migration
  components/gitpod-db/go/stripe_customer.go
  components/gitpod-db/src/container-module.ts
  components/server/package.json
  components/server/src/container-module.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/migration/user-to-team-migration-service.spec.db.ts
  components/server/src/migration/user-to-team-migration-service.ts
  components/server/src/user/stripe-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
  scripts/mysql-test.sh
Labels: size/L, team: webapp

#17605 Remove VS Code changelogs (update `gitpod-web`)
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE

#17614 [SSO] find organizational accounts by email – WEB-346
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-db/src/user-db.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp

#17620 Update runc to v1.1.7
  components/docker-up/dependencies.sh
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/leeway.Dockerfile
  install/installer/go.mod
  install/installer/go.sum
Labels: size/S, team: workspace

#17587 Show a pending status if setup is still required
  components/dashboard/BUILD.yaml
  components/dashboard/src/Login.tsx
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
  components/dashboard/src/dedicated-setup/use-needs-setup.ts
  components/dashboard/src/dedicated-setup/use-show-dedicated-setup.ts
  components/dashboard/src/images/cubicle-dark.png
  components/dashboard/src/images/cubicle-dark@2x.png
  components/dashboard/src/images/cubicle.png
  components/dashboard/src/images/cubicle@2x.png
  components/dashboard/src/index.tsx
  components/dashboard/src/login/SetupPending.tsx
  components/dashboard/src/theme-context.tsx
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp

#17625 [gitpod] Remove go task open right
  .gitpod.yml
Labels: size/XS

#17615 [papi] validate ID token claims – WEB-337
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
Labels: size/L, team: webapp

#17623 [sso] Validate Issuer URL + fix trailing slash WEB-345
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
  components/public-api-server/pkg/oidc/oauth2.go
  components/public-api-server/pkg/oidc/router.go
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
Labels: size/L, team: webapp

#17626 [server] immediately run jobs
  components/server/src/jobs/fix-stripe-job.ts
  components/server/src/jobs/runner.ts
Labels: size/S, team: webapp

#17630 fix build
  components/server/src/jobs/runner.ts
Labels: size/XS, team: webapp

#17629 [server] fix invoices
  components/server/src/jobs/fix-stripe-job.spec.db.ts
  components/server/src/jobs/fix-stripe-job.ts
Labels: size/L, team: webapp

#17631 [server] fix stripe query
  components/server/src/user/stripe-service.ts
Labels: size/XS, team: webapp

#17634 [server] fix adminSetUsageLimit
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp

#17635 Verify/Activate for SSO Configs
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/data/oidc-clients/activate-oidc-client-mutation.ts
  components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
  components/dashboard/src/provider-utils.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
  components/dashboard/src/teams/sso/SSOConfigForm.tsx
Labels: size/L, team: webapp

#17639 SSO Setup screen showing on setup cell
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/use-needs-setup.ts
  components/dashboard/src/dedicated-setup/use-show-dedicated-setup.ts
Labels: size/M, team: webapp

#17622 Update workspace options UX
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
Labels: size/M, team: webapp

#17647 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17636 [server] remove stripe fix again
  components/server/src/container-module.ts
  components/server/src/jobs/fix-stripe-job.spec.db.ts
  components/server/src/jobs/fix-stripe-job.ts
  components/server/src/jobs/runner.ts
Labels: size/L, team: webapp

#17638 remove long-running migrations
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/long-running-migration/long-running-migration.spec.db.ts
  components/gitpod-db/src/long-running-migration/long-running-migration.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.spec.db.ts
  components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
  components/gitpod-db/src/typeorm/entity/db-long-running-migration.ts
  components/gitpod-db/src/typeorm/migration/1684251944953-DropLongRunningMigration.ts
  components/server/src/config.ts
  components/server/src/server.ts
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/types.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XL, team: webapp

#17648 Fix new workspace class element overflow
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
Labels: size/S, team: webapp

#17655 [ws-daemon] Log backup failure error
  components/ws-daemon/pkg/controller/workspace_operations.go
Labels: size/XS, team: workspace

#17654 [server] verify members of paying orgs
  components/server/src/auth/verification-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17656 [server] Fix workspace start mutex initial lock duration
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: webapp

#17641 Update copy around on Delete Org modal
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/XS, team: webapp

#17666 Update SSO Setup learn more link
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
Labels: size/XS, team: webapp

#17601 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/common/GitpodConnectionHandleFactory.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectionHandle.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnectionHandle.kt
  components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml
Labels: size/L, team: IDE, editor: jetbrains

#17668 Fixing unstable react context values and adding lint rule
  components/dashboard/.eslintrc.js
  components/dashboard/src/admin-context.tsx
  components/dashboard/src/payment-context.tsx
  components/dashboard/src/projects/project-context.tsx
Labels: size/M, team: webapp

#17616 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17665 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/S, team: IDE, editor: jetbrains

#17663 [papi] Remove rogue print from PAT tests
  components/public-api-server/pkg/auth/personal_access_token_test.go
Labels: size/XS, team: webapp

#17650 [server] Delete webhook events directly
  components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
Labels: size/S, team: webapp

#17657 [installer] default the FSShiftMethod to ShiftFS
  install/installer/pkg/config/v1/config.go
Labels: size/XS, team: workspace

#17678 [idp] Add email to ID token
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
Labels: size/M, team: webapp

#17676 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17651 [server] delete duplicate auth provider
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-db/src/typeorm/migration/1684328022688-AuthProviderUniqueHostName.ts
  components/server/src/auth/auth-provider-service.ts
Labels: size/M, team: webapp

#17690 Revert "use nftPortForwarder"
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/ports/ports.go
Labels: size/L, team: IDE

#17675 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17633 [server] update OIDC users on sign-in (email) – WEB-370
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/user/user-service.ts
Labels: size/M, team: webapp

#17659 Implement deactivation of OIDC client configs – WEB-333
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config_test.go
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
  components/public-api-server/pkg/oidc/service.go
Labels: size/L, team: webapp

#17700 [db] removed unused instance join
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
Labels: size/S, team: webapp

#17664 Initial commit of the scrubber
  .github/CODEOWNERS
  components/scrubber/BUILD.yaml
  components/scrubber/README.md
  components/scrubber/config.go
  components/scrubber/example_test.go
  components/scrubber/go.mod
  components/scrubber/go.sum
  components/scrubber/sanitisation.go
  components/scrubber/sanitisation_test.go
  components/scrubber/scrubber.go
  components/scrubber/scrubber_test.go
Labels: size/XXL

#17698 [periodic deleter] remove unmanaged tables
  components/gitpod-db/src/tables.ts
Labels: size/M, team: webapp

#17699 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains

#17677 Update PR template
  .github/pull_request_template.md
Labels: size/S

#17701 [dashboard] name org in create dialog
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: webapp

#17658 Touch up SSO Config changes
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/toasts/Toasts.tsx
  components/dashboard/src/components/toasts/reducer.ts
  components/dashboard/src/teams/sso/ActivateConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
  components/dashboard/src/teams/sso/use-verify-client.ts
Labels: size/XL, team: webapp

#17667 Handle an expired admin user link
  .pre-commit-config.yaml
  components/dashboard/BUILD.yaml
  components/dashboard/src/App.tsx
  components/dashboard/src/error-pages/DefaultError.tsx
  components/dashboard/src/error-pages/ErrorPageLayout.tsx
  components/dashboard/src/error-pages/ErrorPages.tsx
  components/dashboard/src/error-pages/ExpiredOTS.tsx
  components/dashboard/src/images/404.webp
  components/dashboard/src/images/404@2x.webp
  components/dashboard/src/images/cubicle-dark.png
  components/dashboard/src/images/cubicle-dark.webp
  components/dashboard/src/images/cubicle-dark@2x.png
  components/dashboard/src/images/cubicle-dark@2x.webp
  components/dashboard/src/images/cubicle.png
  components/dashboard/src/images/cubicle.webp
  components/dashboard/src/images/cubicle@2x.png
  components/dashboard/src/images/cubicle@2x.webp
  components/dashboard/src/index.tsx
  components/dashboard/src/login/SetupPending.tsx
  components/server/src/user/user-controller.ts
Labels: size/L, team: webapp

#17660 Auth window message success handlers running more than once
  components/dashboard/src/provider-utils.tsx
Labels: size/S, team: webapp

#17702 [server] run status updater less frequently
  components/server/src/prebuilds/prebuilt-status-maintainer.ts
Labels: size/XS, team: webapp

#17704 [server] garbage collect ws less often
  components/server/src/jobs/runner.ts
  components/server/src/jobs/workspace-gc.ts
  install/installer/pkg/components/server/configmap.go
Labels: size/S, team: webapp

#17693 [ws-manager-mk2] Remove maintenance CM from installer
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/pkg/maintenance/maintenance.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/constants.go
Labels: size/L, team: workspace

#17628 [server] Use JWTs for Sign-in flow state WEB-365
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket/bitbucket-auth-provider.ts
  components/server/src/container-module.ts
  components/server/src/dev/authenticator-dev.ts
  components/server/src/github/github-auth-provider.ts
  components/server/src/gitlab/gitlab-auth-provider.ts
Labels: size/L, team: webapp

#17494 [server] Migrate snapshots jobs WEB-225
  components/server/src/container-module.ts
  components/server/src/jobs/runner.ts
  components/server/src/jobs/snapshots.ts
  components/server/src/server.ts
  components/server/src/workspace/snapshot-service.ts
Labels: size/L, team: webapp

#17705 Feature Flag Cleanup
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/onboarding/use-show-user-onboarding.ts
Labels: size/S, team: webapp

#17684 Improve Modal a11y
  components/dashboard/package.json
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/contexts/TestContext.tsx
  components/dashboard/src/data/tracking/track-event-mutation.ts
  components/dashboard/src/user-settings/Integrations.test.tsx
  yarn.lock
Labels: size/XL, team: webapp

#17672 Show migration message after migration
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/whatsnew/MigrationPage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/migration/user-to-team-migration-service.spec.db.ts
  components/server/src/migration/user-to-team-migration-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17692 [server] install job for orgonly migration
  components/dashboard/src/app/AppBlockingFlows.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/OrgRequiredRoute.tsx
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/dedicated-setup/GettingStartedStep.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/SetupLayout.tsx
  components/server/.vscode/launch.json
  components/server/src/container-module.ts
  components/server/src/jobs/org-only-migration-job.spec.db.ts
  components/server/src/jobs/org-only-migration-job.ts
  components/server/src/jobs/runner.ts
Labels: size/XL, team: webapp

#17683 Correctly infer branch names for SSO users
  components/server/src/workspace/context-parser.spec.ts
  components/server/src/workspace/context-parser.ts
Labels: size/M, team: webapp

#17703 Update new workspace page header
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: webapp

#17721 [dashboard] create ws page - disable components
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: webapp

#17722 [db] optimize often used qery
  components/gitpod-db/src/typeorm/app-installation-db-impl.ts
Labels: size/S, team: webapp

#17731 Add default value for manually GHA running
  .github/workflows/ide-integration-tests.yml
Labels: size/XS, team: IDE
