Repository gitpod-io/gitpod, pull requests merged in 2023-04, with the labels that each got.

#17117 [preview] add local ssh dns to preview env
  dev/preview/infrastructure/modules/dns/dns.tf
Labels: size/S, team: IDE, release-note-none

#17091 [ws-manager-mk2] Extract headless task failure (WKS-18)
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/S, team: workspace, release-note-none

#17093 [ws-manager-mk2] Dashboard controller heatmaps (WKS-21)
  operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
  operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json
Labels: size/XXL, team: workspace, release-note-none

#17097 [ws-manager-mk2] Fix git status
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-manager-mk2/service/manager.go
  test/README.md
  test/tests/components/ws-manager/git_status_test.go
Labels: size/L, team: workspace, release-note-none

#17129 [server] don't wait for queued prebuilds
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#17030 Adding Toasts
  components/dashboard/src/components/toasts/Toast.tsx
  components/dashboard/src/components/toasts/Toasts.tsx
  components/dashboard/src/components/toasts/reducer.ts
  components/dashboard/src/data/current-user/update-mutation.ts
  components/dashboard/src/index.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  components/dashboard/tailwind.config.js
Labels: size/XL, team: webapp, release-note-none

#17133 [server] Remove OSS check (WEB-91)
  components/ee/payment-endpoint/src/accounting/subscription-service.ts
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/oss-allowlist-db.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/entity/db-oss-allowlist.ts
  components/gitpod-db/src/typeorm/oss-allowlist-db-impl.ts
  components/server/ee/src/user/user-service.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp, release-note-none

#17139 Add /hold to all PRs by default (through template) (WEB-92)
  .github/pull_request_template.md
Labels: size/XS, team: webapp, release-note-none

#17145 Add new feature for custom workspace network CIDR
  components/ws-daemon/nsinsider/main.go
  components/ws-daemon/pkg/content/hooks.go
  components/ws-daemon/pkg/content/service.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-daemon/pkg/iws/iws.go
  install/installer/pkg/cluster/checks.go
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/v1/experimental/validation.go
Labels: size/L, team: workspace, release-note-none

#17125 Update delete account button spacing
  components/dashboard/src/user-settings/Account.tsx
Labels: size/XS, team: webapp, release-note-none

#17114 [ws-manager-mk2] Refactor metrics with EverReady condition
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
Labels: size/L, team: workspace, release-note-none

#17152 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#17135 [Create WS] Various fixes
  components/dashboard/src/data/workspaces/resolve-context-query.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp, release-note-none

#17094 [usage] Add server address to config - WEB-94
  components/usage/pkg/server/server.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/common/net.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/M, team: webapp, release-note-none

#17039 [usage] Implement charge dispute handling - WEB-94
  components/gitpod-cli/go.mod
  components/usage/BUILD.yaml
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/apiv1/fixtures/stripe_on_charge_dispute.yaml
  components/usage/pkg/server/server.go
  components/usage/pkg/stripe/stripe.go
  install/installer/go.mod
  install/installer/go.sum
Labels: size/XXL, team: webapp, team: IDE, release-note-none

#17156 Fixing lint errors in dashboard
  components/dashboard/src/admin/License.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/InfoBox.tsx
  components/dashboard/src/components/MonacoEditor.tsx
  components/dashboard/src/components/PendingChangesDropdown.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/user-settings/selectClass.tsx
Labels: size/M, team: webapp, release-note-none

#16813 Migrate all checkbox inputs to the `CheckBoxInput` component
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/Notifications.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
Labels: community-contribution, size/XL, do-not-merge/hold, release-note

#17098 Update github.com/google/nftables to v0.1.0
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/nsinsider/go.mod
  components/ws-daemon/nsinsider/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/XS, team: workspace, release-note-none

#17166 VS Code Browser release `1.77.2`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#17174 [dev] Add redis to workspace image
  dev/image/Dockerfile
Labels: size/XS, release-note-none

#17175 [stripe] Actually call the billing service :facepalm: WEB-62
  components/public-api-server/pkg/billingservice/client.go
Labels: size/S, team: webapp, release-note-none

#17171 Migrate checkbox component
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/forms/InputField.tsx
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/Notifications.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
Labels: size/XL, team: webapp, release-note-none

#17170 Fixing remaining dashboard lint errors
  components/dashboard/src/components/LinkButton.tsx
  components/dashboard/src/user-settings/Plans.tsx
  components/dashboard/src/utils.ts
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: size/L, team: webapp, release-note-none

#17180 Default to release note NONE in PR template
  .github/pull_request_template.md
Labels: size/XS, team: webapp, release-note-none

#17155 Top Level ErrorBoundary second attempt
  components/dashboard/src/App.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/Setup.tsx
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/components/error-boundaries/ReloadPageErrorBoundary.tsx
  components/dashboard/src/hooks/use-user-loader.ts
  components/dashboard/src/index.tsx
Labels: size/XL, team: webapp, release-note-none

#17074 Implement user account verification with LinkedIn during onboarding
  components/dashboard/package.json
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/images/sign-in-with-linkedin.svg
  components/dashboard/src/onboarding/LinkedInBanner.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/onboarding/StepUserInfo.tsx
  components/dashboard/src/onboarding/UserOnboarding.tsx
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/linked-in-profile-db.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/entity/db-linked-in-profile.ts
  components/gitpod-db/src/typeorm/linked-in-profile-db-impl.ts
  components/gitpod-db/src/typeorm/migration/1680096507296-LinkedInProfile.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/config.ts
  components/server/src/container-module.ts
  components/server/src/linkedin-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/types.go
  install/installer/pkg/config/v1/experimental/experimental.go
  yarn.lock
Labels: size/XL, team: webapp, release-note

#17181 [server] Log explicitly when user is blocked
  components/server/src/api/user.ts
Labels: size/XS, team: webapp, release-note-none

#17182 [usage] Log default price applied when no config exists
  components/usage/pkg/apiv1/pricer.go
Labels: size/XS, team: webapp, release-note-none

#17186 Delete the obsolete `CheckBox` component
  components/dashboard/src/components/CheckBox.tsx
Labels: community-contribution, size/M, do-not-merge/hold, release-note

#17192 VS Code Browser release `1.77.3`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#17195 wrap ff around connect with linkedin
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/onboarding/StepUserInfo.tsx
  components/dashboard/src/onboarding/UserOnboarding.tsx
Labels: size/M, team: webapp, release-note-none

#17159 [dashboard] handle context resolution errors
  components/dashboard/src/Login.tsx
  components/dashboard/src/data/auth-providers/auth-provider-query.ts
  components/dashboard/src/data/workspaces/resolve-context-query.ts
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp, release-note-none

#17165 Update new workspace button style
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: webapp, release-note

#17206 [dashboard] use workspace class component
  components/dashboard/src/components/WorkspaceClass.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/selectClass.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: webapp, release-note-none

#17208 [dashboard] create ws keep button enabled
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: webapp, release-note-none

#17176 Remove unused PodSecurityPolicy feature
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager/cmd/integrationtest-objs.go
  components/ws-manager/pkg/manager/create.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/display.go
  install/installer/pkg/components/agent-smith/role.go
  install/installer/pkg/components/cluster/clusterrole.go
  install/installer/pkg/components/cluster/objects.go
  install/installer/pkg/components/cluster/podsecuritypolicies.go
  install/installer/pkg/components/image-builder-mk3-wsman/clusterrole.go
  install/installer/pkg/components/image-builder-mk3-wsman/objects.go
  install/installer/pkg/components/image-builder-mk3/clusterrole.go
  install/installer/pkg/components/registry-facade/clusterrole.go
  install/installer/pkg/components/registry-facade/objects.go
  install/installer/pkg/components/registry-facade/podsecuritypolicy.go
  install/installer/pkg/components/workspace/objects.go
  install/installer/pkg/components/workspace/podsecuritypolicies.go
  install/installer/pkg/components/workspace/role.go
  install/installer/pkg/components/workspace/rolebinding.go
  install/installer/pkg/components/ws-daemon/clusterrole.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/deprecations.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XXL, team: workspace, release-note-none

#17209 Persist new workspace contextURL on org change
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: webapp, release-note-none

#17212 [pr] update desc with summary
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/pull_request_template.md
  .github/workflows/build.yml
Labels: size/M, release-note-none

#17205 [server] Generate key-pair for signing JWT sessions WEB-100
  install/installer/pkg/components/server/authpki.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/objects.go
Labels: size/M, team: webapp, release-note-none

#17214 [server] Load auth-pki into server config - WEB-100
  components/server/src/config.ts
  install/installer/pkg/components/server/authpki.go
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/configmap_test.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/types.go
Labels: size/L, team: webapp, release-note-none

#17217 [dasboard/server] remove notifications
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/SwitchToPAYG.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/gitpod-messagebus/src/messagebus.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/messaging/local-message-broker.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/messagebus-integration.ts
Labels: size/XL, team: webapp, release-note-none

#17201 Seperate mk1 and mk2 deployment
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/components-workspace/components.go
  install/installer/pkg/components/image-builder-mk3-wsman/configmap.go
  install/installer/pkg/components/image-builder-mk3-wsman/constants.go
  install/installer/pkg/components/image-builder-mk3-wsman/deployment.go
  install/installer/pkg/components/image-builder-mk3-wsman/networkpolicy.go
  install/installer/pkg/components/image-builder-mk3-wsman/objects.go
  install/installer/pkg/components/image-builder-mk3-wsman/rolebinding.go
  install/installer/pkg/components/image-builder-mk3-wsman/tlssecret.go
  install/installer/pkg/components/image-builder-mk3/configmap.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/registry-facade/configmap.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  install/installer/pkg/components/ws-manager/objects.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XXL, team: workspace, release-note-none

#17218 [papi] Mount Auth PKI - WEB-101
  components/public-api/go/config/config.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/public-api-server/authpki.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
  install/installer/pkg/components/server/authpki.go
  install/installer/pkg/components/server/constants.go
Labels: size/L, team: webapp, release-note-none

#17204 Update runc to v1.1.6
  components/docker-up/dependencies.sh
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/leeway.Dockerfile
  install/installer/go.mod
  install/installer/go.sum
Labels: size/M, team: workspace, release-note-none

#17216 [dashboard] Remove "/switch-to-payg"
  components/dashboard/src/SwitchToPAYG.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/user-settings/settings.routes.ts
Labels: size/XXL, team: webapp, release-note-none

#17220 Rephrase credits to hours in LinkedIn onboarding
  components/dashboard/src/onboarding/LinkedInBanner.tsx
  components/dashboard/src/onboarding/StepUserInfo.tsx
Labels: size/XS, team: webapp, release-note-none

#17210 [preview] Use cert-manager namespace for satellite, not certmanager namespace
  dev/preview/workflow/config/monitoring-satellite.yaml
  dev/preview/workflow/preview/deploy-monitoring-satellite.sh
Labels: size/XS, release-note-none, team: security-infrastructure-and-delivery

#17162 [proxy] add analytics endpoint
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/pull_request_template.md
  .github/workflows/build.yml
  components/common-go/analytics/analytics.go
  components/gitpod-protocol/src/util/analytics.ts
  components/proxy/Dockerfile
  components/proxy/conf/Caddyfile
  components/proxy/plugins/analytics/analytics.go
  components/proxy/plugins/analytics/analytics_test.go
  components/proxy/plugins/analytics/go.mod
  components/proxy/plugins/analytics/go.sum
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/common/common.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/experimental/experimental.go
  test/run.sh
Labels: size/XL, team: webapp, release-note-none, team: staff-engineers

#17207 [installer] add flags with ability to overwrite [repository, domain] in the config file for `mirror list`
  install/installer/cmd/mirror_list.go
Labels: size/S, release-note-none, team: security-infrastructure-and-delivery

#17200 [server] Set JWT cookie on sign-in WEB-100
  components/server/package.json
  components/server/src/auth/jwt.spec.ts
  components/server/src/auth/jwt.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/container-module.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/session-handler.ts
Labels: size/L, team: webapp, release-note-none

#17219 [installer] Add key id for each auth keypair - WEB-100
  components/public-api/go/config/config.go
  components/server/src/config.ts
  install/installer/pkg/components/auth/constants.go
  install/installer/pkg/components/auth/keypair.go
  install/installer/pkg/components/auth/objects.go
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/public-api-server/authpki.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/configmap_test.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/objects.go
  install/installer/pkg/components/server/types.go
Labels: size/L, team: webapp, release-note-none

#17187 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/internal/GitpodIgnoredPortsForNotificationServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/internal/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/internal/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/LatestGitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/StableGitpodIgnoredPortsForNotificationServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/StableGitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: IDE, release-note, editor: jetbrains

#17226 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#17230 [server] migrate new users
  components/server/src/user/user-service.ts
Labels: size/XS, team: webapp, release-note-none

#17233 [installer] Remove payment endpoint - WEB-144
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/proxy/configmap.go
  install/installer/pkg/components/proxy/templates/configmap/vhost.payment-endpoint.tpl
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/usage/networkpolicy.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: webapp, release-note-none

#17236 [server] remove /tos endpoint – WEB-121
  components/server/ee/src/container-module.ts
  components/server/ee/src/user/user-service.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/express.ts
  components/server/src/terms/tos-flow.ts
  components/server/src/user/user-controller.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, release-note-none

#17239 [dashboard] Remove chargebee references I
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/user-settings/ChargebeeTeams.tsx
  components/dashboard/src/user-settings/Plans.tsx
Labels: size/XXL, team: webapp, release-note-none

#17238 [server] clean up auth provider
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket/bitbucket-auth-provider.ts
  components/server/src/github/github-auth-provider.ts
  components/server/src/gitlab/gitlab-auth-provider.ts
Labels: size/L, team: webapp, release-note-none

#17243 [supervisor] log potentially leaking grpc streams
  components/supervisor/pkg/supervisor/notification.go
  components/supervisor/pkg/supervisor/services.go
Labels: size/XS, team: IDE, release-note-none

#17231 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#17245 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#17232 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#17249 Remove release note from PR template
  .github/pull_request_template.md
Labels: size/S

#17250 [installer] Remove chargebee refs - WEB-144
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/types.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: webapp, team: IDE

#17251 [server] Remove chargebee config reading WEB-144
  components/server/src/config.ts
Labels: size/XS, team: webapp

#17253 [server] Remove terms acceptance db model - WEB-167
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/terms-acceptance-db.ts
  components/gitpod-db/src/typeorm/entity/db-terms-acceptance-entry.ts
  components/gitpod-db/src/typeorm/terms-acceptance-db-impl.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp

#17255 [db] Remove theia plugin db model - WEB-168
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/theia-plugin-db.ts
  components/gitpod-db/src/typeorm/entity/db-theia-plugin.ts
  components/gitpod-db/src/typeorm/theia-plugin-db-impl.ts
  components/gitpod-protocol/src/protocol.ts
Labels: size/L, team: webapp

#17254 [db] Drop d_b_terms_acceptance_entry
  components/gitpod-db/src/typeorm/migration/1681805965892-DropTermsAcceptance.ts
Labels: size/S, team: webapp

#17252 [server] Remove TermsProvider - unused - WEB-167
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/container-module.ts
  components/server/src/terms/terms-provider.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17257 [db] Drop d_b_theia_plugin - WEB-168
  components/gitpod-db/src/typeorm/migration/1681806678725-DropTheiaPlugin.ts
Labels: size/S, team: webapp

#17258 [db] Remove user message view db model - WEB-172
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/entity/db-user-message-view-entry.ts
  components/gitpod-db/src/typeorm/user-message-views-db-impl.ts
  components/gitpod-db/src/user-message-views-db.spec.db.ts
  components/gitpod-db/src/user-message-views-db.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17256 [server] remove obsolete loginContextMatcher
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/container-module.ts
  components/server/src/user/tos-cookie.ts
  components/server/src/user/user-controller.ts
Labels: size/M, team: webapp

#17259 [db] Drop d_b_user_message_view_entry - WEB-172
  components/gitpod-db/src/typeorm/migration/1681808788247-DropUserMessageView.ts
Labels: size/S, team: webapp

#17261 🧹 remove obsolete ToS/terms code
  components/dashboard/public/tos/index.html
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M

#17266 [dashboard] Fix broken /usage redirect
  components/dashboard/src/app/AppRoutes.tsx
Labels: size/XS, team: webapp

#17262 Purge all Chargebee-related API methods
  components/dashboard/src/service/service-mock.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp

#17269 Remove BillingMode.Chargebee
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
  components/gitpod-protocol/src/billing-mode.ts
  components/server/ee/src/billing/billing-mode.spec.db.ts
  components/server/ee/src/billing/billing-mode.ts
  components/server/ee/src/billing/entitlement-service-chargebee.ts
  components/server/ee/src/billing/entitlement-service.ts
  components/server/ee/src/container-module.ts
  components/server/src/user/user-service.ts
Labels: size/XXL, team: webapp

#17271 [server] Remove reading of license file - WEB-171
  components/server/src/config.ts
Labels: size/S, team: webapp

#17272 [server] Remove chargebee coupon computer
  components/server/ee/src/container-module.ts
  components/server/ee/src/user/coupon-computer.ts
Labels: size/M, team: webapp

#17263 [server] Remove monitoring EE
  components/server/ee/src/container-module.ts
  components/server/ee/src/monitoring-endpoint-ee.ts
  components/server/src/monitoring-endpoints.ts
Labels: size/M, team: webapp

#17244 Update code-nightly
  .github/workflows/code-nightly.yml
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#17276 [server] Delete UserCounter
  components/server/ee/src/container-module.ts
  components/server/ee/src/user/user-counter.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/ee/src/workspace/workspace-factory.ts
Labels: size/M, team: webapp

#17264 [server] Remove license db model - WEB-171
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/license-db.ts
  components/gitpod-db/src/traced-db.ts
  components/gitpod-db/src/typeorm/license-db-impl.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17279 [server] Remove languages provider
  components/server/src/bitbucket-server/bitbucket-server-container-module.ts
  components/server/src/bitbucket-server/bitbucket-server-language-provider.ts
  components/server/src/bitbucket/bitbucket-container-module.ts
  components/server/src/bitbucket/bitbucket-language-provider.spec.ts
  components/server/src/bitbucket/bitbucket-language-provider.ts
  components/server/src/github/github-container-module.ts
  components/server/src/github/languages-provider.ts
  components/server/src/gitlab/gitlab-container-module.ts
  components/server/src/gitlab/languages-provider.ts
  components/server/src/repohost/index.ts
  components/server/src/repohost/languages-provider.ts
  components/server/src/repohost/repository-host.ts
Labels: size/L, team: webapp

#17285 [dashboard] Remove superfluous usage_view feature flag
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/XS, team: webapp

#17240 `experimental` IDEs feature flag
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/gitpod-protocol/src/ide-protocol.ts
  components/ide-service-api/go/config/ideconfig.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/S, team: webapp, team: IDE, release-note-none

#17289 [server] fix prebuild organizationId
  components/server/ee/src/prebuilds/prebuild-manager.ts
Labels: size/S, team: webapp

#17288 Revert making VS Code Browser experimental
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/XS, team: IDE

#17284 [server] Remove usage of do_not_wait_for_ws_manager flag
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp

#17260 bump up gitpod code extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#17268 SSO – check for OIDC Discovery - WEB-165
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/L, team: webapp

#17295 [server] Remove UserDeletionService EE
  components/server/ee/src/container-module.ts
  components/server/ee/src/user/user-deletion-service.ts
  components/server/src/user/user-deletion-service.ts
Labels: size/M, team: webapp

#17299 [lint] golangci - exclude typecheck error by regex
  WORKSPACE.yaml
Labels: size/XS

#17290 [yarn] update yarn.lock
  yarn.lock
Labels: size/M

#17286 [db] Purge all Chargebee-related DB tables
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/migration/1681829114367-DropChargebeeSubscriptionTables.ts
  components/gitpod-db/src/typeorm/migration/1681829127935-DropPendingGitHubEvents.ts
Labels: size/L, team: webapp

#17277 Fix typo in log message
  dev/preview/workflow/lib/k8s-util.sh
Labels: size/XS

#17312 [gha] Fix property propagation to "deploy-gitpod" action
  .github/actions/deploy-gitpod/metadata.yml
  .github/workflows/build.yml
Labels: size/S

#17308 [public-api] JWT Signer & Verifier WEB-101
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/auth/jwt.go
  components/public-api-server/pkg/auth/jwt_test.go
  components/public-api-server/pkg/identityprovider/idp_test.go
  components/public-api-server/pkg/oidc/state_jwt.go
  components/public-api-server/pkg/oidc/state_jwt_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/L, team: webapp

#17315 [supervisor] small fixes of previous leftovers
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE

#17311 [server] stop logging 0 items
  components/gitpod-db/src/periodic-deleter.ts
Labels: size/XS, team: webapp

#17316 [wsman-mk2] Set workspace class environment variables
  components/ws-manager-mk2/controllers/create.go
Labels: size/XS, team: workspace, feature: ws-manager-mk2

#17298 [server] use options from last instances on start
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/ide-service-api/go/ide.pb.go
  components/ide-service-api/go/ide_grpc.pb.go
  components/ide-service-api/ide.proto
  components/ide-service-api/typescript/src/ide.pb.ts
  components/ide-service/pkg/server/server.go
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw_goland.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw_invalid.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw_invalid_with_code.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw_invalid_with_code_desktop.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_gw_invalid_with_goland.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_invalid.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_referrer_invalid_with_intellij.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_intellij.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_intellij_latest.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_with_intellij_config.golden
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp, team: IDE

#17309 adding backend support for payment intents
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/usage/v1/billing.proto
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/XL, team: webapp

#17324 Filter out IDEs on the backend
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/ide-service-api/go/ide.pb.go
  components/ide-service-api/ide.proto
  components/ide-service-api/typescript/src/ide.pb.ts
  components/ide-service/pkg/server/server.go
  components/server/src/ide-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, team: IDE

#17302 [server] Metrics for sessions with JWTs WEB-102
  components/server/src/auth/jwt.spec.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/session-handler.ts
Labels: size/S, team: webapp

#17329 Revert "[server] Metrics for sessions with JWTs WEB-102"
  components/server/src/auth/jwt.spec.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/session-handler.ts
Labels: size/S, team: webapp

#17188 Remove the obsolete `CheckBox` component
  components/dashboard/src/components/CheckBox.tsx
Labels: size/M, team: webapp, release-note-none

#17327 [public-api] Refactor JWT Sign/Verify to be reusable for OIDC - WEB-206
  components/public-api-server/pkg/auth/jwt.go
  components/public-api-server/pkg/auth/jwt_test.go
  components/public-api-server/pkg/auth/session_jwt.go
  components/public-api-server/pkg/auth/session_jwt_test.go
  components/public-api-server/pkg/jws/jwstest/testkeyset.go
  components/public-api-server/pkg/jws/keyset.go
  components/public-api-server/pkg/jws/rsa256.go
  components/public-api-server/pkg/jws/rsa256_test.go
  components/public-api-server/pkg/jws/types.go
  components/public-api-server/pkg/server/server.go
Labels: size/XXL, team: webapp

#17321 🧹 Remove deprecated and unused getPortAuthenticationToken method
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager/pkg/manager/testdata/status_cannotPull_004_CREATING00.json
  components/ws-manager/pkg/manager/testdata/status_cannotPull_005_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_contentInitFailed_005_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED02.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED03.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING01.json
  components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.json
  components/ws-manager/pkg/manager/testdata/status_failedLogs_RUNNING00.json
  components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_ideFailedToStart_005_RUNNING00.json
  components/ws-manager/pkg/manager/testdata/status_prebuildFail_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_prebuildFail_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING01.json
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING02.json
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess_STOPPED00.json
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_stoppedByRequest_000_RUNNING00.json
  components/ws-manager/pkg/manager/testdata/status_stuckInStopping_STOPPING00.json
  components/ws-manager/pkg/manager/testdata/status_workspaceCompleted_01.json
  components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.json
  dev/loadgen/cmd/run.go
  dev/loadgen/configs/prod-benchmark.yaml
  dev/loadgen/configs/workspace-preview-benchmark.yaml
Labels: size/L, team: webapp, team: workspace

#17335 [integration-test] remove plan changing
  test/pkg/integration/apis.go
  test/tests/ide/jetbrains/gateway_test.go
  test/tests/workspace/contexts_test.go
Labels: size/M

#17318 [server] Only try to delete Stripe subscription if the user's BillingMode is "usage-based"
  components/server/ee/src/user/stripe-service.ts
  components/server/src/user/user-deletion-service.ts
Labels: size/M, team: webapp

#17332 [installer] Add JWT cookie opts to config WEB-101
  components/public-api/go/config/config.go
  components/server/src/auth/login-completion-handler.ts
  components/server/src/config.ts
  components/server/src/session-handler.ts
  install/installer/pkg/components/auth/config.go
  install/installer/pkg/components/auth/config_test.go
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/server/configmap_test.go
Labels: size/L, team: webapp

#17317 [wsman-mk2] Use mk2 tls certificates for server and bridge
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/S, team: webapp, team: workspace, feature: ws-manager-mk2

#17196 Add the Browser Terminal as an IDE
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  components/ide-proxy/static/image/ide-logo/terminal.svg
  components/ide-service-api/go/ide.pb.go
  components/ide-service-api/ide.proto
  components/ide-service-api/typescript/src/ide.pb.ts
  components/ide-service/pkg/server/server.go
  components/server/src/ide-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/supervisor/frontend/src/shared/loading-frame.ts
  install/installer/pkg/components/blobserve/configmap.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/L, team: webapp, team: IDE, release-note-none

#17331 [installer] Remove OIDC secret from public-api WEB-206
  components/public-api/go/config/config.go
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
  install/installer/pkg/components/public-api-server/objects_test.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: webapp

#17340 [server] Move snapshot service out of EE
  components/server/ee/src/container-module.ts
  components/server/ee/src/server.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/container-module.ts
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/snapshot-service.ts
Labels: size/L, team: webapp

#17343 [dashboard] Remove local-preview-alert WEB-215
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/LocalPreviewAlert.tsx
  components/dashboard/src/utils.ts
Labels: size/M, team: webapp

#17160 [server] Unimplemented workspaces service
  components/server/src/api/server.ts
  components/server/src/api/workspaces.ts
  components/server/src/container-module.ts
Labels: size/M, team: webapp, release-note-none

#17322 [admin] show workspace instances and organization
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/index.tsx
  components/gitpod-protocol/src/admin-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17338 [server] Move BlockedUserFilter out of ee
  components/server/ee/src/auth/email-domain-service.ts
  components/server/ee/src/container-module.ts
  components/server/src/auth/blocked-user-filter.ts
  components/server/src/container-module.ts
  components/server/src/user/user-service.ts
Labels: size/M, team: webapp

#17339 [server] Remove Workspace Factory EE, merge with standard
  components/server/ee/src/container-module.ts
  components/server/ee/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-factory.ts
Labels: size/XXL, team: webapp

#17341 [server] Move some admin rpcs to non EE
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp

#17346 [server] Move remaining trivial RPCs away from EE
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp

#17348 [dashboard] fix ws query invalidation
  components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
  components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
  components/dashboard/src/data/workspaces/list-workspaces-query.ts
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
Labels: size/S, team: webapp

#17352 Add focus ring for `<SelectableCardSolid>`
  components/dashboard/src/components/SelectableCardSolid.tsx
Labels: size/S, team: webapp

#17323 Add new payment validation flow in Dashboard
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
  components/dashboard/src/components/billing/use-stripe-appearance.ts
  components/dashboard/src/components/billing/use-stripe-promise.ts
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/data/billing/create-hold-payment-intent-mutation.ts
  components/dashboard/src/data/billing/stripe-key-query.ts
  components/dashboard/src/payment-context.tsx
Labels: size/XL, team: webapp

#17354 [server] Move prebuilds out of EE
  components/server/ee/src/auth/host-container-mapping.ts
  components/server/ee/src/bitbucket-server/container-module.ts
  components/server/ee/src/bitbucket/container-module.ts
  components/server/ee/src/container-module.ts
  components/server/ee/src/github/container-module.ts
  components/server/ee/src/gitlab/container-module.ts
  components/server/ee/src/server.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/bitbucket-server/bitbucket-server-container-module.ts
  components/server/src/bitbucket/bitbucket-app-support.ts
  components/server/src/bitbucket/bitbucket-container-module.ts
  components/server/src/container-module.ts
  components/server/src/github/github-app-support.ts
  components/server/src/github/github-container-module.ts
  components/server/src/gitlab/gitlab-app-support.spec.ts
  components/server/src/gitlab/gitlab-app-support.ts
  components/server/src/gitlab/gitlab-container-module.ts
  components/server/src/prebuilds/bitbucket-app-example-push.json
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/bitbucket-server-service.spec.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/prebuilds/bitbucket-service.ts
  components/server/src/prebuilds/github-app-rules.ts
  components/server/src/prebuilds/github-app.spec.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/gitlab-service.ts
  components/server/src/prebuilds/incremental-prebuilds-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/prebuilds/prebuilt-status-maintainer.ts
  components/server/src/prebuilds/start-prebuild-context-parser.ts
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
Labels: size/XXL, team: webapp

#17319 [orgs-only] Show Information before migration.
  components/dashboard/src/App.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/whatsnew/MigrationPage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17337 [preview] Configure with-dedicated-emulation
  components/gitpod-db/src/typeorm/migration/1682403474866-AdminUserOnboardedTimestamp.ts
  components/gitpod-protocol/src/protocol.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, team: webapp

#17336 bump up code
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#17344 [wsman-mk2] Publish workspace activity metric
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace, feature: ws-manager-mk2

#17367 [server] Remove enforcement endpoint WEB-219
  components/server/src/container-module.ts
  components/server/src/server.ts
  components/server/src/user/enforcement-endpoint.ts
  components/server/src/user/user-controller.ts
Labels: size/XL, team: webapp

#17059 New roles
  components/gitpod-protocol/src/permission.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-download-service.ts
Labels: size/S, team: webapp, do-not-merge/release-note-label-needed

#17371 [org-only] relax org name restriction
  components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
Labels: size/M, team: webapp

#17362 [ws-manager-mk2] Add alerts
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
  operations/observability/mixins/workspace/rules/central/ws-manager.yaml
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/L, team: workspace, feature: ws-manager-mk2

#17369 [server] Setup redis mutex to replace leader election
  components/server/package.json
  components/server/src/config.ts
  components/server/src/container-module.ts
  components/server/src/mutex/redlock.ts
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/redis/networkpolicy.go
  install/installer/pkg/components/redis/objects.go
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/configmap_test.go
  install/installer/pkg/components/server/types.go
  yarn.lock
Labels: size/L, team: webapp

#17377 Update Gitpod code
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#17390 Stop asking for company website during user onboarding
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/gitpod-protocol/src/protocol.ts
Labels: size/S, team: webapp

#17358 [dashboard] send heartbeat telemetry
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/frontend-dashboard-service.ts
Labels: size/M, team: webapp, team: IDE

#17391 [server] Wrap using redis mutex API and catch quorum error WEB-229
  components/server/src/redis/mutex.ts
  components/server/src/workspace/garbage-collector.ts
Labels: size/M, team: webapp

#17394 [db] Unblock admin-user by default
  components/gitpod-db/src/typeorm/migration/1682510207256-UnblockAdminuser.ts
Labels: size/S, team: webapp

#17397 [server] Disable new setup modal as long as it's an dead end
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17398 [wsgc] fix workspaceForPurging query
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/XS, team: webapp

#17395 [dashboard] allow skipping the migration
  components/dashboard/src/App.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/whatsnew/MigrationPage.tsx
Labels: size/L, team: webapp

#17368 [wsman-mk2] Add overview dashboard
  operations/observability/mixins/cross-teams/dashboards.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview-mk2.json
Labels: size/XXL, team: workspace, feature: ws-manager-mk2

#17375 [ws-manager-mk2] Update workspace success criteria
  operations/observability/mixins/workspace/dashboards/success-criteria.json
Labels: size/XL, team: workspace, feature: ws-manager-mk2

#17400 [db] directly delete workspaces
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/server/src/workspace/workspace-deletion-service.ts
Labels: size/M, team: webapp

#17389 internal analytics endpoint
  components/proxy/conf/Caddyfile
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/proxy/constants.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/proxy/networkpolicy.go
  install/installer/pkg/components/proxy/service.go
Labels: size/M, team: webapp

#17412 [usage] Add redsync dependency - WEB-266
  components/ee/agent-smith/go.mod
  components/ee/agent-smith/go.sum
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/scheduler/mutex.go
  install/installer/go.mod
  install/installer/go.sum
Labels: size/S, team: webapp, team: workspace

#17409 [server] Fix setting jwt cookie maxAge
  components/server/src/auth/login-completion-handler.ts
Labels: size/XS, team: webapp
