Repository gitpod-io/gitpod, pull requests merged in 2023-01, with the labels that each got.

#15540 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15539 fix: regex of workspace ID validator
  components/common-go/namegen/workspaceid.go
  components/common-go/namegen/workspaceid_test.go
Labels: size/S, release-note, team: staff-engineers

#15517 Wrong cloud provider
  install/infra/single-cluster/azure/README.md
Labels: size/XS, release-note-none

#15546 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15547 Update copyright of generated file
  components/gitpod-protocol/go/gitpod-config-types.go
Labels: size/XS, team: webapp, release-note-none

#15456 [public-api] Implement StopWorkspace and use from Dashboard
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#15549 [iam] Add unimplemented CreateOIDCConfig RPC
  components/iam/pkg/apiv1/oidc_config.go
  components/iam/pkg/apiv1/oidc_config_test.go
  components/iam/pkg/server/server.go
Labels: size/M, team: webapp, release-note-none

#15553 Ensure that oom scores are applied
  install/installer/pkg/components/ws-daemon/configmap.go
Labels: size/XS, team: workspace, release-note

#15545 [previewctl] change staleness logic
  dev/preview/previewctl/cmd/stale.go
  dev/preview/previewctl/pkg/preview/status.go
Labels: size/XS, release-note-none, team: devx

#15556 fix: messaging around projects & prebuild error
  components/server/ee/src/prebuilds/prebuild-manager.ts
  components/server/ee/src/prebuilds/start-prebuild-context-parser.ts
Labels: size/XS, team: webapp, release-note-none

#15527 [JetBrains] Avoid shutting down terminals when closing the client
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt
Labels: size/M, team: IDE, release-note, editor: jetbrains

#15559 [ws-manager] remove unneeded metric
  components/ws-manager/pkg/manager/metrics.go
Labels: size/S, team: workspace, release-note-none

#15389 [dashboard] Allow options on ws start (2/2)
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/hooks/use-user-and-teams-loader.ts
  components/dashboard/src/icons/Editor.svg
  components/dashboard/src/icons/Repository.svg
  components/dashboard/src/icons/WorkspaceClass.svg
  components/dashboard/src/index.css
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/Open.tsx
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/gitpod-protocol/src/ide-protocol.ts
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/XXL, team: webapp, release-note, team: delivery-operations-experience

#15560 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15561 fix: trim repo url while open new workspace
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: size/XS, team: webapp, release-note-none

#15555 [public-api] Define DeleteWorkspace
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/workspace-model.ts
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp, release-note-none

#15541 bump: package `@jmondi/oauth2-server`
  components/gitpod-db/package.json
  components/server/package.json
  yarn.lock
Labels: size/M, team: webapp, release-note-none

#15548 Fix the metric workspace_starts_failure_total
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/metrics.go
  components/ws-manager/pkg/manager/status.go
  components/ws-manager/pkg/manager/testdata/status_brokenScheduler_UNKNOWN00.golden
  components/ws-manager/pkg/manager/testdata/status_cannotPull_004_CREATING00.golden
  components/ws-manager/pkg/manager/testdata/status_cannotPull_005_STOPPED00.golden
  components/ws-manager/pkg/manager/testdata/status_contentInitFailed_005_STOPPED00.golden
  components/ws-manager/pkg/manager/testdata/status_errimgpull.golden
  components/ws-manager/pkg/manager/testdata/status_errimgpull_CREATING01.golden
  components/ws-manager/pkg/manager/testdata/status_failedBeforeStopping_explicitFail.golden
  components/ws-manager/pkg/manager/testdata/status_failedLogs_RUNNING00.golden
  components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN01.golden
  components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN02.golden
  components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.golden
  components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.golden
  components/ws-manager/pkg/manager/testdata/status_headless_STOPPING00.golden
  components/ws-manager/pkg/manager/testdata/status_ideFailedToStart_005_RUNNING00.golden
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING01.golden
  components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING02.golden
  components/ws-manager/pkg/manager/testdata/status_regularStart_Initializing00.golden
  components/ws-manager/pkg/manager/testdata/status_stuckInStopping_RUNNING00.golden
  components/ws-manager/pkg/manager/testdata/status_stuckInStopping_STOPPING00.golden
  components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden
  components/ws-manager/pkg/manager/testdata/status_wsstartup_Creating00.golden
  components/ws-manager/pkg/manager/testdata/status_wsstartup_Creating01.golden
Labels: size/L, team: workspace, release-note-none

#15569 [dashboard] Remove outdated UI experiments
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/App.tsx
  components/dashboard/src/experiments.ts
Labels: size/L, team: webapp, release-note

#15439 Use terraform to manage preview environment certificates
  dev/preview/infrastructure/harvester/cert.tf
  dev/preview/infrastructure/harvester/certificate-letsencrypt.tf
  dev/preview/infrastructure/harvester/certificate-zerossl.tf
  dev/preview/infrastructure/harvester/dns.tf
  dev/preview/infrastructure/harvester/provider.tf
  dev/preview/infrastructure/harvester/variables.tf
Labels: meta: never-stale, size/L, release-note-none, team: devx

#15576 ws-manager: add new reason `out-of-space` for workspace_stops_total metric
  components/ws-manager/pkg/manager/metrics.go
Labels: size/XS, team: workspace, release-note-none

#15442 blobserve: dynamically reload Docker auth config
  components/blobserve/cmd/run.go
  components/blobserve/go.mod
Labels: size/M, team: IDE, release-note-none

#15550 [iam] Implement basic OIDC CreateClientConfig RPC
  components/gitpod-db/go/dbtest/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config.go
  components/iam/pkg/apiv1/oidc_config.go
  components/iam/pkg/apiv1/oidc_config_test.go
Labels: size/L, team: webapp, release-note-none

#15450 Learn more section under each settings
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/settings/EnvironmentVariables.tsx
  components/dashboard/src/settings/Integrations.tsx
  components/dashboard/src/settings/PersonalAccessTokens.tsx
  components/dashboard/src/settings/Preferences.tsx
  components/dashboard/src/settings/SSHKeys.tsx
Labels: meta: never-stale, size/M, team: webapp, release-note-none

#15558 [dashboard] access invoices after cancellation
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: webapp, release-note-none

#15581 [iam] Add Get OIDC Client Config RPC
  components/iam/pkg/apiv1/oidc_config.go
  components/iam/pkg/apiv1/oidc_config_test.go
Labels: size/M, team: webapp, release-note-none

#15585 missing yarn.lock changes
  yarn.lock
Labels: size/M, release-note-none

#15597 Only load zerossl-eab secret when needed
  dev/preview/infrastructure/harvester/certificate-zerossl.tf
Labels: size/XS, release-note-none, team: devx

#15595 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15599 Remove certificate check from Werft job
  .werft/jobs/build/prepare.ts
  .werft/util/certs.ts
Labels: size/M, release-note-none, team: devx

#15586 [server] Wait for image build logs in preparing state
  components/dashboard/debug.sh
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, team: workspace, release-note

#15589 fix: Loading Spinner Alignment
  components/dashboard/src/components/UsageView.tsx
Labels: size/S, team: webapp, release-note-none

#15609 fix headless and prebuild pods not removing never ready annotation
  components/ws-manager/pkg/manager/monitor.go
Labels: size/S, team: workspace, release-note-none

#15606 chore: descriptive output Gitpod CLI
  components/gitpod-cli/cmd/timeout-extend.go
  components/gitpod-cli/cmd/timeout-show.go
Labels: size/XS, team: IDE, release-note-none

#15591 Remove useless escape in email regex
  components/dashboard/src/settings/ProfileInformation.tsx
Labels: community-contribution, size/XS, release-note-none

#15590 Mark auth provider icons as decorative
  components/dashboard/src/provider-utils.tsx
Labels: community-contribution, size/XS, release-note-none

#15490 [inner loop poc] debug workspace window
  WORKSPACE.yaml
  components/gitpod-cli/pkg/supervisor/client.go
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/ide/code/leeway.Dockerfile
  components/proxy/conf/Caddyfile
  components/supervisor/cmd/run.go
  components/supervisor/frontend/src/debug.ts
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/regular.ts
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/hot-swap.sh
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
  components/ws-proxy/pkg/proxy/config.go
  components/ws-proxy/pkg/proxy/infoprovider.go
  components/ws-proxy/pkg/proxy/proxy.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
  components/ws-proxy/pkg/proxy/workspacerouter.go
  components/ws-proxy/pkg/proxy/workspacerouter_test.go
  components/ws-proxy/pkg/sshproxy/server.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/blobserve/configmap.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/constants.go
  install/installer/pkg/components/ws-proxy/configmap.go
Labels: size/XXL, team: webapp, team: workspace, team: IDE, release-note-none

#15619 Improve readability of label in billing settings
  components/dashboard/src/components/BillingAccountSelector.tsx
Labels: community-contribution, size/S, release-note-none

#15575 ws-manager: avoid duplicate logs
  components/ws-manager/pkg/manager/manager.go
  components/ws-manager/pkg/manager/metrics.go
Labels: size/M, team: workspace, release-note-none

#15451 [public-api] add workspaceStatus stream rpc
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/auth/middleware.go
  components/public-api-server/pkg/auth/middleware_test.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/v1connect/workspaces.connect.go
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/go/experimental/v1/workspaces_grpc.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/XL, team: webapp, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#15567 [dashboard] support start-with-options URL
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/start-workspace-options.ts
  components/dashboard/src/workspaces/StartWorkspaceModal.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/start-workspace-modal-context.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/XL, team: webapp, release-note

#15612 Update containerd and ipfs/kubo
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/ipfs/kubo/BUILD.yaml
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/S, team: workspace, team: IDE, release-note-none, team: delivery-operations-experience

#15628 [iam/sso] refactor client config middleware
  components/iam/pkg/oidc/oauth2.go
  components/iam/pkg/oidc/router.go
  components/iam/pkg/oidc/router_test.go
  components/iam/pkg/oidc/service.go
  components/iam/pkg/oidc/service_test.go
Labels: size/L, team: webapp, release-note-none

#15629 [iam/sso] select config by ID on /start
  components/iam/pkg/oidc/service.go
  components/iam/pkg/oidc/service_test.go
Labels: size/M, team: webapp, release-note-none

#15636 [common-go] Clear `GITPOD_HOST` environment variable before test
  components/common-go/experiments/types_test.go
Labels: size/XS, release-note-none, team: staff-engineers

#15635 [observability] Add image build rate panels
  operations/observability/mixins/workspace/dashboards/components/image-builder.json
Labels: size/L, team: workspace, release-note-none

#15644 [iam] try to fix flaky test
  components/iam/pkg/apiv1/oidc_config_test.go
Labels: size/XS, team: webapp, release-note-none

#15574 show user friendly error if git is not found
  components/supervisor/cmd/init.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE, release-note-none

#15647 ws-manager: add log to help troubleshoot
  components/ws-manager/pkg/manager/status.go
Labels: size/S, team: workspace, release-note-none

#15641 [server] Validate fields for setTeamMemberRole
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#15583 [licensor]: remove limits on licence user numbers and feature sets
  components/licensor/ee/pkg/licensor/licensor.go
  components/licensor/ee/pkg/licensor/licensor_test.go
  components/licensor/main.go
Labels: size/M, team: webapp, release-note

#15652 [dashboard - login] align login page product desc.
  components/dashboard/src/Login.tsx
Labels: size/XS, team: webapp, release-note-none

#15648 [JetBrains-Gateway] Menu Options for Usage, Feedback, Help in JB Gateway Plugin
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Labels: size/S, team: IDE, release-note

#15651 [server] Validate userID, teamID is a UUID on team operations
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note

#15653 Add proxy route for public-api
  components/dashboard/src/service/public-api.ts
  components/proxy/conf/Caddyfile
Labels: size/S, team: webapp, release-note-none

#15659 [code] update stable code
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#15661 [iam] (actually) don't fail if test config is missing
  components/iam/pkg/oidc/service.go
Labels: size/XS, team: webapp, release-note-none

#15631 [oidc] find/create User account
  components/server/src/iam/iam-oidc-create-session-payload.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/L, team: webapp, release-note-none

#15679 [.githhub] update ws-manager-api codeowner
  .github/CODEOWNERS
Labels: size/XS, release-note-none

#15675 VS Code `1.74.3`
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#15681 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15668 [dashboard] add "with-options" buttons
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/M, team: webapp, release-note

#15678 [openfga] Deploy when experimental.webapp.openfga.enabled is true
  .github/CODEOWNERS
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/openfga/constants.go
  install/installer/pkg/components/openfga/deployment.go
  install/installer/pkg/components/openfga/objects.go
  install/installer/pkg/components/openfga/service.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: webapp, release-note-none, team: devx, team: delivery-operations-experience

#15685 Use separate folders for caching Gradle dependencies from Stable and Latest JetBrains Gateway Plugin
  components/ide/jetbrains/gateway-plugin/BUILD.yaml
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15688 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15605 Preivew env GCE infra
  dev/preview/infrastructure/gce/certificate-letsencrypt.tf
  dev/preview/infrastructure/gce/certificate-zerossl.tf
  dev/preview/infrastructure/gce/cloudinit.yaml
  dev/preview/infrastructure/gce/dns.tf
  dev/preview/infrastructure/gce/namespace.tf
  dev/preview/infrastructure/gce/provider.tf
  dev/preview/infrastructure/gce/proxy.tf
  dev/preview/infrastructure/gce/startup-script.sh
  dev/preview/infrastructure/gce/variables.tf
  dev/preview/infrastructure/gce/vm.tf
Labels: size/XXL, release-note-none, team: devx

#15682 [installer] Reduce duplication when extracting experimental webapp config
  install/installer/pkg/common/common.go
  install/installer/pkg/components/openfga/objects.go
  install/installer/pkg/components/slowserver/objects.go
  install/installer/pkg/components/toxiproxy/objects.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/objects.go
Labels: size/M, team: webapp, release-note-none, team: delivery-operations-experience

#15694 [dashboard] list latest editor if available
  components/dashboard/src/components/SelectIDEComponent.tsx
Labels: size/XS, team: webapp, release-note-none

#15691 [db] Sync on connection initialization
  components/gitpod-db/src/typeorm/typeorm.ts
Labels: size/S, team: webapp, release-note

#15469 Improve terminal close
  components/supervisor/pkg/terminal/terminal.go
Labels: size/M, team: IDE, release-note-none

#15700 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15702 [public-api] Handle StreamWorkspaceStatus send error
  components/public-api-server/pkg/apiv1/workspace.go
Labels: size/XS, team: webapp, release-note-none

#15692 [openfga] Configure cloud-sql-proxy sidecar
  install/installer/pkg/components/openfga/constants.go
  install/installer/pkg/components/openfga/deployment.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: webapp, release-note-none, team: delivery-operations-experience

#15403 Use workspaceStatus stream rpc in supervisor
  components/supervisor/pkg/serverapi/publicapi.go
Labels: size/L, team: IDE, release-note-none, feature: public-api

#15706 [dashboard] Enable Public API Teams service by default
  components/dashboard/src/contexts/FeatureFlagContext.tsx
Labels: size/XS, team: webapp, release-note

#15703 [openfga] Configure CloudSQL datastore
  install/installer/pkg/components/openfga/deployment.go
Labels: size/L, team: webapp, release-note-none

#15646 [JetBrains-Gateway] fix-IDEA2022.3-gradle-runIde
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
Labels: size/XS, team: IDE, release-note, editor: jetbrains, cla: accepted :heavy_check_mark:

#15710 [openfga] Fix database name interpolation into datastore uri
  install/installer/pkg/components/openfga/deployment.go
Labels: size/XS, team: webapp, release-note-none

#15711 [api] usePublicApiProjectsService defaults to true
  components/dashboard/src/contexts/FeatureFlagContext.tsx
Labels: size/XS, team: webapp, release-note-none

#15719 Switch image builds y-axis on Gitpod/Overview dashboard
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/L, team: webapp, team: workspace, team: IDE, release-note-none, team: devx, team: delivery-operations-experience

#15697 increase buildkit log size to 4MB
  components/image-builder-bob/pkg/builder/builder.go
Labels: size/XS, team: workspace, release-note-none

#15722 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15699 Use project creation time to sort when no prebuild
  components/dashboard/src/data/projects/fetchers.ts
Labels: do-not-merge/hold, size/XS, team: webapp, release-note-none

#15533 Migrate account attribution to team attribution
  components/dashboard/src/Menu.tsx
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/settings/Billing.tsx
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/projects/projects-service.ts
  components/server/src/user/user-controller.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/envvar-prefix-context-parser.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/open-prebuild-prefix-context-parser.ts
Labels: size/XL, team: webapp, release-note-none

#15724 feat: `gp docs` in gitpod cli
  components/gitpod-cli/cmd/docs.go
Labels: size/S, team: IDE, release-note

#15723 Fix supervisor stuck on get config value
  components/supervisor/pkg/serverapi/publicapi.go
Labels: size/S, team: IDE, release-note-none

#15638 [Gitpod CLI] `gp rebuild`
  components/gitpod-cli/cmd/rebuild.go
  components/gitpod-cli/pkg/utils/parseGitpodConfig.go
  components/gitpod-cli/pkg/utils/trackEvent.go
Labels: component: gp cli, size/XL, team: IDE, release-note

#15745 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15493 License: Public API npm package
  components/public-api/typescript/package.json
Labels: meta: never-stale, size/XS, team: webapp, release-note-none

#15753 [public-api] Set proxy connection pool to size 500
  components/public-api-server/pkg/server/server.go
Labels: size/XS, team: webapp, release-note-none

#15656 [dashboard] support supervisor frontend server
  components/dashboard/src/service/service.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/frontend-dashboard-service.ts
  components/gitpod-protocol/src/util/gitpod-host-url.ts
Labels: size/XL, team: webapp, release-note-none

#15764 Add resource requirements for preview delete job
  .werft/platform-delete-preview-environment.yaml
Labels: size/XS, release-note-none, team: devx

#15733 [supervisor] improve instance updates
  components/supervisor/pkg/ports/exposed-ports.go
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: IDE, release-note-none

#15601 Delete semgrep.yml
  .github/workflows/semgrep.yml
Labels: size/S, release-note-none

#15728 [gitpod.yml] educate user about gitpod templates
  components/gitpod-cli/cmd/init.go
  components/server/src/config/configuration-service.ts
Labels: size/S, team: webapp, team: IDE, release-note

#15751 Optional GHA-Builds via argument '/werft with-github-actions'
  .github/pull_request_template.md
  .github/workflows/poc-build.yml
  .werft/build.ts
  .werft/jobs/build/job-config.ts
Labels: size/XL, release-note-none, team: devx

#15762 [webapp] Group CPU alerts by deployment
  operations/observability/mixins/meta/rules/content-service.yaml
  operations/observability/mixins/meta/rules/dashboard.yaml
  operations/observability/mixins/meta/rules/db-sync.yaml
  operations/observability/mixins/meta/rules/db.yaml
  operations/observability/mixins/meta/rules/messagebus.yaml
  operations/observability/mixins/meta/rules/payment-endpoint.yaml
  operations/observability/mixins/meta/rules/proxy.yaml
  operations/observability/mixins/meta/rules/server.yaml
  operations/observability/mixins/meta/rules/usage.yaml
  operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Labels: size/L, team: webapp, release-note-none

#15781 Add resource requirements for preview delete job
  .werft/platform-delete-preview-environment.yaml
Labels: size/S, release-note-none, team: devx

#15783 Add resource requirements for preview delete job
  .werft/platform-delete-preview-environment.yaml
Labels: size/XS, release-note-none, team: devx

#15784 [dashboard] remove deprecation warning on user /projects
  components/dashboard/src/projects/Projects.tsx
Labels: size/S, team: webapp, release-note-none

#15782 [papi] Refactor validation functions to a file
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/project.go
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api-server/pkg/apiv1/tokens.go
  components/public-api-server/pkg/apiv1/user.go
  components/public-api-server/pkg/apiv1/validation.go
  components/public-api-server/pkg/apiv1/workspace.go
Labels: size/L, team: webapp, release-note-none

#15785 [ws-manager-bridge] Stop logging status.auth field
  components/ws-manager-bridge/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#15794 [ws-manager-bridge] Stop logging workspacestatus.auth for prebuilds
  components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
  components/ws-manager-bridge/src/bridge.ts
Labels: size/XS, team: webapp, release-note-none

#15796 Rename GHA-Build from PoC-Build to Build
  .github/workflows/build.yml
Labels: size/XS, release-note-none, team: devx

#15792 Improve S3 speed
  components/content-service/pkg/storage/s3.go
Labels: size/M, team: workspace, release-note-none

#15587 [werft] add `with-dedicated-emulation` switch
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, release-note-none, team: devx

#15802 Support Leeway Vet
  .github/workflows/build.yml
Labels: size/XS, release-note-none, team: devx

#15801 Build all components
  .github/workflows/build.yml
  components/BUILD.yaml
Labels: size/S, release-note-none, team: devx

#15774 [Dashboard] Suggest using `gp rebuild` when image build fails
  components/dashboard/src/start/StartWorkspace.tsx
Labels: do-not-merge/hold, size/S, team: webapp, release-note-none

#15808 dashboard: update gp rebuild copy
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/XS, team: webapp, release-note-none

#15735 [Code][Inner Loop] Add Codelens for launching debug workspace window
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#15811 Partially revert "[supervisor-frontend] implement frontend dashboard client"
  components/supervisor/frontend/src/debug.ts
  components/supervisor/frontend/src/ide/gitpod-service-client.ts
  components/supervisor/frontend/src/ide/heart-beat.ts
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
  components/supervisor/frontend/src/regular.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/XXL, team: IDE, release-note-none

#15813 [supervisor] Remove trackEvent api method
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: IDE, release-note-none

#15810 Fix send initial status in IDEFrontendService
  components/dashboard/src/service/service.tsx
Labels: size/S, team: webapp, release-note-none

#15734 [server] Correctly record client IP for analytics purposes
  components/server/src/express-util.ts
Labels: size/XS, team: webapp, team: IDE, release-note-none

#15740 [Gitpod CLI] `gp rebuild` improvements
  components/gitpod-cli/cmd/rebuild.go
  components/gitpod-cli/pkg/utils/trackEvent.go
Labels: component: gp cli, size/L, team: IDE, release-note-none

#15730 previewctl also install gce contexts
  dev/preview/infrastructure/gce/proxy.tf
  dev/preview/infrastructure/gce/variables.tf
  dev/preview/infrastructure/gce/vm.tf
  dev/preview/previewctl/pkg/k8s/context/k3s/k3s.go
  dev/preview/previewctl/pkg/k8s/pforward.go
  dev/preview/previewctl/pkg/k8s/vm.go
  dev/preview/previewctl/pkg/k8s/vm_test.go
  dev/preview/previewctl/pkg/preview/context.go
Labels: size/XL, release-note-none, team: devx

#15814 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15789 [server] create a freemium team when no team exist
  components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
  components/gitpod-db/src/user-to-team-migration-service.ts
Labels: size/M, team: webapp, release-note-none

#15777 [oidc] Add Organisation ID to OIDC API
  components/public-api/gitpod/experimental/v1/oidc.proto
  components/public-api/go/experimental/v1/oidc.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
Labels: size/M, team: webapp, release-note-none

#15778 [db] Add organisationId to d_b_oidc_client_config + indices
  components/gitpod-db/go/dbtest/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/src/typeorm/migration/1673944879912-AddOrganizationIDToOIDCClientConfig.ts
Labels: size/M, team: webapp, release-note-none

#15779 [iam] Add organisation_id to OIDC Client Config API
  components/iam-api/go/v1/oidc_client_config.pb.go
  components/iam-api/go/v1/oidc_client_config_grpc.pb.go
  components/iam-api/iam/v1/oidc_client_config.proto
Labels: size/M, release-note-none

#15827 [previewctl] point to infra dir by default for stale
  dev/preview/previewctl/cmd/stale.go
  dev/preview/previewctl/cmd/workspaces.go
Labels: size/XS, release-note-none, team: devx

#15830 [obs] Fix webapp monitoring rule names
  operations/observability/mixins/meta/rules/dashboard.yaml
  operations/observability/mixins/meta/rules/db-sync.yaml
  operations/observability/mixins/meta/rules/db.yaml
  operations/observability/mixins/meta/rules/payment-endpoint.yaml
  operations/observability/mixins/meta/rules/proxy.yaml
  operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Labels: size/S, team: webapp, release-note-none

#15817 [installer] Replace OpenFGA with SpiceDB
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/openfga/constants.go
  install/installer/pkg/components/spicedb/constants.go
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/spicedb/objects.go
  install/installer/pkg/components/spicedb/service.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: webapp, release-note-none, team: delivery-operations-experience

#15484 chore(service-waiter): move from `streadway/amqp` to `rabbitmq/amqp091-go`
  License.third-party.go.txt
  components/service-waiter/cmd/messagebus.go
  components/service-waiter/go.mod
  components/service-waiter/go.sum
Labels: size/XS, release-note-none, cla: accepted :heavy_check_mark:

#15832 [obs] Adjust CPU alert thresholds for webapp services
  operations/observability/mixins/meta/rules/content-service.yaml
  operations/observability/mixins/meta/rules/dashboard.yaml
  operations/observability/mixins/meta/rules/db-sync.yaml
  operations/observability/mixins/meta/rules/db.yaml
  operations/observability/mixins/meta/rules/messagebus.yaml
  operations/observability/mixins/meta/rules/payment-endpoint.yaml
  operations/observability/mixins/meta/rules/proxy.yaml
  operations/observability/mixins/meta/rules/server.yaml
  operations/observability/mixins/meta/rules/usage.yaml
  operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Labels: size/S, team: webapp, release-note-none

#15825 Add Pre-Commit-Checks
  .github/workflows/build.yml
Labels: size/S, release-note-none, team: devx

#15718 [installer]: define the rules around the configuration
  install/installer/README.md
  install/installer/pkg/config/README.md
Labels: size/L, release-note-none, team: delivery-operations-experience

#15834 Remove openfga from preview config
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/XS, release-note-none, team: devx

#15831 Revert "Partially revert "[supervisor-frontend] implement frontend dashboard client"
  components/supervisor/frontend/src/debug.ts
  components/supervisor/frontend/src/ide/gitpod-service-client.ts
  components/supervisor/frontend/src/ide/heart-beat.ts
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
  components/supervisor/frontend/src/regular.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/XXL, team: IDE, release-note-none

#15838 Run node clean-up cron job more often
  .werft/platform-trigger-werft-cleanup.yaml
Labels: size/XS, release-note-none, team: devx

#15776 gitpod-cli: call segement directly for analytics
  components/gitpod-cli/cmd/rebuild.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/gitpod-cli/pkg/utils/trackEvent.go
  components/supervisor-api/go/control_grpc.pb.go
  components/supervisor-api/go/info.pb.go
  components/supervisor-api/go/info.pb.gw.go
  components/supervisor-api/go/info_grpc.pb.go
  components/supervisor-api/go/notification.pb.gw.go
  components/supervisor-api/go/notification_grpc.pb.go
  components/supervisor-api/go/port.pb.gw.go
  components/supervisor-api/go/port_grpc.pb.go
  components/supervisor-api/go/status.pb.gw.go
  components/supervisor-api/go/status_grpc.pb.go
  components/supervisor-api/go/terminal.pb.gw.go
  components/supervisor-api/go/terminal_grpc.pb.go
  components/supervisor-api/go/token.pb.gw.go
  components/supervisor-api/go/token_grpc.pb.go
  components/supervisor-api/info.proto
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/services.go
Labels: size/L, team: IDE, release-note-none

#15847 Update services node pool labels
  dev/preview/infrastructure/scripts/bootstrap-k3s.sh
  install/infra/modules/aks/kubernetes.tf
  install/infra/modules/eks/kubernetes.tf
  install/infra/modules/gke/cluster.tf
  install/infra/modules/k3s/main.tf
  install/installer/docs/overview.md
  install/installer/pkg/config/README.md
  install/preview/entrypoint.sh
Labels: size/S, release-note-none, team: devx, team: delivery-operations-experience

#15846 Delete `GetOwnerID` and use OwnerId from config
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: IDE, release-note-none

#15853 [db] Implement basic list oidc client configs
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/oidc_client_config_test.go
Labels: size/M, team: webapp, release-note-none

#15800 [PoC] Custom GitHub Action to create preview environments
  .github/actions/preview-create/Dockerfile
  .github/actions/preview-create/entrypoint.sh
  .github/actions/preview-create/metadata.yml
  .github/workflows/build.yml
Labels: size/M, release-note-none, team: devx

#15844 [server] Add OneTimeSecretServer.serveToken
  components/server/src/one-time-secret-server.ts
  components/server/src/user/user-controller.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp, release-note-none

#15849 [oidc] Propagate OrganizationID to IAM component
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
  components/public-api-server/pkg/apiv1/validation.go
Labels: size/M, team: webapp, release-note-none

#15850 [iam] Store OrganizationID with OIDC Client Configs
  components/iam/pkg/apiv1/oidc_config.go
  components/iam/pkg/apiv1/oidc_config_test.go
Labels: size/M, team: webapp, release-note-none

#15848 [public-api] Reduce duplication in validation functions
  components/public-api-server/pkg/apiv1/validation.go
Labels: size/M, team: webapp, release-note-none

#15658 [installer]: add override option to arbitrarily change the output
  install/installer/cmd/render.go
  install/installer/cmd/testdata/render/overrides-inline/config.yaml
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/postprocess/override.go
Labels: size/L, release-note, team: delivery-operations-experience

#15855 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#15858 [dashboard] never redirect to projects from /
  components/dashboard/src/hooks/use-user-and-teams-loader.ts
Labels: size/S, team: webapp, release-note-none

#15851 [installer] Mount database secret to Public API
  components/public-api/go/config/config.go
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/azure-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
Labels: size/S, team: webapp, release-note-none

#15864 Update `output.golden` file to fix the build pipeline
  install/installer/cmd/testdata/render/overrides-inline/output.golden
Labels: size/XS, release-note-none

#15840 [installer]: promote experimental telemetry config
  install/installer/cmd/testdata/render/telemetry/config.yaml
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/pkg/components/gitpod/cronjob.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/deprecations.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, release-note, team: delivery-operations-experience

#15819 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15820 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, release-note-none, editor: jetbrains

#15806 [revamp] : feedback widget UX
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
Labels: community-contribution, size/S, release-note-none
