Repository gitpod-io/gitpod, pull requests merged in 2023-07, with the labels that each got.

#18119 jb: don't log if alien_plugins.txt file already does not exist
  components/ide/jetbrains/launcher/main.go
Labels: size/XS, team: IDE

#18064 [test] Assert cgroup v2 is enabled
  test/tests/workspace/cgroup_v2_test.go
Labels: size/XS, team: workspace

#18088 [test] Ephemeral storage limit, fix preview workspace classes
  dev/preview/workflow/preview/deploy-gitpod.sh
  test/tests/workspace/ephemeral_storage_limit_test.go
Labels: size/L, team: workspace

#18134 Fix build error undefined: scrubber.TrustedValue
  components/blobserve/go.mod
  components/content-service/go.mod
  components/ee/agent-smith/go.mod
  components/ide-service/go.mod
  components/ide/code-desktop/status/go.mod
  components/ide/code/codehelper/go.mod
  components/ide/jetbrains/launcher/go.mod
  components/image-builder-bob/go.mod
  components/image-builder-mk3/go.mod
  components/installation-telemetry/go.mod
  components/node-labeler/go.mod
  components/openvsx-proxy/go.mod
  components/public-api-server/go.mod
  components/registry-facade/go.mod
  components/service-waiter/go.mod
  components/supervisor/go.mod
  components/usage/go.mod
  components/workspace-rollout-job/go.mod
  components/workspacekit/go.mod
  components/ws-daemon/go.mod
  components/ws-daemon/nsinsider/go.mod
  components/ws-manager-mk2/go.mod
  components/ws-proxy/go.mod
  dev/gp-gcloud/go.mod
  dev/gpctl/go.mod
  dev/loadgen/go.mod
  test/go.mod
Labels: size/L, team: webapp, team: workspace, team: IDE, team: security-infrastructure-and-delivery

#18133 Migrate ws-manager-mk2 to wolfi
  components/ws-manager-mk2/leeway.Dockerfile
Labels: size/XS, team: workspace

#18138 [test] Fix disk pressure, run in parallel
  .github/workflows/workspace-integration-tests.yml
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/gce/vm.tf
  test/README.md
  test/pkg/integration/setup.go
  test/pkg/integration/workspace.go
  test/run.sh
  test/tests/components/content-service/content-service_test.go
  test/tests/components/image-builder/builder_test.go
  test/tests/components/ws-daemon/storage_test.go
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/L, team: workspace, team: IDE

#18063 [test] Add network limiting e2e test
  test/go.mod
  test/go.sum
  test/pkg/agent/daemon/api/api.go
  test/pkg/agent/daemon/main.go
  test/pkg/integration/integration.go
  test/tests/components/ws-daemon/network_limiting_test.go
Labels: size/L, team: workspace, team: IDE

#18137 Upgrade helm rabbitmq to 11.16.1
  install/installer/third_party/charts/rabbitmq/Chart.yaml
Labels: size/XS, team: webapp

#18120 validate: run IDE prebuild only in headless workspace
  components/gitpod-cli/cmd/validate.go
  components/ide/code/codehelper/go.mod
  components/supervisor/pkg/supervisor/config.go
Labels: size/L, team: IDE

#18141 [preview] Update infra concurrency groups to match preview name
  .github/workflows/ide-integration-tests.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/workspace-integration-tests.yml
Labels: size/XS, team: workspace, team: IDE

#18099 [server] add organization service
  components/gitpod-protocol/src/experiments/configcat-server.ts
  components/server/package.json
  components/server/src/authorization/definitions.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/container-module.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/XL, team: webapp

#18131 Point code nightly to release branch
  .github/workflows/code-nightly.yml
Labels: editor: code (browser), team: IDE

#18111 [server] ProjectService - perm-check and testing
  components/gitpod-db/src/container-module.ts
  components/gitpod-protocol/src/analytics.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/authorization/spicedb.ts
  components/server/src/container-module.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/env-var-service.spec.ts
  components/server/src/workspace/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
  components/ws-manager-bridge/src/container-module.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/XXL, team: webapp

#18130 [JetBrains-plugin] Error message shouldn't be editable on Workspace Phase tray window
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/XS, team: IDE, feature: jetbrains-plugins

#18125 [server] Org service does member handling
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/transactional-db-impl.ts
  components/server/.vscode/launch.json
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp

#18136 [metrics] exclude VS Code Browser from error reporting
  components/ide-metrics/pkg/server/server.go
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/M, team: IDE

#18148 Remove workspace-rollout-job
  .github/CODEOWNERS
  components/BUILD.yaml
  components/workspace-rollout-job/BUILD.yaml
  components/workspace-rollout-job/README.md
  components/workspace-rollout-job/cmd/root.go
  components/workspace-rollout-job/go.mod
  components/workspace-rollout-job/go.sum
  components/workspace-rollout-job/hack/registry-facade.yaml
  components/workspace-rollout-job/hack/ws-rollout-job.yaml
  components/workspace-rollout-job/leeway.Dockerfile
  components/workspace-rollout-job/main.go
  components/workspace-rollout-job/pkg/analysis/analyzer.go
  components/workspace-rollout-job/pkg/analysis/worksapce_key_metrics.go
  components/workspace-rollout-job/pkg/rollout/metrics.go
  components/workspace-rollout-job/pkg/rollout/rollout.go
  components/workspace-rollout-job/pkg/rollout/rollout_test.go
  components/workspace-rollout-job/pkg/wsbridge/wsbridge.go
Labels: size/XXL, team: workspace

#18144 Updated outdated dependencies to avoid CVEs
  .werft/package.json
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/package.json
  components/ide-metrics-api/typescript-grpc/package.json
  components/image-builder-api/typescript/package.json
  components/supervisor-api/typescript-grpc/package.json
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  yarn.lock
Labels: size/M, team: webapp, team: workspace, team: IDE

#18153 [server, bridge] Small messagebus cleanup
  components/gitpod-protocol/src/headless-workspace-log.ts
  components/server/src/workspace/messagebus-integration.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/messagebus-integration.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
Labels: size/M, team: webapp

#18155 [ws-man-bridge] Setup redis WEB-595
  components/ws-manager-bridge/package.json
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/redis/client.ts
  install/installer/pkg/components/ws-manager-bridge/configmap.go
  install/installer/pkg/components/ws-manager-bridge/types.go
Labels: size/M, team: webapp

#18156 [ws-man-bridge] Setup noop publisher WEB-595
  components/ws-manager-bridge/src/bridge-controller.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/metrics.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
  components/ws-manager-bridge/src/redis/publisher.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/L, team: webapp

#18157 [server] more project service
  components/server/package.json
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/L, team: webapp

#18160 [server] reduce build time
  WORKSPACE.yaml
  components/gitpod-db/package.json
  components/gitpod-messagebus/package.json
  components/server/BUILD.yaml
  components/server/package.json
  components/ws-manager-bridge/package.json
Labels: size/M, team: webapp

#18163 [test] Fix network limit test, show test duration in slack msg
  .github/workflows/workspace-integration-tests.yml
  test/go.mod
  test/go.sum
  test/pkg/agent/daemon/api/api.go
  test/pkg/agent/daemon/main.go
  test/tests/components/ws-daemon/network_limiting_test.go
Labels: size/L, team: workspace

#18159 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#18162 [ws-man-bridge] Publish ws-instance-update - WEB-592
  components/gitpod-protocol/src/index.ts
  components/gitpod-protocol/src/redis.ts
  components/ws-manager-bridge/package.json
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/redis/publisher.spec.ts
  components/ws-manager-bridge/src/redis/publisher.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/L, team: webapp

#18166 Bump leeway to v0.7.5
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  .werft/aks-installer-tests.yaml
  .werft/build.yaml
  .werft/cleanup-installer-tests.yaml
  .werft/debug.yaml
  .werft/eks-installer-tests.yaml
  .werft/gke-installer-tests.yaml
  .werft/k3s-installer-tests.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  dev/image/Dockerfile
Labels: size/M, team: workspace, team: IDE, team: security-infrastructure-and-delivery

#17919 [server] Set maximum workspace lifetime
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp

#17999 [ws-manager-mk2] Prevent creation of multiple workspace instances with the same id
  components/ws-manager-mk2/service/manager.go
Labels: size/S, team: workspace

#18127 [test] IO Limits
  components/common-go/cgroups/cgroup.go
  components/common-go/cgroups/v2/io.go
  dev/preview/workflow/preview/deploy-gitpod.sh
  test/pkg/agent/daemon/api/api.go
  test/pkg/agent/daemon/main.go
  test/run.sh
  test/tests/components/ws-daemon/cpu_burst_test.go
  test/tests/components/ws-daemon/io_limiting_test.go
  test/tests/workspace/docker_test.go
  test/tests/workspace/process_limit_test.go
Labels: size/L, team: workspace, team: staff-engineers

#18167 [installer] Allow ws-man-bridge to connect to redis WEB-601
  install/installer/pkg/components/redis/networkpolicy.go
Labels: size/XS, team: webapp

#18169 Use leeway segment key secret
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-integration-test.yml
Labels: size/XS, team: IDE

#18172 Log network link state
  components/ws-daemon/nsinsider/main.go
  components/ws-daemon/pkg/iws/iws.go
Labels: size/M, team: workspace

#18140 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#18168 [test] Fix slack footer and improve ws-daemon log
  .github/workflows/workspace-integration-tests.yml
  components/ws-daemon/pkg/content/initializer.go
Labels: size/XS, team: workspace

#18175 [ws-manager-bridge] fix path to entry point
  components/ws-manager-bridge/leeway.Dockerfile
  components/ws-manager-bridge/package.json
Labels: size/XS, team: webapp

#17821 [public-api] Update getWorkspace api response implementation
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/L, team: webapp

#18180 Log ip address for default gateway
  components/ws-daemon/nsinsider/main.go
Labels: size/XS, team: workspace

#17927 removing usageDownload flag
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/usage/UsageView.tsx
Labels: size/XS, team: webapp

#18150 Prevent Input w/ Copy button from submitting forms
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/Tooltip.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/forms/SelectInputField.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/images/check-currentColor.svg
  components/dashboard/src/index.css
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/user-settings/Account.tsx
Labels: size/L, team: webapp

#18178 [github] Basic lacework integration
  .github/workflows/lacework-inline-scanner.yml
  scripts/lw-scan-images.sh
Labels: size/L

#18185 [workflow] Fix trigger for lacework-inline-scanner
  .github/workflows/lacework-inline-scanner.yml
Labels: size/XS

#18174 [server] more org service
  components/gitpod-protocol/src/util/timeutil.ts
  components/server/.eslintrc
  components/server/BUILD.yaml
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/XXL, team: webapp

#18188 Fix lacework integration workflow
  .github/workflows/lacework-inline-scanner.yml
Labels: size/S

#18189 Update VS Code Browser to 1.80.0
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#18191 Update gitpod-web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#18181 [obs] reduce noise related to GitpodWsManagerCrashLoopingMk2
  operations/observability/mixins/workspace/rules/central/ws-manager.yaml
Labels: size/M, team: workspace

#18192 code: Update Nightly
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE

#18145 Address registry-facade dependency issues
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/gitpod-db/go/go.mod
  components/gitpod-db/go/go.sum
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/registry-facade/pkg/registry/blob.go
  components/registry-facade/pkg/registry/blob_test.go
  components/registry-facade/pkg/registry/cache.go
  components/registry-facade/pkg/registry/registry.go
  components/usage/go.mod
  components/usage/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/XL, team: webapp, team: workspace, team: IDE, team: staff-engineers, team: security-infrastructure-and-delivery

#18186 [workspace] Test process priority
  test/tests/workspace/process_priority_test.go
Labels: size/L, team: workspace

#18183 [server] improved testing infrastructure
  components/gitpod-db/BUILD.yaml
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/package.json
  components/server/src/billing/billing-mode.spec.db.ts
  components/server/src/container-module.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/test/mocks/ide-service-mock.ts
  components/server/src/test/mocks/storage-client-mock.ts
  components/server/src/test/mocks/usage-service-client-mock.ts
  components/server/src/test/mocks/workspace-manager-client-mock.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/user/usage-service.ts
  components/server/src/user/user-service.spec.db.ts
Labels: size/XL, team: webapp

#18194 [server] move usage -> org, stripe -> billing
  components/server/src/billing/billing-mode.spec.db.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/stripe-service.ts
  components/server/src/container-module.ts
  components/server/src/orgs/usage-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#18197 [ws-man-bridge] Fix metric label reporting
  components/ws-manager-bridge/src/metrics.ts
Labels: size/XS, team: webapp

#18196 [service-waiter] Extend to support redis WEB-602
  components/service-waiter/cmd/redis.go
  components/service-waiter/go.mod
  components/service-waiter/go.sum
  install/installer/pkg/common/common.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/L, team: webapp

#18193 Update ws-daemon gcloud dependency
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS, team: workspace

#18203 Fix code-nightly.yml
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE

#18201 [alerts] Reduce the threshold for WebAppServicesCrashlooping
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/S, team: webapp

#18199 [server] Report client-side metrics for all spicedb operations
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/prometheus-metrics.ts
Labels: size/M, team: webapp

#18202 [server] Register redis update listeners
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#18047 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#18209 [server] Use a text feature flag to toggle which message updates come…
  components/server/src/messaging/local-message-broker.ts
  components/server/src/messaging/redis-subscriber.ts
Labels: size/M, team: webapp

#18213 Move Gitpod icon away from the navigation
  components/dashboard/src/menu/Menu.tsx
Labels: size/XS, team: webapp

#18208 [server] Gauge for registered listeners
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prometheus-metrics.ts
Labels: size/S, team: webapp

#18211 [ws-man-bridge] Publish ownerID for WorkspaceInstance updates WEB-597
  components/gitpod-protocol/src/redis.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/redis/publisher.spec.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/XS, team: webapp

#18212 [server] Broadcast workspace instance update to listeners WEB-597
  components/server/src/messaging/redis-subscriber.ts
Labels: size/M, team: webapp

#18210 [test] Fix RPC retries & improve logging
  test/pkg/integration/integration.go
  test/tests/components/ws-daemon/cpu_burst_test.go
Labels: size/M, team: workspace, team: IDE

#18217 Change gh event to pull_request_target and runner to GCE
  .github/workflows/authorization.yml
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/comment-ops.yaml
  .github/workflows/configcat.yml
  .github/workflows/create_runner.yml
  .github/workflows/dashboard-sync.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-delete.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/remove_runner.yml
  .github/workflows/workspace-integration-tests.yml
Labels: size/XXL

#18223 Fix lacework gh job
  .github/workflows/lacework-inline-scanner.yml
Labels: size/M

#18207 [alerts] Add JsonRpcApiErrorRates and WebAppServicesCrashlooping to Dedicated
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/XS

#18214 [server] Broadcast prebuild updates from redis WEB-599, WEB-593
  components/gitpod-protocol/src/redis.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
  components/ws-manager-bridge/src/redis/publisher.ts
Labels: size/L, team: webapp

#18227 [test] Fix CPU burst test panic
  test/tests/components/ws-daemon/cpu_burst_test.go
Labels: size/S, team: workspace

#18220 [ws-manager-mk2] Fix metric labels
  install/kots/manifests/kots-app.yaml
  operations/observability/mixins/README.md
  operations/observability/mixins/cross-teams/dashboards/SLOs/workspace-startup-time.libsonnet
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
  operations/observability/mixins/meta/dashboards/components/meta-overview.json
  operations/observability/mixins/self-hosted/dashboards/examples/overview.json
  operations/observability/mixins/workspace/dashboards/components/agent-smith.json
  operations/observability/mixins/workspace/dashboards/components/ws-manager.json
  operations/observability/mixins/workspace/dashboards/node-psi.json
  operations/observability/mixins/workspace/dashboards/success-criteria.json
  operations/observability/mixins/workspace/rules/central/workspacefailure-SLO.yaml
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
  operations/observability/mixins/workspace/rules/satellite/ws-daemon.yaml
Labels: size/XXL, team: webapp, team: workspace, team: security-infrastructure-and-delivery

#18226 Fix preview environment delete job
  .github/workflows/preview-env-delete.yml
Labels: size/M

#18232 Fix summary length error
  .github/workflows/build.yml
Labels: size/S

#18143 [supervisor] improve docker activation
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/activation/activation.go
  components/supervisor/pkg/supervisor/docker.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XL, team: IDE

#18230 Fix: remove ws-manager.json dashboard
  operations/observability/mixins/workspace/dashboards.libsonnet
Labels: size/XS

#18233 Fix disposal of VMs
  .github/workflows/remove_runner.yml
Labels: size/XS

#18231 [server] Add Redis subscription/broadcasting to dashboard
  operations/observability/mixins/meta/dashboards/components/server.json
Labels: size/XXL, team: webapp

#18236 Revert "[supervisor] improve docker activation (#18143)"
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/supervisor/pkg/activation/activation.go
  components/supervisor/pkg/supervisor/docker.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XL, team: IDE

#18237 Fix build previewctl step
  .github/workflows/build.yml
Labels: size/M

#18242 Use env variable directly
  .github/workflows/build.yml
Labels: size/S

#18244 [gha] Docker login for previewctl
  .github/workflows/build.yml
Labels: size/XS

#18239 [ci] Remove license header check, already done in pre-commit
  .github/workflows/build.yml
Labels: size/S

#18219 Update native dependencies base
  components/ide/code/leeway.Dockerfile
Labels: editor: code (browser), size/XS, team: IDE

#18245 Add missing Job needs
  .github/workflows/preview-env-delete.yml
Labels: size/XS

#18222 [obs] further restrict NodePoolLoad to avoid false positives
  operations/observability/mixins/workspace/rules/central/nodes.yaml
Labels: size/XS, team: workspace

#18247 Enable leeway metrics
  .github/workflows/build.yml
Labels: size/S

#18246 Fix invalid LEEWAY_WORKSPACE_ROOT
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE

#18250 [obs] add node variable and update panels in Node PSI dashboard to use it
  operations/observability/mixins/workspace/dashboards/node-psi.json
Labels: size/M, team: workspace

#18224 Remove settings menu in the admin dashboard
  components/dashboard/src/admin/admin.routes.ts
Labels: size/S, team: webapp

#18221 allow disconnect for org owned users
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/S, team: webapp

#18252 [public-api] Remove db debug from OIDC tests
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/XS, team: webapp

#18258 Revert https://github.com/gitpod-io/gitpod/pull/18158
  .github/workflows/build.yml
Labels: size/XS

#18257 [supervisor] correct CreateSSHKeyPair error code
  components/supervisor/pkg/supervisor/services.go
Labels: size/M, team: IDE

#18262 Remove custom coverage-output-path
  .github/workflows/build.yml
Labels: size/S

#18261 Switch installer container image to chainguard
  install/installer/leeway.Dockerfile
Labels: size/XS

#18249 ignore 640 error codes
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/XS, team: webapp

#18241 [build-pipeline] tag the commit & create release
  .github/workflows/build.yml
Labels: size/S

#18267 Remove page title suffix
  components/dashboard/public/index.html
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/XS, team: webapp

#18263 [ws-man-bridge] Refactor constructors and cleanup deps
  components/ws-manager-bridge/src/app-cluster-instance-controller.ts
  components/ws-manager-bridge/src/bridge-controller.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
Labels: size/L, team: webapp

#18112 [dashboard] show warning when select code desktop
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: webapp

#18142 Remove feedback issue template
  .github/ISSUE_TEMPLATE/feedback_issue.yml
Labels: size/S

#18271 Allow `vscode-browser-extension` to report errors
  install/installer/pkg/components/ide-metrics/configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#18260 [server] extract tested usage-service
  .github/workflows/remove_runner.yml
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/billing/billing-mode.spec.db.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/container-module.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/orgs/usage-service.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/test/mocks/mock.spec.ts
  components/server/src/test/mocks/mock.ts
  components/server/src/test/mocks/usage-service-client-mock.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/BUILD.yaml
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: webapp

#18154 [Analytics] Remove date from input for cookieless hash
  components/server/src/analytics.ts
Labels: size/XS, team: webapp

#18278 [server] remove definitely-gp
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/image-source-provider.ts
Labels: size/L, team: webapp

#18279 Update VS Code Browser to `1.80.1`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE

#18281 Change gh runners concurrency rules
  .github/pull_request_template.md
  .github/workflows/build.yml
Labels: size/M

#18286 [supervisor] log ssh tunnel read error
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE

#18296 Add Gitpod Desktop OAuth client
  components/server/src/oauth-server/db.ts
Labels: size/S, team: webapp

#18280 [server] use org service in iam-session-app
  components/server/src/authorization/authorizer.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/test/reset-db.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
  dev/preview/previewctl/cmd/admin.go
Labels: size/L

#18301 [server] warn when resolve image is unsuccessful
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: webapp

#18294 Include Copilot in PR template
  .github/pull_request_template.md
Labels: size/S

#18110 Fix LinkedIn connection bugs and surface errors
  components/dashboard/src/App.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/onboarding/LinkedInBanner.tsx
Labels: size/S, team: webapp

#18283 Update top navigation
  components/dashboard/src/components/PillMenuItem.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/S, team: webapp

#18313 [test] Cleanup skipped duplicate tests
  test/tests/components/ws-daemon/process_priority_test.go
  test/tests/components/ws-daemon/workspace_resource_info_test.go
Labels: size/M, team: workspace

#18314 [dashboard] add website slugs
  components/dashboard/src/utils.ts
Labels: size/XS, team: webapp

#18308 [spicedb] generate ts definitions
  components/server/package.json
  components/server/src/authorization/definitions.ts
  components/spicedb/BUILD.yaml
  components/spicedb/codegen/codegen.go
  components/spicedb/codegen/go.mod
  components/spicedb/codegen/go.sum
  gitpod-ws.code-workspace
  yarn.lock
Labels: size/XL, team: webapp

#18304 Fix: Authorize with undefined – WEB-613
  components/gitpod-protocol/src/messaging/error.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/XS, team: webapp

#18316 [server] remove definitely-gp
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/image-source-provider.ts
Labels: size/L, team: webapp

#18318 Update codeowners
  .github/CODEOWNERS
Labels: size/L

#18251 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#18292 [public-api] align context url with server
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
Labels: size/S, team: webapp

#18317 [server] fix team_created event
  components/server/src/orgs/organization-service.ts
Labels: size/M, team: webapp, team: team-experience

#18322 allow access to supervisor logs within a workspace
  components/supervisor/cmd/init.go
  components/supervisor/cmd/root.go
  components/supervisor/cmd/run.go
  components/supervisor/go.mod
  components/supervisor/go.sum
Labels: size/M, team: team-experience

#18324 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18238 [server, ws-man-bridge] Remove messagebus WEB-618
  components/server/src/container-module.ts
  components/server/src/messaging/local-message-broker.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prebuilds/prebuilt-status-maintainer.ts
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/messagebus-integration.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/main.ts
  components/ws-manager-bridge/src/messagebus-integration.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/XXL, team: webapp, team: team-experience

#18332 [obs] Fix gitpod_workspace_regular_not_active_percentage_mk2, and temporarily disable related alerts
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine

#18216 [installer] Remove messagebus WEB-618
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/common/common.go
  install/installer/pkg/components/components-webapp/components.go
  install/installer/pkg/components/rabbitmq/certs/msgbus-ca.key
  install/installer/pkg/components/rabbitmq/certs/msgbus-ca.pem
  install/installer/pkg/components/rabbitmq/certs/msgbus-client.crt
  install/installer/pkg/components/rabbitmq/certs/msgbus-client.pem
  install/installer/pkg/components/rabbitmq/configuration.go
  install/installer/pkg/components/rabbitmq/constants.go
  install/installer/pkg/components/rabbitmq/helm.go
  install/installer/pkg/components/rabbitmq/objects.go
  install/installer/pkg/components/rabbitmq/rolebinding.go
  install/installer/pkg/components/rabbitmq/secret.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/v1/validation.go
  install/installer/third_party/charts/rabbitmq.go
  install/installer/third_party/charts/rabbitmq/Chart.yaml
  install/installer/third_party/charts/rabbitmq/values.yaml
  install/preview/manifests/messagebus.yaml
Labels: size/XXL, team: webapp, team: security-infrastructure-and-delivery, team: team-experience, team: team-engine

#18269 Remove gitpod-messagebus component WEB-618
  .github/CODEOWNERS
  components/gitpod-messagebus/BUILD.yaml
  components/gitpod-messagebus/HowToKeys.md
  components/gitpod-messagebus/package.json
  components/gitpod-messagebus/src/config.ts
  components/gitpod-messagebus/src/index.ts
  components/gitpod-messagebus/src/jsonrpc-client.ts
  components/gitpod-messagebus/src/jsonrpc-server.ts
  components/gitpod-messagebus/src/messagebus.ts
  components/gitpod-messagebus/src/rpc-client.ts
  components/gitpod-messagebus/src/rpc-server.ts
  components/gitpod-messagebus/tsconfig.json
  components/public-api-server/pkg/proxy/errors.go
  components/server/BUILD.yaml
  components/server/package.json
  components/ws-manager-bridge/BUILD.yaml
  components/ws-manager-bridge/package.json
  yarn.lock
Labels: size/XXL, team: webapp, team: team-experience, team: leadership

#18339 [service-waiter] Remove messagebus
  components/service-waiter/cmd/messagebus.go
  components/service-waiter/go.mod
  components/service-waiter/go.sum
Labels: size/L, team: team-experience

#18333 [server] don't start DB if already running, fix post test db cleanup
  .github/workflows/build.yml
  components/gitpod-db/.vscode/launch.json
  components/gitpod-db/package.json
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-db/src/blocked-repository-db.spec.db.ts
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/email-domain-filter-db.spec.db.ts
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/team-db.spec.db.ts
  components/gitpod-db/src/test/reset-db.ts
  components/gitpod-db/src/typeorm/auth-code-repository-db.spec.db.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
  components/gitpod-db/src/typeorm/entity/db-app-installation.ts
  components/gitpod-db/src/typeorm/entity/db-auth-provider-entry.ts
  components/gitpod-db/src/typeorm/entity/db-one-time-secret.ts
  components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts
  components/gitpod-db/src/typeorm/entity/db-project-env-vars.ts
  components/gitpod-db/src/typeorm/entity/db-snapshot.ts
  components/gitpod-db/src/typeorm/entity/db-token-entry.ts
  components/gitpod-db/src/typeorm/entity/db-user-env-vars.ts
  components/gitpod-db/src/typeorm/entity/db-user-ssh-public-key.ts
  components/gitpod-db/src/typeorm/entity/db-webhook-event.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/one-time-secret-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-db/src/user-storage-resources-spec.db.ts
  components/gitpod-db/src/webhook-event-db.spec.db.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/tsconfig.json
  components/gitpod-protocol/src/encryption/container-module.ts
  components/gitpod-protocol/src/encryption/encryption-service.ts
  components/server/package.json
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/test/reset-db.ts
  components/server/src/user/user-service.spec.db.ts
  yarn.lock
Labels: size/XL, team: team-experience

#18340 [messagebus] Remove remaining refs
  .werft/jobs/build/installer/post-process.sh
  components/server/src/prometheus-metrics.ts
  components/service-waiter/cmd/redis.go
  dev/gpctl/cmd/workspaces-watch.go
  install/installer/pkg/common/constants.go
  install/preview/entrypoint.sh
  test/pkg/integration/setup.go
Labels: size/L, team: team-experience, team: team-engine

#18335 Revert "[server] remove definitely-gp"
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/image-source-provider.ts
Labels: size/L, team: team-experience

#18264 [gitpod-db] Include redis client to share WEB-621
  components/gitpod-db/package.json
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/redis/client.ts
  components/server/src/container-module.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/redis/client.ts
  components/ws-manager-bridge/src/redis/publisher.spec.ts
  components/ws-manager-bridge/src/redis/publisher.ts
Labels: size/M, team: webapp, team: team-experience

#18274 [JetBrains] Update IDE images to new build version
  .github/actions/setup-environment/action.yml
  .github/workflows/build.yml
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-engine

#18343 Disable create release
  .github/workflows/build.yml
Labels: size/S, team: team-engine

#18275 [db] Move redis publisher to gitpod-db WEB-621
  components/gitpod-db/package.json
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/redis/metrics.ts
  components/gitpod-db/src/redis/publisher.spec.ts
  components/gitpod-db/src/redis/publisher.ts
  components/server/src/container-module.ts
  components/server/src/monitoring-endpoints.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/main.ts
  components/ws-manager-bridge/src/metrics.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
  components/ws-manager-bridge/src/redis/publisher.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/L, team: webapp

#18344 Make public URL prefix configurable
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: team-experience

#18320 Hide Invite Members button from non-owners – WEB-611
  components/dashboard/src/teams/Members.tsx
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, team: team-experience

#18273 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#18272 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#18330 Add `Repository` to WS info in Public API
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/S, team: team-experience

#18312 [server/auth] Added user as a resource
  components/gitpod-db/src/index.ts
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/projects/projects-service.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
  components/spicedb/schema/schema.yaml
Labels: size/XL, team: webapp, team: team-experience

#18350 [pull request template] make copilot:summary work
  .github/pull_request_template.md
Labels: size/XS

#18354 [lw-scans] Use oci-tool to download installer
  scripts/lw-scan-images.sh
Labels: size/S

#18346 Downgrade grpc-js – EXP-41
  .werft/package.json
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/package.json
  components/ide-metrics-api/typescript-grpc/package.json
  components/image-builder-api/typescript/package.json
  components/supervisor-api/typescript-grpc/package.json
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  yarn.lock
Labels: size/M, team: team-experience, team: team-engine

#18349 [user-service] extract user-authentication
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/user.spec.ts
  components/server/src/api/user.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/container-module.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/test/expect-utils.ts
  components/server/src/user/user-authentication.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#18348 [installation-telemetry] Remove component ENG-291
  .github/CODEOWNERS
  components/BUILD.yaml
  components/installation-telemetry/BUILD.yaml
  components/installation-telemetry/cmd/root.go
  components/installation-telemetry/cmd/send.go
  components/installation-telemetry/go.mod
  components/installation-telemetry/go.sum
  components/installation-telemetry/leeway.Dockerfile
  components/installation-telemetry/main.go
  components/installation-telemetry/pkg/common/config.go
  components/installation-telemetry/pkg/server/installationAdmin.go
  install/installer/pkg/components/gitpod/constants.go
  install/installer/pkg/components/gitpod/cronjob.go
  install/installer/pkg/components/gitpod/objects.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/deprecations.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/versions/versions.go
Labels: size/XL, team: team-experience, team: team-engine, team: leadership

#18355 Install oci-tool in dev-environment image
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  .werft/build.yaml
  .werft/cleanup-installer-tests.yaml
  .werft/debug.yaml
  .werft/platform-trigger-werft-cleanup.yaml
  dev/image/Dockerfile
Labels: size/M, team: team-experience, team: team-engine
