Repository gitpod-io/gitpod, pull requests merged in 2023-09, with the labels that each got.

#18493 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#18632 Improve workspace preview resource utilization
  dev/preview/workflow/preview/deploy-gitpod.sh
  dev/preview/workflow/preview/post-process.sh
  dev/preview/workflow/vm/charts/fluentbit/values.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/cluster-test.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/common.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/crds.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/operator.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/snapshotclass.yaml
  dev/preview/workflow/vm/manifests/rook-ceph/storageclass-test.yaml
Labels: size/XXL

#18640 [redis] fix readiness probe
  install/installer/pkg/components/redis/deployment.go
Labels: size/XS

#18639 [gha] update JetBrains PRs' reviewer
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates.yml
Labels: size/XS, team: team-experience

#18635 Upgrade buildkit to v0.12.2
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XS, team: team-engine

#18631 [spicedb] fix stale connection handling
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/package.json
  components/ide-metrics-api/typescript-grpc/package.json
  components/image-builder-api/typescript/package.json
  components/server/debug.sh
  components/server/package.json
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/authorization/spicedb.ts
  components/server/src/container-module.ts
  components/server/src/test/service-testing-container-module.ts
  components/supervisor-api/typescript-grpc/package.json
  components/usage-api/typescript/package.json
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  install/installer/pkg/components/spicedb/deployment.go
  yarn.lock
Labels: size/L, team: team-experience, team: team-engine

#18643 Fix e2e test concurrency group on PR builds
  .github/workflows/build.yml
Labels: size/XS, team: team-engine

#18603 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#18641 [ws-manager-api] Remove deprecated ide-related fields
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  dev/loadgen/cmd/benchmark.go
  dev/loadgen/cmd/run.go
  test/pkg/integration/workspace.go
Labels: size/S, team: team-experience, team: team-engine

#18647 Fix nsinsider log
  components/ws-daemon/pkg/nsinsider/nsinsider.go
Labels: size/S, team: team-engine

#18636 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/server/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-bridge/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18651 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18642 [server] Separate instance creation from instance starting (again)
  components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience

#18644 undo limit to fetch the first 100 user repos for New Workspace – EXP-554
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/hooks/use-user-loader.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/L, team: team-experience

#18630 Allow renaming project
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/service/public-api.ts
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/project.go
  components/public-api-server/pkg/apiv1/project_test.go
  components/public-api-server/pkg/apiv1/team.go
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/server/src/projects/projects-service.ts
Labels: size/L, team: team-experience

#18654 [dashboard] remove vscode SSH warning
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: team-experience

#18610 [bbs] update REPO_WRITE permission check EXP-521
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-token-validator.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-token-validator.ts
Labels: size/L, team: team-experience

#18655 [dashboard] initialize project name
  components/dashboard/src/projects/ProjectSettings.tsx
Labels: size/S, team: team-experience

#18625 Avoid ws-manager-mk2 metrics duplication
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
Labels: size/L, team: team-engine

#18600 Browser Terminal GA
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/XS, team: team-experience

#18653 [server] Make PrebuildManager use WorkspaceService.startWorkspace (to remove code duplication)
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience

#18657 code: Update Nightly
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience

#18648 Update jb-launcher environment resolver
  components/ide/jetbrains/launcher/main.go
Labels: size/M, team: team-experience

#18661 [code] Update gitpod-web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#18664 Reduce log verbosity
  components/ws-proxy/pkg/proxy/auth.go
  components/ws-proxy/pkg/proxy/routes.go
Labels: size/XS, team: team-engine

#18663 [alerts] group by cluster for the NodePoolLoad alert
  operations/observability/mixins/workspace/rules/central/nodes.yaml
Labels: size/XS, team: team-engine

#18665 Do not log if the connection was closed abnormally
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: team-experience

#18668 [New Project] Show account name in repo list – EXP-553
  components/dashboard/src/projects/new-project/NewProjectRepoList.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoSelection.tsx
Labels: size/M, team: team-experience

#18670 [intellij] add previous version
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/M, team: team-experience

#18373 [db] Run tests against mysql 8.0.33
  .github/workflows/build.yml
  components/gitpod-db/BUILD.yaml
  install/installer/pkg/components/database/incluster/helm.go
  install/installer/pkg/helm/common.go
  install/installer/pkg/helm/helm.go
Labels: size/M, team: team-experience

#18660 Filter subscriber reconciler events
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/subscriber_controller.go
Labels: size/M, team: team-engine

#18672 [proto] Add usage-api to leeway run components:generate-code-from-protobuf
  components/BUILD.yaml
  components/usage-api/typescript/src/google/protobuf/timestamp.pb.ts
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
Labels: size/XS, team: team-experience

#18596 Update probot lib
  components/server/package.json
  yarn.lock
Labels: size/XXL, team: team-experience

#18634 Upgrade jsonwebtoken lib
  components/gitpod-protocol/src/gitpod-file-parser.ts
  components/gitpod-protocol/src/messaging/node/connection.ts
  components/gitpod-protocol/src/util/debug-app.ts
  components/gitpod-protocol/tsconfig.json
  components/server/package.json
  components/server/src/api/server.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/bearer-authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/jwt.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket/bitbucket-auth-provider.ts
  components/server/src/code-sync/code-sync-service.ts
  components/server/src/dev/authenticator-dev.ts
  components/server/src/dev/passport-dummy.d.ts
  components/server/src/express-util.ts
  components/server/src/express/ws-connection-handler.ts
  components/server/src/express/ws-handler.ts
  components/server/src/express/ws-layer.spec.ts
  components/server/src/express/ws-layer.ts
  components/server/src/github/github-auth-provider.ts
  components/server/src/gitlab/gitlab-auth-provider.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/init.ts
  components/server/src/liveness/liveness-controller.ts
  components/server/src/monitoring-endpoints.ts
  components/server/src/oauth-server/oauth-controller.ts
  components/server/src/one-time-secret-server.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app-rules.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/server.ts
  components/server/src/session-handler.ts
  components/server/src/test/authentication-github.spec.ts
  components/server/src/user/newsletter-subscription-controller.ts
  components/server/src/user/user-controller.ts
  components/server/src/util/grpc-web-ws-transport.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-download-service.ts
  components/server/tsconfig.json
  package.json
  yarn.lock
Labels: size/L, team: team-experience

#18671 [fga] add relationship update job
  components/server/src/authorization/relationship-updater-job.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/container-module.ts
  components/server/src/jobs/runner.ts
  components/usage-api/typescript/tsconfig.json
Labels: size/L, team: team-experience

#18675 [fga] run job more often with smaller chunks
  components/server/src/authorization/relationship-updater-job.ts
Labels: size/S, team: team-experience

#18676 [fga] enable all writes by feature flag
  components/server/src/auth/resource-access.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/M, team: team-experience

#18677 Fix undefined user causes <Login> to be renderd
  components/dashboard/src/hooks/use-user-loader.ts
Labels: size/S, team: team-experience

#18679 enable hmr for dashboard
  components/dashboard/craco.config.js
  components/dashboard/package.json
Labels: size/S, team: team-experience

#18684 Fix preview name in GHA summary report
  .github/actions/deploy-gitpod/entrypoint.sh
Labels: size/XS, team: team-engine

#18683 [fga] retry write relationships
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/orgs/usage-service.ts
Labels: size/M, team: team-experience

#18685 [fga] fix workspace sharing
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: team-experience

#18656 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18688 [log] log requestId
  components/gitpod-protocol/src/util/logging.ts
  components/server/src/util/log-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/M, team: team-experience

#18692 [fga] fix and log missing relationships
  components/server/src/authorization/relationship-updater.ts
Labels: size/S, team: team-experience

#18694 Revert "Filter subscriber reconciler events"
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/subscriber_controller.go
Labels: size/M, team: team-engine

#18695 [gha] update JetBrains platform template reviewers
  .github/workflows/jetbrains-update-plugin-platform-template.yml
Labels: size/XS, team: team-experience

#18687 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18697 [server] improved logging
  components/server/src/jobs/runner.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/server.ts
  components/server/src/util/log-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience

#18701 [fga] additional check
  components/server/src/authorization/relationship-updater.ts
Labels: size/XS, team: team-experience

#18703 Add maintenance metric
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/main.go
Labels: size/M, team: team-engine

#18700 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18681 Adding getSuggestedRepositories method
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/git-providers/suggested-repositories-query.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#18704 [fga] try any spicedb operation 3 times
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience

#18696 Filter subscriber reconciler events (v2)
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/subscriber_controller.go
Labels: size/M, team: team-engine

#18708 remove perm check on internal findTokensForIdentity
  components/server/src/user/user-service.ts
Labels: size/XS, team: team-experience

#18702 Include regular not active alerts in Dedicated
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine

#18709 Solidify runc create retries
  components/docker-up/runc-facade/main.go
Labels: size/S, team: team-engine

#18707 Update VS Code Browser to `1.82.1`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18713 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18673 Reconcile startWorkspace
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/util/timeutil.ts
  components/server/src/container-module.ts
  components/server/src/jobs/runner.ts
  components/server/src/redis/mutex.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-start-controller.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/XL, team: team-experience

#18712 Kill env cmd as a last resource
  components/ide/jetbrains/launcher/main.go
Labels: size/XS, team: team-experience

#18714 [jb] Update JetBrains stable image PR template
  .github/workflows/jetbrains-updates.yml
Labels: size/XS, team: team-experience

#18719 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18698 Add "Enable Prebuilds" to Project Settings – EXP-573
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/forms/InputField.tsx
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/dashboard/src/data/projects/list-projects-query.ts
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/project-context.tsx
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
  components/gitpod-protocol/go/error.go
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/context-url.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/project.go
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/server/src/container-module.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/prebuilds/start-prebuild-context-parser.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/projects/scm-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#18721 Fix rendering of ProjectListItem
  components/dashboard/src/projects/ProjectListItem.tsx
Labels: size/XS, team: team-experience

#18720 [server] Tone down log messages on startWorkspace
  components/server/src/jobs/runner.ts
  components/server/src/redis/mutex.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience

#18722 Fix PAPI conversion
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
Labels: size/XS, team: team-experience

#18691 node grpc spike dashboard to server
  components/dashboard/package.json
  components/dashboard/src/index.tsx
  components/dashboard/src/service/metrics.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/proxy/conf/Caddyfile
  components/public-api/gitpod/experimental/v1/dummy.proto
  components/public-api/go/experimental/v1/dummy.pb.go
  components/public-api/go/experimental/v1/dummy_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/dummy.connect.go
  components/public-api/go/experimental/v1/v1connect/dummy.proxy.connect.go
  components/public-api/typescript/package.json
  components/public-api/typescript/src/gitpod/experimental/v1/dummy_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/dummy_pb.ts
  components/public-api/typescript/src/metrics.ts
  components/public-api/typescript/tsconfig.json
  components/server/package.json
  components/server/src/api/dummy.ts
  components/server/src/api/handler-context-augmentation.d.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/container-module.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/server.ts
  components/server/src/session-handler.ts
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/ide-metrics/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/networkpolicy.go
  install/installer/pkg/components/server/objects.go
  yarn.lock
Labels: size/XXL, team: team-experience

#18715 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#18724 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18729 Update VS Code Browser to 1.82.2
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18693 Change issuer identifier address for OIDC
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
Labels: size/XS, team: team-experience

#18726 [dashboard] unify error reporting
  components/dashboard/src/components/error-boundaries/ReloadPageErrorBoundary.tsx
  components/dashboard/src/service/metrics.ts
  components/dashboard/src/user-context.tsx
  components/public-api/typescript/src/metrics.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#18733 [spicedb] Grant all org members project "editor" role
  components/server/src/authorization/definitions.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/spicedb/schema/schema.yaml
Labels: size/M, team: team-experience

#18732 support jb plugins from image
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/rebuild.sh
Labels: size/L, team: team-experience

#18736 🧹 Update mocha and remove resolutions
  components/gitpod-db/mocha.opts
  components/gitpod-db/package.json
  components/gitpod-protocol/mocha.opts
  components/gitpod-protocol/package.json
  components/public-api/typescript/mocha.opts
  components/public-api/typescript/package.json
  components/server/mocha.opts
  components/server/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge/mocha.opts
  components/ws-manager-bridge/package.json
  package.json
  yarn.lock
Labels: size/XL, team: team-experience, team: team-engine

#18740 [db] inCluster: remove mysql version flag
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/database/incluster/helm.go
  install/installer/pkg/config/v1/config.go
Labels: size/S

#18741 [ubp] Improve logging when checking hasPaidSubscription
  components/server/src/billing/entitlement-service-ubp.ts
Labels: size/S, team: team-experience

#18723 Add default workspace image to org setting
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-cli/cmd/init.go
  components/gitpod-cli/cmd/validate.go
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1694775547603-AddOrgDefaultImageSetting.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/config-provider.spec.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/context-parser-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor-api/go/info.pb.go
  components/supervisor-api/info.proto
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Info.java
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/services.go
Labels: size/XXL, team: team-experience

#18706 Add projects to repository finder
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/typography/MiddleDot.tsx
  components/dashboard/src/icons/RepositoryWithColor.svg
  components/dashboard/src/start/Open.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.spec.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/server/src/repohost/repository-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/suggested-repos-sorter.spec.ts
  components/server/src/workspace/suggested-repos-sorter.ts
Labels: size/XXL, team: team-experience

#18730 [code] Pass GITPOD_CODE_HOST when starting vscode server
  WORKSPACE.yaml
  components/ide/code/codehelper/main.go
  components/ide/code/leeway.Dockerfile
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/M, team: team-experience

#18739 [public-api] improve error handling
  components/dashboard/resolver.js
  components/dashboard/src/service/service.tsx
  components/public-api/typescript/package.json
  components/public-api/typescript/tsconfig.json
  components/server/src/api/server.ts
Labels: size/L, team: team-experience

#18746 [server,dashboard] improve org default image input placeholder
  components/dashboard/src/data/workspaces/default-workspace-image-query.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience

#18756 [fga] add more logging to track down sharing issue
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/S, team: team-experience

#18745 [WorkspaceStarter] Fail instance on all errors
  components/gitpod-protocol/src/util/grpc.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience

#18747 [server,dashboard] verify image accessibility when updating org workspace image setting
  components/dashboard/src/icons/Stack.svg
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/image-builder-api/typescript/src/sugar.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-api/typescript/src/constraints.ts
Labels: size/XL, team: team-experience, team: team-engine

#18766 [fga] trying to understand the sharing issue
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience

#18748 Update docker compose 2.21.0
  WORKSPACE.yaml
Labels: size/XS

#18761 [dashboard] Downtime in-app announcements
  components/dashboard/craco.config.js
  components/dashboard/package.json
  components/dashboard/public/maintenance/favicon.ico
  components/dashboard/public/maintenance/favicon192.png
  components/dashboard/public/maintenance/favicon256.png
  components/dashboard/public/maintenance/favicon512.png
  components/dashboard/public/maintenance/gitpod.svg
  components/dashboard/public/maintenance/index.css
  components/dashboard/public/maintenance/index.html
  components/dashboard/public/maintenance/source.css
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/Alert.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/proxy/conf/Caddyfile
Labels: size/L, team: team-experience

#18749 Update containerd and buildkit
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/common-go/go-update-wc-deps.sh
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/image-builder-mk3/image-builder.code-workspace
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/L, team: staff-engineers, team: team-experience, team: team-engine

#18765 Enable CRI plugin in dockerd
  components/docker-up/docker-up/main.go
Labels: size/S, team: team-engine

#18762 Fix react-query cache persistence
  components/dashboard/src/Login.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/data/git-providers/suggested-repositories-query.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/user-context.tsx
Labels: size/L, team: team-experience

#18768 [alerts] Exclude reason "imageBuildFailedUser" from InstanceStartFailures
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/XS, team: team-experience

#18769 [server, dashboard] Remove api.maySetTimeout (+ code cleanup in User- + EntitlementService)
  components/dashboard/src/data/current-user/may-set-timeout-query.ts
  components/dashboard/src/user-settings/Preferences.tsx
  components/gitpod-protocol/src/billing-mode.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#18770 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18772 [dashboard] tone down "Unable to retrieve workspace-auth cookie" to warn
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/XS, team: team-experience

#18767 Add default image get to PAPI and improve Dashboard
  components/dashboard/src/data/workspaces/default-workspace-image-query.ts
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/dummy.pb.go
  components/public-api/go/experimental/v1/v1connect/workspaces.connect.go
  components/public-api/go/experimental/v1/v1connect/workspaces.proxy.connect.go
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/go/experimental/v1/workspaces_grpc.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/dummy_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
  components/server/src/api/workspaces.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XL, team: team-experience

#18716 Add `prebuildDefaultBranchOnly` setting – EXP-574
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/project.go
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app-rules.ts
  components/server/src/prebuilds/github-app.spec.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/prebuild-manager.spec.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.ts
Labels: size/XL, team: team-experience

#18734 Match branch names by pattern – EXP-575
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api-server/pkg/apiv1/project.go
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/server/src/prebuilds/prebuild-manager.spec.ts
  components/server/src/prebuilds/prebuild-manager.ts
Labels: size/L, team: team-experience

#18777 [supervisor] fix panic with runGP option
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/services.go
Labels: size/M, team: team-experience

#18773 add ws client metrics
  components/dashboard/BUILD.yaml
  components/dashboard/src/service/config.json
  components/dashboard/src/service/metrics.ts
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/messaging/browser/connection.ts
  components/public-api/typescript/src/metrics.ts
  components/supervisor/frontend/BUILD.yaml
  components/supervisor/frontend/package.json
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  components/supervisor/frontend/src/ide/ide-web-socket.ts
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  install/installer/pkg/components/ide-metrics/configmap.go
  yarn.lock
Labels: size/XL, team: team-experience

#18727 [server] add google cloud profiler
  components/server/leeway.Dockerfile
  components/server/package.json
  components/server/src/init.ts
  yarn.lock
Labels: size/XXL, team: team-experience

#18771 Update k3s to gen105
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: team-engine

#18781 [content-service] log ready file metrics
  components/content-service/pkg/initializer/initializer.go
Labels: size/XS, team: team-engine

#18785 Retrieve & Copy Org Id in Org settings
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/XS, team: team-experience

#18789 Revert "[dashboard] Downtime in-app announcements (#18761)"
  components/dashboard/public/maintenance/favicon.ico
  components/dashboard/public/maintenance/favicon192.png
  components/dashboard/public/maintenance/favicon256.png
  components/dashboard/public/maintenance/favicon512.png
  components/dashboard/public/maintenance/gitpod.svg
  components/dashboard/public/maintenance/index.css
  components/dashboard/public/maintenance/index.html
  components/dashboard/public/maintenance/source.css
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/proxy/conf/Caddyfile
Labels: size/L, team: team-experience

#18790 add missing getDefaultWorkspaceImage scope for supervisor
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: team-experience

#18780 [loadgen] Simulate workspace activity
  dev/loadgen/pkg/loadgen/executor.go
Labels: size/M, team: team-engine

#18784 Cleanup installer
  License.third-party.go.txt
  install/installer/docs/overview.md
  install/installer/pkg/common/common.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/common/networkpolicies.go
  install/installer/pkg/common/toleration.go
  install/installer/pkg/components/image-builder-mk3/networkpolicy.go
  install/installer/pkg/components/image-builder-mk3/tlssecret.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/deprecations.go
  install/installer/pkg/config/v1/experimental/experimental.go
  install/installer/pkg/config/versions/versions.go
Labels: size/L, team: team-experience, team: team-engine

#18791 Rename settigns button on project create
  components/dashboard/src/projects/NewProject.tsx
Labels: size/XS, team: team-experience

#18786 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18793 [fga] check workspace relationships
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
Labels: size/M, team: team-experience

#18637 fix: change README img link to website
  README.md
Labels: size/XS

#18783 [content-service] download s3 content using s5cmd
  components/content-service/pkg/storage/s3.go
  components/ws-daemon/leeway.Dockerfile
Labels: size/M, team: team-engine

#18779 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18797 [cli] Support gp idp login aws --duration-seconds ENG-815
  components/gitpod-cli/cmd/idp-login-aws.go
Labels: size/S, team: team-experience

#18759 Remove unnecessary call to imageBuilder.needsImageBuild
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience

#18800 [UX] Redirect to newly created org after creation
  components/dashboard/src/teams/NewTeam.tsx
Labels: size/XS, team: team-experience

#18801 [test] Fix concurrent map writes panic
  test/pkg/integration/apis.go
Labels: size/S, team: team-experience, team: team-engine

#18802 [fga] don't await spicedb calls when disabled
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/L, team: team-experience

#18798 Update dev image
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/docker-up/go.mod
  components/docker-up/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  components/ws-manager-mk2/go.mod
  dev/image/Dockerfile
  install/installer/go.mod
  install/installer/go.sum
Labels: size/XL, team: team-experience, team: team-engine

#18799 [ws-proxy] additional logging to better errors causing OTHER error_type
  components/ws-proxy/pkg/sshproxy/server.go
Labels: size/XS, team: team-engine

#18806 Use yarn run to execute rimraf
  components/server/package.json
Labels: size/XS, team: team-experience

#18804 Update checkout action to v4
  .github/actions/setup-environment/action.yml
  .github/workflows/authorization.yml
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/configcat.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-delete.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/public-api.yml
  .github/workflows/update-image-digest.yml
  .github/workflows/workspace-integration-tests.yml
Labels: size/M, team: team-experience, team: team-engine

#18810 [stripe] reconcile missing invoices
  components/gitpod-db/go/cost_center.go
  components/gitpod-db/go/cost_center_test.go
  components/public-api-server/pkg/webhooks/stripe.go
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/stripe/stripe.go
Labels: size/L, team: team-experience

#18811 [server] keep gitStatus on new instances
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: team-experience

#18813 Fix repo selector loading state and client cache bug
  components/dashboard/package.json
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/setup.tsx
Labels: size/M, team: team-experience

#18803 [metrics] surface user agent and original error timestamp
  components/dashboard/src/service/service.tsx
  components/public-api/typescript/src/metrics.ts
Labels: size/S, team: team-experience

#18807 [usage] FindRunningWorkspaceInstances: Make sure we use an index
  components/gitpod-db/go/workspace_instance.go
  components/gitpod-db/go/workspace_instance_test.go
  components/usage/pkg/apiv1/usage.go
Labels: size/M, team: team-experience

#18812 [server] also log the actual request name
  components/server/src/server.ts
  components/server/src/util/log-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/XS, team: team-experience

#18816 Fix UI Overflow Issue for Long Organization Names
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/XS, team: team-experience

#18809 [server, usage, db] Drop CostCenter.deleted (not used)
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/migration/1695735203768-CostCenterDropDeleted.ts
Labels: size/S, team: team-experience

#18808 [db] DBCodeSyncResource/-Collection: Drop deleted column
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/code-sync-resource-db.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-collection.ts
  components/gitpod-db/src/typeorm/entity/db-code-sync-resource.ts
  components/gitpod-db/src/typeorm/migration/1695733993909-CodeSyncDropDeleted.ts
Labels: size/M, team: team-experience

#18819 [usage] fix reconcilation
  components/usage/pkg/apiv1/billing.go
Labels: size/XS, team: team-experience

#18794 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#18818 [db] DBPrebuiltWorkspace: Add index ind_creationTime
  components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts
  components/gitpod-db/src/typeorm/migration/1695797972732-PrebuildAddIndexCreationTime.ts
Labels: size/S, team: team-experience

#18820 [usage] Add index for usage.draft
  components/gitpod-db/src/typeorm/migration/1695798975062-UsageAddIndexDraft.ts
Labels: size/S, team: team-experience

#18822 [usage] fix gorm error
  components/usage/pkg/apiv1/billing.go
Labels: size/XS, team: team-experience

#18821 [db] UserEnvVar: add index ind_userID
  components/gitpod-db/src/typeorm/entity/db-user-env-vars.ts
  components/gitpod-db/src/typeorm/migration/1695806629753-UserEnvVarAddIndexUserId.ts
Labels: size/M, team: team-experience

#18824 Org selector UI bug fix
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/XS, team: team-experience

#18782 Relax assumptions in supervisor
  components/content-service/pkg/executor/executor.go
  components/content-service/pkg/git/git.go
  components/content-service/pkg/initializer/git.go
  components/content-service/pkg/initializer/initializer.go
  components/supervisor/cmd/dump-initializer.go
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/docker.go
  components/supervisor/pkg/supervisor/git.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/ssh.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/user.go
  components/supervisor/pkg/supervisor/user_test.go
  components/ws-daemon/pkg/content/initializer.go
Labels: size/XL, team: team-experience, team: team-engine

#18828 Ensure containers inherit stdio
  components/docker-up/runc-facade/main.go
Labels: size/XS, team: team-engine

#18829 [content-service] log duration for s3 download and tar extract
  components/content-service/pkg/storage/s3.go
Labels: size/XS, team: team-engine

#18830 [ci] wait 5m on publish to yarn register before timing out
  components/gitpod-protocol/scripts/publish.js
Labels: size/S, team: team-experience

#18834 Add subassembly service API
  components/image-builder-api/go/config/config.go
  components/image-builder-api/go/subassembly.pb.go
  components/image-builder-api/go/subassembly_grpc.pb.go
  components/image-builder-api/subassembly.proto
  components/image-builder-api/typescript/src/subassembly_grpc_pb.d.ts
  components/image-builder-api/typescript/src/subassembly_grpc_pb.js
  components/image-builder-api/typescript/src/subassembly_pb.d.ts
  components/image-builder-api/typescript/src/subassembly_pb.js
  components/ws-manager-api/go/config/config.go
Labels: size/M, team: team-engine

#18832 [db] DBWorkspace: add ind_basedOnPrebuildId
  components/gitpod-db/src/typeorm/migration/1695888330735-WorkspaceIndexBasedOnPrebuildId.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/S, team: team-experience

#18836 [db] Add index for user.verificationPhoneNumber
  components/gitpod-db/src/typeorm/migration/1695901995842-UserAddIndexVerificationPhoneNumber.ts
Labels: size/S, team: team-experience

#18835 [dashboard] remember options per repo
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: team-experience

#18837 [dashboard] set project wsClass
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: team-experience
