Repository gitpod-io/gitpod, pull requests merged in 2023-10, with the labels that each got.

#18848 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18854 [UI] `CreateWorkspace` Overflow bug fix
  components/dashboard/src/components/DropDown2.tsx
Labels: size/XS, team: team-experience

#18855 Increase getSuggestedRepositories client cache to 7 days
  components/dashboard/src/data/git-providers/suggested-repositories-query.ts
Labels: size/XS, team: team-experience

#18856 Implement searchRepos for Bitbucket
  components/server/package.json
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  yarn.lock
Labels: size/M, team: team-experience

#17969 Update `marketplace.json`
  components/ide-proxy/static/code/marketplace.json
Labels: size/M, team: team-experience

#18863 [content-service] remove s5cmd integration
  components/content-service/pkg/storage/s3.go
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/pkg/content/initializer.go
Labels: size/M, team: team-engine

#18853 [public-api] add request context
  components/dashboard/src/service/metrics.ts
  components/server/src/api/dummy.ts
  components/server/src/api/server.ts
  components/server/src/server.ts
  components/server/src/util/log-context.ts
Labels: size/L, team: team-experience

#18867 Prepare code nightly for release
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience

#18862 Implement `searchRepos` for GitLab Repository Provider
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/api.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
Labels: size/M, team: team-experience

#18870 Fix loading state bug when creating new workspace
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: team-experience

#18861 Load recent repos and not all repos for BBS
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/M, team: team-experience

#18868 VS Code Browser Release `1.83.0`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18823 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18851 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18873 Update Platform Version of JetBrains Backend Plugin (EAP) to 233.8264-EAP-CANDIDATE-SNAPSHOT
  .gitpod.yml
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
Labels: size/S, team: team-experience

#18872 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18876 [jb-gw] prepare for EAP 3
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS

#18874 adding missing fields to CreateAndStartWorkspace
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/S, team: team-experience

#18866 Move towards sync deletion (away from PeriodicDeleter) - step II/II
  components/gitpod-db/go/organization.go
  components/gitpod-db/go/organization_membership.go
  components/gitpod-db/go/project.go
  components/gitpod-db/go/project_test.go
  components/gitpod-db/src/auth-provider-entry.spec.db.ts
  components/gitpod-db/src/tables.ts
  components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-auth-provider-entry.ts
  components/gitpod-db/src/typeorm/entity/db-gitpod-token.ts
  components/gitpod-db/src/typeorm/entity/db-project-usage.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/entity/db-team-membership.ts
  components/gitpod-db/src/typeorm/entity/db-team.ts
  components/gitpod-db/src/typeorm/entity/db-token-entry.ts
  components/gitpod-db/src/typeorm/entity/db-user-ssh-public-key.ts
  components/gitpod-db/src/typeorm/migration/1695810605786-TeamDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695817445588-ProjectDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695819413747-DropTableUserStorageResource.ts
  components/gitpod-db/src/typeorm/migration/1695820427730-TokenEntryDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695820658574-AuthProviderEntryDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695821079717-GitpodTokenDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695821464987-TeamMembershipDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695821957148-ProjectUsageDropDeleted.ts
  components/gitpod-db/src/typeorm/migration/1695822248160-UserSshPublicKeyDropDeleted.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/user/gitpod-token-service.ts
Labels: size/XL, team: team-experience

#18881 [server] let me see the error
  components/server/src/projects/projects-service.ts
Labels: size/XS, team: team-experience

#18882 [server] fix null pointer error in projects-service
  components/server/src/projects/projects-service.ts
Labels: size/S, team: team-experience

#18880 [ssh] flexible auth user
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/supervisor-api/control.proto
  components/supervisor-api/go/control.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Control.java
  components/supervisor/pkg/supervisor/services.go
  components/ws-proxy/pkg/sshproxy/server.go
Labels: size/L, team: team-experience, team: team-engine

#18885 Check s3 DeleteObjects response for errors
  components/content-service/pkg/storage/s3.go
Labels: size/XS, team: team-engine

#18877 [code] Update web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#18887 [code] point back to main branch
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience

#18892 Fix account deletion modal
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/Modal.tsx
Labels: component: dashboard, size/S, team: team-experience

#18897 [grafana] SpiceDB dashboard: add graphs for cache hit/miss rate and ratio
  operations/observability/mixins/meta/dashboards/components/spicedb.json
Labels: size/L, team: team-experience

#18896 Extend subassembly service with manifest
  components/image-builder-api/go/subassembly.pb.go
  components/image-builder-api/subassembly.proto
  components/image-builder-api/typescript/src/subassembly_pb.d.ts
  components/image-builder-api/typescript/src/subassembly_pb.js
Labels: size/XS, team: team-engine

#18888 [code] Cleanup unused replace rules
  components/ide/code/codehelper/main.go
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/L, team: team-experience

#18886 Update connect libraries
  components/dashboard/package.json
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/public-api/buf.gen.yaml
  components/public-api/typescript/package.json
  components/public-api/typescript/src/gitpod/experimental/v1/cell_stats_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/cell_stats_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/dummy_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/dummy_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/editor_service_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/editor_service_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/ide_client_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/ide_client_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/identityprovider_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/identityprovider_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/idp_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/idp_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/index.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/pagination_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/scm_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/scm_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/stats_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/stats_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/tokens_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspace_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
  components/public-api/typescript/src/metrics.ts
  components/server/package.json
  components/server/src/api/dummy.ts
  components/server/src/api/handler-context-augmentation.d.ts
  components/server/src/api/server.ts
  components/server/src/api/stats.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/teams.ts
  components/server/src/api/user.spec.ts
  components/server/src/api/user.ts
  components/server/src/api/workspaces.ts
  components/supervisor/frontend/tsconfig.json
  components/supervisor/frontend/webpack.config.js
  yarn.lock
Labels: size/XL, team: team-experience

#18893 [server] SpiceDB: Add request-level caching based on AsyncLocalStorage+ZedTokens
  components/BUILD.yaml
  components/server/BUILD.yaml
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/caching-spicedb-authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/container-module.ts
  components/server/src/util/log-context.ts
  components/spicedb/buf.gen.yaml
  components/spicedb/buf.yaml
  components/spicedb/generate.sh
  components/spicedb/typescript/BUILD.yaml
  components/spicedb/typescript/package.json
  components/spicedb/typescript/src/google/api/expr/v1alpha1/checked.pb.ts
  components/spicedb/typescript/src/google/api/expr/v1alpha1/syntax.pb.ts
  components/spicedb/typescript/src/google/protobuf/duration.pb.ts
  components/spicedb/typescript/src/google/protobuf/empty.pb.ts
  components/spicedb/typescript/src/google/protobuf/struct.pb.ts
  components/spicedb/typescript/src/google/protobuf/timestamp.pb.ts
  components/spicedb/typescript/src/impl/v1/impl.pb.ts
  components/spicedb/typescript/tsconfig.json
Labels: size/XXL, team: team-experience

#18900 [tests] DB: remove deleted column
  test/pkg/integration/apis.go
Labels: size/XS, team: team-experience, team: team-engine

#18901 [server] SpiceDB: Add metric for consistency usage
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/caching-spicedb-authorizer.ts
  components/server/src/prometheus-metrics.ts
Labels: size/L, team: team-experience

#18903 [fga] further debug sharing issue
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/M, team: team-experience

#18894 [server] (re)move deprecated properties
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
Labels: size/L, team: team-experience

#18905 [spicedb] update spicedb
  install/installer/pkg/components/spicedb/constants.go
Labels: size/XS, team: team-experience

#18907 [fga] bump version to redo migrations
  components/server/src/authorization/relationship-updater.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience

#18898 ZedTokens: SpiceDBAuthorizer cleanup
  components/server/src/api/server.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/caching-spicedb-authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/container-module.ts
  components/server/src/jobs/runner.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/server.ts
  components/server/src/util/log-context.ts
  components/server/src/util/request-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/XXL, team: team-experience

#18904 [grafana] SpiceDB: add graph for request consistency
  operations/observability/mixins/meta/dashboards/components/spicedb.json
Labels: size/L, team: team-experience

#18899 Remove Outdated and Safe-to-Delete Feature Flags
  components/dashboard/src/data/featureflag-query.ts
Labels: size/XS, team: team-experience

#18910 [spicedb] Fix application of migrations with ArgoCD
  components/server/src/authorization/relationship-updater.ts
  components/spicedb/buf.gen.yaml
  components/spicedb/typescript/src/impl/v1/impl.pb.ts
  install/installer/pkg/components/spicedb/migrations.go
Labels: size/S, team: team-experience

#18911 [spicedb] Apply migrations in the ArgoCD PreSync hook
  install/installer/pkg/components/spicedb/migrations.go
Labels: size/XS, team: team-experience

#18915 [ws-proxy] Add /health route
  components/ws-proxy/pkg/proxy/proxy.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: size/S, team: team-engine

#18914 Update VS Code Browser to `1.73.1`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18917 [proxy] Add /api/health 200
  components/proxy/conf/Caddyfile
Labels: size/XS, team: team-experience

#18735 [server] Remove feature flag workspace_start_controller
  components/server/src/workspace/workspace-start-controller.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience

#18916 [eng-874] workspace creating time metric
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
Labels: size/M, team: team-engine

#18889 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18875 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18919 [papi] add ListTeamMembers and GetTeamInvitation APIs
  components/public-api-server/pkg/apiv1/team.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/go/experimental/v1/teams.pb.go
  components/public-api/go/experimental/v1/teams_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/teams.connect.go
  components/public-api/go/experimental/v1/v1connect/teams.proxy.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/teams_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
  components/server/src/api/teams.ts
Labels: size/L, team: team-experience

#18913 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18918 add new repo list/detail routes behind flag
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/repositories/detail/RepositoryDetail.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
Labels: size/M, team: team-experience

#18895 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#18871 adding create project modal
  components/dashboard/package.json
  components/dashboard/src/components/Alert.tsx
  components/dashboard/src/components/AuthorizeGit.tsx
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/dashboard/src/data/projects/list-projects-query.ts
  components/dashboard/src/hooks/use-temporary-value.ts
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/create-project-modal/CreateProjectModal.tsx
  components/dashboard/src/start/Open.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/projects/projects-service.ts
  components/server/src/projects/scm-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/suggested-repos-sorter.spec.ts
  components/server/src/workspace/suggested-repos-sorter.ts
  yarn.lock
Labels: size/XXL, team: team-experience

#18926 (ci): fix setup environment's step name
  .github/workflows/build.yml
Labels: size/XS

#18924 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18927 Update leeway to v0.7.9
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  dev/image/Dockerfile
Labels: size/M, team: team-experience, team: team-engine

#18929 [e2e] Fix multi-repo test
  test/tests/components/ws-manager/multi_repo_test.go
Labels: size/XS, team: team-engine

#18921 remove supervisor_live_git_status
  components/common-go/experiments/flags.go
  components/dashboard/src/components/PendingChangesDropdown.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/workspace-instance.ts
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/supervisor/pkg/supervisor/git.go
  components/ws-manager-bridge/src/bridge.ts
Labels: size/L, team: staff-engineers, team: team-experience

#18932 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18923 Setup podkit folder and move Combobox into it
  components/dashboard/package.json
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/podkit/combobox/Combobox.tsx
  components/dashboard/src/hooks/use-debounce.ts
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: size/M, team: team-experience

#18930 [public-api] add v2 WorkspaceService.getWorkspace
  components/public-api/gitpod/experimental/v2/workspace.proto
  components/public-api/go/experimental/v2/v2connect/workspace.connect.go
  components/public-api/go/experimental/v2/v2connect/workspace.proxy.connect.go
  components/public-api/go/experimental/v2/workspace.pb.go
  components/public-api/go/experimental/v2/workspace_grpc.pb.go
  components/public-api/typescript/BUILD.yaml
  components/public-api/typescript/src/gitpod/experimental/v2/workspace_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v2/workspace_pb.ts
Labels: size/XL, team: team-experience

#18934 Fix incorrect start workspace url
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/supervisor/frontend/src/shared/urls.ts
Labels: size/XS, team: team-experience

#18937 Make installer a bit more extensible
  dev/version-manifest/main.go
  dev/version-manifest/version-manifest
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/versions/versions.go
Labels: size/L, team: team-experience

#18852 Privacy policy update alert
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: team-experience

#18935 Setup data loading for repos list
  components/dashboard/craco.config.js
  components/dashboard/package.json
  components/dashboard/src/components/RepositoryURL.tsx
  components/dashboard/src/components/podkit/lib/cn.ts
  components/dashboard/src/components/podkit/typography/Text.tsx
  components/dashboard/src/components/podkit/typography/TextMuted.tsx
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/dashboard/src/data/projects/list-all-projects-query.ts
  components/dashboard/src/data/projects/list-projects-query.ts
  components/dashboard/src/hooks/use-pretty-repo-url.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/project-context.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/tsconfig.json
  yarn.lock
Labels: size/XL, team: team-experience

#18936 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18884 [dashboard] integrate v2 WorkspaceService.getWorkspace
  components/dashboard/src/components/PendingChangesDropdown.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/user-context.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/gitpod-protocol/BUILD.yaml
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/context-url.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/proxy/conf/Caddyfile
  components/server/src/api/hello-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/api/workspaces.ts
Labels: size/XXL, team: team-experience

#18949 Add IPFS storage to overview dashboard
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/L, team: team-engine

#18941 Increase project name max length
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/server/src/projects/projects-service.ts
Labels: size/M, team: team-experience

#18944 Revert "unblock EXP-96 (#18387)"
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
Labels: size/S, team: team-experience

#18952 Fix Alert close icon colors
  components/dashboard/src/components/Alert.tsx
Labels: component: dashboard, size/S, team: team-experience

#18951 [supervisor] increase default workspace image cache duration and do p…
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/S, team: team-experience

#18948 [GRPC] Organization API
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/.vscode/settings.json
  components/gitpod-protocol/BUILD.yaml
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/experimental/v2/organization.proto
  components/public-api/gitpod/experimental/v2/pagination.proto
  components/public-api/go/experimental/v2/organization.pb.go
  components/public-api/go/experimental/v2/organization_grpc.pb.go
  components/public-api/go/experimental/v2/pagination.pb.go
  components/public-api/go/experimental/v2/v2connect/organization.connect.go
  components/public-api/go/experimental/v2/v2connect/organization.proxy.connect.go
  components/public-api/typescript/src/gitpod/experimental/v2/organization_connect.ts
  components/public-api/typescript/src/gitpod/experimental/v2/organization_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v2/pagination_pb.ts
  components/server/src/api/organization-service-api.ts
Labels: size/XXL

#18956 [supervisor] Don't panic if connection is already closed
  components/gitpod-protocol/go/reconnecting-ws.go
Labels: size/XS, team: team-experience

#18954 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18957 fix JWT verification
  components/server/src/session-handler.ts
Labels: size/XS, team: team-experience

#18959 Ak/revert
  components/server/src/api/rate-limited.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/config.ts
  components/server/src/session-handler.ts
Labels: size/L, team: team-experience

#18958 [installer] Change cookie name
  install/installer/pkg/components/auth/config.go
  install/installer/pkg/components/auth/config_test.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/server/configmap_test.go
Labels: size/S, team: team-experience

#18963 Update PAPI component, should cause a new build
  components/public-api-server/README.md
  components/public-api-server/pkg/oidc/service_test.go
Labels: size/XS, team: team-experience

#18962 [db] userById fails on undefined
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.spec.db.ts
Labels: size/M, team: team-experience

#18964 [server] report internal errors to check permissions
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/XS, team: team-experience

#18966 [server] JWT cookie management tests
  components/server/src/auth/jwt.spec.ts
  components/server/src/config.ts
  components/server/src/session-handler.spec.db.ts
  components/server/src/session-handler.ts
  components/server/src/test/service-testing-container-module.ts
Labels: size/XL, team: team-experience

#18973 Revert "Revert "unblock EXP-96 (#18387)""
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
Labels: size/S, team: team-experience

#18975 [jb-gw] work around a bug in supervisor returning an empty user
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/XS, team: team-experience

#18977 [supervisor] return missing user for ssh keys
  components/supervisor/pkg/supervisor/services.go
Labels: size/XS, team: team-experience

#18968 [public-api] put back rate limiting
  components/server/src/api/rate-limited.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/config.ts
Labels: size/L, team: team-experience

#18978 [a11y] User setting Git providers 📱 improvement
  components/dashboard/src/components/Modal.tsx
Labels: user experience, size/XS, aspect: accessibility, team: team-experience

#18961 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18982 Add throughput condition
  components/ws-manager-api/go/crd/v1/workspace_types.go
Labels: size/S, team: team-engine

#18985 Only show privacy policy notice on Gitpod Cloud
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/AppNotifications.tsx
  components/server/src/user/user-service.ts
Labels: size/M, team: team-experience

#18988 Automatically accept privacy policy upon registering
  components/server/src/user/user-service.ts
Labels: size/XS, team: team-experience

#18987 Fix `?until` in BBS commit contexts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
Labels: size/M, team: team-experience

#18986 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18989 [server] fix deleteUser permissions
  components/server/src/user/user-deletion-service.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience
