Repository gitpod-io/gitpod, pull requests merged in 2023-03, with the labels that each got.

#16616 Adding a company size question to new user onboarding flow
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/dashboard/src/onboarding/company-size.ts
  components/dashboard/src/onboarding/exploration-reasons.ts
  components/gitpod-protocol/src/protocol.ts
Labels: size/M, team: webapp, release-note-none

#16602 [db-sync] Remove remaining references
  components/gitpod-db/go/oidc_client_config.go
  components/gitpod-db/go/personal_access_token.go
  components/gitpod-db/go/project.go
  components/gitpod-db/go/stripe_customer.go
  components/gitpod-db/go/team.go
  components/gitpod-db/go/team_membership.go
  components/gitpod-db/go/workspace.go
  components/gitpod-db/go/workspace_instance.go
  components/gitpod-db/src/typeorm/entity/db-blocked-repository.ts
  components/gitpod-db/src/typeorm/entity/db-pending-github-event.ts
  components/gitpod-db/src/typeorm/entity/db-prebuild-info-entry.ts
  components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace-updatable.ts
  components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts
  components/gitpod-db/src/typeorm/entity/db-project-env-vars.ts
  components/gitpod-db/src/typeorm/entity/db-project-info.ts
  components/gitpod-db/src/typeorm/entity/db-project-usage.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/entity/db-team-membership-invite.ts
  components/gitpod-db/src/typeorm/entity/db-team-membership.ts
  components/gitpod-db/src/typeorm/entity/db-team-subscription-2.ts
  components/gitpod-db/src/typeorm/entity/db-team.ts
  components/gitpod-db/src/typeorm/entity/db-user-ssh-public-key.ts
  components/gitpod-db/src/typeorm/entity/db-webhook-event.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/server/src/auth/bearer-authenticator.ts
  components/server/src/workspace/workspace-deletion-service.ts
  components/ws-manager-bridge/src/bridge.ts
  operations/observability/mixins/meta/dashboards/components/db.json
  operations/observability/mixins/meta/dashboards/components/meta-services.json
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/L, team: webapp, release-note-none

#16600 [stripe] Return NotFound for non-existent attribution IDs
  components/server/ee/src/user/stripe-service.ts
Labels: size/XS, team: webapp, release-note-none

#16612 [ws-manager-mk2] Show start failures in dashboard, show daemon ctrl metrics
  operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
  operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json
Labels: size/XXL, team: workspace, release-note-none

#16611 [ws-manager-mk2] Remove headless field
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/XS, team: workspace, release-note-none

#16585 [ws-manager-mk2] Refactor metric collection and add tests
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
Labels: size/L, team: workspace, release-note-none

#16608 Allow registry-facade and ws-daemon to run in dedicated GPU node pools
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/toleration.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: size/M, team: workspace, release-note-none, team: security-infrastructure-and-delivery

#16599 [redis] Fix readiness probe
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/redis/deployment.go
Labels: size/XS, team: webapp, release-note-none, team: security-infrastructure-and-delivery

#16620 [supervisor] instance update fatal if no permission
  components/supervisor/pkg/serverapi/publicapi.go
Labels: size/XS, team: IDE, release-note-none

#16623 Updating company size labels
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/dashboard/src/onboarding/company-size.ts
Labels: size/S, team: webapp, release-note-none

#16628 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16592 Adding a Button component
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/icons/SpinnerWhite.svg
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/L, team: webapp, release-note-none

#16627 Pull project from useCurrentProject()
  components/dashboard/src/projects/ProjectSettings.tsx
Labels: size/XS, team: webapp, release-note

#16445 [server] Log user errors as info
  components/gitpod-protocol/src/messaging/error.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/S, team: webapp, release-note-none

#16629 [server] Only show notifications for not-cancelled subscriptions
  components/gitpod-protocol/src/team-subscription-protocol.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#16630 [admin] Remove non-working workspace links
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/admin/gcp-info.ts
Labels: size/L, team: webapp, release-note-none

#16618 Making top nav menu responsive
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/Separator.tsx
  components/dashboard/src/index.css
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/onboarding/UserOnboarding.tsx
Labels: size/XL, team: webapp, release-note-none

#16519 [ws-manager-mk2] Setup separate image builder deployment for mk2
  components/image-builder-mk3/cmd/run.go
  components/ws-manager-mk2/service/manager.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/components-workspace/components.go
  install/installer/pkg/components/image-builder-mk3-wsman/clusterrole.go
  install/installer/pkg/components/image-builder-mk3-wsman/configmap.go
  install/installer/pkg/components/image-builder-mk3-wsman/constants.go
  install/installer/pkg/components/image-builder-mk3-wsman/deployment.go
  install/installer/pkg/components/image-builder-mk3-wsman/networkpolicy.go
  install/installer/pkg/components/image-builder-mk3-wsman/objects.go
  install/installer/pkg/components/image-builder-mk3-wsman/rolebinding.go
  install/installer/pkg/components/image-builder-mk3-wsman/tlssecret.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
Labels: size/XXL, team: workspace, release-note-none, feature: ws-manager-mk2, team: security-infrastructure-and-delivery

#16622 [ws-manager-mk2] Fix race where pod gets recreated in Stopped phase
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json
Labels: size/M, team: workspace, release-note-none

#16590 Update VS Code Browser to `1.76`
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16638 [server] Implement tsAddMembersToOrg
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#16646 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16596 New Settings option & `New Workspace ...` fix
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
Labels: size/XS, team: webapp, release-note

#16655 [redis] Fix readiness probe (again)
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/redis/deployment.go
Labels: size/XS, release-note-none, team: security-infrastructure-and-delivery

#16654 [ws-daemon] Check connection to containerd socket
  components/ws-daemon/pkg/container/containerd.go
  install/installer/cmd/config_files_containerd.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/containerd/k3s.go
  install/installer/pkg/containerd/location.go
Labels: size/L, team: workspace, release-note-none, team: security-infrastructure-and-delivery

#16650 Remove SID as default owner of installer/installer
  .github/CODEOWNERS
Labels: size/XS, release-note-none, team: security-infrastructure-and-delivery

#16657 fix: Improved Integrations UX
  components/dashboard/src/user-settings/AuthEntryItem.tsx
  components/dashboard/src/user-settings/IntegrationItemEntry.tsx
  components/dashboard/src/user-settings/Integrations.tsx
Labels: community-contribution, size/L, release-note

#16659 [server] Polish notification texts
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#16482 Gitpod OIDC Identity Provider
  components/gitpod-cli/BUILD.yaml
  components/gitpod-cli/cmd/idp-login-aws.go
  components/gitpod-cli/cmd/idp-login-vault.go
  components/gitpod-cli/cmd/idp-login.go
  components/gitpod-cli/cmd/idp-token.go
  components/gitpod-cli/cmd/idp.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/middleware/logging.go
  components/public-api-server/middleware/logging_test.go
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
  components/public-api-server/pkg/identityprovider/cache.go
  components/public-api-server/pkg/identityprovider/cache_test.go
  components/public-api-server/pkg/identityprovider/idp.go
  components/public-api-server/pkg/identityprovider/idp_test.go
  components/public-api-server/pkg/server/server.go
  components/public-api/gitpod/experimental/v1/identityprovider.proto
  components/public-api/go/client/client.go
  components/public-api/go/config/config.go
  components/public-api/go/experimental/v1/identityprovider.pb.go
  components/public-api/go/experimental/v1/identityprovider_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/identityprovider.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/identityprovider_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/identityprovider_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/idp_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/idp_pb.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/public-api-server/configmap.go
  install/installer/pkg/components/public-api-server/configmap_test.go
Labels: size/XXL, team: webapp, team: IDE, release-note-none

#16633 Simplify image-builder-mk3 and registry-facade init containers
  components/BUILD.yaml
  components/image-builder-mk3/cmd/setup.go
  components/image-builder-mk3/leeway.Dockerfile
  components/registry-facade/ca-updater/BUILD.yaml
  components/registry-facade/ca-updater/Dockerfile
  components/registry-facade/ca-updater/README.md
  components/registry-facade/ca-updater/install-packages
  components/registry-facade/cmd/setup.go
  components/registry-facade/leeway.Dockerfile
  components/ws-manager/pkg/manager/manager.go
  dev/ready-probe-labeler/main.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/ca.go
  install/installer/pkg/common/common.go
  install/installer/pkg/components/image-builder-mk3-wsman/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/registry-facade/configmap.go
  install/installer/pkg/components/registry-facade/constants.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/registry-facade/objects.go
Labels: size/XL, team: workspace, release-note-none, team: security-infrastructure-and-delivery

#16656 [server] Remove feature flag controller - unused
  .github/pull_request_template.md
  components/server/src/container-module.ts
  components/server/src/feature-flag/featureflag-controller.ts
  components/server/src/server.ts
Labels: size/M, team: webapp, release-note-none

#16632 [server] Log empty origin header in debug, attach origin to other log
  components/server/src/express-util.ts
  components/server/src/server.ts
Labels: size/XS, team: webapp, release-note-none

#16677 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16635 [github] Improve log entries when retrieving github files
  components/server/src/github/file-provider.ts
Labels: size/M, team: webapp, release-note-none

#16647 Report ErrorBoundary from Dashboard
  components/dashboard/src/components/ErrorBoundary.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#16626 [public-api] Auto-generate proxy handler
  components/public-api/buf.gen.yaml
  components/public-api/generate.sh
  components/public-api/go/experimental/v1/v1connect/ide_client.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/oidc.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/projects.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/teams.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/tokens.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/user.proxy.connect.go
  components/public-api/go/experimental/v1/v1connect/workspaces.proxy.connect.go
  components/public-api/go/protoc-proxy-gen/protoc-proxy-gen.go
  gitpod-ws.code-workspace
Labels: size/XXL, team: webapp, release-note-none

#16663 [server] Implement cancelTeamSubscription
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp, release-note-none

#16634 [prebuild] Log github app user errors as info
  components/server/ee/src/prebuilds/github-app.ts
Labels: size/S, team: webapp, release-note-none

#16680 [server] Log github getFileContent errors in debug
  components/server/src/github/file-provider.ts
Labels: size/XS, team: webapp, release-note-none

#16601 [ws-manager-mk2] Protect environment secrets
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/role.go
Labels: size/L, team: workspace, release-note-none, feature: ws-manager-mk2

#16683 [image-builder] Set correct image name
  install/installer/pkg/components/image-builder-mk3-wsman/deployment.go
Labels: size/XS, team: workspace, release-note-none

#16637 [ws-man-bridge] Remove non-governing codepaths
  components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/config.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
  components/ws-manager-bridge/src/preparing-update-emulator.ts
  components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Labels: size/L, team: webapp, release-note-none

#16681 update yarn.lock
  yarn.lock
Labels: size/S, release-note-none

#16613 [ws-manager-mk2] Loadgen fixes, concurrent reconciliation
  components/ws-daemon/pkg/controller/snapshot_controller.go
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/service/manager.go
  dev/loadgen/cmd/benchmark.go
  dev/loadgen/pkg/loadgen/executor.go
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
Labels: size/L, team: workspace, release-note-none

#16643 [ws-manager-mk2] Enable tracing, add debug logs
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
  dev/loadgen/pkg/loadgen/executor.go
  dev/loadgen/pkg/observer/success.go
Labels: size/M, team: workspace, release-note-none

#16665 [ws-manager-mk2] Fix stopped status
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
Labels: size/XS, team: workspace, release-note-none

#16678 Switch to Pay-as-you-go
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/SwitchToPAYG.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/org-icon/OrgIcon.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: webapp, release-note-none

#16687 [ws-manager-mk2] Add duration validation
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
Labels: size/XS, team: workspace, release-note-none

#16692 bump up gitpod-code to pick up fixes for rebuild hints
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16673 Adding Typography components for Headings/Subheadings
  components/dashboard/src/Login.tsx
  components/dashboard/src/Setup.tsx
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/Blocked.tsx
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/components/ErrorBoundary.tsx
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/ThemeSelector.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/onboarding/StepPersonalize.tsx
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/Billing.tsx
  components/dashboard/src/user-settings/ChargebeeTeams.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/Notifications.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/user-settings/SelectAccountModal.tsx
  components/dashboard/src/whatsnew/WhatsNew.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/tailwind.config.js
Labels: size/XXL, team: webapp, release-note-none

#16693 [gp] track git event with instanceId
  components/gitpod-cli/cmd/git-track-command.go
Labels: size/XS, team: IDE, release-note-none

#16696 [server] lower the heartbeat limit
  components/server/src/auth/rate-limiter.ts
Labels: size/XS, team: webapp, release-note-none

#16695 Reuse context from the reconciler
  components/ws-manager/pkg/manager/pod_controller.go
Labels: size/XS, team: workspace, release-note-none

#16671 Update containerd self-signed certificate configuration
  components/registry-facade/cmd/setup.go
Labels: size/S, team: workspace, release-note-none

#16703 Add README to `ide-metrics`
  components/ide-metrics/README.md
Labels: size/S, team: IDE, release-note-none

#16705 [server] fix typo in rate limiter
  components/server/src/auth/rate-limiter.ts
Labels: size/XS, team: webapp, release-note-none

#16694 User Preferences page cleanup
  components/dashboard/src/data/current-user/may-set-timeout-query.ts
  components/dashboard/src/user-settings/Preferences.tsx
Labels: size/L, team: webapp, release-note-none

#16701 Add `x-client` in ide-metrics component
  components/ide-metrics-api/go/config/config.go
  components/ide-metrics/config-example.json
  components/ide-metrics/pkg/server/server.go
  components/ide-metrics/pkg/server/server_test.go
  components/supervisor/pkg/metrics/reporter.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/L, team: IDE, release-note-none

#16685 [dashboard] query cache orgs
  components/dashboard/src/App.tsx
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/SwitchToPAYG.tsx
  components/dashboard/src/Usage.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/License.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/OrgRequiredRoute.tsx
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/contexts/FeatureFlagContext.tsx
  components/dashboard/src/data/auth-providers/delete-org-auth-provider-mutation.ts
  components/dashboard/src/data/auth-providers/org-auth-providers-query.ts
  components/dashboard/src/data/billing-mode/org-billing-mode-query.ts
  components/dashboard/src/data/organizations/org-members-query.ts
  components/dashboard/src/data/organizations/orgs-query.ts
  components/dashboard/src/data/projects/list-projects-query.ts
  components/dashboard/src/experiments/client.ts
  components/dashboard/src/hooks/use-user-and-teams-loader.ts
  components/dashboard/src/index.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/project-context.tsx
  components/dashboard/src/start/CreateWorkspace.tsx
  components/dashboard/src/teams/GitIntegrationsPage.tsx
  components/dashboard/src/teams/JoinTeam.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/teams-context.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
Labels: size/XXL, team: webapp, release-note-none

#16699 Update styles on Switch to PAYG
  components/dashboard/src/SwitchToPAYG.tsx
Labels: size/M, team: webapp, release-note-none

#16688 [ws-manager-mk2] Fix prebuild update events
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace, release-note-none, feature: ws-manager-mk2

#16559 [gha] tidy up the build, and skip job if pr got edited, but there were no checkbox changes
  .github/workflows/build.yml
Labels: size/L, release-note-none

#16708 [dashboard] cache get SupportedWorkspaceClasses
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/user-settings/selectClass.tsx
Labels: size/L, team: webapp, release-note-none

#16710 [code] Point back to main branch
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE, release-note-none

#16714 [public-api] Fix GetIDToken test
  components/public-api-server/pkg/apiv1/identityprovider_test.go
Labels: size/XS, team: webapp, release-note-none

#16667 Remove invalid files
  install/installer/go.mod.orig
  install/installer/go.mod.rej
Labels: size/XL, release-note-none

#16421 [gha] comment ops + recreate_vm
  .github/actions/preview-create/entrypoint.sh
  .github/actions/preview-create/metadata.yml
  .github/workflows/build.yml
  .github/workflows/comment-action.yaml
  .github/workflows/comment-ops.yaml
Labels: size/L, release-note-none

#16719 Add missing IDE GH Actions to `CODEOWNERS`
  .github/CODEOWNERS
Labels: size/XS, team: IDE, release-note-none

#16726 [server] ensure workspaces get started once
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, release-note-none

#16730 [gha] fix comment ops
  .github/workflows/comment-ops.yaml
Labels: size/S, release-note-none

#16716 [image-builder-bob] update to buildkit 0.11.4
  components/common-go/go-update-wc-deps.sh
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XS, team: workspace, release-note-none, team: staff-engineers

#16732 [gha] fix comment ops gh url
  .github/workflows/comment-ops.yaml
Labels: size/M, release-note-none

#16733 [gha] fix comment ops p3
  .github/workflows/comment-ops.yaml
Labels: size/XS, release-note-none

#16631 [ws-man-bridge-api] Always set govern to true
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.js
  components/ws-manager-bridge/src/cluster-service-server.ts
  dev/gpctl/cmd/clusters-register.go
Labels: size/S, team: webapp, team: workspace, release-note-none

#16734 [gha] fix comment ops p4
  .github/workflows/comment-ops.yaml
Labels: size/XS, release-note-none

#16225 [gha] enable gha build by default
  .github/pull_request_template.md
  .github/workflows/build.yml
  .werft/build.ts
  .werft/jobs/build/job-config.ts
Labels: size/S, release-note-none

#16737 fix gha build-gitpod
  .github/workflows/build.yml
Labels: size/XS, release-note-none

#16736 [switch-to-payg] Fix cancellation call for TS2
  components/dashboard/src/SwitchToPAYG.tsx
Labels: size/S, team: webapp, release-note-none

#16746 [dashboard] cache usage queries
  components/dashboard/src/Pagination/Pagination.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/data/usage/usage-query.ts
Labels: size/L, team: webapp, release-note-none

#16729 [installer] Do not pull blobserve implementation into installer
  components/blobserve/cmd/run.go
  components/blobserve/pkg/blobserve/blobserve.go
  components/blobserve/pkg/blobserve/blobspace_test.go
  components/blobserve/pkg/blobserve/refstore.go
  components/blobserve/pkg/config/blobserve.go
  components/blobserve/pkg/config/config.go
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/L, team: IDE, release-note-none

#16690 [redis] Add prometheus exporter
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/redis/constants.go
  install/installer/pkg/components/redis/deployment.go
Labels: size/M, team: webapp, release-note-none

#16668 [installer] Add OpenTelemetry env variables to tracing
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/common.go
Labels: size/S, team: webapp, release-note-none

#16731 [server] Sing-in as admin based on admin credentials file
  components/server/src/config.ts
  components/server/src/user/user-controller.ts
Labels: size/L, team: webapp, release-note-none

#16751 Limit Team Members privileges
  components/dashboard/src/teams/Members.tsx
Labels: size/XS, team: webapp, team: IDE, release-note-none

#16756 [dashboard] remaining owner cannot leave org
  components/dashboard/src/teams/Members.tsx
Labels: size/S, team: webapp, release-note-none

#16758 [gha] don't build preview on main
  .github/workflows/build.yml
Labels: size/XS, release-note-none

#16738 [registry-facade] Fallback to other blob sources if blob cannot be provided
  components/registry-facade/pkg/registry/blob.go
Labels: size/L, team: workspace, release-note

#16747 [tests] continue running workspace integ tests on werft for the short term
  .werft/workspace-run-integration-tests.sh
Labels: size/XS, team: workspace, release-note-none

#16720 [rebuild] fix open with VS Code Desktop actions
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note-none

#16742 [dashboard] make new workspace aware of project
  components/dashboard/src/data/workspaces/resolve-context-query.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp, release-note-none

#16760 [server] Mount admin-credentials
  components/server/src/config.ts
  components/server/src/user/user-controller.ts
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/kind-webapp/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/server/types.go
Labels: size/M, team: webapp, release-note-none

#16417 Show loading spinner when loading team members
  components/dashboard/src/teams/Members.tsx
Labels: community-contribution, size/XS, release-note, cla: accepted :heavy_check_mark:

#16774 Allow TLS v1.2
  components/supervisor/pkg/serverapi/publicapi.go
Labels: size/XS, team: IDE, release-note-none

#16777 Update switch to PAYG action button label
  components/dashboard/src/SwitchToPAYG.tsx
Labels: size/XS, team: webapp, release-note-none

#16765 [dashboard] fix missing billing entry
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
Labels: size/S, team: webapp, release-note-none

#16702 [ws-manager-mk2] Maintenance mode
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/pkg/maintenance/maintenance.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/constants.go
Labels: size/L, release-note-none

#16785 [gha] fix concurrency groups and preview name for multiple events
  .github/workflows/build.yml
Labels: size/S, release-note-none, team: security-infrastructure-and-delivery

#16788 [server] further limit sendHeartbeat
  components/server/src/auth/rate-limiter.ts
Labels: size/XS, team: webapp, release-note-none

#16784 [dashboard] keep start button disabled
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: webapp, release-note-none

#16780 [Switch to PAYG] Switch Org context for TS2 links
  components/server/ee/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#16706 [db] Setup go db tracing
  components/gitpod-db/go/conn.go
  components/gitpod-db/go/go.mod
  components/gitpod-db/go/go.sum
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/usage/go.mod
  components/usage/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/M, team: webapp, team: IDE, release-note-none

#16789 [dashboard] closeable limit-reached-modal
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: webapp, release-note-none

#16790 [dashboard] reloading browser reloads the orgs
  components/dashboard/src/App.tsx
  components/dashboard/src/data/organizations/orgs-query.ts
  components/dashboard/src/data/setup.tsx
Labels: size/S, team: webapp, release-note-none

#16779 Update Switch to PAYG success subtitle
  components/dashboard/src/SwitchToPAYG.tsx
Labels: size/S, team: webapp, release-note-none

#16795 [ws-man-bridge] Correct name for Workspace Instance Controller var
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/M, team: webapp, release-note-none

#16798 [gha] fix build + docker build
  .github/pull_request_template.md
  .github/workflows/build.yml
Labels: size/S, release-note-none, team: security-infrastructure-and-delivery

#16796 [server] allow members to leave
  components/dashboard/src/App.tsx
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp, release-note-none

#16802 [gha] mount /var/tmp to 'host'
  .github/workflows/build.yml
Labels: size/XS, release-note-none, team: security-infrastructure-and-delivery

#16636 Update search input style on project pages
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/M, team: webapp, release-note

#16799 Upgrade web extension
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE, release-note

#16715 [gpctl] Add users block command
  dev/gpctl/BUILD.yaml
  dev/gpctl/cmd/users-block.go
  dev/gpctl/cmd/users.go
  dev/gpctl/go.mod
  dev/gpctl/go.sum
Labels: size/L, team: workspace, release-note

#16745 Add custom supervisor metrics
  components/supervisor/pkg/metrics/reporter.go
  components/supervisor/pkg/serverapi/metrics.go
  components/supervisor/pkg/serverapi/publicapi.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/L, team: IDE, release-note-none

#16797 [dev-image] Set DB_HOST to 127.0.0.1 by default
  components/gitpod-db/BUILD.yaml
  dev/image/Dockerfile
Labels: size/XS, team: webapp, release-note-none

#16816 [github prebuilds] Fix trigger for default branch
  components/server/ee/src/prebuilds/github-enterprise-app.ts
  components/server/src/github/github-context-parser.spec.ts
  components/server/src/github/github-context-parser.ts
Labels: size/M, team: webapp, release-note

#16769 [migrations] Make workspace cluster name the PK, drop composite PK on (name, appCluster)
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/migration/1678365331415-WorkspaceClustersNamePK.ts
  components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
Labels: size/L, team: webapp, release-note-none

#16820 Remove slowDatabase references
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/actions/deploy-gitpod/metadata.yml
  .github/workflows/build.yml
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/config/v1/config.md
Labels: size/S, release-note-none, team: security-infrastructure-and-delivery

#16819 [dashboard] Use proxy endpoint to fetch feature flags
  components/dashboard/src/experiments/client.ts
Labels: size/M, team: webapp, release-note-none

#16413 [ws-manager-mk2] Support public SSH keys
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/service/manager.go
  components/ws-proxy/cmd/run.go
  components/ws-proxy/pkg/proxy/infoprovider.go
Labels: size/M, team: workspace, release-note-none, feature: ws-manager-mk2

#16825 Remove workspace_classes_backend feature flag
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/cluster-sync-service.ts
Labels: size/M, team: webapp, release-note-none

#16826 [dashboard] give start workspace button focus
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/start/start-workspace-options.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: webapp, release-note-none

#16830 [gha] don't skip gitpod build
  .github/workflows/build.yml
Labels: size/XS, release-note-none, team: security-infrastructure-and-delivery

#16832 [node-labeler] Do not return an error if the node does not exist
  components/node-labeler/cmd/run.go
Labels: size/S, team: workspace, release-note-none

#16833 [node-labeler] Skip checks if label already present
  components/node-labeler/cmd/run.go
Labels: size/S, team: workspace, release-note-none

#16807 [billing] place a hold on cards before subscribing
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
Labels: size/M, team: webapp, release-note-none

#16761 [server] Remove admin OTS create/use flow
  components/server/src/config.ts
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/user/user-controller.ts
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
Labels: size/L, team: webapp, release-note-none

#16824 Remove usage of applicationCluster column from WorkspaceCluster
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
  components/gitpod-protocol/src/workspace-cluster.ts
  components/image-builder-api/typescript/src/sugar.ts
  components/server/ee/src/workspace/gitpod-server-impl.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/typescript/src/client-provider-source.ts
  components/ws-manager-api/typescript/src/client-provider.spec.ts
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-bridge/src/bridge-controller.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/cluster-sync-service.ts
Labels: size/XL, team: webapp, team: workspace, release-note-none

#16822 [Switch to PAYG] Deduplicate calls to server.subscribeToStripe
  components/dashboard/src/SwitchToPAYG.tsx
  components/dashboard/src/hooks/use-local-storage.ts
Labels: size/L, team: webapp, release-note-none

#16835 Update `marketplace.json`
  components/ide-proxy/static/code/marketplace.json
Labels: editor: code (browser), size/S, team: IDE, release-note-none

#16834 [changelog] updated changelog
  CHANGELOG.md
Labels: approved, size/XS, release-note-none, lgtm

#16848 [public-api] List teams concurrently
  components/public-api-server/pkg/apiv1/team.go
Labels: size/M, team: webapp, release-note-none

#16842 [preview] fix wait, diff-apply, regression-check slack
  .github/workflows/build.yml
  .github/workflows/preview-env-check-regressions.yml
  dev/preview/workflow/lib/k8s-util.sh
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, release-note-none, team: security-infrastructure-and-delivery

#16844 [server] Tone down unnecessary logging around websocket verifyClient
  components/server/src/express-util.ts
  components/server/src/server.ts
Labels: size/XS, team: webapp, release-note-none

#16839 [db] Drop applicationCluster column from d_b_workspace_cluster
  components/gitpod-db/src/typeorm/migration/1678796232269-DropApplicationClusterFromWorkspaceClusters.ts
Labels: size/S, team: webapp, release-note-none

#16840 [ws-man-bridge] Remove application_cluster
  components/ws-manager-bridge-api/cluster-service.proto
  components/ws-manager-bridge-api/go/cluster-service.pb.go
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
  components/ws-manager-bridge-api/typescript/src/cluster-service_pb.js
  components/ws-manager-bridge/src/cluster-service-server.ts
  dev/gpctl/cmd/clusters-list.go
Labels: size/XS, team: webapp, team: workspace, release-note-none

#16854 Revert "Remove workspace_classes_backend feature flag (#16825)"
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/cluster-sync-service.ts
Labels: size/M, team: webapp, release-note-none

#16837 [node-labeler] Add debug.sh script
  components/node-labeler/debug.sh
Labels: size/XS, team: workspace, release-note-none

#16855 [ws-manager] Log timeout
  components/ws-manager/pkg/manager/monitor.go
Labels: size/XS, team: workspace, release-note-none

#16806 [ws-manager-mk2] Protect tokens
  .werft/jobs/build/installer/post-process.sh
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/service/manager.go
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-workspace/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/common/common.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/components/ws-daemon/objects.go
  install/installer/pkg/components/ws-daemon/role.go
  install/installer/pkg/components/ws-daemon/rolebinding.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/namespace.go
  install/installer/pkg/components/ws-manager-mk2/objects.go
  install/installer/pkg/components/ws-manager-mk2/role.go
  install/installer/pkg/components/ws-manager-mk2/rolebinding.go
Labels: size/XXL, team: workspace, release-note-none, feature: ws-manager-mk2

#16850 Org Settings Page Header updates & cleanup
  components/dashboard/src/components/Alert.tsx
  components/dashboard/src/components/EmptyMessage.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/teams/GitIntegrationsPage.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/TeamBilling.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
Labels: size/L, team: webapp, release-note-none

#16871 Allow vscode desktop error report
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/XS, team: IDE, release-note-none

#16874 [org] Disallow logins with organizational Git Auth
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/authenticator.ts
Labels: size/S, team: webapp, release-note-none

#16876 Remove applicationCluster from tables.ts
  components/gitpod-db/src/tables.ts
Labels: size/XS, team: webapp, release-note-none

#16870 Update VS Code Browser to `1.76.2`
  WORKSPACE.yaml
  install/installer/cmd/testdata/render/agent-smith/output.golden
  install/installer/cmd/testdata/render/aws-setup/output.golden
  install/installer/cmd/testdata/render/custom-pull-repository/output.golden
  install/installer/cmd/testdata/render/customization/output.golden
  install/installer/cmd/testdata/render/external-registry/output.golden
  install/installer/cmd/testdata/render/gcp-setup/output.golden
  install/installer/cmd/testdata/render/http-proxy/output.golden
  install/installer/cmd/testdata/render/ide-config/output.golden
  install/installer/cmd/testdata/render/kind-ide/output.golden
  install/installer/cmd/testdata/render/kind-meta/output.golden
  install/installer/cmd/testdata/render/message-bus-password/output.golden
  install/installer/cmd/testdata/render/minimal/output.golden
  install/installer/cmd/testdata/render/overrides-inline/output.golden
  install/installer/cmd/testdata/render/pod-config/output.golden
  install/installer/cmd/testdata/render/shortname/output.golden
  install/installer/cmd/testdata/render/statefulset-customization/output.golden
  install/installer/cmd/testdata/render/telemetry/output.golden
  install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
  install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
  install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE, release-note-none

#16881 [server] Fix file provider accept header
  components/server/src/github/file-provider.ts
Labels: size/XS, team: webapp, release-note-none

#16868 Org SSO Page updates
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/data/oidc-clients/delete-oidc-client-mutation.ts
  components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
  components/dashboard/src/data/oidc-clients/upsert-oidc-client-mutation.ts
  components/dashboard/src/teams/GitIntegrationsPage.tsx
  components/dashboard/src/teams/SSO.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/apiv1/oidc_test.go
Labels: size/XXL, team: webapp, release-note-none

#16853 [observability] add superviosr dashboard
  operations/observability/mixins/IDE/dashboards/components/supervisor.json
Labels: size/XXL, team: IDE, release-note-none

#16886 [preview] pass context to rollout status
  .github/workflows/preview-env-check-regressions.yml
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, team: IDE, release-note-none, team: security-infrastructure-and-delivery

#16898 [gha] fix ide integration tests
  .github/workflows/ide-integration-tests.yml
Labels: size/M, team: IDE, release-note-none

#16859 Remove cgroups v1 from commons-go
  components/common-go/cgroups/v1/cpu.go
  components/common-go/cgroups/v1/memory.go
  components/ws-daemon/pkg/iws/iws.go
Labels: size/L, team: workspace, release-note-none, team: staff-engineers

#16899 [common-go] Support rate limiting by enum key
  components/common-go/grpc/ratelimit.go
  components/common-go/grpc/ratelimit_test.go
Labels: size/S, release-note-none, team: staff-engineers
