Repository gitpod-io/gitpod, pull requests merged in 2023-08, with the labels that each got.

#18377 [server] Remove obsolete (Theia) User Storage Resource
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/typeorm/entity/db-user-storage-resource.ts
  components/gitpod-db/src/typeorm/user-storage-resources-db-impl.ts
  components/gitpod-db/src/user-storage-resources-db.ts
  components/gitpod-db/src/user-storage-resources-spec.db.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/code-sync/code-sync-service.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: team-experience

#18396 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18400 [server] don't error on project not_found
  components/gitpod-protocol/src/messaging/error.ts
  components/server/src/workspace/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience

#18399 [server] try to fix org membership on login
  components/server/src/iam/iam-session-app.ts
  components/server/src/orgs/organization-service.ts
Labels: size/M, team: team-experience

#18402 Filter by `organizationId` in `ListWorkspaces`
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/S, component: public-api, team: team-experience

#18397 Support custom CA in trust-manager
  install/installer/pkg/components/cluster/certmanager.go
Labels: size/M

#18404 [supervisor] commit java typings
  components/supervisor-api/java/.gitignore
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Control.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/ControlServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Info.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/InfoServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Notification.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/NotificationServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Port.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/PortServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Status.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/StatusServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TerminalOuterClass.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TerminalServiceGrpc.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Token.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TokenServiceGrpc.java
Labels: size/XXL

#18390 [server] enhanced mocha setups
  .gitpod.yml
  components/gitpod-db/src/config.ts
  components/server/.vscode/launch.json
  components/server/.vscode/settings.json
  components/server/BUILD.yaml
  components/server/mocha.opts
  components/server/package.json
Labels: size/M, team: team-experience

#18401 [ws-daemon] Fix workspace location for log backup
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  test/pkg/integration/apis.go
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/M, team: team-experience, team: team-engine

#18405 [supervisor] add http binding for create private ssh keys
  components/supervisor-api/control.proto
  components/supervisor-api/go/control.pb.go
  components/supervisor-api/go/control.pb.gw.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Control.java
Labels: size/L, team: team-experience

#18321 Fix listeners leaks – EXP-206
  components/gitpod-db/package.json
  components/gitpod-protocol/package.json
  components/server/package.json
  components/server/src/monitoring-endpoints.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/ws-manager-bridge/package.json
  yarn.lock
Labels: size/M, team: team-experience

#18407 [test] Improve e2e test slack message
  .github/actions/integration-tests/action.yml
  .github/workflows/workspace-integration-tests.yml
Labels: size/XS, team: team-engine

#18409 [obs] delay triggering GitpodWorkspaceTooManyRegularNotActiveMk2
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine

#18413 [server] fix tsc complaining about complex type
  components/server/src/prebuilds/github-app.ts
Labels: size/XS, team: team-experience

#18411 [supervisor] expose control service over REST
  components/supervisor-api/control.proto
  components/supervisor-api/go/control.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Control.java
  components/supervisor/pkg/supervisor/services.go
Labels: size/XXL, team: team-experience

#18342 adding getTeams scope for desktop oauth client
  components/server/src/oauth-server/db.ts
Labels: size/XS, team: team-experience

#18417 [server] make first user owner
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/BUILD.yaml
  components/server/package.json
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/user-controller.ts
  components/server/src/user/user-service.ts
Labels: size/XL, team: team-experience

#18426 [supervisor-api] don't generate java typings separately
  .gitpod.yml
  components/supervisor-api/BUILD.yaml
  components/supervisor-api/generate.sh
  components/supervisor-api/java/BUILD.yaml
Labels: size/S

#18422 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18394 [server] run relationship updater on findUserById
  components/server/src/authorization/authorizer.spec.db.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
Labels: size/XXL, team: team-experience

#18428 Se/featureflag-spicedb
  components/server/src/authorization/authorizer.spec.db.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/projects/projects-service.ts
Labels: size/M, team: team-experience

#18433 Update VS Code Browser to `1.81.0`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18437 [server] handle uncaught exception from grpc-js
  components/server/src/init.ts
  components/ws-manager-bridge/src/main.ts
Labels: size/M, team: team-experience

#18436 [dev] Blowtorch: minor fix for current kubernetes version
  dev/blowtorch/pkg/dart/injector.go
Labels: size/XS

#18403 [fga] Workspace: create, get, stop and delete
  components/gitpod-db/src/traced-db.ts
  components/gitpod-protocol/src/messaging/client-call-metrics.ts
  components/gitpod-protocol/src/util/tracing.ts
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/container-module.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/test/expect-utils.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
  components/server/src/workspace/workspace-deletion-service.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/spicedb/codegen/codegen.go
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience

#18415 [JB GW]: Support ssh over websocket tunnel
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodSettingsConfigurable.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodSettingsState.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWebSocketTunnelServer.kt
Labels: size/XL, team: team-experience

#18434 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18429 [server] Cleanup around EntitlementService and BillingMode
  components/dashboard/src/service/service-mock.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, do-not-merge/hold, team: team-experience

#18410 [server] Merge WorkspaceDeletionService into WorkspaceGC
  components/dashboard/src/service/service-mock.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/container-module.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/test/expect-utils.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-deletion-service.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#18431 [GHA] Fix code nightly action broken
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience

#18441 Update caddy to v2.7.2
  components/proxy/plugins/analytics/go.mod
  components/proxy/plugins/analytics/go.sum
  components/proxy/plugins/configcat/go.mod
  components/proxy/plugins/configcat/go.sum
  components/proxy/plugins/corsorigin/go.mod
  components/proxy/plugins/corsorigin/go.sum
  components/proxy/plugins/frontend_dev/go.mod
  components/proxy/plugins/frontend_dev/go.sum
  components/proxy/plugins/headlesslogdownload/go.mod
  components/proxy/plugins/headlesslogdownload/go.sum
  components/proxy/plugins/jsonselect/go.mod
  components/proxy/plugins/jsonselect/go.sum
  components/proxy/plugins/logif/go.mod
  components/proxy/plugins/logif/go.sum
  components/proxy/plugins/secwebsocketkey/go.mod
  components/proxy/plugins/secwebsocketkey/go.sum
  components/proxy/plugins/sshtunnel/go.mod
  components/proxy/plugins/sshtunnel/go.sum
  components/proxy/plugins/workspacedownload/go.mod
  components/proxy/plugins/workspacedownload/go.sum
  components/ws-proxy/go.sum
Labels: size/XXL, team: team-experience, team: team-engine

#18445 [server] FIx missing User.fullName attribute for SSO users – EXP-365
  components/server/src/iam/iam-oidc-create-session-payload.ts
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/S, team: team-experience

#18447 [dashboard] update website slugs
  components/dashboard/src/utils.ts
Labels: size/XS, team: team-experience

#18414 fix watch mode
  components/content-service-api/typescript/package.json
  components/image-builder-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
Labels: size/XS, team: team-engine

#18446 [dashboard] don't falsely show image build info
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/XS, team: team-experience

#18444 [fga] allow toggling centralizedPermissions on/off
  .github/workflows/build.yml
  components/dashboard/src/data/featureflag-query.ts
  components/server/package.json
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/test/service-testing-container-module.ts
Labels: size/L, team: team-experience

#18449 [usage] add optional UserID to filter usage
  components/gitpod-db/go/usage.go
  components/gitpod-db/go/usage_test.go
  components/gitpod-protocol/src/usage.ts
  components/server/src/orgs/usage-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
Labels: size/L, team: team-experience

#18353 Update OpenSSH to v9.3p2
  components/supervisor/openssh/leeway.Dockerfile
Labels: size/XS, team: team-experience

#18451 [server] fix Suggested Context URLs for BBS – EXP-354
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience

#18456 [server] sequentially gc workspaces
  components/server/src/jobs/workspace-gc.ts
Labels: size/L, team: team-experience

#18457 [mysql] increase and monitor poolsize
  components/gitpod-db/src/typeorm/typeorm.ts
  components/server/src/init.ts
  components/server/src/prometheus-metrics.ts
Labels: size/M, team: team-experience

#18452 Adding project scopes for desktop oauth client
  components/server/src/oauth-server/db.ts
Labels: size/XS, team: team-experience

#18450 Add a new trust bundle for custom SSL certificates
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/create.go
  install/installer/pkg/components/cluster/certmanager.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
Labels: size/L, team: team-engine

#18463 [server] fix org-owned users without membership
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/S, team: team-experience

#18461 [fga] migrated user service methods
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience

#18469 Remove unnecessary source array from trust manager objects
  install/installer/pkg/components/cluster/certmanager.go
Labels: size/XS

#18460 [workspace-cluster] bump docker and docker compose deps
  WORKSPACE.yaml
Labels: size/XS, team: team-engine

#18459 fga: migrate workspaces
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
Labels: size/L, team: team-experience

#18462 [gha] fix JetBrains integration test
  .github/actions/integration-tests/action.yml
Labels: size/XS

#18472 [obs] GitpodImageBuildDurationAnomaly fires too often for Dedicated
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
Labels: size/XS, team: team-engine

#18471 [tests] reduce flakiness associated with DB connections
  test/pkg/integration/apis.go
Labels: size/S, team: team-experience, team: team-engine

#18474 Make Git env vars independent of custom certs
  components/ws-manager-mk2/controllers/create.go
  components/ws-manager-mk2/controllers/create_test.go
Labels: size/M, team: team-engine

#18418 [gated-release] trigger staging/prod install
  .github/workflows/build.yml
Labels: size/S, team: team-engine

#18477 [server] added metric for db pool queueing
  components/server/src/init.ts
  components/server/src/prometheus-metrics.ts
Labels: size/S, team: team-experience

#18478 fix install app release name
  .github/workflows/build.yml
Labels: size/XS

#18468 Improve GithubRepositoryProvider.getUserRepos – EXP-407
  components/server/src/github/github-repository-provider.spec.ts
  components/server/src/github/github-repository-provider.ts
Labels: size/M, team: team-experience

#18481 [server] added metric for db pool queueing (#18477)
  components/server/src/init.ts
  components/server/src/prometheus-metrics.ts
Labels: size/S, team: team-experience

#18438 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#18455 Make db waiter to wait latest migration
  components/gitpod-db/BUILD.yaml
  components/gitpod-db/scripts/generate-latest-migration.sh
  components/service-waiter/BUILD.yaml
  components/service-waiter/cmd/database.go
  components/service-waiter/cmd/database_test.go
  components/service-waiter/cmd/resources/latest-migration.txt
  install/installer/pkg/common/common.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/L, team: team-experience

#18480 Improve organization members filter
  components/dashboard/src/teams/Members.tsx
Labels: size/S, team: team-experience

#18484 [server] fix typeorm metrics
  components/server/src/init.ts
Labels: size/M, team: team-experience

#18475 [ws-manager-mk2] test create w/o git config
  components/ws-manager-mk2/controllers/create_test.go
Labels: size/S, team: team-engine

#18487 Improve SSO log in button UX
  components/dashboard/src/login/SSOLoginForm.tsx
Labels: size/XS, team: team-experience

#18479 [fga] Introduce sshkeyservice
  components/server/src/authorization/definitions.ts
  components/server/src/container-module.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/sshkey-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience

#18486 [ws-daemon] additional logging for markunmount
  components/ws-daemon/pkg/daemon/markunmount.go
Labels: size/XS, team: team-engine

#18489 [preview] update VM image for gen103
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: team-engine

#18496 [obs] reduce false positives for GitpodImageBuildDurationAnomaly
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
Labels: size/S, team: team-engine

#18485 Update VS Code Browser to `1.81.1`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: team-experience

#18495 Update runc to v1.1.9
  components/docker-up/dependencies.sh
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/leeway.Dockerfile
  components/ws-manager-mk2/go.mod
  install/installer/go.mod
  install/installer/go.sum
Labels: size/S, team: team-engine

#18499 [preview] update VM image to account for kernel update
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: team-engine

#18419 Enable leader election in ws-manager-mk2
  components/ws-manager-mk2/cmd/sample-workspace/main.go
  components/ws-manager-mk2/config/manager/manager.yaml
  components/ws-manager-mk2/main.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
Labels: size/S, team: team-engine

#18506 Add ECR authentication support to image-builder
  components/image-builder-api/go/config/config.go
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/auth/auth_test.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/image-builder-mk3/pkg/resolve/resolve.go
  components/scrubber/scrubber.go
  components/scrubber/scrubber_test.go
  install/installer/pkg/components/image-builder-mk3/configmap.go
  install/installer/pkg/config/v1/config.go
Labels: size/L, team: team-engine

#18508 Revert "Enable leader election in ws-manager-mk2"
  components/ws-manager-mk2/cmd/sample-workspace/main.go
  components/ws-manager-mk2/config/manager/manager.yaml
  components/ws-manager-mk2/main.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
Labels: size/S, team: team-engine

#18500 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18498 [bbs] add pagination to getRepos – EXP-417 EXP-416
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
Labels: size/M, team: team-experience

#18473 [ws-daemon] error log clean-up
  components/common-go/watch/file.go
  components/ws-daemon/pkg/netlimit/netlimit.go
Labels: size/XS, team: staff-engineers, team: team-engine

#18507 [obs] demote GitpodImageBuildDurationAnomaly to a warning
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
Labels: size/XS, team: team-engine

#18509 [server] delete unused guard
  components/server/src/auth/resource-access.spec.ts
  components/server/src/auth/resource-access.ts
Labels: size/L, team: team-experience

#18510 Add baseref as additional image build auth
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Labels: size/S, team: team-engine

#18513 [ws-manager-mk2] remove experimental mode feature
  components/ws-manager-api/go/config/config.go
  components/ws-manager-mk2/controllers/create.go
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/scripts/bootstrap-k3s.sh
  dev/preview/infrastructure/variables.tf
  gitpod-ws.code-workspace
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: team-engine

#18467 [fga] extract WorkspaceService.start
  components/server/package.json
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/user.spec.ts
  components/server/src/api/user.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/user-authentication.ts
  components/server/src/user/user-controller.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience

#18514 [papi]: Add `GetSuggestedRepoURLs`
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/public-api-server/pkg/apiv1/scm.go
  components/public-api-server/pkg/apiv1/scm_test.go
  components/public-api-server/pkg/server/server.go
  components/public-api/gitpod/experimental/v1/scm.proto
  components/public-api/go/experimental/v1/scm.pb.go
  components/public-api/go/experimental/v1/scm_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/scm.connect.go
  components/public-api/go/experimental/v1/v1connect/scm.proxy.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/scm_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/scm_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_pb.ts
Labels: size/XL, component: public-api, team: team-experience

#18517 [fga] more FGA checks and service use
  components/server/src/authorization/definitions.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience

#18502 [fga] Introduce GitpodTokenService
  components/server/src/authorization/definitions.ts
  components/server/src/container-module.ts
  components/server/src/user/gitpod-token-service.spec.db.ts
  components/server/src/user/gitpod-token-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/XL, team: team-experience

#18519 [fga] Skip old permission system if `centralizedPermissions` is enabled
  components/server/src/auth/resource-access.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/user/user-controller.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
Labels: size/L, team: team-experience

#18503 [fga] Introduce EnvVarService
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/authorization/definitions.ts
  components/server/src/container-module.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/env-var-service.spec.ts
  components/server/src/workspace/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience

#18527 [fga] WorkspaceService port ops
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#18511 Enable leader election in ws-manager-mk2
  components/ws-manager-mk2/cmd/sample-workspace/main.go
  components/ws-manager-mk2/config/manager/manager.yaml
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  test/go.mod
  test/go.sum
  test/pkg/integration/setup.go
  test/run.sh
  test/tests/components/ws-manager/maintenence_test.go
Labels: size/XL, team: team-experience, team: team-engine

#18537 Revert "Enable leader election in ws-manager-mk2"
  components/ws-manager-mk2/cmd/sample-workspace/main.go
  components/ws-manager-mk2/config/manager/manager.yaml
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/service/manager.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  test/go.mod
  test/go.sum
  test/pkg/integration/setup.go
  test/run.sh
  test/tests/components/ws-manager/maintenence_test.go
Labels: size/XL, team: team-experience, team: team-engine

#18533 [server] add `searchString` to `getRepositoriesForAutomatedPrebuilds` – EXP-461
  components/dashboard/src/projects/NewProject.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: team-experience

#18534 Brad/exp 458 fe allow pasting in a git clone url to create project as
  components/dashboard/src/data/git-providers/github-queries.ts
  components/dashboard/src/data/git-providers/provider-repositories-query.ts
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/new-project/NewProjectAccountSelector.tsx
  components/dashboard/src/projects/new-project/NewProjectAuthRequired.tsx
  components/dashboard/src/projects/new-project/NewProjectCreateFromURL.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoList.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoSelection.tsx
  components/dashboard/src/projects/new-project/NewProjectSearchInput.tsx
  components/dashboard/src/projects/new-project/NewProjectSubheading.tsx
  components/dashboard/src/projects/new-project/reconfigure-github.ts
Labels: size/XXL, team: team-experience

#18543 [code] Fix gp-code build
  components/ide/code/leeway.Dockerfile
Labels: size/S, team: team-experience

#18544 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18538 [WIP][fga] WorkspaceService: watchWorkspaceImageBuildLogsm getHeadlessLog, WorkspaceService.sendHeartBeat
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/headless-log-service.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#18530 [papi] List editor options
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/public-api-server/pkg/apiv1/editor_service.go
  components/public-api-server/pkg/apiv1/editor_service_test.go
  components/public-api-server/pkg/server/server.go
  components/public-api/gitpod/experimental/v1/editor_service.proto
  components/public-api/go/experimental/v1/editor_service.pb.go
  components/public-api/go/experimental/v1/editor_service_grpc.pb.go
  components/public-api/go/experimental/v1/v1connect/editor_service.connect.go
  components/public-api/go/experimental/v1/v1connect/editor_service.proxy.connect.go
  components/public-api/typescript/src/gitpod/experimental/v1/editor_service_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/editor_service_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/scm_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/scm_pb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/user_pb.ts
Labels: size/XL, component: public-api, team: team-experience

#18540 [fga] project visibility and prebuild perms
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/debug.sh
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/spicedb/codegen/codegen.go
  components/spicedb/schema/schema.yaml
Labels: size/L

#18536 Remove FUSE support
  components/gitpod-protocol/src/wsready.ts
  components/image-builder-api/go/imgbuilder.pb.go
  components/image-builder-api/go/imgbuilder_grpc.pb.go
  components/image-builder-api/go/mock/mock.go
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.js
  components/image-builder-api/typescript/src/imgbuilder_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_pb.js
  components/local-app-api/go/localapp_grpc.pb.go
  components/registry-facade-api/go/imagespec.pb.go
  components/registry-facade-api/go/provider.pb.go
  components/registry-facade-api/go/provider_grpc.pb.go
  components/workspacekit/BUILD.yaml
  components/workspacekit/cmd/rings.go
  components/workspacekit/leeway.Dockerfile
  components/ws-daemon-api/go/workspace_daemon.pb.go
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.js
  components/ws-daemon-api/workspace_daemon.proto
  components/ws-daemon/nsinsider/main.go
  components/ws-daemon/pkg/content/config_test.go
  components/ws-daemon/pkg/iws/iws.go
  install/installer/docs/overview.md
  install/installer/example-config.yaml
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/load.go
  install/installer/pkg/config/v1/validation.go
Labels: size/L, team: team-experience, team: team-engine

#18549 [fga] WorkspaceService.controlAdmission
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/spicedb/schema/schema.yaml
Labels: size/XL, team: team-experience

#18558 [integrationtests] create org
  test/pkg/integration/workspace.go
Labels: size/XS, team: team-experience, team: team-engine

#18555 🐛 Fix: Broken logic in Org. member loading state
  components/dashboard/src/teams/Members.tsx
Labels: size/S, team: team-experience

#18561 [spicedb] rolling update when schema changes
  components/server/src/authorization/spicedb-authorizer.ts
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/spicedb/schema.go
Labels: size/M, team: team-experience

#18560 [fga] prebuild access
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/M, team: team-experience

#18562 [fga] check some admin functions
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/user-authentication.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/codegen/codegen.go
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience

#18319 Update primary button style
  components/dashboard/src/Login.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/EmptyMessage.tsx
  components/dashboard/src/components/SelectableCardSolid.tsx
  components/dashboard/src/index.css
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/tailwind.config.js
Labels: size/M, team: team-experience

#18572 [bbs] fix incorrect revision fetch EXP-496
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
Labels: size/L, team: team-experience

#18552 Update to webpack 5 in supervisor frontend
  components/supervisor/frontend/package.json
  components/supervisor/frontend/tsconfig.json
  components/supervisor/frontend/webpack.config.js
  yarn.lock
Labels: size/XXL, team: team-experience

#18575 [bbs] check webhooks permission in scm itself
  components/server/src/prebuilds/bitbucket-server-service.ts
Labels: size/S, team: team-experience

#18521 [preview] use k3s 1.26
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS

#18574 [fga] Devx improvements
  components/BUILD.yaml
  components/gitpod-protocol/src/experiments/configcat-server.ts
  components/gitpod-protocol/src/experiments/configcat.ts
  components/server/src/auth/verification-service.ts
  components/server/src/container-module.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience

#18563 Support pagination to fetch _all_ Bitbucket branches
  components/server/src/bitbucket/bitbucket-repository-provider.ts
Labels: git provider: bitbucket, size/M, team: team-experience

#18559 [fga] added create_snapshot permission
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/M, team: team-experience

#18515 Add CreateAndStartWorkspace to public-api
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
  components/server/src/oauth-server/db.ts
Labels: size/M, team: team-experience

#18579 [image-builder-api] log more, traces aren't always available
  components/image-builder-api/typescript/src/sugar.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience, team: team-engine

#18584 removing calc links since it doesn't exist anymore
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
Labels: size/S, team: team-experience

#18578 🐛 fix: CLS bug on Git providers settings page
  components/dashboard/src/user-settings/AuthEntryItem.tsx
Labels: size/XS, team: team-experience

#18553 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18566 Incremental repo searching
  components/dashboard/package.json
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/git-providers/provider-repositories-query.ts
  components/dashboard/src/hooks/use-state-with-debounce.ts
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/new-project/NewProjectAccountSelector.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoSelection.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  yarn.lock
Labels: size/XL, team: team-experience

#18565 [fga] WorkspaceService.getWorkspace(s)
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience

#18569 [server] FGA checks for all admin*Workspace methods
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/spicedb/schema/schema.yaml
Labels: size/M, team: team-experience

#18588 [fga] only migrate non-deleted workspaces
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/redis/mutex.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#18581 Support managed redis
  components/gitpod-db/src/redis/client.ts
  components/server/src/container-module.ts
  components/ws-manager-bridge/src/container-module.ts
  install/installer/pkg/components/server/configmap.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/L, team: team-experience

#18546 [papi] List workspace classes
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/v1connect/workspaces.connect.go
  components/public-api/go/experimental/v1/v1connect/workspaces.proxy.connect.go
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/go/experimental/v1/workspaces_grpc.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_connectweb.ts
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
  components/server/src/api/workspaces.ts
Labels: size/L, component: public-api

#18589 Update Desktop scopes
  components/server/src/oauth-server/db.ts
Labels: size/XS, component: public-api, team: team-experience

#18525 update node to 18.17.1
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  components/dashboard/.eslintrc.js
  components/dashboard/craco.config.js
  components/dashboard/package.json
  components/dashboard/postcss.config.js
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/modal.css
  components/dashboard/src/components/org-icon/styles.css
  components/dashboard/src/dedicated-setup/styles.css
  components/dashboard/src/index.tsx
  components/dashboard/tailwind.config.js
  components/gitpod-db/leeway.Dockerfile
  components/gitpod-db/package.json
  components/gitpod-protocol/package.json
  components/ide-metrics-api/typescript-grpcweb/package.json
  components/local-app-api/typescript-grpcweb/package.json
  components/server/leeway.Dockerfile
  components/server/package.json
  components/supervisor/frontend/package.json
  components/ws-manager-bridge/leeway.Dockerfile
  components/ws-manager-bridge/package.json
  dev/image/Dockerfile
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-engine

#18592 [fga] minor fixes
  components/server/src/authorization/relationship-updater.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/M, team: team-experience

#18550 [server] terminate ws on shutdown
  components/server/src/express/ws-handler.ts
  components/server/src/init.ts
  components/server/src/server.ts
Labels: size/M, team: team-experience

#18570 [wip] SpiceDB reconnect behavior
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/authorization/spicedb.ts
  components/server/src/container-module.ts
  components/server/src/test/service-testing-container-module.ts
  install/installer/pkg/components/spicedb/deployment.go
  yarn.lock
Labels: size/L, team: team-experience

#18594 Enable reading of keyring
  components/ws-daemon/seccomp-profile-installer/main.go
Labels: size/S, team: team-engine

#18587 Update gitpod-web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#18585 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#18590 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18591 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18602 Add link to preview env logs
  dev/preview/previewctl/cmd/report.go
Labels: size/XS, team: team-engine

#18601 Improve gp idp login aws
  components/gitpod-cli/cmd/idp-login-aws.go
Labels: size/M, team: team-experience

#18547 Add support for pod disruption budget
  install/installer/pkg/common/common.go
  install/installer/pkg/common/pod_disruption_budget.go
  install/installer/pkg/components/blobserve/objects.go
  install/installer/pkg/components/blobserve/pdb.go
  install/installer/pkg/components/dashboard/objects.go
  install/installer/pkg/components/dashboard/pdb.go
  install/installer/pkg/components/node-labeler/objects.go
  install/installer/pkg/components/node-labeler/pdb.go
  install/installer/pkg/components/openvsx-proxy/objects.go
  install/installer/pkg/components/openvsx-proxy/pdb.go
  install/installer/pkg/components/proxy/objects.go
  install/installer/pkg/components/proxy/pdb.go
  install/installer/pkg/components/public-api-server/objects.go
  install/installer/pkg/components/public-api-server/pdb.go
  install/installer/pkg/components/server/objects.go
  install/installer/pkg/components/server/pdb.go
  install/installer/pkg/components/ws-manager-mk2/objects.go
  install/installer/pkg/components/ws-manager-mk2/pdb.go
  install/installer/pkg/components/ws-proxy/objects.go
  install/installer/pkg/components/ws-proxy/pdb.go
Labels: size/L, team: team-experience, team: team-engine

#18598 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#18539 Enable leader election in ws-manager-mk2 (v3)
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-mk2/cmd/sample-workspace/main.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/config/manager/manager.yaml
  components/ws-manager-mk2/controllers/maintenance_controller.go
  components/ws-manager-mk2/controllers/subscriber_controller.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/timeout_controller_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/pkg/activity/activity.go
  components/ws-manager-mk2/service/manager.go
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  test/go.mod
  test/go.sum
  test/pkg/integration/setup.go
  test/run.sh
  test/tests/components/ws-manager/maintenence_test.go
Labels: size/XXL, team: team-experience, team: team-engine

#18336 Hide the latest editor warning for stopping or stopped workspaces
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/S, team: team-experience

#18523 Update GitLab REST client library
  components/server/leeway.Dockerfile
  components/server/package.json
  components/server/src/gitlab/api.ts
  components/server/src/gitlab/file-provider.ts
  components/server/src/gitlab/gitlab-app-support.ts
  components/server/src/gitlab/gitlab-auth-provider.ts
  components/server/src/gitlab/gitlab-context-parser.spec.ts
  components/server/src/gitlab/gitlab-context-parser.ts
  components/server/src/gitlab/gitlab-file-provider.spec.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/ws-manager-bridge/leeway.Dockerfile
  package.json
  yarn.lock
Labels: size/XL, team: team-experience

#18609 Update page titles
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/teams/JoinTeam.tsx
Labels: size/XS, team: team-experience

#18583 [ws-proxy] Implement graceful shutdown
  components/ws-proxy/cmd/run.go
  components/ws-proxy/pkg/proxy/proxy.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/M, team: team-engine

#18616 Update kumquat colors
  components/dashboard/src/admin/BlockedEmailDomains.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/TeamsSearch.tsx
  components/dashboard/src/admin/UserSearch.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/ItemsList.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoList.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/TokenEntry.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceStatusIndicator.tsx
Labels: size/M, team: team-experience

#18618 [dashboard] unique project links
  components/dashboard/src/projects/project-context.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
Labels: size/M, team: team-experience

#18620 [image-builder-bob] Force refresh of oauth token
  components/image-builder-bob/pkg/proxy/proxy.go
Labels: size/S, team: team-engine

#18612 Improve git performance
  components/content-service/pkg/initializer/git.go
Labels: size/S, team: team-engine

#18617 [usage] fix endTime not align to draft stop condition
  components/usage/pkg/apiv1/usage.go
Labels: size/XS, team: team-experience

#18611 [image-builder-mk3] log errors for auth
  components/image-builder-mk3/pkg/auth/auth.go
Labels: size/M, team: team-engine

#18621 [image-builder-bob] retry on bad request
  components/image-builder-bob/pkg/proxy/proxy.go
Labels: size/XS, team: team-engine

#18627 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup
