Repository gitpod-io/gitpod, pull requests merged in 2023-11, with the labels that each got.

#18991 [jb] mark as stable in .gitpod.yml
  components/gitpod-protocol/data/gitpod-schema.json
Labels: size/XS, team: team-experience

#18997 [ops] change team from Workspace to Engine
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
  operations/observability/mixins/workspace/rules/central/ipfs.yaml
  operations/observability/mixins/workspace/rules/central/nodes.yaml
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
Labels: size/S, team: team-engine

#18998 [obs] remove noisy GitpodWorkspaceStuckOnStoppedMk2
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
Labels: size/S, team: team-engine

#18976 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18993 [supervisor] Remove default image fetch to improve IDE startup performance
  components/gitpod-cli/cmd/init.go
  components/gitpod-cli/cmd/validate.go
  components/supervisor-api/go/info.pb.go
  components/supervisor-api/info.proto
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Info.java
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/services.go
Labels: size/XL, team: team-experience

#18967 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18999 Update containerd and buildkit deps for gen 106
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/common-go/go-update-wc-deps.sh
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/L, team: staff-engineers, team: team-experience, team: team-engine

#19002 [obs] remove GitpodImagebuildStartSuccess warning
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
Labels: size/S, team: team-engine

#18992 Fix normalized case-sensitive search params
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
Labels: size/XS, team: team-experience

#19000 Gitpod VS Code Browser Release `1.84`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#18979 Podkit additions: Button, DropDown, Headings
  components/dashboard/package.json
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/components/podkit/buttons/LinkButton.tsx
  components/dashboard/src/components/podkit/buttons/LoadingButton.tsx
  components/dashboard/src/components/podkit/dropdown/DropDown.tsx
  components/dashboard/src/components/podkit/dropdown/DropDownActions.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/index.css
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: size/XXL, team: team-experience

#19005 Allow creation of events
  install/installer/pkg/components/workspace/objects.go
  install/installer/pkg/components/workspace/role.go
  install/installer/pkg/components/workspace/rolebinding.go
Labels: size/M, team: team-engine

#19009 [dashboard] add title to repo list
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: size/XS, team: team-experience

#18974 Detect Kotlin Gradle DSL & populate .gitpod.yml suggestions
  components/server/src/config/config-inferrer.spec.ts
  components/server/src/config/config-inferrer.ts
Labels: size/M, team: team-experience

#18972 Handle unknown routes to avoid stack traces leaks
  components/server/src/express-util.ts
Labels: aspect: security, size/S, team: team-experience

#19013 [dashboard] deduplicate repositories
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/L, team: team-experience

#19011 [a11y] Add dark mode support to `InputWithCopy` and `TextInputField` components
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
Labels: size/XS, aspect: accessibility, team: team-experience

#18984 Update kube-rbac-proxy to v0.15.0
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/common/constants.go
Labels: size/XS, team: team-engine

#19015 [dashboard] error message on ws-cluster update
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: team-experience

#18971 Local App v2 :)
  components/ide-proxy/Dockerfile
  components/local-app/BUILD.js
  components/local-app/BUILD.yaml
  components/local-app/README.md
  components/local-app/cmd/config-delete-context.go
  components/local-app/cmd/config-get-contexts.go
  components/local-app/cmd/config-set-context.go
  components/local-app/cmd/config-use-context.go
  components/local-app/cmd/config.go
  components/local-app/cmd/login.go
  components/local-app/cmd/organization-get.go
  components/local-app/cmd/organization-list.go
  components/local-app/cmd/organizations.go
  components/local-app/cmd/root.go
  components/local-app/cmd/root_test.go
  components/local-app/cmd/whoami.go
  components/local-app/cmd/workspace-create.go
  components/local-app/cmd/workspace-delete.go
  components/local-app/cmd/workspace-get.go
  components/local-app/cmd/workspace-list-classes.go
  components/local-app/cmd/workspace-list-editors.go
  components/local-app/cmd/workspace-list.go
  components/local-app/cmd/workspace-list_test.go
  components/local-app/cmd/workspace-open.go
  components/local-app/cmd/workspace-ssh.go
  components/local-app/cmd/workspace-start.go
  components/local-app/cmd/workspace-stop.go
  components/local-app/cmd/workspace-up.go
  components/local-app/cmd/workspace.go
  components/local-app/go.mod
  components/local-app/go.sum
  components/local-app/leeway.Dockerfile
  components/local-app/main/gitpod-cli/main.go
  components/local-app/main/gitpod-local-companion/main.go
  components/local-app/pkg/auth/auth.go
  components/local-app/pkg/auth/auth_test.go
  components/local-app/pkg/config/context.go
  components/local-app/pkg/constants/constants.go
  components/local-app/pkg/helper/workspace.go
  components/local-app/pkg/prettyprint/errors.go
  components/local-app/pkg/prettyprint/prettyprint.go
  components/local-app/pkg/prettyprint/prettyprint_test.go
  components/proxy/conf/Caddyfile
  components/public-api/go/client/client.go
  components/public-api/go/client/client_test.go
  components/server/src/oauth-server/db.ts
Labels: component: local app, size/XXL, team: team-experience

#18925 Improve Workspace timeout settings error UX
  components/dashboard/src/user-settings/Preferences.tsx
Labels: size/M, team: team-experience

#19016 Add "more elements" hint to repo search.
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/search-repositories-query.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
  components/server/src/repohost/repository-provider.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#19004 Update k3s to gen 106
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS

#19025 [installer] fix service-waiter bug
  install/installer/pkg/common/common.go
Labels: size/XS

#19026 Revert service-waiter (components) for dashboard
  install/installer/pkg/components/dashboard/deployment.go
Labels: size/XS, team: team-experience

#19024 Gitpod VS Code Browser Release `1.84.1`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19019 [LocalCLI] add completion for `--class` and `--editor` flags
  .gitpod.yml
  components/local-app/BUILD.yaml
  components/local-app/README.md
  components/local-app/cmd/root.go
  components/local-app/cmd/workspace-create.go
  components/local-app/cmd/workspace-up.go
Labels: size/M, team: team-experience

#19029 Print information after login
  components/local-app/cmd/login.go
  components/local-app/cmd/whoami.go
Labels: size/M, team: team-experience

#19030 Improve log level printing
  components/local-app/cmd/root.go
Labels: size/S, team: team-experience

#19035 Add GiB left in storage warning
  operations/observability/mixins/workspace/rules/central/ipfs.yaml
Labels: size/XS, team: team-engine

#19036 Use humanize1024 instead in storage warning
  operations/observability/mixins/workspace/rules/central/ipfs.yaml
Labels: size/XS, team: team-engine

#19031 local cli: better logging for `ws stop`
  components/local-app/cmd/workspace-stop.go
  components/local-app/pkg/helper/workspace.go
Labels: size/M, team: team-experience

#19010 [papi] add watchWorkspace API
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/generate-async-generator.spec.ts
  components/gitpod-protocol/src/generate-async-generator.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/package.json
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/workspace-service.ts
  package.json
  yarn.lock
Labels: size/XL, team: team-experience

#19033 Add (out-out) telemetry to CLI
  components/local-app/BUILD.js
  components/local-app/cmd/login.go
  components/local-app/cmd/login_test.go
  components/local-app/cmd/root.go
  components/local-app/cmd/root_test.go
  components/local-app/cmd/workspace-create.go
  components/local-app/cmd/workspace-list-classes.go
  components/local-app/cmd/workspace-list-editors.go
  components/local-app/cmd/workspace-list_test.go
  components/local-app/cmd/workspace-up.go
  components/local-app/go.mod
  components/local-app/go.sum
  components/local-app/pkg/auth/auth.go
  components/local-app/pkg/config/context.go
  components/local-app/pkg/helper/workspace.go
  components/local-app/pkg/prettyprint/errors.go
  components/local-app/pkg/prettyprint/prettyprint.go
  components/local-app/pkg/telemetry/telemetry.go
Labels: size/XL, team: team-experience

#19020 Adding ConfigurationServiceAPI
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/repositories/detail/RepositoryDetail.tsx
  components/dashboard/src/repositories/detail/RepositoryName.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/service/public-api.ts
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/configuration_grpc.pb.go
  components/public-api/go/v1/v1connect/configuration.connect.go
  components/public-api/go/v1/v1connect/configuration.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/configuration_connect.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
Labels: size/XXL, team: team-experience

#19045 [server] remove gitpod support mention from errors
  components/server/src/api/server.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/S, team: team-experience

#19044 Add storage metadata to workspace CR
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
Labels: size/S, team: team-engine

#19047 [usage] export creation and stopped time
  components/dashboard/src/usage/download/transform-usage-record.ts
  components/gitpod-db/go/usage.go
  components/gitpod-db/go/workspace_instance.go
  components/gitpod-protocol/src/usage.ts
  components/usage/pkg/apiv1/usage.go
Labels: size/S, team: team-experience

#19043 [dashboard] fix list repositories without projects
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
Labels: size/S, team: team-experience

#19017 [server] move FGA calls into AuthProviderService
  components/gitpod-db/src/typeorm/entity/db-auth-provider-entry.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/auth-provider-scopes.ts
  components/server/src/auth/auth-provider-service.spec.db.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/host-context-provider-impl.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19046 local cli: support additional ssh arguments
  components/local-app/cmd/workspace-ssh.go
  components/local-app/go.mod
  components/local-app/pkg/helper/workspace.go
Labels: size/M, team: team-experience

#19041 add authprovider.proto to public-api
  components/public-api/gitpod/v1/authprovider.proto
  components/public-api/go/v1/authprovider.pb.go
  components/public-api/go/v1/authprovider_grpc.pb.go
  components/public-api/go/v1/v1connect/authprovider.connect.go
  components/public-api/go/v1/v1connect/authprovider.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/authprovider_connect.ts
  components/public-api/typescript/src/gitpod/v1/authprovider_pb.ts
Labels: size/XXL

#19050 Add test for ObserveWorkspaceUntilStarted
  components/local-app/pkg/helper/workspace.go
  components/local-app/pkg/helper/workspace_test.go
Labels: size/L, team: team-experience

#19003 Collect workspace classes from workspace cluster
  components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
  components/gitpod-db/src/typeorm/migration/1699012261520-WorkspaceClusterAvailableClasses.ts
  components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
  components/gitpod-db/src/workspace-cluster-db.spec.db.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/workspace-cluster.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/config/config.go
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/client-provider.ts
  components/ws-manager-api/typescript/src/constraints.ts
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-api/typescript/src/promisified-client.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-mk2/service/manager.go
  components/ws-manager-mk2/service/manager_test.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XL, team: team-experience, team: team-engine

#19051 Fix hanging streams
  components/local-app/README.md
  components/local-app/cmd/workspace-create.go
  components/local-app/cmd/workspace-stop.go
  components/local-app/pkg/helper/workspace.go
Labels: size/S, team: team-experience

#19053 We only have CRDs now
  components/ws-proxy/pkg/config/config.go
  install/installer/pkg/components/ws-proxy/configmap.go
Labels: size/XS, team: team-engine

#19055 Gitpod VS Code Browser Release `1.84.2`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19058 [spicedb] Change readiness probe to unblock startup
  install/installer/pkg/components/spicedb/deployment.go
Labels: size/S, team: team-experience

#19034 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19008 [public-api] Add AuthProviderService service
  components/dashboard/src/service/json-rpc-authprovider-client.ts
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/v1/authprovider.proto
  components/public-api/go/v1/authprovider.pb.go
  components/public-api/typescript/src/gitpod/v1/authprovider_pb.ts
  components/server/src/api/auth-provider-service-api.ts
  components/server/src/api/pagination.spec.ts
  components/server/src/api/pagination.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/unauthenticated.spec.ts
  components/server/src/api/unauthenticated.ts
  components/server/src/auth/auth-provider-service.spec.db.ts
  components/server/src/auth/auth-provider-service.ts
Labels: size/XXL, team: team-experience

#19056 [gitpod-cli] Add auto-updating capabilities
  components/local-app/BUILD.js
  components/local-app/BUILD.yaml
  components/local-app/README.md
  components/local-app/cmd/config-get.go
  components/local-app/cmd/config-set.go
  components/local-app/cmd/login.go
  components/local-app/cmd/root.go
  components/local-app/cmd/root_test.go
  components/local-app/cmd/version-update.go
  components/local-app/cmd/version-update_test.go
  components/local-app/cmd/version.go
  components/local-app/go.mod
  components/local-app/go.sum
  components/local-app/leeway.Dockerfile
  components/local-app/main/gitpod-local-companion/main.go
  components/local-app/main/update-manifest/main.go
  components/local-app/pkg/config/config.go
  components/local-app/pkg/config/context.go
  components/local-app/pkg/constants/constants.go
  components/local-app/pkg/selfupdate/selfupdate.go
  components/local-app/pkg/selfupdate/selfupdate_test.go
  components/local-app/version.go
  components/local-app/version.txt
Labels: size/XXL, team: team-experience

#19038 [public-api] aligns with latest guidelines
  components/dashboard/package.json
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/data/organizations/update-org-mutation.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/buf.yaml
  components/public-api/gitpod/v1/organization.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/container-module.ts
  components/server/src/orgs/default-workspace-image-validator.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#19069 Remove Prebuild Events page and jsonrpc methods
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/projects/Events.tsx
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: team-experience

#19021 Configuration Detail setup
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/components/WidePageWithSubmenu.tsx
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailGeneral.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
  components/dashboard/src/repositories/detail/RepositoryDetail.tsx
  components/dashboard/src/repositories/detail/RepositoryName.tsx
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfigurationModal.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
Labels: size/XXL, team: team-experience

#19042 [installer] make sure dashboard is deployed after server and papi-server
  components/common-go/experiments/configcat.go
  components/common-go/experiments/flags.go
  components/common-go/experiments/types.go
  components/service-waiter/cmd/component.go
  components/service-waiter/cmd/component_test.go
  components/service-waiter/go.mod
  components/service-waiter/go.sum
  components/service-waiter/pkg/metrics/metrics.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/dashboard/constants.go
  install/installer/pkg/components/dashboard/deployment.go
  install/installer/pkg/components/ide-metrics/configmap.go
  install/installer/pkg/components/ide-metrics/constants.go
  install/installer/pkg/components/ide-metrics/networkpolicy.go
  install/installer/pkg/components/proxy/networkpolicy.go
Labels: size/XL, team: staff-engineers, team: team-experience

#19039 Repository Config list page
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/components/podkit/layout/PageHeading.tsx
  components/dashboard/src/components/podkit/tables/Table.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/repositories/list/PaginationControls.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/projects/projects-service.ts
Labels: size/XXL, team: team-experience

#19068 Support disabling preemptible preview VMs
  .github/actions/preview-create/entrypoint.sh
  .github/actions/preview-create/metadata.yml
  .github/pull_request_template.md
  .github/workflows/build.yml
Labels: size/XS

#19032 Remove scroll gutter styles
  components/dashboard/src/index.css
Labels: size/XS, team: team-experience

#19072 Configuration Details: Workspace Defaults
  components/dashboard/package.json
  components/dashboard/src/app/AppLoading.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/podkit/forms/Label.tsx
  components/dashboard/src/components/podkit/forms/RadioListField.tsx
  components/dashboard/src/components/podkit/loading/Delayed.tsx
  components/dashboard/src/components/podkit/loading/LoadingState.tsx
  components/dashboard/src/data/projects/project-queries.ts
  components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailWorkspaces.tsx
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  yarn.lock
Labels: size/XL, team: team-experience

#19066 Update runc to v1.1.10
  components/local-app/go.mod
  components/local-app/go.sum
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/leeway.Dockerfile
  install/installer/go.mod
  install/installer/go.sum
Labels: size/S, team: team-experience, team: team-engine

#19074 [server] remove obsolete and unused `getSuggestedContextURLs`
  components/dashboard/src/service/service-mock.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/public-api-server/pkg/apiv1/scm.go
  components/public-api-server/pkg/apiv1/scm_test.go
  components/server/src/auth/rate-limiter.ts
  components/server/src/oauth-server/db.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#19023 [server] Introduce RequestContext
  components/gitpod-protocol/src/analytics.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/gitpod-protocol/src/util/logging.ts
  components/server/leeway.Dockerfile
  components/server/src/analytics.ts
  components/server/src/api/auth-provider-service-api.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/handler-context-augmentation.d.ts
  components/server/src/api/hello-service-api.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/auth/subject-id.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/container-module.ts
  components/server/src/init.ts
  components/server/src/jobs/runner.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/server.ts
  components/server/src/util/log-context.ts
  components/server/src/util/request-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#19022 [papi] migrate ListWorkspaces and WatchWorkspaceStatus
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
  components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
  components/dashboard/src/data/workspaces/list-workspaces-query.ts
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/dashboard/src/workspaces/WorkspaceStatusIndicator.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-protocol/src/public-api-pagination.spec.ts
  components/gitpod-protocol/src/public-api-pagination.ts
  components/public-api/generate.sh
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/XXL, team: team-experience

#19085 [public-api] Add envvar proto file
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/go/v1/envvar_grpc.pb.go
  components/public-api/go/v1/v1connect/envvar.connect.go
  components/public-api/go/v1/v1connect/envvar.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/envvar_connect.ts
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
Labels: size/XXL, team: team-experience

#19077 Remove obsolete New Project page
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/data/git-providers/github-queries.ts
  components/dashboard/src/data/git-providers/provider-repositories-query.ts
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/new-project/NewProjectAccountSelector.tsx
  components/dashboard/src/projects/new-project/NewProjectAuthRequired.tsx
  components/dashboard/src/projects/new-project/NewProjectCreateFromURL.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoList.tsx
  components/dashboard/src/projects/new-project/NewProjectRepoSelection.tsx
  components/dashboard/src/projects/new-project/NewProjectSearchInput.tsx
  components/dashboard/src/projects/new-project/NewProjectSubheading.tsx
  components/dashboard/src/projects/new-project/reconfigure-github.ts
  components/dashboard/src/projects/projects.routes.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/bitbucket/bitbucket-app-support.ts
  components/server/src/container-module.ts
  components/server/src/github/github-app-support.ts
  components/server/src/gitlab/gitlab-app-support.spec.ts
  components/server/src/gitlab/gitlab-app-support.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19064 Gitpod CLI: Improve Segment logging
  components/ide-proxy/BUILD.yaml
  components/ide-proxy/Dockerfile
  components/local-app/cmd/root.go
  components/local-app/pkg/telemetry/telemetry.go
  components/proxy/conf/Caddyfile
Labels: size/S, team: team-experience

#19081 [gRPC] Enable PATs to be used for authorizing with the gRPC API
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/auth/bearer-authenticator.spec.db.ts
  components/server/src/auth/bearer-authenticator.ts
  components/server/src/auth/function-access.ts
  components/server/src/auth/personal-access-token.spec.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/server.ts
  dev/gpctl/cmd/public-api-workspace.go
  dev/gpctl/cmd/public-api-workspaces-get.go
  dev/gpctl/cmd/public-api-workspaces-list.go
  dev/gpctl/cmd/public-api.go
  dev/gpctl/go.mod
  dev/gpctl/go.sum
Labels: size/XL, team: team-experience, team: team-engine

#19079 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19089 [proxy] Expose v1 api on api. subdomain
  components/proxy/conf/Caddyfile
  dev/gpctl/cmd/public-api-workspaces-get.go
  dev/gpctl/cmd/public-api-workspaces-list.go
  dev/gpctl/cmd/public-api.go
Labels: size/M, team: team-experience, team: team-engine

#19090 [public-api] Add ssh key proto
  components/public-api/gitpod/v1/ssh.proto
  components/public-api/go/v1/ssh.pb.go
  components/public-api/go/v1/ssh_grpc.pb.go
  components/public-api/go/v1/sshkey.pb.go
  components/public-api/go/v1/sshkey_grpc.pb.go
  components/public-api/go/v1/v1connect/ssh.connect.go
  components/public-api/go/v1/v1connect/ssh.proxy.connect.go
  components/public-api/go/v1/v1connect/sshkey.connect.go
  components/public-api/go/v1/v1connect/sshkey.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/ssh_connect.ts
  components/public-api/typescript/src/gitpod/v1/ssh_pb.ts
  components/public-api/typescript/src/gitpod/v1/sshkey_connect.ts
  components/public-api/typescript/src/gitpod/v1/sshkey_pb.ts
Labels: size/XXL, team: team-experience

#19092 [server/dashboard] use ApplicationError
  components/dashboard/src/service/json-rpc-authprovider-client.ts
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/server/src/api/auth-provider-service-api.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/L, team: team-experience

#19078 Adding pagination tokens for config service
  components/dashboard/src/components/podkit/buttons/LoadingButton.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/repositories/list/PaginationControls.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/public-api/gitpod/v1/pagination.proto
  components/public-api/go/v1/pagination.pb.go
  components/public-api/typescript/src/gitpod/v1/pagination_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/pagination.spec.ts
  components/server/src/api/pagination.ts
Labels: size/XL, team: team-experience

#19067 [public-api] Migrate envvarService
  components/dashboard/src/data/projects/set-project-env-var-mutation.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/service/json-rpc-envvar-client.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-db/src/utils.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19096 Imported repos list empty state updates
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/repositories/list/RepoListEmptyState.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
Labels: size/XL, team: team-experience

#19094 [server] fix listAuthProviderDescriptions if unauthenticated
  components/server/src/api/auth-provider-service-api.ts
Labels: size/XS, team: team-experience

#19063 [baseserver] Emit metrics for logs produced by level ENG-349
  components/common-go/baseserver/server.go
  components/common-go/log/log.go
  components/common-go/log/metrics.go
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/gitpod-db/go/go.mod
  components/gitpod-db/go/go.sum
  components/ide/code/codehelper/go.mod
  components/ide/code/codehelper/go.sum
  components/ide/jetbrains/launcher/go.mod
  components/ide/jetbrains/launcher/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/service-waiter/go.mod
  components/service-waiter/go.sum
  components/ws-daemon/nsinsider/go.mod
  components/ws-daemon/nsinsider/go.sum
  dev/gp-gcloud/go.mod
  dev/gp-gcloud/go.sum
  dev/loadgen/go.mod
  dev/loadgen/go.sum
Labels: size/L, team: staff-engineers, team: team-experience, team: team-engine

#19075 [papi] Add proto for SCMService
  components/public-api/gitpod/v1/scm.proto
  components/public-api/go/v1/scm.pb.go
  components/public-api/go/v1/scm_grpc.pb.go
  components/public-api/go/v1/v1connect/scm.connect.go
  components/public-api/go/v1/v1connect/scm.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/scm_connect.ts
  components/public-api/typescript/src/gitpod/v1/scm_pb.ts
Labels: size/XL, team: team-experience

#19099 Add GitpodWorkspaceHighStartFailureRate alert
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
Labels: size/S, team: team-engine

#19102 [public-api] define error details
  components/public-api/generate.sh
  components/public-api/gitpod/experimental/v1/dummy.proto
  components/public-api/gitpod/experimental/v1/editor_service.proto
  components/public-api/gitpod/experimental/v1/ide_client.proto
  components/public-api/gitpod/experimental/v1/identityprovider.proto
  components/public-api/gitpod/experimental/v1/oidc.proto
  components/public-api/gitpod/experimental/v1/pagination.proto
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/gitpod/experimental/v1/scm.proto
  components/public-api/gitpod/experimental/v1/stats.proto
  components/public-api/gitpod/experimental/v1/teams.proto
  components/public-api/gitpod/experimental/v1/tokens.proto
  components/public-api/gitpod/experimental/v1/user.proto
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/gitpod/v1/authprovider.proto
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/gitpod/v1/error.proto
  components/public-api/gitpod/v1/organization.proto
  components/public-api/gitpod/v1/pagination.proto
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/gitpod/v1/scm.proto
  components/public-api/gitpod/v1/ssh.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/experimental/v1/oidc.pb.go
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/go/experimental/v1/tokens.pb.go
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/error.pb.go
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/go/v1/scm.pb.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/typescript/src/gitpod/v1/error_pb.ts
Labels: size/XXL, team: team-experience

#19100 [server] remove unused `getFeaturedRepositories`
  components/dashboard/src/service/service-mock.ts
  components/gitpod-db/src/typeorm/entity/db-repository-whitelist.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#19062 [public-api] migrate PrebuildService
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/data/prebuilds/latest-project-prebuild-query.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/service/json-rpc-prebuild-client.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/generate-async-generator.spec.ts
  components/gitpod-protocol/src/generate-async-generator.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/prebuilds/prebuild-manager.spec.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/util/request-context.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19086 Restructure config and contexts
  components/local-app/cmd/config-context-delete.go
  components/local-app/cmd/config-context-list.go
  components/local-app/cmd/config-context-modify.go
  components/local-app/cmd/config-context-use.go
  components/local-app/cmd/config-context.go
  components/local-app/cmd/config-get.go
  components/local-app/cmd/config-set.go
  components/local-app/version.txt
Labels: size/L, team: team-experience

#19080 `updateConfiguration`
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/configuration_grpc.pb.go
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/v1connect/configuration.connect.go
  components/public-api/go/v1/v1connect/configuration.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/configuration_connect.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
Labels: size/XL, team: team-experience

#19095 [public-api] Some renaming
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/service/json-rpc-envvar-client.ts
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/envvar-service-api.ts
Labels: size/M, team: team-experience

#19097 Add sorting to imported repos list and corresponding API
  components/dashboard/public/complete-auth/index.html
  components/dashboard/src/FromReferrer.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/OauthClientApproval.tsx
  components/dashboard/src/admin/BlockedEmailDomains.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/app/Blocked.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/components/error-boundaries/ReloadPageErrorBoundary.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/components/podkit/loading/LoadingState.tsx
  components/dashboard/src/components/podkit/tables/SortableTable.tsx
  components/dashboard/src/components/podkit/tables/Table.tsx
  components/dashboard/src/components/toasts/Toast.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
  components/dashboard/src/index.css
  components/dashboard/src/projects/InstallGitHubApp.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/usage/UsageDateFilters.tsx
  components/dashboard/src/usage/download/DownloadUsage.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/user-settings/SelectAccountModal.tsx
  components/dashboard/src/whatsnew/WhatsNew.tsx
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/gitpod/v1/sorting.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/sorting.pb.go
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/public-api/typescript/src/gitpod/v1/sorting_pb.ts
  components/server/src/api/configuration-service-api.ts
Labels: size/XXL, team: team-experience

#19106 [build] make `yarn build` more incremental
  components/dashboard/tsconfig.json
  components/gitpod-db/package.json
  components/gitpod-db/tsconfig.json
  components/gitpod-protocol/package.json
  components/gitpod-protocol/tsconfig.json
  components/server/package.json
  components/server/tsconfig.json
Labels: size/S, team: team-experience

#19111 [build] fix tsconfig
  components/gitpod-protocol/tsconfig.json
Labels: size/XS, team: team-experience

#19112 [server] Removes unused RepositoryService.canInstall
  components/server/src/prebuilds/bitbucket-server-service.spec.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/prebuilds/bitbucket-service.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/prebuilds/gitlab-service.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience

#19098 [server] Extract ScmService to be used by both APIs
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/server/src/api/scm-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/authenticator.ts
  components/server/src/bitbucket-server/bitbucket-server-token-handler.ts
  components/server/src/bitbucket/bitbucket-token-handler.ts
  components/server/src/container-module.ts
  components/server/src/github/github-token-helper.ts
  components/server/src/gitlab/gitlab-token-helper.ts
  components/server/src/projects/projects-service.ts
  components/server/src/projects/scm-service.ts
  components/server/src/scm/scm-service.spec.db.ts
  components/server/src/scm/scm-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/user/token-provider.ts
  components/server/src/user/token-service.ts
  components/server/src/workspace/git-token-scope-guesser.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#19117 Fix for "never read"
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: team-experience

#19103 [dashboard/server] app error conversion based on error details
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/server/src/auth/errors.ts
  components/server/src/errors/index.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/context-parser-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19076 Migrate CreateAndStartWorkspace method in dashboard
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/create-workspace-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/context.pb.go
  components/public-api/go/v1/context_grpc.pb.go
  components/public-api/go/v1/v1connect/context.connect.go
  components/public-api/go/v1/v1connect/context.proxy.connect.go
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript/src/gitpod/v1/context_connect.ts
  components/public-api/typescript/src/gitpod/v1/context_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/container-module.ts
  components/server/src/express-util.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/server.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/util/request-context.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/context-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XXL, team: team-experience

#19110 [public-api] migrate ssh service
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/service/json-rpc-ssh-client.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/gitpod-protocol/src/public-api-converter.spec.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/gitpod/v1/ssh.proto
  components/public-api/go/v1/ssh.pb.go
  components/public-api/go/v1/sshkey.pb.go
  components/public-api/go/v1/sshkey_grpc.pb.go
  components/public-api/go/v1/v1connect/sshkey.connect.go
  components/public-api/go/v1/v1connect/sshkey.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/ssh_pb.ts
  components/public-api/typescript/src/gitpod/v1/sshkey_connect.ts
  components/public-api/typescript/src/gitpod/v1/sshkey_pb.ts
  components/server/src/api/server.ts
  components/server/src/api/ssh-service-api.ts
  components/server/src/api/teams.spec.db.ts
Labels: size/XL, team: team-experience

#19125 [configcat] ensure that browser updates the cache
  components/proxy/plugins/configcat/configcat.go
Labels: size/XS, team: team-experience

#19107 cli: prompt for organization on login
  components/local-app/cmd/login.go
  components/local-app/go.mod
  components/local-app/go.sum
  components/local-app/version.txt
Labels: size/M, team: team-experience

#19105 [ws-manager-mk2] Add node utilization metrics
  components/ws-manager-mk2/controllers/metrics.go
Labels: size/L, team: team-engine

#19127 [usage] fix usage export
  components/usage/pkg/apiv1/usage.go
Labels: size/XS, team: team-experience

#19109 cli: use the gitpod endpoint for analytics
  components/local-app/cmd/root.go
  components/local-app/pkg/telemetry/telemetry.go
  components/local-app/version.txt
Labels: size/M, team: team-experience

#19059 Refactor configuration of workspace SSH key
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-proxy/pkg/common/infoprovider.go
  components/ws-proxy/pkg/proxy/infoprovider.go
  components/ws-proxy/pkg/sshproxy/server.go
Labels: size/L, team: team-experience, team: team-engine

#18933 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  dev/jetbrains-test/src/test/kotlin/io/gitpod/jetbrains/launcher/GatewayLauncherTest.kt
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19140 [dashboard] enable grpc migration per service
  components/dashboard/src/service/public-api.ts
  components/gitpod-protocol/src/generate-async-generator.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience

#19006 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#18878 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19146 Get SSH username from workspacekit
  components/ws-proxy/pkg/sshproxy/server.go
Labels: size/M, team: team-engine

#19148 Reduce job log verbosity
  components/server/src/jobs/runner.ts
Labels: size/XS, team: team-experience

#19149 [dashboard] Fix Repository Finder after switch to SCM Service
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/projects/create-project-modal/CreateProjectModal.tsx
  components/dashboard/src/repositories/create/ImportRepositoryModal.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: team-experience

#19141 [service-waiter] use ide proxy for metric report
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/ide-proxy/constants.go
Labels: size/S, team: team-experience

#19144 SubjectId: Address mismatch (I)
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/util/request-context.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#19152 [server] consider unfinished prebuilds
  components/server/src/prebuilds/incremental-workspace-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
Labels: size/S, team: team-experience

#19121 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19132 [papi] add user.proto and GetAuthenticatedUser – EXP-845
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/public-api-converter.ts
  components/public-api/generate.sh
  components/public-api/gitpod/v1/editor.proto
  components/public-api/gitpod/v1/user.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/editor.pb.go
  components/public-api/go/v1/scm_grpc.pb.go
  components/public-api/go/v1/user.pb.go
  components/public-api/go/v1/user_grpc.pb.go
  components/public-api/go/v1/v1connect/scm.connect.go
  components/public-api/go/v1/v1connect/user.connect.go
  components/public-api/go/v1/v1connect/user.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/typescript/src/gitpod/v1/editor_pb.ts
  components/public-api/typescript/src/gitpod/v1/scm_connect.ts
  components/public-api/typescript/src/gitpod/v1/user_connect.ts
  components/public-api/typescript/src/gitpod/v1/user_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
Labels: size/XL, team: team-experience

#19154 [ws-manager-mk2] Add workspace pending time histogram
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/M, team: team-engine

#19156 Fix leeway `make-user-admin` script
  components/BUILD.yaml
Labels: size/XS, team: team-experience

#19137 Fix some log statements and a minor in pre-commit settings
  .pre-commit-config.yaml
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
Labels: size/XS, team: team-experience

#19160 [ws-manager-mk2] Count node utilization by workspace pod requests
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/M, team: team-engine

#19162 Fix logic that hydrates protobuf msgs and add test
  components/dashboard/src/data/setup.test.ts
  components/dashboard/src/data/setup.tsx
Labels: size/S, team: team-experience

#19151 decouple gitpod-protocol from public-api
  .gitignore
  components/dashboard/BUILD.yaml
  components/dashboard/package.json
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/service/metrics.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/user-settings/Integrations.tsx
  components/gitpod-protocol/BUILD.yaml
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/index.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/gitpod-protocol/src/metrics.ts
  components/public-api/typescript-common/BUILD.yaml
  components/public-api/typescript-common/package.json
  components/public-api/typescript-common/src/auth-providers.ts
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript-common/src/public-api-errors.ts
  components/public-api/typescript-common/src/public-api-pagination.spec.ts
  components/public-api/typescript-common/src/public-api-pagination.ts
  components/public-api/typescript-common/tsconfig.json
  components/public-api/typescript/package.json
  components/server/BUILD.yaml
  components/server/package.json
  components/server/src/api/auth-provider-service-api.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/api/scm-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/ssh-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/errors/index.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/context-parser-service.ts
  components/supervisor/frontend/BUILD.yaml
  components/supervisor/frontend/package.json
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  yarn.lock
Labels: size/XL, team: team-experience

#19159 Install pre-commit hooks in prebuild
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  dev/image/Dockerfile
Labels: size/M, team: team-experience, team: team-engine

#19129 Migrate parts of gPRC workspaceService
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/default-workspace-image-query.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/service/service.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/user.pb.go
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript/src/gitpod/v1/user_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#19138 Refine workspace API
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/XXL, team: team-experience

#19135 Gitpod CLI changelog
  components/local-app/CHANGELOG.md
  components/local-app/cmd/root.go
Labels: size/S, team: team-experience

#19165 [dashboard] only keep public-api migration FF per a service
  components/dashboard/src/service/public-api.ts
Labels: size/XS, team: team-experience

#19161 Update repo config detail pages to use nested router
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/WidePageWithSubmenu.tsx
  components/dashboard/src/components/forms/InputField.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailGeneral.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailWorkspaces.tsx
  components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
Labels: size/L, team: team-experience

#19172 Revert "Refine workspace API (#19138)"
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/XXL, team: team-experience

#19170 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup
