Repository gitpod-io/gitpod, pull requests merged in 2023-12, with the labels that each got.

#19167 [dev] Add "previewctl get url"
  dev/preview/previewctl/cmd/get.go
Labels: size/S, team: team-experience

#19176 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19157 Repo List - Style updates
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/Header.tsx
  components/dashboard/src/components/forms/SelectInputField.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/components/podkit/layout/PageHeading.tsx
  components/dashboard/src/components/podkit/loading/LoadingState.tsx
  components/dashboard/src/components/podkit/tables/SortableTable.tsx
  components/dashboard/src/components/podkit/tables/Table.tsx
  components/dashboard/src/index.css
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
Labels: size/L, team: team-experience

#19179 [public-api] improve request exception logging
  components/dashboard/src/service/metrics.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service.tsx
  components/public-api/typescript-common/README.md
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/server/src/api/server.ts
Labels: size/L, team: team-experience

#19128 Configuration Variables page
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/projects/set-project-env-var-mutation.ts
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationModifyVariableModal.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationRemoveVariableModal.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableItem.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
  components/dashboard/src/service/json-rpc-envvar-client.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XXL, team: team-experience

#19178 Revert Refine workspace and fix bugs
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/public-api/generate.sh
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_1.json
  components/public-api/typescript-common/fixtures/toWorkspace2_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_2.json
  components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_3.json
  components/public-api/typescript-common/fixtures/toWorkspace_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace_1.json
  components/public-api/typescript-common/fixtures/toWorkspace_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace_2.json
  components/public-api/typescript-common/fixtures/toWorkspace_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace_3.json
  components/public-api/typescript-common/fixtures/toWorkspace_4.golden
  components/public-api/typescript-common/fixtures/toWorkspace_4.json
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/XXL, team: team-experience

#19185 [dashboard] proactively reconnect grpc streams
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/L, team: team-experience

#19184 New Prebuild Settings UI for repo configs
  components/dashboard/src/components/forms/SelectInputField.tsx
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/dashboard/src/repositories/detail/shared/WorkspaceClassOptions.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
Labels: size/XL, team: team-experience

#19192 Fix admin dashboard convert failed case
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.json
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_2.json
  components/public-api/typescript-common/scripts/new-fixtures.js
  components/public-api/typescript-common/src/fixtures.spec.ts
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/XL, team: team-experience

#19189 [iam] Use proper subjectId in updateOIDCUserOnSignin
  components/server/src/iam/iam-session-app.ts
Labels: size/XS, team: team-experience

#19193 [server] hook verification API service
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
Labels: size/XS, team: team-experience

#19194 [db] fix the query for non-fga migrated users
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.spec.db.ts
Labels: size/M, team: team-experience

#19177 Frontend development: redirect instead of proxy
  components/BUILD.yaml
  components/dashboard/README.md
  components/dashboard/craco.config.js
  components/dashboard/package.json
  components/proxy/conf/Caddyfile
  components/proxy/plugins/frontend_dev/frontend_dev.go
  components/proxy/plugins/frontend_dev/frontend_dev_test.go
  components/proxy/plugins/frontend_dev/go.mod
Labels: size/XL, team: team-experience

#19190 Fix text input background color
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/index.css
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
  components/dashboard/tailwind.config.js
Labels: size/L, team: team-experience

#19196 handle redirects in host reachability test
  components/server/src/auth/auth-provider-service.ts
Labels: size/XS, team: team-experience

#19195 [authorizer] prepare Authorizer for SubjectId rollout
  components/server/src/auth/subject-id.ts
  components/server/src/authorization/authorizer.spec.db.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/util/request-context.ts
Labels: size/L, team: team-experience

#19118 Migrate gRPC workspaceService other workspace related method
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
  components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
  components/dashboard/src/data/workspaces/list-workspaces-query.ts
  components/dashboard/src/data/workspaces/stop-workspace-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
  components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts
  components/dashboard/src/data/workspaces/update-workspace-mutation.ts
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/XXL, team: team-experience

#19207 Fix team-db spec
  components/gitpod-db/src/team-db.spec.db.ts
Labels: size/XS, team: team-experience

#19198 [dashboard] don't invalidate useOrganizations on update of user settings
  components/dashboard/src/data/organizations/orgs-query.ts
Labels: size/S, team: team-experience

#19204 Migrate WorkspaceService snapshot methods
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/fixtures/toWorkspaceSnapshot_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSnapshot_1.json
  components/public-api/typescript-common/fixtures/toWorkspaceSnapshot_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSnapshot_2.json
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/snapshot-service.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#19212 add GitpodV1APIServerErrors alert
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/S, team: team-experience

#19210 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19217 Scope config lookup to org
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/context-service.ts
Labels: size/S, team: team-experience

#19213 Migrate instanceUpdate on service.tsx
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/frontend-dashboard-service.ts
  components/public-api/typescript-common/fixtures/toAndFromPhase_1.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_1.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_10.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_10.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_11.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_11.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_12.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_12.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_2.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_2.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_3.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_3.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_4.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_4.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_5.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_5.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_6.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_6.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_7.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_7.json
  components/public-api/typescript-common/fixtures/toAndFromPhase_9.golden
  components/public-api/typescript-common/fixtures/toAndFromPhase_9.json
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/L, team: team-experience

#19221 Migrate InstallationService GetInstallationWorkspaceDefaultImage method
  components/dashboard/src/data/installation/default-workspace-image-query.ts
  components/dashboard/src/data/workspaces/default-workspace-image-query.ts
  components/dashboard/src/service/json-rpc-installation-client.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/public-api/gitpod/v1/installation.proto
  components/public-api/go/v1/installation.pb.go
  components/public-api/go/v1/installation_grpc.pb.go
  components/public-api/go/v1/v1connect/installation.connect.go
  components/public-api/go/v1/v1connect/installation.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/installation_connect.ts
  components/public-api/typescript/src/gitpod/v1/installation_pb.ts
  components/server/src/api/installation-service-api.ts
  components/server/src/auth/installation-service.ts
Labels: size/L, team: team-experience

#19187 [server] implement getAuthenticatedUser RPC
  components/public-api/typescript-common/src/public-api-converter.ts
  components/server/src/api/server.ts
  components/server/src/api/user-service-api.ts
  components/server/src/api/user.spec.ts
  components/server/src/api/user.ts
Labels: size/XL, team: team-experience

#19205 Adding prebuild status filter to repo configs list ui
  components/dashboard/package.json
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/podkit/select/Select.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/projects/projects-service.ts
  yarn.lock
Labels: size/XL, team: team-experience

#19224 Conditionally apply org id filter to project lookup
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
Labels: size/M, team: team-experience

#19231 [papi] Update UserService proto
  components/dashboard/src/service/json-rpc-user-client.ts
  components/public-api/gitpod/v1/user.proto
  components/public-api/go/v1/user.pb.go
  components/public-api/go/v1/user_grpc.pb.go
  components/public-api/go/v1/v1connect/user.connect.go
  components/public-api/go/v1/v1connect/user.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/user_connect.ts
  components/public-api/typescript/src/gitpod/v1/user_pb.ts
  components/server/src/api/user-service-api.ts
Labels: size/M, team: team-experience

#19235 [auth] RequestContext: add missing runWithSubjectId
  components/server/src/code-sync/code-sync-service.ts
  components/server/src/user/user-controller.ts
Labels: size/L, team: team-experience

#19230 Reflect Privacy policy update
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience

#19234 Migrate workspaceService updatePort method
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience

#19188 [jb] Add joinLink2 endpoint
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/launcher/main.go
Labels: size/XL, team: team-experience

#19226 Updating a few styles after design review
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
  components/dashboard/src/components/podkit/forms/RadioListField.tsx
  components/dashboard/src/components/podkit/tables/Table.tsx
  components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/dashboard/src/repositories/detail/shared/WorkspaceClassOptions.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
Labels: size/L, team: team-experience

#19242 [server] remove unused code
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/repohost/repo-service.ts
Labels: size/M, team: team-experience

#19222 Migrate resolve context url
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/data/workspaces/resolve-context-query.ts
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/workspace.pb.go
  components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace_1.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/context-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: team-experience

#19233 Update alpine to v3.19
  components/ide/code/codehelper/leeway.Dockerfile
  components/supervisor/leeway.Dockerfile
  components/supervisor/openssh/leeway.Dockerfile
Labels: size/S, team: team-experience

#19223 [dashboard] use HTTP endpoint for telemetry
  components/dashboard/package.json
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/data/tracking/track-event-mutation.ts
  components/dashboard/src/onboarding/UserOnboarding.tsx
  components/dashboard/src/service/service.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/metrics.ts
  components/gitpod-protocol/src/util/deferred.ts
  components/proxy/conf/Caddyfile
  components/public-api/typescript-common/package.json
  components/server/src/analytics-controller.ts
  components/server/src/api/rate-limited.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/container-module.ts
  components/server/src/express-util.ts
  components/server/src/rate-limitter.ts
  components/server/src/server.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/ws-manager-api/typescript/package.json
  package.json
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-engine

#19239 Fix relative URLs on the Integrations page
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/XS, team: team-experience

#19240 Remove global heading styles and use components for headings/labels
  components/dashboard/src/App.tsx
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/FromReferrer.tsx
  components/dashboard/src/OauthClientApproval.tsx
  components/dashboard/src/admin/BlockedEmailDomains.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/Blocked.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/index.css
  components/dashboard/src/projects/InstallGitHubApp.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/start/Open.tsx
  components/dashboard/src/start/VerifyModal.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
Labels: size/XL, team: team-experience

#19243 [papi] Add RPCs for Admin pages
  components/dashboard/src/app/AdminRoute.tsx
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/service/json-rpc-user-client.ts
  components/public-api/gitpod/v1/user.proto
  components/public-api/go/v1/user.pb.go
  components/public-api/go/v1/user_grpc.pb.go
  components/public-api/go/v1/v1connect/user.connect.go
  components/public-api/go/v1/v1connect/user.proxy.connect.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/user_connect.ts
  components/public-api/typescript/src/gitpod/v1/user_pb.ts
  components/server/src/api/user-service-api.ts
Labels: size/XL, team: team-experience

#19245 [workspace] update docker compose for gen107
  WORKSPACE.yaml
Labels: size/XS, team: team-engine

#19246 [workspace] bump buildkit and containerd dependencies for gen107
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/common-go/go-update-wc-deps.sh
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  install/installer/go.mod
  install/installer/go.sum
Labels: size/L, team: staff-engineers, team: team-experience, team: team-engine

#19206 [content-service] do git config after we have an init'd folder
  components/content-service/pkg/initializer/git.go
Labels: size/S, team: team-engine

#19250 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19248 Prevent a single error from breaking query client cache indefinitely
  components/dashboard/src/data/setup.tsx
Labels: size/XS, team: team-experience

#19244 Podkit buttons everywhere
  components/dashboard/src/components/Alert.tsx
  components/dashboard/src/components/AuthorizeGit.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/EmptyMessage.tsx
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/components/LinkButton.tsx
  components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
  components/dashboard/src/dedicated-setup/GettingStartedStep.tsx
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/onboarding/LinkedInBanner.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/projects/create-project-modal/CreateProjectModal.tsx
  components/dashboard/src/start/VerifyModal.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
  components/dashboard/src/teams/sso/ActivateConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClients.tsx
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/user-settings/ShowTokenModal.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: component: dashboard, size/XL, team: team-experience

#19251 [workspace] update AMI for gen107 for previews
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS

#19260 [code] Update code dockerfile
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/M, team: team-experience

#19215 Delete owned user on member removal
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/data/organizations/members-query.ts
  components/dashboard/src/hooks/use-user-loader.ts
  components/dashboard/src/teams/Members.tsx
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
Labels: size/L, team: team-experience

#19257 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19256 Update existing podkit components to use new contextual pk classes
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
  components/dashboard/src/components/podkit/combobox/Combobox.tsx
  components/dashboard/src/components/podkit/dropdown/DropDown.tsx
  components/dashboard/src/components/podkit/dropdown/DropDownActions.tsx
  components/dashboard/src/components/podkit/forms/RadioListField.tsx
  components/dashboard/src/components/podkit/typography/Text.tsx
  components/dashboard/src/components/podkit/typography/TextMuted.tsx
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
Labels: size/L, team: team-experience

#19261 Switch component updates
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/tailwind.config.js
Labels: size/S, team: team-experience

#19263 [server] Ensure env var id when doing update in old api
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: team-experience

#17977 Remove Werft badge from README
  README.md
Labels: meta: never-stale, size/XS

#19265 Remove Copilot notes from PR template
  .github/pull_request_template.md
Labels: size/XS

#19191 Add org-level workspace class restrictions
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/org-workspace-classes-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1701725025283-AddOrgSettingWorkspaceClass.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/organization_grpc.pb.go
  components/public-api/go/v1/v1connect/organization.connect.go
  components/public-api/go/v1/v1connect/organization.proxy.connect.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_connect.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/auth/installation-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/XXL, team: team-experience

#19268 Revert preview env workspace classes changes
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M

#19266 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19272 Revert "Add org-level workspace class restrictions"
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/org-workspace-classes-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1701725025283-AddOrgSettingWorkspaceClass.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/organization_grpc.pb.go
  components/public-api/go/v1/v1connect/organization.connect.go
  components/public-api/go/v1/v1connect/organization.proxy.connect.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_connect.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/auth/installation-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#19273 [gitpod-db] AddOrgSettingWorkspaceClass1701725025283
  components/gitpod-db/src/typeorm/migration/1701725025283-AddOrgSettingWorkspaceClass.ts
Labels: size/S, team: team-experience

#19264 cli: WS SSH & Opening improvements
  components/local-app/CHANGELOG.md
  components/local-app/cmd/config-set.go
  components/local-app/cmd/workspace-open.go
  components/local-app/cmd/workspace-ssh.go
  components/local-app/pkg/helper/workspace.go
  components/local-app/version.txt
Labels: size/M, team: team-experience

#19275 Revert "Revert "Add org-level workspace class restrictions"" - Server
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/organization_grpc.pb.go
  components/public-api/go/v1/v1connect/organization.connect.go
  components/public-api/go/v1/v1connect/organization.proxy.connect.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_connect.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/auth/installation-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XL, team: team-experience

#19276 Revert and fixing "Revert "Add org-level workspace class restrictions"" - Dashboard
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/org-workspace-classes-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XL, team: team-experience

#19274 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19277 [content-service] revert git config feature.manyFiles true
  components/content-service/pkg/initializer/git.go
Labels: size/XS, team: team-engine

#19269 Remove Access Token scope checkbox
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
Labels: size/M, team: team-experience

#19120 Improve selfupdate support
  components/local-app/pkg/selfupdate/selfupdate.go
Labels: size/XS, team: team-experience

#19281 [ws-proxy] add SSH Summary to overview dashboard
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/L, team: team-engine

#19279 [code] Update code to 1.85.1
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19280 [server] fix unit test
  components/server/src/auth/auth-provider-service.spec.db.ts
  components/server/src/auth/bearer-authenticator.spec.db.ts
  components/server/src/authorization/authorizer.spec.db.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/scm/scm-service.spec.db.ts
  components/server/src/session-handler.spec.db.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/gitpod-token-service.spec.db.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/workspace-service.spec.db.ts
Labels: size/M, team: team-experience

#19270 Respect allowed org ws classes in config settings
  components/dashboard/src/repositories/detail/shared/WorkspaceClassOptions.tsx
Labels: size/XS, team: team-experience

#19282 Update openssh to v9.6-P1
  components/supervisor/openssh/leeway.Dockerfile
Labels: size/XS, team: team-experience

#19247 Improving prebuild related auth errors
  components/dashboard/src/App.tsx
  components/dashboard/src/components/toasts/Toasts.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/index.css
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/prebuilds/EnablePrebuildsError.tsx
  components/dashboard/tailwind.config.js
  components/public-api/gitpod/v1/error.proto
  components/public-api/go/v1/error.pb.go
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-errors.ts
  components/public-api/typescript/src/gitpod/v1/error_pb.ts
  components/server/src/auth/auth-provider-scopes.ts
  components/server/src/auth/resource-access.ts
  components/server/src/bitbucket-server/bitbucket-server-token-handler.ts
  components/server/src/bitbucket/bitbucket-token-handler.ts
  components/server/src/errors/index.ts
  components/server/src/github/api.ts
  components/server/src/github/github-context-parser.ts
  components/server/src/github/github-token-helper.ts
  components/server/src/gitlab/gitlab-context-parser.ts
  components/server/src/gitlab/gitlab-token-helper.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/prebuilds/gitlab-service.ts
  components/server/src/prebuilds/token-scopes-inclusion.spec.ts
  components/server/src/prebuilds/token-scopes-inclusion.ts
  components/server/src/scm/scm-service.ts
Labels: size/XXL, team: team-experience

#19285 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19286 Update privacy policy effective date
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience

#19271 [installer] Add ws-daemon-ng to version manifests
  install/installer/pkg/config/versions/versions.go
Labels: size/XS, team: team-experience

#19291 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: team-experience

#19299 [obs] tune GitpodWorkspaceStuckOnStoppingMk2 alert
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
Labels: size/S, team: team-engine
