Repository gitpod-io/gitpod, pull requests merged in 2023-06, with the labels that each got.

#17720 Fix double submission on SSO Config modal
  components/dashboard/src/admin/BlockedEmailDomains.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/components/Alert.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/ConfirmationModal.tsx
  components/dashboard/src/components/LinkButton.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
  components/dashboard/src/data/projects/set-project-env-var-mutation.ts
  components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/start/VerifyModal.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/teams/sso/ActivateConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/OIDCClientListItem.tsx
  components/dashboard/src/user-settings/Account.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/user-settings/SSHKeys.tsx
  components/dashboard/src/user-settings/ShowTokenModal.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XXL, team: webapp

#17804 [observability] add WorkspaceUpdates filter to supervisor
  operations/observability/mixins/IDE/dashboards/components/supervisor.json
Labels: size/S, team: IDE

#17795 Have db-tests run during CI again
  components/gitpod-db/package.json
  components/server/BUILD.yaml
  components/server/src/api/teams.spec.db.ts
  components/server/src/container-module.ts
  components/server/src/user/user-service.spec.db.ts
Labels: size/M, team: webapp

#17803 [ws-manager-mk2] Remove full workspace backup
  components/content-service-api/go/content-manifest.go
  components/content-service/pkg/layer/provider.go
  components/content-service/pkg/layer/provider_test.go
  components/content-service/pkg/storage/storage.go
  components/workspacekit/cmd/rings.go
  components/ws-daemon-api/daemon.proto
  components/ws-daemon-api/go/daemon.pb.go
  components/ws-daemon-api/go/daemon_grpc.pb.go
  components/ws-daemon-api/go/mock/mock.go
  components/ws-daemon-api/go/workspace_daemon.pb.go
  components/ws-daemon-api/go/workspace_daemon_grpc.pb.go
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_pb.js
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.js
  components/ws-daemon-api/workspace_daemon.proto
  components/ws-daemon/pkg/content/archive.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  install/installer/pkg/components/server/types.go
  test/tests/components/ws-manager/content_test.go
Labels: size/L, team: webapp, team: workspace, feature: ws-manager-mk2

#17662 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#17787 [server] Remove self-hosted installation admin telemetry endpoint
  components/dashboard/src/admin-context.tsx
  components/dashboard/src/admin/Settings.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/index.tsx
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/index.ts
  components/gitpod-db/src/installation-admin-db.ts
  components/gitpod-db/src/typeorm/entity/db-installation-admin.ts
  components/gitpod-db/src/typeorm/installation-admin-db-impl.ts
  components/gitpod-protocol/src/admin-protocol.ts
  components/gitpod-protocol/src/index.ts
  components/gitpod-protocol/src/installation-admin-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/container-module.ts
  components/server/src/installation-admin/installation-admin-controller.ts
  components/server/src/installation-admin/telemetry-data-provider.ts
  components/server/src/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp

#17799 [server] Validate cloneURL in createProject WEB-404
  components/server/src/projects/projects-service.ts
Labels: size/S, team: webapp

#17796 Remove CHANGELOG.md
  CHANGELOG.md
Labels: size/XXL

#17813 [gitpod-db] remove deprected/unused `tokens` column – WEB-400
  components/gitpod-db/src/typeorm/entity/db-identity.ts
  components/gitpod-db/src/typeorm/migration/1685694597883-RemoveIdentityTokens.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17790 [public-api] Update getWorkspace proto
  components/public-api/gitpod/experimental/v1/workspaces.proto
Labels: size/S, team: webapp

#17820 Point code nightly to release branch
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE

#17558 [ws-proxy] don't hit blobserve with web sockets
  components/ws-proxy/pkg/proxy/routes.go
Labels: size/XS, team: workspace

#17798 [server] Make JWT Session rolling through refresh endpoint WEB-418
  components/server/src/iam/iam-session-app.ts
  components/server/src/server.ts
  components/server/src/session-handler.ts
Labels: size/M, team: webapp

#17815 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17823 [server] avoid returning DBUser on ws API – WEB-400
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17829 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/common/GitpodConnectionHandleFactory.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectionHandle.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnectionHandle.kt
  test/pkg/integration/apis.go
Labels: size/M, team: workspace, team: IDE

#17819 Read email from SSO profile – WEB-437
  components/dashboard/src/user-settings/Account.tsx
  components/gitpod-db/src/typeorm/entity/db-identity.ts
  components/gitpod-db/src/typeorm/migration/1685955742395-AddLastSigninTimeToIdentity.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/iam/iam-session-app.ts
Labels: size/L, team: webapp

#17818 Remove CDE Universe footnote
  components/dashboard/src/images/cdeuniverse.svg
  components/dashboard/src/start/StartPage.tsx
Labels: size/M, team: webapp

#17748 Update login page layout
  components/dashboard/src/Login.tsx
  components/dashboard/src/images/welcome/automate.svg
  components/dashboard/src/images/welcome/code.svg
  components/dashboard/src/images/welcome/collaborate.svg
  components/dashboard/src/images/welcome/customize.svg
  components/dashboard/src/images/welcome/fresh.svg
  components/dashboard/src/images/welcome/prebuild.svg
Labels: size/XL, team: webapp

#17830 try to fix flaky terminal tests by using timeout context to unblock closing of terminals
  components/supervisor/pkg/terminal/terminal.go
  components/supervisor/pkg/terminal/terminal_test.go
Labels: size/M, team: IDE

#17807 Update Usage page design
  components/dashboard/src/Usage.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageView.tsx
  components/dashboard/src/data/usage/usage-query.ts
  components/dashboard/src/usage/UsageDateFilters.tsx
  components/dashboard/src/usage/UsageEntry.tsx
  components/dashboard/src/usage/UsageSummary.tsx
  components/dashboard/src/usage/UsageView.tsx
Labels: size/XXL, team: webapp

#17824 [db] Add go model for User - WEB-263
  components/gitpod-db/go/dbtest/identity.go
  components/gitpod-db/go/dbtest/user.go
  components/gitpod-db/go/identity.go
  components/gitpod-db/go/user.go
  components/gitpod-db/go/user_test.go
Labels: size/L, team: webapp

#17847 fix publishg of JB GW plugin
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
Labels: size/XS, team: IDE

#17848 [ws-manager-mk2] Remove ws-manager-mk2 from experimental section
  components/ws-daemon/cmd/run.go
  components/ws-daemon/pkg/daemon/config.go
  components/ws-daemon/pkg/daemon/daemon.go
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/ws-daemon/configmap.go
  install/installer/pkg/components/ws-daemon/constants.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-daemon/role.go
  install/installer/pkg/components/ws-daemon/rolebinding.go
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/components/ws-manager-mk2/objects.go
  install/installer/pkg/components/ws-proxy/role.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XL, team: workspace, feature: ws-manager-mk2

#17858 [content-service] Fix GCP error message check
  components/content-service/pkg/storage/gcloud.go
Labels: size/XS, team: workspace

#17304 Enable ws-manager-mk2 in preview environments by default
  .github/actions/deploy-gitpod/entrypoint.sh
  .github/actions/deploy-gitpod/metadata.yml
  .github/pull_request_template.md
  .github/workflows/build.yml
  .werft/jobs/build/deploy-to-preview-environment.ts
  .werft/jobs/build/installer/installer.ts
  .werft/jobs/build/job-config.ts
Labels: size/S, team: workspace, feature: ws-manager-mk2

#17832 [server] Removed deprecated api.getEnvVars
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17849 Update usage export toast style
  components/dashboard/src/components/toasts/Toast.tsx
  components/dashboard/src/usage/download/DownloadUsage.tsx
Labels: size/XS, team: webapp

#17864 [db] fix expensive table check
  components/gitpod-db/src/periodic-deleter.ts
Labels: size/XS, team: webapp

#17846 [server] Remove old session cookies - WEB-103
  components/server/package.json
  components/server/src/auth/authenticator.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/express-util.ts
  components/server/src/express.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/server.ts
  components/server/src/session-handler.ts
  components/server/src/user/user-controller.ts
  components/server/src/websocket/websocket-connection-manager.ts
  yarn.lock
Labels: size/XL, team: webapp

#17865 [server] Remove stale workspace feature flags
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp, team: workspace

#17853 Add voice calls for phone verification
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/start/VerifyModal.tsx
  components/server/src/auth/verification-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17855 [preview] update image for gen99
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: workspace

#17867 [go] Remove jwtSessions feature flag
  components/common-go/experiments/flags.go
  components/public-api-server/pkg/auth/session_jwt.go
  components/public-api-server/pkg/server/server.go
Labels: size/S, team: webapp, team: staff-engineers

#17868 [agent-smith] Stop workspace through ws-manager
  components/ee/agent-smith/BUILD.yaml
  components/ee/agent-smith/go.mod
  components/ee/agent-smith/go.sum
  components/ee/agent-smith/pkg/agent/actions.go
  components/ee/agent-smith/pkg/agent/agent.go
  components/ee/agent-smith/pkg/config/config.go
  install/installer/pkg/components/agent-smith/configmap.go
  install/installer/pkg/components/agent-smith/daemonset.go
Labels: size/L, team: workspace

#17840 [ws-manager-mk2] Log conflict errors as info
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/S, team: workspace

#17862 [db] Drop sessions table & db - WEB-106
  components/gitpod-db/src/tables.ts
  install/installer/pkg/components/database/incluster/init/01-create-and-init-sessions-db.sql
  install/installer/pkg/components/database/incluster/init/04-drop-sessions-db.sql
  install/installer/pkg/components/database/init/files/00-create-and-init-sessions-db.sql
  install/installer/pkg/components/database/init/files/02-drop-sessions-db.sql
Labels: size/M, team: webapp

#17852 Adjust filtering of usage entries
  components/dashboard/src/usage/UsageEntry.tsx
  components/dashboard/src/usage/UsageView.tsx
  components/dashboard/src/usage/download/transform-usage-record.ts
Labels: size/S, team: webapp

#17869 Add Bitbucket to Git Providers under Orgs – WEB-454
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/M, team: webapp

#17873 Add phone verification analytics events
  components/server/src/auth/verification-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17889 [server] Fix org git auth
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/jobs/org-only-migration-job.ts
  components/server/src/migration/user-to-team-migration-service.spec.db.ts
  components/server/src/migration/user-to-team-migration-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#17891 Fix /login/slug handling – WEB-458
  components/dashboard/src/login/SSOLoginForm.tsx
Labels: size/XS, team: webapp

#17882 cleaning up fragment usage
  components/dashboard/src/Login.tsx
  components/dashboard/src/admin/BlockedEmailDomains.tsx
  components/dashboard/src/admin/BlockedRepositories.tsx
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/admin/Property.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/admin/WorkspacesSearch.tsx
  components/dashboard/src/components/Button.tsx
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/components/Tooltip.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/components/toasts/Toast.tsx
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
  components/dashboard/src/onboarding/LinkedInBanner.tsx
  components/dashboard/src/projects/Events.tsx
  components/dashboard/src/projects/NewProject.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/dashboard/src/usage/UsageEntry.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/dashboard/src/whatsnew/WhatsNew-2021-06.tsx
  components/dashboard/src/whatsnew/WhatsNew.tsx
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
Labels: size/XXL, team: webapp

#17893 Fix logins into existing accounts
  components/server/src/auth/generic-auth-provider.ts
Labels: size/M, team: webapp

#17897 User.getPrimaryEmail to return email of SSO identity – WEB-437
  components/dashboard/src/user-settings/Account.tsx
  components/gitpod-protocol/src/protocol.ts
Labels: size/L, team: webapp

#17863 [preview] Enable network limiting
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/XS, team: workspace

#17903 Update VS Code Browser to `1.79.0`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE

#17856 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#17899 [ws-manager-mk2] Test prebuilds and imagebuilds
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
Labels: size/L, team: workspace, feature: ws-manager-mk2

#17767 [ws-manager-mk2] Configure max workspace lifetime
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/timeout_controller_test.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace

#17904 [dashboard] Always use Public API for workspace stop & delete
  components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
  components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
  components/dashboard/src/data/workspaces/stop-workspace-mutation.ts
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/M, team: webapp

#17905 [server] Store only User ID on WS connection instance - WEB-460
  components/server/src/user/user-controller.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: webapp

#17880 Return and show error when stopping workspace in maintenance mode
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
  components/gitpod-protocol/src/messaging/error.ts
  components/public-api-server/pkg/proxy/errors.go
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17910 Prefer experimental IDE options
  components/dashboard/src/components/SelectIDEComponent.tsx
Labels: component: dashboard, size/S

#17907 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17908 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17870 Remove unused workspace port auth
  components/gitpod-protocol/src/util/workspace-port-authentication.ts
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-token-validator.spec.ts
  components/server/src/bitbucket/bitbucket-context-parser.spec.ts
  components/server/src/bitbucket/bitbucket-file-provider.spec.ts
  components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
  components/server/src/dev/dev-data.ts
  components/server/src/github/github-file-provider.spec.ts
  components/server/src/gitlab/gitlab-app-support.spec.ts
  components/server/src/gitlab/gitlab-context-parser.spec.ts
  components/server/src/gitlab/gitlab-file-provider.spec.ts
  components/server/src/gitlab/gitlab-repository-provider.spec.ts
  components/server/src/prebuilds/bitbucket-server-service.spec.ts
  components/server/src/user/token-provider.ts
  components/server/src/user/token-service.ts
Labels: size/L, team: webapp

#17911 [server] allow debugging
  .vscode/launch.json
  components/server/debug.sh
  components/server/deploy.sh
  components/server/package.json
Labels: size/M, team: webapp

#17912 [gitpod-db] don't leak DBUser
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#17878 [test] Add integration test for exposing ports
  test/pkg/integration/workspace.go
  test/tests/workspace/ports_test.go
Labels: size/L, team: workspace, team: IDE

#17860 [ws-manager-mk2] Remove persistent volume claim feature
  components/content-service/pkg/initializer/prebuild.go
  components/content-service/pkg/layer/provider.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/workspacekit/cmd/rings.go
  components/ws-daemon-api/daemon.proto
  components/ws-daemon-api/go/daemon.pb.go
  components/ws-daemon-api/typescript/src/daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_pb.js
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/config/config.go
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/example-config.yaml
  install/installer/pkg/components/ws-manager-mk2/configmap.go
  install/installer/pkg/config/v1/config.go
  install/installer/pkg/config/v1/config.md
  install/installer/pkg/config/v1/experimental/experimental.go
  test/pkg/integration/apis.go
  test/tests/components/ws-manager/content_test.go
  test/tests/components/ws-manager/prebuild_test.go
  test/tests/components/ws-manager/tasks_test.go
  test/tests/workspace/git_hooks_test.go
  test/tests/workspace/git_test.go
Labels: size/XXL, team: workspace, team: IDE, feature: ws-manager-mk2

#17794 enrich workspace events
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: meta: never-stale, size/S, team: webapp

#17916 [ide-metrics] add counters for local-ssh proxy
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/M, team: IDE

#17923 [server] remove user relation from gitpod_token
  components/gitpod-db/src/typeorm/entity/db-gitpod-token.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/resource-access.ts
  components/server/src/user/user-controller.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: webapp

#17926 Use a script for BROWSER variable
  components/supervisor/BUILD.yaml
  components/supervisor/browser.sh
  components/supervisor/leeway.Dockerfile
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
Labels: size/S, team: IDE

#17906 [gitpod-db] cache user object
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/data-cache.ts
  components/gitpod-db/src/test-container.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/server/package.json
  components/server/src/auth/login-completion-handler.ts
  components/server/src/billing/billing-mode.spec.db.ts
  components/server/src/jobs/org-only-migration-job.spec.db.ts
  components/server/src/main.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/redis/data-cache.spec.ts
  components/server/src/redis/data-cache.ts
  components/server/src/test/authentication-github.spec.ts
  components/server/src/user/user-service.spec.db.ts
  components/ws-manager-bridge/ee/src/index.ts
  components/ws-manager-bridge/src/index.ts
  gitpod-ws.code-workspace
  yarn.lock
Labels: size/XXL

#17875 [papi] Extract JWT cookie when extracting creds
  components/public-api-server/pkg/apiv1/identityprovider_test.go
  components/public-api-server/pkg/apiv1/oidc_test.go
  components/public-api-server/pkg/apiv1/project_test.go
  components/public-api-server/pkg/apiv1/team_test.go
  components/public-api-server/pkg/apiv1/tokens_test.go
  components/public-api-server/pkg/apiv1/user_test.go
  components/public-api-server/pkg/apiv1/workspace_test.go
  components/public-api-server/pkg/auth/context.go
  components/public-api-server/pkg/auth/metrics.go
  components/public-api-server/pkg/auth/middleware.go
  components/public-api-server/pkg/auth/middleware_test.go
  components/public-api-server/pkg/auth/session_jwt.go
  components/public-api-server/pkg/server/server.go
Labels: size/XL, team: webapp

#17932 [dashboard] migration cleanups
  components/dashboard/src/Usage.tsx
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/admin/UserDetail.tsx
  components/dashboard/src/admin/WorkspaceDetail.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/BillingAccountSelector.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/UsageLimitReachedModal.tsx
  components/dashboard/src/data/billing-mode/user-billing-mode-query.ts
  components/dashboard/src/data/organizations/orgs-query.ts
  components/dashboard/src/data/workspaces/list-workspaces-query.ts
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
  components/dashboard/src/user-settings/Billing.tsx
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
  components/dashboard/src/user-settings/settings.routes.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XXL, team: webapp

#17921 Remove setup-gcloud from workspace integration tests workflow
  .github/workflows/workspace-integration-tests.yml
Labels: size/S, team: workspace

#17934 [scrubber] various fixes
  components/scrubber/scrubber.go
  components/scrubber/scrubber_test.go
Labels: size/L

#17936 [server] add organizationId to old workspaces
  components/server/src/jobs/org-only-migration-job.spec.db.ts
  components/server/src/jobs/org-only-migration-job.ts
Labels: size/L, team: webapp

#17640 Improve git integrations during user onboarding
  components/dashboard/src/components/AuthorizeGit.tsx
Labels: size/XS, team: webapp

#17940 [registry-facade] Use resolverProvider for static layers
  components/registry-facade/pkg/registry/layersource.go
  components/registry-facade/pkg/registry/layersource_test.go
  components/registry-facade/pkg/registry/registry.go
Labels: size/S, team: workspace

#17929 Don't change editor/ws class values if user has modified them
  components/dashboard/src/components/DropDown2.tsx
  components/dashboard/src/hooks/use-dirty-state.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: webapp

#17930 [obs] setup better names for alert rules
  operations/observability/mixins/IDE/rules/vscode.yaml
  operations/observability/mixins/meta/rules/content-service.yaml
Labels: size/XS, team: webapp, team: IDE

#17946 [server] Cache refreshes TTL on cache hit
  components/server/src/redis/data-cache.ts
Labels: size/XS, team: webapp

#17945 [usage] restore previous spending Limit
  components/gitpod-db/go/cost_center.go
  components/gitpod-db/go/cost_center_test.go
Labels: size/L, team: webapp

#17949 [gpctl] Use mk2 tls by default
  dev/gpctl/cmd/clusters-gettlsconfig.go
  dev/gpctl/cmd/workspaces.go
  dev/loadgen/README.md
Labels: size/XS, team: workspace

#17951 [server] fix stripe job
  components/server/src/jobs/fix-stripe-job.ts
  components/server/src/user/stripe-service.ts
Labels: size/S, team: webapp

#17948 [job] drop job state feature
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/typeorm/entity/db-job-state.ts
  components/gitpod-db/src/typeorm/job-state-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/job-state-db-impl.ts
  components/gitpod-db/src/typeorm/migration/1686817846678-DropJobState.ts
  components/server/src/jobs/org-only-migration-job.spec.db.ts
  components/server/src/jobs/org-only-migration-job.ts
  components/server/src/jobs/runner.ts
Labels: size/L, team: webapp

#17924 [ws-manager-mk2] Simplify workspace session management
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-daemon/pkg/controller/workspace_provider.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-daemon/pkg/internal/session/store.go
  components/ws-daemon/pkg/internal/session/store_test.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/internal/session/workspace_test.go
Labels: size/XXL, team: workspace, feature: ws-manager-mk2

#17950 [wsman-mk2] Change default class to g1-standard
  components/ws-manager-api/go/config/config.go
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/S, team: workspace

#17941 [obs] remove ws-manager (mk1) alert references
  operations/observability/mixins/workspace/rules/central/workspacefailure-SLO.yaml
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
  operations/observability/mixins/workspace/rules/satellite/ws-daemon.yaml
Labels: size/L, team: workspace

#17944 [obs] Fix workspace alerts to work in Grafana cloud
  operations/observability/mixins/workspace/rules/central/workspaces.yaml
  operations/observability/mixins/workspace/rules/central/ws-daemon.yaml
  operations/observability/mixins/workspace/rules/central/ws-manager.yaml
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
  operations/observability/mixins/workspace/rules/satellite/ws-daemon.yaml
Labels: size/S, team: workspace

#17952 [wsman-bridge] Remove worksplace classes feature flag
  components/ws-manager-bridge/src/cluster-service-server.ts
  components/ws-manager-bridge/src/cluster-sync-service.ts
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/main.ts
Labels: size/L, team: webapp

#17831 Allow user env vars for GitLab subgroups
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/user-env-var.spec.ts
  components/server/src/auth/resource-access.ts
  components/server/src/workspace/env-var-service.spec.ts
Labels: size/XL, team: webapp

#17958 Update VS Code Browser to `1.79.2`
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: editor: code (browser), size/XS, team: IDE

#17961 [ws-manager-mk2] Simplifiy condition checking
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/pkg/activity/activity.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: workspace

#17956 Show User ID on Account page
  components/dashboard/src/user-settings/Account.tsx
Labels: component: dashboard, size/S, team: webapp

#17933 [common-go] Avoid "bind: address already in use" during tests
  components/common-go/baseserver/testing.go
Labels: size/S, team: webapp, team: staff-engineers

#17937 [spicedb] Upgrade to v1.22.0 WEB-412
  install/installer/pkg/components/spicedb/constants.go
Labels: size/XS, team: webapp

#17938 [spicedb] Add CI validation check WEB-476
  .github/workflows/authorization.yml
Labels: size/S

#17918 [server] Remove dead permissions code
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/permission.ts
  components/server/src/user/authorization-service.spec.ts
  components/server/src/user/user-controller.ts
  components/ws-manager-api/typescript/src/client-provider.spec.ts
  install/installer/pkg/components/ws-manager-bridge/types.go
Labels: size/L, team: webapp, team: workspace

#17964 [ws-manager-mk2] Cleanup mk1 from workflow inputs and tests
  .github/workflows/build.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/workspace-integration-tests.yml
  test/README.md
  test/pkg/integration/apis.go
  test/pkg/integration/setup.go
  test/tests/components/ws-manager/protected_secrets_test.go
Labels: size/M, team: workspace, team: IDE

#17973 [spicedb] Initial schema with projects
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/L, team: webapp

#17976 Code-nightly -> `gp-code/main`
  .github/workflows/code-nightly.yml
Labels: size/XS, team: IDE

#17971 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains

#17972 [server] mark orphaned instances stopped
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: webapp

#17920 Prepare for gen100
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: workspace

#17979 [server] Remove mayStartWorkspaceOnRepo
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XS, team: webapp

#17947 [usage] compute correct spending limit
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/gitpod-db/go/cost_center.go
  components/gitpod-db/go/cost_center_test.go
  components/gitpod-db/src/typeorm/migration/1686907204398-FreeCredits.ts
  components/server/src/user/user-service.ts
Labels: size/L, team: webapp

#17953 [test] Add test for fuse device
  test/pkg/integration/fuse.go
  test/tests/components/ws-daemon/fuse_device_test.go
Labels: size/L, team: workspace, team: IDE

#17974 [test] Add test for process limit
  dev/preview/workflow/preview/deploy-gitpod.sh
  test/pkg/integration/integration.go
  test/pkg/integration/workspace.go
  test/tests/workspace/process_limit_test.go
Labels: size/L, team: workspace, team: IDE

#17970 Avoid label truncation on the integration buttons
  components/dashboard/src/components/AuthorizeGit.tsx
Labels: size/XS, team: webapp

#17986 [test] Speed up setup, debug and disable k3s
  test/README.md
  test/pkg/integration/setup.go
  test/tests/workspace/k3s_test.go
Labels: size/L, team: workspace, team: IDE

#17987 [perms] Align perm checks with permissions in model
  components/server/src/authorization/checks.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17981 [server] Remove hasPermission rpc
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: webapp

#17989 [perms] Add constants and types for resources and perms
  components/server/src/authorization/checks.ts
  components/server/src/authorization/definitions.ts
  components/server/src/authorization/perms.ts
Labels: size/S, team: webapp

#17991 [perms] Helpers for relationship, object ref and subject
  components/server/src/authorization/checks.ts
  components/server/src/authorization/definitions.ts
Labels: size/M, team: webapp

#17990 [server] Remove hasPermission from go API client
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
Labels: size/M, team: webapp

#17963 [observability] add dashboard for local ssh IDE-154
  operations/observability/mixins/IDE/dashboards.libsonnet
  operations/observability/mixins/IDE/dashboards/components/local-ssh.json
Labels: size/XXL, team: IDE

#17877 Update Ports View to bring ability to change port forward protocol IDE-150
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: IDE

#17854 [test] update convenience script to manually run tests & remove werft test scripts/references
  .werft/jobs/build/trigger-integration-tests.ts
  .werft/workspace-run-integration-tests.sh
  .werft/workspace-run-integration-tests.yaml
  test/.gitignore
  test/run.sh
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/XL, team: workspace

#17995 [test] Update slack msg to include nr skipped
  .github/workflows/workspace-integration-tests.yml
  test/run.sh
Labels: size/XS, team: workspace

#17985 [ws-proxy] Return last instance if multiple instances are found
  components/ws-proxy/pkg/proxy/infoprovider.go
Labels: size/S, team: workspace

#17997 [workspace] Update regular not active alert
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: workspace

#17980 [db, ts] Introduce a generic db.transaction()
  components/content-service-api/typescript/package.json
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-db/src/typeorm/transactional-db-impl.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-protocol/package.json
  components/image-builder-api/typescript/package.json
  components/server/package.json
  components/server/src/container-module.ts
  components/server/src/user/user-service.spec.db.ts
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  components/ws-manager-bridge/package.json
  yarn.lock
Labels: size/XXL, team: webapp, team: workspace

#17983 Remove getContentBlob Upload/Download URL
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/gitpod-protocol/src/gitpod-service.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  test/tests/components/content-service/content-service_test.go
Labels: size/L, team: webapp, team: workspace

#18005 Rename copy user ID tooltip
  components/dashboard/src/user-settings/Account.tsx
Labels: size/XS, team: webapp

#17996 [test] Fix flakes and speed up prebuild tests
  test/pkg/integration/workspace.go
  test/tests/components/ws-manager/content_test.go
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/L, team: workspace, team: IDE

#17939 [server] clean up org-only migration code
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-db/src/project-db.spec.db.ts
  components/gitpod-db/src/typeorm/entity/db-project.ts
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/user-db.spec.db.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-protocol/src/attribution.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/auth/resource-access.spec.ts
  components/server/src/billing/billing-mode.spec.db.ts
  components/server/src/billing/billing-mode.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/container-module.ts
  components/server/src/jobs/fix-stripe-job.spec.db.ts
  components/server/src/jobs/fix-stripe-job.ts
  components/server/src/jobs/org-only-migration-job.spec.db.ts
  components/server/src/jobs/org-only-migration-job.ts
  components/server/src/jobs/runner.ts
  components/server/src/migration/user-to-team-migration-service.spec.db.ts
  components/server/src/migration/user-to-team-migration-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/user/stripe-service.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: webapp

#17998 `gp ssh`
  components/gitpod-cli/cmd/ssh.go
Labels: component: gp cli, size/M, team: IDE

#18014 [db] check if table exists before creating
  components/gitpod-db/src/typeorm/migration/1686907204398-FreeCredits.ts
Labels: size/XS, team: webapp

#18012 [db] Make Team DB transactional
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
Labels: size/S, team: webapp

#18004 [perms] Simplify guard operations
  components/server/src/authorization/perms.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: webapp

#18018 [db] some cleanups for db impls
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/transactional-db-impl.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/L, team: webapp

#18022 Add longest running reconcile to dashboards
  operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
  operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json
Labels: size/XL, team: workspace

#18017 [ws-daemon] Add OWI to logs
  components/ws-daemon/cmd/run.go
  components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
  components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go
  components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
  components/ws-daemon/pkg/cgroup/plugin_psi.go
  components/ws-daemon/pkg/container/containerd.go
  components/ws-daemon/pkg/content/hooks.go
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-daemon/pkg/netlimit/netlimit.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
Labels: size/L, team: workspace

#18016 [perms] check for read/write permissions on orgs – WEB-512
  components/server/src/authorization/checks.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/M, team: webapp

#17935 Remove hostname from callback URL – WEB-398
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/user-settings/Integrations.test.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/authenticator.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/express.ts
Labels: size/L, team: webapp

#18009 Fix tab navigation for `InputWithCopy`
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/index.css
Labels: component: dashboard, size/S, team: webapp, aspect: accessibility

#18010 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/installation-telemetry/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, team: webapp, team: workspace, team: IDE, release-note-none, team: security-infrastructure-and-delivery, automated pr, kind/cleanup

#18021 [perms] Everyone has member in an org, plus they can have owner
  components/server/src/authorization/definitions.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/M, team: webapp

#18029 [configcat] use internal route
  components/proxy/conf/Caddyfile
  install/installer/pkg/common/common.go
  install/installer/pkg/common/constants.go
  install/installer/pkg/components/ide-service/constants.go
  install/installer/pkg/components/openvsx-proxy/constants.go
  install/installer/pkg/components/proxy/constants.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/proxy/networkpolicy.go
  install/installer/pkg/components/proxy/service.go
Labels: size/M, team: webapp, team: IDE

#18033 [dashboard] retry useUserQuery if error code is not 401 – WEB-560
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/hooks/use-user-loader.ts
Labels: size/S, team: webapp

#18027 [server] make members private
  components/server/src/user/user-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XL, team: webapp

#18035 [test] Fix tests, set team spending limit
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/XS, team: webapp, team: workspace

#18023 [usage] cleanup after org-only mig
  components/gitpod-db/go/cost_center_test.go
  components/gitpod-db/go/dbtest/cost_center.go
  components/gitpod-db/go/dbtest/stripe_customer.go
  components/gitpod-db/go/dbtest/usage.go
  components/gitpod-db/go/dbtest/workspace_instance.go
  components/gitpod-db/go/stripe_customer_test.go
  components/gitpod-db/go/usage_test.go
  components/gitpod-db/go/workspace_instance.go
  components/gitpod-db/go/workspace_instance_test.go
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/apiv1/billing_test.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/stripe/stripe_test.go
Labels: size/L, team: webapp

#17993 [perms] Grant owner/member on role change WEB-505, WEB-507
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/server/src/authorization/perms.ts
  components/server/src/authorization/relationships.ts
  components/server/src/container-module.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: webapp

#18030 Keep search input visible when scrolling on the repository and editor dropdown
  components/dashboard/src/components/DropDown2.tsx
Labels: size/XS, team: webapp

#18008 [perms] Check & Update relationships on removeTeamMember WEB-508
  components/server/src/authorization/checks.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/M, team: webapp

#18038 [db] allow nesting transactions
  components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-db/src/typeorm/transactional-db-impl.ts
Labels: size/M, team: webapp

#18036 [perms] Remove duplicate CI check
  .github/workflows/permissions.yml
Labels: size/S

#18026 [preview] Disable fail-fast and limit parallel jobs to 1
  .github/workflows/preview-env-gc.yml
Labels: size/XS

#18042 Fix supervisor ssh tunnel close stale connection
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XS, team: IDE

#17843 Remove welcome page check
  components/dashboard/src/Login.tsx
Labels: size/S, team: webapp

#18037 [perms] Project and org relations
  components/server/src/authorization/relationships.ts
  components/server/src/projects/projects-service.ts
Labels: size/M, team: webapp

#18048 [usage] reduce log noise
  components/usage/pkg/scheduler/scheduler.go
Labels: size/XS, team: webapp

#18032 openvsx proxy clean up domain
  components/openvsx-proxy/pkg/config.go
  components/openvsx-proxy/pkg/openvsxproxy_test.go
  install/installer/pkg/components/openvsx-proxy/configmap.go
Labels: size/XS, team: webapp, team: IDE

#18041 [server] Guard org authProvider-related API calls centralizedPermissions
  components/server/src/authorization/checks.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/gitpod-server-impl.ts
  install/installer/pkg/components/spicedb/data/schema.yaml
Labels: size/M, team: webapp
