Repository gitpod-io/gitpod, pull requests merged in 2024-05, with the labels that each got.

#19695 [ws-manager-mk2] allow the k8s client a higher limit
  components/ws-manager-mk2/main.go
Labels: size/S, team: team-engine

#19687 Deal with clipboard permission issues
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/utils.ts
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/L, team: team-experience

#19697 [dashboard] don't select non-selectable element
  components/dashboard/src/components/podkit/combobox/Combobox.tsx
Labels: size/XS, team: team-experience

#19630 [supervisor] remove JAVA_TOOL_OPTIONS hack
  components/common-go/experiments/flags.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
Labels: size/M, team: staff-engineers, team: team-experience

#19698 [ws-manager-mk2] Make WorkspaceRunningCondition.LastTransitionTime stable
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-mk2/controllers/status.go
Labels: size/M, team: team-engine

#19699 [bridge] Remember last status update, and skip if they are identical
  components/gitpod-protocol/src/protocol.ts
  components/ws-manager-bridge/src/bridge.spec.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/metrics.ts
Labels: size/L, team: team-experience

#19688 [.github] integration test comments
  .github/workflows/workspace-integration-tests.yml
Labels: size/XS

#19701 Allow setting default role for new joiners
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/teams/Members.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1714741006746-OrgSettingDefaultRole.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
Labels: size/L, team: team-experience

#19665 Add integration tests for JetBrains backend plugin
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/L, team: team-experience

#19702 [obs] a couple QOL improvements
  operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
  operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
Labels: size/L, team: team-experience

#19603 Remove direct support link from phone verification modal
  components/dashboard/src/start/VerifyModal.tsx
Labels: size/S, team: team-experience

#19704 [code] build stable code `1.89.0`
  WORKSPACE.yaml
Labels: size/XS

#19706 [code] upgrade Browser VS Code to 1.89.0
  .github/workflows/code-nightly.yml
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: team-experience

#19705 [server] Don't ask for new access token if workspace is already starting
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience

#19708 [server] Fix mistaken re-classification of workspace start errors
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: team-experience

#19692 [test] fix integration tests
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/variables.tf
  dev/preview/workflow/preview/deploy-gitpod.sh
  test/tests/components/ws-manager/prebuild_test.go
  test/tests/workspace/process_priority_test.go
Labels: size/S, team: team-experience, team: team-engine

#19726 Build code 1.89.1
  WORKSPACE.yaml
Labels: size/XS

#19728 Fix regular IDE integration tests
  components/gitpod-protocol/go/gitpod-service.go
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/XS, team: team-experience

#19731 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience

#19724 Upgrade gha `create-pull-request` to `v6`
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  .github/workflows/jetbrains-updates.yml
Labels: size/XS, team: team-experience

#19729 [code] upgrade Browser VS Code to 1.89.1
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: team-experience

#19715 Opportunistic token refresh (for BitBucket Server)
  components/gitpod-db/src/typeorm/entity/db-token-entry.ts
  components/gitpod-db/src/typeorm/migration/1715096375962-TokenReservedUntil.ts
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/gitpod-db/src/user-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/auth/auth-provider.ts
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/user/token-provider.ts
  components/server/src/user/token-service.spec.db.ts
  components/server/src/user/token-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience

#19733 [server] listWorkspaceSessions API
  components/dashboard/src/service/json-rpc-workspace-client.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/v1connect/workspace.connect.go
  components/public-api/go/v1/v1connect/workspace.proxy.connect.go
  components/public-api/go/v1/workspace.pb.go
  components/public-api/go/v1/workspace_grpc.pb.go
  components/public-api/typescript-common/fixtures/toBlockedRepository_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.json
  components/public-api/typescript-common/fixtures/toWorkspace_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace_4.golden
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_connect.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/authorization/definitions.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience

#19710 Build - make backend-plugin readiness a condition of JetBrains IDEs readiness
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
  components/ide/jetbrains/launcher/go.mod
  components/ide/jetbrains/launcher/go.sum
  components/ide/jetbrains/launcher/main.go
  components/supervisor/cmd/init.go
  components/supervisor/hot-deploy.sh
  components/supervisor/pkg/metrics/metrics.go
  components/supervisor/pkg/shared/constant.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: team-experience

#19743 Update JetBrains launcher image
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/M, team: team-experience

#19727 Add `scope` flag to idp commands
  components/gitpod-cli/cmd/idp-gcloud-token.go
  components/gitpod-cli/cmd/idp-login-aws.go
  components/gitpod-cli/cmd/idp-login-vault.go
  components/gitpod-cli/cmd/idp-login.go
  components/gitpod-cli/cmd/idp-token.go
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
  components/public-api-server/pkg/identityprovider/idp_test.go
  components/public-api/gitpod/experimental/v1/identityprovider.proto
  components/public-api/go/experimental/v1/identityprovider.pb.go
  components/public-api/typescript/src/gitpod/experimental/v1/identityprovider_pb.ts
Labels: size/L, team: team-experience

#19746 [GHA] add VS Code Browser release
  .github/workflows/build.yml
  .github/workflows/code-build.yaml
  .github/workflows/code-updates.yml
  components/ide/code/gha-update-image/check-code-build.ts
  components/ide/code/gha-update-image/index.ts
  components/ide/code/gha-update-image/lib/common.ts
  components/ide/code/gha-update-image/package.json
  components/ide/code/gha-update-image/yarn.lock
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XXL, team: team-experience

#19745 [image-builder] Fix ignoring of user-passed authentication
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience, team: team-engine

#19718 [dev] Make Team Enterprise co-own everything
  .github/CODEOWNERS
Labels: size/L, team: leadership

#19748 Switch to new instance when instanceId updated
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19747 [bridge] add healthz endpoint
  components/ws-manager-bridge/src/healthz.ts
  components/ws-manager-bridge/src/main.ts
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/M, team: team-experience, team: team-enterprise

#19734 [image-builder-mk3] Improve logging and tracing for build
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/image-builder-mk3/pkg/resolve/resolve.go
  dev/gpctl/cmd/imagebuilds-build-batch.go
  dev/gpctl/cmd/imagebuilds-list.go
  gitpod-ws.code-workspace
Labels: size/M, team: team-engine, team: team-enterprise

#19749 [obs] alert on-call when ws-manager-bridge events received is too high
  operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Labels: size/S, team: team-experience, team: team-enterprise

#19752 [obs] Opt WsManagerBridgeHighEventsReceived into Enterprise alering
  operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Labels: size/XS, team: team-experience, team: team-enterprise

#19751 [jb] bring more compatibility to cwm joinLink
  components/ide/jetbrains/launcher/main.go
Labels: size/S, team: team-experience, team: team-enterprise

#19753 [obs] fix startup time panels
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/M, team: team-enterprise

#19750 [server] Fix mis-reporting of errors as "success" (in addition)
  components/server/src/user/token-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19755 Improve product onboarding form
  components/dashboard/src/components/forms/CheckboxInputField.tsx
  components/dashboard/src/onboarding/OnboardingStep.tsx
  components/dashboard/src/onboarding/StepOrgInfo.tsx
  components/dashboard/src/onboarding/exploration-reasons.ts
  components/dashboard/src/onboarding/signup-goals.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19754 Update JetBrains launcher to latest version
  components/ide/jetbrains/image/gha-update-image/lib/pin-version.ts
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: team-experience, team: team-enterprise

#19759 Fix code GitHub actions
  .github/workflows/code-build.yaml
  .github/workflows/code-updates.yml
  components/ide/code/gha-update-image/check-code-build.ts
  components/ide/code/gha-update-image/index.ts
  components/ide/code/gha-update-image/lib/common.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19761 Add openvscode-server release in code update GHA
  .github/workflows/code-build.yaml
  .github/workflows/code-nightly.yml
  .github/workflows/code-updates.yml
Labels: size/XL, team: team-experience, team: team-enterprise

#19764 [dashboard] only send close heartbeat when web IDEs are closed
  components/dashboard/src/service/service.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#19763 Updata code build image
  components/ide/code/leeway.Dockerfile
Labels: size/S, team: team-experience, team: team-enterprise

#19769 [dashboard] don't show add org in dedicated
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#19768 Remove token refresh feature flags
  components/server/src/user/token-service.spec.db.ts
  components/server/src/user/token-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19775 [PAYG - dashboard] Add Gitpod Enterprise callout in New workspace component
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19777 [PAYG-dashboard] Add Gitpod Enterprise callout on login page for PAYG users
  components/dashboard/src/Login.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19774 [supervisor] Fix race on terminal listener closing
  components/supervisor/pkg/terminal/terminal.go
Labels: size/XS, team: team-experience, team: team-enterprise

#19770 [server, ws-proxy] Test cookie filter against real name generator
  components/server/go/BUILD.yaml
  components/server/go/go.mod
  components/server/go/go.sum
  components/server/go/pkg/lib/cookie.go
  components/ws-proxy/BUILD.yaml
  components/ws-proxy/go.mod
  components/ws-proxy/pkg/proxy/routes_test.go
  install/installer/BUILD.yaml
  install/installer/go.mod
  install/installer/pkg/components/auth/config.go
  install/installer/pkg/components/auth/config_test.go
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#19772 [JetBrains] improve tasks' terminals
  components/ide/jetbrains/backend-plugin/hot-deploy.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/internal/GitpodTerminalServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/L, team: team-experience, team: team-enterprise

#19778 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  .github/workflows/build.yml
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19779 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19782 [bridge] Fix logging/bridge.stop
  components/ws-manager-bridge/src/bridge-controller.ts
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
  components/ws-manager-bridge/src/wsman-subscriber.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19773 [ws-proxy] Filter cookies on all routes that send traffic to the workspace (except supervisor)
  components/ws-proxy/pkg/proxy/auth_test.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: size/M, team: team-engine, team: team-enterprise

#19776 WorkspaceStarter: fix + cleanup error handling
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19781 [server] eagerly fetch config files in parallel
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/config/config-inferrer.spec.ts
  components/server/src/config/config-inferrer.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19771 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19790 [Organization settings] Bisect General settings
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/components/podkit/buttons/LinkButton.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/XXL, do-not-merge/hold, team: team-experience, team: team-enterprise

#19794 [dashboard] Add Organization Networking settings page
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/teams/TeamNetworking.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
Labels: size/L, do-not-merge/hold, team: team-experience, team: team-enterprise

#19793 [dashboard] Add owner check to `/billing` page
  components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#19789 set visitor prefence cookies of website on signup if no previous selection has been made
  components/server/src/auth/generic-auth-provider.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19798 [PAYG-dashboard] Enterprise callout in Invite members modal for all PAYG users
  components/dashboard/src/teams/Members.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19797 [dashboard] Don't lowercase context URLs
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19792 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#19799 [dashboard] tell users to verify by signing up
  components/dashboard/src/start/VerifyModal.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#19800 [dashboard] StartWorkspace modal: Ctrl+Enter as shortcut for "Continue"
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19791 Tolerate GPU taint
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: team: team-engine, team: team-enterprise

#19801 Provide option to disable fuse device
  components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19803 [server] SpiceDB: try up to 3 times not only for INTERNAL, but also DEADLINE_EXCEEDED
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19805 [JetBrains] support new cwm response format
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: team-experience, team: team-enterprise

#19788 [dashboard] Restructure Organization Settings
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/PageWithSubMenu.tsx
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/components/podkit/buttons/LinkButton.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/TeamAuthentication.tsx
  components/dashboard/src/teams/TeamNetworking.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
Labels: size/XXL, team: team-experience, team: team-enterprise

#19811 [GP-CLI] fix incorrect pre-configured workspace image for enterprise
  components/gitpod-cli/cmd/init.go
  components/gitpod-cli/pkg/gitpodlib/config.go
Labels: size/S, team: team-experience, team: team-enterprise

#19806 [dashboard] Fix queries useOrgSettings/useConfiguration
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/ide-options/ide-options-query.ts
  components/dashboard/src/data/organizations/org-settings-query.ts
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#19812 [server] allow fetching task specific prebuild-logs
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/gitpod-db/src/typeorm/workspace-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/headless-log-controller.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19786 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19815 Fix main build golden tests
  components/public-api/typescript-common/fixtures/toPrebuild_1.golden
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19813 Bring more compatibility to OIDC verification
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
Labels: size/M, team: team-experience, team: team-enterprise

#19818 Increase the contrast of dashboard log view
  components/dashboard/src/components/WorkspaceLogs.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#19810 Cap length of GitStatus updates
  components/server/src/workspace/workspace-service.ts
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/serverapi/publicapi_test.go
Labels: size/L, team: team-experience, team: team-enterprise

#19814 [server] Introduce job CapGitStatus
  components/gitpod-db/src/periodic-deleter.ts
  components/server/src/authorization/relationship-updater-job.ts
  components/server/src/container-module.ts
  components/server/src/jobs/cap-git-status.ts
  components/server/src/jobs/database-gc.ts
  components/server/src/jobs/installation-admin-cleanup.ts
  components/server/src/jobs/ots-gc.ts
  components/server/src/jobs/runner.ts
  components/server/src/jobs/snapshots.ts
  components/server/src/jobs/token-gc.ts
  components/server/src/jobs/webhook-gc.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-start-controller.ts
Labels: size/L, team: team-experience, team: team-enterprise
