Repository gitpod-io/gitpod, pull requests merged in 2024-03, with the labels that each got.

#19492 Fix new workspace page re-render loop and false negative error message for ws class
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/WorkspaceClassesOptions.tsx
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/repositories/detail/workspaces/ConfigurationWorkspaceClassesOptions.tsx
Labels: size/L, team: team-experience

#19497 [scrubber] Scrub URL path parts separately
  components/scrubber/config.go
  components/scrubber/sanitisation.go
  components/scrubber/sanitisation_test.go
  components/scrubber/scrubber.go
  components/scrubber/scrubber_test.go
Labels: size/L

#19491 [code] Update code to 1.87.0
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19502 [obs] fix alerts for workspace deployments
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
  operations/observability/mixins/workspace/rules/central/node-labeler.yaml
  operations/observability/mixins/workspace/rules/central/ws-manager.yaml
  operations/observability/mixins/workspace/rules/central/ws-proxy.yaml
Labels: size/XS, team: team-engine

#19501 Do not flash unknown prebuild status
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/S, team: team-experience

#19506 [server] Remove feature flags and cleanup dead code in TokenService
  components/server/src/user/token-service.ts
Labels: size/M, team: team-experience

#19509 Add db migration for org-level default editor
  components/gitpod-db/src/typeorm/migration/1709709649212-AddOrgSettingsDefaultEditor.ts
Labels: size/S, team: team-experience

#19507 Allow running prebuilds on a specific branch
  components/dashboard/src/components/InputWithCopy.tsx
  components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
  components/server/src/api/prebuild-service-api.ts
  components/server/src/prebuilds/prebuild-manager.ts
Labels: size/M, team: team-experience

#19516 Increase frequency of the gc job
  install/installer/pkg/components/server/configmap.go
Labels: size/XS, team: team-experience

#19514 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19515 Dismiss persisted toast on prebuild detail page
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/S, team: team-experience

#19510 Add pinnedEditorVersions db migration
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1709626232691-AddPinnedEditorVersions.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
Labels: size/M, team: team-experience

#19513 Add ide versions in ide-service
  components/ide-service-api/go/config/ideconfig.go
  components/ide-service-api/go/ide_grpc.pb.go
  components/ide-service-api/typescript/src/ide.pb.ts
  components/ide-service/example-ide-config.json
  components/ide-service/pkg/server/server.go
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.json
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.json
Labels: size/L, team: team-experience

#19517 Fix freshly authed SCMs on the new workspace page
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: team-experience

#19522 Alert for high load average on headless nodes
  operations/observability/mixins/workspace/rules/central/nodes.yaml
Labels: size/S, team: team-engine

#19524 Add panel for headless nodes
  operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Labels: size/L, team: team-engine

#19539 [server] reduce false positive alerting
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/XS, team: team-experience

#19523 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19520 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19518 Fix handling multiple repos with same context URL
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/suggested-repositories-query.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
  components/dashboard/src/projects/create-project-modal/CreateProjectModal.tsx
  components/dashboard/src/repositories/create/AddRepositoryModal.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/public-api/gitpod/v1/scm.proto
  components/public-api/go/v1/scm.pb.go
  components/public-api/typescript/src/gitpod/v1/scm_pb.ts
  components/server/src/api/scm-service-api.ts
  components/server/src/scm/scm-service.ts
  components/server/src/workspace/suggested-repos-sorter.spec.ts
  components/server/src/workspace/suggested-repos-sorter.ts
Labels: size/L, team: team-experience

#19545 [obs] temporarily reduce alert frequency
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine

#19538 Fix configuration input with preset value
  components/dashboard/src/prebuilds/configuration-input/ConfigurationInput.tsx
Labels: size/XS, team: team-experience

#19548 Make sure to refetch ws ctx after `AuthorizeGit`
  components/dashboard/src/components/AuthorizeGit.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: team-experience

#19551 [dashboard] update login screen and autostart
  components/dashboard/src/Login.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XL, team: team-experience

#19479 Add pin editor version
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/ide-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/auth/rate-limiter.ts
  components/server/src/ide-service.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/util/objects.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/XXL, team: team-experience

#19549 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19550 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19546 Fix papi failed to convert with `wsi.conditions` undefined
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/XS, team: team-experience

#19537 [ws-manager-mk2] Add workspace reconciler tracing
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/service/manager.go
Labels: size/M, team: team-engine

#19532 [code] Update code 1.87.1
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: team-experience

#19552 Parse context URLs when creating configurations
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/workspace/context-service.ts
Labels: size/S, team: team-experience

#19555 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19547 Respond bad_request with reserved env var name prefix `GITPOD_`
  components/gitpod-protocol/src/protocol.ts
  components/server/src/user/env-var-service.ts
Labels: size/M, team: team-experience

#19558 Ensure valid repository tie when listing prebuilds
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/gitpod-db/src/typeorm/workspace-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/L, team: team-experience

#19562 Fix line heights for `<h1>`s (#19559)
  components/dashboard/src/components/typography/headings.tsx
Labels: size/XS, team: team-experience

#19568 [observability] increase dashboard pods readiness check duration
  operations/observability/mixins/meta/rules/dashboard.yaml
Labels: size/XS, team: team-experience

#19564 Add repo-level editor restriction
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/data/ide-options/ide-options-query.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailEditors.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/editors/ConfigurationWorkspaceEditorsOptions.tsx
  components/dashboard/src/repositories/repositories.routes.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/projects/projects-service.ts
Labels: size/XL, team: team-experience

#19566 Unify prebuild status indicators
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/M, team: team-experience

#19569 Improve dashboard editor restriction settings
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/M, team: team-experience

#19570 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19527 remove repetitive words
  components/gitpod-db/go/cost_center.go
  components/registry-facade/pkg/registry/registry.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-manager-mk2/service/manager.go
  dev/preview/ssh-vm.sh
  test/tests/components/ws-manager/prebuild_test.go
Labels: size/S

#19572 Rebuild dev-image for go v1.22
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/lacework-inline-scanner.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  components/public-api/typescript-common/fixtures/toWorkspace2_2.json
  components/supervisor/openssh/BUILD.yaml
  components/supervisor/openssh/leeway.Dockerfile
  dev/image/Dockerfile
Labels: size/M, team: team-experience, team: team-engine

#19573 Use custom runner for JetBrains auto update GHA
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-auto-update.yml
Labels: size/L, team: team-experience

#19579 White list `GITPOD_IMAGE_AUTH` env var name
  components/gitpod-protocol/src/protocol.ts
  components/server/src/user/env-var-service.ts
Labels: size/XS, team: team-experience

#19567 Introduce `/quickstart`
  components/dashboard/src/App.tsx
  components/dashboard/src/components/QuickStart.tsx
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/provider-utils.tsx
  components/gitpod-protocol/src/util/gitpod-cookie.ts
Labels: size/L, team: team-experience

#19561 Let prebuilds be cancelled
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/server/src/prebuilds/prebuild-manager.ts
Labels: size/L, team: team-experience

#19576 Update ws-daemon gcloud dependency and runc
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS

#19582 Align base image of GHA
  .github/workflows/jetbrains-auto-update-template.yml
Labels: size/XS, team: team-experience

#19575 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19581 Fix inconsistent autostart data on ws creation
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/S, team: team-experience

#19583 Fix breadcrumb padding
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
Labels: size/XS, team: team-experience

#19584 Align design to editor icon and breadcrumb
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
Labels: size/XS, team: team-experience
