Repository gitpod-io/gitpod, pull requests merged in 2024-01, with the labels that each got.

#19287 [ws-manager-api] remove unused SSHKey field
  components/ws-manager-api/README.md
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
Labels: size/M, team: team-engine

#19303 [usage] track email for free allowance
  components/gitpod-db/go/cost_center.go
  components/gitpod-db/go/cost_center_test.go
  components/gitpod-db/src/typeorm/migration/1704350022475-TrackEmailForFreeCredits.ts
  components/gitpod-protocol/go/gitpod-config-types.go
Labels: size/L, team: team-experience

#19288 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19295 Make `gitpod org get` use the context's org by default
  components/local-app/CHANGELOG.md
  components/local-app/cmd/organization-get.go
Labels: size/XS, team: team-experience

#19297 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19292 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19304 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS

#19308 Fix integration tests workflow run list
  .github/workflows/workspace-integration-tests.yml
Labels: size/XS, team: team-engine

#19306 Fix button gap
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/XS, team: team-experience

#19310 [UX] Refactor Tab menu styles to highlight active state
  components/dashboard/src/components/TabMenuItem.tsx
Labels: size/XS, team: team-experience

#19318 [server] fix can not join org
  components/server/src/orgs/organization-service.ts
Labels: size/S, team: team-experience

#19319 [server] fix db tests with test ctx wrap
  components/server/src/auth/auth-provider-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/gitpod-token-service.spec.db.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/workspace-service.spec.db.ts
Labels: size/M, team: team-experience

#19314 Redirect on workspace stop
  components/dashboard/src/service/service.tsx
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  components/supervisor/frontend/src/shared/index.css
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/M, team: team-experience

#19321 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19322 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19323 Revert "Redirect on workspace stop"
  components/dashboard/src/service/service.tsx
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  components/supervisor/frontend/src/shared/index.css
  components/supervisor/frontend/src/shared/loading-frame.ts
Labels: size/M, team: team-experience

#19317 [observability] update dashboard not all ready alert
  operations/observability/mixins/meta/rules/dashboard.yaml
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/S, team: team-experience

#19329 [dashboard] Fix GitHub app integration URL in user settings
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/XS, team: team-experience

#19330 Update code web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19325 Revert "Revert "Redirect on workspace stop" (#19323)"
  components/dashboard/src/service/service.tsx
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
Labels: size/M, team: team-experience

#19332 [code] Update code web
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19334 Add track event `team_joined` back
  components/server/src/orgs/organization-service.ts
Labels: size/XS, team: team-experience

#19337 Add admin role to builtin admin back
  components/gitpod-db/src/typeorm/migration/1705591447620-AdminUserAddAdminRole.ts
Labels: size/S, team: team-experience

#19324 [papi] add api to allow organization owner to create a temporary token
  components/public-api/gitpod/v1/token.proto
  components/public-api/go/v1/token.pb.go
  components/public-api/go/v1/token_grpc.pb.go
  components/public-api/go/v1/v1connect/token.connect.go
  components/public-api/go/v1/v1connect/token.proxy.connect.go
  components/public-api/typescript/src/gitpod/v1/token_connect.ts
  components/public-api/typescript/src/gitpod/v1/token_pb.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/api/token-service-api.ts
  components/server/src/authorization/definitions.ts
  components/spicedb/schema/schema.yaml
  test/tests/smoke-test/collaborator_test.go
  test/tests/smoke-test/papi_create_temp_token_test.go
Labels: size/XXL, team: team-experience, team: team-engine

#19331 [server] fix BBS metadata `latest-commit-metadata` not defined cause prebuild trigger failed
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/M, team: team-experience

#19339 [installer] update log level of spicedb
  install/installer/pkg/components/spicedb/deployment.go
Labels: size/XS, team: team-experience

#19336 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS

#19316 Define `ListOrganizationPrebuilds`
  components/dashboard/src/service/json-rpc-prebuild-client.ts
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/go/v1/prebuild_grpc.pb.go
  components/public-api/go/v1/v1connect/prebuild.connect.go
  components/public-api/go/v1/v1connect/prebuild.proxy.connect.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_connect.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/prebuild-service-api.ts
Labels: size/L, team: team-experience

#19346 Add tracing logging for hanging issue
  components/dashboard/src/app/AppLoading.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/orgs-query.ts
  components/dashboard/src/hooks/use-user-loader.ts
Labels: size/M, team: team-experience

#19345 Fix & Refactor Git Integration settings modal
  components/dashboard/src/user-settings/Integrations.tsx
Labels: size/M, team: team-experience

#19343 [papi] log ctx time if request took too much time
  components/server/src/api/server.ts
Labels: size/XS, team: team-experience

#19344 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19326 Implement `ListOrganizationPrebuilds`
  components/dashboard/src/service/json-rpc-prebuild-client.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/authorization/definitions.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/spicedb/schema/schema.yaml
Labels: size/L, team: team-experience

#19351 [papi] better grpc code for application unimplemented
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/S, team: team-experience

#19333 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19356 [dashboard] ux improvement on pat list
  components/dashboard/src/user-settings/TokenEntry.tsx
Labels: size/XS, team: team-experience

#19348 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/XS, team: team-experience

#19355 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19349 Add invalid billing address notification
  components/dashboard/package.json
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
  components/gitpod-db/go/stripe_customer.go
  components/gitpod-db/src/typeorm/migration/1706212918085-AddInvalidBillingAddressToStripeCustomer.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/public-api-server/pkg/billingservice/client.go
  components/public-api-server/pkg/billingservice/mock_billingservice/billingservice.go
  components/public-api-server/pkg/billingservice/noop.go
  components/public-api-server/pkg/webhooks/stripe.go
  components/server/src/auth/rate-limiter.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/usage-api/go/v1/billing.pb.go
  components/usage-api/go/v1/billing_grpc.pb.go
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/usage/v1/billing.proto
  components/usage/pkg/apiv1/billing.go
  components/usage/pkg/stripe/stripe.go
  yarn.lock
Labels: size/XL, team: team-experience

#19353 [papi] add prebuild log url to prebuild message
  components/dashboard/src/service/json-rpc-prebuild-client.ts
  components/proxy/conf/Caddyfile
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript-common/fixtures/toPrebuild_1.golden
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/server.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/headless-log-service.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XXL, team: team-experience

#19364 [openvsx-proxy] Pass in proxy settings as env vars
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/M, team: team-experience

#19362 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19367 [installer] Fix wrong env var name for proxy settings
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: size/XS, team: team-experience

#19366 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/S

#19368 [installer] Use experimental config properly for openvsx-proxy
  install/installer/pkg/components/openvsx-proxy/statefulset.go
Labels: team: team-experience

#19374 [installer] Adding proxy setting env vars to registry facade
  install/installer/pkg/components/registry-facade/daemonset.go
Labels: size/S, team: team-engine

#19372 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19375 [installer] Check if experimental config is nil
  install/installer/pkg/components/registry-facade/daemonset.go
Labels: size/M, team: team-engine

#19370 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine
