Repository gitpod-io/gitpod, pull requests merged in 2024-06, with the labels that each got.

#19824 Fix missing requests for repository details
  components/dashboard/src/data/configurations/configuration-queries.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19833 Code nightly pin to release branch
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#19832 Fix the prebuilds view with no task logs
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/server/src/workspace/headless-log-controller.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19823 [bob] Log body of "Bad Request" responses
  components/image-builder-bob/pkg/proxy/proxy.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19809 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#19827 [server] API: Ignore write-after-close error
  components/server/src/api/server.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19835 Add proper version info to JetBrains launcher and backend-plugin
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/build.sh
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/launcher/BUILD.yaml
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/pkg/constant/version.go
Labels: size/M, team: team-experience, team: team-enterprise

#19831 [server] add workspace.deletionEligabilityTime
  components/gitpod-db/src/typeorm/entity/db-workspace.ts
  components/gitpod-db/src/typeorm/migration/1717407555612-WorkspaceDeletionEligibilityTime.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19838 [server] update job for eligableDeletionTime
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19845 [GHA] improve JetBrains EAP jobs
  .github/workflows/jetbrains-auto-update-template.yml
  components/ide/jetbrains/image/resolve-latest-ide-version.sh
Labels: size/S, team: team-experience, team: team-enterprise

#19840 Add proper tabs to Podkit
  components/dashboard/package.json
  components/dashboard/src/components/podkit/tabs/Tabs.tsx
  components/dashboard/src/index.css
  components/dashboard/src/workspaces/ConnectToSSHModal.tsx
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: size/L, team: team-experience, team: team-enterprise

#19849 [server, bridge] Bump grpc-js and authzed clients
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/util/grpc.ts
  components/ide-metrics-api/typescript-grpc/package.json
  components/ide-service-api/typescript/package.json
  components/image-builder-api/typescript/package.json
  components/server/package.json
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/authorization/spicedb.ts
  components/spicedb/typescript/package.json
  components/supervisor-api/typescript-grpc/package.json
  components/usage-api/typescript/package.json
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  yarn.lock
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#19852 [GHA] fix branch conflict
  .github/workflows/code-updates.yml
Labels: size/XS

#19843 [installer] content-service: Add PodDisruptionBudget (maxUnavailable: 1)
  install/installer/pkg/components/content-service/objects.go
  install/installer/pkg/components/content-service/pdb.go
Labels: size/S, team: team-engine, team: team-enterprise

#19847 Add Podkit tabs to Prebuilds' detail
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19841 [VS Code Browser] Build stable code `1.90.0`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19854 [VS Code Browser] Update stable code to `1.90.0`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#19855 [server] Fix CapGitStatus job
  components/server/src/jobs/cap-git-status.spec.db.ts
  components/server/src/jobs/cap-git-status.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19856 Automatically cancel org's subscription upon its deletion
  components/gitpod-db/go/stripe_customer.go
  components/server/package.json
  components/server/src/billing/stripe-service.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/user-deletion-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  yarn.lock
Labels: size/L

#19861 [server] Fix CapGitStatus job (again)
  components/server/src/jobs/cap-git-status.spec.db.ts
  components/server/src/jobs/cap-git-status.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19848 Fix JetBrains warmup configured `both` versions but only latest version takes effect
  components/supervisor/pkg/supervisor/config.go
Labels: size/S, team: team-experience, team: team-enterprise

#19846 [java] add java ops for processor count and container support
  components/common-go/experiments/flags.go
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
  components/ws-manager-mk2/controllers/create.go
Labels: size/M, team: staff-engineers, team: team-experience, team: team-engine, team: team-enterprise

#19862 Keep nanoseconds for file ModifleTime when backup
  components/ws-daemon/pkg/content/archive.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19865 Fix main build
  components/ws-manager-mk2/controllers/create_test.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19866 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19851 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19870 [server] CapGitStatus: Log instanceIds of capped instances
  components/server/src/jobs/cap-git-status.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19871 Improve extension detection in the dashboard
  components/dashboard/public/index.html
  components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#19874 [server] Drop feature flag workspace_start_new and related code
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19875 QoL improvements for the prebuild UI
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19876 Improve dashboard and readme copy
  README.md
  components/dashboard/src/teams/TeamAuthentication.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
  components/server/src/bitbucket/README.md
  components/server/src/github/api.ts
  components/server/src/user/token-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19842 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/L, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19878 Gpl/ft/supervisor-listen-files
  components/supervisor/pkg/supervisor/services.go
Labels: size/L, team: team-experience, team: team-enterprise

#19867 Tolerate all taints
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19877 [proxy] enable metrics for Caddy
  components/proxy/conf/Caddyfile
Labels: size/S, team: team-experience, team: team-enterprise

#19882 Revert " [proxy] enable metrics for Caddy"
  components/proxy/conf/Caddyfile
Labels: size/S, team: team-experience, team: team-enterprise

#19863 Integrate reading from log files into Supervisor's `terminal.Listen`
  components/server/src/workspace/headless-log-service.ts
  components/supervisor-api/go/task.pb.go
  components/supervisor-api/go/task.pb.gw.go
  components/supervisor-api/go/task_grpc.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Task.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TaskServiceGrpc.java
  components/supervisor-api/task.proto
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/tasks.go
Labels: size/XXL, team: team-experience, team: team-enterprise

#19880 Support mounting NFS shares into workspaces
  components/workspacekit/pkg/seccomp/notify.go
  components/ws-daemon-api/go/daemon.pb.go
  components/ws-daemon-api/go/daemon_grpc.pb.go
  components/ws-daemon-api/go/mock/mock.go
  components/ws-daemon-api/go/workspace_daemon.pb.go
  components/ws-daemon-api/go/workspace_daemon_grpc.pb.go
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/daemon_pb.js
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.js
  components/ws-daemon-api/workspace_daemon.proto
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/pkg/iws/iws.go
Labels: size/L, team: team-engine, team: team-enterprise

#19872 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19886 Update all jb-launcher to latest version
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: team-experience, team: team-enterprise

#19883 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19889 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19890 [server] Remove CapGitStatus job, increase limit for CapStatus job
  components/server/src/container-module.ts
  components/server/src/jobs/cap-git-status.spec.db.ts
  components/server/src/jobs/cap-git-status.ts
  components/server/src/jobs/cap-status.ts
  components/server/src/jobs/runner.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19891 Increase OAuth isHostReachable timeout from 2 to 15 seconds
  components/server/src/auth/auth-provider-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19884 [cleanup] Remove various feature flags I
  components/common-go/experiments/flags.go
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/hooks/use-user-loader.ts
  components/dashboard/src/start/VerifyModal.tsx
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
  components/public-api-server/pkg/apiv1/tokens.go
  components/public-api-server/pkg/apiv1/tokens_test.go
  components/server/src/api/verification-service-api.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/XL, team: staff-engineers, team: team-experience, team: team-enterprise

#19881 [server] Remove old FGA feature flags:
  components/dashboard/src/service/public-api.ts
  components/server/src/api/server.ts
  components/server/src/auth/auth-provider-service.spec.db.ts
  components/server/src/auth/bearer-authenticator.spec.db.ts
  components/server/src/auth/resource-access.ts
  components/server/src/authorization/authorizer.spec.db.ts
  components/server/src/authorization/authorizer.ts
  components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
  components/server/src/authorization/relationship-updater.spec.db.ts
  components/server/src/authorization/relationship-updater.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/usage-service.spec.db.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/scm/scm-service.spec.db.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/gitpod-token-service.spec.db.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/token-service.spec.db.ts
  components/server/src/user/user-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-service.spec.db.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#19888 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19885 [proxy] enable metrics for Caddy again
  components/proxy/conf/Caddyfile
Labels: size/XS, team: team-experience, team: team-enterprise

#19894 [cleanup] remove FF for supervisor publicapi
  components/common-go/experiments/flags.go
  components/supervisor/pkg/serverapi/metrics.go
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: staff-engineers, team: team-experience, team: team-enterprise

#19897 [gha] do not skip openvscode-server release
  .github/workflows/code-updates.yml
Labels: size/XS

#19895 [cleanup] remove FF for components service-waiter
  components/common-go/experiments/flags.go
  components/service-waiter/cmd/component.go
  components/service-waiter/cmd/component_test.go
  components/service-waiter/pkg/metrics/metrics.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/components/ide-metrics/configmap.go
Labels: size/XL, team: staff-engineers, team: team-experience, team: team-enterprise

#19898 [VS Code Browser] Build stable code `1.90.1`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#19899 [cleanup] Drop more feature flags
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/onboarding/StepUserInfo.tsx
  components/server/src/auth/verification-service.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/jobs/cap-status.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19903 [VS Code Browser] Update stable code to `1.90.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#19896 [dashboard] Fix PrebuildStatus rendering and updating (on PrebuildList)
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/prebuild-utils.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19905 [JetBrains] fix alert for JAVA_TOOL_OPTIONS
  components/ide/jetbrains/launcher/main.go
Labels: size/XS, team: team-experience, team: team-enterprise

#19906 Improve code-updates GHA
  .github/workflows/code-updates.yml
Labels: size/S

#19907 [JetBrains] improve task terminals
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
Labels: size/XS, team: team-experience, team: team-enterprise

#19904 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19902 [cleanup] remove unnecessary FFs
  components/dashboard/src/app/AppLoading.tsx
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/orgs-query.ts
  components/dashboard/src/hooks/use-user-loader.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailWorkspaces.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19911 Align experience of latest pinned and unpinned version
  components/ide-service-api/go/config/ideconfig.go
  components/ide-service/BUILD.yaml
  components/ide-service/pkg/server/ideconfig.go
  components/ide-service/pkg/server/testdata/ideconfig_happypath.golden
  components/ide-service/pkg/server/testdata/ideconfig_happypath_resolve.golden
  components/ide-service/pkg/server/testdata/ideconfig_happypath_versions.golden
  components/ide-service/pkg/server/testdata/ideconfig_happypath_versions.json
  components/ide-service/pkg/server/testdata/ideconfig_idetype_not_correct.golden
  components/ide-service/pkg/server/testdata/ideconfig_idetype_unknown.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.golden
  components/ide/gha-update-image/index-jb.ts
  components/ide/gha-update-image/lib/jb-pin-version.ts
  components/ide/gha-update-image/lib/jb-stable-version.ts
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/XXL, team: team-experience, team: team-enterprise

#19915 [VS Code Browser] Update stable code to `1.90.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19920 Remove unnecessary debug log
  components/ide-service/pkg/server/ideconfig.go
Labels: size/XS, team: team-experience, team: team-enterprise

#19921 Switch code nightly job to `gp-code/main`
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#19887 Image builds in prebuilds UI
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/java/.gitignore
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/PrebuildOuterClass.java
  components/public-api/typescript-common/fixtures/toPrebuild_1.golden
  components/public-api/typescript-common/fixtures/toPrebuild_1.json
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
Labels: size/XXL, team: team-experience, team: team-enterprise

#19919 Improve ide images updating GHA
  components/ide/gha-update-image/check-code-build.ts
  components/ide/gha-update-image/index-code.ts
  components/ide/gha-update-image/lib/code-pin-version.ts
  components/ide/gha-update-image/lib/common.ts
  components/ide/gha-update-image/lib/jb-stable-version.ts
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/L, team: team-experience, team: team-enterprise

#19925 [gha] thrown when fetching empty version
  components/ide/gha-update-image/lib/code-pin-version.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19928 [gha] add `oci-tool` to fix code updates errors
  .github/workflows/code-build.yaml
  .github/workflows/code-updates.yml
Labels: size/XS

#19927 Support version pin for JetBrains warmup prebuild
  components/ide-service/BUILD.yaml
  components/ide-service/example-ide-config.json
  components/ide-service/pkg/server/server.go
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin.json
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_2.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_2.json
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_ide_notfound.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_ide_notfound.json
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_version_notfound.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij_pin_version_notfound.json
Labels: size/L, team: team-experience, team: team-enterprise

#19930 Add Java & Kotlin generated files to gitattributes
  .gitattributes
Labels: size/XS

#19913 [JetBrains] add more integration tests
  .devcontainer/Dockerfile
  .github/workflows/jetbrains-updates.yml
  components/gitpod-protocol/go/gitpod-service.go
  dev/jetbrains-test/.gitignore
  dev/jetbrains-test/BUILD.yaml
  dev/jetbrains-test/README.md
  dev/jetbrains-test/test.sh
  test/BUILD.yaml
  test/go.mod
  test/go.sum
  test/pkg/integration/apis.go
  test/pkg/integration/publicapi.go
  test/pkg/integration/workspace.go
  test/run.sh
  test/tests/ide/jetbrains/base_in_workspace_test.go
  test/tests/ide/jetbrains/base_test.go
  test/tests/ide/jetbrains/gateway_test.go
  test/tests/ide/jetbrains/warmup-indexing.sh
Labels: size/XXL, team: team-experience, team: team-engine, team: team-enterprise

#19933 [gha] correct code new version detection
  .github/workflows/code-updates.yml
  components/ide/gha-update-image/index-code.ts
  components/ide/gha-update-image/lib/code-pin-version.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19929 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#19931 [server] remove old workspace gc logic
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/jobs/workspace-gc.ts
Labels: size/L, team: team-experience, team: team-enterprise

#19926 [obs] Add Caddy metrics to Proxy dashboard & Caddy alerts
  operations/observability/mixins/meta/dashboards/components/proxy.json
  operations/observability/mixins/meta/rules/proxy.yaml
Labels: size/XXL, team: team-experience, team: team-enterprise

#19934 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#19937 [VS Code Browser] Build stable code `1.90.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#19918 Remove repository-related feature flags, which are no longer used
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/repositories/coachmarks/MigrationCoachmark.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#19942 Gracefully stop supervisor to fix abrupt connection termination for tasks
  components/supervisor/pkg/supervisor/notification.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: team-experience, team: team-enterprise

#19916 Introduce prebuild task tab component
  components/dashboard/package.json
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/hooks/use-analytics-tracking.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
  components/dashboard/src/utils.ts
  components/server/src/workspace/headless-log-controller.ts
  components/supervisor/pkg/supervisor/notification.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
  yarn.lock
Labels: component: dashboard, size/XL, team: team-experience, team: team-enterprise

#19923 Remove project-related code
  components/dashboard/src/admin/ProjectDetail.tsx
  components/dashboard/src/admin/ProjectsSearch.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/data/prebuilds/organization-prebuilds-query.ts
  components/dashboard/src/images/projects-empty-dark.svg
  components/dashboard/src/images/projects-empty.svg
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildListPage.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
  components/dashboard/src/projects/Prebuild.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/projects/ProjectVariables.tsx
  components/dashboard/src/projects/Projects.tsx
  components/dashboard/src/projects/RemoveProjectModal.tsx
  components/dashboard/src/projects/create-project-modal/CreateProjectModal.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
Labels: component: dashboard, size/XXL, team: team-experience, team: team-enterprise

#19943 [server] Remove job CapStatus
  components/server/src/container-module.ts
  components/server/src/jobs/cap-status.ts
  components/server/src/jobs/runner.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19914 [usage, server, dashboard] Remove ff usage_update_scheduler_duration
  components/dashboard/src/usage/UsageView.tsx
  components/gitpod-protocol/src/usage.ts
  components/server/src/orgs/usage-service.ts
  components/server/src/test/mocks/usage-service-client-mock.ts
  components/usage-api/go/v1/usage.pb.go
  components/usage-api/go/v1/usage_grpc.pb.go
  components/usage-api/typescript/src/google/protobuf/duration.pb.ts
  components/usage-api/typescript/src/google/protobuf/timestamp.pb.ts
  components/usage-api/typescript/src/usage/v1/billing.pb.ts
  components/usage-api/typescript/src/usage/v1/usage.pb.ts
  components/usage-api/usage/v1/usage.proto
  components/usage/pkg/apiv1/usage.go
  components/usage/pkg/apiv1/usage_test.go
  components/usage/pkg/server/server.go
  components/usage/pkg/server/server_test.go
Labels: size/L, team: team-experience, team: team-enterprise

#19940 Fix nightly VS Code Browser rewrite stable version images
  .github/workflows/code-nightly.yml
  components/ide/code/BUILD.yaml
  components/ide/code/leeway.Dockerfile
  components/ide/gha-update-image/lib/code-pin-version.ts
  components/ide/gha-update-image/lib/common.ts
  components/ide/gha-update-image/lib/jb-pin-version.ts
  install/installer/cmd/ideconfigmap.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  test/run.sh
Labels: size/L, team: team-experience, team: team-enterprise

#19912 [server] Move ff google_cloud_profiler into env var/installer config
  components/server/src/init.ts
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/S, team: team-experience, team: team-enterprise

#19939 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#19947 [gha] fix nit bugs of IDE images update
  components/ide/gha-update-image/lib/code-pin-version.ts
  components/ide/gha-update-image/lib/common.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19951 [gha] correct images to use
  .github/workflows/jetbrains-updates.yml
  components/ide/gha-update-image/lib/code-pin-version.ts
  components/ide/gha-update-image/lib/jb-pin-version.ts
Labels: size/S, team: team-experience, team: team-enterprise

#19957 Add timeout for taskservice in supervisor
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/S, team: team-experience, team: team-enterprise

#19955 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19828 Deprecate intelliJ 2022.3.3
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/server/src/ide-service.spec.ts
  components/server/src/ide-service.ts
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/L, team: team-experience, team: team-enterprise

#19959 [obs] reduce potential for ProxyBadGateway to trigger
  operations/observability/mixins/meta/rules/proxy.yaml
Labels: size/XS, team: team-experience, team: team-enterprise

#19954 [VS Code Browser] Update stable code to `1.90.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#19963 [gha] fix IDE integration tests
  .github/workflows/ide-integration-tests.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#19962 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#19965 Update cmd name in `gp timeout set` example
  components/gitpod-cli/cmd/timeout-set.go
Labels: size/XS, team: team-experience, team: team-enterprise

#19945 Enable displaying JB warmup tasks in the Prebuilds UI
  components/public-api/typescript-common/fixtures/toPrebuild_1.golden
  components/public-api/typescript-common/fixtures/toPrebuild_1.json
  components/public-api/typescript-common/src/public-api-converter.ts
  components/supervisor/pkg/supervisor/config.go
Labels: size/L, team: team-experience, team: team-enterprise

#19917 [server] audit log service
  .gitignore
  components/gitpod-db/src/audit-log-db.ts
  components/gitpod-db/src/container-module.ts
  components/gitpod-db/src/typeorm/audit-log-db-impl.ts
  components/gitpod-db/src/typeorm/entity/db-audit-log.ts
  components/gitpod-db/src/typeorm/migration/1718628014741-AddAuditLogs.ts
  components/gitpod-protocol/src/audit-log.ts
  components/public-api/buf.gen.yaml
  components/public-api/gitpod/v1/auditlogs.proto
  components/public-api/go/v1/auditlogs.pb.go
  components/public-api/go/v1/auditlogs_grpc.pb.go
  components/public-api/go/v1/v1connect/auditlogs.connect.go
  components/public-api/go/v1/v1connect/auditlogs.proxy.connect.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/AuditLogServiceClient.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/AuditLogServiceClientInterface.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Auditlogs.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/auditlogs_connect.ts
  components/public-api/typescript/src/gitpod/v1/auditlogs_pb.ts
  components/server/src/api/audit-log-service-api.ts
  components/server/src/api/server.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/audit/AuditLogService.spec.db.ts
  components/server/src/audit/AuditLogService.ts
  components/server/src/authorization/definitions.ts
  components/server/src/container-module.ts
  components/server/src/jobs/auditlog-gc.ts
  components/server/src/websocket/websocket-connection-manager.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL

#19966 [audit logs] scrub values
  components/server/src/audit/AuditLogService.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19967 Fix dropped errors on available prebuilds
  components/server/src/messaging/redis-subscriber.ts
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-manager-bridge/src/container-module.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.spec.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#19908 Remove old browser extension detection mechanism
  components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#19970 [proxy] return 503 for /analytics errors, instead of 502
  components/proxy/plugins/analytics/analytics.go
Labels: size/S, team: team-experience, team: team-enterprise

#19971 Do not send initial `queued` prebuild phase from workspace starter
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19969 Cleanup watching prebuilds
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/detail/PrebuildTaskErrorTab.tsx
  components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
Labels: component: dashboard, size/L, team: team-experience, team: team-enterprise

#19974 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise
