Repository gitpod-io/gitpod, pull requests merged in 2024-10, with the labels that each got.

#20251 Fix Stripe modal on short viewports
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20255 Update login page
  components/dashboard/src/Login.tsx
  components/dashboard/src/icons/GitpodEngraved.tsx
  components/dashboard/src/icons/IconEarlyAccess.tsx
  components/dashboard/src/index.css
  components/dashboard/tailwind.config.js
Labels: size/XXL, team: team-experience, team: team-enterprise

#20254 Updated App notification
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/components/Alert.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20260 Fix login sidebar width on very wide displays
  components/dashboard/src/Login.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20259 [ops] Introduce GitpodWsManagerMk2BackupFailureError and GitpodWsManagerMk2BackupFailureCritical
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/S, team: team-engine, team: team-enterprise

#20253 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20252 [ws-manager-mk2] include nodeName on failure
  components/ws-manager-mk2/controllers/status.go
Labels: size/XS, team: team-engine, team: team-enterprise

#20265 Fix login URL host parsing regression
  components/dashboard/src/Login.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20268 Privacy Policy update notification
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20266 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20270 Fix docs URLs
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-cli/cmd/docs.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20269 Fix spicedb throwing on invalid arguments
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/workspace/workspace-service.ts
Labels: component: server, size/M, team: team-experience, team: team-enterprise

#20272 Follow-ups from #20269
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/gitpod-protocol/src/util/parse-workspace-id.spec.ts
  components/gitpod-protocol/src/util/parse-workspace-id.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20264 Fix repo names for Bitbucket (Server)
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/bitbucket/bitbucket-context-parser.spec.ts
  components/server/src/bitbucket/bitbucket-context-parser.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/context-service.ts
  components/server/src/workspace/workspace-factory.spec.db.ts
  components/server/src/workspace/workspace-service.spec.db.ts
Labels: git provider: bitbucket, size/L, team: team-experience, team: team-enterprise

#20267 Improve handling of missing files for BB and BBS
  components/server/src/bitbucket-server/bitbucket-server-file-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
  components/server/src/bitbucket/bitbucket-file-provider.spec.ts
  components/server/src/bitbucket/bitbucket-file-provider.ts
Labels: git provider: bitbucket, size/L

#20282 [VS Code Browser] Build stable code `1.94.1`
  WORKSPACE.yaml
  components/ide/code/BUILD.yaml
  components/ide/code/leeway.Dockerfile
  components/ide/code/leeway.nightly.Dockerfile
Labels: editor: code (browser), size/L, team: IDE, team: team-experience, team: team-enterprise

#20283 Add Azure DevOps to browser extension ad
  components/dashboard/src/images/browser-extension/azure-devops.webp
  components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20284 [VS Code Browser] Update stable code to `1.94.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20285 Update Open VSX extension control manifest
  components/ide-proxy/Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20273 Update platform version of JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthCallbackHandler.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthService.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionService.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/common/GitpodConnectionHandleFactory.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectionHandleFactory.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnectionHandleFactory.kt
  components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml
Labels: size/XL, team: team-experience, team: team-enterprise

#20274 Disable JetBrains local ports forwarding with FF
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodPortForwardingService.kt
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20287 Improve repository finder search URL validation
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/utils.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20288 [JetBrains] improve handling of client connection termination
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Labels: size/M, team: team-experience, team: team-enterprise

#20291 Fix constant Gitpod Plugin exception on Gateway startup
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthCallbackHandler.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthService.kt
Labels: size/S, team: team-experience, team: team-enterprise

#20295 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20296 Repository finder & context parsing improvements
  components/dashboard/src/components/podkit/combobox/Combobox.tsx
  components/server/src/workspace/context-parser-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20292 Don't report `supervisor_check_ready` unless the FF is enabled
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20286 [vscode] Fix code dockerfile
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/M, team: team-experience, team: team-enterprise

#20302 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20281 Provide a nicer image build failed message
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/M, team: team-experience, team: team-enterprise

#20297 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20271 [ws-gc] WS soft deletion improvements
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/config.ts
  components/server/src/jobs/workspace-gc.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20294 [VS Code Browser] Build stable code `1.94.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20303 Update README.md
  README.md
Labels: size/XS

#20304 [VS Code Browser] Update stable code to `1.94.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20305 fix: avoid accessing null value
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20307 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20308 [code] Fix code dockerfile
  components/ide/code/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20293 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20311 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20279 [WS CLI] Make `env --scope=user` compatible with GitLab groups
  components/gitpod-cli/cmd/env.go
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20299 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20313 [gha] update gateway EAP plugin to use `build` instead of `version`
  components/ide/gha-update-image/lib/jb-helper/jb-gradle-task-config.ts
  components/ide/gha-update-image/lib/jb-helper/jb-helper.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20312 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20317 [dashboard] Add a notice of Prebuild GC to the prebuilds list
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20318 [supervisor] set pod failure reason when supervisor is reaped
  components/supervisor/cmd/init.go
  components/supervisor/go.mod
  components/supervisor/go.sum
Labels: size/M, team: team-experience, team: team-enterprise

#20322 [supervisor] switch lib back to use upstream `ramr/go-reaper`
  components/supervisor/cmd/init.go
  components/supervisor/go.mod
  components/supervisor/go.sum
Labels: size/S, team: team-experience, team: team-enterprise

#20323 Add AWS re:Invent 2024 notification
  components/dashboard/src/AppNotifications.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20325 [supervisor] revert recent changes to reduce frequency of `supervisor run error with unexpected exit code`
  components/supervisor/cmd/init.go
  components/supervisor/go.mod
  components/supervisor/go.sum
Labels: size/M, team: team-experience, team: team-enterprise

#20321 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20328 Bump Browser Terminal
  WORKSPACE.yaml
Labels: size/XS

#20332 [supervisor] Fix subscription leaks in PortsStatus
  components/local-app/pkg/bastion/bastion.go
  components/supervisor/pkg/ports/served-ports.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20333 [VS Code Browser] Build stable code `1.95.0`
  WORKSPACE.yaml
  components/ide/code/BUILD.yaml
  components/ide/code/leeway.Dockerfile
  components/ide/code/leeway.nightly.Dockerfile
Labels: editor: code (browser), size/L, team: IDE, team: team-experience, team: team-enterprise

#20335 [dashboard] do not show repo examples from incompatible providers
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20338 [VS Code Browser] Update stable code to `1.95.0`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise
