Repository gitpod-io/gitpod, pull requests merged in 2024-02, with the labels that each got.

#19379 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19376 Update containerd and buildkit go modules
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/image-builder-mk3/pkg/auth/auth.go
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/agent-smith/daemonset.go
  install/installer/pkg/components/blobserve/deployment.go
  install/installer/pkg/components/content-service/deployment.go
  install/installer/pkg/components/ide-metrics/deployment.go
  install/installer/pkg/components/ide-service/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
  test/go.mod
Labels: size/L, team: team-experience, team: team-engine

#19385 [dashboard] check billing address on gitpodio only
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience

#19389 Revert jb stable images to 2023.3.2
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: team-experience

#19391 Enable vscode 1.85 for older linux distros
  components/ide-service/pkg/server/server.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/L, team: team-experience

#19395 Add a note about no proxy env var
  install/installer/pkg/config/v1/experimental/experimental.go
Labels: size/XS

#19396 [registry-facade] Remove support for proxy settings
  install/installer/pkg/components/registry-facade/daemonset.go
Labels: size/S, team: team-engine

#19383 [image-builder-bob] update buildkit version
  components/image-builder-bob/leeway.Dockerfile
  dev/preview/infrastructure/scripts/bootstrap-k3s.sh
Labels: size/XS, team: team-engine

#19394 [JB] Properly overide jb config and cache folder locations
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/L, team: team-experience

#19393 [workspace-starter] Fix re-start issue in case ws-manager emits ALREDY_EXISTS
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience

#19399 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, do-not-merge/hold, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19354 Prebuilds List UI
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/components/podkit/combobox/Combobox.tsx
  components/dashboard/src/components/podkit/tables/SortableTable.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/prebuilds/organization-prebuilds-query.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/prebuilds/list/ConfigurationInput.tsx
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildListEmptyState.tsx
  components/dashboard/src/prebuilds/list/PrebuildListErrorState.tsx
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
  components/dashboard/src/projects/Prebuilds.tsx
  components/dashboard/src/projects/Project.tsx
  components/dashboard/src/projects/ProjectListItem.tsx
  components/dashboard/src/projects/prebuild-utils.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfigurationModal.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/gitpod-db/src/typeorm/workspace-db-impl.spec.db.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/api/prebuild-service-api.ts
  components/server/src/prebuilds/prebuild-manager.ts
Labels: size/XXL, team: team-experience

#19404 [code] Update code to 1.86.1
  WORKSPACE.yaml
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid.golden
  components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid.json
  components/ide/code/leeway.Dockerfile
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/M, team: team-experience

#19406 [code] Update code
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19402 [redis] Fix readiness probe
  install/installer/pkg/components/redis/deployment.go
Labels: size/XS, team: team-engine

#19407 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19403 [preview] update to gen108 VM image
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/modules/harvester/variables.tf
  dev/preview/infrastructure/scripts/bootstrap-k3s.sh
  dev/preview/infrastructure/variables.tf
Labels: size/S, team: team-engine

#19405 Disable Workspace creation directly from prebuilds
  components/dashboard/src/projects/Prebuild.tsx
Labels: size/S, team: team-experience

#19414 [code] Update code-web extension image
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19361 [dashboard] add single prebuild page
  components/dashboard/package.json
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/data/prebuilds/prebuild-query.ts
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/dashboard/src/projects/prebuild-utils.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildDetailPage.tsx
  components/dashboard/src/repositories/repositories.routes.ts
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: size/XL, team: team-experience

#19417 fix: Invalid Billing address error
  components/dashboard/src/AppNotifications.tsx
Labels: size/S, team: team-experience

#19418 Fix start workspace button alignment
  components/dashboard/src/Login.tsx
  components/dashboard/src/components/podkit/buttons/Button.tsx
Labels: size/XS, team: team-experience

#19421 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: team-experience

#19419 Misc UI fixes for configs and prebuilds
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/prebuilds/prebuild-query.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/dashboard/src/projects/prebuild-utils.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildDetailPage.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
Labels: size/L, team: team-experience

#19423 [auth] Make error from SCM trusted
  components/server/src/auth/generic-auth-provider.ts
Labels: size/XS, team: team-experience

#19422 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19426 fix: Workspace Timeout Bug: Correctly Apply disabledClosedTimeout Flag for Enhanced User Control
  components/dashboard/src/user-settings/Preferences.tsx
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience

#19427 Update code-web extension
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19431 Fix stripe API rate limit error
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience

#19424 Prebuild fixes v2
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/prebuilds/configuration-input/Combobox.tsx
  components/dashboard/src/prebuilds/configuration-input/ComboboxItem.tsx
  components/dashboard/src/prebuilds/configuration-input/ComboboxSelectedItem.tsx
  components/dashboard/src/prebuilds/configuration-input/ConfigurationInput.tsx
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
  components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
  components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfigurationModal.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildDetailPage.tsx
Labels: size/XL, team: team-experience

#19428 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS

#19430 Update Platform Version of JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt
Labels: size/S, team: team-experience

#19437 Update Platform Version of JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: team-experience

#19429 Update Platform Version of JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS

#19438 [billing] fix: stripe service for their address parameters
  components/usage/pkg/stripe/stripe.go
Labels: size/XS, team: team-experience

#19432 [code] Update code 1.86.2
  WORKSPACE.yaml
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/XS, team: team-experience

#19439 GitpodWorkspaceTooManyRegularNotActiveMk2: add lower bound of 20
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine

#19413 Configuration coachmark
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/podkit/popover/Popover.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildListErrorState.tsx
  components/dashboard/src/repositories/coachmarks/MigrationCoachmark.tsx
  components/gitpod-protocol/src/protocol.ts
  components/public-api/gitpod/v1/user.proto
  components/public-api/go/v1/user.pb.go
  components/public-api/typescript-common/fixtures/toUser_1.golden
  components/public-api/typescript/src/gitpod/v1/user_pb.ts
Labels: component: dashboard, size/L, team: team-experience

#19444 [redis] Use TCP probe
  install/installer/pkg/components/redis/deployment.go
Labels: size/XS

#19397 [lacework] Use 'installer mirror list' and include Docker Hub images
  .github/workflows/lacework-inline-scanner.yml
  scripts/lw-scan-images.sh
Labels: size/M

#19446 Imported repositories -> Repository settings
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/repositories/coachmarks/MigrationCoachmark.tsx
  components/dashboard/src/repositories/create/AddRepositoryModal.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
  components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
  components/dashboard/src/repositories/list/RepoListEmptyState.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
Labels: size/L, team: team-experience

#19447 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19450 [api] Fix /api/logout
  components/server/src/session-handler.ts
Labels: size/S, team: team-experience

#19451 [frontend] Smooth relogin
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/hooks/use-user-loader.ts
Labels: size/S, team: team-experience

#19443 [dashboard] Be more defensive when constructing "invalida billing address" notifications
  components/dashboard/src/AppNotifications.tsx
Labels: size/M, team: team-experience

#19445 [server, dashboard] improve single prebuild view
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/public-api/typescript-common/src/prebuild-utils.spec.ts
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/util/request-context.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience

#19440 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19442 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19456 [server] Fix handling of multiple session cookies with the same name
  components/public-api-server/pkg/auth/middleware.go
  components/server/src/session-handler.spec.db.ts
  components/server/src/session-handler.ts
Labels: size/L, team: team-experience

#19452 [auth] Attempt to refresh token 3 times EXP-1413
  components/server/src/user/token-service.ts
Labels: size/M, team: team-experience

#19457 Make sure logs are aligned to the left
  components/dashboard/src/components/WorkspaceLogs.tsx
Labels: size/XS, team: team-experience

#19455 [IdP] add `user_id` claim and allow to customize OIDC subject via FF
  components/common-go/experiments/flags.go
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
  components/public-api-server/pkg/server/server.go
Labels: size/L, team: staff-engineers, team: team-experience

#19449 Manually rerun prebuilds
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/prebuilds/list/PrebuildList.tsx
  components/dashboard/src/prebuilds/list/PrebuildListEmptyState.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
  components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
  components/server/src/workspace/workspace-factory.ts
Labels: size/L, team: team-experience

#19459 Remove ability to edit repository variables
  components/dashboard/src/repositories/detail/variables/ConfigurationAddVariableModal.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableItem.tsx
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
Labels: size/L, team: team-experience

#19462 [dashboard] add route without FF checking
  components/dashboard/src/app/AppRoutes.tsx
Labels: size/S, team: team-experience

#19463 [dashboard] reduce API call in prebuild pages
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/typescript-common/fixtures/toPrebuild_1.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
Labels: size/M, team: team-experience

#19461 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19465 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#19392 [JetBrains] make plugin support other platforms
  components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/XS

#19468 [dashboard] fix workspace start options ordering
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/M, team: team-experience

#19460 Add guidance for debugging failed prebuilds
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/server/src/api/prebuild-service-api.ts
Labels: size/M, team: team-experience

#19469 [server] Missing SCM access: Filter out user error on workspace start
  components/proxy/conf/Caddyfile
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/workspace-starter.ts
  operations/observability/mixins/meta/rules/server.yaml
Labels: size/S, team: team-experience

#19472 Fix failed prebuild reruns
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/XS, team: team-experience

#19476 Fix duration validation
  components/gitpod-protocol/src/gitpod-service.ts
Labels: size/XS, team: team-experience

#19478 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19482 [server] Improve behavior and reporting around "refreshToken"
  components/server/src/prometheus-metrics.ts
  components/server/src/user/token-service.ts
Labels: size/M, team: team-experience

#19480 [papi] add `restricted_workspace_classes` in repository settings
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/go/v1/configuration.pb.go
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_2.golden
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
Labels: size/M, team: team-experience

#19481 [papi,server] implement `restricted_workspace_classes` in server
  components/public-api-server/pkg/apiv1/project.go
  components/public-api-server/pkg/apiv1/project_test.go
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_1.golden
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.golden
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.json
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.json
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.json
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.json
  components/public-api/typescript-common/src/public-api-converter.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/L, team: team-experience

#19473 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19489 Add db migration for org-level editor restriction
  components/gitpod-db/src/typeorm/migration/1709205581055-AddOrgSettingsRestrictedEditors.ts
Labels: size/S, team: team-experience

#19488 [papi] add proto of restricted editors on org-level and repo-level
  components/public-api/gitpod/experimental/v1/projects.proto
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/experimental/v1/projects.pb.go
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/organization.pb.go
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.golden
  components/public-api/typescript/src/gitpod/experimental/v1/projects_pb.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
Labels: size/M, team: team-experience

#19410 [dashboard] restrict workspace classes on repo-level
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/components/WorkspaceClassesOptions.tsx
  components/dashboard/src/components/podkit/switch/Switch.tsx
  components/dashboard/src/components/podkit/typography/Headings.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/workspaces/workspace-classes-query.test.ts
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailWorkspaces.tsx
  components/dashboard/src/repositories/detail/workspaces/ConfigurationWorkspaceClassesOptions.tsx
  components/dashboard/src/repositories/repositories.routes.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XXL, team: team-experience
