Repository gitpod-io/gitpod, pull requests merged in 2024-12, with the labels that each got.

#20413 [server] Add SCM repo search integration tests
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
  components/server/src/github/github-repository-provider.spec.ts
  components/server/src/gitlab/gitlab-repository-provider.spec.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20421 [dashboard] Privacy policy update notification
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20419 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20423 [server] Fix permission check for logs streaming
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/headless-log-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20424 [cli] ports-list: Increase timeout for establishing connection + receiving response to 5s -> 10s
  components/gitpod-cli/cmd/ports-list.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20425 Delete .github/workflows/lacework-inline-scanner.yml
  .github/workflows/lacework-inline-scanner.yml
Labels: size/M

#20429 Cleanup AWS re:Invent notifications
  components/dashboard/src/AppNotifications.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20426 Add WS image metrics to workspace instances
  components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts
  components/gitpod-db/src/typeorm/migration/1733397172273-AddWorkspaceInstanceMetrics.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/workspace.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/WorkspaceOuterClass.java
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.json
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/go/core_grpc.pb.go
  components/ws-manager-api/go/mock/mock.go
  components/ws-manager-api/typescript/src/core_grpc_pb.d.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.js
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-mk2/service/manager.go
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#20436 Gpl/970-multi-org-tests
  components/server/src/iam/iam-session-app.spec.ts
  components/server/src/iam/iam-session-app.ts
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.spec.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/gitpod-token-service.spec.db.ts
  components/server/src/user/sshkey-service.spec.db.ts
  components/server/src/user/token-service.spec.db.ts
  components/server/src/user/user-service.spec.db.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20439 [ws-daemon] reduce requested memory to 2Gi
  install/installer/pkg/components/ws-daemon/daemonset.go
Labels: size/XS, team: team-engine, team: team-enterprise

#20420 Minor README updates
  README.md
Labels: size/XS

#20437 Add insights page
  components/dashboard/package.json
  components/dashboard/src/Insights.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/components/accordion/Accordion.tsx
  components/dashboard/src/data/insights/list-workspace-sessions-query.ts
  components/dashboard/src/insights/WorkspaceSession.tsx
  components/dashboard/src/insights/WorkspaceSessionGroup.tsx
  components/dashboard/src/insights/download/DownloadInsights.tsx
  components/dashboard/src/insights/download/download-sessions.ts
  components/dashboard/src/usage/UsageEntry.tsx
  components/dashboard/src/usage/UsageView.tsx
  components/dashboard/src/usage/download/DownloadUsage.tsx
  components/dashboard/src/usage/download/download-usage-csv.ts
  components/dashboard/tailwind.config.js
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/workspace.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/WorkspaceOuterClass.java
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/workspace/context-parser.ts
  components/server/src/workspace/workspace-service.ts
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-enterprise

#20443 [VS Code Browser] Build stable code `1.96.0`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20449 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20450 [.github] prometheus-redis-exporter:latest is no longer available
  .github/workflows/update-image-digest.yml
Labels: size/S, team: team-experience, team: team-engine, team: team-enterprise

#20451 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20455 [dashboard] Fix bottom page margins for Prebuilds, Repositories and Insights
  components/dashboard/src/Insights.tsx
  components/dashboard/src/prebuilds/list/PrebuildListPage.tsx
  components/dashboard/src/repositories/list/RepositoryList.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20456 [server] Fix context setting for PRs for insights
  components/dashboard/src/insights/download/download-sessions.ts
  components/public-api/typescript-common/src/public-api-converter.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20448 Introduce `max_parallel_running_workspaces` for orgs
  components/dashboard/src/components/OrgMemberPermissionsOptions.tsx
  components/dashboard/src/components/WorkspaceClassesOptions.tsx
  components/dashboard/src/components/forms/TextInputField.tsx
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/teams/policies/MaxParallelWorkspaces.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1734079239772-AddOrgSettingsMaxParallelWorkspaces.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/leeway.Dockerfile
  components/server/src/api/organization-service-api.ts
  components/server/src/api/teams.spec.db.ts
  components/server/src/billing/entitlement-service-ubp.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/container-module.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/workspace/workspace-service.ts
  gitpod-ws.code-workspace
Labels: size/XL, team: team-experience, team: team-enterprise

#20458 [obs] Make sure to not alert for 0 backup failures
  operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Labels: size/XS, team: team-engine, team: team-enterprise

#20461 [server] fix private GitHub avatars
  components/server/src/github/github-auth-provider.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20444 Replace YouTube with Mux for Gitpod demo video
  components/dashboard/package.json
  components/dashboard/src/components/podkit/loading/Skeleton.tsx
  components/dashboard/src/onboarding/VideoSection.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  yarn.lock
Labels: size/L, team: team-experience, team: team-enterprise

#20468 [server] Fix workspace service's workspace ID validation
  components/gitpod-protocol/src/util/parse-workspace-id.spec.ts
  components/gitpod-protocol/src/util/parse-workspace-id.ts
  components/server/src/api/workspace-service-api.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20469 [installer] Mount custom CA certs into all relevant places
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/public-api-server/deployment_test.go
Labels: size/S, team: team-experience, team: team-enterprise

#20474 [oidc] Fix the HEAD method call that checks reachability
  components/public-api-server/pkg/apiv1/oidc.go
  components/server/src/user/user-authentication.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20473 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise
