Repository gitpod-io/gitpod, pull requests merged in 2024-04, with the labels that each got.

#19585 Bump Tailwind to `v3.4.3`
  components/dashboard/package.json
  yarn.lock
Labels: size/L, team: team-experience

#19588 [JetBrains] fix EAP backend-plugin not start issue
  components/ide/jetbrains/backend-plugin/launch-dev-server.sh
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodPortForwardingService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/GitpodCopyWebUrlAction.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/ControllerStatusService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodTerminalService.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/launcher/main.go
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/L, editor: jetbrains, team: team-experience

#19587 Update `marketplace.json`
  components/ide-proxy/static/code/marketplace.json
Labels: size/M, team: team-experience

#19544 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine

#19595 [JetBrains] fix mk plugin dir failed
  components/ide/jetbrains/launcher/main.go
Labels: size/XS, team: team-experience

#19596 Increase initial healthcheck start
  components/node-labeler/cmd/run.go
  install/installer/pkg/components/registry-facade/daemonset.go
Labels: size/XS, team: team-engine

#19590 Improve queries on workspace start page
  components/dashboard/package.json
  components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
  components/dashboard/src/data/configurations/configuration-queries.ts
  components/dashboard/src/data/ide-options/ide-options-query.ts
  components/dashboard/src/data/workspaces/workspace-classes-query.ts
  yarn.lock
Labels: size/M, team: team-experience

#19600 Use proper error code when repo is blocked
  components/server/src/workspace/workspace-starter.ts
Labels: size/XS, team: team-experience

#19601 Clean up SCM connections of installation admin
  components/server/src/auth/authenticator.ts
  components/server/src/container-module.ts
  components/server/src/jobs/installation-admin-cleanup.ts
  components/server/src/jobs/runner.ts
Labels: size/M, team: team-experience

#19598 [code] Update code 1.88
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/components/workspace/ide/constants.go
Labels: size/S, team: team-experience

#19605 Account for passed env vars with quickstart
  components/dashboard/src/components/QuickStart.tsx
Labels: size/XS, team: team-experience

#19604 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19611 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19614 [jb] add 2023.3 versions back
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/L, team: team-experience

#19617 [jb] Remove clion versions
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/S, team: team-experience

#19613 Force refresh workspace git access tokens
  components/server/src/user/token-provider.ts
  components/server/src/user/token-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience

#19619 Increase modal dialog min width
  components/dashboard/src/components/Modal.tsx
Labels: size/XS, team: team-experience

#19623 [dashboard] switch to org on join
  components/dashboard/src/teams/JoinTeam.tsx
Labels: size/XS, team: team-experience

#19620 Do not show Editor type for JB
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
Labels: size/M, team: team-experience

#19626 Fix checking 401 error for GitHub
  components/server/src/github/github-context-parser.ts
Labels: size/XS, team: team-experience

#19631 [bitbucket.org] fix normalizeScopes
  components/server/src/bitbucket/bitbucket-auth-provider.ts
Labels: size/S, team: team-experience

#19628 Store ide configmap in a json file
  components/ide-service/pkg/server/ideconfig.go
  install/installer/BUILD.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/XXL, team: team-experience

#19612 Fix one frame starting on workspace stopping page
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages2.test.ts
  components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages2.ts
  components/dashboard/src/service/service.tsx
  components/dashboard/src/start/StartWorkspace.tsx
Labels: size/L, team: team-experience

#19635 [ws-manager-mk2] logging improvements
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/timeout_controller.go
  components/ws-manager-mk2/controllers/workspace_controller.go
Labels: size/S, team: team-engine

#19640 Fix changing URL hash on `/new`
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: team-experience

#19643 Fix autostart always false
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/XS, team: team-experience

#19645 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19646 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19629 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#19639 Hide editor versions for user prefs
  components/dashboard/src/components/SelectIDEComponent.tsx
  components/dashboard/src/onboarding/StepPersonalize.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: team-experience

#19634 Automatic JetBrains update script
  .github/workflows/jetbrains-updates.yml
  components/ide/jetbrains/image/gha-update-image/index.js
  components/ide/jetbrains/image/gha-update-image/index.ts
  components/ide/jetbrains/image/gha-update-image/package.json
  components/ide/jetbrains/image/gha-update-image/yarn.lock
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/XXL, team: team-experience

#19651 Fix GHA ide integration tests
  .github/workflows/ide-integration-tests.yml
Labels: size/XS, team: team-experience

#19656 Enhance token long and experiment with longer token validity expectation
  components/server/src/user/token-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/S, team: team-experience

#19660 Revert "[JetBrains] Update IDE images to new build version"
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/XS, team: team-experience

#19661 [ws-daemon] Change readiness behavior to wait for registry-facade
  components/ws-daemon/pkg/container/config.go
  components/ws-daemon/pkg/container/containerd.go
  components/ws-daemon/pkg/daemon/config.go
  install/installer/pkg/components/ws-daemon/configmap.go
Labels: size/M, team: team-engine

#19659 ✨ revamp product readme
  README.md
Labels: size/L

#19664 Make JetBrains stable GHA use the minimal major build version
  components/ide/jetbrains/image/gha-update-image/index.ts
  components/ide/jetbrains/image/gha-update-image/lib/common.ts
  components/ide/jetbrains/image/gha-update-image/lib/errors.ts
  components/ide/jetbrains/image/gha-update-image/lib/pin-version.ts
  components/ide/jetbrains/image/gha-update-image/lib/stable-version.test.ts
  components/ide/jetbrains/image/gha-update-image/lib/stable-version.ts
Labels: size/XXL, team: team-experience

#19672 [ws-proxy] Tighten cookie filter
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: size/S, team: team-engine

#19663 Update go-redis to v9.5.1
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/gitpod-cli/go.mod
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/registry-facade/pkg/registry/registry.go
  install/installer/go.mod
  install/installer/go.sum
Labels: size/M, team: team-experience, team: team-engine

#19637 Fix super long unauthed contexts for quickstart
  components/dashboard/src/components/QuickStart.tsx
  components/dashboard/src/utils.ts
Labels: size/M, team: team-experience

#19650 Browser Extension Advertisement
  components/dashboard/package.json
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/images/browser-extension/bitbucket.webp
  components/dashboard/src/images/browser-extension/github.webp
  components/dashboard/src/images/browser-extension/gitlab.webp
  components/dashboard/src/index.css
  components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/tailwind.config.js
  yarn.lock
Labels: size/L, team: team-experience

#19677 Deduplicate SCM providers for browser extension banner
  components/dashboard/package.json
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/setup.tsx
  components/dashboard/src/hooks/use-debounce.ts
  components/dashboard/src/hooks/use-state-with-debounce.ts
  components/dashboard/src/projects/ProjectSettings.tsx
  components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
  yarn.lock
Labels: size/M, team: team-experience

#19681 Log refresh token failures with user id ctx
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/user/token-service.ts
Labels: size/XS, team: team-experience

#19667 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience

#19655 Update usage scheduler according to FF
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/usage/usage-query.ts
  components/dashboard/src/usage/UsageView.tsx
  components/usage/go.mod
  components/usage/go.sum
  components/usage/pkg/server/server.go
  components/usage/pkg/server/server_test.go
  install/installer/pkg/components/usage/configmap.go
  install/installer/pkg/components/usage/configmap_test.go
Labels: size/XL, team: team-experience

#19679 [dashboard] Check JWT token every 5 mins
  components/dashboard/src/user-context.tsx
Labels: size/XS, team: team-experience

#19685 [workspace cluster] update docker compose for gen111
  WORKSPACE.yaml
Labels: size/XS

#19686 [server] Issue new token in case of new signing key
  components/server/src/auth/jwt.spec.ts
  components/server/src/auth/jwt.ts
  components/server/src/session-handler.ts
Labels: size/M, team: team-experience

#19690 [preview] deploy monitoring after gitpod is deployed
  dev/preview/workflow/preview/deploy-gitpod.sh
  dev/preview/workflow/preview/preview.sh
Labels: size/XS, team: team-experience, team: team-engine

#19691 [loadgen] fix the org associated with template repos
  dev/loadgen/configs/prod-benchmark.yaml
Labels: size/XS, team: team-engine
