Repository gitpod-io/gitpod, pull requests merged in 2024-09, with the labels that each got.

#20162 Update images digests
  install/installer/pkg/components/redis/constants.go
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20161 Verify new organization joinees
  components/server/src/orgs/organization-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20165 Improve JetBrains integration tests to show proper failed message
  test/tests/ide/jetbrains/gateway_test.go
  test/tests/ide/jetbrains/warmup-indexing.sh
Labels: size/S, team: team-experience, team: team-enterprise

#20164 Build patch for VS Code Browser
  WORKSPACE.yaml
Labels: size/XS, team: team-enterprise

#20166 [GP-CLI] fix `gp preview` not outputting stderr and stdout properly
  components/gitpod-cli/cmd/preview.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20160 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#20167 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20169 Switch code nightly job
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20173 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20175 [supervisor] Frontend: re-try + track "checkReady"
  components/dashboard/src/service/service.tsx
  components/gitpod-protocol/src/frontend-dashboard-service.ts
  components/gitpod-protocol/src/util/timeout.spec.ts
  components/gitpod-protocol/src/util/timeout.ts
  components/gitpod-protocol/tsconfig.json
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
  components/supervisor/frontend/src/index.ts
  components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
  components/ws-proxy/pkg/proxy/pass.go
  components/ws-proxy/pkg/proxy/routes.go
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20172 [PAPI] Retry steams upon not receiving data for 10 seconds
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/app/WebsocketClients.tsx
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-protocol/src/util/timeout.spec.ts
  components/gitpod-protocol/src/util/timeout.ts
  components/server/src/workspace/workspace-service.ts
  components/supervisor/frontend/src/ide/supervisor-service-client.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20180 Update stable JetBrains IDEs
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/L, team: team-experience, team: team-enterprise

#20181 [VS Code Browser] Build stable code `1.93.0`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20183 [VS Code Browser] Update stable code to `1.93.0`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20187 Updated license summary for npm packages
  License.third-party.npm.txt
Labels: team: team-enterprise

#20192 Revert "Switch code nightly job"
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20189 [dashboard] Potential fix for "lost workspace updates" in StartWorkspace.tsx introduced in #20095
  components/dashboard/src/start/StartWorkspace.tsx
Labels: do-not-merge/hold, size/XS, team: team-experience, team: team-enterprise

#20193 [gp] Allow update of existing user-scoped env vars
  components/gitpod-cli/cmd/env.go
  components/gitpod-cli/cmd/validate.go
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/mock.go
  components/server/src/workspace/workspace-starter.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20177 Add full clone setting for prebuilds
  components/content-service-api/go/initializer.pb.go
  components/content-service-api/initializer.proto
  components/content-service-api/typescript/src/initializer_pb.d.ts
  components/content-service-api/typescript/src/initializer_pb.js
  components/content-service/pkg/git/git.go
  components/content-service/pkg/initializer/git.go
  components/content-service/pkg/initializer/initializer.go
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/gitpod-protocol/src/wsready.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_2.golden
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.golden
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toPrebuildSettings_1.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#20198 [ws-proxy] remove cors settings
  components/ws-proxy/go.mod
  components/ws-proxy/go.sum
  components/ws-proxy/pkg/config/config.go
  components/ws-proxy/pkg/proxy/config.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
Labels: size/L, team: team-engine, team: team-enterprise

#20197 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20178 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20200 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/gha-update-image/lib/jb-stable-version.ts
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: team-experience, team: team-enterprise

#20201 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)
  components/ide/gha-update-image/index-jb-platform-update.ts
  components/ide/gha-update-image/lib/jb-update-platform-version.ts
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
Labels: size/S, team: team-experience, team: team-enterprise

#20204 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20199 [idp] Guarantee stable email address for IDP token for organization-bound users
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/go/user.go
  components/gitpod-protocol/go/user_test.go
  components/gitpod-protocol/src/protocol.ts
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
Labels: size/L, team: team-experience, team: team-enterprise

#20206 [gp] Introduce "gp user-info" showing userId and email
  components/gitpod-cli/cmd/user-info.go
Labels: size/L, team: team-experience, team: team-enterprise

#20213 [GHA] upgrade JetBrains integration tests use lib`actions/upload-arti…
  .github/workflows/jetbrains-integration-test.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20211 [VS Code Browser] Build stable code `1.93.1`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20195 Reduce required Bitbucket scopes
  components/public-api/typescript-common/src/auth-providers.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
  components/server/src/bitbucket/bitbucket-oauth-scopes.ts
  components/server/src/user/token-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20188 Updated license list for golang dependencies
  License.third-party.go.txt
Labels: size/L, team: team-enterprise

#20214 [VS Code Browser] Update stable code to `1.93.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20218 [gha] fix JetBrains Gateway upgrade script
  components/ide/gha-update-image/lib/jb-update-platform-version.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20220 [jb-gha] improve nightly script and update file structure
  .github/workflows/jetbrains-auto-update-template.yml
  components/ide/gha-update-image/BUILD.yaml
  components/ide/gha-update-image/config/jb-backend-plugin-versions.json
  components/ide/gha-update-image/index-jb-nightly.ts
  components/ide/gha-update-image/index-jb-platform-update.ts
  components/ide/gha-update-image/lib/common.ts
  components/ide/gha-update-image/lib/jb-helper/jb-gradle-task-config.ts
  components/ide/gha-update-image/lib/jb-helper/jb-helper.ts
  components/ide/gha-update-image/lib/jb-helper/jb-releases.ts
  components/ide/gha-update-image/lib/jb-stable-version.ts
  components/ide/gha-update-image/lib/jb-update-platform-version.ts
Labels: size/XXL, team: team-experience, team: team-enterprise

#20217 Enforce minimum scopes in the UI
  components/dashboard/src/user-settings/Integrations.tsx
  components/gitpod-db/src/typeorm/user-db-impl.ts
  components/public-api/typescript-common/src/auth-providers.ts
  components/server/src/auth/auth-provider-scopes.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/resource-access.ts
  components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
  components/server/src/bitbucket-server/bitbucket-server-token-handler.ts
  components/server/src/bitbucket/bitbucket-auth-provider.ts
  components/server/src/bitbucket/bitbucket-oauth-scopes.ts
  components/server/src/bitbucket/bitbucket-token-handler.ts
  components/server/src/dev/dev-data.ts
  components/server/src/github/api.ts
  components/server/src/github/github-auth-provider.ts
  components/server/src/github/github-context-parser.ts
  components/server/src/github/github-token-helper.ts
  components/server/src/github/scopes.ts
  components/server/src/gitlab/api.ts
  components/server/src/gitlab/gitlab-auth-provider.ts
  components/server/src/gitlab/gitlab-context-parser.ts
  components/server/src/gitlab/gitlab-token-helper.ts
  components/server/src/gitlab/scopes.ts
  components/server/src/test/service-testing-container-module.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20196 [ws-proxy] introduce RED metrics, including a http_version label
  components/ws-proxy/pkg/common/infoprovider.go
  components/ws-proxy/pkg/proxy/metrics.go
  components/ws-proxy/pkg/proxy/pass.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/workspacerouter.go
Labels: size/XL, team: team-engine, team: team-enterprise

#20226 Add hashed user ID cookie in analytics controller service
  components/server/src/analytics-controller.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20227 [gp] Add helpful message in case "gp env --scope=user" fails because of missing create permission
  components/gitpod-cli/cmd/env.go
  components/gitpod-cli/cmd/validate.go
Labels: size/M, team: team-experience, team: team-enterprise

#20229 refactor: Update setHashedUserIdCookie method in analytics controller
  components/server/src/analytics-controller.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20222 Cell Disabled mode
  components/dashboard/src/cell-disabled/DisabledCell.tsx
  components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
  components/dashboard/src/hooks/use-user-loader.ts
  components/gitpod-protocol/src/messaging/error.ts
  components/public-api/gitpod/v1/error.proto
  components/public-api/go/v1/error.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Error.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/error_pb.ts
  components/server/src/api/server.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20231 Implement hashed user ID cookie for analytics on Gitpod domains
  components/server/src/analytics-controller.ts
  components/server/src/session-handler.spec.db.ts
  components/server/src/session-handler.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20232 Hashed user ID cookie improvements
  components/dashboard/src/user-context.tsx
  components/server/src/auth/login-completion-handler.ts
  components/server/src/session-handler.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20233 Update Open VSX extension control manifest
  components/ide-proxy/Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20221 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20228 Prebuild trigger checks
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/prebuilds/EnablePrebuildsError.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/configuration_grpc.pb.go
  components/public-api/go/v1/v1connect/configuration.connect.go
  components/public-api/go/v1/v1connect/configuration.proxy.connect.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationServiceClient.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationServiceClientInterface.kt
  components/public-api/typescript/src/gitpod/v1/configuration_connect.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/prebuilds/bitbucket-app.ts
  components/server/src/prebuilds/bitbucket-server-app.ts
  components/server/src/prebuilds/github-app.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/prebuild-manager.spec.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20236 Upgrade platform version of JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodMetricControlProvider.kt
Labels: size/M, team: team-experience, team: team-enterprise

#20219 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20238 [Workspace CLI] better logs streaming for `validate`
  components/gitpod-cli/cmd/validate.go
  components/gitpod-cli/cmd/validate_test.go
  components/gitpod-cli/go.mod
Labels: size/L, team: team-experience, team: team-enterprise

#20240 Proper webhook installation detection
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/gitpod-protocol/src/protocol.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/go/v1/configuration_grpc.pb.go
  components/public-api/go/v1/v1connect/configuration.connect.go
  components/public-api/go/v1/v1connect/configuration.proxy.connect.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationServiceClient.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationServiceClientInterface.kt
  components/public-api/typescript/src/gitpod/v1/configuration_connect.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/auth/host-context-provider-impl.ts
  components/server/src/github/github-container-module.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/prebuilds/bitbucket-service.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/prebuilds/gitlab-service.ts
  components/server/src/projects/projects-service.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/repohost/repository-host.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20245 [Bitbucket Server] better tag context handling
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
Labels: git provider: bitbucket, size/M, team: team-experience, team: team-enterprise

#20239 [GHA] fix code nightly job
  components/ide/code/BUILD.yaml
  components/ide/code/leeway.nightly.Dockerfile
  components/ide/gha-update-image/BUILD.yaml
  components/local-app-api/typescript-grpcweb/webpack.config.js
Labels: size/L, team: team-experience, team: team-enterprise

#20241 Update images digests
  install/installer/pkg/components/redis/constants.go
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20202 Add Azure DevOps integration
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/auth-providers/auth-provider-options-query.ts
  components/dashboard/src/data/auth-providers/create-org-auth-provider-mutation.ts
  components/dashboard/src/data/auth-providers/create-user-auth-provider-mutation.ts
  components/dashboard/src/data/auth-providers/update-org-auth-provider-mutation.ts
  components/dashboard/src/data/auth-providers/update-user-auth-provider-mutation.ts
  components/dashboard/src/images/azuredevops.svg
  components/dashboard/src/provider-utils.tsx
  components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
  components/dashboard/src/user-settings/AuthEntryItem.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/gitpod-protocol/src/protocol.ts
  components/public-api/gitpod/v1/authprovider.proto
  components/public-api/go/v1/authprovider.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Authprovider.java
  components/public-api/typescript-common/fixtures/toAuthProvider_1.golden
  components/public-api/typescript-common/src/auth-providers.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/authprovider_pb.ts
  components/server/package.json
  components/server/src/api/auth-provider-service-api.ts
  components/server/src/auth/auth-provider-service.ts
  components/server/src/auth/host-container-mapping.ts
  components/server/src/azure-devops/README.md
  components/server/src/azure-devops/azure-api.spec.ts
  components/server/src/azure-devops/azure-api.ts
  components/server/src/azure-devops/azure-auth-provider.ts
  components/server/src/azure-devops/azure-container-module.ts
  components/server/src/azure-devops/azure-context-parser.spec.ts
  components/server/src/azure-devops/azure-context-parser.ts
  components/server/src/azure-devops/azure-converter.ts
  components/server/src/azure-devops/azure-file-provider.spec.ts
  components/server/src/azure-devops/azure-file-provider.ts
  components/server/src/azure-devops/azure-repository-provider.spec.ts
  components/server/src/azure-devops/azure-repository-provider.ts
  components/server/src/azure-devops/azure-token-helper.ts
  components/server/src/azure-devops/azure-token-validator.ts
  components/server/src/azure-devops/azure-urls.ts
  components/server/src/dev/dev-data.ts
  components/server/src/repohost/repo-url.spec.ts
  components/server/src/repohost/repo-url.ts
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-enterprise

#20234 Non-project repository starting restrictions
  components/dashboard/src/admin/TeamDetail.tsx
  components/dashboard/src/components/OrgMemberPermissionsOptions.tsx
  components/dashboard/src/data/organizations/members-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1727033423127-AddOrgRoleRestrictionSettings.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20235 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise
