Repository gitpod-io/gitpod, pull requests merged in 2024-08, with the labels that each got.

#20075 [gha] delete `comment-ops`
  .github/workflows/comment-ops.yaml
Labels: size/L

#20081 Fix JetBrains Plugin publish bug
  components/ide/jetbrains/gateway-plugin/build.gradle-latest.kts
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
Labels: size/S, team: team-experience, team: team-enterprise

#20082 [VS Code Browser] Build stable code `1.92.0`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20084 [VS Code Browser] Update stable code to `1.92.0`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20088 Switch code nightly job back
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20087 [readme/docs] address internal docs repository
  docs/README.md
Labels: size/XS

#20089 [dashboard] Remove `Beta` Label from Gitpod Access Tokens
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20086 [dashboard] Refactor workspace last active time tooltip
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20083 Support validate `claims` with CEL expr for SSO
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
  components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
  components/dashboard/src/teams/sso/SSOConfigForm.tsx
  components/gitpod-db/go/oidc_client_config.go
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/public-api-server/pkg/apiv1/oidc.go
  components/public-api-server/pkg/oidc/router.go
  components/public-api-server/pkg/oidc/service.go
  components/public-api-server/pkg/oidc/service_test.go
  components/public-api/gitpod/experimental/v1/oidc.proto
  components/public-api/go/experimental/v1/oidc.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Oidc.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20093 [prebuilds, workspace-gc] Fix and add tests for not showing soft-dele…
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.spec.db.ts
  components/gitpod-db/src/workspace-db.ts
  components/server/src/jobs/workspace-gc.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20092 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20095 [dashboard, server] Fix streaming of image build logs
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/data/workspaces/default-workspace-image-query.ts
  components/dashboard/src/start/StartPage.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20097 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20101 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20103 [VS Code Browser] Build stable code `1.92.1`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20100 [server] Add some tests
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket/bitbucket-context-parser.ts
  components/server/src/prebuilds/incremental-workspace-service.ts
  components/server/src/workspace/workspace-factory.spec.db.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XXL, team: team-experience, team: team-enterprise

#20105 [VS Code Browser] Update stable code to `1.92.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20106 Fix JetBrains integration tests
  dev/jetbrains-test/test.sh
Labels: size/XS

#20107 Fix workspace list grid on Safari
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20099 Organization timeout defaults
  components/dashboard/src/data/billing-mode/org-billing-mode-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1723148483807-AddOrgTimeoutSettings.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/experimental/v1/oidc_pb.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/billing/entitlement-service.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/user-service.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20109 [JetBrains] bump up latest backend plugin platform version and fix integration tests
  components/ide/jetbrains/backend-plugin/build.gradle-latest.kts
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/gateway-plugin/build.gradle-latest.kts
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle.properties
  dev/jetbrains-test/.gitignore
  dev/jetbrains-test/BUILD.yaml
  dev/jetbrains-test/test.sh
  test/tests/ide/jetbrains/base_test.go
Labels: size/M, team: team-experience, team: team-enterprise

#20111 [OIDC] IDP: use workspace.context.normalizedContextUrl to fill the "sub" and "context" claims of the IDToken
  components/public-api-server/pkg/apiv1/identityprovider.go
  components/public-api-server/pkg/apiv1/identityprovider_test.go
Labels: size/L, team: team-experience, team: team-enterprise

#20113 Fix file permissions for NFS shares
  components/ws-daemon/pkg/iws/iws.go
Labels: size/S, team: team-engine, team: team-enterprise

#20112 [image-builder] Detect "429 - Too Many Request" and bubble up as "Unavailable"
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/image-builder-mk3/pkg/resolve/resolve.go
  components/image-builder-mk3/pkg/resolve/resolve_test.go
Labels: size/M, team: team-engine, team: team-enterprise

#20119 [gha] fix incorrect runner concurrency setting
  .github/workflows/jetbrains-integration-test.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20121 [dashboard] Remove last unused feature flag references
  components/dashboard/src/data/featureflag-query.ts
Labels: team: team-experience, team: team-enterprise

#20120 [JetBrains] force upgrade IntelliJ IDEA to `2024.2`
  WORKSPACE.yaml
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: team-experience, team: team-enterprise

#20123 Fix JetBrains backend plugin not up-to-date for prebuilds
  components/ide/jetbrains/launcher/main.go
Labels: size/S, team: team-experience, team: team-enterprise

#20124 [VS Code Browser] Build stable code `1.92.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20125 Fix incorrect usage of `os.Stat`
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
Labels: size/M, team: team-experience, team: team-enterprise

#20127 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20131 [TB] limit OAuth scopes
  components/server/src/oauth-server/db.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20130 Revert "[VS Code Browser] Build stable code `1.92.2`"
  WORKSPACE.yaml
Labels: size/XS

#20134 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20135 [gha] add preview summary to images digests update PR
  .github/workflows/update-image-digest.yml
Labels: size/XS

#20133 [TB] Update respond data of joinLink2
  components/ide-service/pkg/server/server.go
  components/ide/jetbrains/launcher/main.go
Labels: size/M, team: team-experience, team: team-enterprise

#20138 Append IDEA `2024.1.4` to versions list
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/XS, team: team-experience, team: team-enterprise

#20137 Update outdated SSO docs link for Enterprise onboarding
  components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20136 [JetBrains] Upgrade Gitpod Gateway plugins and fix integration tests
  components/ide/jetbrains/gateway-plugin/BUILD.yaml
  components/ide/jetbrains/gateway-plugin/build.gradle-latest.kts
  components/ide/jetbrains/gateway-plugin/build.gradle-stable.kts
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  dev/jetbrains-test/.gitignore
  dev/jetbrains-test/BUILD.yaml
  dev/jetbrains-test/test.sh
  test/BUILD.yaml
Labels: size/XL, team: team-experience, team: team-enterprise

#20115 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#20141 Fix JetBrains Rider integration
  components/BUILD.yaml
  components/ide/gha-update-image/lib/common.ts
  components/ide/gha-update-image/lib/jb-pin-version.ts
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/build.gradle-latest.kts
  components/ide/jetbrains/backend-plugin/build.gradle-stable.kts
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle-latest-rider.properties
  components/ide/jetbrains/backend-plugin/gradle-stable-rider.properties
  components/ide/jetbrains/backend-plugin/gradle.properties
  components/ide/jetbrains/backend-plugin/src/main/resources-rider/META-INF/plugin.xml
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
  install/installer/pkg/config/versions/versions.go
Labels: size/XL, team: team-experience, team: team-enterprise

#20145 Fix Rider build on main
  components/ide/jetbrains/backend-plugin/build.gradle-latest.kts
  components/ide/jetbrains/backend-plugin/build.gradle.kts
  components/ide/jetbrains/backend-plugin/gradle-latest-rider.properties
  components/ide/jetbrains/backend-plugin/gradle-stable-rider.properties
Labels: size/S, team: team-experience, team: team-enterprise

#20146 Update Rider versions' backend-plugin image
  install/installer/pkg/components/ide-service/ide-configmap.json
  test/tests/ide/jetbrains/gateway_test.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20144 Use supervisor mount namespace for nfs mount
  components/ws-daemon/pkg/iws/iws.go
  components/ws-daemon/pkg/iws/uidmap.go
Labels: size/M, team: team-engine, team: team-enterprise

#20150 Feature flag for disabling listening for all prebuild updates
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20149 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20152 Validate redirect url
  components/dashboard/src/Login.tsx
  components/dashboard/src/OauthClientApproval.tsx
  components/dashboard/src/utils.test.ts
  components/dashboard/src/utils.ts
  components/server/src/oauth-server/oauth-controller.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20154 Improve CORS settings
  components/ws-proxy/go.mod
  components/ws-proxy/go.sum
  components/ws-proxy/pkg/config/config.go
  components/ws-proxy/pkg/proxy/config.go
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
  install/installer/pkg/common/common.go
  install/installer/pkg/common/common_test.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/L, team: staff-engineers, team: team-experience, team: team-engine, team: team-enterprise

#20157 Fix `ws-proxy` pending
  components/ws-proxy/pkg/config/config.go
  install/installer/pkg/common/common.go
Labels: size/S, team: team-engine, team: team-enterprise

#20151 Improve frontend handling of many projects
  components/dashboard/package.json
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/git-providers/suggested-repositories-query.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/data/projects/create-project-mutation.ts
  components/dashboard/src/data/projects/list-all-projects-query.ts
  components/dashboard/src/index.tsx
  components/dashboard/src/projects/project-context.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/server/src/api/scm-service-api.ts
  components/server/src/projects/projects-service.ts
  yarn.lock
Labels: size/XL, team: team-experience, team: team-enterprise

#20158 Lower fetch priority of metrics
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/metrics.ts
  components/gitpod-protocol/tsconfig.json
  components/supervisor/frontend/package.json
  components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
  yarn.lock
Labels: component: dashboard, size/S, team: team-experience, team: team-enterprise

#20156 Simplify example repositories
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/predefined-repos.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
Labels: size/M, team: team-experience, team: team-enterprise
