Repository gitpod-io/gitpod, pull requests merged in 2024-07, with the labels that each got.

#19973 Make auth cookie stricter
  components/gitpod-protocol/src/util/gitpod-host-url.ts
  components/server/go/pkg/lib/cookie.go
  components/server/src/auth/generic-auth-provider.ts
  components/server/src/auth/login-completion-handler.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/session-handler.spec.db.ts
  components/server/src/session-handler.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/user/user-controller.ts
  components/ws-proxy/pkg/proxy/routes.go
  components/ws-proxy/pkg/proxy/routes_test.go
  install/installer/pkg/components/auth/config_test.go
  install/installer/pkg/components/public-api-server/configmap_test.go
  install/installer/pkg/components/server/configmap_test.go
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#19980 [.devcontainer] fix container build
  .devcontainer/Dockerfile
Labels: size/XS

#19984 Get java feature flags from server
  components/common-go/experiments/flags.go
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/supervisor_test.go
Labels: size/M, team: staff-engineers, team: team-experience, team: team-enterprise

#19985 [VS Code Browser] switch nightly job to `1.91`
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#19989 Log query if repo is not found
  components/server/src/github/github-context-parser.ts
Labels: size/M, team: team-experience, team: team-enterprise

#19990 [server] don't allow blocked users to create workspaces
  components/server/src/workspace/workspace-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#19991 [dashboard] Onboarding: Add Gitpod repository template to New workspace component
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/predefined-repos.ts
  components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
  components/dashboard/src/icons/GitpodRepositoryTemplate.svg
  components/dashboard/src/start/start-workspace-options.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19987 [dashboard] Onboarding: new video onboarding for new workspace
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19992 [Dashboard] Show pinned status of workspaces
  .devcontainer/Dockerfile
  components/dashboard/src/components/PendingChangesDropdown.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#19996 [ws-manager] Don't skip content backup for failed prebuilds
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/ws-daemon/pkg/controller/workspace_controller.go
Labels: size/S, team: team-experience, team: team-engine, team: team-enterprise

#19968 Do not create fuse device if it already exists
  components/ws-daemon/nsinsider/main.go
Labels: size/XS, team: team-engine, team: team-enterprise

#19995 [preview] Update for gen115
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS

#19998 [dashboard] chore: Update copy texts for empty `/workspaces` page
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19999 [dashboard] feat: Add predefined repositories to `/new`
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#19997 [server] Drop old cookie migration path
  components/server/src/session-handler.spec.db.ts
  components/server/src/session-handler.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20002 [VS Code Browser] Build stable code `1.91.0`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#19982 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20001 [dashboard] minor fixes for pinning changes
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20004 [VS Code Browser] Update stable code to `1.91.0`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#19981 Update extension control manifest
  components/ide-proxy/Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20008 code: Update Nightly
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20009 [JetBrains] fix latest terminal integration broken
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/XS, team: team-experience, team: team-enterprise

#20010 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20014 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20015 [dashboard] Update Pending changes dropdown component to improve menu styling
  components/dashboard/src/components/PendingChangesDropdown.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20000 Prebuild issues roundup
  components/dashboard/package.json
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
  components/dashboard/src/utils.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/headless-workspace-log.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/buf.gen.yaml
  components/public-api/gitpod/v1/prebuild.proto
  components/public-api/go/v1/prebuild.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Dummy.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/EditorServiceOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/IdeClient.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Identityprovider.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Oidc.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/PaginationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Projects.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Scm.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Stats.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Teams.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Tokens.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/UserOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Workspaces.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Auditlogs.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Authprovider.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Editor.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Envvar.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Error.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Installation.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Pagination.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/PrebuildOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Scm.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Sorting.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Ssh.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Token.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/UserOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Verification.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/WorkspaceOuterClass.java
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/prebuild_pb.ts
  components/server/src/container-module.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/headless-log-service.ts
  components/server/src/workspace/workspace-service.ts
  components/ws-manager-bridge/src/prebuild-state-mapper.ts
Labels: size/XXL, team: team-experience, team: team-enterprise

#20016 [dashboard] imporved workspace entry layout
  components/dashboard/src/components/ItemsList.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20017 [dashboard] enable naming of workspaces
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20018 Improve empty workspace view
  components/dashboard/package.json
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  yarn.lock
Labels: component: dashboard, size/L, team: team-experience, team: team-enterprise

#20019 Fix code nightly workflow typo
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#19961 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20023 Fix changes dropdown alignment
  components/dashboard/src/components/PendingChangesDropdown.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
  yarn.lock
Labels: component: dashboard, size/M, team: team-experience, team: team-enterprise

#20024 Accessible workspace pinning
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
Labels: component: dashboard, size/M, team: team-experience, team: team-enterprise

#20027 Revert nightly job to use release `1.91`
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20021 [PAYG] [dashboard] Onboarding: Product Educational content in `/ workspaces` view
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/components/podkit/layout/PageHeading.tsx
  components/dashboard/src/icons/gitpod-stroked.svg
  components/dashboard/src/images/blog-banner-bg.png
  components/dashboard/src/workspaces/BlogBanners.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/VideoCarousel.tsx
  components/dashboard/src/workspaces/WorkspaceEntry.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/XL, team: team-experience, team: team-enterprise

#20028 Add support for opening bitbucket server tags
  components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20031 [VS Code Browser] Build stable code `1.91.1`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20032 Fix Gitpod CLI arm builds
  components/local-app/BUILD.js
Labels: size/XS, team: team-experience, team: team-enterprise

#20033 [VS Code Browser] Update stable code to `1.91.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20030 Filter out not available editors before update org and repository settings
  components/dashboard/src/components/IdeOptions.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/ide-protocol.ts
  components/gitpod-protocol/src/protocol.ts
  components/server/src/ide-service.spec.ts
  components/server/src/ide-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20006 Activity-based prebuilds
  components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
  components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Error.java
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toConfiguration_1.json
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.json
  components/public-api/typescript-common/fixtures/toPrebuildSettings_1.golden
  components/public-api/typescript-common/fixtures/toPrebuildSettings_1.json
  components/public-api/typescript-common/fixtures/toPrebuildSettings_2.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/auth/host-context-provider-impl.ts
  components/server/src/bitbucket-server/bitbucket-server-container-module.ts
  components/server/src/bitbucket/bitbucket-container-module.ts
  components/server/src/github/github-container-module.ts
  components/server/src/gitlab/gitlab-container-module.ts
  components/server/src/prebuilds/bitbucket-server-service.spec.ts
  components/server/src/prebuilds/bitbucket-server-service.ts
  components/server/src/prebuilds/bitbucket-service.ts
  components/server/src/prebuilds/constants.ts
  components/server/src/prebuilds/github-enterprise-app.ts
  components/server/src/prebuilds/github-service.ts
  components/server/src/prebuilds/gitlab-app.ts
  components/server/src/prebuilds/gitlab-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  components/server/src/repohost/repo-service.ts
  components/server/src/repohost/repository-host.ts
  components/server/src/scm/scm-service.ts
  components/server/src/test/service-testing-container-module.ts
  components/server/src/user/token-service.spec.db.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/workspace-service.ts
Labels: size/XXL, team: team-experience, team: team-enterprise

#20038 Update activity-based prebuilds tests
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toPrebuildSettings_1.golden
  components/public-api/typescript-common/fixtures/toPrebuildSettings_2.golden
Labels: size/XS, team: team-experience, team: team-enterprise

#20022 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20029 Fix not able to open workspace with nightly code
  .github/workflows/code-nightly.yml
  components/server/src/workspace/workspace-starter.ts
  install/installer/pkg/components/blobserve/configmap.go
Labels: size/S

#20034 [PAYG - dashboard]: Implement Personalised content selection for users based on profile
  components/dashboard/src/icons/gitpod-stroked.svg
  components/dashboard/src/workspaces/PersonalizedContent.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XL, team: team-experience, team: team-enterprise

#20035 [server] allow configure timeouts via featureflag
  components/server/src/billing/entitlement-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20041 Fix very tall modals
  components/dashboard/src/components/Modal.tsx
Labels: component: dashboard, size/M, team: team-experience, team: team-enterprise

#20042 [dashboard] Update `enabling` role
  components/dashboard/src/onboarding/job-roles.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20040 Track used prebuild strategy with started repositories
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20039 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20044 Uniq onboarding answers before update
  components/dashboard/src/data/current-user/update-mutation.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20043 Fix permissions checks for stopping prebuilds
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/workspace-service.ts
  components/supervisor/pkg/supervisor/tasks.go
Labels: size/S, team: team-experience, team: team-enterprise

#20045 Update images digests
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20047 Fix incorrect redirects to newer prebuilds
  components/dashboard/src/data/prebuilds/prebuild-queries.ts
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
  components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#20049 [TB] add OAuth entry
  components/server/src/oauth-server/db.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20051 [TB] allow to config launcher from Dashboard
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/service/service.tsx
  components/dashboard/src/user-settings/SelectIDE.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/go/gitpod-service.go
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/ide-service/example-ide-config.json
  components/ide-service/pkg/server/server.go
  components/ide/jetbrains/launcher/main.go
  components/public-api/buf.gen.yaml
  components/public-api/gitpod/v1/editor.proto
  components/public-api/go/v1/editor.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Editor.java
  components/public-api/typescript-common/fixtures/toUser_1.golden
  components/public-api/typescript-common/fixtures/toUser_1.json
  components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/editor_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/oauth-server/db.ts
  components/server/src/oauth-server/oauth-controller.ts
  components/server/src/util/featureflags.ts
  components/server/src/workspace/workspace-starter.ts
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/XL, team: team-experience, team: team-enterprise

#20050 Don't show repo examples around prebuilds
  components/dashboard/src/components/RepositoryFinder.tsx
Labels: component: dashboard, size/M, team: team-experience, team: team-enterprise

#20048 Be more helpful when there is no image build for prebuilds
  components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
Labels: component: dashboard, size/S, team: team-experience, team: team-enterprise

#20053 [dashboard] Fix duration displaying (no "undefinedh")
  components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20055 [ws-manager-bridge] Persist before publishing any update to maintain consistency guarantees
  components/ws-manager-bridge/src/bridge.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20052 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20054 [audit log] Fix audit log persistence
  components/gitpod-db/src/typeorm/entity/db-audit-log.ts
  components/gitpod-db/src/typeorm/transformer.ts
  components/gitpod-protocol/src/util/stringify.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/server/src/api/server.ts
  components/server/src/audit/AuditLogService.spec.db.ts
  components/server/src/audit/AuditLogService.ts
  components/server/src/websocket/websocket-connection-manager.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20058 Bump xterm IDE
  WORKSPACE.yaml
  components/ide/xterm/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20059 [ws-manager-mk2] log the stop reason
  components/ws-manager-mk2/controllers/metrics.go
Labels: size/XS, team: team-engine, team: team-enterprise

#20060 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20057 Various prebuild fixes
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/public-api/typescript-common/src/prebuild-utils.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/tasks.go
Labels: size/L, team: team-experience, team: team-enterprise

#20063 Upgrade xterm to v5.5.0
  components/dashboard/package.json
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/gitpod-db/package.json
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-enterprise

#20066 Bump xterm
  WORKSPACE.yaml
Labels: size/XS

#20065 Buffer logs to not overflow xterm
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/utils.ts
Labels: component: dashboard, size/M, team: team-experience, team: team-enterprise

#20064 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20067 Implement `gp tasks stop --force-success`
  components/gitpod-cli/cmd/tasks-stop.go
  components/supervisor-api/go/terminal.pb.go
  components/supervisor-api/go/terminal.pb.gw.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TerminalOuterClass.java
  components/supervisor-api/terminal.proto
  components/supervisor/pkg/supervisor/tasks.go
  components/supervisor/pkg/terminal/service.go
  components/supervisor/pkg/terminal/terminal.go
Labels: size/M, team: team-experience, team: team-engine, team: team-enterprise

#20062 [supervisor] Make sure we read the last chunk of message when task is closed
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/WorkspaceLogs.tsx
  components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
  components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/gitpod-protocol/src/protocol.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/headless-log-controller.ts
  components/server/src/workspace/headless-log-service.ts
  components/server/src/workspace/workspace-service.ts
  components/supervisor/pkg/supervisor/services.go
Labels: size/XL, team: team-experience, team: team-enterprise

#20070 Switch code nightly job to `1.92`
  .github/workflows/code-nightly.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20069 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20061 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#19958 [JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience
