Repository gitpod-io/gitpod, pull requests merged in 2024-11, with the labels that each got.

#20342 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20339 [.gitpod.yml] Introduce top-level `env`
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/src/protocol.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20319 [JBGateway] connection-based client side additional heartbeat
  components/ide/jetbrains/gateway-plugin/build.gradle.kts
  components/ide/jetbrains/gateway-plugin/gradle.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodSettingsConfigurable.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodSettingsState.kt
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
  components/supervisor-api/control.proto
  components/supervisor-api/go/control.pb.go
  components/supervisor-api/go/control.pb.gw.go
  components/supervisor-api/go/control_grpc.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Control.java
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/ControlServiceGrpc.java
  components/supervisor/pkg/serverapi/publicapi.go
  components/supervisor/pkg/supervisor/services.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XL, team: team-experience, team: team-enterprise

#20343 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20340 Revert "Add Flex webinar notification banner" & Bring back AWS re:Invent banner
  components/dashboard/src/AppNotifications.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20346 Update images digests
  install/installer/pkg/components/redis/constants.go
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20348 [tests] fix JetBrains warmup integration test
  test/tests/ide/jetbrains/warmup-indexing.sh
Labels: size/XS, team: team-experience, team: team-enterprise

#20349 [gha] prevent slack notifications for skipped JetBrains nightly builds
  .github/workflows/jetbrains-auto-update-template.yml
Labels: size/S, team: team-experience, team: team-enterprise

#20316 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20344 [observability] Introduce "ReplicaUnavailable" alerts
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
  operations/observability/mixins/workspace/rules/central/node-labeler.yaml
  operations/observability/mixins/workspace/rules/central/ws-manager.yaml
  operations/observability/mixins/workspace/rules/central/ws-proxy.yaml
Labels: size/M, team: team-engine, team: team-enterprise

#20320 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodSettingsConfigurable.kt
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20345 [context parser] Check current ref for Docker image existence
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-protocol/src/protocol.ts
  components/image-builder-bob/cmd/build.go
  components/image-builder-bob/pkg/builder/config.go
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/workspace.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/WorkspaceOuterClass.java
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/server/src/api/workspace-service-api.ts
  components/server/src/azure-devops/azure-file-provider.ts
  components/server/src/bitbucket-server/bitbucket-server-file-provider.ts
  components/server/src/bitbucket/bitbucket-file-provider.ts
  components/server/src/github/file-provider.ts
  components/server/src/gitlab/file-provider.ts
  components/server/src/repohost/file-provider.ts
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/context-parser-service.ts
  components/server/src/workspace/image-source-provider.ts
  components/server/src/workspace/workspace-factory.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#20352 Fix public API test on `main`
  components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_2.golden
  components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
  components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
Labels: size/S, team: team-experience, team: team-enterprise

#20354 Log edge case for `updateDeletionEligibilityTime`
  components/server/src/workspace/workspace-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20351 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/S, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20358 [server] Add more tests around "prebuild selection"
  components/server/src/prebuilds/incremental-workspace-service.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/context-service.spec.db.ts
  components/server/src/workspace/context-service.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20364 Fix Bitbucket Server repository provider tests
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20361 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20363 Fix GitHub Integration tests
  components/server/src/dev/dev-data.ts
  components/server/src/errors/index.ts
  components/server/src/github/github-context-parser.spec.ts
  components/server/src/github/github-repository-provider.spec.ts
  components/server/src/github/github-repository-provider.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20365 Fix Dockerfile paths with relative decorators
  components/server/src/workspace/config-provider.ts
  components/server/src/workspace/image-source-provider.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20369 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20243 [ws-manager] Re-create workspace pods on rejection
  components/ws-daemon-api/go/mock/mock.go
  components/ws-daemon-api/go/workspace_daemon.pb.go
  components/ws-daemon-api/go/workspace_daemon_grpc.pb.go
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_grpc_pb.js
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.d.ts
  components/ws-daemon-api/typescript/src/workspace_daemon_pb.js
  components/ws-daemon-api/workspace_daemon.proto
  components/ws-daemon/pkg/cgroup/cgroup.go
  components/ws-daemon/pkg/container/container.go
  components/ws-daemon/pkg/container/containerd.go
  components/ws-daemon/pkg/content/hooks.go
  components/ws-daemon/pkg/controller/mock.go
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-daemon/pkg/cpulimit/dispatch.go
  components/ws-daemon/pkg/daemon/daemon.go
  components/ws-daemon/pkg/daemon/markunmount.go
  components/ws-daemon/pkg/diskguard/guard.go
  components/ws-daemon/pkg/dispatch/dispatch.go
  components/ws-daemon/pkg/internal/session/workspace.go
  components/ws-daemon/pkg/iws/iws.go
  components/ws-daemon/pkg/netlimit/netlimit.go
  components/ws-daemon/pkg/nsinsider/nsinsider.go
  components/ws-manager-api/go/config/config.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/controllers/metrics.go
  components/ws-manager-mk2/controllers/status.go
  components/ws-manager-mk2/controllers/subscriber_controller.go
  components/ws-manager-mk2/controllers/suite_test.go
  components/ws-manager-mk2/controllers/workspace_controller.go
  components/ws-manager-mk2/controllers/workspace_controller_test.go
  dev/gpctl/cmd/workspaces-list.go
  dev/rejector/.gitignore
  dev/rejector/go.mod
  dev/rejector/go.sum
  dev/rejector/main.go
Labels: size/XXL, team: team-experience, team: team-engine, team: team-enterprise

#20372 [ws-manager] don't ever set PodRejected if WorkspaceConditionEverReady=true
  components/ws-manager-mk2/controllers/status.go
Labels: size/S, team: team-engine, team: team-enterprise

#20360 Fix prebuild lookup for prebuilds run in reverse-chronological order
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/prebuilds/incremental-workspace-service.ts
  components/server/src/workspace/context-service.spec.db.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20371 [VS Code Browser] Build stable code `1.95.3`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20370 JetBrains IDEs `2024.3` stable release
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/BUILD.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionHandleFactoryImpl.kt
  components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/L, team: team-experience, team: team-enterprise

#20375 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20377 [scrubber] Changes to allow to extend scrubber (for scrubbing of genie data))
  components/scrubber/scrubber.go
Labels: size/M

#20376 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20379 Fix SCM integration tests and run them on build
  .github/workflows/build.yml
  components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-api.ts
  components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
  components/server/src/github/github-repository-provider.ts
  components/server/src/gitlab/gitlab-context-parser.spec.ts
  components/server/src/gitlab/gitlab-repository-provider.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20381 Fix middot for VS Code desktop in IDE selector
  components/dashboard/src/components/SelectIDEComponent.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20380 [supervisor] init: Add logging around termination
  components/supervisor/cmd/init.go
Labels: size/S, team: team-experience, team: team-enterprise

#20384 [code] Fix gitpod-web dockerfile
  WORKSPACE.yaml
  components/ide/code/gitpod-web-extension/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20385 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/M, team: IDE, team: team-experience, team: team-enterprise

#20383 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20388 [dashboard] Refactor Login layout and messaging for Gitpod Classic users
  components/dashboard/src/Login.tsx
  components/dashboard/src/images/gitpod-classic-card.png
Labels: size/L, team: team-experience, team: team-enterprise

#20387 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  dev/preview/workflow/preview/patch-ide-configmap.js
  install/installer/pkg/components/ide-service/ide-configmap.json
  install/installer/pkg/components/ide-service/ide_config_configmap.go
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20386 Branch Protection Monitor Workflow
  .github/workflows/Monitor Branch Protection Changes.yml
Labels: size/XL

#20395 [preview] update to gen117 image
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: team-enterprise

#20399 Clean up `repositoryFinderSearch` feature flag
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/git-providers/search-repositories-query.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
  components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20400 Don't be so chatty when `hasReadAccess` throws
  components/server/src/bitbucket/bitbucket-repository-provider.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20397 [tests] show dotfile installing failure reason
  test/tests/components/ws-manager/dotfiles_test.go
Labels: size/S

#20405 [papi] add editor info to experimental.v1
  components/gitpod-protocol/go/gitpod-service.go
  components/public-api-server/pkg/apiv1/workspace.go
  components/public-api/gitpod/experimental/v1/workspaces.proto
  components/public-api/go/experimental/v1/workspaces.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/experimental/v1/Workspaces.java
  components/public-api/typescript/src/gitpod/experimental/v1/workspaces_pb.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20406 [papi] fix unit tests for workspaces service
  components/public-api-server/pkg/apiv1/workspace.go
Labels: size/XS, team: team-experience, team: team-enterprise

#20408 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20402 [server] fix more revealing BB error logs
  components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
  components/server/src/bitbucket-server/utils.ts
  components/server/src/bitbucket/bitbucket-context-parser.ts
  components/server/src/bitbucket/bitbucket-file-provider.ts
  components/server/src/bitbucket/bitbucket-repository-provider.ts
Labels: size/M, team: team-experience, team: team-enterprise
