Repository gitpod-io/gitpod, pull requests merged in 2025-02, with the labels that each got.

#20559 Organization-recommended repositories
  components/dashboard/package.json
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/components/podkit/dropdown/DropDown.tsx
  components/dashboard/src/data/git-providers/predefined-repos.ts
  components/dashboard/src/data/organizations/suggested-repositories-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/dashboard/src/teams/TeamOnboarding.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  yarn.lock
Labels: size/XL, team: team-experience, team: team-enterprise

#20578 CI: use latest Configcat GHA
  .github/workflows/configcat.yml
Labels: size/XS

#20568 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20582 Repo suggestions improvements
  components/dashboard/src/components/RepositoryFinder.tsx
  components/dashboard/src/data/git-providers/predefined-repos.ts
  components/dashboard/src/insights/download/DownloadInsights.tsx
  components/dashboard/src/repositories/detail/ConfigurationDetailGeneral.tsx
  components/dashboard/src/repositories/detail/general/ManageRepoSuggestion.tsx
  components/dashboard/src/repositories/list/RepoListItem.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/dashboard/src/teams/TeamOnboarding.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XL, team: team-experience, team: team-enterprise

#20583 [dashboard] Don't show User Notifications and Feedback on Dedicated
  components/dashboard/src/Insights.tsx
  components/dashboard/src/data/installation/default-workspace-image-query.ts
  components/dashboard/src/data/installation/installation-config-query.ts
  components/dashboard/src/dedicated-setup/use-needs-setup.ts
  components/dashboard/src/dedicated-setup/use-show-dedicated-setup.ts
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/teams/OrgSettingsPage.tsx
  components/dashboard/src/teams/policies/MaxParallelWorkspaces.tsx
  components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20593 Add permission check for Insights page and don't show it in the menu for non-owners
  components/dashboard/src/Insights.tsx
  components/dashboard/src/menu/OrganizationSelector.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20586 [docker-up] Auto-login dockerd if GITPOD_IMAGE_AUTH is set
  components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
  components/dashboard/src/repositories/detail/variables/EnableDockerdAuthentication.tsx
  components/docker-up/BUILD.yaml
  components/docker-up/docker-up/main.go
  components/docker-up/dockerd/args.go
  components/docker-up/dockerd/args_test.go
  components/docker-up/go.mod
  components/docker-up/go.sum
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/image-builder-bob/cmd/proxy.go
  components/image-builder-bob/pkg/proxy/auth.go
  components/image-builder-bob/pkg/proxy/auth_test.go
  components/public-api/gitpod/v1/configuration.proto
  components/public-api/go/v1/configuration.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/ConfigurationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/configuration_pb.ts
  components/server/src/api/configuration-service-api.ts
  components/server/src/projects/projects-service.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/docker.go
  components/supervisor/pkg/supervisor/docker_test.go
  components/ws-manager-mk2/controllers/create.go
Labels: size/XXL, team: team-experience, team: team-engine, team: team-enterprise

#20368 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#20600 [dashboard] Remove shutdown notice
  components/dashboard/src/Login.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20601 Fix main build
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_2.golden
  components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.golden
  components/public-api/typescript-common/fixtures/toConfiguration_1.golden
  components/public-api/typescript-common/fixtures/toConfiguration_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_2.golden
  components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.golden
Labels: size/M, team: team-experience, team: team-enterprise

#20549 Make JetBrains backend plugin compatible with `2025.1`
  .github/workflows/jetbrains-update-plugin-platform-template.yml
  components/ide/jetbrains/backend-plugin/gradle-latest.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Labels: size/M, team: team-experience, team: team-enterprise

#20592 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20577 Organization onboarding welcome message
  components/dashboard/package.json
  components/dashboard/src/components/forms/InputField.tsx
  components/dashboard/src/components/podkit/forms/TextArea.tsx
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/index.css
  components/dashboard/src/login/SSOLoginForm.tsx
  components/dashboard/src/repositories/detail/general/ManageRepoSuggestion.tsx
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/TeamOnboarding.tsx
  components/dashboard/src/teams/TeamPolicies.tsx
  components/dashboard/src/teams/onboarding/OrgMemberAvatarInput.tsx
  components/dashboard/src/teams/onboarding/OrganizationJoinModal.tsx
  components/dashboard/src/teams/onboarding/WelcomeMessageConfigurationField.tsx
  components/dashboard/src/teams/onboarding/WelcomeMessageEditor.tsx
  components/dashboard/src/teams/onboarding/WelcomeMessagePreview.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/gitpod-db/package.json
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/package.json
  components/server/src/api/organization-service-api.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/projects/projects-service.spec.db.ts
  components/server/src/projects/projects-service.ts
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-enterprise

#20585 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20611 Update images digests
  install/installer/leeway.Dockerfile
Labels: size/XS, release-note-none, automated pr, kind/cleanup

#20530 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20612 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#20618 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20627 [components] include scheduler-extender:docker in all-docker build
  .github/CODEOWNERS
  components/BUILD.yaml
Labels: size/XS, team: leadership, team: team-enterprise

#20632 [memory bank] Initialize cline memory bank
  memory-bank/.clinerules
  memory-bank/activeContext.md
  memory-bank/components/blobserve.md
  memory-bank/components/common-go.md
  memory-bank/components/content-service.md
  memory-bank/components/dashboard.md
  memory-bank/components/docker-up.md
  memory-bank/components/gitpod-cli.md
  memory-bank/components/gitpod-db.md
  memory-bank/components/gitpod-protocol.md
  memory-bank/components/ide-metrics.md
  memory-bank/components/ide-proxy.md
  memory-bank/components/ide-service.md
  memory-bank/components/ide.md
  memory-bank/components/image-builder-bob.md
  memory-bank/components/image-builder-mk3.md
  memory-bank/components/ipfs.md
  memory-bank/components/local-app.md
  memory-bank/components/node-labeler.md
  memory-bank/components/openvsx-proxy.md
  memory-bank/components/proxy.md
  memory-bank/components/public-api-server.md
  memory-bank/components/registry-facade.md
  memory-bank/components/scheduler-extender.md
  memory-bank/components/scrubber.md
  memory-bank/components/server.md
  memory-bank/components/service-waiter.md
  memory-bank/components/spicedb.md
  memory-bank/components/supervisor.md
  memory-bank/components/usage.md
  memory-bank/components/workspacekit.md
  memory-bank/components/ws-daemon.md
  memory-bank/components/ws-manager-bridge.md
  memory-bank/components/ws-manager-mk2.md
  memory-bank/components/ws-proxy.md
  memory-bank/productContext.md
  memory-bank/progress.md
  memory-bank/projectbrief.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: size/XXL

#20613 [server] add feature flags for spicedb client options
  components/server/src/authorization/spicedb.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20572 Add more initializer-related info to /insights API
  components/content-service/pkg/initializer/initializer.go
  components/dashboard/src/Insights.tsx
  components/dashboard/src/insights/download/download-sessions.ts
  components/gitpod-db/src/typeorm/entity/db-workspace-instance-metrics.ts
  components/gitpod-db/src/typeorm/migration/1739892121734-AddWorkspaceInstanceMetricsTable.ts
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
  components/gitpod-db/src/workspace-db.ts
  components/gitpod-protocol/src/protocol.ts
  components/gitpod-protocol/src/workspace-instance.ts
  components/public-api/gitpod/v1/workspace.proto
  components/public-api/go/v1/workspace.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/WorkspaceOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/workspace_pb.ts
  components/ws-daemon/cmd/content-initializer.go
  components/ws-daemon/cmd/content-initializer/main.go
  components/ws-daemon/cmd/debug-run-initializer.go
  components/ws-daemon/debug.Dockerfile
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/controller/mock.go
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/controller/workspace_controller_test.go
  components/ws-daemon/pkg/controller/workspace_operations.go
  components/ws-manager-api/core.proto
  components/ws-manager-api/go/core.pb.go
  components/ws-manager-api/go/core_grpc.pb.go
  components/ws-manager-api/go/crd/v1/workspace_types.go
  components/ws-manager-api/go/mock/mock.go
  components/ws-manager-api/typescript/src/core_grpc_pb.d.ts
  components/ws-manager-api/typescript/src/core_grpc_pb.js
  components/ws-manager-api/typescript/src/core_pb.d.ts
  components/ws-manager-api/typescript/src/core_pb.js
  components/ws-manager-bridge/src/bridge.ts
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_snapshots.yaml
  components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
  components/ws-manager-mk2/config/webhook/manifests.yaml
  components/ws-manager-mk2/service/manager.go
Labels: size/XXL, team: team-experience, team: team-engine, team: team-enterprise

#20629 [VS Code Browser] Build stable code `1.97.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20633 [ide-proxy] update extension control manifest
  components/ide-proxy/Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20638 [ws-daemon] Fix panix in tests
  components/ws-daemon/pkg/controller/workspace_controller.go
Labels: size/XS, team: team-engine, team: team-enterprise

#20639 [memory-bank] Update with more details
  memory-bank/.clinerules
  memory-bank/activeContext.md
  memory-bank/components/content-service-api.md
  memory-bank/components/ide-metrics-api.md
  memory-bank/components/ide-service-api.md
  memory-bank/components/image-builder-api.md
  memory-bank/components/local-app-api.md
  memory-bank/components/registry-facade-api.md
  memory-bank/components/supervisor-api.md
  memory-bank/components/usage-api.md
  memory-bank/components/ws-daemon-api.md
  memory-bank/components/ws-manager-api.md
  memory-bank/components/ws-manager-bridge-api.md
  memory-bank/progress.md
  memory-bank/techContext.md
Labels: size/XXL

#20640 [VS Code Browser] Update stable code to `1.97.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise
