Repository gitpod-io/gitpod, pull requests merged in 2025-01, with the labels that each got.

#20466 [dashboard] Fix Arc favourites
  components/dashboard/src/components/podkit/buttons/LinkButton.tsx
  components/dashboard/src/start/StartWorkspace.tsx
Labels: meta: stale, size/M, team: team-experience, team: team-enterprise

#20497 [server] log all deletion eligibility time updates
  components/gitpod-protocol/go/gitpod-config-types.go
  components/server/src/workspace/workspace-service.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20501 [.github] bump update image digests create-pull-request step dependency
  .github/workflows/update-image-digest.yml
Labels: size/XS

#20489 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20428 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20467 [dashboard] Insights page improvements
  components/dashboard/.vscode/settings.json
  components/dashboard/src/Insights.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#20519 [VS Code Browser] Build stable code `1.96.3`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20521 [VS Code Browser] Update stable code to `1.96.3`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20511 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20520 [dashboard] Add org resources to the top of the workspace list
  components/dashboard/src/components/Modal.tsx
  components/dashboard/src/components/PillLabel.tsx
  components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
  components/dashboard/src/user-settings/Preferences.tsx
  components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
  components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
  components/server/src/api/organization-service-api.ts
Labels: size/XL, team: team-experience, team: team-enterprise

#20529 [gha] Update actions/upload-artifact@v3 -> actions/upload-artifact@v4
  .github/actions/integration-tests/action.yml
  .github/workflows/jetbrains-integration-test.yml
Labels: size/XS, team: team-experience, team: team-enterprise

#20505 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20526 [dev] Update workspace libraries to match kubernetes (containerd, runc, buildkit)
  WORKSPACE.yaml
  components/blobserve/cmd/run.go
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/blobserve/pkg/blobserve/blobserve.go
  components/blobserve/pkg/blobserve/refstore.go
  components/common-go/go-update-wc-deps.sh
  components/ide-service/go.mod
  components/ide-service/go.sum
  components/ide-service/pkg/ocitool/resolve.go
  components/image-builder-bob/cmd/daemon.go
  components/image-builder-bob/cmd/proxy.go
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/image-builder-mk3/pkg/resolve/resolve_test.go
  components/registry-facade/cmd/run.go
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/registry-facade/pkg/registry/registry.go
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
  components/ws-daemon/pkg/content/initializer.go
  components/ws-daemon/pkg/controller/workspace_controller.go
  components/ws-daemon/pkg/libcontainer/README.md
  components/ws-daemon/pkg/libcontainer/specconv/example.go
  components/ws-daemon/pkg/libcontainer/specconv/spec_linux.go
  components/ws-daemon/seccomp-profile-installer/go.mod
  components/ws-daemon/seccomp-profile-installer/go.sum
  gitpod-ws.code-workspace
  install/installer/go.mod
  install/installer/go.sum
  install/installer/pkg/components/agent-smith/daemonset.go
  install/installer/pkg/components/blobserve/deployment.go
  install/installer/pkg/components/content-service/deployment.go
  install/installer/pkg/components/docker-registry/secret.go
  install/installer/pkg/components/ide-metrics/deployment.go
  install/installer/pkg/components/ide-service/deployment.go
  install/installer/pkg/components/image-builder-mk3/deployment.go
  install/installer/pkg/components/openvsx-proxy/statefulset.go
  install/installer/pkg/components/proxy/deployment.go
  install/installer/pkg/components/public-api-server/deployment.go
  install/installer/pkg/components/registry-facade/daemonset.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/spicedb/deployment.go
  install/installer/pkg/components/usage/deployment.go
  install/installer/pkg/components/ws-daemon/daemonset.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
  install/installer/pkg/components/ws-manager-mk2/deployment.go
  install/installer/pkg/components/ws-proxy/deployment.go
Labels: size/XXL, team: staff-engineers, team: team-experience, team: team-engine, team: team-enterprise

#20509 [node-labeler] Introduce workspace count controller
  components/node-labeler/BUILD.yaml
  components/node-labeler/cmd/root.go
  components/node-labeler/cmd/run.go
  components/node-labeler/cmd/run_test.go
  components/node-labeler/crd/workspace.gitpod.io_workspaces.yaml
  components/node-labeler/go.mod
  components/node-labeler/go.sum
  install/installer/pkg/components/node-labeler/role.go
Labels: size/XXL, team: team-engine, team: team-enterprise

#20536 Auto-configure default JVM Xmx based on workspace resources
  components/ide/jetbrains/launcher/main.go
  components/ide/jetbrains/launcher/main_test.go
  components/ws-manager-mk2/controllers/create.go
  dev/preview/workflow/preview/deploy-gitpod.sh
Labels: size/M, team: team-experience, team: team-engine, team: team-enterprise

#20534 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20540 [JetBrains] wait for the file to be closed before returning
  .idea/misc.xml
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
Labels: size/S, team: team-experience, team: team-enterprise

#20524 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20538 Introduce org-level GITPOD_IMAGE_AUTH
  components/dashboard/src/data/organizations/org-envvar-queries.ts
  components/dashboard/src/service/json-rpc-envvar-client.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/variables/NamedOrganizationEnvvarItem.tsx
  components/dashboard/src/teams/variables/OrganizationRemoveEnvvarModal.tsx
  components/gitpod-db/src/project-db.ts
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/entity/db-org-env-var.ts
  components/gitpod-db/src/typeorm/migration/1737449780009-OrgEnvVars.ts
  components/gitpod-db/src/typeorm/project-db-impl.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/protocol.ts
  components/public-api/gitpod/v1/envvar.proto
  components/public-api/go/v1/envvar.pb.go
  components/public-api/go/v1/envvar_grpc.pb.go
  components/public-api/go/v1/v1connect/envvar.connect.go
  components/public-api/go/v1/v1connect/envvar.proxy.connect.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/EnvironmentVariableServiceClient.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/EnvironmentVariableServiceClientInterface.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/Envvar.java
  components/public-api/typescript-common/fixtures/toOrganizationEnvironmentVariable_1.golden
  components/public-api/typescript-common/fixtures/toOrganizationEnvironmentVariable_1.json
  components/public-api/typescript-common/src/public-api-converter.spec.ts
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/envvar_connect.ts
  components/public-api/typescript/src/gitpod/v1/envvar_pb.ts
  components/server/src/api/envvar-service-api.ts
  components/server/src/authorization/definitions.ts
  components/server/src/user/env-var-service.spec.db.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience, team: team-enterprise

#20525 Add optional, org-wide Gitpod commit annotation
  components/dashboard/src/data/featureflag-query.ts
  components/dashboard/src/data/organizations/update-org-settings-mutation.ts
  components/dashboard/src/teams/TeamSettings.tsx
  components/gitpod-cli/cmd/git-commit-message-helper.go
  components/gitpod-cli/cmd/git-commit-message-helper_test.go
  components/gitpod-db/src/typeorm/entity/db-team-settings.ts
  components/gitpod-db/src/typeorm/migration/1737714449389-AddOrgSettingsCommitAnnotation.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/typescript-common/src/public-api-converter.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/supervisor/pkg/supervisor/config.go
  components/supervisor/pkg/supervisor/supervisor.go
Labels: size/XL, team: team-experience, team: team-enterprise

#20547 [dashboard] team setting design polish + more consistent color use
  components/dashboard/src/components/ContextMenu.tsx
  components/dashboard/src/components/EmptyMessage.tsx
  components/dashboard/src/components/ItemsList.tsx
  components/dashboard/src/components/PrebuildLogs.tsx
  components/dashboard/src/components/UsageBasedBillingConfig.tsx
  components/dashboard/src/components/typography/headings.tsx
  components/dashboard/src/feedback-form/FeedbackComponent.tsx
  components/dashboard/src/index.css
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/onboarding/LinkedInBanner.tsx
  components/dashboard/src/prebuilds/list/PrebuildListEmptyState.tsx
  components/dashboard/src/prebuilds/list/PrebuildTable.tsx
  components/dashboard/src/repositories/list/RepoListEmptyState.tsx
  components/dashboard/src/repositories/list/RepositoryTable.tsx
  components/dashboard/src/start/StartWorkspace.tsx
  components/dashboard/src/teams/NewTeam.tsx
  components/dashboard/src/teams/TeamOnboarding.tsx
  components/dashboard/src/teams/TeamSettings.tsx
  components/dashboard/src/teams/variables/NamedOrganizationEnvvarItem.tsx
  components/dashboard/src/usage/UsageView.tsx
  components/dashboard/src/user-settings/EnvironmentVariables.tsx
  components/dashboard/src/user-settings/Integrations.tsx
  components/dashboard/src/user-settings/PersonalAccessTokens.tsx
  components/dashboard/src/user-settings/ShowTokenModal.tsx
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XL, team: team-experience, team: team-enterprise

#20555 [dashboard] re-order org docker auth config
  components/dashboard/src/dedicated-setup/SetupLayout.tsx
  components/dashboard/src/teams/TeamSettings.tsx
Labels: size/M, team: team-experience, team: team-enterprise

#20543 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20560 [server] Add organization image auth context to workspace image validation
  components/server/src/container-module.ts
  components/server/src/orgs/default-workspace-image-validator.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/user/env-var-service.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20565 [server] make gRPC clients viable in non-HTTP/2-compatible environments
  components/dashboard/src/service/public-api.ts
  components/dashboard/src/service/service.tsx
  components/gitpod-db/src/redis/publisher.ts
  components/gitpod-protocol/src/redis.ts
  components/server/src/messaging/redis-subscriber.ts
  components/server/src/prebuilds/prebuild-manager.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/prebuild-updater.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20544 [JetBrains] display workspace name on the navbar
  components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
  components/gitpod-protocol/src/protocol.ts
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodGatewayClientCustomizationProvider.kt
  components/server/src/workspace/workspace-starter.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20569 [server] Don't block soft deletion rewinds in `updateDeletionEligibilityTime`
  components/server/src/workspace/workspace-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise
