Repository gitpod-io/gitpod, pull requests merged in 2025-08, with the labels that each got.

#20990 Add netcat and redis-tools to devcontainer
  .devcontainer/Dockerfile
Labels: size/XS

#20992 Fix environment variable parsing for comma-separated values in CLI
  components/gitpod-cli/cmd/env.go
Labels: team: team-enterprise

#21010 [agent-smith] introduce file detector
  components/ee/agent-smith/example-config.json
  components/ee/agent-smith/pkg/agent/agent.go
  components/ee/agent-smith/pkg/classifier/classifier.go
  components/ee/agent-smith/pkg/classifier/filesystem_test.go
  components/ee/agent-smith/pkg/classifier/sinature.go
  components/ee/agent-smith/pkg/config/config.go
  components/ee/agent-smith/pkg/config/config_test.go
  components/ee/agent-smith/pkg/detector/filesystem.go
  components/ee/agent-smith/pkg/detector/filesystem_test.go
  dev/preview/workflow/preview/deploy-gitpod.sh
  install/installer/pkg/components/agent-smith/configmap.go
  install/installer/pkg/components/agent-smith/constants.go
  install/installer/pkg/components/agent-smith/daemonset.go
Labels: size/XXL, team: team-enterprise
