Repository gitpod-io/gitpod, pull requests merged in 2025-07, with the labels that each got.

#20933 [server] Fix mismatch collation issue in workspace instance metrics query
  components/gitpod-db/src/typeorm/workspace-db-impl.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20922 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20966 [dev] Improve devcontainer, add automations
  .devcontainer/devcontainer.json
  .gitignore
  .gitpod/automations.yaml
  dev/install-dependencies.sh
Labels: size/L

#20971 [dev] Automatically authorize gh
  .devcontainer/devcontainer.json
  .gitpod.yml
  dev/github-token.sh
  dev/setup-github-auth.sh
Labels: size/M

#20968 [server] Implement context env var validation behind context_env_var_validation feature flag
  components/server/src/util/featureflags.ts
  components/server/src/workspace/envvar-prefix-context-parser.spec.ts
  components/server/src/workspace/envvar-prefix-context-parser.ts
Labels: size/XXL, team: team-enterprise

#20976 Unblock Ona on Classic: Fix SDKMAN_DIR mismatch in Flex environments
  .devcontainer/Dockerfile
Labels: size/S

#20973 [VS Code Browser] Build stable code `1.102.3`
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise
