Repository gitpod-io/gitpod, pull requests merged in 2025-04, with the labels that each got.

#20724 Minimal change
  README.md
Labels: size/XS

#20726 [installer] Avoid https://tldr.fail
  install/installer/pkg/common/common.go
Labels: size/XS

#20732 [db] Migrations image: explicitly add bash
  components/gitpod-db/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20733 [trivy] Drop superfluous trivyignore entries as follow up to #20694
  scripts/trivy/trivyignore.yaml
Labels: size/M

#20747 Patch build VSCode Browser 1.98
  WORKSPACE.yaml
Labels: size/XS

#20748 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20752 [common-go] continue on hashConfig errors
  components/common-go/watch/file.go
Labels: size/XS

#20753 [ops] add Slack alert for GitpodImageBuilderMk3InternalErrors
  operations/observability/mixins/workspace/rules/central/image-builder.yaml
Labels: size/S

#20762 feat(dashboard): Update header layout and start page branding
  components/dashboard/src/menu/Menu.tsx
  components/dashboard/src/start/StartPage.tsx
Labels: size/L

#20763 [JetBrains] Upgrade IDEs to 2025.1
  .github/workflows/jetbrains-integration-test.yml
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/internal/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodClientProjectSessionTracker.kt
  components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
  components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
  components/ide/jetbrains/gateway-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/L

#20770 [server] Fix custom CA
  install/installer/pkg/common/certificate.go
  install/installer/pkg/components/server/deployment.go
  install/installer/pkg/components/ws-manager-bridge/deployment.go
Labels: size/S, team: team-experience, team: team-enterprise

#20740 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20766 [dashboard] try using skeletons for loading repo suggestions
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: component: dashboard, size/XL

#20774 [server] Allow org env vars in repos that don't have projects
  components/server/src/user/env-var-service.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20778 [JetBrains] Attach tasks with `exec` to properly handle terminal resize
  components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
Labels: size/XS, team: team-experience, team: team-enterprise

#20779 [dashboard] fix workspaces list rendering
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XL, team: team-experience, team: team-enterprise

#20764 Upgrade Leeway to 0.10.2
  .devcontainer/Dockerfile
  dev/image/Dockerfile
Labels: size/XS, team: team-experience, team: team-engine, team: team-enterprise

#20780 Upgrade Dev Env with Leeway 0.10.2
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-integration-test.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  components/supervisor/BUILD.yaml
  components/supervisor/leeway.Dockerfile
  components/supervisor/openssh/BUILD.yaml
Labels: size/M, team: team-experience, team: team-engine, team: team-enterprise
