Repository gitpod-io/gitpod, pull requests merged in 2025-06, with the labels that each got.

#20867 [server] Fix spicedb retry on DEADLINE_EXCEEDED & UNAVAILABLE
  components/server/src/authorization/spicedb-authorizer.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20854 [image-builder] Avoid returning "Unknown"
  .clinerules/learning-journal.md
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/ws-manager-mk2/main.go
  components/ws-manager-mk2/pkg/proxy/imagebuilder.go
  components/ws-manager-mk2/pkg/proxy/servicename-prefixer.go
  components/ws-manager-mk2/pkg/proxy/servicename-prefixer_test.go
Labels: size/XXL, team: team-engine, team: team-enterprise

#20843 [scrubber] Scrub URLs in log messages
  components/gitpod-protocol/src/util/scrubbing-config.ts
  components/gitpod-protocol/src/util/scrubbing.spec.ts
  components/gitpod-protocol/src/util/scrubbing.ts
  components/scrubber/config.go
  components/scrubber/sanitisation_test.go
  components/scrubber/scrubber_test.go
  components/server/src/workspace/workspace-starter.ts
  components/ws-manager-bridge/src/workspace-instance-controller.ts
Labels: size/L, team: team-experience, team: team-enterprise

#20868 [image-builder] Introduce retry for all resolver requests (timeout 15s, up to 3 times) for all network-related issues
  components/image-builder-api/generate.sh
  components/image-builder-api/go/imgbuilder.pb.go
  components/image-builder-api/go/imgbuilder_grpc.pb.go
  components/image-builder-api/go/mock/mock.go
  components/image-builder-api/go/subassembly.pb.go
  components/image-builder-api/go/subassembly_grpc.pb.go
  components/image-builder-api/imgbuilder.proto
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_grpc_pb.js
  components/image-builder-api/typescript/src/imgbuilder_pb.d.ts
  components/image-builder-api/typescript/src/imgbuilder_pb.js
  components/image-builder-api/typescript/src/subassembly_grpc_pb.d.ts
  components/image-builder-api/typescript/src/subassembly_grpc_pb.js
  components/image-builder-api/typescript/src/subassembly_pb.d.ts
  components/image-builder-api/typescript/src/subassembly_pb.js
  components/image-builder-mk3/pkg/orchestrator/orchestrator.go
  components/image-builder-mk3/pkg/orchestrator/orchestrator_test.go
  components/image-builder-mk3/pkg/resolve/resolve.go
  components/server/src/workspace/workspace-starter.ts
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20879 [registry-facade] Do retry if copying a blob fails mid way
  components/registry-facade/pkg/registry/blob.go
  components/registry-facade/pkg/registry/blob_test.go
  memory-bank/activeContext.md
  memory-bank/components/registry-facade.md
  memory-bank/progress.md
Labels: size/L, team: team-engine, team: team-enterprise

#20880 [registry-facade] Properly retry fetching mainfests/config as well
  components/registry-facade/pkg/registry/manifest.go
  components/registry-facade/pkg/registry/manifest_test.go
Labels: size/XL, team: team-engine, team: team-enterprise

#20869 [supervisor] Drop feature flag supervisor_terminal_no_deadline_exceeded
  components/supervisor/pkg/supervisor/supervisor.go
  components/supervisor/pkg/supervisor/tasks_test.go
  components/supervisor/pkg/terminal/service.go
  components/supervisor/pkg/terminal/terminal_test.go
Labels: size/M, team: team-experience, team: team-enterprise

#20882 Ona banner in Gitpod classic
  components/dashboard/src/Analytics.tsx
  components/dashboard/src/images/ona-wordmark.svg
  components/dashboard/src/workspaces/BlogBanners.tsx
Labels: size/L, team: team-experience, team: team-enterprise

#20892 Add Claude Code for Gitpod and Gitpod Classic
  .devcontainer/Dockerfile
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-integration-test.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  CLAUDE.md
  dev/image/Dockerfile
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#20896 Add Claude settings configuration
  .claude/settings.json
  .gitignore
Labels: size/S, team: team-enterprise

#20863 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20895 [cleanup] Remove MCP servers setup from .gitpod.yml
  .gitpod.yml
  scripts/install-git-mcp-go.sh
  scripts/install-linear-mcp-go.sh
Labels: size/L

#20906 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20920 [VS Code Browser] Build stable code `1.101.1`
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20924 [VS Code Browser] Update stable code to `1.101.1`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20926 [VS Code Browser] Build stable code `1.101.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20927 [VS Code Browser] Update stable code to `1.101.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise
