Repository gitpod-io/gitpod, pull requests merged in 2025-09, with the labels that each got.

#21034 Cute little message
  README.md
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/OnaRightPanel.tsx
  components/dashboard/src/start/OnaBanner.tsx
  components/dashboard/src/workspaces/BlogBanners.tsx
Labels: size/L, team: team-enterprise

#21039 Revert audit log args redaction to restore CloudWatch visibility
  components/server/src/audit/AuditLogService.ts
Labels: size/S, team: team-enterprise

#21041 Chore copy updates
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/Login.tsx
  components/dashboard/src/OnaRightPanel.tsx
  components/dashboard/src/start/OnaBanner.tsx
  components/dashboard/src/workspaces/BlogBanners.tsx
Labels: size/S, team: team-enterprise

#21045 Update README with sunset details and Ona introduction
  README.md
Labels: size/M

#21060 cleanup Gitpod PAYG login CTAs
  components/dashboard/src/Login.tsx
Labels: size/M, team: team-enterprise

#21064 [dashboard] robots-meta: noindex -> noindex, nofollow, noarchive, nosnippet, noimageindex
  components/dashboard/public/index.html
Labels: size/XS, team: team-enterprise
