Repository gitpod-io/gitpod, pull requests merged in 2025-03, with the labels that each got.

#20646 [server] OrganizationService:Fix unpin for pinnedEditorVersions (don't use deepmerge but overwrite if set)
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/orgs/organization-service.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20647 [dev] Install git and linear MCP servers
  .gitpod.yml
  scripts/install-git-mcp-go.sh
  scripts/install-linear-mcp-go.sh
Labels: size/L

#20649 [dashboard] Fix org-suggested repositories when settings org query is fetching
  components/dashboard/src/data/organizations/suggested-repositories-query.ts
Labels: size/XS

#20659 [dashboard] fix getting started card copy
  components/dashboard/src/workspaces/Workspaces.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20636 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20637 [spicedb] Fix intermittent "Error: 4 DEADLINE_EXCEEDED...Waiting for LB pick"
  components/content-service-api/typescript/package.json
  components/gitpod-protocol/package.json
  components/gitpod-protocol/src/util/grpc.ts
  components/ide-metrics-api/typescript-grpc/package.json
  components/image-builder-api/typescript/package.json
  components/image-builder-api/typescript/src/sugar.ts
  components/server/package.json
  components/server/src/authorization/spicedb-authorizer.ts
  components/server/src/authorization/spicedb.ts
  components/server/src/util/content-service-sugar.ts
  components/supervisor-api/typescript-grpc/package.json
  components/ws-daemon-api/typescript/package.json
  components/ws-manager-api/typescript/package.json
  components/ws-manager-bridge-api/typescript/package.json
  yarn.lock
Labels: meta: stale, size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20669 [server] Introduces ReadinessProbe
  components/content-service/content-service.code-workspace
  components/image-builder-mk3/image-builder.code-workspace
  components/server/src/container-module.ts
  components/server/src/liveness/probes.ts
  components/server/src/liveness/readiness-controller.ts
  components/server/src/server.ts
  components/ws-manager-mk2/ws-manager-mk2.code-workspace
  gitpod-ws.code-workspace
  install/installer/pkg/components/server/constants.go
  install/installer/pkg/components/server/deployment.go
  memory-bank/.clinerules
  memory-bank/activeContext.md
  memory-bank/progress.md
  memory-bank/systemPatterns.md
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20672 [server] Fix broken /ready endpoint and chaned the probe to be a StartupProbe
  components/server/src/liveness/probes.ts
  components/server/src/liveness/readiness-controller.ts
  components/server/src/server.ts
  install/installer/pkg/components/server/deployment.go
Labels: size/L, team: team-experience, team: team-enterprise

#20673 [server] Add /ready probe to smooth rollout of server pods
  components/server/src/container-module.ts
  components/server/src/liveness/probes.ts
  components/server/src/liveness/readiness-controller.ts
  components/server/src/liveness/startup-controller.ts
  components/server/src/server.ts
  install/installer/pkg/components/server/deployment.go
Labels: size/XL, team: team-experience, team: team-enterprise

#20661 [VS Code Browser] Build stable code `1.98.2`
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20677 [VS Code Browser] Update stable code to `1.98.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20666 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20679 Update development dependencies
  .devcontainer/Dockerfile
Labels: size/S

#20681 Update dev image
  dev/image/Dockerfile
Labels: size/S

#20685 Bump runc in ws-daemon
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS, team: team-engine, team: team-enterprise

#20684 Bump caddy to latest
  components/dashboard/leeway.Dockerfile
  components/ide-proxy/Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20686 Gentle protobufjs bump
  yarn.lock
Labels: size/S

#20680 Update runc to v1.2.6 and gcloud to v515.0.0
  components/ws-daemon/leeway.Dockerfile
Labels: size/XS, team: team-engine, team: team-enterprise

#20691 [server] Remove google-cloud-profiler
  components/server/package.json
  components/server/src/init.ts
  yarn.lock
Labels: size/XXL, team: team-experience, team: team-enterprise

#20683 Bump golang.org/x/crypto
  components/blobserve/go.mod
  components/blobserve/go.sum
  components/content-service/go.mod
  components/content-service/go.sum
  components/gitpod-cli/go.mod
  components/gitpod-cli/go.sum
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/local-app/go.mod
  components/local-app/go.sum
  components/proxy/Dockerfile
  components/proxy/plugins/analytics/go.mod
  components/proxy/plugins/analytics/go.sum
  components/proxy/plugins/configcat/go.mod
  components/proxy/plugins/configcat/go.sum
  components/proxy/plugins/corsorigin/go.mod
  components/proxy/plugins/corsorigin/go.sum
  components/proxy/plugins/frontend_dev/go.mod
  components/proxy/plugins/frontend_dev/go.sum
  components/proxy/plugins/headlesslogdownload/go.mod
  components/proxy/plugins/headlesslogdownload/go.sum
  components/proxy/plugins/jsonselect/go.mod
  components/proxy/plugins/jsonselect/go.sum
  components/proxy/plugins/logif/go.mod
  components/proxy/plugins/logif/go.sum
  components/proxy/plugins/secwebsocketkey/go.mod
  components/proxy/plugins/secwebsocketkey/go.sum
  components/proxy/plugins/sshtunnel/go.mod
  components/proxy/plugins/sshtunnel/go.sum
  components/proxy/plugins/workspacedownload/go.mod
  components/proxy/plugins/workspacedownload/go.sum
  components/public-api-server/go.mod
  components/public-api-server/go.sum
  components/registry-facade/go.mod
  components/registry-facade/go.sum
  components/supervisor/go.mod
  components/supervisor/go.sum
  components/ws-daemon/go.mod
  components/ws-daemon/go.sum
  dev/changelog/go.mod
  dev/changelog/go.sum
  dev/gp-gcloud/go.mod
  dev/gp-gcloud/go.sum
  dev/gpctl/go.mod
  dev/gpctl/go.sum
  dev/preview/previewctl/go.mod
  dev/preview/previewctl/go.sum
  dev/ssh-load-test/go.mod
  dev/ssh-load-test/go.sum
  install/installer/go.mod
  install/installer/go.sum
  test/go.mod
  test/go.sum
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20692 [server, bridge] Switch base-images to node:18.20.7-alpine to avoid CVEs
  components/server/leeway.Dockerfile
  components/ws-manager-bridge/leeway.Dockerfile
Labels: size/S, team: team-experience, team: team-enterprise

#20693 Revert "[image-builder-bob] bump up buildkit (#20690)"
  .github/workflows/build.yml
  components/image-builder-bob/leeway.Dockerfile
Labels: size/XS, team: team-engine, team: team-enterprise

#20689 Updating Go dependency: Docker and Git to fix CVE
  components/image-builder-bob/go.mod
  components/image-builder-bob/go.sum
  components/image-builder-mk3/go.mod
  components/image-builder-mk3/go.sum
  components/local-app/go.mod
  components/local-app/go.sum
Labels: size/M, team: team-experience, team: team-engine, team: team-enterprise

#20695 [db] Switch to node:18.20.7-alpine base image
  components/gitpod-db/leeway.Dockerfile
Labels: size/S, team: team-experience, team: team-enterprise

#20696 [installer] Bump kube-rbac-proxy to v0.19.0
  install/installer/pkg/common/constants.go
Labels: size/XS

#20697 [db] Bump cloud-sql-proxy to v1.37.6
  components/gitpod-db/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20703 [gha] Fix IDE integration tests
  .github/workflows/ide-integration-tests.yml
  components/ide/gha-update-image/lib/common.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20704 [gha] Correct installer tag finding for IDE integration tests
  .github/workflows/ide-integration-tests.yml
  components/ide/gha-update-image/lib/common.ts
Labels: size/XS, team: team-experience, team: team-enterprise

#20706 [docs] Remove empty line
  README.md
Labels: size/XS

#20712 [dev] Introduce script and CI step using trivy to scan and enforce 0 CRITICAL in images
  .github/workflows/build.yml
  scripts/trivy/scan-installer-config.yaml
  scripts/trivy/trivy-scan-images.sh
  scripts/trivy/trivyignore.yaml
Labels: size/XL

#20714 New Gitpod Classic notification
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/Login.tsx
Labels: size/S, team: team-experience, team: team-enterprise

#20719 [server, bridge] Bind metrics apps to "127.0.0.1" instead of "localhost"
  components/server/src/server.ts
  components/ws-manager-bridge/src/main.ts
Labels: size/XS, team: team-experience, team: team-enterprise
