Repository gitpod-io/gitpod, pull requests merged in 2025-05, with the labels that each got.

#20782 [server] Fix permission issue for collaborators in listenForPrebuildUpdates
  components/server/src/orgs/organization-service.spec.db.ts
  components/server/src/workspace/gitpod-server-impl.ts
Labels: size/M, team: team-experience, team: team-enterprise

#20786 Build VS Code Browser 1.99.3
  .github/workflows/code-build.yaml
  WORKSPACE.yaml
  components/ide/code/leeway.Dockerfile
Labels: size/XS, team: team-experience, team: team-enterprise

#20801 Create SBOMs and scan for vulnerablities
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-integration-test.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  WORKSPACE.yaml
  components/BUILD.yaml
Labels: size/L, team: team-experience, team: team-engine, team: team-enterprise

#20799 [VS Code Browser] Update stable code to `1.99.3`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20806 [gitpod-protocol] handle host:port:token for getGitpodImageAuth
  components/gitpod-protocol/src/protocol.spec.ts
  components/gitpod-protocol/src/protocol.ts
  components/image-builder-bob/pkg/proxy/auth.go
  components/image-builder-bob/pkg/proxy/auth_test.go
  components/image-builder-mk3/pkg/auth/auth.go
  components/image-builder-mk3/pkg/auth/auth_test.go
  components/supervisor/pkg/supervisor/docker.go
  components/supervisor/pkg/supervisor/docker_test.go
Labels: size/XL, team: team-experience, team: team-engine, team: team-enterprise

#20784 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20813 [server, dashboard, db] Org-wide "maintenance mode"
  components/dashboard/src/AppNotifications.tsx
  components/dashboard/src/app/AppRoutes.tsx
  components/dashboard/src/data/maintenance-mode/maintenance-mode-mutation.ts
  components/dashboard/src/data/maintenance-mode/maintenance-mode-query.ts
  components/dashboard/src/data/maintenance-mode/maintenance-notification-mutation.ts
  components/dashboard/src/data/maintenance-mode/maintenance-notification-query.ts
  components/dashboard/src/menu/OrganizationSelector.tsx
  components/dashboard/src/org-admin/AdminPage.tsx
  components/dashboard/src/org-admin/MaintenanceModeBanner.tsx
  components/dashboard/src/org-admin/MaintenanceModeCard.tsx
  components/dashboard/src/org-admin/MaintenanceNotificationBanner.tsx
  components/dashboard/src/org-admin/MaintenanceNotificationCard.tsx
  components/dashboard/src/org-admin/RunningWorkspacesCard.tsx
  components/dashboard/src/service/json-rpc-organization-client.ts
  components/dashboard/src/workspaces/CreateWorkspacePage.tsx
  components/gitpod-db/src/team-db.ts
  components/gitpod-db/src/typeorm/entity/db-team.ts
  components/gitpod-db/src/typeorm/migration/1715259000000-AddMaintenanceModeToTeam.ts
  components/gitpod-db/src/typeorm/migration/1715694000000-AddMaintenanceNotificationToTeam.ts
  components/gitpod-db/src/typeorm/team-db-impl.ts
  components/gitpod-protocol/src/gitpod-service.ts
  components/gitpod-protocol/src/teams-projects-protocol.ts
  components/public-api/gitpod/v1/organization.proto
  components/public-api/go/v1/organization.pb.go
  components/public-api/go/v1/organization_grpc.pb.go
  components/public-api/go/v1/v1connect/organization.connect.go
  components/public-api/go/v1/v1connect/organization.proxy.connect.go
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationOuterClass.java
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationServiceClient.kt
  components/public-api/java/src/main/java/io/gitpod/publicapi/v1/OrganizationServiceClientInterface.kt
  components/public-api/typescript/src/gitpod/v1/organization_connect.ts
  components/public-api/typescript/src/gitpod/v1/organization_pb.ts
  components/server/src/api/organization-service-api.ts
  components/server/src/authorization/definitions.ts
  components/server/src/orgs/organization-service.ts
  components/server/src/prometheus-metrics.ts
  components/server/src/workspace/gitpod-server-impl.ts
  components/server/src/workspace/workspace-service.ts
  components/server/src/workspace/workspace-starter.ts
  components/spicedb/schema/schema.yaml
Labels: size/XXL, team: team-experience, team: team-enterprise

#20817 Update images digests
  components/blobserve/leeway.Dockerfile
  components/content-service/leeway.Dockerfile
  components/dashboard/leeway.Dockerfile
  components/ee/agent-smith/leeway.Dockerfile
  components/ide-metrics/leeway.Dockerfile
  components/ide-proxy/Dockerfile
  components/ide-service/leeway.Dockerfile
  components/ide/jetbrains/backend-plugin/leeway.Dockerfile
  components/ide/jetbrains/image/leeway.Dockerfile
  components/ide/jetbrains/launcher/leeway.Dockerfile
  components/image-builder-mk3/leeway.Dockerfile
  components/leeway.Dockerfile
  components/local-app/leeway.Dockerfile
  components/node-labeler/leeway.Dockerfile
  components/openvsx-proxy/leeway.Dockerfile
  components/proxy/Dockerfile
  components/public-api-server/leeway.Dockerfile
  components/registry-facade/leeway.Dockerfile
  components/service-waiter/leeway.Dockerfile
  components/usage/leeway.Dockerfile
  components/ws-daemon/leeway.Dockerfile
  components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
  components/ws-manager-mk2/leeway.Dockerfile
  components/ws-proxy/leeway.Dockerfile
  dev/changelog/leeway.Dockerfile
  install/installer/leeway.Dockerfile
  install/installer/pkg/components/redis/constants.go
  test/leeway.Dockerfile
Labels: size/M, release-note-none, automated pr, kind/cleanup, team: team-experience, team: team-engine, team: team-enterprise

#20823 Update privacy policy date to May 16th, 2025
  components/dashboard/src/AppNotifications.tsx
Labels: size/XS, team: team-experience, team: team-enterprise

#20755 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE

#20833 [dev/preview] bump GCP AMI
  dev/preview/infrastructure/modules/gce/variables.tf
  dev/preview/infrastructure/variables.tf
Labels: size/XS, team: team-enterprise

#20835 [memory bank] Some optimizations to improve effectiveness
  .clinerules/memory-bank.md
  memory-bank/activeContext.md
  memory-bank/components.md
  memory-bank/components/content-service-api.md
  memory-bank/components/gitpod-db.md
  memory-bank/components/gitpod-protocol.md
  memory-bank/components/ide-metrics-api.md
  memory-bank/components/ide-service-api.md
  memory-bank/components/image-builder-api.md
  memory-bank/components/local-app-api.md
  memory-bank/components/public-api-server.md
  memory-bank/components/public-api.md
  memory-bank/components/registry-facade-api.md
  memory-bank/components/server.md
  memory-bank/components/spicedb.md
  memory-bank/components/supervisor-api.md
  memory-bank/components/usage-api.md
  memory-bank/components/ws-daemon-api.md
  memory-bank/components/ws-manager-api.md
  memory-bank/components/ws-manager-bridge-api.md
  memory-bank/productContext.md
  memory-bank/progress.md
  memory-bank/projectbrief.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: size/XXL

#20828 [supervisor] add new .gitpod.yml on-port option `ignore-completely`
  components/gitpod-protocol/data/gitpod-schema.json
  components/gitpod-protocol/go/gitpod-config-types.go
  components/gitpod-protocol/src/protocol.ts
  components/supervisor-api/go/status.pb.go
  components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/Status.java
  components/supervisor-api/status.proto
  components/supervisor/pkg/ports/ports.go
Labels: size/S, team: team-experience, team: team-enterprise

#20840 [VS Code Browser] Build stable code `1.100.2`
  WORKSPACE.yaml
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience

#20848 [VS Code Browser] Update stable code to `1.100.2`
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/S, team: IDE, team: team-experience, team: team-enterprise

#20852 [dev] Bump node 18.x to 22.15.1
  .devcontainer/Dockerfile
  .github/actions/delete-preview/Dockerfile
  .github/actions/deploy-gitpod/Dockerfile
  .github/actions/deploy-monitoring-satellite/Dockerfile
  .github/actions/preview-create/Dockerfile
  .github/workflows/build.yml
  .github/workflows/code-nightly.yml
  .github/workflows/ide-integration-tests.yml
  .github/workflows/jetbrains-auto-update-template.yml
  .github/workflows/jetbrains-integration-test.yml
  .github/workflows/preview-env-check-regressions.yml
  .github/workflows/preview-env-gc.yml
  .github/workflows/workspace-integration-tests.yml
  .gitpod.yml
  components/gitpod-db/leeway.Dockerfile
  components/ide/code/gitpod-web-extension/leeway.Dockerfile
  components/server/leeway.Dockerfile
  components/ws-manager-bridge/leeway.Dockerfile
Labels: size/M, team: team-experience, team: team-engine, team: team-enterprise

#20855 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise

#20675 [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)
  components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Labels: size/XS, team: IDE, editor: jetbrains, team: team-experience

#20769 [JetBrains] Update IDE images to new build version
  WORKSPACE.yaml
  components/ide/jetbrains/backend-plugin/gradle-stable.properties
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: size/M, team: IDE, editor: jetbrains, team: team-experience, team: team-enterprise

#20853 Redact args in the logs of audit log service
  components/server/src/audit/AuditLogService.ts
Labels: size/S, team: team-experience, team: team-enterprise

#20861 [code] update code image layers
  install/installer/pkg/components/ide-service/ide-configmap.json
Labels: editor: code (browser), size/XS, team: IDE, team: team-experience, team: team-enterprise
